### ISSUE TITLE
Running Android in debug mode. Game crashes.

### ISSUE THREAD

**Issue by smks** [openfl/openfl#1007]
E/AudioTrack(  780): AudioTrack::set : Exit
E/ACDB-LOADER(  243): Error: ACDB AudProc vol returned = -19
E/ACDB-LOADER(  243): Error: ACDB AFE returned = -19
I/trace   (30804): Lib.hx:360: Null Object Reference
I/trace   (30804): Called from *._Function_1_1 (ApplicationMain.hx line 98)
I/trace   (30804): Called from Reflect.callMethod (C:\HaxeToolkit\haxe\std/cpp/_std/Reflect.hx line 50)
I/trace   (30804): Called from Main.main (Main.hx line 68)
I/trace   (30804): Called from openfl._legacy.display.DisplayObjectContainer.addChild (openfl/_legacy/display/DisplayObjectContainer.hx line 31)
I/trace   (30804): Called from openfl._legacy.display.DisplayObject.__setParent (openfl/_legacy/display/DisplayObject.hx line 423)
I/trace   (30804): Called from openfl._legacy.display.DisplayObjectContainer.__onAdded (openfl/_legacy/display/DisplayObjectContainer.hx line 379)
I/trace   (30804): Called from openfl._legacy.display.DisplayObject.__onAdded (openfl/_legacy/display/DisplayObject.hx line 362)
I/trace   (30804): Called from openfl._legacy.display.DisplayObject.dispatchEvent (openfl/_legacy/display/DisplayObject.hx line 70)
I/trace   (30804): Called from openfl._legacy.display.DisplayObject.__dispatchEvent (openfl/_legacy/display/DisplayObject.hx line 182)
I/trace   (30804): Called from openfl._legacy.events.EventDispatcher.dispatchEvent (openfl/_legacy/events/EventDispatcher
E/AppsCustomizePagedView( 2437): Create Res Apk Failed

**Comment by GimmickyApps** [comment]
@smks which API are you targeting, and which one is in use on your device/emulator?

**Comment by smks** [comment]
Hey, was targeting SDK 23 and dispatching to both a Samsung Galaxy Note and a Oneplus 1.

**Comment by ibilon** [comment]
The error was specified in the fourth line, `Null Object Reference`, coming from Main.hx line 68.

**Comment by JackLove7** [comment]
what's mean about **Creat Res Apk Failed**?how can i  deal with that?
