### ISSUE TITLE
tiles issue when >2 layers

### ISSUE THREAD

**Issue by fresh-flash** [openfl/openfl#1009]
Hi! 
I want to create tile to tile fill. Every row is `TilemapLayer`. Code:

``` haxe
private var _bds:Array<BitmapData> = new Array<BitmapData>();
private var _tiles:Sprite;
private var _tilemap:Tilemap;
private var _tileset:Tileset;
function setTiles(e:MouseEvent = null):Void {
    var _layer:TilemapLayer;
    if (_tilemap != null) {//remove all tiles
        for (l in _tilemap.numLayers ... 0) {
            _layer = _tilemap.getLayerAt(l);
            for (t in _layer.numTiles ... 0) {
                _layer.removeTileAt(t);
            }
            _tilemap.removeLayerAt(l);
        }
        _tiles.removeChild(_tilemap);
        _tilemap = null;
    }
    _tilemap = new Tilemap(stage.stageWidth, stage.stageHeight);
    _tiles.addChild(_tilemap);
    var _nextX:Float = 0;
    var _nextY:Float = 0;
    var _bd:BitmapData = null;
    var _tile:Tile;
    while (_nextY < stage.stageHeight) {
        _nextX = 0;
        _bd = _bds[Math.round(Math.random() * (_bds.length - 1))];
        _tileset = new Tileset(_bd);
        _tileset.addRect(_bd.rect);
        _layer = new TilemapLayer(_tileset);
        _tilemap.addLayer(_layer);
        while (_nextX < stage.stageWidth) {
            _tile = new Tile(_nextX, _nextY);
            _layer.addTile(_tile);
            _nextX += _bd.width;
        }
        _nextY += _bd.height;
        _nextX = 0;
    }
}
```

Texture filled by random tiles for every row. But after second layer used wrong coordinates.
![image](https://cloud.githubusercontent.com/assets/10502143/12292210/3807f7a6-b9f4-11e5-87d3-7ea42e41cfb8.png)
All is ok if I comment this check `if (tile.id != cacheTileID)` in openfl._internal.renderer.flash.FlashTilemap.hx, line 42
![image](https://cloud.githubusercontent.com/assets/10502143/12292503/2287ce0e-b9f6-11e5-933d-7ba973ab7d21.png)
Maybe my code wrong? Or problem in openfl?

**Comment by larsiusprime** [comment]
Which platform target are you using?

**Comment by fresh-flash** [comment]
flash, html5 has the same problem, which is solved by commenting similar 69 line 
`if (tile.id != cacheTileID) ` in `openfl._internal.renderer.canvas.CanvasTilemap.hx`. 
I have not tested other platforms.
