### ISSUE TITLE
TextField 2px offset

### ISSUE THREAD

**Issue by NekR** [openfl/openfl#1014]
What is the idea of constant 2px offset in TextField?

https://github.com/openfl/openfl/blob/master/openfl/_internal/text/TextEngine.hx#L587-L588

**Comment by MSGhero** [comment]
Flash textfields have a 2px gutter: http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/TextLineMetrics.html

**Comment by NekR** [comment]
@MSGhero right. Anyway, this seems weird to me, maybe because I am not a Flash developer.
