### ISSUE TITLE
OpenFL stopped processing touch events after device rotation

### ISSUE THREAD

**Issue by iskolbin** [openfl/openfl#1016]
osx elcapitan, lime 2.8.3, openfl 3.5.3

I encountered this problem while running html5 build of the game. If you tap somewhere in the canvas area and rotate device( not releasing your finger) to change screen orientation then openfl stops processing touch events. My workaround is altering **lime/_backend/html5/HTML5Window.hx** :
```diff
@@ -356,7 +356,7 @@ class HTML5Window {


        private function handleResize ():Void {
-               primaryTouch = null;
+
                var stretch = parent.fullscreen || (setWidth == 0 && setHeight == 0);

                if (element != null && (div == null || (div != null && stretch))) {
```

**Comment by iskolbin** [comment]
Pull request: https://github.com/openfl/lime/pull/673

**Comment by ibilon** [comment]
Closing since this is a lime issue.
