### ISSUE TITLE
SimpleButton not working

### ISSUE THREAD

**Issue by NekR** [openfl/openfl#1020]
Just updated OpenFL to 3.6 and `SimpleButton` not working, over and down states are not activating. Not sure which version of OpenFL I had before, but it worked. Also didn't tried standalone `SimpleButton`, but I suppose it should work anyway if it worked.

Tested on Android and Mac.

**Comment by tienery** [comment]
Version 3.4.x still has `SimpleButton`s working as expected. Also, see my post on the OpenFL forums: http://community.openfl.org/t/simplebuttons-logic-seems-to-fail-in-3-5-3/7232

**Comment by NekR** [comment]
@tienery yeah, I have exact same problem. Thanks for the info!

So I should use version for now.. sad thing.

**Comment by sjian** [comment]
We had issues with SimpleButton in 3.5.3 and found that the hit mask was acting oddly. The workaround for us was to create an explicit sprite for the hitbox using graphics.drawRect. My theory is that there's something wrong with doing hit tests against bitmaps, but haven't had time to verify that yet.

**Comment by NekR** [comment]
@sjian all my states for SimpleButton are like this:

```
overState.graphics.beginFill(0xEEEEEE, 1);
overState.graphics.drawRect(0, 0, this.width, this.height);
overState.graphics.endFill();
```

So I am not sure that it's bitmap related problem.

Okay, so this works for me:
```
new SimpleButton(defaultState, overState, downState, defaultState);
```

**Comment by sjian** [comment]
Cool. As a side note, reusing a DisplayObject for two different states didn't work well for us on HTML5. So we generate two separate instances.

**Comment by NekR** [comment]
Okay, I will keep that in mind. Thanks :-)
