### ISSUE TITLE
BitmapDataChannel compiler errors on Flash when doc-gen is defined

### ISSUE THREAD

**Issue by Gama11** [openfl/openfl#1021]
```xml
<haxedef name="doc-gen" />
```

```haxe
package;

import openfl.display.BitmapData;
import openfl.display.BitmapDataChannel;
import openfl.display.Sprite;

class Main extends Sprite 
{
	public function new() 
	{
		super();
		new BitmapData(1, 1).copyChannel(
			null, null, null, BitmapDataChannel.ALPHA, 0);
	}
}
```

```
src/Main.hx:13: characters 21-44 : openfl.display.BitmapDataChannel should be UInt
src/Main.hx:13: characters 21-44 : For function argument 'sourceChannel'
```

It compiles when `to UInt` is added to the extern definition of `BitmapDataChannel`, but I'm not sure if that's a proper fix.

This causes issues when generating API docs, as `doc-gen` should be defined for that.
Haxe 3.2.0, OpenFL 3.6.0, Lime 2.9.0.

**Comment by jgranick** [comment]
https://github.com/openfl/openfl/blob/develop/extern/openfl/display/BitmapDataChannel.hx

Yeah, I think that is reasonable, or perhaps it could be an abstract over UInt to begin with, if the type in Flash Player is UInt anyway.

Feel free to commit this fix yourself if it resolves all the issues for you. Thank you! :wink:
