### ISSUE TITLE
[CPP&NEKO] Caret's color not changing with textColor.

### ISSUE THREAD

**Issue by eminfedar** [openfl/openfl#1026]
Caret's color is always black. It must be changeable.

**Comment by ibilon** [comment]
Doesn't look like the flash api (and player) allows that,
and by extension openfl won't.

**Comment by eminfedar** [comment]
if export type is flash, caret's color changing well but on neko & cpp not changing, always black.

**Comment by NekR** [comment]
@eminfedar yes, caret color is simply hardcoded in file. Am there actually is an PR which fixes that, but no one wants to apply it (it also adds a way to specify color of the caret).

Anyway, I do not see why OpenFL 100% follows Flash with all their legacy problems. At least, additional features what do not exists in flash and could exist in OpenFL is perfectly fine. I am pretty sure everyone developer wants better experience here, not just compatibility with Flash. Plus, remember that not everyone user of OpenFL had worked with Flash and it's confusing for them that adding simple features is so much problem.

**Comment by Gama11** [comment]
@NekR Is #480 the PR you mean?

**Comment by eminfedar** [comment]
@Gama11 oh #480 is what I exactly search for :) why #480 was not added to the openfl library?

**Comment by NekR** [comment]
@Gama11 I am not exactly sure which one, I saw one some time ago when I was investigating `TextField` caret color problem. Anyway, if that PR wasn't as good as needed, then it's not a problem, I can make my own. My only doubt is that OpenFL do not often accept PRs.

**Comment by ubald** [comment]
I deleted the branch at one point, so that closed the PR, but I could submit it again, I'm still using my own branch with the modifications, it's just named differently now.  The branches might not be up to date, I only rebase once in a while when I work on my project that's using it.

OpenFL: https://github.com/ubald/openfl/tree/caret-and-highlight 
Lime: https://github.com/ubald/lime/tree/caret-and-highlight

**Comment by jgranick** [comment]
I know this is an older discussion, I do not want to make people feel frustrated with the feeling that they are being purposely ignored. I am trying to work through to clean up the "debt" of Github Issues we have. One at a time :smile:

First from an OpenFL perspective, the goal here is to emulate the behavior of Flash's `TextField`. The caret is always black in Flash. We do not plan to expose a new property on `TextField` that allows the color to be changed. That said, I am now open to a hidden `__caretColor` property, which you could change if you override `TextField`. 

This could break in the future, but this would be better than patching each release of OpenFL. This is not the answer that probably want to hear, but what do you think?

**Comment by jgranick** [comment]
WAIT -- I was thinking of the highlight color. The above applies to my feelings about highlight color 😊 

`textFormat.textColor` is used for caret color. Resolved 🏆
