### ISSUE TITLE
[Cpp] TextField isn't getting UTF-8 characters until I click on it.

### ISSUE THREAD

**Issue by eminfedar** [openfl/openfl#1027]
openfl.text.TextField isn't getting Turkish characters until clicking on it. { ç,ö,ü,ı,İ,Ç,Ö,Ü ...}

I am focusing the textfield with Lib.current.stage.focus = textField;
Focusing is successful but it only receives english characters until I click on it and focus again with mouse.

**Comment by chpla** [comment]
in my case, it receives no characters at all under the following circumstances:
-i previously assigned the .text property something other than the current content of the text field
-I set the focus by assigning stage.focus = myTextField

**Comment by jgranick** [comment]
https://trello.com/c/xI2A76zD/14-improve-utf-8-text-support-in-openfl-text-textfield
