### ISSUE TITLE
Segmentation fault on Linux native target when loading embedded sound assets.

### ISSUE THREAD

**Issue by KirillPoletaev** [openfl/openfl#1031]
Steps to reproduce:

1 - Pull PiratePig sample.
2 - In PiratePigGame.hx load and play the theme this way:

```
        trace("load sound...");
        Assets.loadSound ("sounds/theme.ogg").onComplete(function(sound:Sound){
            trace("play sound");
            sound.play();
        });
```

3 - The project.xml needs to be updated:

```
    <assets path="Assets/sounds" rename="sounds" unless="web">
        <sound path="3.wav" id="sound3" />
        <sound path="4.wav" id="sound4" />
        <sound path="5.wav" id="sound5" />
    </assets>

    <assets path="Assets/sounds" rename="sounds" embed="false" type="music" />
```

At this point after compilation the game will work properly, the sound will be loaded and played as expected.

4 - Set embed to true:

```
<assets path="Assets/sounds" rename="sounds" embed="true" type="music" />
```

It crashes:

```
~/Documents/demo/PiratePig/Export/linux64/cpp/bin $ ./PiratePig
PiratePigGame.hx:161: load sound...
Segmentation fault
```

Compiled and tested on Linux Mint, with the latest haxelib builds of OpenFL and Lime.

**Comment by ibilon** [comment]
Can't reproduce, if the problem is still there with latest version of lime and openfl please reopen.
