### ISSUE TITLE
Type not found: 'V' on Mac and iOS Targets

### ISSUE THREAD

**Issue by 0xFireball** [openfl/openfl#1033]
export XCODE_APP_SUPPORT_DIR=/Applications/Xcode.app/Contents/Developer/Library/Xcode
    export XCODE_PRODUCT_BUILD_VERSION=7B91b
    export XCODE_VERSION_ACTUAL=0710
    export XCODE_VERSION_MAJOR=0700
    export XCODE_VERSION_MINOR=0710
    export ZERO_LINK=NO
    export arch=arm64
    export diagnostic_message_length=80
    export variant=normal
    /Applications/Xcode.app/Contents/Developer/usr/bin/make
Haxe device build: Release-iphoneos-v7
haxe Build.hxml -D HXCPP_ARMV7 -cpp build/Release-iphoneos-v7 
/usr/lib/haxe/std/Map.hx:136: lines 136-138 : Type not found : V
make: *** [build-haxe-armv7] Error 1

** BUILD FAILED **

The following build commands failed:
	ExternalBuildToolExecution Build\ Haxe
(1 failure)

**Comment by ibilon** [comment]
What version of haxe do you have?
If not the latest (3.2.1) does upgrading help?

Does the error also occurs on other targets?

**Comment by 0xFireball** [comment]
The problem has been solved by the most recent OpenFL update.
