### ISSUE TITLE
OpenFL iOS Build/Test errors:

### ISSUE THREAD

**Issue by 0xFireball** [openfl/openfl#1034]
Build Failed:

The following build commands failed:
Ld build/Release-iphoneos/TestApp.app/TestApp normal arm64

I have no idea what to do.

If it helps, I have iPhone 5, iPhone 6, iPad 4, and iPad Pro, and 2 Macs running OS X 10.10.5

**Comment by jgranick** [comment]
Builds are currently working fine, but if there are any more problems, please visit community.openfl.org and start a discussion there :smile:

**Comment by 0xFireball** [comment]
Yes, I noticed that this was fixed with an update to OpenFL quite a while ago. Thanks!
