### ISSUE TITLE
Neko + Next: Graphics#lineTo() with Infinity crashes

### ISSUE THREAD

**Issue by Gama11** [openfl/openfl#1036]
```haxe
var sprite = new Sprite();
Lib.current.addChild(sprite);
sprite.graphics.lineStyle(1, 0, 1);
sprite.graphics.moveTo(0, 0);
sprite.graphics.lineTo(Math.POSITIVE_INFINITY, 0);
```

Of course you wouldn't just pass Infinity in there on purpose, but this can easily happen unnoticed if dividing by 0. `lineTo()` should just fail gracefully in that case, like it does on all other targets I've tested (Legacy, Flash, HTML5, Cpp + Next).

Tested with OpenFL 3.6.0, Lime 2.9.0 and Haxe 3.2.1.

**Comment by ibilon** [comment]
I've got a crash on cpp+next (linux).
And no crash with `--window-hardware=false` (neko/cpp next).

Also on flash, if you moveTo(60,60) before, you'll see a line going to the left, and also to the left for the negative infinity.
If infinite on y then a line to the top, and a dot if infinite on both.

**Comment by ibilon** [comment]
Here's the backtrace http://pastebin.com/w4KYMC1W, somehow `lime_cairo_set_operator (handle, CairoOperator.CLEAR);` segfault.

Diving into lime's gl/cairo renderer was a bit much for me, so I just guarded it against infinity,
and the flash behavior isn't documented on infinity, nor does it makes sense so I didn't reproduced it.
