### ISSUE TITLE
OpenFL install times out even with -notimeout

### ISSUE THREAD

**Issue by moue** [openfl/openfl#1038]
I'm trying to install OpenFL via terminal on OS X El Capitan. Regardless of whether I run ```haxelib install openfl``` or ```haxelib -notimeout install openfl``` I get the same error: 

```
Downloading openfl-3,6,0.zip...
Download complete : 0 bytes in 10s (0KB/s)
Http connection timeout. Try running haxelib -notimeout <command> to disable timeout
```
After taking a look at issue #153, I downloaded openfl-3,6,0.zip from [here](http://lib.haxe.org/p/openfl) and unzipped the file to the .current folder like issue #153 suggested: 
```
unzip ~/Downloads/haxe/openfl-3,6,0.zip -d /usr/local/lib/haxelib/openfl/.current
```
It unzipped without any errors, and I also copied the contents of .current into another folder 3,6,0 in my /usr/local/lib/haxelib/openfl directory
```
cp -a .current/ 3,6,0
``` 
But when I ran ```haxelib run openfl setup```, I got the following response:
```
[file_contents,/usr/local/lib/haxelib/openfl//.current]
```
I have no idea why this might be. The command ```haxelib path openfl``` gives me the following response:
```
[file_contents,/usr/local/lib/haxelib/openfl/.current]
```
In any case, running the ```openfl``` command gives me the error: 
```
zsh: command not found: openfl
```
What might I be doing wrong?

**Comment by ibilon** [comment]
`.current` should be a file.

Delete the openfl directory and do `haxelib install openfl-3,6,0.zip`.

**Comment by moue** [comment]
Thanks, doing that fixed my problem! I ended up following the [manual installation instructions](http://www.openfl.org/documentation/advanced-setup/manual-install/) to get everything set up.
