### ISSUE TITLE
Need to implement UncaughtErrorEvent

### ISSUE THREAD

**Issue by larsiusprime** [openfl/openfl#1039]
As far as I can tell, OpenFL/Lime does not throw an UncaughtErrorEvent in next the way legacy does. This leaves [crashdumper](https://www.github.com/larsiusprime/crashdumper) without a way to catch crashes in next.

I think I discussed this with @jgranick at some point, this is just serving as a reminder so that we get around to implementing it. I might take a stab at it eventually but if someone knows how to do it feel free to knock it out.

**Comment by jgranick** [comment]
Implemented :smile:

**Comment by Tiago-Ling** [comment]
Sorry for commenting on a closed issue, but is `UncaughtErrorEvent` working in 3.6.1 in native platforms? 

Tried listening to it but no luck...
