### ISSUE TITLE
R6025 C++ Runtime Error

### ISSUE THREAD

**Issue by eminfedar** [openfl/openfl#1047]
I have this error on testing : http://imgur.com/SEoj7tQ

Specs : 
* HaxeFlixel v3.3.12
* OpenFL v3.6.0
* Lime v2.9.0
* HXCPP 3.2.205

PC : 
* Windows 10
* R9 280

**Comment by larsiusprime** [comment]
We'll need some more context to narrow down this error. What are you trying to compile? Can you post some code that reproduces the error?

**Comment by eminfedar** [comment]
it was never happened again. But my code was not interesting. I used FlxSprite, FlxText, FlxBar etc. if it happens again, I will write here.
