### ISSUE TITLE
"Error after opening sound data" "Not Sound"

### ISSUE THREAD

**Issue by Jacic** [openfl/openfl#1051]
This was an issue I had before, and I thought was fixed, but it turns out it wasn't. The previous issue is [here](https://github.com/openfl/openfl/issues/521).

Basically, I have sounds in my game (for example, a sound that plays when a new menu item is selected). These sounds work, most of the time. Selecting different menu items on the main menu, for example, always works (at least, I have yet to see it fail). However, sometimes, seemingly randomly, if the sound attempts to play from, say a pause menu later, the game crashes. I think the crash is more likely if the sound hadn't been played by that point, but I'm not entirely sure, because sometimes it does work regardless of when/if it was played before.

Here are example stack traces:
Error after opening sound data
Not Sound
Called from openfl._legacy.display.Stage.__pollTimers (openfl/_legacy/display/Stage.hx line 1084)
Called from openfl._legacy.display.Stage.__checkRender (openfl/_legacy/display/Stage.hx line 351)
Called from openfl._legacy.display.Stage.__render (openfl/_legacy/display/Stage.hx line 1103)
Called from openfl._legacy.display.DisplayObjectContainer.__broadcast (openfl/_legacy/display/DisplayObjectContainer.hx line 260)
Called from openfl._legacy.display.DisplayObjectContainer.__broadcast (openfl/_legacy/display/DisplayObjectContainer.hx line 260)
Called from openfl._legacy.display.DisplayObjectContainer.__broadcast (openfl/_legacy/display/DisplayObjectContainer.hx line 286)
Called from openfl._legacy.display.DisplayObject.__broadcast (openfl/_legacy/display/DisplayObject.hx line 161)
Called from openfl._legacy.display.DisplayObject.__dispatchEvent (openfl/_legacy/display/DisplayObject.hx line 182)
Called from openfl._legacy.events.EventDispatcher.dispatchEvent (openfl/_legacy/events/EventDispatcher.hx line 98)
Called from com.haxepunk.Engine.onEnterFrame (com/haxepunk/Engine.hx line 304)
Called from com.haxepunk.Engine.update (com/haxepunk/Engine.hx line 129)
Called from PlayScene.update (PlayScene.hx line 278)
Called from com.haxepunk.Scene.update (com/haxepunk/Scene.hx line 86)
Called from Player.update (Player.hx line 112)
Called from Player.collideObjects (Player.hx line 424)
Called from Player.damage (Player.hx line 288)
Called from AudioHandler.play (AudioHandler.hx line 27)
Called from Audio.play (Audio.hx line 22)
Called from com.haxepunk.Sfx.new (com/haxepunk/Sfx.hx line 39)
Called from openfl._legacy.Assets.getSound (openfl/_legacy/Assets.hx line 484)
Called from DefaultAssetLibrary.getSound (DefaultAssetLibrary.hx line 562)
Called from Type.createInstance (/usr/lib/haxe/std/cpp/_std/Type.hx line 82)
Called from __ASSET__sfx_shot_wav.new (openfl/_legacy/Assets.hx line 2288)
Called from openfl._legacy.media.Sound.loadCompressedDataFromByteArray (openfl/_legacy/media/Sound.hx line 140)
Called from extern.cffi (/usr/lib/haxe/lib/hxcpp/3,2,171/src/hx/Lib.cpp line 147)
AL lib: (EE) alc_cleanup: 1 device not closed

---

Error after opening sound data
Not Sound
Called from openfl._legacy.display.Stage.__pollTimers (openfl/_legacy/display/Stage.hx line 1084)
Called from openfl._legacy.display.Stage.__checkRender (openfl/_legacy/display/Stage.hx line 351)
Called from openfl._legacy.display.Stage.__render (openfl/_legacy/display/Stage.hx line 1103)
Called from openfl._legacy.display.DisplayObjectContainer.__broadcast (openfl/_legacy/display/DisplayObjectContainer.hx line 260)
Called from openfl._legacy.display.DisplayObjectContainer.__broadcast (openfl/_legacy/display/DisplayObjectContainer.hx line 260)
Called from openfl._legacy.display.DisplayObjectContainer.__broadcast (openfl/_legacy/display/DisplayObjectContainer.hx line 286)
Called from openfl._legacy.display.DisplayObject.__broadcast (openfl/_legacy/display/DisplayObject.hx line 161)
Called from openfl._legacy.display.DisplayObject.__dispatchEvent (openfl/_legacy/display/DisplayObject.hx line 182)
Called from openfl._legacy.events.EventDispatcher.dispatchEvent (openfl/_legacy/events/EventDispatcher.hx line 98)
Called from com.haxepunk.Engine.onEnterFrame (com/haxepunk/Engine.hx line 304)
Called from com.haxepunk.Engine.update (com/haxepunk/Engine.hx line 129)
Called from PauseScene.update (PauseScene.hx line 544)
Called from AudioHandler.play (AudioHandler.hx line 27)
Called from Audio.play (Audio.hx line 22)
Called from com.haxepunk.Sfx.new (com/haxepunk/Sfx.hx line 39)
Called from openfl._legacy.Assets.getSound (openfl/_legacy/Assets.hx line 484)
Called from DefaultAssetLibrary.getSound (DefaultAssetLibrary.hx line 562)
Called from Type.createInstance (/usr/lib/haxe/std/cpp/_std/Type.hx line 82)
Called from __ASSET__sfx_hurtbyceilingorfloor_wav.new (openfl/_legacy/Assets.hx line 2288)
Called from openfl._legacy.media.Sound.loadCompressedDataFromByteArray (openfl/_legacy/media/Sound.hx line 141)
Called from extern.cffi (/usr/lib/haxe/lib/hxcpp/3,2,205/src/hx/Lib.cpp line 155)
AL lib: (EE) alc_cleanup: 1 device not closed

A while back I had reorganized my audio-handling code in an attempt to fix this, but it didn't help. The previously mentioned issue was closed, stating that a file handle leak was occurring, and had been fixed, but as I'm still experiencing crashes I believe the issue has not been fixed. Unfortunately, I'm not sure what is causing this.

**Comment by whilesoftware** [comment]
I'm seeing a similar crash. This crept up after upgrading to haxe flixel 4.2.0 (I was upgrading from something pre-4.0).

Crashdumper output:

Error after opening sound data
CrashDumper.hx:234: CRASH session.id = rsbs_2016-10-21_23'21'11
CrashDumper.hx:235: MESSAGE = SystemData
{
  OS : OS X 10.11.6 (15G1004) MacBook Pro MacBookPro10,1
  RAM: 8388608 KB (8 GB)
  CPU: Intel Core i7 2.3 GHz
  GPU: Intel HD Graphics 4000 1536 MB 2880 x 1800 Retina
, driver v. unknown
}
--------------------------------------
filename:	redshiftblueshift
package:	com.zeroone.redshiftblueshift
version:	0.0.1
sess. ID:	rsbs_2016-10-21_23'21'11
started:	2016-10-21 23:21:11
--------------------------------------
crashed:	2016-10-21 23:24:08
duration:	00:02:57
error:		Not Sound
stack:
extern.cffi (/usr/local/lib/haxe/lib/hxcpp/3,3,49/src/hx/Lib.cpp line 160)
openfl._legacy.media.Sound.loadCompressedDataFromByteArray (openfl/_legacy/media/Sound.hx line 141)
__ASSET__assets_sounds_cpp_hurt_ogg.new (openfl/_legacy/Assets.hx line 2288)
Type.createInstance (/usr/local/lib/haxe/std/cpp/_std/Type.hx line 83)
DefaultAssetLibrary.getSound (DefaultAssetLibrary.hx line 1066)
openfl._legacy.Assets.getSound (openfl/_legacy/Assets.hx line 484)
flixel.system.frontEnds.SoundFrontEnd.play (flixel/system/frontEnds/SoundFrontEnd.hx line 187)
SoundManager.p (SoundManager.hx line 49)
Missile.update (Missile.hx line 44)
flixel.group.FlxTypedGroup.update (flixel/group/FlxGroup.hx line 137)
flixel.group.FlxTypedGroup.update (flixel/group/FlxGroup.hx line 137)
PlayState.update (PlayState.hx line 303)
flixel.FlxState.tryUpdate (flixel/FlxState.hx line 171)
flixel.FlxGame.update (flixel/FlxGame.hx line 765)
flixel.FlxGame.step (flixel/FlxGame.hx line 689)
flixel.FlxGame.onEnterFrame (flixel/FlxGame.hx line 554)
openfl._legacy.events.EventDispatcher.dispatchEvent (openfl/_legacy/events/EventDispatcher.hx line 98)
openfl._legacy.display.DisplayObject.__dispatchEvent (openfl/_legacy/display/DisplayObject.hx line 182)
openfl._legacy.display.DisplayObject.__broadcast (openfl/_legacy/display/DisplayObject.hx line 161)
openfl._legacy.display.DisplayObjectContainer.__broadcast (openfl/_legacy/display/DisplayObjectContainer.hx line 286)
openfl._legacy.display.Stage.__render (openfl/_legacy/display/Stage.hx line 1103)
openfl._legacy.display.Stage.__checkRender (openfl/_legacy/display/Stage.hx line 351)
openfl._legacy.display.Stage.__pollTimers (openfl/_legacy/display/Stage.hx line 1084)
