### ISSUE TITLE
Window.fullscreen detection bug

### ISSUE THREAD

**Issue by SARFEX** [openfl/openfl#1055]
**1.** set fullscreen mode on (alt + enter) _// stage.window.fullscreen = true;_
**2.** change focus from app (alt + tab)
**3.** go back to app again (alt + tab) _// stage.window.fullscreen = false;_

Target: cpp next

Lime 2.9.0
Openfl 3.6.0
Haxe 3.2.1

**Comment by jgranick** [comment]
This issue was moved to openfl/lime#873
