### ISSUE TITLE
[Android] rendering  with Tilesheet.TILE_TRANS_2x2

### ISSUE THREAD

**Issue by Yanrishatum** [openfl/openfl#1056]
Rendering of scaled Tilesheet via `TILE_TRANS_2x2` with atlases (tested with 2k atlas) results in rendering of parts that are around target rectangle. Made a simple project to test it:
https://dl.dropboxusercontent.com/u/34170815/Projects/_temp/MobileScaleTest.zip
You'll see as white rectangle becomes bigger via scale, there will be red and green borders, which are placed around white pixel on atlas image.

UPD: `Graphics.drawTriangles` has this issue too.

**Comment by larsiusprime** [comment]
Does this error occur on other targets or just Android?

**Comment by Yanrishatum** [comment]
Does not appears on neko/windows targets. Can't test it on iOS. (and this appeared not only on my device)

**Comment by grayhaze** [comment]
Are you able to provide screenshots of the problem? I also tried another two devices with different resolutions and still can't replicate the problem. I've now tried devices with resolutions of 480x800, 800x1280, 1080x1920 and 1440x2560, and Android versions ranging from Lollipop to Marshmallow.

**Comment by Yanrishatum** [comment]
Have a bunch of them. It supposed to render perfectly white rectangle, but I get adjacent pixels on atlas at corners.
And second device that definitely affected is:
Prestigio Multiphone PAP3350 duo
Android 4.2.2
320х480

![device-2016-03-11-093527](https://cloud.githubusercontent.com/assets/1061373/13695111/8d43ee78-e76c-11e5-82a3-90b0b036b8f4.png)
![device-2016-03-11-093543](https://cloud.githubusercontent.com/assets/1061373/13695109/8d42f2ac-e76c-11e5-83d2-413a5ea80470.png)
![device-2016-03-11-093559](https://cloud.githubusercontent.com/assets/1061373/13695107/8d4243a2-e76c-11e5-9522-a6a662283bb8.png)
![device-2016-03-11-093622](https://cloud.githubusercontent.com/assets/1061373/13695110/8d437a9c-e76c-11e5-9b45-87f8991d5e4d.png)
![device-2016-03-11-093426](https://cloud.githubusercontent.com/assets/1061373/13695108/8d42db78-e76c-11e5-99f6-d49f642a59d0.png)
![device-2016-03-11-093447](https://cloud.githubusercontent.com/assets/1061373/13695112/8d44ab9c-e76c-11e5-9164-94916905cc32.png)
![device-2016-03-11-093511](https://cloud.githubusercontent.com/assets/1061373/13695113/8d5b8998-e76c-11e5-9f60-420ab242f54f.png)
