### ISSUE TITLE
[Flash] Variable flash.display3D::Context3DBufferUsage is not defined

### ISSUE THREAD

**Issue by phil-allcock** [openfl/openfl#1059]
Compiling for flash is fine, but at runtime I get the error:

> Variable flash.display3D::Context3DBufferUsage is not defined

when calling:
`Context3DBufferUsage.DYNAMIC_DRAW`

**Comment by jgranick** [comment]
This is caused (I believe!) by running on an older Flash Player version. However, I believe we inline our enum use now, so even this would work on old versions of the player. Thanks :smile:
