### ISSUE TITLE
Some methods are only available when targeting flash

### ISSUE THREAD

**Issue by buckle2000** [openfl/openfl#1060]
e.g.
`textField` is a instance of `flash.text.TextField`
textField.getCharBoundaries(0); //ERROR: flash.text.TextField has no field getCharBoundaries

**Comment by Gama11** [comment]
I think it's not implemented in OpenFL Legacy, but should be available in Next.

**Comment by ibilon** [comment]
The function is available in next and we don't develop new feature on legacy anymore (still accept pull requests on it).

Don't hesitate to open new issues if you have trouble with next.
