### ISSUE TITLE
BitmapData copyPixels/draw/scroll bug for OSX neko/cpp targets

### ISSUE THREAD

**Issue by kuremu** [openfl/openfl#1061]
There seems to be a bug when calling a BitmapData's copyPixels if you pass the same BitmapData as the first argument (ie. sourceBitmapData). Instead of being copied once, the image is repeated infinitely in the direction of the destPoint. Cloning the BitmapData for the copyPixels call gives the expected output. This issue also seems to affect BitmapData's draw() and scroll() functions.

This issue is present in OSX neko and CPP targets, but Flash and HTML5 targets seem to be fine. I'm using OSX 10.10.5, OpenFL 3.6.0, Lime 2.9.0

```haxe
var image = Assets.getBitmapData ("assets/openfl.png");
    
// this results in the image repeating in the "direction" defined by the copyPixel destPoint argument
// the scroll() and draw() functions also appear to be affected
var bd:BitmapData = new BitmapData(100, 400);
bd.copyPixels(image, image.rect, new Point());
var bitmap = new Bitmap(bd);
addChild(bitmap);
bd.copyPixels(bd, bd.rect, new Point(0, 100));
//bd.scroll(0, 100);
//bd.draw(bd, new Matrix(1, 0, 0, 1, 0, 100));
    
// cloning bd in the copyPixels call provides correct result
var bd:BitmapData = new BitmapData(100, 400);
bd.copyPixels(image, image.rect, new Point());
var bitmap = new Bitmap(bd);
addChild(bitmap);
bitmap.x = 100;
bd.copyPixels(bd.clone(), bd.rect, new Point(0, 100));
//bd.draw(bd.clone(), new Matrix(1, 0, 0, 1, 0, 100));
```

<img width="207" alt="screen shot 2016-03-13 at 11 26 40 pm" src="https://cloud.githubusercontent.com/assets/937418/13728642/144f03d2-e973-11e5-914b-fc82d797f262.png">

**Comment by azrafe7** [comment]
Since source and dest buffers are the same in this case, they overwrite each other (doesn't happen with flash/js because it seems that the buffer is always a copy):

![test_copypx](https://cloud.githubusercontent.com/assets/1266447/15020336/e7f1eef8-1221-11e6-9e36-3ff39c105073.gif)

**Comment by ibilon** [comment]
@azrafe7 do you think we should force a copy too?

**Comment by azrafe7** [comment]
@ibilon, thinking about it, there are some options here:

 1. always make a copy when source and dest are the same
 - make a copy only when source and dest are the same and their rects overlap (but dest is not fully contained in source)
 - rearrange the order in which pixels are copied, when necessary (i.e. copy from bottom instead of top - or from right instead of left -)
 - state in the docs that the buffer is not a clone, and let the user deal with it

1 is the easy one
2 is a bit tricky but should work.
3 would probably perform better, but the code would be less readable
4 is a possibility too

**Comment by MSGhero** [comment]
Yeah, `copyPx` in as3 makes a copy if the source and destination bmds are the same. `alphaBitmapData` also forces a copy if needed, but I don't think anyone has ever used that parameter before.

**Comment by larsiusprime** [comment]
Unless we want more weird edge case bugs, I think it's probably best to follow as3/flash's behavior here and copy if source/dest match.

**Comment by ibilon** [comment]
Fixing the issue 2 minutes, fixing the tests code 2 hours,
but worth it.

scroll is still bugged but that's a lime issue.
