### ISSUE TITLE
Stage.__pollTimers Error [Null Object Reference]

### ISSUE THREAD

**Issue by eminfedar** [openfl/openfl#1067]
I'm making a MMORPG, using threads, udp sockets, etc...

And I control almost every variable if null. But I get this error 'Randomly'. I can't solved yet. I just reading socket messages, kill and revive monsters, change flxtexts...

This is  uncaughtError listener trace :

```
Main.hx:30: [UncaughtErrorEvent type=null bubbles=null cancelable=null error="Null Object Reference"] 
Main.hx:31: Error:Null Object Reference 
Main.hx:32: ErrorID:0
Main.hx:33: TEXT:
Main.hx:34: eStr:#function0
Main.hx:35: eType:uncaughtError
Main.hx:36: eTarget:[object UncaughtErrorEvents]
Main.hx:37: eCurTarget:[object UncaughtErrorEvents]
```

This is error : 

```
Null Object Reference
Called from openfl._legacy.display.Stage.__pollTimers (openfl/_legacy/display/Stage.hx line 1084)
Called from openfl._legacy.display.Stage.__checkRender (openfl/_legacy/display/Stage.hx line 351)
Called from openfl._legacy.display.Stage.__render (openfl/_legacy/display/Stage.hx line 1103)
Called from openfl._legacy.display.DisplayObjectContainer.__broadcast (openfl/_legacy/display/DisplayObjectContainer.hx line 286)
Called from openfl._legacy.display.DisplayObject.__broadcast (openfl/_legacy/display/DisplayObject.hx line 161)
Called from openfl._legacy.display.DisplayObject.__dispatchEvent (openfl/_legacy/display/DisplayObject.hx line 182)
Called from openfl._legacy.events.EventDispatcher.dispatchEvent (openfl/_legacy/events/EventDispatcher.hx line 98)
Called from flixel.FlxGame.onEnterFrame (flixel/FlxGame.hx line 541)
Called from flixel.FlxGame.draw (flixel/FlxGame.hx line 860)
Called from flixel.FlxState.draw (flixel/FlxState.hx line 60)
Called from flixel.group.FlxTypedGroup.draw (flixel/group/FlxGroup.hx line 157)
Called from flixel.group.FlxTypedGroup.draw (flixel/group/FlxGroup.hx line 157)
Called from flixel.group.FlxTypedGroup.draw (flixel/group/FlxGroup.hx line 157)
Called from flixel.FlxSprite.draw (flixel/FlxSprite.hx line 622)
Called from flixel.FlxSprite.drawComplex (flixel/FlxSprite.hx line 664)
Called from flixel.FlxCamera.drawPixels (flixel/FlxCamera.hx line 546)
Called from flixel.graphics.tile.FlxDrawTilesItem.addQuad (flixel/graphics/tile/FlxDrawTilesItem.hx line 42)
```

**Comment by MSGhero** [comment]
If you look at the call stack, the error is occurring inside `FlxDrawTilesItem.addQuad`, so I would look there. This is the same as error 1009 in flash "Cannot access a property or method of a null object reference," so you're probably passing `null` into the frame or matrix parameter of that function. If you can test on flash, you can debug this 100x better.

Not an openfl issue, probably.

**Comment by eminfedar** [comment]
Can't I debug with CPP and see the null object which gives error? I find hxcpp but I can't managed to use it. Actullay I played the game about 7-8 minutes. Everything is same, I just killing same mobs again and again, but it gives this error after 7-8 minutes without a reason.

Maybe the openfl or lime has errors?

**Comment by MSGhero** [comment]
Only your flixel code is causing the errors, and the error it's causing seems to be that you are giving it null parameters. You have to give more details about your code, it is impossible for us to solve a null object reference without knowing where it happened.

**Comment by ibilon** [comment]
The stacktrace doesn't indicate an openfl issue.
