### ISSUE TITLE
Null Object Reference when using SharedObject.getLocal

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [openfl/openfl#1070]
In my code I am doing:

```
so = openfl.net.SharedObject.getLocal("game_options");
```

And I am getting:

```
Called from openfl.net.SharedObject::getLocal openfl/net/SharedObject.hx line 166
Error : Null Object Reference
```

when I remove this [line](https://github.com/openfl/openfl/blob/develop/openfl/net/SharedObject.hx#L166) the error disapears, but I am not sure which damage I am doing.

**Comment by ibilon** [comment]
That shouldn't be null, what target was this? Did you try on other targets?

**Comment by RudolfVonKrugstein** [comment]
The targe is linux 64 bit. I am trying to compile my game without the "-Dv2" option. With "-Dv2" everything is fine.

**Comment by jgranick** [comment]
This should be fixed in newer versions :smile:
