### ISSUE TITLE
OpenFL next can only draw very simple movieclips on native targets.

### ISSUE THREAD

**Issue by mikkelmr** [openfl/openfl#1073]
I am only able to see simple rectangular graphics loaded from a swf using Next. More complex shapes are not drawn. See screenshot below

![image](https://cloud.githubusercontent.com/assets/16362939/14109601/12eb7e38-f5c3-11e5-8a9a-0fb5880c0456.png)

It works fine on HTML5 target, but the issue occurs at least on Windows & IOS.

However switching to either legacy or forcing software rendering like this:

```
<set name="openfl-legacy" />
or 
<window hardware="false" />
```

Makes the shapes appear correctly as shown below

![image](https://cloud.githubusercontent.com/assets/16362939/14109532/c3c1bee4-f5c2-11e5-9132-5f29757bfb65.png)

The attached project(Shapes.zip) can be used to reproduce the error.
[Shapes.zip](https://github.com/openfl/openfl/files/193542/Shapes.zip)

**Comment by jgranick** [comment]
Tested using the latest :smile:

![image](https://cloud.githubusercontent.com/assets/833997/21660037/7cb5ccd2-d282-11e6-8bf2-f2f672baa0ba.png)
