### ISSUE TITLE
Review pull requests and issues for TextField and compile an action plan

### ISSUE THREAD

**Issue by jgranick** [openfl/openfl#1085]
There are pending pull requests and issue reports related to TextField, once we have tests to confirm our current functionality, we need to triage the contributions and the reports we have received to formulate what we need to work on to make the TextField implementation even greater than it is :smile:

**Comment by tienery** [comment]
So `setTextFormat` will eventually officially be implemented? :)

**Comment by larsiusprime** [comment]
@tienery I assume you're talking about text *ranges* ? I believe setting the text format for the entire text field should work (but ranges don't, at least not last time I checked).

**Comment by tienery** [comment]
I meant that I made a pull request, because that's based on the subject matter: https://github.com/openfl/openfl/pull/1066

**Comment by larsiusprime** [comment]
oh excellent! Yeah we need to get a test suite together because I think the will is definitely here to get this stuff improved, we just need to be able to validate we're not causing regressions

**Comment by ibilon** [comment]
Alright so I went through all issues and pr and assigned all textfield related ones to the appropriate milestone.

Completely agree with @larsiusprime, without anti-regression tests it'd be hard to really improve.
Also we'll need something to compare to, flash?

Do you think comparison of the rendered text (similar to what @ashes999 did for svg https://github.com/openfl/svg/pull/26) would work?

**Comment by larsiusprime** [comment]
We have a facility in the renderer to take a screenvuffer start, perhaps we could do bmp diffs within a tolerance to account for noise, etc? or test with bitmap fonts for exact match?

and yes flash sounds like a good ground truth or at least a starting anchor point

**Comment by ibilon** [comment]
Made a some code for functional testing, see https://github.com/openfl/openfl/commit/3d70076bfcf87fcd157f29415f77f48a2579a629

currently the first test run is ok, but the following don't render, most likely something not cleaned up between the tests.

It's only for neko/cpp but it's a starting point.

**Comment by ibilon** [comment]
"Fixed" this issue, now each test is run in its own process,
so no more interference between tests.

As a side effect you can now also do `neko tests.n -k classname testname` to launch an openfl app running the test code.

So all that's left now is to do more test and start looking at the issues/pull requests :)

**Comment by ashes999** [comment]
+1
