### ISSUE TITLE
Implement BitmapData.perlinNoise

### ISSUE THREAD

**Issue by xerosugar** [openfl/openfl#1087]
Was trying to port a threshold-effect snippet I found online to HaxeFlixel that involved using perlinNoise, but...

"Lib.hx:113: Warning: BitmapData.perlinNoise is not implemented"

;-;

**Comment by MSGhero** [comment]
#913 Basically we're not sure how flash's works and if we should use simplex noise instead.

**Comment by ibilon** [comment]
Duplicate, closing.
