### ISSUE TITLE
BitmapData.threshold for Canvas and DOM

### ISSUE THREAD

**Issue by MiltonW** [openfl/openfl#1088]
Threshold works fine for most targets, but when using html5 (canvas and dom) I hit a snag: 

When I alter the 'DisplayingABitmap' example to:
```
var bmd = Assets.getBitmapData ("assets/openfl.png");
bmd.threshold(bmd, bmd.rect, new Point(0, 0), "==", 0xFF7C76DD, 0xFF8A3E34, 0xFFFFFFFF, true);
var bitmap = new Bitmap (bmd);
addChild (bitmap);
```
no bitmap is shown when trying canvas/dom

Canvas gives me no error.
Dom gives:

> Uncaught TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(HTMLImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap)'

When I use -Dwebgl it works fine....

**Comment by azrafe7** [comment]
Changing [these lines](https://github.com/openfl/lime/blob/13a7ec51c2119e80c3bd07ec89c6842568d004d9/lime/graphics/Image.hx#L973-L975) in Image.threshold() seems to work for me.

```haxe
    #if (js && html5)
    ImageCanvasUtil.convertToCanvas (this);
    ImageCanvasUtil.sync (this, false);
    ImageCanvasUtil.createImageData (this);
    #end
```

Is that the proper way to handle it?

**Comment by jgranick** [comment]
This appears to be resolved now, it behaved as expected with the above sample code, or with other threshold values :smile:
