### ISSUE TITLE
CPP Crashes when trying to use Embedded Sounds

### ISSUE THREAD

**Issue by SeiferTim** [openfl/openfl#1089]
Here's the problem:

I have a project that I've been working on for months. It has been necessary to work on the project on different computers at different times. So, I have 2 computers I use regularly: Computer A is a Dell 'gaming' laptop that is a few years old. Computer B is a Dell Desktop that is a little bit newer but they are otherwise very similar - both running Win 7 64-bit, 8 GB of RAM. Up-to-date on drivers and everything.

So, for a long time, I'd been able to develop using either machine with no problems. Then, about a month ago, I started having a problem with the laptop.

I am using HaxeFlixel to develop with (although this is an OpenFL problem). When I build a project with embedded audio files, using Next, my application crashes on the laptop as soon as I try to play any sound. No errors show up in the console, nothing on the screen, the game just quits.

However, build the same project on my desktop computer, and it does not crash on the desktop or on other computers - it DOES still crash on the laptop.

Any project I build on the laptop - if I run it on the laptop, or any computer, including the desktop, it crashes.
Any project I build on the desktop seems to work on all the computers I've tested it on - except the laptop.

I've recreated this problem with the Flixel Mode demo (just had to add `embed="true"` to Project.xml, and then build with `lime test windows -Dnext`)
And on the OpenFL PiratePig demo - they both do the exact same thing.

I've verified that all of my libraries and everything are the same on both computers. I've uninstalled/reinstalled everything on the laptop, done `lime rebuild windows -Dnext -clean` and a few other things that people have suggested, but nothing seems to work.

**Comment by Gama11** [comment]
I can reproduce this in the PiratePig sample on Neko by adding `embed="true"` [here](https://github.com/openfl/openfl-samples/blob/3.3.1/demos/PiratePig/project.xml#L29).

**Comment by larsiusprime** [comment]
As of right now I'm putting a $50 bounty on this bug, payable from me upon verification that it's fixed.

**Comment by Gama11** [comment]
Can this be closed then, with https://github.com/openfl/lime/pull/708 merged?

**Comment by ibilon** [comment]
It can.
