### ISSUE TITLE
Word wrap correction

### ISSUE THREAD

**Issue by tienery** [openfl/openfl#1093]
I can't make a pull request from another branch because I've messed up my checkouts on my local repo, but the fix is very simple.

On line 869 of `TextEngine.hx`, the code:

```
offsetX = widthValue + spaceWidth;
```

should be:

```
offsetX += widthValue + spaceWidth;
```

Results before change:

![img](http://i.imgur.com/kQUJqoH.png)

Results after change:

![img](http://i.imgur.com/hGmoMOs.png)

**Comment by MSGhero** [comment]
I gotchu

**Comment by jgranick** [comment]
I think this has been resolved, thank you! 🏅
