### ISSUE TITLE
[openfl 3.6.1, lime 2.9.1] [Android] Unsuccessful attempt addChild(textField)

### ISSUE THREAD

**Issue by wolfhoundgelert** [openfl/openfl#1096]
Without "-Dlegacy" flag my minimal android app crashes with "Unfortunately, YourApp has stopped" message, when I try to add a TextField instance to the Stage.

With "-Dlegacy" flag it works.

**Comment by ibilon** [comment]
Could you post the log?

May be the same issue as #1111

**Comment by MiltonW** [comment]
@ibilon Maybe these help?

http://community.openfl.org/t/creating-textfield-crashes-mac-ios-build/7590
http://community.openfl.org/t/malloc-error-with-textfield-in-neko/7639

**Comment by wolfhoundgelert** [comment]
Solved in last releases
