### ISSUE TITLE
Improve support for transparent embedding on HTML5

### ISSUE THREAD

**Issue by Matan** [openfl/openfl#1097]
The Stage object is always instantiated with a background colour, this prevents transparency as the canvas always filled with said colour.

See this commit from way back: https://github.com/openfl/openfl/commit/dda7305a3d0c7bfb26533c883a2b8e2d948096e1

However, reverting back won't fix the issue. I've done some tests, the `config.background` can never be null. Nor 'unset' as the CLI always provides white as the default colour.

Thus, there is no way to pass null to allow transparency. For now, I can manually enable transparency by `@:privateAccess stage.__transparent = true;` at the start of my app.

Not sure what the best approach would be, maybe to add a new window parameter `transparent : Bool` or by passing a special -1 value to allow the passing of null to the Stage instantiation.

Let me know what you think. Happy to help implement something. :)

**Comment by jgranick** [comment]
Lime 4 (and subsequently OpenFL 4.9) revised the default HTML template, I believe you should be able to override the background color now, by adding `background: null` to the config object in the `lime.embed` call.

Also, I believe you may also be able to do it in XML using `<window background="" />`

Please let me know if these solutions don't work for you :smile:

**Comment by zehelvion** [comment]
Using OpenFL 4.9 and currently it keeps setting the background to black.
This is what I tried to do:

```
	<script type="text/javascript">
		lime.embed ("::APP_FILE::", "openfl-content", ::WIN_WIDTH::, ::WIN_HEIGHT::, {parameters: {background: null}});
	</script>

	<window background="" fps="60" />

Many thanks. :)
```
