### ISSUE TITLE
Line rendering discrepancies

### ISSUE THREAD

**Issue by IBwWG** [openfl/openfl#1104]
...as distinct from #841...

With both drawRect and lineTo, there seems to be variance between targets on openfl 3.6.1 (lime 2.9.1), also between legacy and Next.

See https://github.com/HaxeFlixel/flixel/pull/1822#issuecomment-213066681 for one example with drawRect.  If I replace the code in question with lineTo, on legacy Flash you get:

![lineto-legacy-flash](https://cloud.githubusercontent.com/assets/16719964/14722477/0c524650-080c-11e6-8e9d-5ba0909f3aa0.png)

And on legacy neko, and also legacy native windows you instead get:

![lineto-legacy-neko](https://cloud.githubusercontent.com/assets/16719964/14722523/356045d8-080c-11e6-9f6c-2c00c58a1932.png)

And I'd screenshot with Next but I always forget the proper way to re-enable that on HaxeFlixel...anyway hopefully the above is enough to show that things could use a review.

**Comment by ibilon** [comment]
I looked at you flixel pr but I'm not very familiar with it.

Could you post the openfl code required to see this bug?

**Comment by IBwWG** [comment]
Sorry, *I* had looked at the openfl code, but I forgot that I hadn't posted it directly, since it was part of the lib.  Will do shortly.

**Comment by IBwWG** [comment]
Hmm, there are more layers involved than I thought.

**Comment by IBwWG** [comment]
Not a straightforward reproduction, either, it seems.

**Comment by IBwWG** [comment]
OK, it seems that having a white background affects things, and also that the results are a bit different than what I think should be the equivalent through a few layers of haxeflixel library code.

This code:

```haxe
package;

import openfl.display.Graphics;
import openfl.display.Sprite;
import openfl.Lib;

class Main extends Sprite 
{

	public function new() 
	{
		super();
		
		var solid = new Sprite();
		solid.graphics.beginFill(0xffffff);
		solid.graphics.drawRect(100, 100, 10, 10);
		addChild(solid);
		var border = new Sprite();
		border.graphics.lineStyle(1, 0xff0000, 0.5);
		border.graphics.drawRect(100, 100, 10, 10);
		addChild(border);
	}

}
```

Gives this on legacy neko:

![openfl-drawrect-legacy-neko](https://cloud.githubusercontent.com/assets/16719964/14760621/37478bde-0949-11e6-8763-c1da67a52233.png)

And on legacy flash:

![openfl-drawrect-legacy-flash](https://cloud.githubusercontent.com/assets/16719964/14760623/5c2f0b20-0949-11e6-8c49-753a8ffd84bd.png)


Whereas this code:

```haxe
package;

import openfl.display.Graphics;
import openfl.display.Sprite;
import openfl.Lib;

class Main extends Sprite 
{

	public function new() 
	{
		super();
		
		var solid = new Sprite();
		solid.graphics.beginFill(0xffffff);
		solid.graphics.drawRect(100, 100, 10, 10);
		addChild(solid);
		var border = new Sprite();
		border.graphics.lineStyle(1, 0xff0000, 0.5);
		border.graphics.moveTo(100, 100);
		border.graphics.lineTo(110, 100);
		border.graphics.lineTo(110, 110);
		border.graphics.lineTo(100, 110);
		border.graphics.lineTo(100, 100);
		addChild(border);
	}

}
```

Gives this for legacy neko:

![openfl-lineto-legacy-neko](https://cloud.githubusercontent.com/assets/16719964/14760636/aa9cdf12-0949-11e6-9c42-85a8276041c3.png)

And this for legacy flash:

![openfl-lineto-legacy-flash](https://cloud.githubusercontent.com/assets/16719964/14760648/df916e0e-0949-11e6-93f5-7f32ec3bd587.png)

It's quite odd that it's not giving a between-pixels look, but there are still discrepancies even with this reproduction.

The original haxeflixel code was:

```haxe
		var gfx:Graphics = beginDrawDebug(camera);
		gfx.lineStyle(1, color, 0.5);
		gfx.drawRect(rect.x, rect.y, rect.width, rect.height);
		endDrawDebug(camera);
```

Now, the coordinates being fed in are the same (floats, but they happen to be rounded), and endDrawDebug simply calls the camera's BitmapData.draw(a) where `a` is the sprite you get back as `gfx` above.  So they should be equivalent, but I'm not well versed on these parts of haxeflixel's internals either.  Maybe HF sets some of openfl's rendering settings to things other than the default?

**Comment by jgranick** [comment]
We'll continue to track improvements to the positioning of line rendering here:

https://github.com/openfl/openfl/issues/1148

Thank you again for your help!
