### ISSUE TITLE
Negative Dimensions in Graphics API Causes layering issues

### ISSUE THREAD

**Issue by CharlesAnifowose** [openfl/openfl#1110]
This is maybe a more of a word of caution to others about the handling of the HTML5 Canvas API than it is an issue with OpenFL, but I wanted to post this anyway. If a negative value is used in functions like drawRect, you can end up with an object which covers the entire draw layer which can wreak havoc on MouseEvent listeners. This is not an issue in SWF publishing. 

My team is getting around this for the moment by wrapping the drawRect functions by sanitizer functions, but we may want to consider doing this at the level of the Lime renderer for the benefit of the community :)

**Comment by jgranick** [comment]
I think this is working right in current versions, but if you still have this problem, a little bit of sample code would really help. Thank you :smile:
