### ISSUE TITLE
hitTestPoint shapeFlag not working

### ISSUE THREAD

**Issue by Miltage** [openfl/openfl#1114]
I'm trying to do a pixel perfect hit test with a `Sprite`, but I'm getting a collision with the `Sprite`'s bounding box rather than it's actual shape, even if I set the `shapeFlag` parameter.

I took a look at the code for the function and unless I'm wrong, it looks like the parameter is not taken into account.

```
public function hitTestPoint (x:Float, y:Float, shapeFlag:Bool = false):Bool {

    if (parent != null) {

        var bounds = new Rectangle ();
        __getBounds (bounds, __getWorldTransform ());

        return bounds.containsPoint (new Point (x, y));

    }

    return false;

}
```

**Comment by ibilon** [comment]
Indeed that's missing.

**Comment by jgranick** [comment]
Fixed: https://github.com/openfl/openfl/commit/9796630ad81c9c30624425da26f1c1998f53e1f4
