### ISSUE TITLE
Wrong render or screen height in tablets with on-screen controls

### ISSUE THREAD

**Issue by shadowofsoul** [openfl/openfl#1115]
I'm not sure if the problems is from rendering or from an incorrect reported height by the Capabilities class, but this is what i saw.

Test case:
Empty project, generated a sprite, with a green bar at the bottom, the goal is to align it to the bottom of the screen. Using OpenFL Legacy. Tested on a real tablet, android 4.4.2

The problem:
With devices that has a bottom bar to control the home button, back, etc.. like tablets:
1) the reported size by Capabilities is the same with fullscreen=true|false
2) if fullscreen is false, and  you try to align the element to the bottom, it actually do it, but it's get hide by the android control bar
3) if fullscreen is true, the element is aligned not to the bottom of the screen, but at where the android control bar starts, leaving a blank space.

Screenshots:

fullscreen mode on:
![device-2016-04-29-105937](https://cloud.githubusercontent.com/assets/375696/14918616/52c82b8c-0dfb-11e6-941a-b66814eaec1a.png)

fullscreen mode on activating the control bar (so you can see that the white space starts where the controls bar is rendered)
![screenshot_2016-04-29-21-58-57](https://cloud.githubusercontent.com/assets/375696/14918667/8abab730-0dfb-11e6-8ecb-579f4d71c54a.png)

fullscreen mode off (bar is always visible)
![device-2016-04-29-111123](https://cloud.githubusercontent.com/assets/375696/14918700/a8eae360-0dfb-11e6-9c6f-455e74dfa145.png)

Important:
I tested this on a phone, that doesn't has this bar, and the code works perfectly.
I don't have this kind of problem if i use Lime 2.4.4 and OpenFL 3.1.0, with exactly the same code. all renders correctly.

Test Project:

[testsize.zip](https://github.com/openfl/openfl/files/242613/testsize.zip)

**Comment by ibilon** [comment]
Capabilities returns the screen's size, not the window's.
Does it work if you use `Stage.stageHeight`?

**Comment by shadowofsoul** [comment]
`src/com/ipsilondev/testsize/Main.hx:37: characters 9-26 : Class<openfl._legacy.display.Stage> has no field stageHeight`

**Comment by shadowofsoul** [comment]
`Lib.current.stage.stageHeight` did the trick for when fullscreen = false, but still, seems that the reported size is wrong when fullscreen is enabled (i have the same empty space)
