### ISSUE TITLE
TextField does not "\r" as it handles "\n" for line breaks

### ISSUE THREAD

**Issue by jgranick** [openfl/openfl#1120]
We need to improve the code to handle both "\r" and "\n" as line breaks

**Comment by larsiusprime** [comment]
Just checking for clarity:

"\r\n" still counts as one line break, not two, right? Because windows text files are chock-full of those.

But yes a "\r" by itself or a "\n" by itself should probably be interpreted as a line break.

**Comment by tienery** [comment]
I think most cross-platform editors by itself use "\n" by default, without "\r". Also, I've only ever seen Notepad on Windows that does not correctly interpret a "\n", and instead **requires both** characters.

That's the only editor I know that has that behaviour, most other editors will line break where "\n" exists, and ignores the "\r", at least visually speaking.

**Comment by jgranick** [comment]
Flash and legacy both appear to treat "\r" and "\n" as a line break, "\r\n" causes two line breaks
