### ISSUE TITLE
Experimental Webgl

### ISSUE THREAD

**Issue by peteshand** [openfl/openfl#1121]
Hey

There is an issue in OpenGLView in regards to Experimental WebGL initialization. Basically when initializing a context with "experimental-webgl", no option params are past in.

This is the class with the problem.
https://github.com/openfl/openfl/blob/develop/openfl/display/OpenGLView.hx

```
__context = cast __canvas.getContext ("webgl", {
	
	alpha: false, 
	premultipliedAlpha: false, 
	antialias: false, 
	depth: Reflect.hasField (window.config, "depthBuffer") ? window.config.depthBuffer : true, 
	stencil: Reflect.hasField (window.config, "stencilBuffer") ? window.config.stencilBuffer : false
	
});

if (__context == null) {
	
	__context = cast __canvas.getContext ("experimental-webgl");
	
}

```
I've fixed this in my branch, but it's been difficult to get small fixed like this merged due to other unrelated amendments I'm made.

This is what is needs to change to:
```
var options = {
	alpha: false, 
	premultipliedAlpha: false, 
	antialias: true, 
	depth: Reflect.hasField (window.config, "depthBuffer") ? window.config.depthBuffer : true, 
	stencil: Reflect.hasField (window.config, "stencilBuffer") ? window.config.stencilBuffer : false
}

__context = cast __canvas.getContext ("webgl", options);

if (__context == null) {
	__context = cast __canvas.getContext ("experimental-webgl", options);
}
```
Is someone able to make this fix?

**Comment by ibilon** [comment]
Indeed, thanks for reporting the issue!
