### ISSUE TITLE
TextField.textWidth and textHeight crash with lime 2.9.1

### ISSUE THREAD

**Issue by RealyUniqueName** [openfl/openfl#1122]
Following snippet crashes openfl app with lime 2.9.1 on neko and cpp targets.

``` haxe
var txt = new flash.text.TextField();
txt.text = 'hello';
trace(txt.textWidth);
```

```
$ lime test neko -debug 
*** Error in `./test': free(): invalid pointer: 0x00007f112f547596 ***
Aborted (core dumped)
```

It works fine with `-Dlegacy` or with lime 2.9.0

**Comment by danhett** [comment]
OK, I'm getting this too. Any advice?

**Comment by RealyUniqueName** [comment]
Here https://github.com/RealyUniqueName/StablexUI/issues/227#issuecomment-226109903 @r3d9u11 said he got it to work with neko 2.1
