### ISSUE TITLE
Textfield: Sometimes text added to the textfield is not always shown on CPP

### ISSUE THREAD

**Issue by mikkelmr** [openfl/openfl#1133]
On Windows and IOS I have experienced that sometimes text added to the textfield is not shown.

Take the following snippet:

```haxe
var tf = new TextField();
tf.multiline = true;
addChild (tf);
	
tf.text = "Trace me\n";
haxe.Timer.delay
(
	function() { 
		tf.text += "Trace me also please\n"; 
	},
	0
);	
```
I would expect to see both lines added to the textfield, but only the first one appears.
And the only difference I can see is, that the second line is added in a delayed function call.

I'm on the latest code in development branch in both OpenFL and Lime. And OpenFL Next. On legacy it works as expected.

**Comment by larsiusprime** [comment]
What happens if you use appendText() instead of ```tf.text +=``` ?

**Comment by mikkelmr** [comment]
@larsiusprime no difference.

**Comment by mikkelmr** [comment]
However, using --window-hardware=false makes it work. I actually discovered this when I tested it over a remote desktop and suddenly everything worked.



According to @jgranick this could have something to do with dirty caching - quoting from our [slack  conversation](https://openfl.slack.com/archives/help/p1463519545001087):

>does it work using --window-hardware=false on the desktop? 
There's two layers of dirty caching -- the Cairo surface used for the text render, the GL surface uploaded to the GPU
> if either is not flagged "dirty" properly, then it will not show new changes
> (this is what keeps it from redrawing and recreating textures every frame)
