### ISSUE TITLE
Enable ColorTransform

### ISSUE THREAD

**Issue by jgranick** [openfl/openfl#1140]
We need to continue searching if there is a fast approach to `colorTransform` that we could use on HTML5 canvas or Cairo.

We also need to see if we should consider adding `colorTransform` back into the standard shader, or if we should use a custom shader to enable this functionality

**Comment by mtari** [comment]
Hi Joshua,
Sorry for bothering you with this. But can I ask what's the progress on this? We would like to use colorTransform on HTML5 for our project.
Thanks, Mihaly

**Comment by vizanto** [comment]
This pull request: https://github.com/openfl/openfl/pull/1246 implements it :)   Depending on the type of graphics it's probably faster than per-pixel color transformations.

**Comment by mtari** [comment]
Great news. Thank you.

**Comment by jgranick** [comment]
https://trello.com/c/jEkE8r1B/16-add-support-for-sprite-transform-colortransform
