### ISSUE TITLE
Improve support for pixel precision in `Graphics`

### ISSUE THREAD

**Issue by ianharrigan** [openfl/openfl#1148]
So there seems to be some inconsistencies in the results of drawing boxes and borders between flash and cpp (im sure other non-flash targets will be similar). Heres a small example:

``` haxe
class Main extends Sprite {
    public function new() {
        super();

        var g:Graphics = this.graphics;
        // using lineStyle
        box(this.graphics, 10, 10, 100, 30);
        box(this.graphics, 10.5, 50.5, 100.5, 30.5);

        // using lineTo
        box(this.graphics, 130, 10, 100, 30, "lines");
        box(this.graphics, 130.5, 50.5, 100.5, 30.5, "lines");

        // using rects for borders
        box(this.graphics, 250, 10, 100, 30, "rects");
        box(this.graphics, 250.5, 50.5, 100.5, 30.5, "rects");
    }

    private static function box(g:Graphics, x:Float, y:Float, w:Float, h:Float, compound:String = "no") {
        var bg:Int = 0xCCCCCC;
        var fg:Int = 0x000000;
        if (compound == "no") {
            g.beginFill(bg);
            g.lineStyle(1, fg);
            g.drawRect(x, y, w, h);
            g.endFill();
        } else if (compound == "lines") {
            g.beginFill(bg);
            g.lineStyle(1, fg);

            g.moveTo(x, y); // top
            g.lineTo(x + w, y);

            g.moveTo(x + w, y); // right
            g.lineTo(x + w, y + h);

            g.moveTo(x + w + 1, y + h); // bottom
            g.lineTo(x, y + h);


            g.moveTo(x, y + h); // left
            g.lineTo(x, y);


            g.lineStyle();
            g.drawRect(x, y, w, h);
            g.endFill();
        } else if (compound == "rects") {
            g.beginFill(fg); // top
            g.drawRect(x, y, w, 1);
            g.endFill();

            g.beginFill(fg); // right
            g.drawRect(x + w, y, 1, h);
            g.endFill();

            g.beginFill(fg); // bottom
            g.drawRect(x, y + h, w + 1, 1);
            g.endFill();

            g.beginFill(fg); // left
            g.drawRect(x, y, 1, h);
            g.endFill();

            g.beginFill(bg);
            g.drawRect(x + 1, y + 1, w - 1, h - 1);
            g.endFill();
        }
    }
}
```

And here is the flash results:
![image](https://cloud.githubusercontent.com/assets/3024242/15532934/80262ef0-2262-11e6-9a59-f7754853dcad.png)

And here is cpp:
![image](https://cloud.githubusercontent.com/assets/3024242/15532946/95470cf0-2262-11e6-81a5-7e353c0e92f5.png)

Im using next and the git version.

Cheers,
Ian

**Comment by larsiusprime** [comment]
Thanks for the solid repro case. It would be really nie to iron out all these kinks!

**Comment by ibilon** [comment]
The most likely reason: https://cairographics.org/FAQ/#sharp_lines

**Comment by ianharrigan** [comment]
So ive actually updated the example a little as previously the drawing calls were interfering with each other. Now the `box` function creates a sprite and resets the x/y draw position to 0. The results are better, but still an issue. Instead of update the code example ive added another as both i think are useful.

```haxe
class Main extends Sprite {
	public function new() {
		super();
        
        // using lineStyle
        box(10, 10, 100, 30);
        box(10.5, 50.5, 100.5, 30.5);

        // using lineTo
        box(130, 10, 100, 30, "lines");
        box(130.5, 50.5, 100.5, 30.5, "lines");
        
        // using rects for borders
        box(250, 10, 100, 30, "rects");
        box(250.5, 50.5, 100.5, 30.5, "rects");
	}
    
    private static function box(x:Float, y:Float, w:Float, h:Float, compound:String = "no") {
        var sprite:Sprite = new Sprite();
        var g:Graphics = sprite.graphics;
        sprite.x = x;
        sprite.y = y;
        Lib.current.stage.addChild(sprite);
        x = 0; y = 0;
        
        var bg:Int = 0xCCCCCC;
        var fg:Int = 0x000000;
        if (compound == "no") {
            g.beginFill(bg);
            g.lineStyle(1, fg);
            g.drawRect(x, y, w, h);
            g.endFill();
        } else if (compound == "lines") {
            g.beginFill(bg);
            g.lineStyle(1, fg);
            
            g.moveTo(x, y); // top
            g.lineTo(x + w, y);
            
            g.moveTo(x + w, y); // right
            g.lineTo(x + w, y + h);
            
            g.moveTo(x + w + 1, y + h); // bottom
            g.lineTo(x, y + h);
            
            
            g.moveTo(x, y + h); // left
            g.lineTo(x, y);
            
            
            g.lineStyle();
            g.drawRect(x, y, w, h);
            g.endFill();
        } else if (compound == "rects") {
            g.beginFill(fg); // top
            g.drawRect(x, y, w, 1);
            g.endFill();
            
            g.beginFill(fg); // right
            g.drawRect(x + w, y, 1, h);
            g.endFill();
            
            g.beginFill(fg); // bottom
            g.drawRect(x, y + h, w + 1, 1);
            g.endFill();
            
            g.beginFill(fg); // left
            g.drawRect(x, y, 1, h);
            g.endFill();
            
            g.beginFill(bg);
            g.drawRect(x + 1, y + 1, w - 1, h - 1);
            g.endFill();
        }
    }
}
```

cpp results:
![image](https://cloud.githubusercontent.com/assets/3024242/15540335/04f81336-2287-11e6-8288-cfa6fad87b78.png)

Note: this is much more like the results i get in haxeui2 (currently im drawing compound borders using rects and forcing co-ords to ints - which isnt ideal)

**Comment by ianharrigan** [comment]
Quick follow up, it can be fixed with the following code (keep in mind its throw away code, and makes assumptions, like border size being 1), but this gives _fairly_ consistent results:

At the start of the `box` function
```
        var sprite:Sprite = new Sprite();
        var g:Graphics = sprite.graphics;
        sprite.x = x;
        sprite.y = y;
        Lib.current.stage.addChild(sprite);
        var xm = .5 - (x % 1); // x-modifier
        var ym = .5 - (y % 1); // y-modifier
        var wm = (x % 1); // w-modifier
        var hm = (y % 1); // h-modifier
        x = 0; y = 0;

        x -= xm;
        y -= ym;
        w += wm;
        h += hm;
```

cpp results:
![image](https://cloud.githubusercontent.com/assets/3024242/15540728/451b33d8-2289-11e6-987b-9591dc67e717.png)

So this does fix but i wonder if 
* there is a better way of doing it
* if this should be in openfl to handle this type of stuff

What do you think?

**Comment by vizanto** [comment]
@ianharrigan would you like to try again now that https://github.com/openfl/openfl/pull/1446 is merged?

**Comment by ianharrigan** [comment]
@vizanto - will do later tonight / this weekend. Cheers!

**Comment by vizanto** [comment]
Flash is still better, unfortunately:
![screen shot 2017-01-27 at 15 51 33](https://cloud.githubusercontent.com/assets/326263/22375003/b11b7f5c-e4a8-11e6-9621-ab53566ca2e3.png)

**Comment by ianharrigan** [comment]
Yup, i get similar results:

![image](https://cloud.githubusercontent.com/assets/3024242/22381671/c039f2e2-e4c2-11e6-917d-2b3bf4c46df6.png)

![image](https://cloud.githubusercontent.com/assets/3024242/22381689/d5fdbe9c-e4c2-11e6-8167-6e74942c12ad.png)

Any thoughts?

**Comment by ibilon** [comment]
Probably the same reason I mentioned https://cairographics.org/FAQ/#sharp_lines cairo can't draw non blurry 1px wide lines at integer positions, it needs the +0.5.

**Comment by ianharrigan** [comment]
Right, yeah, and you think its the job of the user to do this? I mean, this isnt an enhancement that belongs in openfl? Seems like something that could happen _fairly_ often.

**Comment by jgranick** [comment]
I don't think he was saying that :smile:

In some cases, we need a +0.5 offset, perhaps, to get things sharp. In other cases, this may mess up the drawing, so it's touch-and-go.

Anyway, it might be worth testing, to help get closer to a solution, but ultimately it should happen internally :smile:

**Comment by ianharrigan** [comment]
(just be clear that "Right, yeah, and you think its the job of the user to do this?" wasnt sarcastic at all, it was a genuine question ;) )

**Comment by jgranick** [comment]
Well, I just wanted to make sure we are were clear, this is listed as an "Enhancement" under OpenFL for a reason! 😅

**Comment by ianharrigan** [comment]
Fair play. :)

**Comment by intoxopox** [comment]
Any updates on this?
