### ISSUE TITLE
BlendMode doesn't work on Neko and CPP

### ISSUE THREAD

**Issue by thecocce** [openfl/openfl#1149]
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** CPP, Neko ,Windows. Android

________________________________

Hi the blandmode works only on flash target.
![blendmodes demo](https://cloud.githubusercontent.com/assets/3259703/15556615/098b3732-22cf-11e6-9596-457c67c0b2d0.jpg)

**Observed behavior:**
**Expected behavior:**

**Comment by larsiusprime** [comment]
Looks like you're using a flixel project. Did you compile with -Dnext flag? Flixel by default forces the "-Dlegacy" flag so you need to use -Dnext to counteract it.

**Comment by thecocce** [comment]
Hi , I usually use legacy on flixel. So is not supported in legacy mode anymore?

**Comment by MSGhero** [comment]
Some things never worked correctly in legacy. Legacy is still the default for flixel, though.

**Comment by larsiusprime** [comment]
@thecocce It's been this way for a long time. There were certain things that legacy never could or would support, including blend modes. This is why we created next, so that we could eventually fill in these gaps and eventually make legacy obsolete.
