### ISSUE TITLE
[OSX] Failed to install OpenFL via 'haxelib install openfl'

### ISSUE THREAD

**Issue by xarple** [openfl/openfl#1162]
I followed the instructions of the official site, installed Haxe through installer, then run 'haxelib install openfl', I got these:

> xarples-MacBook-Air:~ xarple$ haxelib install openfl
> Downloading openfl-3,6,1.zip...
> Download complete : 0 bytes in 0.6s (0KB/s)
> Eof
> xarples-MacBook-Air:~ xarple$ 

Did I missed something steps?
Thanks.

**Comment by jgranick** [comment]
This was an issue with the haxelib server, it sounds like. It should be working now

Thank you! :smile:
