### ISSUE TITLE
Where did AGLSLShaderUtils go?

### ISSUE THREAD

**Issue by peteshand** [openfl/openfl#1166]
Hey where did AGLSLShaderUtils go in the latest update? Both Starling and Away3D rely on this class

**Comment by peteshand** [comment]
openfl._internal.aglsl.AGLSLCompiler right?

**Comment by jgranick** [comment]
Hi @peteshand,

The goal is to make the Stage3D bindings officially supported, and to continue to move closer to the level of functionality one expects one porting from Flash to Haxe.

You should be able to use the updated AGALMiniAssembler similar to the one that Adobe provides, here's an example of the change:

https://github.com/openfl/starling/commit/249a842bcf9984f053a8254313d376239ea7f590

I would also like to talk more about the future of Starling on Haxe, and how we can move toward both an OpenFL Stage3D implementation that works like we'd expect, and how we can gather together the strengths of all the Starling versions and how we can support Starling as close to no modification as possible so we can stay up-to-date :smile:

**Comment by peteshand** [comment]
Hey @jgranick

Cheers for the quick reply.. yeah that's pretty much what I ended up doing... tho, you're example is a little more clean.

Happy to chat regarding OpenFL and Starling... my goal with Haxeling has always been to use the Haxelib version of OpenFL and Lime... Unless I can't get something merged ;) 

I have reached out to vroad regarding working together and we had planned on working on the Starling V2 port, but he decided against it at the last minute.

And I actually didn't even know there was a Starling in the OpenFL github... Is this a completely different port or forked from vroad's version?

What do you have in mind moving forward?

**Comment by peteshand** [comment]
It would be awesome to get a bit more robust testing around targeting AIR.

**Comment by peteshand** [comment]
Hey Joshua, What's your email?

**Comment by jgranick** [comment]
I just sent you an email :shipit:
