### ISSUE TITLE
TextField Input doesn't erase existent text with backspace

### ISSUE THREAD

**Issue by shadowofsoul** [openfl/openfl#1173]
Hi,

i think i found a really weird bug, as i could only reproduce it with a 4.4.2 chinese tablet that i use for testing (language set in spanish btw, i tested setting up the language in english (US) with the same result), tested exactly the same code in a samsung neo 4, and i couldn't reproduce it);

i'm using openfl legacy, 3.6.1 and lime 2.9.1. compiled with hxcpp 3.2.205 and 3.3.49. i tested with  the most basic code:

      txt = new TextField();

		txt.y = 100;

		txt.x = 100;		

		txt.type = TextFieldType.INPUT;

		txt.textColor = 0x000000;

		txt.border = true;

		txt.text = "lala";

		addChild(txt);`

what i'm having as result is:

*Whatever is set via `txt.text` can't be erased with backspace
*If i do focus and write on it, i can erase what i wrote, but anything that was before, can't be erased
*After i lose focus, this new text wrote manually, becomes permanent, and can't be erased with backspace
*The only way to erase this "permanent" text, is selecting it, and hitting a new letter (backspace doesn't work)
*Even if i select the word at the middle of it, and erase it by pressing a new letter, the rest of the word would not be erased by backspace, only the new text i insert before i lose focus can be erased with backspace.

i'm not really looking for a solution, i suppose that no one faced something like this. Just a guide of where in the lime code, i could put a trace to debug it and submit a pull request :)

Adding a video so you can see what i'm talking about.

[bug-textt.mp4.zip](https://github.com/openfl/openfl/files/344417/bug-textt.mp4.zip)

**Comment by Yanrishatum** [comment]
1. Backspace does not work because it does not implemented at all. And so does enter, arrows, delete, pg up, pg down, home, end, insert, etc.
2. Handling can be added, but considering on how String currently handled you may have problems with Unicode characters.

**Comment by shadowofsoul** [comment]
From what i could see in the code, backspace is implemented ( https://github.com/openfl/lime/blob/master/legacy/project/src/sdl2/SDL2Stage.cpp#L902 and https://github.com/openfl/lime/blob/master/legacy/project/src/sdl2/SDL2Stage.cpp#L973 ) and it actually works (i have also be able to have it working on a samsung neo 4) on i suppose, almost all devices, except the one i have (if not, other would already reported this before).

after seeing the code, this could be a problem in the translation of the SDL keys -> flash key codes when the focus is lost and is back again, but i couldn't debug by putting a `VLOG` there yet why i can't compile lime legacy for android for a problem in the `-std=c++11` that for some reason is not recognized by my `g++ 4.8.1` i have. So i will try to set up a VM or if someone knows how to change that flag to `c++0x` that supposedly should work to compile it.

**Comment by jgranick** [comment]
Does this work without legacy?

**Comment by shadowofsoul** [comment]
on next, it crashes as soon it start. attaching the log (on both, the tablet and the samsung neo 4)
[log-next.txt](https://github.com/openfl/openfl/files/350747/log-next.txt)

**Comment by shadowofsoul** [comment]
closing this, legacy is not supported anymore. i'll handle this on my own (or not, as i can only reproduce it on this table specifically)

**Comment by srevid** [comment]
I reproduce it on HTC M8 Android 6.0.1
