### ISSUE TITLE
Segfault starting DisplayingABitmap on Linux Mint 17.2 32-bit

### ISSUE THREAD

**Issue by IBwWG** [openfl/openfl#1176]
haxe 3.2.1, openfl 3.6.1, openfl-samples 3.3.1, and lime 2.9.1.

I'm launching from the export /bin directory after compiling it on the same machine.  I also tried `openfl run project.xml linux` per https://github.com/openfl/openfl/issues/630#issuecomment-98473773 but with the same result.

```
~/DisplayingABitmap $ lime build project.xml linux
...
~/bin $ ./DisplayingABitmap
Segmentation fault
```

And then /var/log/syslog has this to say about it:

```
kernel: [116461.214165] DisplayingABitm[14990]: segfault at 74614472 ip b10c8d5c sp bff980d0 error 4 in i915_dri.so[b0e56000+526000]
```

I get the exact same error with PiratePig, and also with Defender's Quest on that machine.  In all three cases, a window is created and immediately closes.

**Comment by ibilon** [comment]
Does `openfl test linux --window-hardware=false` work?

**Comment by IBwWG** [comment]
(Sorry for the delay, took a bit to recompile on my old netbook here)...yes!  It worked great!  What does this mean?  :)

**Comment by ibilon** [comment]
It means that it builds without hardware acceleration, ie. opengl.

Might be a driver issue, or an incompatible card, you need opengl 2 (I think) to be able to run openfl app.

Could you print the output of the command `glxinfo | grep 'version'`

**Comment by IBwWG** [comment]
Ah, thanks.  That would do it, I guess, since the output is:

```
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
OpenGL version string: 1.4 Mesa 10.1.3
```

**Comment by ibilon** [comment]
Yeah that's not going to be enough.

I wonder if we could have software as fallback in this case.

**Comment by IBwWG** [comment]
That would be wonderful.  That or at least a check, so that instead of segfaulting it can just state the version requirement.  :)  (Meanwhile I'm finding it a bit less than straightforward to upgrade OpenGL versions on Mint.)

**Comment by IBwWG** [comment]
I even upgraded to Mint 17.3, and also installed the "unsafe" only-available-showing-level-4 update for Mesa, and it still shows the same versions.  I wonder if that's normal...

**Comment by IBwWG** [comment]
Although, it seems that it may be impossible to upgrade past 1.4 since my graphics card is too old: "Intel Mobile 945GSE Express Integrated Graphics Controller"

Is there no way to support older hardware / GL versions for 2d applications?  (I have no idea what I'm asking, but there's a similar question about Godot out there, for example.)

**Comment by ibilon** [comment]
We can't support opengl <2, missing too many features.

The only thing we could do is detecting it and falling back on software,
I'll see if that's possible.

**Comment by IBwWG** [comment]
Thanks, I'd appreciate that.  Right now I have two builds out, but for example, itch.io doesn't let you pick between builds for the same platform from their app, so a fallback would let everything work much smoother and save whichever users don't get the right build from exposure to errors and having to figure out which build they need.

**Comment by jgranick** [comment]
I think we already fallback to software automatically for GL 1 drivers, same build

**Comment by larsiusprime** [comment]
What about SwiftShader as an alternative fallback?

http://blog.chromium.org/2016/06/universal-rendering-with-swiftshader.html

**Comment by IBwWG** [comment]
Why close?

**Comment by tienery** [comment]
Perhaps because Josh has been doing cleanup, and since the issue has not been commented on for almost half a year, it can be safe to assume that the issue has been resolved in that time.

**Comment by IBwWG** [comment]
I'm not sure that's a safe assumption, but I hope it's true.  :)

**Comment by tienery** [comment]
Well, if not, and you get the same issue with this related case, there's no stopping you from reopening the issue :)

**Comment by jgranick** [comment]
Hey guys :smile:

There is no segmentation fault when running `openfl test DisplayingABitmap linux` here using current versions of OpenFL and Lime. We should support both OpenGL and software renderer support, so even on machines with a poor graphics card, the issue should be resolved.

I understand that the issue exists for your in OpenFL 3.6.1 and Lime 2.9.1, but we have had more than a dozen releases since then, to resolve this and other issues, so to say it is fixed is not quite true from that perspective :smile:
