### ISSUE TITLE
Mouse events not firing for container if .mouseChildren == false

### ISSUE THREAD

**Issue by chpla** [openfl/openfl#1177]
On html5 target, it seems that when a DisplayObjectContainer is listening to mouseEvents and its .mouseChildren property set to true, the events for the container are not firing any more. This behavior is inconsistent with the behavior in as3, where mouse events are firing for both the container and the child in such a scenario.

**Comment by jgranick** [comment]
Would you mind sharing a small code sample where it works in Flash, but not in other targets? Thank you! :smile:

**Comment by chpla** [comment]
Okay, here goes:

`var parentObj:Sprite = new Sprite();
var childObj:Sprite = new Sprite();

parentObj.addChild(childObj);
addChild(parentObj);

parentObj.addEventListener(MouseEvent.CLICK, parentClickFn);
childObj.addEventListener(MouseEvent.CLICK, childClickFn);

function parentClickFn(evt:MouseEvent):Void
{
  trace('Parent clicked!');
}

function childClickFn(evt:MouseEvent):Void
{
  trace('Child clicked!');
}

parentObj.mouseChildren = true;`

In AS3, clicking the child object will produce both traces. In Openfl, only "Child clicked!" is produced.

**Comment by jgranick** [comment]
The following code is working for me (OpenFL 4.0.3, Lime 4.0.3)

```haxe
package;


import openfl.display.Sprite;
import openfl.events.MouseEvent;


class Main extends Sprite {
	
	
	public function new () {
		
		super ();
		
		var parentObj:Sprite = new Sprite();
		var childObj:Sprite = new Sprite();
		
		parentObj.graphics.beginFill (0xFF00FF);
		parentObj.graphics.drawRect (0, 0, 1000, 1000);
		
		childObj.graphics.beginFill (0xFF0000);
		childObj.graphics.drawRect (0, 0, 100, 100);
		
		parentObj.addChild(childObj);
		addChild(parentObj);
		
		parentObj.addEventListener(MouseEvent.CLICK, parentClickFn);
		childObj.addEventListener(MouseEvent.CLICK, childClickFn);
		
		parentObj.mouseChildren = true;
		
	}
	
	
	function parentClickFn(evt:MouseEvent):Void {
		
		trace('Parent clicked!');
		
	}
	
	
	function childClickFn(evt:MouseEvent):Void {
		
		trace('Child clicked!');
		
	}
	
	
}
```

Does it work for you? What version are you using?
