### ISSUE TITLE
Mono OGG files don't play

### ISSUE THREAD

**Issue by IBwWG** [openfl/openfl#1178]
They don't complain, trace, anything.  They just don't play.  Stereo OGG files in the same project play fine.

Note, this is _only_ happening on my beta tester's win7 box, but not on any other of 6 win7 machines that we've tried the game on.  The same pattern of playing vs playing nothing (errorless) also occurs for this person in Firefox, but not in VLC or Safari, which play all the OGGs just fine.  In Firefox the visual volume levels indicator shows that it's playing something too, just nothing is heard; stereo file in the same context works fine.

This is OpenFL 3.6.1.

The files that don't work were exported from Audacity or VLC, as were the (stereo) files that _do_ work.

The unfortunate thing is that there's no way to just script a conversion in VLC or Audacity.  Audacity can do it, but not through their "chains" function, so it means doing every file one at a time.

It would be much better if the mono files worked on all computers instead of playing silence without complaining.  Is there some kind of debug statements I could add to investigate the issue better?

**Comment by IBwWG** [comment]
An example mono OGG that doesn't work:
[TheLostPieceOfAtlantisLastPiece.zip](https://github.com/openfl/openfl/files/346558/TheLostPieceOfAtlantisLastPiece.zip)

**Comment by ibilon** [comment]
That doesn't look like an openfl bug if it doesn't apply to everybody and if this person already has issues playing ogg files in firefox.

**Comment by IBwWG** [comment]
Well, I'm thinking it's a bug in both openfl and whatever firefox uses (maybe they use the same lib?) because it works fine for that same person in VLC and Safari.  Also, they don't have issues with all ogg files: stereo ogg play fine for them in all four cases, openfl, firefox, safari, and vlc.

**Comment by larsiusprime** [comment]
I have a similar report of audio mysteriously not working in DQ for certain
users, hope this is the root of it

On Sat, Jul 9, 2016 at 12:34 PM, KJB <notifications@github.com> wrote:

> Well, I'm thinking it's a bug in both openfl and whatever firefox uses
> (maybe they use the same lib?) because it works fine for that same person
> in VLC and Safari. Also, they don't have issues with all ogg files: stereo
> ogg play fine for them in all four cases, openfl, firefox, safari, and vlc.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/openfl/openfl/issues/1178#issuecomment-231546026>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAtG-DLj4kaF96vwdRPEW2nWf29MsULKks5qT9utgaJpZM4JEdvp>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by IBwWG** [comment]
@larsiusprime Can you ask them to verify that a stereo version works for them, and/or that the mono ogg works for them in VLC?  You said audio rather than music...I just had a look at some of your assets, and at least title and happy are stereo, but among the sfx, I found at least one mono (clang_01) and one stereo (boost_1).  For your users is audio just not working at all?  Or just some files?

**Comment by jgranick** [comment]
The OGG has been improved in our current releases, though we have not implemented streaming audio, which had known issues in OpenFL 3.6.1. Hoping we will be able to get a new implementation soon that works around the known issues we had before, and is more solid :smile:
