### ISSUE TITLE
Is bit shifting really faster than integer multiplication/division?

### ISSUE THREAD

**Issue by vroad** [openfl/openfl#1179]
I think there is not much reason to prefer shift operators over multiplication operators. It just makes source code harder to read.

http://stackoverflow.com/questions/6357038/is-multiplication-and-division-using-shift-operators-in-c-actually-faster

https://github.com/openfl/openfl/blob/0433654517dff7ac57c1cf0d550d24cc1d644dc3/openfl/utils/ByteArray.hx#L720

**Comment by MSGhero** [comment]
Saves you from having to type out `Std.int` which gets annoying after a while, especially if you've used as3 where floats are automatically truncated to ints. Your link was for integers anyway, not floats. It doesn't matter either way.

**Comment by jgranick** [comment]
@vroad I think that is derived from code that Nicolas Cannasse wrote, I agree it's confusing to read :smile:
