### ISSUE TITLE
Vector allocates 10 elements when an element is pushed to empty Vector, and grows little by little unless you reserve capacity

### ISSUE THREAD

**Issue by vroad** [openfl/openfl#1180]
https://github.com/openfl/openfl/blob/1697a96a65bd8f94db277a3376cfd00f099ffc83/openfl/Vector.hx#L319

Why don't you double current size, just like STL vector? Increasing Vector size little by little may make app actually slower, as it internally allocates new array and copies old Vector content.

**Comment by ibilon** [comment]
Title is misleading, it only allocates when the size is too low ;)

It's extremely debatable, allocating a bigger array takes longer, and for the +10 if you end up only doing it once it's ok.

If performances are an issue the user should reserve enough space before pushing to the vector.

**Comment by vroad** [comment]
Why did you choose 10? Could it be 5, 20, or even 100 or 1000?

Current implementation wastes memory if you have a few number of elements. I also looked at ByteArray impl, and it uses 150%(3/2) of current size. I'm not sure why this number is used, but is still better than Adding 10 elements each time you run out of elements. It should be slow to allocate/copy memory every 10 elements is pushed.

@ibilon It's not always possible to predict how many elements you need before doing something... And many reserve()s may make code dirtier.

**Comment by vroad** [comment]
You said you can improve by performance by reserving enough space, but you could say it in an opposite way. "If memory usage is an issue the user should reserve enough space before pushing to the vector".

I think that Vector should work as fast as possible even when you don't know how many elements you need beforehand. I guess this is one of the reason why STL vector doubles current size when growing. You cannot optimize this case with currentSize+10 technique.

Also, doesn't CPUs work better if size of Vector is multiple of 4/8/16? Size of vector will be multiple of these numbers if you grow vector by doubling curent size multiple times.

**Comment by jgranick** [comment]
Hi @vroad

I just made a change to make it consistent with ByteArray, I would be fine with discussing this later, if we want a different algorithm for how much more we allocate, whether we use Nicolas' value, or just go double. Either way, it makes sense for it to be consistent, and not to have as arbitrary a number :wink:

Thanks
