### ISSUE TITLE
Run always on 8.1

### ISSUE THREAD

**Issue by julio6114** [openfl/openfl#1181]
Hi,

When I launch project on ios simulator like that:
`openfl run ios -simulator`
the simulator is always on 8.1 sdk
`Launch app on "com.apple.CoreSimulator.SimDeviceType.iPhone-6, 8.1"`

I've got 7.3.1 Xcode

I don't see what I can do to fix it

Thanks

**Comment by ibilon** [comment]
Let's discuss this in the lime issue.

**Comment by julio6114** [comment]
Ok thanks
