### ISSUE TITLE
MovieClip.addFrameScript not supported on Android

### ISSUE THREAD

**Issue by KnightMearh** [openfl/openfl#1182]
Haven't tried other native targets, but calling addFrameScript on Android platform seems to be completely ignored. It does work correctly in HTML5 target.

If I do my own makeshift function by checking 'if ( anim.currentFrame == # ) anim.stop();' it works that way, so am thinking this was just left out somewhere instead of something hard to do on native.

This is lime 2.9.0 and openfl 3.6.0 (can confirm it is also not working with lime 2.9.1 and openfl 3.6.1)

**Comment by jgranick** [comment]
Is it possible this is legacy? OpenFL (not legacy) should support it. Thanks :smile:

**Comment by CrazyFlasher** [comment]
Doesn't work on Android OpenFL develop + Lime 7.6.3
