### ISSUE TITLE
Why Utils3D haven't be fully implemented?

### ISSUE THREAD

**Issue by Neugls** [openfl/openfl#1184]
Currently, Utils3D only implemented a function `projectVector`  but other two function `pointTowards`  and `projectVectors` haven't? 

Whether the algorithm hard or other reason?
I have found a post gived some tips on function `projectVectors`: [Post](http://basrolog.blogspot.com/2010/03/utils3dprojectvectors-slow.html)

Hope the other two functions can work.

Thank you for the awesome OpenFL

**Comment by jgranick** [comment]
Hi!

This just hasn't happened yet. I have not done a lot with three-dimensional geometry, so I'm not immediately sure how these are implemented, though we'd be happy to accept any improvements to `Utils3D` :smile:

Is `projectVectors` the same as the `projectVector` method, but instead of writing one `Vector3D`, it writes `x` and `y` values to the `projectedVerts` array, and the `z` goes into the `t` value of the `uvts` array?

Do you have an example of code we could use to test?

These just haven't been implemented, but I'm sure they are not rocket science. The link you gave does not support UVs,

**Comment by Neugls** [comment]
HI, Thank you for reply.
I have writed the projectedVerts as the following code shows
`public static function projectVectors(m : Matrix3D, verts : Array<Float>, projectedVerts : Array<Float>, uvts : Array<Float>) : Void {
		if ( verts.length % 3 != 0 ) return;
		
		var n = m.rawData,
			x:Float, y:Float, z:Float, w:Float,
			x1:Float, y1:Float, z1:Float, w1:Float,
			i:Int = 0;
		
		while ( i < verts.length ) {
			x = verts[i];
			y = verts[i + 1];
			z = verts[i + 2];
			w = 1;
			
			x1 = x * n[0] + y * n[4] + z * n[8] + w * n[12];
			y1 = x * n[1] + y * n[5] + z * n[9] + w * n[13];
			z1 = x * n[2] + y * n[6] + z * n[10] + w * n[14];
			w1 = x * n[3] + y * n[7] + z * n[11] + w * n[15];
			
			projectedVerts.push( x1 / w1 );
			projectedVerts.push( y1 / w1 );
			
			uvts.push( 0 );
			uvts.push( 1/w1 );
			
			i += 3;
		}
		
	}`

And with a example to check whether it works or not, the following code works on Flash

`package;

import openfl.display.StageAlign;
import openfl.display.StageScaleMode;
import openfl.geom.Point;
import openfl.geom.Vector3D;
import openfl.display.Shape;
import openfl.display.Sprite;
import openfl.Lib;
import openfl.events.Event;
import openfl.geom.Matrix3D;
import openfl.geom.PerspectiveProjection;
import openfl.geom.Utils3D;

typedef Solid = {
	var verts: Array<Float>;
	var	indices: Array<Int>;
}


/**
 * ...
 * @author Silence
 */
class Main extends Sprite 
{

	public function new() 
	{
		super();
		
		if (stage != null) {
			
			stage.align = StageAlign.TOP_LEFT;
			stage.scaleMode = StageScaleMode.NO_SCALE;
		}
			
		var shape:Shape = new Shape();
		addChild( shape );
		
		
		var solid:Solid = {
			verts: [0,1,0, 1,0,0, 0,0,1, -1,0,0, 0,0,-1, 0,-1,0],
			indices: [0,1,2,0,2,3,0,3,4,0,4,1,5,2,1,5,3,2,5,4,3,5,1,4]
		};
		
		function drawSolid( matrix:Matrix3D, color:UInt ) {
			var persVerts:Array<Float> = new Array<Float>(),
				uvtData:Array<Float> = new Array<Float>();
			
			Utils3D.projectVectors( matrix, solid.verts, persVerts, uvtData );
			
			for ( i in 0...persVerts.length ) {
				persVerts[i] += (i % 2 == 0)?stage.stageWidth / 2 : stage.stageHeight / 2;
			}
			
			shape.graphics.lineStyle(1, color);
			shape.graphics.drawTriangles(persVerts, solid.indices, uvtData, 'negative');
			
		}
		
		var radius:Int = 30;
		function trackVector( theta:Float ):Vector3D {
			return  new Vector3D(
				radius*Math.cos(theta),
				radius*Math.sin(2*theta),
				0.1*radius*Math.sin(theta)
			);   				
		}	
		
		var markers:Array<Vector3D> = new Array<Vector3D>();
		for ( i in 0...100 ) {
			markers.push(trackVector(i / 100 * 2 * Math.PI));
		}
		
		var stars:Array<Vector3D> = new Array<Vector3D>();
		
		for ( i in 0...200 ) {
			stars.push(new Vector3D(
				5*radius*(Math.random()-0.5),
				5*radius*(Math.random()-0.5),
				5*radius*(Math.random()-0.5)
			));
		}
			
			
		var pers:PerspectiveProjection = new PerspectiveProjection();
		pers.fieldOfView = 55;
		pers.focalLength = 480;
		var persMatrix:Matrix3D = pers.toMatrix3D();
		var worldMatrix:Matrix3D = new Matrix3D();
		var solidMatrix:Matrix3D = new Matrix3D();
		var theta:Float = 0;
		
		
		stage.addEventListener(Event.RESIZE, function(e:Event):Void{
				pers.projectionCenter = new Point(stage.stageWidth/2, stage.stageHeight/2);
		});
		addEventListener(Event.ENTER_FRAME, function(e:Event):Void{
			shape.graphics.clear();
			var target:Vector3D = trackVector(theta);
			target.z += 2;
			var eye:Vector3D = trackVector(theta - 0.4);
			eye.z += 5;
			var sightLine:Vector3D = Vector3D.Z_AXIS;
			var diff:Vector3D = target.subtract(eye);
			var axis:Vector3D = sightLine.crossProduct(diff);
			var rotateTheta:Float = -Vector3D.angleBetween(sightLine, diff) * 180 / Math.PI;
			
			worldMatrix.identity();
			//构建摄像机世界，以眼睛到目标点的位置为焦距
			worldMatrix.appendTranslation( -eye.x, -eye.y, -eye.z);
			
			//让摄像头对准目标点
			worldMatrix.appendRotation(rotateTheta, axis);
			//让摄像头保持正向
			worldMatrix.appendRotation(Math.atan2(axis.x, axis.y) * 180 / Math.PI + 90, sightLine);
			worldMatrix.append(persMatrix);
			
			
			var n:Int = markers.length;
			while (n > 0) {
				n--;
				solidMatrix.identity();
				solidMatrix.appendTranslation(markers[n].x, markers[n].y, markers[n].z);
				solidMatrix.append(worldMatrix);
				
				if (solidMatrix.transformVector(new Vector3D(0,0,0)).z > 1) {
					drawSolid(solidMatrix, 0xa00000);
				}
			}
			n = stars.length;
			while (n > 0  ) {
				n--;
				solidMatrix.identity();
				solidMatrix.appendRotation(theta * 500, Vector3D.Z_AXIS);
				solidMatrix.appendTranslation(stars[n].x, stars[n].y, stars[n].z);
				solidMatrix.append(worldMatrix);
				if (solidMatrix.transformVector(new Vector3D(0,0,0)).z > 1) {
					drawSolid(solidMatrix, 0x707000);
				}
			}
			
			solidMatrix.identity();
			solidMatrix.appendTranslation(target.x, target.y, target.z);
			solidMatrix.append(worldMatrix);
			
			drawSolid(solidMatrix, 0xffffff);
			theta = (theta + 0.005) % (2 * Math.PI);
		});
		
	}
	
	
}
`
![20160718135439](https://cloud.githubusercontent.com/assets/1432749/16906761/3f21f382-4cef-11e6-8e24-def2d2cb8d06.png)

But in the openFL, it just shows blank, have got nothing, You can help check what's going wrong?

Thank you.

**Comment by MSGhero** [comment]
@Neugls if you try drawing anything in OpenFL, does it show up? Or is it black always? What target?

I have issues when I compile to cpp targets, maybe you do too.

**Comment by Neugls** [comment]
@MSGhero I have test html5 and neko target, both compiled successfully. When I comments the line off

`shape.graphics.drawTriangles(persVerts, solid.indices, uvtData, 'negative'); `

and use 
`shape.graphics.drawRect(0, 0, 100, 100)`

it shows a rectangle shape.

So, may be `graphics.drawTriangles` have some problem.

Here is the project file. 
While I can not upload the zip file, so I changed the extesion to jpg to upload, you can rechange the extension back to zip to open.

![3dtrack](https://cloud.githubusercontent.com/assets/1432749/16942745/56fa7e62-4dca-11e6-8004-2a6abd1309fc.jpg)
Thank you.

**Comment by Neugls** [comment]
Hi, I have checked that there is an error on `Matrix3D.appendRotation` method, and have fixed the problem at #1208 , and I finaly got same point data as flash at the final `drawTriangles` method,  on flash, it works fine, but on openfl, have got nothing just a black screen. So, I am now sure there are some problems in the `Graphics.drawTriangles` method, hope you guys can fix this problem.  Thank you.
