### ISSUE TITLE
Japanese doesn't word wrap correctly in TextFields

### ISSUE THREAD

**Issue by larsiusprime** [openfl/openfl#1185]
Repro case:
https://gist.github.com/larsiusprime/5df42543a4b09e07274cce2ad9943b83

What it should look like (flash isn't loading the font but the wrapping is correct):
![2016-07-08 13_24_40-adobe flash player 17](https://cloud.githubusercontent.com/assets/739064/16697479/686df3f4-450f-11e6-801a-8755637736bf.png)

What it does look like (neko/html5 have same results):
![2016-07-08 13_25_06-badjptext](https://cloud.githubusercontent.com/assets/739064/16697481/6b86881c-450f-11e6-843c-3c4598bc8ebd.png)

As you can see, it seems to be an issue with Japanese specifically, as cyrillic (Russian in this case) text wraps correctly. 

I tried with Korean text just now:
![2016-07-08 13_27_48-badjptext](https://cloud.githubusercontent.com/assets/739064/16697562/ce801d7a-450f-11e6-8260-43a0747a95ad.png)

And that seems to be working correctly. I don't have any Chinese strings to test with.

The Korean test string is:
`'시체\n시체들은 종종 죽은 지 몇 일 후에 구덩이 속에서 다시 일어납니다. 이런 괴물들은 ""다시 돌아온 자""라는 의미의 ""망령""이라 알려져 있습니다.'`

And the font is "nanum gothic", bold, available here:
http://www.ffonts.net/NanumGothicBold.font

Everything else necessary to repro with for Japanese is included in the gist.

**Comment by larsiusprime** [comment]
So from some conversations deduced it's because Japanese doesn't use spaces.

Update, just did a test to see what happens if I remove all the spaces from english text:

Flash:
![2016-07-08 13_49_41-adobe flash player 17](https://cloud.githubusercontent.com/assets/739064/16698211/d6156eac-4512-11e6-9751-22912adc6e33.png)

OpenFL (neko/html5):
![2016-07-08 13_48_06-badjptext](https://cloud.githubusercontent.com/assets/739064/16698198/c7275400-4512-11e6-8737-951dbf85ef37.png)

If you remove the english spaces, flash's behavior (but not openfl's) is to break on whatever character, even in the middle of a line.

So it seems like this approach would be "no worse" than flash, and would be appropriate regardless of locale.

**Comment by larsiusprime** [comment]
Presumably the issue is somewhere in this giant function:
https://github.com/openfl/openfl/blob/develop/openfl/_internal/text/TextEngine.hx#L576

**Comment by MSGhero** [comment]
Every issue is in that function 😉 

I'll look at it in a bit.

**Comment by MSGhero** [comment]
Ok problem: Part 1 also needs to do Part 2 when the next line break comes after a long, unbroken string.

Right now, everything assumes only spaces and crlfs can cause a line break, so it adds chunks of text at a time. Preeeeetty sure it needs to be done character by character since any of those chunks can be too big. I can't immediately think of a way to avoid that.

**Comment by MSGhero** [comment]
Getting there. Kinda looks like flash's text is slightly wider? Look closely at the n

HTML5:
![image](https://cloud.githubusercontent.com/assets/5033927/16706091/3f5be5bc-456d-11e6-8f0c-06cd56bb6f26.png)

Flash:
![image](https://cloud.githubusercontent.com/assets/5033927/16706112/c4e46588-456d-11e6-94c1-597272026020.png)


Someone else post, I don't want 5 in a row :(

**Comment by larsiusprime** [comment]
Great work!

**Comment by larsiusprime** [comment]
@MSGhero : here are the local changes I made that fix the "trailing premature broken character" edge case:
https://github.com/larsiusprime/openfl/commit/9ff46d6e15e8ab46b112e55cab641ffff1cd1a48

**Comment by MSGhero** [comment]
Edge cases 🙃🍷🙄😒😤😭

**Comment by larsiusprime** [comment]
You also want these:
https://github.com/larsiusprime/openfl/commit/42c189d7d66c2cf74eb1287afb94c2d142083061
https://github.com/larsiusprime/openfl/commit/caaf65059b3c6e96aee4e26503b69fefac2cff4e
https://github.com/larsiusprime/openfl/commit/21685e0313fd796a0c3d5edaa50ed4e0b70af329

**Comment by MSGhero** [comment]
Here's a fun example, same font that you posted earlier:

```haxe
var size = #if neko 12 #else 11 #end; // flash 11pt == neko 12pt for some reason???

var font = Assets.getFont("assets/mplus2cb.ttf").fontName;

var tf = new TextField();
tf.embedFonts = true;
tf.defaultTextFormat = new TextFormat(font, size, null, null, null, null, null, null, TextFormatAlign.LEFT);
tf.text = "こを使するこ123456789012345678901 23 4567890キストです。";
tf.x = 30;
tf.y = 30;
tf.width = 100;
tf.height = 200;
tf.border = true;
tf.wordWrap = true;
addChild(tf);
```
Neko top, flash bottom
![image](https://user-images.githubusercontent.com/5033927/29102696-8b898a52-7c80-11e7-9a55-cc63df2e871a.png)

On flash, the first break occurs after the first Japanese bit. On Neko, with my changes, the break occurs after some numbers. However, if you change the string to have English letters after the first Japanese bit (`こを使するこabcde`), it breaks mid-letters on Flash. Flash is purposefully breaking on numbers rather than doing it by `lineWidth > width - 2`.
