### ISSUE TITLE
Starling + Dom + Starling Textfield with htmlText = crash

### ISSUE THREAD

**Issue by peteshand** [openfl/openfl#1187]
There is an issue where if you use Starling 2.x and OpenFL together with the Dom renderer and add a starling textfield with htmlText, it will cause the browser to lock up. This has to do with the fact that textFormatRanges aren't created when the Dom renderer is used.. This causes an infinite loop when styling is applied.

I'm not sure the best way around this... I can put something in Starling to not allow htmlText when the Dom renderer is used.. or we could add something in the openfl TextField class to create textFormatRanges is starling is being used..

Something like the below
https://github.com/openfl/openfl/blob/develop/openfl/text/TextField.hx

Line 1160
if (#if (js && html5) #if dom false && #end __div == null #else true #end) {
change to
if (#if (js && html5) #if starling true && #elseif dom false && #end __div == null #else true #end) {

Thoughts?

**Comment by jgranick** [comment]
I think this crash in DOM text was solved. If not, please let me know
