### ISSUE TITLE
SharedObject.flush() throws error on html5 target

### ISSUE THREAD

**Issue by chpla** [openfl/openfl#1188]
SharedObject is obtained by a call to static method SharedObject.getLocal('foo/bar/yadda', '/', false);.

When I try to use the .flush() method on the object, I get the following error:

Cannot serialize function.

**Comment by MSGhero** [comment]
What are you attempting to serialize? Something with a function as a variable?

**Comment by chpla** [comment]
I'm not aware that I'm trying to serialize anything. I'm trying to save the data content of the SharedObject.

**Comment by MSGhero** [comment]
I meant what is in the `data` object.

Your data gets serialized when you save it to save space if possible. The original AS3 saves the data to AMF3 format, and HTML5 probably uses Haxe's native serialization. So you're probably serializing a function property of your object.

It could also be that there's an issue with OpenFL, but it's probably directly calling Haxe's `serialize`.

**Comment by chpla** [comment]
I get it. Here's the data object, serialized with Json.stringify:

{"_saved_configuration":{},"_accounts":[],"_so_ignored_accounts":[],"_cid":"product_new_html","_generation":"64"}

**Comment by chpla** [comment]
Little bit OT, but this makes me wonder -  where does openfl store this data anyway? A cookie? Local storage?

**Comment by MSGhero** [comment]
It uses `haxe.Serializer` directly rather than stringify, and it goes into local storage.

**Comment by chpla** [comment]
I used Cookie now and Json.stringify. No idea where haxe.Serializer saw Functions in my data object. So I guess the issue has been worked around, but I still don't think it makes much sense, that haxe.Serializer is complaining in this way. And it's certainly not consistent with the behavior of SharedObject in as3.

**Comment by MSGhero** [comment]
It works fine for me: http://try.haxe.org/#700F3

OpenFL does not use AMF3 encoding in the non-flash targets.

**Comment by chpla** [comment]
Well it may work for some objects (like yours), but not others (like mine)... unlike Json.stringify, which seems to be able to serialize my data object just fine (as seen above).

So it seems like this is perhaps more of an issue with haxe.Serializer. Or it's desired behavior, but in that case, what I don't understand is where that method sees any functions in my object, as there should be none and Json.stringify doesn't seem to see them as well.

**Comment by MSGhero** [comment]
But I used the same object you said that you used... Unless you haven't actually told us the object you're using, in which case please tell us exactly what you're trying to serialize and not the stringified output.

If there is a problem, it's with your code or with haxe and not OpenFL, though, regardless of what you're trying to do.

**Comment by chpla** [comment]
> If there is a problem, it's with your code or with haxe and not OpenFL, though, regardless of what you're trying to do.

Guess I'll have to agree.

**Comment by jgranick** [comment]
I think we'd have to see what you set `data` to, in order to see what Haxe is seeing here.

If your object has functions attached that Haxe serializer is unhappy with, why not save Haxe JSON on the shared object data? Then you get the same save mechanism, but still JSON like you wanted?
