### ISSUE TITLE
Stage3D requestContext3D signature missmatch

### ISSUE THREAD

**Issue by dschreck** [openfl/openfl#1189]
The first parameter on Stage3D.requestContext3D should be a string.

http://api.haxe.org/flash/display/Stage3D.html#requestContext3D
requestContext3D (?context3DRenderMode:String, ?profile:Context3DProfile):Void

http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/Stage3D.html#requestContext3D()
requestContext3D(context3DRenderMode:String = "auto", profile:String = "baseline"):void

vs:

http://api.openfl.org/openfl/display/Stage3D.html#requestContext3D
 requestContext3D (?context3DRenderMode:Context3DRenderMode, ?profile:Context3DProfile):Void

**Comment by jgranick** [comment]
Hey :smile:

We have our own special enum types, that convert to and from Strings. This means that we can strictly type our APIs (such as `requestContext3D` while also allowing String literals.

Both of these should work:

```haxe
stage3Ds[0].requestContext3D ("auto");
stage3Ds[0].requestContext3D (Context3DRenderMode.AUTO);
```

We could have used `public static inline var AUTO = "auto";` instead, and the above would work, but our abstract enums should allow more compact code, better performance and can be switched over

```haxe
switch (renderMode) {
    case AUTO:
    case SOFTWARE:
}
```

If you experience any issues with (what should be) valid code not compiling or giving you trouble, please let me know!

https://github.com/openfl/openfl/blob/develop/openfl/display3D/Context3DRenderMode.hx
