### ISSUE TITLE
DisplayObject pivot/anchor point

### ISSUE THREAD

**Issue by Misiur** [openfl/openfl#1190]
I was surprised to find lack of these, and lack of such feature request in the issues. I come from flambe background where it's just a matter of `Sprite#setAnchor` (https://aduros.com/flambe/api/flambe/display/Sprite.html#setAnchor). All I could find was this 3rd party library - https://github.com/yupswing/akifox-transform 

Is it lack of interest for such a feature, difficulty of implementing it, performance penalties, problems with portablility, or some other factor?

Sorry if this was already discussed, I didn't find any references.

**Comment by jgranick** [comment]
It's not added, because it's a simple thing to do:

```haxe
var sprite = new Sprite ();
bitmap.x = -bitmap.width / 2;
bitmap.y = -bitmap.height / 2;
sprite.addChild (bitmap);
sprite.rotation = 45;
```

No need for another library :smile:

**Comment by Misiur** [comment]
Oh. Should've thought of that. Thanks, and keep up the good work! (don't abandon us as flambe project did :( )

**Comment by jgranick** [comment]
Oh! I didn't know that Flambe wasn't still active. We've been going for more than six years, no plans to stop :smile:
