### ISSUE TITLE
WebGL Errors in BitmapData getTexture function (html5 target)

### ISSUE THREAD

**Issue by chpla** [openfl/openfl#1195]
Since upgrading to 4.0.* I'm having some serious problems with the rendering pipeline... the following error message keeps coming up in the console and things get really slow. Also, some of the visible BitmapData on screen looks corrupted in all sorts of ways.

WebGL: INVALID_VALUE: texImage2D: no canvas
252(index):1 [GroupMarkerNotSet(crbug.com/242999)!:A0DAB685D47F0000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.

**Comment by jgranick** [comment]
Do you have a small sample case we could use to replicate what you are seeing? We haven't seen this in our testing, but maybe your project triggers some unusual case in the renderer.

What OS, browser and version are you testing with? Thank you

**Comment by chpla** [comment]
It looks like I caused this by creating BitmapData instances while accidentally providing Floats as arguments... ugh. So, I guess this can be closed.
