### ISSUE TITLE
DisplayingABitmap doesn't display a bitmap for CPP (hardware = true)

### ISSUE THREAD

**Issue by MiltonW** [openfl/openfl#1196]
Lime 3.0.1/OpenFL 4.0.1

DisplayingABitmap sample doesn't display a bitmap for CPP target (neko/linux), when using hardware="true". Other targets work (including WebGL).

**Comment by rgsone** [comment]
Same problem here (same version and target Lime 3.0.1/OpenFL 4.0.1 - windows/neko)
Bitmap exist (have correct width + height) but not displaying.
Same problem when i test with FPS object.

**Comment by jgranick** [comment]
Would you both mind trying OpenFL 4.0.3 and Lime 4.0.3 that were just released? We fixed an issue that affected certain Android devices, it might be related?

**Comment by MiltonW** [comment]
Yes, works fine now on Linux. Thanks!

**Comment by jgranick** [comment]
Awesome to hear, thank you :smile:
