### ISSUE TITLE
Assets.getBitmapData not working?

### ISSUE THREAD

**Issue by madrazoman** [openfl/openfl#12]
In https://github.com/openfl/openfl/wiki/Transition-to-OpenFL
says "you can use the "openfl.Assets" like you would in NME".

However, if you change "DisplayingABitmap" sample as:
-Adding "import openfl.Assets"
-Replacing 
"var bitmap = new Bitmap (new Image (0, 0));" 
for
var bitmap = new Bitmap (Assets.getBitmapData ("assets/nme.png"));
(or
"var bitmap = new Bitmap (Assets.getBitmapData ("nme.png"));"
)

the bitmap is not displayed, and no error or warning is shown.

**Comment by dagnelies** [comment]
I fell in the same trap. Perhaps the error message could be more noob friendly by stating "... Please check your project.xml"
