### ISSUE TITLE
BitmapData.fillRect behavior

### ISSUE THREAD

**Issue by chpla** [openfl/openfl#1202]
In as3, when I do this:

myBitmapData.fillRect(myBitmapData.rect, 0);

the image content of myBitmapData gets cleared. In openfl, the above call doesn't seem to do anything by itself. Instead, to clear the image content, I first have to make the same call but with a non-zero value for color, as a workaround:

myBitmapData.fillRect(myBitmapData.rect, 0xFFFF0000);
myBitmapData.fillRect(myBitmapData.rect, 0);

**Comment by jgranick** [comment]
This appears to work for me, could you share more about what version you are using, what targets you are testing, and possibly share code for a simple example project that reproduces your problem? Thank you

**Comment by chpla** [comment]
I experienced the problem while trying to erase what was previously drawn with .draw() on a BitmapData object. The old image persisted when I did the .fillRect with zero as the color parameter.

**Comment by chpla** [comment]
Platform is OSX, browser is Chrome.

**Comment by jgranick** [comment]
This works for me:

```haxe
package;


import openfl.display.Bitmap;
import openfl.display.BitmapData;
import openfl.display.Sprite;


class Main extends Sprite {
	
	
	public function new () {
		
		super ();
		
		var sprite = new Sprite ();
		sprite.graphics.beginFill (0xFF0000);
		sprite.graphics.drawRect (0, 0, 100, 100);
		
		var bitmapData = new BitmapData (100, 100, true, 0);
		bitmapData.draw (sprite);
		
		bitmapData.fillRect (bitmapData.rect, 0);
		
		var bitmap = new Bitmap (bitmapData);
		addChild (bitmap);
		
	}
	
	
}
```

Perhaps this is an issue that was since resolved?

Thank you
