### ISSUE TITLE
Neko crashing without any errors

### ISSUE THREAD

**Issue by Misiur** [openfl/openfl#1204]
Basically if there are any runtime errors neko application window will simply close without any error messages. Here are my warnings, as far as I could google the AL message is simply about improper audio library closing so I guess that's unrelated.

> Export/windows/neko/debug/haxe/ApplicationMain.hx:200: characters 88-106 : Warning : Use programPath instead
> AL lib: (EE) alc_cleanup: 1 device not closed
> [Finished in 7.9s]

Windows 7 x64

> $ haxelib list
> hxcpp: [3.2.205]
> lime: 2.9.0 2.9.1 [3.0.0]
> openfl: 3.6.0 3.6.1 [4.0.0]
> $ haxe -version
> 3.3.0

**Comment by ibilon** [comment]
How are you launching, though the command line or an ide?

**Comment by Misiur** [comment]
Sublime text with haxe plugin. Without crash normal trace calls show up in my build result panel.

**Comment by ibilon** [comment]
Do you get an error message if you launch from the command line?

**Comment by Misiur** [comment]
> test@test-HP MINGW64 /d/Dev/Sea (master)
> $ openfl test neko
> Export/windows/neko/release/haxe/ApplicationMain.hx:200: characters 88-106 : Warning : Use programPath instead
> AL lib: (EE) alc_cleanup: 1 device not closed

Same result, split second of a window.

I'm testing with `trace(null + 0)` - compiles without errors yet I know will throw an exception in neko.

**Comment by jgranick** [comment]
Try `openfl test next -debug` from the command-line

**Comment by Misiur** [comment]
> test@test-HP MINGW64 /d/Dev/Sea (master)
> $ openfl test neko -debug
> Export/windows/neko/debug/haxe/ApplicationMain.hx:200: characters 88-106 : Warning : Use programPath instead
> AL lib: (EE) alc_cleanup: 1 device not closed
> 
> test@test-HP MINGW64 /d/Dev/Sea (master)

Same behaviour.

**Comment by jgranick** [comment]
This is totally up to Neko -- some errors might not result in a stack trace, or perhaps, you have a different Neko version on your system than we normally use (with Haxe 3.3?) and it behaves differently

**Comment by Misiur** [comment]
> test@test-HP MINGW64 /d/Dev/Sea (master)
> $ neko -version
> 2.1.0

I've tried directly:

```
package;

class Main
{
    public static function main() {
        trace(null + 1.0);
    }
}
```

> test@test-HP MINGW64 /d/Dev/Neko
> $ haxe -main Main -neko neko.n
> 
> test@test-HP MINGW64 /d/Dev/Neko
> $ neko neko.n
> Called from ? line 1
> Called from Main.hx line 6
> Uncaught exception - Invalid operation (+)
> 
> test@test-HP MINGW64 /d/Dev/Neko

Then I went to the build folder of my project and started it directly

> test@test-HP MINGW64 /d/Dev/Sea/Export/windows/neko/debug/bin (master)
> $ ./Sea.exe
> AL lib: (EE) alc_cleanup: 1 device not closed

However, when just clicking on executable, it showed console window with more info for a split second, so I tried calling it from windows command line, not mingw:

> D:\Dev\Sea\Export\windows\neko\debug\bin>Sea.exe
> Called from thx.fp._Map.Map_Impl_::$statics line 1
> Called from ApplicationMain::main line 143
> Called from ApplicationMain::create line 26
> Called from lime.app.Preloader::create line 58
> Called from openfl.display.Preloader::start line 93
> Called from NMEPreloader::onLoaded line 107
> Called from openfl.events.EventDispatcher::dispatchEvent line 95
> Called from openfl.display.DisplayObject::__dispatchEvent line 269
> Called from openfl.events.EventDispatcher::__dispatchEvent line 237
> Called from openfl.display.Preloader::display_onComplete line 129
> Called from lime.app.Preloader::start line 242
> Called from lime.app.Event_Void_Void::dispatch line 145
> Called from ApplicationMain::init line 87
> Called from ApplicationMain::start line 173
> Called from Type::createInstance line 109
> Called from DocumentClass::$init line 212
> Called from DocumentClass::new line 239
> Called from Main::new line 13
> Uncaught exception - Invalid operation (+)
> AL lib: (EE) alc_cleanup: 1 device not closed
> 
> D:\Dev\Sea\Export\windows\neko\debug\bin>

So I guess it's not openFL fault, maybe problem with stderr stream or something. When I'll find a solution I'll post it here.

**Comment by jgranick** [comment]
I'm going to close this issue, but I've been debating whether we should consider contributing to Neko, and performing nightly builds on our build servers. This might be a valuable improvement :smile:
