### ISSUE TITLE
TextField can't embed fonts on Android target

### ISSUE THREAD

**Issue by man2** [openfl/openfl#1215]
Code 
```
var font:Font = Assets.getFont("assets/regular_font.ttf");
var format:TextFormat = new TextFormat(font.fontName, 16,0xffffff);
_textField = new TextField();
_textField.defaultTextFormat = format;
_textField.embedFonts = true;
_textField.text = "hello world";
Lib.current.addChild(_textField);
```

lime git
openfl3 git branch
haxe 3.2.1

It just loaded default font. Font embed works well on mac target

**Comment by man2** [comment]
It appears that font.fontName returns gibberish on Android target

**Comment by jgranick** [comment]
What version of the Android NDK are you using to build? Using a newer one, in my testing, appeared to fix the unicode implementation and resolve this problem

**Comment by man2** [comment]
okay, can I use latest NDK r12b?

**Comment by jgranick** [comment]
Yes, so long as you have this patch in "android-toolchain.xml"

https://github.com/HaxeFoundation/hxcpp/commit/25247b443474ef5323ae299e94bb7a2674a4fa0d

NDK v11 seems to work without this fix

**Comment by man2** [comment]
closing this, not directly an openfl issue

**Comment by xoopx** [comment]
I got same problem with ndk13. font.fontName returns gibberish.
