### ISSUE TITLE
TextField does not render htmlText correctly

### ISSUE THREAD

**Issue by vroad** [openfl/openfl#1217]
This picture is screenshot of starling-samples.
On Flash htmlText renders correctly, but not on native and html5.

Flash:
![demo_web_flash](https://cloud.githubusercontent.com/assets/396351/17248109/12157c82-55d3-11e6-8189-80d861068cbf.png)

Native targets:
![demo_web_native](https://cloud.githubusercontent.com/assets/396351/17248165/844dfbe4-55d3-11e6-910f-b8ce27afe3b1.png)

colors are not used, and some characters are missing.

I tried html5 and got infinite loop with dom mode. In other modes I didn't get crash, but got the same kind of output as native.

https://github.com/openfl/starling
https://github.com/openfl/starling/blob/869b48aadc83ccc9fee6d4e8ca5cfbb891d57bfa/samples/demo/src/scenes/TextScene.hx#L49-L54
https://github.com/openfl/starling/blob/869b48aadc83ccc9fee6d4e8ca5cfbb891d57bfa/starling/text/TrueTypeCompositor.hx#L89

**Comment by jgranick** [comment]
This works properly in the current demo :smile:
