### ISSUE TITLE
Android Back Button detection not working

### ISSUE THREAD

**Issue by man2** [openfl/openfl#1218]
@jgranick 
Is there a new trick to get android back button detection working? Right now, the application is just closed when I pressed back button.

 can't find it anywhere on openfl-samples and tests

Tried with 
```
stage.addEventListener(KeyboardEvent.KEY_DOWN, onKeyboardDown);
private function onKeyboardDown(e:KeyboardEvent):Void 
	{
		if (e.keyCode == openfl.ui.Keyboard.ESCAPE)
		{
			e.stopImmediatePropagation();
		        doSomething(); // not working
		}
	}
```
is not working on android target. mac target is working just fine

**Comment by man2** [comment]
bump @jgranick 
any clues please?

**Comment by man2** [comment]
from adb log i got this when pressing back button on android

Key down dispatch to org.libsdl.app.SDLSurface{41f92438 VFE..... .F...... 0,0-540,960}, event = KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=158, metaState=0, flags=0x48, repeatCount=0, eventTime=3315193, downTime=3315193, deviceId=3, source=0x101 }

is there supposed to be a new way of detecting android back button

**Comment by man2** [comment]
got the answer here
https://github.com/openfl/openfl/issues/827

should be better documented, at least being used in openfl-samples. I'm closing this issue now

**Comment by jgranick** [comment]
Does it equal `lime.ui.KeyCode.APP_CONTROL_BACK`?

**Comment by man2** [comment]
yes exactly

**Comment by man2** [comment]
it doesn't work anymore on lime 3.0.3. is there any changes lately?

**Comment by man2** [comment]
@jgranick

**Comment by man2** [comment]
error is on my code.
