### ISSUE TITLE
new openfl version(4.0.2) GL issues

### ISSUE THREAD

**Issue by lovedna** [openfl/openfl#1220]
i use gl to draw a picture,openfl version(3.6.1) is ok
the new version picture's color looks like white
this issue on android and windows target , neko and html5 target is ok.

**Comment by jgranick** [comment]
Could you share more code so we can try and reproduce what you are seeing?

**Comment by lovedna** [comment]
//code here:

package;
import openfl.Lib;
import openfl.display.OpenGLView;
import openfl.events.Event;
import openfl.geom.Rectangle;
import openfl.gl.GL;
import openfl.gl.GLBuffer;
import openfl.gl.GLProgram;
import openfl.gl.GLShader;
import openfl.utils.Float32Array;
import openfl.utils.Int16Array;
//neko and html5 target can see a colored triangle
//windows and android target can see nothing
class TestGL
{
	private var _vertBuffer:GLBuffer;
	private var _indexBuffer:GLBuffer;
	private var _program:GLProgram;
	private var _positionLocation:Int;
	private var _colorLocation:Int;
	public function new() 
	{
		var view:OpenGLView = new OpenGLView();
		view.addEventListener(Event.ADDED_TO_STAGE, view_addedToStage);
		Lib.current.addChild(view);
	}
	
	private function view_addedToStage(e:Event):Void 
	{
		var view:OpenGLView = cast e.target;
		view.removeEventListener(Event.ADDED_TO_STAGE, view_addedToStage);
		var data:Array<Float> =
		[
			-1, -1, 0, 1, 0, 0, 1,
			1, -1, 0, 0, 1, 0, 1,
			0, 1, 0, 0, 0, 1, 1
		];
		var indexs:Array<Int> =
		[
			0,1,2
		];
		_vertBuffer = GL.createBuffer();
		GL.bindBuffer(GL.ARRAY_BUFFER, _vertBuffer);
		GL.bufferData(GL.ARRAY_BUFFER, new Float32Array(data), GL.STATIC_DRAW);
		_indexBuffer = GL.createBuffer();
		GL.bindBuffer(GL.ELEMENT_ARRAY_BUFFER, _indexBuffer);
		GL.bufferData(GL.ELEMENT_ARRAY_BUFFER, new Int16Array(indexs), GL.STATIC_DRAW);
		var str:String = "
			precision mediump float;
			attribute vec3 position;
			attribute vec4 color;
			varying vec4 vcolor;
			void main(void){
				gl_Position = vec4(position, 1.0);
				vcolor = color;
			}
		";
		var vs:GLShader = GL.createShader(GL.VERTEX_SHADER);
		GL.shaderSource(vs, str);
		GL.compileShader(vs);
		str = "
			precision mediump float;
			varying vec4 vcolor;
			void main(void){
				gl_FragColor = vcolor;
			}
		";
		var fs:GLShader = GL.createShader(GL.FRAGMENT_SHADER);
		GL.shaderSource(fs, str);
		GL.compileShader(fs);
		_program = GL.createProgram();
		GL.attachShader(_program, vs);
		GL.attachShader(_program, fs);
		GL.linkProgram(_program);
		_positionLocation = GL.getAttribLocation(_program, "position");
		_colorLocation = GL.getAttribLocation(_program, "color");
		view.render = _render;
	}
	private function _render(rect:Rectangle):Void
	{
		GL.clearColor(1, 1, 1, 1);
		GL.clearDepth(1);
		GL.colorMask(true, true, true, true);
		GL.clear(GL.COLOR_BUFFER_BIT | GL.DEPTH_BUFFER_BIT);
		GL.viewport(0, 0, Std.int(rect.width), Std.int(rect.height));
		GL.useProgram(_program);
		GL.bindBuffer(GL.ARRAY_BUFFER, _vertBuffer);
		var stride:Int = (3 + 4) * 4;
		var offset:Int = 0;
		GL.vertexAttribPointer(_positionLocation, 3, GL.FLOAT, false, stride, offset);
		GL.enableVertexAttribArray(_positionLocation);
		offset += 3 * 4;
		GL.vertexAttribPointer(_colorLocation, 4, GL.FLOAT, false, stride, offset);
		GL.enableVertexAttribArray(_colorLocation);
		GL.bindBuffer(GL.ELEMENT_ARRAY_BUFFER, _indexBuffer);
		GL.drawElements(GL.TRIANGLES, 3, GL.UNSIGNED_SHORT, 0);
		GL.disableVertexAttribArray(_positionLocation);
		GL.disableVertexAttribArray(_colorLocation);
		GL.bindBuffer(GL.ARRAY_BUFFER, null);
		GL.bindBuffer(GL.ELEMENT_ARRAY_BUFFER, null);
		GL.useProgram(null);
	}
}
