### ISSUE TITLE
ByteArray.fromArrayBuffer and fromBytes does not check if input bytes is null

### ISSUE THREAD

**Issue by vroad** [openfl/openfl#1221]
Since `ByteArray`implicitly convert from `Bytes` with `@:from` meta, this may lead to strange error because it could allow you to create `ByteArray`with null `ByteArrayData`, which usually doesn't happen. I've got null reference exception with `openfl.net.URLLoader`, for example. URLLoader does not check if the result of `Bytes.readFile()` is null.

https://github.com/openfl/openfl/blob/636b7fca98b6fbec9c7d6c861dc2a427c546e11a/openfl/utils/ByteArray.hx#L74
https://github.com/openfl/openfl/blob/636b7fca98b6fbec9c7d6c861dc2a427c546e11a/openfl/utils/ByteArray.hx#L97
https://github.com/openfl/openfl/blob/636b7fca98b6fbec9c7d6c861dc2a427c546e11a/openfl/utils/ByteArray.hx#L691
https://github.com/openfl/openfl/blob/636b7fca98b6fbec9c7d6c861dc2a427c546e11a/openfl/utils/ByteArray.hx#L719

https://github.com/openfl/openfl/blob/15be4f5bd5eecbd8f0074ddfe966564d99ee1dc0/openfl/net/URLLoader.hx#L108-L109

**Comment by jgranick** [comment]
Should have been resolved a while ago, thank you 😄
