### ISSUE TITLE
Nearest-neighbor and graphics.beginBitmapFill()

### ISSUE THREAD

**Issue by Rinzylal** [openfl/openfl#1222]
I am a bit new to OpenFL so it might be that I am doing something wrong. Using the latest version (4.0.3) of OpenFL, I am trying to draw an upscaled pixel-art sprite. The code I am using:
```
graphics.clear();
graphics.beginBitmapFill(bitmapData, null, false);
graphics.drawRect(0, 0, bitmapData.width, bitmapData.height);
graphics.endFill();
```
The third argument of the `beginBitmapFill` method turns smoothing on or off. Yet the sprite still looks blurry and not the way it should look if it was using nearest-neighbor interpolation.

I was not able to reproduce this issue on OpenFL version 3.6.1 and Lime 2.9.1.

**Comment by wildfireheart** [comment]
Same issue on macOS native

**Comment by ibilon** [comment]
Is it also blurry if you compile with `openfl test mac --window-hardware=false`?

**Comment by wildfireheart** [comment]
Somehow it doesn't want to let me compile with `--window-hardware=false` option, compiler says that option doesn't exist, do I have something set wrong? I'm using latest haxelib version.

**Comment by wildfireheart** [comment]
Yes. 
Using Shape & graphics.beginBitmapFill():
![shape beginbitmapfill](https://cloud.githubusercontent.com/assets/11695359/17505484/baa4dc54-5e01-11e6-9c82-2ba6d25b99a7.png)
Visible boundaries are individual shapes.

Using Bitmap & bitmapData.copyPixels():
![bitmap copypixels](https://cloud.githubusercontent.com/assets/11695359/17505485/bad10bd0-5e01-11e6-9ca1-44f2db620f04.png)
which is expected result.

**Comment by mayakwd** [comment]
Is it on any platform or you means html5?
