### ISSUE TITLE
ATF wrong decoding from byteArray

### ISSUE THREAD

**Issue by loudoweb** [openfl/openfl#1229]
I try to upload an **ATF** file from `Texture.uploadCompressedTextureFromByteArray()`but I've got wrong error throwing. It says that my ATF file is a cubemap but I've check with _atfinfo command line_ and I can confirm that the file is not a cubemap.

So, I've check further how the decoding worked and all values except the signature are wrong (version, cubemap, format, width and height).

I think we can learn from this : https://github.com/away3d/away3d-core-openfl/blob/4916415870c8cb4e566363c95074c8f7c969c653/away3d/textures/ATFData.hx

I made quick changes on the decoder with the code from away3d and I've got correct values. I'll try to make a pull request but I don't know how far I can get.

**Comment by loudoweb** [comment]
I've made some progress on ATF implementation that you can find here : https://github.com/loudoweb/openfl/commit/5abfa8052d6e2f59854672310f5831a9e6ae7348

**All headers are correctly read now (version, format, type, length, width, height...)!**

Sadly, I can't make it work after. When I load the data from the JPEGXR to the Texture with uploadFromByteArray() it crashes. Is there something I've missed?
I tried with RGBA88888 atf format.

**Comment by jgranick** [comment]
I've been reading about ATF, where does JPEG XR come in?

http://wiki.starling-framework.org/manual/atf_textures

**Comment by loudoweb** [comment]
I see some mentions about JPEG XR in the user guide. http://www.adobe.com/devnet/flashruntimes/articles/atf-users-guide.html

Also, on texturePacker I can set JXR compression for ATF-RGBA8888 or ATF-DXT5.

Anyway, I'll be happy if I can use ATF with openfl/cpp (with or without JXR). The headers works now, we just need to upload the texture from the ByteArray...I guess.

**Comment by hklindworth** [comment]
ATF with DXT1/DXT5 block compression and without JPEG-XR+LZMA should work now. This is imho also the most important format as it reduces texture size on GPU by 75% or 87.5% for DXT1.
If you care about filesizes you can compress the atf with gzip afterwards.
