### ISSUE TITLE
BitmapData.fromBytes issue on html5 target

### ISSUE THREAD

**Issue by lovedna** [openfl/openfl#1236]
i use URLLoader load png file then use BitmapData.fromBytes  to get a BitmapData
js and image in the same url domain
on pc
 Safari throw an error "Cross-origin image load denied by Cross-Origin Resource Sharing police."
 Chrome not has this error
on mobile
android  is fine on Chrome 
ios Chrome and Safari may be have this error(i don't know how to get console view),and i can't see the image show.

how do i do?
 is there a crossdomain.xml file to allow js load image from bytes?or has other solution?

**Comment by jgranick** [comment]
Have you tried using openfl.display.Loader? It's similar, you just listen to the "contentLoaderInfo" property, but loads images

**Comment by lovedna** [comment]
useing openfl.display.Loader is fine
but i need use URLLoader load bytes first,because i saved custom data into png file.

or openfl.display.Loader read contentLoaderInfo.bytes but the value is null.

so now i use URLLoader load image file bytes first ,then use Loader to load image Bytes.  make loading time twice.
i think this is not a good solution.

**Comment by lovedna** [comment]
i think this fix my issue
https://github.com/openfl/lime/commit/df31f15be5b9da247c97c9933d98525673c1d626
