### ISSUE TITLE
Android mask not displaying

### ISSUE THREAD

**Issue by danielmar** [openfl/openfl#1247]
It seems there's an issue with masks on android:

Here's latest OpenFL 4.0.3 from haxelib:
![screenshot_2016-08-21-11-08-06](https://cloud.githubusercontent.com/assets/2474262/17836186/98cec3c6-6791-11e6-949d-5c64fa0ce47f.png)

And current develop branch:
![screenshot_2016-08-21-11-18-00](https://cloud.githubusercontent.com/assets/2474262/17836196/f4279fea-6791-11e6-9430-3edc25617709.png)

	private function setupMask():Void {
		_mask.graphics.clear();
		_mask.graphics.beginFill(0x000000);
		_mask.graphics.drawRect(0, 0, _fillWidth*(_maskTo - _maskFrom), _fillHeight);
		_mask.graphics.endFill();
		_mask.x = _fillWidth*_maskFrom;
		_fill.mask = _mask;
		addChild(_mask);
	}

	private function updateMask(perc:Float):Void {
		_mask.scaleX = perc;
	}

**Comment by jgranick** [comment]
I'm having difficulty reproducing this. Is it possible that you are getting bad values, or that it is related to changes in event dispatching, or the ADDED_TO_STAGE bug that was fixed?

Here is my sample case:

```haxe
package;


import openfl.display.Sprite;
import motion.easing.Linear;
import motion.Actuate;


class Main extends Sprite {
	
	
	public function new () {
		
		super ();
		
		var background = new Sprite ();
		background.graphics.beginFill (0xFF0000);
		background.graphics.drawRect (0, 0, stage.stageWidth, stage.stageHeight);
		addChild (background);
		
		var mask = new Sprite ();
		mask.graphics.copyFrom (background.graphics);
		addChild (mask);
		
		mask.scaleX = 0;
		
		background.mask = mask;
		
		Actuate.tween (mask, 20, { scaleX: 1 }).ease (Linear.easeNone);
		
	}
	
	
}
```

It works on GL on the desktop, I did not test on Android, but it should behave the same.

**Comment by danielmar** [comment]
It seems that the issue has to do with Android scaling:
if window's resizable flag is false (like in my game) the mask does not work properly unless I add an extra added_to_stage event. here's the snippet I used for testing:

https://gist.github.com/danielmar/e8279de77906bbda8dc59a65067e2786

**Comment by danielmar** [comment]
Heya!
Looks likebd67dcaf5c0ee9f87a14312afa1dc30d0870ffd9 fixes this issue.

**Comment by jgranick** [comment]
Awesome! Please let me know if you ever have issues with this again :shipit:
