### ISSUE TITLE
Sprite's stage member is null

### ISSUE THREAD

**Issue by danielmar** [openfl/openfl#1248]
Testing the develop branch, a sprite's stage is member is null after the ADDED_TO_STAGE event is trigged:

	public function new() {
		super();
	        ...
		addEventListener(Event.ADDED_TO_STAGE, handleStage);
	}

	private function handleStage(e:Event):Void {
		removeEventListener(Event.ADDED_TO_STAGE, handleStage);
		stage.addEventListener(MouseEvent.MOUSE_DOWN, handleOverlay); <- null
	}

Not sure if relevant, but this sprite's ADDED_TO_STAGE event is triggered before it's parent's ADDED_TO_STAGE event.

Reproducted on HTML5 and Android targets.

**Comment by jgranick** [comment]
Thanks for the report!

It appears to be working correctly with this test:

```haxe
package;


import openfl.display.Sprite;
import openfl.events.Event;


class Main extends Sprite {
	
	
	public function new () {
		
		super ();
		
		var sprite = new Sprite ();
		var sprite2 = new Sprite ();
		
		sprite.addEventListener (Event.ADDED_TO_STAGE, function (_) {
			
			trace ("sprite added to stage");
			trace (sprite.stage);
			
		});
		
		sprite2.addEventListener (Event.ADDED_TO_STAGE, function (_) {
			
			trace ("sprite2 added to stage");
			trace (sprite2.stage);
			
		});
		
		sprite.addChild (sprite2);
		addChild (sprite);
		
	}
	
	
}
```

It was dispatching `ADDED_TO_STAGE` events three times, instead of two, before the latest fix. Now it seems to look correct

**Comment by danielmar** [comment]
Thanks for the fix!

**Comment by vizanto** [comment]
Nested display objects still seem to have a null stage
