### ISSUE TITLE
Compile time legacy 2 secs vs next 7 secs

### ISSUE THREAD

**Issue by mastef** [openfl/openfl#1249]
Since we spoke about this on Slack, I'd document the issue and benchmark here. Benchmark was run on `DisplayingABitmap` demo from `openfl-samples`

On windows compare
`Measure-Command {lime build neko --times -Dmacro-times -Dlegacy}`
`Measure-Command {lime build neko --times -Dmacro-times}`

On mac/unix compare
`time lime build neko --times -Dmacro-times -Dlegacy`
`time lime build neko --times -Dmacro-times`

Results :
Macro times : `legacy 0.9 secs` vs `next 3.5 secs`
Execution times : `legacy 2.2 secs` vs `next 7.5 secs`

Note :
One feedback was to set a `HXCPP_COMPILE_CACHE` directory in `.hxcpp_config.xml` but the results are time-wise still the same. Another thing that vastly improves the difference is using the completion server, which however seems to be broken atm.

Screenshot of results :
![Screenshot of legacy vs next compile times](http://new.tinygrab.com/6c91891dfedfd4c5a2da71f2fbf73a525608621da9.png)

**Comment by jgranick** [comment]
Further discussion here: https://github.com/openfl/openfl/issues/1395
