### ISSUE TITLE
TextField don't add newline on Enter-key

### ISSUE THREAD

**Issue by r3d9u11** [openfl/openfl#1254]
Hi. I have some problem with openfl.text.TextField: it don't add new lines on Enter (for neko -64 and cpp -64 targets)

haxe: 3.2.1
neko: 2.1.0
openfl-html5: 1.0.5
openfl-native: 1.4.0
openfl-nativedialog: 1.2.0
openfl-ouya: 1.0.2
openfl-samples: 4.0.0
openfl: 4.0.3
lime-tools: 1.5.7
lime: 3.0.3

os: Linux Mint 18 x64

**example**
Main.hx

```
package;

import openfl.display.*;
import openfl.text.*;

class Main extends openfl.display.Sprite {
    public function new () {
        super();

        var tf:TextField = new TextField();
        tf.width = 300;
        tf.height = 300;
        tf.border = true;
        tf.multiline = true;
        tf.selectable = true;
        tf.type = TextFieldType.INPUT;

        this.addChild(tf);
    }
}
```

Thanks

**Comment by MSGhero** [comment]
Textfields are in a weird, incomplete spot right now. Some of us are fixing things, but I haven't had the time recently to work on it. Input text was next on my list, though.

**Comment by r3d9u11** [comment]
Thank you for your answer, I hope that solution will be found.

**Comment by ibilon** [comment]
Added a commit that helps, the newline is added, and you can write on the next line.
But the caret doesn't appear until a non space is added on the line (beside the first line).
And maj+up and maj-down aren't supported yet.

**Comment by r3d9u11** [comment]
Work's fine now! Many thanks for fix!
