### ISSUE TITLE
WebGL lots of getError calls

### ISSUE THREAD

**Issue by Misiur** [openfl/openfl#1255]
I opened BunnyMark and CPU profile in chrome:
![](http://i.imgur.com/5v98Lg7.png)

I don't have any errors in the console, just curious if that's normal. If not, can this be caused by my graphics card model? How can I see what kind of errors I'm receiving?

**Comment by jgranick** [comment]
There are no GL errors, but the wrapper seems to be expensive to always use on -debug, so I am making it require `-Dwebgl-debug`, otherwise it's off by default.

https://github.com/openfl/lime/commit/7ba22eb9aefec4214c5763a68a6c8892a8b139ae

Thanks for your help :smile:
