### ISSUE TITLE
Flash TileMap + Smoothing does not smooth

### ISSUE THREAD

**Issue by dyarosla** [openfl/openfl#1257]
When the smoothing flag is true, the bitmapData.draw call currently uses a non-smoothed source.

[FlashTilemap](https://github.com/openfl/openfl/blob/c4fc773cb5b3194edb798da04959f7d814d0c5a4/openfl/_internal/renderer/flash/FlashTilemap.hx) needs to set `bitmap.smoothing = smoothing;` after the `bitmap.bitmapData = sourceBitmapData;` line. 

As is, Flash internally sets bitmap.smoothing to false after every call to bitmap.bitmapData =, including `bitmap.bitmapData = sourceBitmapData;`

**Comment by jgranick** [comment]
Fixed :smile: https://github.com/openfl/openfl/commit/62de51a5a322660acbc07c08d132c68be7d9a55f
