### ISSUE TITLE
openfl.net.FileReference error

### ISSUE THREAD

**Issue by r3d9u11** [openfl/openfl#1258]
Hi. I have some error, when I try to open file dialog.

Haxe: 3.2.1
Neko 2.1.0
Haxelib:

```
   actuate: 1.8.6 [1.8.7]   
   hxcpp: 3.2.205 [3.3.49]
   openfl-html5: [1.0.5]
   openfl-native: [1.4.0]
   openfl-nativedialog: [1.2.0]
   openfl-ouya: [1.0.2]
   openfl-samples: [4.0.0] 3.3.1
   openfl: 4.0.3 [4.1.0] 3.6.1
   lime-samples: [2.6.0]
   lime-tools: [1.5.7]
   lime: 2.9.1 3.0.3 [3.1.0]
```

OS: Linux Mint 18 x64

Main.hx:

```
package;

import openfl.events.*;
import openfl.display.*;
import openfl.net.FileFilter;
import openfl.net.FileReference;

class Main extends Sprite {
    public function new () {
        super();
        this.onLoadProjBtnClick();
    }

    function onLoadProjBtnClick () : Void {
        var loadRef:FileReference = new FileReference();
        loadRef.browse([new FileFilter('XML', '*.xml')]);
        loadRef.addEventListener(Event.SELECT, function(e:Event) cast(e.target, FileReference).load());
        loadRef.addEventListener(Event.COMPLETE, function(e:Event) trace('selected: ${e.target.data}'));
    }
}
```

If target is neko, then I have error after launching compiled program:

```
An exception occured in a neko Thread :
./lime@lime_file_dialog_open_file
```

If target is cpp, then nothing happens: have no errors, but and the dialog doesn't displays.

Thanks.

**Comment by MSGhero** [comment]
In flash, the file reference object has to be a class-level variable. If it's a local variable like yours, the variable loses scope once the function ends, and the request is not followed through. 

Maybe the behavior is the same on the other targets.

**Comment by r3d9u11** [comment]
Ok, I changed example (if I correctly understand):
```
package;

import openfl.events.*;
import openfl.display.*;

import openfl.net.FileFilter;
import openfl.net.FileReference;

class Main extends Sprite {
	var loadRef:FileReference = new FileReference();
	
	public function new () {
		super();
		
		loadRef.browse([new FileFilter('Stablexui XML', '*.xml')]);
		loadRef.addEventListener(Event.SELECT, function(e:Event) cast(e.target, FileReference).load());
		loadRef.addEventListener(Event.COMPLETE, function(evt:Event) trace('selected: ${evt.target.data}'));
	}
}
```

But this changes have no effect. I have error
```
An exception occured in a neko Thread :
./lime@lime_file_dialog_open_file
```

**Comment by MSGhero** [comment]
Ok that's an actual error then it seems.

**Comment by jgranick** [comment]
I forgot --

Native file dialog is disabled on Linux right now, we have only GTK support in the sub-library we use for dialog boxes, but the method of including GTK references to build it seemed bad for running on a system that might not have GTK... or a different version of GTK. I do not want to have a problem with Lime projects not running at all on systems that don't match this suitably.

**Comment by r3d9u11** [comment]
Which version needed for this functions? Mate (DE of Linux Mint) based on Gtk2

**Comment by jgranick** [comment]
We just replaced our FileDialog code in Lime, it worked for me in Linux now :smile:

**Comment by r3d9u11** [comment]
many thanks!
