### ISSUE TITLE
FlxText Line Spacing Inconsistency

### ISSUE THREAD

**Issue by pizzamakesgames** [openfl/openfl#1263]
This has been identified as an OpenFL issue since it's fixed by switching from next to legacy. Sorry if this is too much of an assumption to file an issue.

![Issue](http://i.imgur.com/idmgfrV.png)
The space between line 1 and 2 is smaller than the other ones. Visible escape character at the end.

When using FlxText with the next branch of OpenFL, the spacing between the lines of text is consistently off by some pixels. Divided by the game's scale factor, it's 3 pixels of line space for the first, then 4 twice, with this pattern repeating for any more lines. 

![Pattern](http://i.imgur.com/LwCx1iS.png)

The game runs at x4 scaling, so it can't be an imperfect scaling problem. I'm experiencing the issue using a small pixel font with a letter size of 5x6 pixels at size 16. If you want to reproduce the issue, here's a dropbox link of the .ttf and the code used: [SkullzFontv130_FF.ttf](https://www.dropbox.com/s/bb3cy02ec9lvez2/SkullzFontv130_FF.ttf?dl=0)

`var newtext = new FlxText(0, 0, 180, [for (i in 0...5) "XXXXXXX"].join("\n"), 16, true);
newtext.font = "assets/fonts/SkullzFontv130_FF.ttf";
add(newtext);
`

For some fonts, it seems to be fine, especially bigger ones. The default font of Flixel does not have this issue, though I had a double-sized version of the above font, with reversed line space inconsistency. None of this seems to be present in OpenFL legacy. I'd just switch, though I need to use next in order to avoid [these two](http://community.openfl.org/t/sound-issue-al-lib-ee-alc-cleanup-1-device-not-closed/7047) [sound issues](http://community.openfl.org/t/sound-hx-118-error-could-not-load-assets-music-mysound-ogg/7201).

Further, using next, I'm able to use the addon class FlxTypeText and change it's line spacing with the leading value of textField.TextFormat. Using legacy, applying a TextFormat to an FlxTypeText object does not change it's leading. For regular FlxText, changing it's leading using TextFormat works for both legacy and next.

One last thing. The escape character \r does get drawn as a blank space in legacy, while it gets drawn as one of those big missing character rectangles, visible in the first screenshot, for next. A way to also have it be blank in next would be great.

**Comment by MSGhero** [comment]
If you're not testing on the latest version of OpenFL, try that first since there have been a few fixes since 3.6.1.

If you want, you can manually merge #1066, #1094, and #1186 and see if anything changes. These don't fix input text (they might break them), but that needs to be handled these three issues have been merged.

**Comment by pizzamakesgames** [comment]
I'd love to use the latest version of OpelFL but haxeflixel is telling me:
C:/HaxeToolkit/haxe/lib/flixel/git/flixel/system/macros/FlxDefines.hx:80: characters 48-67 : Please run 'haxelib set openfl 3.6.1' (Flixel is currently incompatible with OpenFL 4.0.0 or newer).

How would I get to use the latest version of OpenFL? It'd be great if this issue would've been fixed since.

**Comment by MSGhero** [comment]
Use OpenFL and don't use flixel. If this issue does not exist on the dev branch of OpenFL, then it's already been fixed.

**Comment by pizzamakesgames** [comment]
That's a possibility, thanks!

**Comment by pizzamakesgames** [comment]
Since the issue persists on a flash build, it's my understanding that it's not related to OpenFL. Additionally, I've found the cause and a workaround. The font I used was simply too small. By increasing it's size times 2 and adjusting the font size of the FlxText object from 8 to 16, the lines space stays consistent. With that, I declare this issue closed!
