### ISSUE TITLE
[hx 3.2.1, openfl 4.1.0, lime 3.1.0, munit 2.1.2] Can't test openfl Tile or its inheritor with munit for -as3 target

### ISSUE THREAD

**Issue by wolfhoundgelert** [openfl/openfl#1265]
https://github.com/wolfhoundgelert/openfl_and_munit-test

It's ok:
haxelib run munit test -neko

It's not working:
haxelib run munit test -as3

haxe -main TestMain -lib munit -lib hamcrest -lib openfl -lib lime -cp src -cp test -swf-version 11 -swf build/as3_test.swf
HaxeWrapper.hx:73: c:\haxetoolkit\haxe\lib/openfl/4,1,0/openfl/display/IBitmapDrawable.hx:16: characters 8-66 : Type not found : RenderSession
HaxeWrapper.hx:73: test/TestMain.hx:16: lines 16-81 : Defined in this class
HaxeWrapper.hx:73: c:\haxetoolkit\haxe\lib/openfl/4,1,0/openfl/_internal/renderer/AbstractMaskManager.hx:14: characters 9-41 : Type not found : RenderSession
HaxeWrapper.hx:73: test/TestMain.hx:16: lines 16-81 : Defined in this class
HaxeWrapper.hx:73: c:\haxetoolkit\haxe\lib/openfl/4,1,0/openfl/_internal/renderer/cairo/CairoMaskManager.hx:17: lines 17-21 : Type not found : RenderSession
Error: Error compiling hxml for as3
Target as3 C:\d\workspace\repos\openfl_and_munit-test\build\as3_test.swf

**Comment by wolfhoundgelert** [comment]
Explanation from @slavara:

When we assemble openfl project on flash target it uses `IBitmapDrawable` from flash platform.
When we start munit tests on flash target it uses `openfl.display.IBitmapDrawable`, which contains unappropriated for flash code - e.g. `RenderSession`.
We can't use `--remap openfl:flash` because `openfl.display` package contains classes aren't represented on flash platform.

**Comment by jgranick** [comment]
You can use `openfl display flash` on a project to see an example of what we use to compile. The Flash target (particularly) gets a set of extern classes when building.

I wish that there was a way to add proper OpenFL support to munit. I used to use a `-cmd` to fool it into running builds, but this no longer works.

In our tests, I have to `openfl build flash && openfl build html5` before running `haxelib run munit test`

https://github.com/openfl/openfl/blob/develop/tests/unit/run.bat

**Comment by wolfhoundgelert** [comment]
Thanks a lot, Joshua!
