### ISSUE TITLE
Runtime crash with Main that doesn't extend DisplayObject

### ISSUE THREAD

**Issue by Gama11** [openfl/openfl#1269]
```haxe
class Main {}
```

Compiling this to Neko, the application crashes immediately on startup with `AL lib: (EE) alc_cleanup: 1 device not closed`.

Legacy had similar issues:

```
Called from C:\HaxeToolkit\haxe\std/neko/_std/Type.hx line 103
Called from ApplicationMain.hx line 119
Called from openfl/_legacy/Lib.hx line 122
```

In the case of legacy, the macro that builds `DocumentClass` fails, leading to a missing constructor, which makes `Type.createInstance()` fail.

I haven't really looked into it the Next / OpenFL 4 crash, but I assume that similar assumptions are being made, since adding `extends openfl.display.DisplayObject` fixes the issue.

I assume that `Main` classes that don't extend a `DisplayObject` are simply not supported. In that case, this should be caught at compile time and output a helpful error message, like `Main must extend openfl.display.DisplayObject` or something like that, instead of failing at runtime.

**Comment by ibilon** [comment]
You don't need to extend anything special,
but the tools assume they'll found an entry point, either a static main or a constructor (explicit, or implicit for subclasses).

**Comment by Gama11** [comment]
I see. That should still be possible to verify at compile-time.

**Comment by ibilon** [comment]
https://github.com/openfl/openfl/commit/6c619506e85697419dab3e2c69e52de55eb4922d correctly fixes it at compile time and doesn't add a global try/catch around the user code.

**Comment by Gama11** [comment]
Awesome! 👍
