### ISSUE TITLE
Feature request: implement bitmapData.getTexture() for flash target

### ISSUE THREAD

**Issue by Beeblerox** [openfl/openfl#1270]
I'd like to add functionality to `BitmapData` class to make it easier to manage textures in stage3d mode - just like openfl does it on native targets: bitmaps keep tracking info about its modifications, and if it had been modified then it regenerates textures. 
I know i could write my own wrapper for `BitmapData` or even extend it with some hacking into asset management system, but i'm not sure if it's a good idea.
So i'd like to have such feature on flash target on openfl level. And i'm asking if anyone is interested in such thing.
if you accept to have such feature in openfl core, then i would be glad to prepare PR for it.

feel free to close this issue if you think that it doesn't deserve to be here.

**Comment by ibilon** [comment]
So adding something like a `onModification` signal on all target including flash? (if I understand correctly)

Joshua isn't a fan of modifying the public api of flash classes, (which is a valid position)
but adding it as private, so needing @:privateAccess, could be ok? cc @jgranick

I wonder how the native renderer deal with this, the use case is pretty similar.

**Comment by Beeblerox** [comment]
basically i'd like to have something like this in `openfl.display.BitmapData`:
```
public function getTexture(context:Context3D):Texture
{
	if (_dirty)
	{
		if (_texture != null)
		{
			_texture.dispose();
		}
			
		_texture = context.createTexture(powOfTwo(width), powOfTwo(height), Context3DTextureFormat.BGRA, false);
		_texture.uploadFromBitmapData(this);
	}
		
	_dirty = false;
	return _texture;
	}
```

@ibilon on native targets every `BitmapData` have `image:Image` property which hold actual data and `Image` have `dirty` flag, which sets to `true` every time we call methods on bitmap data (not every time actually, but only then data is changing).

**Comment by ibilon** [comment]
Injecting functions into externs is possible, but I don't think variables can be injected.

If openfl classes were "real" on flash something like
```haxe
class BitmapData {
  private var __instance:flash.display.BitmapData;
  public inline function clone() {
    return __instance.clone();
  }
}
```
things like these would be a lot simpler.
Also we wouldn't have to use custom externs (which aren't without issues)

https://github.com/openfl/openfl/blob/develop/openfl/display/BitmapData.hx
wait now I'm confused, I thought there would be a `#if flash typedef BitmapData = flash.display.BitmapData;`
and https://github.com/openfl/lime/blob/develop/lime/graphics/Image.hx#L30 seems to be also made for flash

So does that mean that even on flash BitmapData have `(image:Image).dirty`?
And after testing no, looks like it's null.

@jgranick how does openfl.display.BitmapData/lime.graphics.Image work on flash?

**Comment by jgranick** [comment]
I think this would be a nice feature, but unfortunately there is no way to know if a Flash `BitmapData` has been changed or not since the last access.

Technically speaking, this could be implemented using a weak-key `Dictionary`, to match `BitmapData` instances with matching Stage3D `Texture` references, but the hard part is that if the original `BitmapData` is changed, we don't know, and so we always have to update the `Texture`, or risk it being out-of-date.

Happy to discuss this more. Slack or the forums is probably best, so we can keep issues down to only bugs :smile:
