### ISSUE TITLE
TextField.displayAsPassword not working

### ISSUE THREAD

**Issue by KnightMearh** [openfl/openfl#1271]
I recall TextField.displayAsPassword working some number of openfl/lime versions ago, but it doesn't seem to function in openfl 4.0.3 / lime 3.0.3 or openfl 4.1.0 / lime 3.1.0.

Haven't been able to test every target, but definitely does not work on Android (and I'm pretty sure HTML as well).

Can't find any documentation / issues, etc after digging around for a bit so leaving a bug here.

**Comment by loudoweb** [comment]
I think it has been fixed recently. Try this commit https://github.com/openfl/openfl/commit/2e26a32de9c1634b25c45319cf3e546089d77e00

**Comment by KnightMearh** [comment]
Patched locally with that commit - now working. Thanks!

Two other items (let me know if separate bugs are better, but they are related to this):
* Cursor caret position when in displayAsPassword mode doesn't align with the character positions. The easiest repro is to open an input field with displayAsPassword set (true) and type short letters, like j or i. Notice how large the deviation gets between the text and the caret. I know this has been an issue for a while.
* Cursor caret in any input field (not just password) doesn't render if the text is empty with the keyboard active (ie; FocusEvent.FOCUS_IN). The caret only shows once the user types at least one character into the field. The cursor will hide again if you delete characters once their are none.

**Comment by jgranick** [comment]
Fixed :smile:

`displayAsPassword` and the cursor caret with no text should work on Cairo and canvas render modes. I am having trouble with DOM mode -- I think we need to re-evaluate how text there is implemented
