### ISSUE TITLE
SoundMixer retains reference to SoundChannel without explicit stop()?

### ISSUE THREAD

**Issue by Leander1P** [openfl/openfl#1275]
`SoundChannel.stop ()` has a `SoundMixer.__unregisterSoundChannel (this);` but `__dispose()` does not, and we're seeing a large accumulation of `SoundChannels` staying alive unless we arrange to hook up a `SOUND_COMPLETE` listener that explicitly calls `SoundChannel.stop()`.

There are two callbacks in this file -- `source_onComplete` an html5-only `soundInstance_onComplete` -- but only one is used -- `source_onComplete`, regardless of the platform.  This unconditionally calls `__dispose`, which leaves the SoundChannel in an invalid state.  (If the html5 branch was supposed to call the `soundInstance_onComplete`, that does *not* call `__dispose`.)

I'm a little unclear on the intended behavior here.  It doesn't seem like the channel is intended to be reusable (at least on non-HTML5 platforms) after `source_onComplete`?

Do we need to be tracking all SoundChannel instances we get from `Sound.play`, listen for `SOUND_COMPLETE`, and manually call `SoundChannel.stop` on the instance when we've received `SOUND_COMPLETE`, in order to make them available for GC?

**Comment by Leander1P** [comment]
(We're testing just adding the `__unregisterSoundChannel` call to `__dispose` locally, and that appears to work, but I'm not sure if I understand all the invariants here, especially given the extraneous `onComplete`.)

**Comment by jgranick** [comment]
Okay, I think the latest commit will help.

`SoundMixer` support is new -- so we probably just missed some cases here.

I do not believe Flash `SoundChannel` objects are re-usable -- if you want to skip or fast-forward, you play again from a different position (thereby creating a new sound channel)
