### ISSUE TITLE
Removal of Shader Filters :(

### ISSUE THREAD

**Issue by er453r** [openfl/openfl#1276]
Why where shader filters removed in this commit: https://github.com/openfl/openfl/commit/dfc0a8e1eb294933e4d1f29057dd095332b085f6#diff-d7890a18e2f5fea2df16f6edeb7e830e ? Only software implementations where left, which mainly (and sadly) do not work and have much worse performance than gpu shaders.

I'm especially interested in `ColorMatrixFilter` which is essential in achieving high framerates with pixel manipulation.

**Comment by er453r** [comment]
Damn. I've started migrating from 3.6.1 and more suprises pop out.

Shaders where removed from `DisplayObject`? https://github.com/openfl/openfl/commit/5d73ec61968688c293519ba69d07dde5db8fcaf6#diff-077e7bafea7e35f6bae5d2dc11d69319

Why? Removing shaders is a large step back :/

**Comment by er453r** [comment]
OK, I rolled up my sleeves and dove into the code.

I've managed to write a working `ColorMatrixFilter` with `4.2.0` here is sample https://gist.github.com/er453r/cb0bc6a2d444d48f2fdc40869de52cf9

It is not ideal since:
* it passes arguments as strings (basically it modifies the source)
* it compiles every time arguments change

I've tried doing this "by the book", reverse engineering the new shader approach and came up with that https://gist.github.com/er453r/168fb8374ec307ba6b3f097d0b4c0cf8

This does not work since:
* the new approach does not pass any arguments set in `data`
* the new approach does not handle mat4 arguments
* (my private opinion - I don't like the over user of `Dynamic` int the new approach)

Anyways - things happening here with shaders are super not cool - this should be done in a seprete branch and merged in when final. Now serious hacking is required to make them work :(

**Comment by Beeblerox** [comment]
@er453r i extended shader class to handle automatic uniform setting, here is what i got:
https://github.com/Beeblerox/flixel/blob/Separate-render/flixel/graphics/shaders/FlxShader.hx

it always assumes that you pass an array for shader parameter value (see here example - https://github.com/Beeblerox/flixel/blob/Separate-render/flixel/system/render/hardware/gl/HardwareRenderer.hx#L192-L193)

and you must set shader's parameters value before calling `renderSession.shaderManager.setShader(shader);` (if you use this method, if not then just don't care about it)

**Comment by Beeblerox** [comment]
So here is quick example of how you can have ColorMatrixFilter now: https://gist.github.com/Beeblerox/7a57799df87e03667cc7070e41603a01

**Comment by Beeblerox** [comment]
i wanted to make PR to openfl with such fuctionality, but not sure if it will be accepted

**Comment by Beeblerox** [comment]
Btw, i don't like that shaders had been changed since openfl 3.6, especially that they are heavily using Dynamic without almost any typization

**Comment by ibilon** [comment]
Not really familiar with openfl's shader system but indeed the use of `implements Dynamic` not only seem unsafe but not necessary, an enum would hold that perfectly.

Your automatic uniform setting looks useful.

**Comment by Beeblerox** [comment]
@ibilon i'll try to make PR then

**Comment by jgranick** [comment]
Hi everyone,

Two problems with the old system (among others) is that it 1.) varied too much with the original Flash API and 2.) required that you have the shader source at compile time.

I've made a pass (thank you @Beeblerox for the example update!) to do a couple things:

 * ShaderInput and ShaderParameter are now @:generic, this should improve performance when used on C++
 * ShaderData is still dynamic, but there's no way to get around this (without enforcing a compile-time requirement)
 * Setting the `input` or `value` properties (I believe) should work now

This should walk the balance of preserving the same API signature (with the noted exception that `ShaderInput` and `ShaderParameter` no longer `implement Dynamic`) while making the shader system all-around more useful by finishing the support of pushing in values.

@Beeblerox, one quick note on your source:

Why don't you try doing `glVertexSource` or `glFragmentSource` before calling `super ()`?

**Comment by Beeblerox** [comment]
@jgranick thank you, i've missed that i can set these variables before calling super constructor. i already changed it in my code

**Comment by mayakwd** [comment]
I guess it's better to provide some sample code, initialization and passing parameters to shader is not obvious.

**Comment by Beeblerox** [comment]
Speaking of another filters. I guess it's possible to have ConvolutionFilter also, since it uses single render pass. But it requires setting new shader uniform - uTextureSize. So to have it we need to add this uniform we need to add new uniform which will be general for other shaders. I guess this isn't bad, since this uniform could be useful for other types of shaders (effects) and it was in openfl 3.6

@jgranick i'll try your changes for shaders today. btw, when do you plan to make next openfl release on haxelib?

**Comment by jgranick** [comment]
I have just made a pass (using a macro) that makes the `Shader` class strictly typed. I am not fully happy with the API (such as the static GL_VERTEX_SOURCE) but I think this can improve a bit.

The basic idea is that I would like `new Shader` to work without anything special. Classes that extend `Shader` could (using a macro) be strictly typed, one-off shaders would be more dynamic, but still work. Hopefully this would give us the best of both worlds -- strict types for performance and safety (when we know at compile-time the shader) but still allow for runtime generation of shaders.

With a little more polish, we'll be able to move from supporting only one shader per flat object (currently) to supporting multiple filters on complex objects, once we re-integrate framebuffer support.

There were many edge-case problems with our previous support, but now that the rendering is stable, I have hopes for integrating support again so this can expand further.

**Comment by er453r** [comment]
@jgranick from what I see, `ShaderData` is only iterated over, so wouldn't `Array<ShaderParametr>`, or `StringMap<ShaderParametr>` suffice?

**Comment by jgranick** [comment]
@er453r I am doing what I can to straddle the functionality we want (benefits of strict types, etc) while trying to mirror an existing Flash API:

http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/Shader.html
http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/ShaderData.html
http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/ShaderInput.html
http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/ShaderParameter.html

I also like that our current system allows for one-off shaders, where the source is generated at runtime. Compile-time features are good for core shaders, but being able to do something like the following (I think) also improves the utility

```haxe
var shader = new Shader (null);
shader.glFragmentSource = myCustomFragmentSource;

object.filters = [ new ShaderFilter (shader) ];
```
