### ISSUE TITLE
SoundChannel __source or __sourceInstance onComplete listener leak

### ISSUE THREAD

**Issue by Leander1P** [openfl/openfl#1279]
We're still chasing SoundChannel "leaks"; thank you @jgranick for the help in #1275, that was quite useful.  =)

I added this:

```
        #if !html5
        __source.onComplete.remove(source_onComplete);
        #else
        __soundInstance.removeEventListener ("complete", source_onComplete);
        #end
```

...to `source_onComplete` to allow the reference from the listener on `__source` or `___soundInstance` to drop.  It might be better placed in `stop` and/or `__dispose`, though?

(I'm also still a little confused by why `soundInstance_onComplete` is there, only `source_onComplete` seems to be used, `html5` or otherwise.  Should it be removed?  Or should the `#else` block in `private function new` be pointing at it instead?`)

We're down to no SoundChannel leaks on `html5` with this change in addition to https://github.com/CreateJS/SoundJS/pull/233 .  I have yet to use hxtelemetry or similar to verify that this has fixed our `android` build leaks completely, though.

**Comment by jgranick** [comment]
Let me know if you see any more leaks :smile:
