### ISSUE TITLE
completion on openfl project is broken

### ISSUE THREAD

**Issue by ibilon** [openfl/openfl#1280]
Compiler based completion defines `display`,
and some type are hidden from it which cause "type not found" errors

Like https://github.com/openfl/openfl/blob/develop/openfl/_internal/renderer/RenderSession.hx

And some type are different in display mode like https://github.com/openfl/openfl/blob/develop/openfl/utils/ByteArray.hx

Last but not least the flash extern, I don't even get it why are they mapped to openfl classes on display?!
https://github.com/openfl/openfl/blob/develop/externs/core/flash/flash/Memory.hx

Besides some very specific cases, mostly involving macro, `#if display` shouldn't be used.

**Comment by ibilon** [comment]
On the subject of externs what are https://github.com/openfl/openfl/tree/develop/externs/core/openfl and https://github.com/openfl/openfl/tree/develop/externs/extras/ used for @jgranick?
According to the include.xml they are pulled in when in display mode (and the first one on flash build too)

**Comment by jgranick** [comment]
The externs (and `-Ddisplay`) are used for multiple things.

It is used for code completion, used for documentation, and used for (in the future) compiling lightweight applications (which would rely on an openfl.js or lime.js, for example)

The `openfl._internal` package not should be exposed to `display`. All platforms should use the same files for code completion -- the public API for OpenFL is intended to be unified, it prevents frustrating "cannot merge" errors when generating documentation, and gives us a single place to add ASDoc documentation.

Are we missing an `#if !display` import somewhere?

**Comment by ibilon** [comment]
But it should, I'm not talking about whether to add @:noCompletion or not, but an actual **error** from the compiler because the type isn't defined while in display mode.

Completion shouldn't use some extern definition, it gives wrong information on type hover, go to definition and things like that.

Totally get why it's done for documentation, but then let's use a `documentation` flag ant abuse the `display` flag.

Also for openfl.js why not just use `--macro exclude("openfl")` it'll make the type extern and assume it'll be available at runtime.

**Comment by ibilon** [comment]
On the asdoc issue, is it really a problem?
Is there more than the openfl package/are there classes duplicated?
Assuming we don't use the openfl externs.

Do doc merge issues come from flash vs non flash?

Also I'd really like to know why the flash externs point to openfl classes on display, display shouldn't be called on them, there's a remap flash -> openfl right?

**Comment by jgranick** [comment]
I do not want the internals of OpenFL's implementation to be exposed to code completion -- otherwise, developers may also end up making unnecessary assumptions about our implementation, leading to upgrade problems later (when the public API still works the same)

`RenderSession` is not a public API, being hidden makes development of OpenFL itself a little more cumbersome, but I do not want this ever to be exposed to other users.

There is no Flash -> OpenFL remap, this would break support for Flash-only classes that are not implemented in OpenFL. We do customize certain types (such as enum values) and also the openfl.* classes are the ones with ASDoc comments -- we _definitely_ don't want to duplicate those

**Comment by ibilon** [comment]
Alright then when I remove the display guard I'll add some @:noCompletion, but being in **_**internal that should already be enough.

Oh so that's why the extern redirect, for the documentation, probably ok I guess.

I think I got it, but I'll still make the changes in a separate branch ;)

**Comment by jgranick** [comment]
You cannot add @:noCompletion to a class, only fields. This format also means we don't have to clutter our internal code with a @:noCompletion on everything we define

**Comment by ibilon** [comment]
It also means that completion **doesn't work**,
the compiler isn't ok with types not being found.

**Comment by jgranick** [comment]
What is asking for `RenderSession`? Without referencing our internal implementation, there shouldn't be code referencing it. That's why I wondered, though (say, in the special case of `Tilemap` on the Flash target) if we were missing an `#if !display` around an include

**Comment by jgranick** [comment]
Also, is there an easy way to test if code completion is working properly? Is there a way we could extend our Travis unit tests to be sure that completion works?

**Comment by ibilon** [comment]
No idea, @Gama11 is the one with the bug, but it's not on latest so can't be Tilemap.

But all that seems like a hack, there should be a better way to hide things from completion,
maybe haxe could support @:noCompletion on class? (cc @Simn)
Although I'm pretty sure classes in packages starting with an underscore are already hidden.

**Comment by Simn** [comment]
We could support `@:noCompletion` on classes, but then it is only going to work on latest Haxe version so that's probably not a satisfactory solution.

The whole "hide the internal implementation in display mode" business seems to be a bad idea. Where do these classes actually show up?

**Comment by Gama11** [comment]
For the record, this is the error I was getting:

` C:/HaxeToolkit/haxe/lib/openfl/3,6,1/openfl/_internal/renderer/opengl/utils/SpriteBatch.hx:36: characters 19-32 : Type not found : RenderSession`

**Comment by andyli** [comment]
Internal fields can be defined as `@:allow(openfl) private`. It would be even stricter than `@:noCompletion`, which doesn't really prevent people from using the internal fields.

Ideally one can define the internal class itself as private, but `@:allow` doesn't expose private types (https://github.com/HaxeFoundation/haxe/issues/5731). However, if all fields are private, people can't use the class anyway.

**Comment by Gama11** [comment]
`@:allow(openfl)` is a bad idea - I made that mistake in Flixel. It means that all subclasses of classes in the openfl package have access as well.

**Comment by andyli** [comment]
Good point. That's tricky since people are expect to extends Sprite...

**Comment by ibilon** [comment]
The issue also highlight the need for really private fields/functions,
really useful in any code where the user is expected to subclass.

**Comment by andyli** [comment]
I also wish that is real private fields. But, hey, ruby and python don't have real private fields either...

**Comment by jgranick** [comment]
It may seem unconventional, but it is important to me that the underlying implementation for OpenFL is hidden. I believe this results in better code completion, and reduces the cases where updates to OpenFL break older projects.

We can discuss this more on Slack or the forums, but this is a desired behavior for now :smile:
