### ISSUE TITLE
TextField on html5 target only accessible with mouse after changing content programmatically

### ISSUE THREAD

**Issue by chpla** [openfl/openfl#1285]
When I use a dynamic TextField for user input on html5 targets, and I programmatically change its content, the text field loses focus and becomes inaccessible except through clicking on it again with the mouse. The event handlers for the focus get called properly if I try focusing it through other means (e.g. by setting stage.focus), but it is not possible to input text with the keyboard unless the text field is clicked on. After clicking on it once, it remains accessible until the content is again changed in the program.

**Comment by jgranick** [comment]
This is working for me on the latest source of OpenFL and Lime:

```haxe
package;


import openfl.display.Sprite;
import openfl.events.Event;
import openfl.text.TextField;


class Main extends Sprite {
	
	
	public function new () {
		
		super ();
		
		var textField = new TextField ();
		textField.text = "Hello";
		textField.type = INPUT;
		addChild (textField);
		
		var i = 0;
		
		addEventListener (Event.ENTER_FRAME, function (_) {
			
			i++;
			
			if (i == 240) {
				
				textField.text += "h";
				i = 0;
				
			}
			
		});
		
	}
	
	
}
```

Are you using -Dcanvas or -Ddom? The above is working for GL. It is also possible that this was improved since the last release, or that there is something more complex happening in your code that is changing focus

**Comment by chpla** [comment]
If you modify it like this, the error occurs:

`package;


import openfl.display.Sprite;
import openfl.events.TimerEvent;
import openfl.text.TextField;
import openfl.utils.Timer;


class Main extends Sprite {


    public function new () {

        super ();

        var textField = new TextField ();
        textField.text = "Hello";
        textField.type = INPUT;
        addChild (textField);

        var timer = new Timer (5000);
        timer.addEventListener (TimerEvent.TIMER, function (_) {

            textField.text = "";

        });
        timer.start ();

    }


}`

**Comment by chpla** [comment]
(the important change is that I assign the text field something rather than just concatenating. Upon assigning text, it loses focus and must be clicked again to refocus.

**Comment by ibilon** [comment]
The bug also happens on neko.
