### ISSUE TITLE
Wrong import in openfl._internal.renderer.flash::FlashTilemap line 4

### ISSUE THREAD

**Issue by wolfhoundgelert** [openfl/openfl#1289]
(4) import flash.display.Sprite;

**Comment by ibilon** [comment]
Could you give more details?

What did you do, what target, is the error at run time or compile time, does it happen on other code like the samples?

**Comment by wolfhoundgelert** [comment]
It was something like "You can't use flash.display.Sprite on neko target.." in my unit-tests.
It looks like a bug with import because there isn't any flash-import in that package)

**Comment by ibilon** [comment]
Your hxml must be wrong.
Use `openfl display neko` to see what kind of classpath/define you need to put in it.

**Comment by wolfhoundgelert** [comment]
Ok, thanks! Maybe I'm wrong.
