### ISSUE TITLE
[HTML5] Type not found : js.html.webgl.Texture

### ISSUE THREAD

**Issue by T1mL3arn** [openfl/openfl#1292]
Compiling project in HaxeDevelop or cmd ```openfl test html5``` gives me this:
```Haxe
C:/HaxeToolkit/lime/3,2,1/lime/graphics/opengl/GLTexture.hx:18: characters 20-41 : 
Type not found : js.html.webgl.Texture
```
OpenFl 4.2.0
Lime 3.2.1 
Haxe 3.3.0

**Comment by jgranick** [comment]
Sounds like this issue https://github.com/HaxeFoundation/haxe/issues/5577

**Comment by T1mL3arn** [comment]
Yes indeed, file is missing. Just reinstalled haxe - and it works. Thanks!
