### ISSUE TITLE
TextField auto-scroll

### ISSUE THREAD

**Issue by KnightMearh** [openfl/openfl#1297]
If you have an input text field and enter more characters than the field supports, the text will trail off the end bounds and not render because it doesn't horizontally scroll. Noting that I have currently only tested this in Android target.

repro:
1. Create an input field.

```
  var tf = new openfl.text.TextField();
  tf.type = TextFieldType.INPUT;
```
1. Enter a value longer than the field can provide. In this example, "myemail@test.com".
2. Observe  [`myemail@tes`] // text is cut off
3. Expected  [`il@test.com`]  // text scrolls to show end

**Comment by KnightMearh** [comment]
Then as a follow up (will write up a separate bug to describe further), the caret render position (and highlighted text start/end index) on a field that has scrolled is offset.

**Comment by jgranick** [comment]
https://trello.com/c/5quOPFtW/29-add-support-for-auto-scrolling-in-input-textfields
