### ISSUE TITLE
Multitouch.supportsTouchEvents not accurate, always true outside of HTML5

### ISSUE THREAD

**Issue by bendmorris** [openfl/openfl#1300]
This function used to call a "lime_stage_get_multitouch_supported" function, now it simply returns true on any native platform.

**Comment by jgranick** [comment]
The old code was hard-coded to return true on mobile, Windows or Linux.

We may consider `SDL_GetNumTouchDevices` in the future, but it looks as if this may return 0 until touch input is received on some platforms:

https://wiki.libsdl.org/SDL_GetNumTouchDevices

Thanks :smile:

**Comment by bendmorris** [comment]
Weird - this doesn't seem accurate either, but if it's consistent with the previous logic that's good enough for me. I noticed some regressions because this value had changed (on OSX) when switching to OpenFL 4.

Thanks!
