### ISSUE TITLE
Type not found : flash.system.ImageDecodingPolicy

### ISSUE THREAD

**Issue by darmie** [openfl/openfl#1304]
Openfl v 4.2.0

`C:\HaxeToolkit\haxe\lib\openfl/4,2,0/externs/core/openfl/openfl/system/LoaderContext.hx:16: characters 54-111 : Type not found : flash.system.ImageDecodingPolicy
`

**Comment by jgranick** [comment]
Looks like this issue:

https://github.com/HaxeFoundation/haxe/issues/5577
