### ISSUE TITLE
stageX / Y not initialized in manually dispatched MouseEvent

### ISSUE THREAD

**Issue by Gama11** [openfl/openfl#1305]
Tested with OpenFL 4.2.0 and Lime 3.2.1.

```haxe
import openfl.events.MouseEvent;
import openfl.display.Sprite;

class Main extends Sprite {
	public function new() {
		super();
		stage.addEventListener(MouseEvent.MOUSE_MOVE, onMouseMove);
		stage.dispatchEvent(new MouseEvent(MouseEvent.MOUSE_MOVE,
			true, false, 1, 2, stage, false, false, false));
	}

	function onMouseMove(e) {
		trace(e.stageX, e.stageY);
		stage.removeEventListener(MouseEvent.MOUSE_MOVE, onMouseMove);
	}
}
```

On Flash, the output is `1,2` like expected.

On Cpp, it's `0,0`.
On Neko, it's `null,null`, which is especially problematic because of invalid operation errors when the values are used for calculation (this is how I noticed the problem). Same on HTML5.

So it looks like `e.stageX` / `Y` are simply uninitialized.

**Comment by jgranick** [comment]
This is kind of a strange behavior, but we'll copy it 😕
