### ISSUE TITLE
What happened to SystemPath?

### ISSUE THREAD

**Issue by asciiascetic** [openfl/openfl#1310]
I need to be able to write files to android devices.  I used to use SystemPath to locate directories to which I could save files, but it seems to have vanished from more recent versions. What is recommended to replace it?

**Comment by jgranick** [comment]
Check out lime.system.System

http://api.openfl.org/lime/system/System.html

:smile:

**Comment by asciiascetic** [comment]
Thanks sir, I appreciate your dedication to gleebs your projects that benefit gleebs like me.

**Comment by jgranick** [comment]
No problem, have a great day :wink:
