### ISSUE TITLE
Openfl > 4.2.0, html5, MouseEvent.MOUSE_DOWN stopped listening

### ISSUE THREAD

**Issue by hopewise** [openfl/openfl#1311]
In HTML5, once I've upgraded from 4.2.0 to 4.3.0, this line of code failed to add event lister:

    corePresenter.addEventListener(MouseEvent.MOUSE_DOWN, handlePress);

where `corePresenter ` is a `MovieClip`

**Comment by jgranick** [comment]
Are you using a mouse, or touch? Is there a larger piece of code I could try to compile? ( I assume that larger samples of code like Pirate Pig work?)

**Comment by hopewise** [comment]
I am sorry, it's hard to get a larger piece of code, but I am not 100% sure if this is an event issue either, I am closing this issue, until I make sure what the exact problem in my code was.
