### ISSUE TITLE
OpenFL 4.2+/Lime 3.2+: Project.xml <certificate> password attribute gets lost for Android release builds

### ISSUE THREAD

**Issue by joeymanderley** [openfl/openfl#1312]
For Android release builds pre-gradle, if the < certificate > element in project.xml had an "alias-password" attribute but not a "password" attribute (if the keystore itself had a different password than the alias), the build would detect it and the command line would ask you for the missing password.

Post-gradle, the KEY_STORE_PASSWORD field in the generated gradle.properties gets set to null in the same situation, or even if you DO specify a "password" attribute in project.xml.

~~A confirmed workaround is to make a "signing.properties" file with the passwords in them and put it in the Android build directory. Looking through the lime template I suspect using a HXP and Keystore() would similarly work.~~

**UPDATE:** Actually "signing.properties" didn't work; without signing information, the build simply reported success without signing the apk. Also it seems KEY_STORE_PASSWORD was getting set to null even when a password was supplied most likely because the password contained some characters the XML parser didn't like. 

_I guess you can close this one, unless prompting for a missing keystore password rather than failing explicitly or silently (if the entire certificate element is missing) is a big enough issue that it needs to be fixed._

**Comment by jgranick** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Would be nice to prompt for password if doing an Android release build and the password is not defined](https://trello.com/c/6W5G8ovz/62-would-be-nice-to-prompt-for-password-if-doing-an-android-release-build-and-the-password-is-not-defined)

**Comment by jgranick** [comment]
Thanks for your help, I opened a card on Trello so we can track this as an improvement, I do think it could be a good idea! :smile:
