### ISSUE TITLE
openfl shader “input null”  error on html5 target

### ISSUE THREAD

**Issue by keesungz** [openfl/openfl#1314]
First， I found the function "set_glVertexSource"  set value to  _glFragmentSource   but no set value to _glVertexSource. I think it's a bug otherwise howto keep GLSL "varying" is same between glFragment and glVertex。 Second，I write a custom shader using new glVertexSource and glFragmentSource，browser arise a “set property input of null” error,but I set bitmapdata to a "uniform stamper" variable. the browser arise  the same error even if I use the below glVertexSource and glFragmentSource.

var customShader = new Shader();
shader.glVertexSource =
“void main(void)
{

}";

shader.glFragmentSource =
“void main(void)
{

}";

mybitmap.filters=[ new shaderFilter(customShader) ];

Although has a flaw, but It's great that openfl 4.x support GLSL shader more widely!

**Comment by jgranick** [comment]
The base `openfl.display.Shader` class should add a call that sets the glVertexSource if you do not define it. It comes from a macro, so it's a little bit hidden from plain sight.

The shaders (right now) are reliant upon matching the same core naming scheme for core uniforms and attributes. Most shaders will have one sampler, called "uImage0", though I posted a sampler that illustrated how you could add another sampler and set its input.

Without seeing your code, is it possible you define more than one sampler? Try removing the second sampler (if that's the case) and use only uImage0. The source for `openfl.display.Shader` should help illustrate what the standard shader source looks like

**Comment by keesungz** [comment]
Dear jgranick，
    I rewrite Fragment Source according your advice and it's OK!  Thank your very much！

**Comment by jgranick** [comment]
Awesome! Glad to hear 😁
