### ISSUE TITLE
Dynamic Textfield with displayAsPassword==true renders cursor in wrong place on html5 target

### ISSUE THREAD

**Issue by chpla** [openfl/openfl#1316]
The cursor is rendered in the position as if the text field was displaying clear text (so if I enter "WWWWW" the cursor ends up further on the right than I enter "IIIII".

To reproduce, use any such textfield on html5 targets.

**Comment by ibilon** [comment]
I don't have this issue on the development version,
what version of lime/openfl do you use?

**Comment by chpla** [comment]
currently working with 4.3.0 here. If the issue has already been fixed, all the better.

**Comment by ibilon** [comment]
Could also be a font/browser issue, do you use the default one? and which browser?
Tested on firefox with default font.

**Comment by jgranick** [comment]
Yes, I think I fixed this recently

**Comment by mayakwd** [comment]
Yep, it's fixed already.
