### ISSUE TITLE
Bug bounty (200€ per problem)

### ISSUE THREAD

**Issue by PlayaJan** [openfl/openfl#1317]
Hi there! :) 

I´m working on a larger project and encountered some show-stoppers. I will pay anybody who can fix one or more of these problems until the 4th of November **200€ per problem.**

Problem 1: You have to click textfields over and over again: https://github.com/openfl/openfl/issues/1285

Problem 2: Multiline textfields don´t work properly: https://github.com/openfl/openfl/issues/1254 

Problem 3: Cursor issues at password fields: https://github.com/openfl/openfl/issues/1316

Thanks a lot in advance, 
Jan

**Comment by tienery** [comment]
I assume you mean the 4th of November, it's almost the end of October :)

**Comment by PlayaJan** [comment]
You´re right, I fixed that! :)

**Comment by matrefeytontias** [comment]
Isn't #1316 solved already ? @ibilon says he can't replicate.

**Comment by mayakwd** [comment]
@ibilon, well, I guess this issue can be closed, all bugs are fixed (including #1316)

**Comment by ibilon** [comment]
Not sure if #1254 is really fixed, tried on my home computer and it looks like it adds two new lines.

**Comment by PlayaJan** [comment]
Seems like I worked with an outdated version - I´m sorry! I´ll check all 3 problems with the latest version and get back to you if everything works now.

**Comment by mayakwd** [comment]
@PlayaJan, try develop-version, it contains fixes for the first and second issues, they are not officially released.

**Comment by mayakwd** [comment]
@ibilon now it's totally complete :-)
