### ISSUE TITLE
Android - Inconsistent full screen size

### ISSUE THREAD

**Issue by danielmar** [openfl/openfl#1325]
Hey,

Using a Nexus 5, Android 6.0 I get varying full screen sizes when opening my game:

Centered 1080x1776
![0](https://cloud.githubusercontent.com/assets/2474262/19717401/1563d6f0-9b69-11e6-944a-ba42b648a899.png)
Fullscreen 1080x1920
![1](https://cloud.githubusercontent.com/assets/2474262/19717400/1562a866-9b69-11e6-893a-2dfb5a71067c.png)
Bottom 1080x1776 - this one also causes MouseEvent X,Y issues
![2](https://cloud.githubusercontent.com/assets/2474262/19717402/156595da-9b69-11e6-9073-da3079a5ac6a.png)

I'm using OpenFL 4.3.1, Lime 3.3.0 and Android SDK 22
Project's window is set to a fixed size and resizable="false"

It works fine with devices that have physical home buttons, or if I set fullscreen to false, so I guess it's an issue with the immersive mode?

**Comment by jgranick** [comment]
I believe this was fixed when we updated SDL in Lime version 3.4.0, and subsequently in 3.5.0

https://hg.libsdl.org/SDL/rev/f7d8e9d871c5

Please let me know if you're still having issues :smile:

**Comment by Tembac** [comment]
is there any workaround for this on older lime versions ?

I'm using HaxeFlixel with next and I'm having this problem. 

https://github.com/HaxeFlixel/flixel/issues/2128
