### ISSUE TITLE
Arabic and Farsi Fonts disjointed

### ISSUE THREAD

**Issue by asciiascetic** [openfl/openfl#1327]
When I include an Arabic font (in this case Noto Naskh Arabic) the strings I wish to display show up as individual standing forms instead of the cursive script, and they seem to be reversed in order.  For example: خوش آمدید displays as expected in my browser etc, but not on Android / Linux targets. I have checked that the Noto Naskh Arabic typeface itself is not to blame.  

My principle target is using openfl-legacy, but for a starting place I tried the AddingText sample from openfl-samples 4.0.0 with openfl 4.2.0  and lime 3.2.0 to the same effect.  Here is a screencap of how the text displays instead of how it ought to above.

![arabicaddingtext](https://cloud.githubusercontent.com/assets/1368610/19829636/de36f6be-9db4-11e6-9162-d98b880e1ac2.png)

Any Joy?

**Comment by ibilon** [comment]
Does it work in a non legacy app?
If it does maybe there's a way for you to backport the required fix,
if not then it will have to be fixed.

**Comment by asciiascetic** [comment]
Like I said, I tried it out in the AddingText demo from the most recent openfl-demos (4.0.0), using the most recent openfl (4.2.0) and lime (3.2.0).

My target is openfl-legacy, where it also does not work. I made sure to test on the newest and most up-to-date versions available as a kind of sanity-check.

If it can be made to work with non-legacy, then I have a case for updating the whole project.

**Comment by jgranick** [comment]
There is no legacy in OpenFL 4.x

On Linux, we have Harfbuzz in Lime, which gives us information about how the letters should be placed. For rendering (however) we are using `cairo.showText` which does not use this information. The solution is to use Harfbuzz for placement, then to render glyphs individually based on that detail

**Comment by asciiascetic** [comment]
Yes, I should have been more specific.

I inherited a project that is being built with openfl 3.6.1 and the openfl-legacy is set in the project.xml file.

When I encountered the above font issue in my project, I decided to try out Arabic fonts in a completely unrelated test - i.e. the AddingText sample with openfl 4.2.0.  I'd be happy if Arabic fonts would display correctly in any combination of versions and compile switches.  

I really shouldn't have mentioned legacy at all, as it just seems to have confused everybody.  The truth is I have no idea what sequence of decisions led to the use of legacy, and previous devs are well out of frame at this point.

In anycase I'll try the Harfbuzz extension. I noticed no mention of Android in your comment, does that mean that you don't expect it to work there? 

Cheers

**Comment by jgranick** [comment]
If you want, try uncommenting this code:

https://github.com/openfl/openfl/blob/develop/openfl/_internal/renderer/cairo/CairoTextField.hx#L223-L241

(and comment the `cairo.showText` call below it)

It's not perfect, but it is code that might be a step toward implementing rendering based upon the positions Harfbuzz gives us.

I don't know (though) if we need to feed Harfbuzz with different language information prior to requesting where the glyphs should be rendered

**Comment by asciiascetic** [comment]
I may do just that, because I am already now involved with this issue. But for now I'm just using extension-harfbuzz and the convenience class it provides called HarfbuzzText.

I include my alterations to AddingText here only to benefit googlers, sorry if it pollutes the issue ticket a little.

```haxe
package;


import openfl.display.Sprite;
// import openfl.text.Font;
// import openfl.text.TextField;
// import openfl.text.TextFormat;
import extension.harfbuzz.HarfbuzzText;

class Main extends Sprite {
	
	
	public function new () {
		
		super ();
		
		// var format = new TextFormat ("Noto Naskh Arabic", 30, 0x7A0026);
		// var textField = new TextField ();

		
		// textField.defaultTextFormat = format;
		// textField.embedFonts = true;
		// textField.selectable = false;

		var textField = new HarfbuzzText('assets/NotoNaskhArabic-Regular.ttf',
					     30,
					     0x7A0026,
					     HarfbuzzText.RIGHT,
					     1);
		textField.width = 200;
		
		textField.text = "خوش آمدید";
		
		addChild (textField);
		
	}
	
	
}
```

In order to get this to work on the Linux I had to `lime rebuild extension-harfbuzz linux`

**Comment by jgranick** [comment]
I'm going to track this improvement here, thanks :)

https://trello.com/c/kyCMF674/26-update-font-renderer-to-rely-on-harfbuzz-positioning-which-allows-complex-text-layouts
