### ISSUE TITLE
Android setup fails

### ISSUE THREAD

**Issue by matthewswallace** [openfl/openfl#1328]
I have the latest git version of lime and openfl. If I run `openfl setup android` I get the following error.

```
Called from utils/PlatformSetup.hx line 239
Called from /usr/local/lib/haxe/std/neko/_std/sys/io/File.hx line 54
Uncaught exception - [file_open,/opt/android-sdk/tools/dmtracedump]
```

I'm on OS X 10.11.6 running Haxe 3.3.0-rc2

**Comment by ibilon** [comment]
Is that the first line? Or does it look like it succeeded in writing other files before?
Are you running with admin/root rights?

**Comment by matthewswallace** [comment]
ok ... `sudo openfl setup android` worked

**Comment by matthewswallace** [comment]
now I get the following error after running setup as admin/super

```
Called from lime/tools/helpers/ProcessHelper.hx line 172
Called from lime/tools/helpers/ProcessHelper.hx line 242
Uncaught exception - Error running: chmod -R 777 ~/.android []
```
