### ISSUE TITLE
Stage3D texture issues

### ISSUE THREAD

**Issue by vroad** [openfl/openfl#1334]
1. uploadFromTypedArray in Texture constructor is not a meaningless
call, please don't remove it. It's needed for render to texture.
2. What's low memory mode? Downscaling? That may break rendering if texture atlas is used. I guess many real-world applications use texture atlas in some way, so I don't think this is useful for users. I'd rather implement this in higher level, since Stage3D is meant for lower level abstraction. For example, you could make some space by removing old textures from cache if you run out of memory.
3. Does memory usage for Texture include all miplevels? It looks like only size for level 0 is used.

I've heard that Flask Stage3D textures allocate all mip levels even if you don't need them, but should I do that in OpenFL? That's bad for memory usage.
RectangleTexture doesn't have such problems since it doesn't support mipmaps.

**Comment by jgranick** [comment]
1. Could you help share an example of where you are using `uploadFromTypedArray`? I think you can do something like `uploadFromByteArray (typeArray.buffer)` instead, though perhaps we could allow direct conversion (without referencing `.buffer`) in the future

 2. As you (may) know, the Stage3D layer is a port from another platform, it appears to have code for a low-memory mode where it uses smaller textures, but this is disabled right now

 3. Similarly, the code had ways to track memory usage, but it is not fully correct (as you have seen) with tracking multiple miplevels

I think the question of miplevels is whether you enable mipmapping for the texture or not

**Comment by vroad** [comment]
I meant you shouldn't delete this part. https://github.com/openfl/openfl/blob/aca5608a67d5294ab1db947af09f96c677b57722/openfl/display3D/textures/Texture.hx#L39

To be able to use Texture you should allocate at least first level using glTexImage2D. Since you don't use Texture.uploadFrom* calls in the case of render to texture, removing this part could cause OpenGL errors.

**Comment by vroad** [comment]
Where can I read more about low-memory mode? It's technically impossible to implement that by downscaling textures, as texture atlases/filters rely on texture resolution.

It might be possible to implement that with 16bit color texture though.

**Comment by jgranick** [comment]
We can discuss more off of Github issues, the `uploadFromTypedArray` issue should be resolved :smile:
