### ISSUE TITLE
Safari external font issue

### ISSUE THREAD

**Issue by zatarus** [openfl/openfl#1336]
Using safari 10.0 and Assets.getFont(), font applies only when you select or create the text at runtime. This is maybe about adding a text in new() function (just a theory)

Firefox is showing all fonts properly.

Version dump:
```
haxe-3.3.0-rc.1
hxcpp 3.2.102
lime 3.4.1
openfl 4.4.1
```

Adding my font http get log which has no errors:
```
10.0.2.2 - - [02/Nov/2016 20:28:57] "GET /assets/fonts/open-sans/LICENSE.txt?497200 HTTP/1.1" 200 -
10.0.2.2 - - [02/Nov/2016 20:28:57] "GET /assets/fonts/open-sans/OpenSans-Bold.eot?497200 HTTP/1.1" 200 -
10.0.2.2 - - [02/Nov/2016 20:28:57] "GET /assets/fonts/open-sans/OpenSans-Bold.svg?497200 HTTP/1.1" 200 -
10.0.2.2 - - [02/Nov/2016 20:28:57] "GET /assets/fonts/open-sans/OpenSans-Bold.woff?497200 HTTP/1.1" 200 -
10.0.2.2 - - [02/Nov/2016 20:28:57] "GET /assets/fonts/open-sans/OpenSans-Regular.eot?497200 HTTP/1.1" 200 -
10.0.2.2 - - [02/Nov/2016 20:28:57] "GET /assets/fonts/open-sans/OpenSans-Regular.svg?497200 HTTP/1.1" 200 -
10.0.2.2 - - [02/Nov/2016 20:28:57] "GET /assets/fonts/open-sans/OpenSans-Regular.woff?497200 HTTP/1.1" 200 -
```

**Comment by jgranick** [comment]
`Assets.getFont` is a compile-time feature, but you should be able to use any webfont name in your `TextFormat` if you load fonts later, a different way. I'm happy to hear suggestions if you think there are ways we can make it easier to work with fonts in the future (such as a `Font.fromName` constructor, or something?)

Thanks :wink:
