### ISSUE TITLE
Neko mac build from linux doesn't work anymore

### ISSUE THREAD

**Issue by zatarus** [openfl/openfl#1337]
**(at linux)** `haxelib run openfl build mac`
then
**(at mac)**` cd Export/mac64/neko/release/bin/<APP>.app/Contents/MacOS`
**(at mac)** `./<APP>`

Used to work, however now gives error:
`./<APP>: cannot execute binary file`

More debug info:

- `$ file <APP>` gives: <APP> ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, stripped

- MacOS directory contains two files: lime.ndll and <APP> executable

- Bug span is around a year, more likely a lime issue. If you think so, let me know and I can move this issue there.

**Comment by jgranick** [comment]
Lime included template files for Neko for Windows, Mac and Linux with the goal of supporting cross-desktop builds, however, in practice, the generated Neko output in many tests failed to function properly on a system that did not have Neko installed.

If the host system needs Neko installed, then it's a bit of a waste to go through the steps we were taking, and we had an out-of-date version of Neko for Mac which did not support binary sizes as large as the (patched) Linux or Windows versions, either.

Beyond the patch, Neko has a new version release with Haxe 3.3 development builds, newer than all our templates, which would have required more testing to integrate.

I am not sure that Neko is able to be used for more than a testing target at the moment, so the template files were removed, and we rely now on the host OS install of Neko.

I do still want cross-desktop builds, but perhaps using Electron (with an HTML5 build) or if HL (Nicolas' new VM) turns out, then we could enable it then

**Comment by zatarus** [comment]
Thank you for taking time on brief response. Just for notes, reason I used cross-desktop builds was to keep openfl in a VM. That is a rising trend for Vagrant users as well. I developed this way about a year in  a sandbox without installing anything haxe in my computer (good for messing a lot and using different variations). I hope someday it will be trivial to bring it back. Despite slow down, I already switched to html5 to save the day :)

**Comment by jgranick** [comment]
That's interesting, I would be interested in learning about how to integrate a workflow like this.

Speaking of HTML5, I'm interested in a "live code" scenario where we have a host application wrapper that reloads the JS content when the files are updated.

**Comment by zatarus** [comment]
For my case, I prepared a simple Vagrantfile to spin up an ubuntu box with added provision commands to install haxe, openfl etc. 

Then I used the following script outside:
```
#!/bin/bash
vagrant ssh << EOF 
    haxelib run openfl build mac 
EOF
if [ $? -eq 0 ]; then
    cd Export/mac64/neko/release/bin/TheApp.app/Contents/MacOS
    ./TheApp
fi
```
Which basically,  ssh into vm, runs the command, goes out, cd to release, then runs the neko. 

**For additional html5 serving I did following:**

Added Vagrantfile to have the forwarded port configuration:
`config.vm.network "forwarded_port", guest: 3000, host: 3000`

I had runserver.py to have:

```
import os
import socket
import SimpleHTTPServer
import SocketServer
PORT = 3000

os.system("haxelib run openfl build html5") # compiles the project

# Absolutely essential!  This ensures that socket resuse is setup BEFORE
# it is bound.  Will avoid the TIME_WAIT issue
class MyTCPServer(SocketServer.TCPServer):
    def server_bind(self):
        self.socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        self.socket.bind(self.server_address)

print "Serving at port " + str(PORT)
Handler = SimpleHTTPServer.SimpleHTTPRequestHandler
httpd = MyTCPServer(("0.0.0.0", PORT), Handler)
os.chdir("Export/html5/release/bin/")
httpd.serve_forever()
# httpd.shutdown() # If you want to programmatically shut off the server
```

Where I would `vagrant ssh` into machine and then `python runserver.py`. My browser always open at localhost:3000, this part is quick enough for my case as I usually do web development same way. Living reload can be added with packages like https://pythonhosted.org/watchdog/. Only challenge would be to have OpenFL to compile only changed js files, I believe it currently compiles all hx files even only one line changed. Hope these help for idea to evolve.

**Comment by jgranick** [comment]
Do you think HTML serving would work by forwarding the port, but using the Node HTTP server included in the Lime tools?

**Comment by zatarus** [comment]
Absolutely, forwarding above is just for VM itself, one thing to make sure is node have to bind on 0.0.0.0 instead of 127.0.0.1.  Reason I wrote above server from scratch was to eliminate need of node for my setup.

**Comment by jgranick** [comment]
Oh, Lime includes an embedded Node server, `openfl test html5` boots it up and runs it for your project :smile:

**Comment by zatarus** [comment]
Just realized it includes a compiled binary, okay I might have a prejudge whenever I see a Node that would be reason I didnt go for it xP  Good thing the command is already there!
