### ISSUE TITLE
-Dmodular issue

### ISSUE THREAD

**Issue by lovedna** [openfl/openfl#1338]
Type.getClassName not return the class path
i found all class __name__  is value true,so it can not call join function
not use -Dmodular the __name__ is value array of string

**Comment by jgranick** [comment]
So you are saying that Type.getClassName fails with -Dmodular, is this when referencing an OpenFL, Lime or Haxe core class, or one of your own classes?

**Comment by lovedna** [comment]
yes,my own class  the `__name__` is true
the core class is ok
how to fix it?
