### ISSUE TITLE
Assets.getText don't work with multiple dots in file name

### ISSUE THREAD

**Issue by boorik** [openfl/openfl#1339]
I don't know if it's  solved in openfl new versions but in 3.6.1 with lime 2.9.1, I have this behaviour :

I tryed to import a xml from sparrow altas like this :
var xml:String = Assets.getText("assets/data/tuto/anim5.sparrow2.xml");
trace(xml);
output :
 �T

After renaming file in anim5sparrow2.xml everything went good.

**Comment by jgranick** [comment]
What platform?

**Comment by boorik** [comment]
Sorry, tested on html5 and windows.

**Comment by boorik** [comment]
My bad,
File encoding was not Utf8 and changing the encoding was not doing anything until i changed the filename.
