### ISSUE TITLE
TextField don't display special symbols

### ISSUE THREAD

**Issue by r3d9u11** [openfl/openfl#1346]
Hi. How I can display text with special symbols?

Haxe 3.2.1
OS Linux Mint 18 x64
Default encoding UTF-8

Text editors are correctly displays string with special symbols:

vim
![vim](https://cloud.githubusercontent.com/assets/15020827/20308441/fa80c41e-ab54-11e6-8627-5091a936a094.png)

xed
![xed](https://cloud.githubusercontent.com/assets/15020827/20308446/0433b8a4-ab55-11e6-927b-168d3ca75fe2.png)

But when I trying to display this string in my test application, I have a troubles: in terminal window this text was correctly displayed, but not in my gui-window.
![zxc](https://cloud.githubusercontent.com/assets/15020827/20308476/22931d58-ab55-11e6-92c5-66822b3c7476.png)

project sample:
[9.5.3_DrawText.zip](https://github.com/openfl/openfl/files/592137/9.5.3_DrawText.zip)

Thanks.

**Comment by MSGhero** [comment]
Haxe doesn't use the correct string encoding yet. Last I checked, it will be fixed in the next version. There is a library called unifill that does it, but you'd have to manually edit OpenFL textfield and text engine to use that library. Or wait until Haxe 3.4 comes out.

**Comment by r3d9u11** [comment]
Thank you for your answer and hint!

**Comment by jgranick** [comment]
https://trello.com/c/xI2A76zD/14-improve-utf-8-text-support-in-openfl-text-textfield
