### ISSUE TITLE
Skipping frames when swf framerate is higher than project.xml framerate

### ISSUE THREAD

**Issue by NemoStein** [openfl/openfl#1348]
In swflite (tested on HTML5, Neko and Windows), if the swf fps is higher than the project fps, OpenFL skips some frames of the swf.
This behaviour is predictable in the sense that the skipping rate is proportional. E.g.:
If the **project is set to 30 fps** and the **swf is set to 60 fps**, every even frame of the swf will be skipped.
The inverse (if the swf is set to lower fps than the project) doesn't happens.

This doesn't match the flash target behaviour. In flash the loaded swf will always play at the host swf (the loaded fps is ignored) and this is the expected behaviour.

Visually, in higher fps (e.g.: 60), this isn't easily noticeable, but the biggest problem is that the `Event.ENTER_FRAME` isn't called at all for skipped frames.

[Here is a zip](https://github.com/openfl/openfl/files/597444/Test.zip) with a test project (.fla file included)

Notice how only odd numbers are traced on console and printed on screen.

**Comment by jgranick** [comment]
On some targets (such as HTML5), the project will run with vsync, so it may run 60 GPS  (or on my desktop, 120 FPS) which ruins most animation. SWFLite is designed to use the original FPS, but you can define `swflite-parent-fps" to change the behavior

**Comment by NemoStein** [comment]
Oh, I see... `<haxedef name="swflite-parent-fps" />` solved my problems.
Since this is the native behaviour of Flash and this feature (vsync) may result in unpredictable side-effects (`Event.ENTER_FRAME` and such not firing), shouldn't it be opt-in?

**Comment by jgranick** [comment]
I understand that this is the behavior of Flash, but what if you have a 12 FPS animation, and run at 120 FPS? It will ALWAYS be wrong, unless you make your own manual `gotoAndStop` frame controls, but better for us to handle this ourselves in a smart way IMHO than to force people to do this themselves.

What side effect do you have for the skipped frames, is Event.ENTER_FRAME coming through? Is it skipping a frame action, or something else that you need?

**Comment by NemoStein** [comment]
> Is it skipping a frame action, or something else that you need?

Exactly!
To work around the fact that there is no way a swf can communicate with haxe by traditional means (no event dispatching, no AS3, etc) I've came up with the following solution:
Every exported class from swf extends my `ScriptableMovieClip`, which in turn extends `MovieClip`.
It walks the `currentLabels` array looking for *signals* (stop, goto, doThis, doThat and such) and hooks this action to the label frame.

When the `Event.ENTER_FRAME` fires in such frame the action hooked to it is called and magic happens!
If the `Event.ENTER_FRAME` fails to fire the action doesn't execute.

I hate the idea of code in timeline (this is confusing, error prone, messes with decoupling and this and that and you know what I'm talking about), but there must be a way to control timeline animations.
To be fair, I only use `stop()` and `dispatchEvent()`.

Here's my (stripped down, only one signal to demonstrate) `ScriptableMovieClip`:
```haxe
package nemostein.swf;

import openfl.display.MovieClip;
import openfl.events.Event;

@:keepSub
class ScriptableMovieClip extends MovieClip
{
	var actions:Map<Int, Void->Void>;
	
	function new ()
	{
		super();
		
		actions = new Map<Int, Void->Void>();
		
		for (label in currentLabels)
		{
			if (label.name == 'stop')
			{
				actions.set(label.frame, onSignalStop);
			}
		}
		
		addEventListener(Event.ENTER_FRAME, onEnterFrame);
	}
	
	function onSignalStop() 
	{
		stop();
	}
	
	function onEnterFrame(event:Event):Void 
	{
		var action = actions.get(currentFrame);
		if (action != null)
		{
			action();
		}
	}
}
```

**Comment by jgranick** [comment]
When we skip a frame (due to varying FPS), perhaps we should still check if it has a frame script, and execute that? Is that the issue you were having? (Leap frogging over a "stop" frame action, for example). BTW, you can also use `addFrameScript`

**Comment by jgranick** [comment]
Ah, I guess this is already the behavior!

https://github.com/openfl/openfl/blob/develop/openfl/display/MovieClip.hx#L220-L237

I'm going to close for now, let me know if you run into problems :smile:
