### ISSUE TITLE
Embedding fonts on ios doesn't work 4.4.1 current develop branch

### ISSUE THREAD

**Issue by matthewswallace** [openfl/openfl#1349]
I'm not sure if this problem is in Lime or OpenFL but I tried using latest develop branches of both as of the date of creating this ticket and Fonts do not embed when building for iOS

**Comment by jgranick** [comment]
When you build with the current release of Lime, `-verbose`should show the embedded name of the fonts you include. Try using that name in your `textFormat` with fonts.

Does the `AddingText` or `PiratePig` sample show correct fonts for you?

**Comment by jgranick** [comment]
I tried "PiratePig" just now, and the embedded font is working fine on the iPad. Let me know if you continue to have trouble, and we can dig into the specific case that doesn't appear to be working. Thank you for your help :smile:
