### ISSUE TITLE
Pitch shifting/bending

### ISSUE THREAD

**Issue by matrefeytontias** [openfl/openfl#1350]
Before the major refactor of version 4 and upwards (that is, at least in 3.6.1), `openfl.media.SoundChannel` exposed an undocumented `pitch` member variable that allowed for pitch shifting on native targets. Looking through the documentation, there doesn't seem to be a way to do that anymore, which is too bad since this is a very good thing to have in a game.

**Comment by alexandervrs** [comment]
Yes, I agree that'd be a great thing to have for game audio

**Comment by jgranick** [comment]
Ultimately, this would be an improvement to the Lime `AudioSource` API. We aren't going to change the API on the OpenFL side :smile:

**Comment by jgranick** [comment]
This issue was moved to openfl/lime#871
