### ISSUE TITLE
SharedObject Async file write

### ISSUE THREAD

**Issue by mastef** [openfl/openfl#1351]
As mentioned here: https://github.com/openfl/openfl/issues/593#issuecomment-96283033 by @MSGhero  it would be great to have an option of having SharedObject async writing possible.

Use-case : E.g. to reduce lags while doing any file writes during a game ( auto-save, save on first move, etc ). On some platforms small lags can be felt - e.g. Android.

It would be great to be able to do the SharedObject save as Async instead, so it doesn't stop the whole execution just for the file-open/write.

**Comment by jgranick** [comment]
I'm sure that would be possible for most platforms, though I'm unsure about how it would work on Android. Due to the unique thread behavior on Android, calling native APIs from a different Haxe thread might either not work, or might not improve performance

**Comment by jgranick** [comment]
Tracking here: https://trello.com/c/9Pkl8vG8/27-consider-adding-async-sharedobject-file-write-support
