### ISSUE TITLE
Image rendering issue with HTML5 and Neko/Windows build

### ISSUE THREAD

**Issue by sfiq** [openfl/openfl#1352]
![Rendering issue between builds](https://puu.sh/snpjr/2ce9dac616.jpg)
For some reason the images are being rendered incorrectly, I've checked with CodeXL (OpenGL Debugger) and the textures that's loaded to the GPU looks exactly like this so it's no bug with my shaders.

At first I've tried using Assets.getBitmapData() from openfl.Assets to upload the image like this
```GL.texImage2D(GL.TEXTURE_2D, 0, GL.RGBA, Width, Height, 0, GL.RGBA, GL.UNSIGNED_BYTE, bitmapData.image.data);``` causing this to happen.

Oddly enough, using Assets.getImage() from lime.Assets resolves the issue.
I'm not too sure what's causing this to happen but it's one weird bug.

**Comment by jgranick** [comment]
When you load from OpenFL, it makes textures BGRA on native. libcairo uses BGRA, so it improves performance moving to/from software rendering :smile:

**Comment by sfiq** [comment]
Ah that makes sense, I thought it was a bug but it never occurred to me that color format is different.
