### ISSUE TITLE
Playing sound from the same source breaks on HTML5

### ISSUE THREAD

**Issue by matrefeytontias** [openfl/openfl#1368]
Forcing a sound file to loop by playing it several times (via SOUND_COMPLETE) breaks it after a number of iterations dependent on the target. It seems to be one iteration for neko and around 7 for C++, for example. See https://github.com/HaxePunk/HaxePunk/blob/dev/com/haxepunk/Sfx.hx ; this code is part of HaxePunk but only uses OpenFL. This code has not been touched since OpenFL 3.6.1 (which does work with it), but the erroneous behaviour happens on every OpenFL 4 version.

EDIT : instance of the problem with HaxePunk

```Haxe
import com.haxepunk.Scene;
import com.haxepunk.Sfx;

class MainScene extends Scene
{
    override public function begin()
    {
        (new Sfx("audio/music.ogg")).loop();
    }
}
```

**Comment by vroad** [comment]
There was a bug that double deletes the same OpenAL source, but this bug was introduced in relatively recent version of lime.

Since OpenAL implementations are free to reuse the same source id for new audio source, deleting the same source again could lead to unexpected behavior (such as deleting the source currently in use).

https://github.com/openfl/lime/commit/2f2cc8e1d5ac3a95a2a23862fe8905a6f62d6dbd

**Comment by matrefeytontias** [comment]
Is this the commit that introduced the bug or the fix ? Using HaxePunk with git OpenFL and Lime' git repos suddenly makes Haxe hangs when compiling. The issue is not from HaxePunk as well, since it compiles fine with 4.4.1 and 3.4.1 respectively.

**Comment by matrefeytontias** [comment]
Alright, looping is fixed on all targets. There is a different issue now though, and it only shows up with HTML5 : whenever one single sound asset is loaded from different points in the program, only one instance can be played at a time, playing the other will have no effect. Again, it uses the HaxePunk code I posted above, and again it was working before OpenFL 4 / Lime 3. Example code :
```Haxe
import com.haxepunk.HXP;
import com.haxepunk.Scene;
import com.haxepunk.Sfx;

class MainScene extends Scene
{
	override public function begin()
	{
		var s1 = new Sfx("audio/music.ogg");
		var s2 = new Sfx("audio/music.ogg");
		s1.play();
		HXP.alarm(1., function (_:Dynamic) { s2.play(); }); // doesn't play a thing
	}
}
```

**Comment by jgranick** [comment]
Thanks for your feedback, it seems that we cannot play the same sound back multiple times at once in howler.js, unless I am mistaken. I have opened an issue here:

https://github.com/goldfire/howler.js/issues/682
