### ISSUE TITLE
Event dispatching works differently on OpenFL when listeners are added/removed inside an listener

### ISSUE THREAD

**Issue by vroad** [openfl/openfl#1369]
This difference makes Starling v2 work differently on OpenFL. If you add another `CONTEXT3D_CREATE` listener inside an `CONTEXT3D_CREATE` listener like this, Context3D gets recreated right after first creation.

https://github.com/Gamua/Starling-Framework/blob/62834683211b7928448e75c6ac6d02cac220e183/starling/src/starling/core/Starling.as#L582

Starling's built-in event dispatcher avoids this problem like this.
- create copy of Vector(listener list) when removeEventListener is called
- save number of listeners before entering dispatch loop

So events are dispatched correctly even if you remove/add listeners in a listener.

https://github.com/Gamua/Starling-Framework/blob/e81c1d869a3cc53ba518557c7fe59c634d34e649/starling/src/starling/events/EventDispatcher.as#L137-L139

I'm not sure how `EventDispatcher` works on OpenFL. Why does it have 2 maps rather than 1 map?
https://github.com/openfl/openfl/blob/e966c7237160579ced5a117764a7611a55a82f70/openfl/events/EventDispatcher.hx#L13-L14

**Comment by jgranick** [comment]
Does this still occur with the latest development build of OpenFL? How can I test this? Thanks :smile:

**Comment by vroad** [comment]
My build is based on openfl 4.4.1. How are event listeners handled now?

I only saw this issue on starling v2.0 port. Starling adds listener for context recreation inside an listener, and that causes unnecessary context recreation.

**Comment by jgranick** [comment]
Recently, we went through a lot of test cases for event dispatching, with fixes. If you experience any specific issues with the current version that we can replicate in a small sample, let me know :smile:
