### ISSUE TITLE
Lib.application.window.title = value seems to change the window title but crash the application

### ISSUE THREAD

**Issue by alexandervrs** [openfl/openfl#1372]
I have a function in my app's Window class to change the window title on the fly, it seems that it works but shortly after the application crashes.

```haxe
public inline function SetTitle(text:String):Void {
	Lib.application.window.title = text;
}
```

Using OpenFL 4.4.1 on Windows 10 64bit

**Comment by jgranick** [comment]
Thank you, it is fixed now :smile:

The Window class is in Lime, so that would be the best place for reports like this, but no worries :grin:

https://github.com/openfl/lime/commit/78bc7aa6a32a9ce2e6714edcac8c3b526765c69c
