### ISSUE TITLE
TextField can not enter Chinese in HTML5

### ISSUE THREAD

**Issue by cjmxp** [openfl/openfl#1376]
TextField can not enter Chinese in HTML5

My system is Mac OS browser is Frefox。

Safari can not be entered correctly。

OpenFL Command-Line Tools (4.4.1-LfOW60)

**Comment by cjmxp** [comment]
My system is Mac OS browser is Frefox

**Comment by jgranick** [comment]
Can you tell if the input events come through properly, or if this is a rendering issue?

**Comment by jgranick** [comment]
Possibly related to: https://trello.com/c/xI2A76zD/14-improve-utf-8-text-support-in-openfl-text-textfield

**Comment by RblSb** [comment]
I think these two issues can be closed?
