### ISSUE TITLE
List minimum requirements on the main website for exported builds?

### ISSUE THREAD

**Issue by alexandervrs** [openfl/openfl#1377]
Is it possible to have a section on the website that lists the minimum requirements for exported executables? Some stores like Steam require that you know that information so you can list the requirements better for your customers. I could not really find any info about it in the main website.

e.g.
**OpenFL executables minimum requirements for exported builds**

**Windows**
Windows Vista or newer, 32 or 64bit
DirectX 11 or newer
Pixel Shader 2 or newer

**Mac OSX**
Mac OSX 10.6

**Linux**
Ubuntu 14.04 LTS 64bit
Shared libraries installed:
joystick
openssl
...

**Android**
Android 4.1, API Level 16

etc.

**Comment by jgranick** [comment]
That would probably be helpful, we try to keep the minimum requirements such that it targets the vast majority of users (like 99%) for each platform.

I believe we support Windows XP (depending on the Visual Studio compiler used), but we don't test for it. I think OpenGL version 3 is required for hardware acceleration, but we fallback to software rendering for older graphics drivers.

macOS 10.6 (x86_64) is probably correct for the minimum there.

Linux we currently build on Ubuntu 14.04, but until recently built on 12.04. We support practically any distribution out-of-the-box, but other distributions can be supported by rebuilding Lime from the source (such as an old centOS or other distribution with old glibc versions). I'm not aware of any serious package requirements at runtime, I believe most of them are optional, so certain features will just not work if you have no audio libraries, for example.

We should be supporting Android 2.3 (API 9) and greater, so long as the device supports GLES2. We similarly support basically any version of iOS you want to support.

**Comment by jgranick** [comment]
I've opened a topic here to discuss it more, thanks :smile: http://community.openfl.org/t/minimum-runtime-requirements-for-openfl-projects/8591
