### ISSUE TITLE
Stage3D creates Context3D even when it's not requested

### ISSUE THREAD

**Issue by vroad** [openfl/openfl#1378]
Not only this create unnecessary context even when it's not needed, but also causes rendering issues on Starling v2.0.
Starling misunderstands that context is shared because Stage3D already has Context3D instance, and does not render anything. :worried:

https://github.com/openfl/openfl/blob/cfe82edd6f10575fee5d58d4040baabd25a4e31e/openfl/_internal/renderer/opengl/GLRenderer.hx#L62-L66

Looking at your code in openfl, there seems to be many piece of code that does the almost same thing.

https://github.com/openfl/openfl/blob/9b27b24317808d470ee6f0e1923575b3e2957806/openfl/display/Stage3D.hx#L220-L224
https://github.com/openfl/openfl/blob/9b27b24317808d470ee6f0e1923575b3e2957806/openfl/display/Stage3D.hx#L168-L173

Have you ever heard of a principle named "DRY(Don't repeat yourself)"?
It should be possible to reduce duplicates like that, instead of writing everything twice(WET). It's not easy for other people to understand WET code, and of course bad for maintainability. I'm not certain how many places I should modify to make some changes to WET code, because code is just copied and pasted everywhere...

I have hard time understanding your code... Why not just dispatch CONTEXT3D_CREATE event when context is created?? It's a lot easier.

https://github.com/openfl/openfl/blob/9b27b24317808d470ee6f0e1923575b3e2957806/openfl/display/Stage3D.hx#L154-L159

I'm not sure why Context3D needs RenderSession, because it looks unused.

**Comment by jgranick** [comment]
I understand that the code seems to go through possibly unneeded steps.

When you `requestContext3D` in Flash, it does not dispatch immediately. If you request a context repeatedly, it will dispatch `CONTEXT3D_CREATE` events, so long as it has not dispatched the event yet. Request twice in a row, you will get one event, but request after the event, and you will get another. This is the behavior that the dispatch code in `Stage3D` is meant to emulate. In my tests, it behaves consistently with Flash Player, with one noted exception.

Flash Player has no hardware render context by default, until you `requestContext3D`. OpenFL does on desktop, mobile or WebGL, and optionally (but not by default) has a context on HTML5 `-Ddom`. Unlike Flash Player, we _do_ have a context initialized. Like it or not, `Stage3D` on OpenFL GL targets are _always_ using a shared context. Cooperation between different renderers (such as the OpenFL core renderer, Starling or other libraries) will need to improve more over time.

**Comment by vroad** [comment]
Is it really impossible if Context3D is not initialized instantly??
Let me have a look at those code. Also I'd like to find a solution without too much duplicates.

**Comment by vroad** [comment]
I think that just creating `Context3D` after 1ms delay works:
 - Don't schedule anything if one is pending
 - After delay, check if current renderer supports Stage3D. if not, dispatch error event.
 - Create `Context3D` if one is not there
 - Dispatch success event

That way you don't have to insert `__createContext` everywhere.

According to API reference, it throws exceptions when you request another context with different profile, if one is pending. 

> Making it available instantly allows for deeper integration between Stage3D, the core OpenFL renderer, and new features such as render-to-texture inside OpenFL
I'm not sure why it helps, you still have to deal with lots of state changes OpenFL renderer makes. It still gets broken regardless of when it's created, and we should find real solution instead of adding lots of workarounds, which may introduce other bugs...

I was thinking of creating OpenGL state wrapper that is shared by all OpenFL classes, which reverts all state changes at the beginning of rendering. You just have to make sure that you make state changes via this class. That should work regardless of Context3D creation timing, as long as you save/restore all states.

**Comment by vroad** [comment]
I've found that you are allocating Stage3D textures in `GLRenderer`, but why not allocating that by yourself? Also, this depends on single context setting. Does not look future-proof, I'm not sure what happens if you dispose `Context3D` or if you have multiple Stage3Ds.

The name "BitmapData.fromTexture()" might be a little confusing. It's not obvious whether it accepts `GLTexture` or `openfl.display3D.textures.Texture`.

**Comment by vroad** [comment]
Not sure why you want to create Stage3D textures inside `GLRenderer`. Maybe you just wanted to save rendered result to texture. Does anybody want that from Stage3D? Or it just doesn't have to be Stage3D, and you just tried to save yourself from some typing?

As I said before, rendering to texture is an expensive operation. Try not to use that when possible.
Starling does not do that for caching rendered results because it's expensive.

https://github.com/openfl/openfl/blob/cfe82edd6f10575fee5d58d4040baabd25a4e31e/openfl/_internal/renderer/opengl/GLRenderer.hx#L220-L250

There doesn't seem to be a way to disable this feature. Is everybody forced to use cached texture?

I just want to be able to use Stage3D without hidden implemantation difference like this.

**Comment by jgranick** [comment]
Does anyone else have an opinion on this?

**Comment by jgranick** [comment]
We can continue discussing this on Slack or the forums. This is not a bug, so I'm taking it down from Github Issues. Thank you so much for caring so much about this, I hope that we can find the best solution long-term :grin:
