### ISSUE TITLE
Video extends DisplayObject

### ISSUE THREAD

**Issue by kasparsj** [openfl/openfl#1382]
I'm getting these errors in javascript, when clicking on videos:
```Uncaught TypeError: target.get_tabEnabled is not a function(…)```

I guess the solution would be to have Video extend InteractiveObject, at least for:
```#if js```

**Comment by jgranick** [comment]
`Video` behaves similar to `Bitmap`, if we are looking for a hit test, it's supposed to help trigger the hit test (you hit an object!) but the target should be the parent interactive object (usually a sprite). I copied code from `Bitmap` and the error went away for me :smile:

**Comment by kasparsj** [comment]
Thanks
