### ISSUE TITLE
Current issues with BitmapaData.draw()

### ISSUE THREAD

**Issue by ramsestom** [openfl/openfl#1383]
- Blend modes are ignored on cpp targets. This is always the default BlendMod.ADD mode that is used whatever the BlendMode parametter passed to the function

- On ccp and html5 targets, using a matrix in combination with a Colortransform crop the drawn object if the matrix change the size or position of the drawn object. Only part of the object remaining in the region where the object will be drawn without a matrix transform is visible. For exemple applying a colortransform and a matrix.translate(10, 5) to a (20,20) square object result in a (10,15) rectangle to be drawn (with the colortransform applied to it)...

**Comment by jgranick** [comment]
Does anyone want to take a look at this?

**Comment by jgranick** [comment]
I've opened two new cards in Trello (where I'm beginning to track improvements to OpenFL)

https://trello.com/c/2POUb5xF/32-add-support-for-bitmapdata-draw-with-blend-modes
https://trello.com/c/aHfsznNZ/33-improve-support-for-bitmapdata-draw-with-colortransform

Thank you :smile:
