### ISSUE TITLE
Update timing of Stage3D's VideoTexture

### ISSUE THREAD

**Issue by vroad** [openfl/openfl#1385]
You are simply updating texture inside this method, but what happens if you use VideoTexture multiple times in a single frame? Multiple unnecessary upload? Unexpected thing may happen if textures are updated between each calls.

You could avoid that with frame counter, or register it to somewhere and update every frame.

Also, why did you do this in a method named `__getTexture()`? It's not clear what this method does unless you see source code.
You have to make sure that you don't call this in a functions that doesn't render, that is pretty hard to guess for others.
Why shouldn't this be a separate call, like `updateVideoTexture()`?

https://github.com/openfl/openfl/blob/develop/openfl/display3D/textures/VideoTexture.hx#L63-L81

**Comment by jgranick** [comment]
I agree, updating only if the texture is dirty would be better. Does anyone want to take a crack at this? Thanks

**Comment by jgranick** [comment]
I've added this as an enhancement here :smile: https://trello.com/c/YB8sxsvE/30-improve-stage3d-videotexture-to-only-update-when-the-video-changes
