### ISSUE TITLE
OpenGL Texture and cairo surface are not disposed in BitmapData.dispose()

### ISSUE THREAD

**Issue by vroad** [openfl/openfl#1389]
This could be bad for performance, since timing of resource destruction with finalizers is non-deterministic. At least on .NET and on Java, objects with finalizers are promoted to older generations and live longer. It may never get called if your application is short-lived.

I'm afraid that it will cause memory bloats as VM doesn't know anything about external memory, like cairo surface and OpenGL texture. If too many objects are destroyed in a row, that may cause GC stall.

Not removing OpenGL resources might be more problematic because it's often put in a separate memory space (VRAM), which decreases memory pressure to main memory and causes GC to take longer.

https://github.com/openfl/openfl/blob/cfe82edd6f10575fee5d58d4040baabd25a4e31e/openfl/display/BitmapData.hx#L385

https://msdn.microsoft.com/en-us/library/ff647790.aspx?f=255&MSPPError=-2147217396#scalenetchapt05_topic10

> - **Avoid implementing a Finalize method.** The garbage collector must promote finalizable objects to older generations to facilitate finalization, which makes them long-lived objects.

Java has the same performance penalty for finalizers:

http://stackoverflow.com/questions/2860121/why-do-finalizers-have-a-severe-performance-penalty

**Comment by jgranick** [comment]
I'm afraid that there may be errors in rendering if we remove these surfaces immediately, while they are still used somewhere inside the render process. We could forcibly remove them on dispose if that's better for GC, but there's a risk that it will not be well-tested, and will cause crashes

**Comment by vroad** [comment]
I think that app should stop working with clear error message (such as "BitmapData is already disposed") if you try to use already disposed BitmapData, at least in debug mode. If there is any code that may bind already deleted textures, that should be considered bad code and should be fixed.

Some implementations may collect those resources more aggressively but others may don't. So we shouldn't rely on that.

**Comment by jgranick** [comment]
We don't actually have a way to force delete a Cairo software surface at the moment (since the garbage collection improvements) and we don't necessarily know the GL state. Perhaps we could force a GC run in dispose? Otherwise, we'll have to look at deeper changes/improvements inside to allow forced deletion. Thank you
