### ISSUE TITLE
Bitmap smoothing set to false on changing bitmapData

### ISSUE THREAD

**Issue by hiepth** [openfl/openfl#1391]
Function set_bitmapData in Bitmap.hx should not change value of smoothing to false.

	private function set_bitmapData (value:BitmapData):BitmapData {
		
		bitmapData = value;
		//smoothing = false;

**Comment by jgranick** [comment]
Please test on Flash Player, and see if it changes smoothing to false on `bitmapData` changes. This was changed, since this is how I believe Flash Player treats changes. Thanks :smile:

**Comment by hiepth** [comment]
So what we need here is directive?
#if flash
smoothing = false;
#end

**Comment by jgranick** [comment]
If you try changing `bitmap.bitmapData` on the Flash target, I believe it changes `smoothing` to false again, in many APIs, we mean for OpenFL to behave similarly to Flash Player, so that's why we do the same, but please let me know if you test and Flash Player does not do this, thanks :smile:
