### ISSUE TITLE
issues with Preloader

### ISSUE THREAD

**Issue by derhab** [openfl/openfl#1393]
Hello,

I try to use develop branch (openfl 4.5.2, lime 3.5.2)
At building project for html5 target I get following issue:
When loading swf library, preloader not working properly, the ProgressEvent comes only twice, at the beginning and end of the loading.
In project.xml:
<library path="assets/screens.swf" preload="true"/>

**Comment by MSGhero** [comment]
This is a normal thing that happens in flash when you test locally because you have access to all the bits already. Are you testing locally?

**Comment by derhab** [comment]
No, I tested it on a remote server, too.

**Comment by jgranick** [comment]
Previously, SWF libraries actually used the standard asset library in order for preloading to work properly. With the revision of our asset library system (to enable SWF libraries to preload separately) it aggravated another problem -- the preload events were dispatched for only one standard asset library, and the others were loaded after.

I've just hacked support in for the OpenFL and Lime development branches to allow SWF preloading as a part of the standard preload process. Could you take a look and see if it is working better for you?

Thank you :smile:

**Comment by derhab** [comment]
I have just tested, but preloader unfortunately is still not working properly.

**Comment by jgranick** [comment]
Other than sparse progress events, is it working properly?

**Comment by derhab** [comment]
The current situation is as follows:
I created a custom preloader, progress events come normally, but their values are incorrect
Progress events handler:
```
`private function this_onProgress (e:ProgressEvent):Void
{
	trace ("bytesLoaded: " + e.bytesLoaded, " bytesTotal: " + e.bytesTotal);
}`
```

Output:
```
Preloader.hx:87: bytesLoaded: 0, bytesTotal: 6
Preloader.hx:87: bytesLoaded: 1, bytesTotal: 6
Preloader.hx:87: bytesLoaded: 2, bytesTotal: 6
Preloader.hx:87: bytesLoaded: 3, bytesTotal: 6
Preloader.hx:87: bytesLoaded: 4, bytesTotal: 6
Preloader.hx:87: bytesLoaded: 5, bytesTotal: 6
Preloader.hx:87: bytesLoaded: 6, bytesTotal: 6
Preloader.hx:87: bytesLoaded: 7, bytesTotal: 6
Preloader.hx:87: bytesLoaded: 8, bytesTotal: 6
Preloader.hx:87: bytesLoaded: 9, bytesTotal: 6
Preloader.hx:87: bytesLoaded: 10, bytesTotal: 6
Preloader.hx:87: bytesLoaded: 11, bytesTotal: 6
Preloader.hx:87: bytesLoaded: 183, bytesTotal: 6
.......
Preloader.hx:87: bytesLoaded: 196, bytesTotal: 6
Preloader.hx:87: bytesLoaded: 197, bytesTotal: 6
Preloader.hx:87: bytesLoaded: 198, bytesTotal: 6
Preloader.hx:87: bytesLoaded: 198, bytesTotal: 6
Preloader.hx:96: load complete
```
Obtained values seem strange ... the total data amount is about 13 mb

**Comment by jgranick** [comment]
Thanks, we need to work more on the new preload system, ultimately I think we need to embed the file sizes in the asset manifest, so we know in advance how large the full asset list will be before we download

**Comment by jgranick** [comment]
I'm tracking this improvement here, thanks :smile:

https://trello.com/c/Yyk00pai/44-improve-the-quality-of-progress-events-for-core-assetlibrary-types
