### ISSUE TITLE
Issue with transparency of bitmaps with jpeg compression setting in swf library

### ISSUE THREAD

**Issue by derhab** [openfl/openfl#1394]
And one more issue (develop branch, openfl 4.5.2, lime 3.5.2)
At using a swf library, images in library, which have transparent areas (and in the properties panel have jpeg compression), shown with black areas in places where there should be a transparent pixels.
However, when using openfl 4.5.0 and lime 3.5.0, it works correctly. Despite the jpeg compression in swf, we have a normal transparent pixels.2. At using a swf library, images in library, which have transparent areas (and in the properties panel have jpeg compression), shown with black areas in places where there should be a transparent pixels.
However, when using openfl 4.5.0 and lime 3.5.0, it works correctly. Despite the jpeg compression in swf, as a result we have a normal transparent pixels.

**Comment by jgranick** [comment]
Please try the latest round of commits, I've made a lot of changes that should improve the situation here. Thanks :smile:

**Comment by derhab** [comment]
Thanks, now it works correctly!
