### ISSUE TITLE
Huge project compilation speed decrease on library upgrade

### ISSUE THREAD

**Issue by infidel-** [openfl/openfl#1395]
This might be a lime issue but I've no idea how to separate it from openfl. I've been using openfl 3.6.1 and lime 2.9.1 for some time (Haxe 3.2.1). I've just upgraded it to openfl 4.5.2 and lime 3.5.2 and I've immediately noticed a significant compilation speed decrease, especially when using the compilation server. I'm also using HaxePunk engine on top of it but it doesn't seem like the problem is in there because the results for older library versions + engine are very good.

I've set the haxelib library versions and restarted compilation server every time. I also ran openfl command to build project first but then used haxe directly to remove the additional compilation commands.

Before (generated HXML):
```
-main ApplicationMain 
-cp /home/infidel/haxelib/HaxePunk/2,6,0
-D HaxePunk=2.6.0
-cp /home/infidel/haxelib/openfl/3,6,1
-D openfl=3.6.1
-cp /home/infidel/haxelib/lime/2,9,1
-D lime=2.9.1
-cp ./
-D source-header=haxe
-D openfl-next
-D tools=2.9.1
-D no-compilation
-D lime-opengl
-D openfl-html5
-D canvas
-D webgl
-D lime-html5
-D tile_shader
-D mydebug
-D verbose=1
-D html5
-D web
--macro com.haxepunk.utils.Platform.run()
--remap flash:openfl
--connect
6000
-js .bin/html5/bin/parasite.js
-cp .bin/html5/haxe
-D html5
--macro allowPackage("flash")
```

Before:
```
infidel@purplestar ~/p/parasite-OLDHTML5> time haxe .bin/html5/haxe/release.hxml
0.02user 0.05system 0:04.43elapsed 1%CPU (0avgtext+0avgdata 12108maxresident)k
0inputs+0outputs (0major+944minor)pagefaults 0swaps

infidel@purplestar ~/p/parasite-OLDHTML5> time haxe .bin/html5/haxe/release.hxml
0.04user 0.01system 0:01.12elapsed 5%CPU (0avgtext+0avgdata 12172maxresident)k
0inputs+0outputs (0major+926minor)pagefaults 0swaps

infidel@purplestar ~/p/parasite-OLDHTML5> time haxe .bin/html5/haxe/release.hxml
0.05user 0.01system 0:01.08elapsed 6%CPU (0avgtext+0avgdata 12164maxresident)k
0inputs+0outputs (0major+924minor)pagefaults 0swaps

```
We see close to 5 sec compilation on the first attempt and close to 1 sec on the subsequent ones which is excellent and is my target goal.

After (HXML):
```
-main ApplicationMain 
-cp /home/infidel/haxelib/HaxePunk/2,6,0
-D HaxePunk=2.6.0
--macro openfl._internal.utils.ExtraParams.include()
-cp /home/infidel/haxelib/openfl/4,5,2
-D openfl=4.5.2
--macro lime.Lib.extraParams()
-cp /home/infidel/haxelib/lime/3,5,2
-D lime=3.5.2
-cp ./
-D source-header=haxe
-D tools=3.5.2
-D howlerjs
-D no-compilation
-D lime-opengl
-D openfl-html5
-D webgl
-D lime-html5
-D tile_shader
-D mydebug
-D verbose=1
-D html5
-D web
--macro com.haxepunk.utils.Platform.run()
--remap flash:openfl
--connect
6000
-js .bin/html5/release/bin/parasite.js
-cp .bin/html5/release/haxe
-D html5
```

After:
```
infidel@purplestar ~/p/parasite> time haxe .bin/html5/release/haxe/release.hxml
0.02user 0.02system 0:07.39elapsed 0%CPU (0avgtext+0avgdata 12112maxresident)k
0inputs+0outputs (0major+945minor)pagefaults 0swaps

infidel@purplestar ~/p/parasite> time haxe .bin/html5/release/haxe/release.hxml
0.03user 0.02system 0:05.43elapsed 1%CPU (0avgtext+0avgdata 12036maxresident)k
0inputs+0outputs (0major+925minor)pagefaults 0swaps

infidel@purplestar ~/p/parasite> time haxe .bin/html5/release/haxe/release.hxml
0.02user 0.02system 0:05.96elapsed 0%CPU (0avgtext+0avgdata 12248maxresident)k
0inputs+0outputs (0major+945minor)pagefaults 0swaps
```

7 seconds before, 6 seconds after. Not only there's a huge (in relative terms) drop in compilation speed when using the compilation server but it's also just not helping much. 

Building for windows platform is even worse overall (there's also a separate issue of the resulting EXE file not working at all).

Before (HXML):
```
-main ApplicationMain 
-cp /home/infidel/haxelib/HaxePunk/2,6,0
-D HaxePunk=2.6.0
-cp /home/infidel/haxelib/openfl/3,6,1
-D openfl=3.6.1
-cp /home/infidel/haxelib/lime/2,9,1
-D lime=2.9.1
-cp ./
-D source-header=haxe
-D lime-openal
-D openfl-next
-D tools=2.9.1
-D lime-cairo
-D no-compilation
-D lime-opengl
-D native
-D lime-native
-D lime-curl
-D openfl-native
-D tile_shader
-D mydebug
-D windows
-D desktop
--macro com.haxepunk.utils.Platform.run()
--remap flash:openfl
--connect
6000
-cp .bin/windows/neko/haxe
-neko .bin/windows/neko/obj/ApplicationMain.n
--macro keep("Main")
```

Before:
```
infidel@purplestar ~/p/parasite-OLDHTML5> time haxe .bin/windows/neko/haxe/release.hxml
0.03user 0.01system 0:07.69elapsed 0%CPU (0avgtext+0avgdata 12244maxresident)k
0inputs+0outputs (0major+943minor)pagefaults 0swaps

infidel@purplestar ~/p/parasite-OLDHTML5> time haxe .bin/windows/neko/haxe/release.hxml
0.01user 0.04system 0:03.49elapsed 1%CPU (0avgtext+0avgdata 12104maxresident)k
0inputs+0outputs (0major+943minor)pagefaults 0swaps

infidel@purplestar ~/p/parasite-OLDHTML5> time haxe .bin/windows/neko/haxe/release.hxml
0.01user 0.04system 0:01.88elapsed 2%CPU (0avgtext+0avgdata 12104maxresident)k
0inputs+0outputs (0major+943minor)pagefaults 0swaps
```
8 sec -> 2 sec. Worse than HTML5 but is pretty good considering I also get the benefit of convenient stack traces on errors during the development.

After (HXML):
```
-main ApplicationMain 
-cp /home/infidel/haxelib/HaxePunk/2,6,0
-D HaxePunk=2.6.0
--macro openfl._internal.utils.ExtraParams.include()
-cp /home/infidel/haxelib/openfl/4,5,2
-D openfl=4.5.2
--macro lime.Lib.extraParams()
-cp /home/infidel/haxelib/lime/3,5,2
-D lime=3.5.2
-cp ./
-D source-header=haxe
-D lime-openal
-D tools=3.5.2
-D lime-cairo
-D no-compilation
-D lime-opengl
-D native
-D lime-native
-D lime-curl
-D openfl-native
-D tile_shader
-D lime-cffi
-D mydebug
-D windows
-D desktop
--macro com.haxepunk.utils.Platform.run()
--remap flash:openfl
--connect
6000
-cp .bin/windows/neko/release/haxe
-neko .bin/windows/neko/release/obj/ApplicationMain.n
--macro keep("Main")
```

After:
```
infidel@purplestar ~/p/parasite> time haxe .bin/windows/neko/release/haxe/release.hxml
0.03user 0.08system 0:11.32elapsed 0%CPU (0avgtext+0avgdata 12112maxresident)k
0inputs+0outputs (0major+944minor)pagefaults 0swaps

infidel@purplestar ~/p/parasite> time haxe .bin/windows/neko/release/haxe/release.hxml
0.05user 0.02system 0:08.59elapsed 0%CPU (0avgtext+0avgdata 12168maxresident)k
0inputs+0outputs (0major+924minor)pagefaults 0swaps

infidel@purplestar ~/p/parasite> time haxe .bin/windows/neko/release/haxe/release.hxml
0.03user 0.04system 0:07.77elapsed 0%CPU (0avgtext+0avgdata 12040maxresident)k
0inputs+0outputs (0major+926minor)pagefaults 0swaps
```
11 seconds to 7 seconds.

Now for my point. 7 seconds is basically not acceptable for quick iteration during the development. Are there some new flags that I should make use of or some options to speed this up? I couldn't find anything on that issue.

There might be a question why I don't use 3.3.0 or 3.4.0. There's some bug in the macro compilation code somewhere there that breaks the use of compilation server.

**Comment by jgranick** [comment]
These may be relevant:

https://groups.google.com/forum/#!topic/haxelang/nTrTBVQhSvQ
https://github.com/HaxeFoundation/haxe/issues/4826
https://github.com/HaxeFoundation/haxe/issues/5465

**Comment by jgranick** [comment]
We use more Haxe code than we did in OpenFL legacy, I'm very interested in what we could do to speed up our compilation times.

I'm ultimately very interested in a "go-to" fast testing target for iterating over a project. I wonder if we should use JS + a desktop wrapper as a default target, or if CPPIA, HL or some other target could bring our compile times down

**Comment by infidel-** [comment]
Shouldn't all Haxe code cache on the compilation server after the first compilation? Maybe the issue is due to some macro-related stuff?

I can do the HTML5 target already, that brings the compilation down to somewhat bearable 3-4 seconds IIRC. But I don't think it's all due to the target, Neko target was always pretty quick with compilation server enabled.

**Comment by jgranick** [comment]
The Haxe compiler can speed up compilation using cache, but no, it still performs work no matter what. As you (may) have seen in the links I referenced, I haven't gotten any good answers from anyone about what we can do to speed things up, except that I hear that 64-bit Haxe seems to run faster on Windows, and that Windows filesystem emulation in the way the Haxe compiler is built may be the reason Haxe runs slower on Windows.

Beyond this, only experiments may tell what we could do to make Lime and OpenFL build faster 😦

**Comment by jgranick** [comment]
I have opened a new issue here: https://github.com/HaxeFoundation/haxe/issues/5928
