### ISSUE TITLE
Openfl 4.5.2 and lime 3.5.2 Windows EXE generation from Linux fails

### ISSUE THREAD

**Issue by infidel-** [openfl/openfl#1396]
As I've written in the other issue I've been using openfl 3.6.1 and lime 2.9.1 for some time (Haxe 3.2.1). I've just upgraded it to openfl 4.5.2 and lime 3.5.2. I'm using Linux in a VM and now I can't produce a working Windows EXE (Windows 7 64-bit host). I've tried both -32 and -64 options during the build just in case but upon trying to run the resulting EXE file Windows says this: "This version of this file is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need an x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher."

I've attached the resulting EXE file to the issue.

[parasite.zip](https://github.com/openfl/openfl/files/672154/parasite.zip)

**Comment by jgranick** [comment]
I think this is due to this change:

https://github.com/openfl/lime/commit/b6a895b7af547f1146d437c05309171bd39275d5

There were issues with Neko executables not working unless the host system had Neko installed, and with poor performance, and with code size limits, as well as some other Neko-related issues that I feel make it difficult to consider Neko as a release target.

I have started to think of Neko as a testing-only target, but maybe I am wrong, and there are things we can do to improve its use.

We have a few other options, though, for cross-desktop builds we could consider. We have JavaScript support (and could use Electron, Node-Webkit, etc), there's Java, C# and Node.js that could be supported, or we could look at using HXSL, or possibly CPPIA output for the Haxe C++ target.

Open to your input, thank you :smile:

**Comment by infidel-** [comment]
> I think this is due to this change

Are you saying that cross-compilation of Windows target is currently completely broken on Linux? 

```
openfl build project.xml windows
```
Running this under Linux goes through the Neko path (according to the help, it should go through CPP one and I don't know how to force it) producing a broken executable.

Looking at the referenced code it does look like you've broken a working cross-compilation implementation. Why did you do it? :) That probably also concerns the #1388, though I'm not sure if cross-compilation Windows -> Linux worked before, I've never tried it.

> There were issues with Neko executables not working unless the host system had Neko installed, and with poor performance, and with code size limits, as well as some other Neko-related issues that I feel make it difficult to consider Neko as a release target.

Well, a couple of points. I don't know what issues with executables not working you are talking about, but in my case everything worked both on Linux and Windows by putting the appropriate dlls into the game folder. Secondly, poor performance. Are you saying that Neko performance is worse than JS? This does not sound right, though admittedly I haven't checked for some time. And even if it is, the performance is perfectly fine for turn-based games (my case).

What's more important for me is that Neko is much more stable and produces more understandable errors than CPP or JS target in most cases. I've seen enough segmentation faults and "Error in parasite.js:3652" (or something) to say that Neko is the clear winner here. And it compiles faster than CPP. If the other issue I've opened was a non-issue like before, I was looking at 1 second compilation times for Neko which is what I need.

> I have started to think of Neko as a testing-only target, but maybe I am wrong, and there are things we can do to improve its use.

Well, I'm certainly thinking about it as a valid binary target for desktops :)

> We have a few other options, though, for cross-desktop builds we could consider. We have JavaScript support (and could use Electron, Node-Webkit, etc), there's Java, C# and Node.js that could be supported, or we could look at using HXSL, or possibly CPPIA output for the Haxe C++ target.

If the issue is just uncommenting that part of code then I suggest do that instead and add some specific ifs around. If you really hate this piece of code, make it work specifically in the case of cross-compiling with Neko target or mark it as legacy. I've said my thoughts about JS and CPP above, Java is a ridiculous piece of bloatware that needs much more libraries to work on a random user's computer than anything else. HXSL? Isn't that a shader language? If you're talking about Hashlink, I haven't looked at it yet but I'm betting it's not stable or mature enough for production yet.

At the very least it should not just quietly produce a broken executable, it needs a clear error message. And you need to restore the cross-compiling functionality in some way.

**Comment by jgranick** [comment]
I'm tracking this here: https://trello.com/c/5lWukowR/46-add-support-for-cross-desktop-builds

What binaries did you have to copy? The goal was for the output directly to be self-contained

**Comment by infidel-** [comment]
I don't remember anymore in case of Windows platform and switching to older lime and openfl produces the working self-contained directory currently. In case of Linux I had to copy over "libpcre.so.3", the user I tested it with had a different version.
