### ISSUE TITLE
HTML5 display error use openfl 4.5.2 +lime 3.5.2 

### ISSUE THREAD

**Issue by keesungz** [openfl/openfl#1400]
Ou a mobile html5 project  work perfect (openfl 4.41+lime 3.4.1), but **don't display anything** after updated project  to  openfl 4.5.2 +lime 3.5.2 !

The project work right when  I set "Dom" or "canvas" render option at project.xml. I know webgl is default render option, so the problem maybe caused by webgl render. I only use webgl render because I use gl shader filter.

pls give me any advise！

**Comment by jgranick** [comment]
Are there any errors in the JavaScript console?

Do other samples work?

Thank you :smile:

**Comment by keesungz** [comment]
Thank your for your reply! 
No any errors  in the JavaScript console and no other sample。 The project work right in the desktop browser。

**Comment by jgranick** [comment]
So other samples display properly, but only your project does not display when using WebGL?

Would it be possible to try and insert something small into the entry point of your code?

```haxe
var sprite = new Sprite ();
sprite.graphics.beginFill (0xFF0000);
sprite.graphics.drawRect (0, 0, 100, 100);
addChild (sprite);

return;
```

Can you see if that displays for you?

**Comment by keesungz** [comment]
I found the reason caused my project don't display properly. I set "<window allow-high-dpi="true"  />" at project.xml, my project display sprite  if I remove this set, but the image is very blurry！

**Comment by keesungz** [comment]
I found the reason caused my project don't display properly，because I set "window allow-high-dpi="true" " at project.xml. My project display sprite if I remove this set, but the image is very blurry！

**Comment by jgranick** [comment]
Ah hah, great! We'll I'll open a new issue about that:

https://github.com/openfl/openfl/issues/1415

...and we can close this one. Hopefully we can add high-DPI support to HTML5 in the future here. Thank you again for your help :smile:
