### ISSUE TITLE
error: lime.utils.Bytes has no field readFile

### ISSUE THREAD

**Issue by r3d9u11** [openfl/openfl#1401]
Hi. I tried to use FileReference, but have exception:
`/haxelib/openfl/4,5,2/openfl/net/FileReference.hx:116: characters 10-24 : lime.utils.Bytes has no field readFile`

in test was used openfl 4.5.2 and lime 3.5.2 (latest versions in haxelib)

```
package;

import openfl.events.*;
import openfl.display.*;
import openfl.net.FileFilter;
import openfl.net.FileReference;

class Main extends Sprite {
    public function new () {
        super();
        this.onLoadProjBtnClick();
    }

    function onLoadProjBtnClick () : Void {
        var loadRef:FileReference = new FileReference();
        loadRef.browse([new FileFilter('XML', '*.xml')]);
        loadRef.addEventListener(Event.SELECT, function(e:Event) cast(e.target, FileReference).load());
        loadRef.addEventListener(Event.COMPLETE, function(e:Event) trace('selected: ${e.target.data}'));
    }
}
```

Thanks.

**Comment by jgranick** [comment]
Thanks for the report!

This is fixed in development builds, we'll do a release to get this out the door :smile: https://github.com/openfl/openfl/commit/317202db26f19d2d3dff12eac04de25256016357

**Comment by r3d9u11** [comment]
thank you! :)
