### ISSUE TITLE
Improve UTF-8 text support in `openfl.text.TextField`

### ISSUE THREAD

**Issue by jgranick** [openfl/openfl#1402]
Haxe 3.2.1 has limited UTF-8 support on some platforms, @larsiusprime has an implementation of an abstract string that should help make TextField work more appropriately, at the cost of performance. We need to integrate this support by default, or make it available behind a define, for applications using a broader character set

**Comment by jgranick** [comment]
Possibly related: https://github.com/openfl/openfl/issues/1376

**Comment by jgranick** [comment]
Information on a String abstract that may be a good choice for improving UTF-8 in TextField (`String` references internally would be replaced with the abstract

https://gist.github.com/larsiusprime/6cd097b9493c8173a315c68f2bc60457

**Comment by pozirk** [comment]
Yes, really need that. :)
In my case for Android target, I can enter text in Cyrillic, but if I try to delete some letters, the whole string just disappears.
And after that, no matter what I type, even Latin symbols, input stays empty, while there is text in it.

**Comment by pozirk** [comment]
Not fixed!
I still can not type in Cyrillic on native platforms.

**Comment by RblSb** [comment]
@pozirk Could you give an example of a problem code?

**Comment by pozirk** [comment]
Yes!

```
text = new TextField();
...
text.type = TextFieldType.INPUT;
```

Now launch it on Android or Windows or any native target, I suppose, and try to enter Cyrillic letters.
