### ISSUE TITLE
Add further `cacheAsBitmap` support on all renderers

### ISSUE THREAD

**Issue by jgranick** [openfl/openfl#1404]
We should be able to implement `cacheAsBitmap` to trigger framebuffer-based `BitmapData` on GL, and software-based `BitmapData` elsewhere, to further optimization additional rendering

**Comment by jgranick** [comment]
This PR is worth referencing for a `cacheAsBitmap` implementation https://github.com/openfl/openfl/pull/1374

**Comment by francoisvn** [comment]
Any timeline for this? It seems like it would solve a problem I've currently having: http://community.openfl.org/t/flattening-tilemap-for-composite-alpha/9124

**Comment by jgranick** [comment]
This is initially finished. Support for framebuffer-based images would be ideal, but currently it is working using software
