### ISSUE TITLE
Expand `displayObject.mask` support

### ISSUE THREAD

**Issue by jgranick** [openfl/openfl#1406]
In addition to the current square only, full on/off masking that is currently supported, the goal is to enable GLSL-based full masking for hardware targets.

When `cacheAsBitmap` is true for both the mask and the masked object, the alpha from the mask should be used. Otherwise, only `alpha > 0` should be considered for masking.

- [ ] Add GLSL support for masking (with support for different object sizes) in the core shaders
- [ ] Add `cacheAsBitmap` support (using framebuffers), so we can bake a set of objects (such as `Sprite`-based mask) to a single texture we can use for comparing alpha. Use framebuffers for performance
- [ ] Implement the "are both using `cacheAsBitmap`?" behavior for alpha gradient masking
- [ ] Evaluate improved Cairo/canvas support for masks

**Comment by jgranick** [comment]
Blocked by https://github.com/openfl/openfl/issues/1404

**Comment by wushshsha** [comment]
mask

**Comment by jgranick** [comment]
For initial on/off masking on OpenGL, there's some progress on it in this test branch: https://github.com/openfl/openfl/tree/feature/gl-stencil-mask

**Comment by wushshsha** [comment]
This mask still can not work.

**Comment by Greg209** [comment]
An alternative implementation of masking is available in this PR #1709 . It renders the mask to a bitmap and a shader is used to mask the bitmap of the display object. Give it a try and see if provides what you need.

**Comment by wushshsha** [comment]
For example: 
http://community.openfl.org/t/the-mask-dont-work-on-html5-and-html5-dom/8667

**Comment by wushshsha** [comment]
canvas: shape mask is ok!
webgl: shape mask is error!
