### ISSUE TITLE
Add support for `SAMPLE_DATA` / generated sound

### ISSUE THREAD

**Issue by jgranick** [openfl/openfl#1407]

**Comment by starburst997** [comment]
As a starting point, this [class](https://github.com/ncannasse/heaps/blob/master/hxd/snd/NativeChannel.hx) does a pretty good job. Support Flash / HTML5 and Lime OpenAL.

**Comment by jgranick** [comment]
Closed in favor of: https://github.com/openfl/openfl/issues/1705
