### ISSUE TITLE
@:bitmap does not appear to be working in a preloader on native

### ISSUE THREAD

**Issue by jgranick** [openfl/openfl#1416]
> If I do something like this, I can see my Back image on Flash target, but just black or white screen on native:

```haxe
@:bitmap("assets/preload.jpg") class Back extends BitmapData {}
...
public function new()
{
  var bmpd:BitmapData = new Back(width, height);
  var back:Bitmap = new Bitmap(bmpd, PixelSnapping.AUTO, true);
  addChild(back);

  addEventListener(Event.ADDED_TO_STAGE, onInit);
  addEventListener(ProgressEvent.PROGRESS, onUpdate);
  addEventListener(Event.COMPLETE, onLoaded);
}
```

http://community.openfl.org/t/preloader-now-that-nmepreloader-is-depreciated/8437/42

**Comment by jgranick** [comment]
This is currently working, marking as closed :smile:

**Comment by jgranick** [comment]
Opening again until I can confirm on Android

**Comment by jgranick** [comment]
Getting a report that @:font might not work on Flash Player, should test that as well

**Comment by jgranick** [comment]
Working with current builds on Android

`@:font` has also been fixed for Flash Player :shipit:

**Comment by pozirk** [comment]
I've tried preloader with latest openfl/lime, but still don't see my preloader image, only white screen on Windows.

**Comment by jgranick** [comment]
I created a "CustomPreloader" sample yesterday, in the current "openfl-samples" release:

https://github.com/openfl/openfl-samples/tree/master/features/display/CustomPreloader

I modified the `Preloader` class to test an embedded image, and it is working for me here. Could you run `openfl create CustomPreloader` then try using the following code for `Preloader`?

```haxe
package;


import haxe.Timer;
import openfl.display.Bitmap;
import openfl.display.BitmapData;
import openfl.display.Sprite;
import openfl.events.Event;
import openfl.events.ProgressEvent;

@:bitmap("Assets/openfl.png") class Graphic extends BitmapData {}


class Preloader extends Sprite {
	
	
	public function new () {
		
		super ();
		
		var bitmapData = new Graphic (0, 0);
		var bitmap = new Bitmap (bitmapData);
		addChild (bitmap);
		
		addEventListener (Event.COMPLETE, this_onComplete);
		addEventListener (ProgressEvent.PROGRESS, this_onProgress);
		
	}
	
	
	private function update (percent:Float):Void {
		
		graphics.clear ();
		graphics.beginFill (0x1F9DB2);
		graphics.drawRect (0, 0, stage.stageWidth * percent, stage.stageHeight);
		
	}
	
	
	private function this_onComplete (event:Event):Void {
		
		update (1);
		
		// optional
		
		event.preventDefault ();
		
		Timer.delay (function () {
			
			dispatchEvent (new Event (Event.UNLOAD));
			
		}, 2000);
		
	}
	
	
	private function this_onProgress (event:ProgressEvent):Void {
		
		if (event.bytesTotal <= 0) {
			
			update (0);
			
		} else {
			
			update (event.bytesLoaded / event.bytesTotal);
			
		}
		
	}
	
	
}
```

**Comment by pozirk** [comment]
I found the problem, if I have this listener, preloader image doesn't show up, why?
`addEventListener(Event.ADDED_TO_STAGE, onInit);`
Otherwise it works fine.

Also, I have
`var bmpd:BitmapData = new Back(screenWidth, screenHeight);`
and _screenWidth_ with _screenHieght_ have no effect on image.
Sometime image can be smaller then screen and should be scaled.
Although it can be easy fixed later with
```
back.width = screenWidth;
back.height = screenHeight;
```

**Comment by jgranick** [comment]
I tested using different numbers for the `width` and `height` arguments, but they are ignored on Flash. It seems like these parameters should be optional (which I could do on non-Flash targets) but that would break compatibility with Flash, so that's why we have it there for now.

I added an `ADDED_TO_STAGE` listener, but it did not break the preloader. Perhaps this is a timing issue?

If the preloader does not really need to display, it may be `ADDED_TO_STAGE`, then immediately it is `COMPLETE` and is removed. This would appear to have never displayed.

In this sample I am using `event.preventDefault ()` on the preloader, and dispatching `Event.UNLOAD` manually. This is optional. If you do not, it will be removed immediately.

Using the latest, you can also add `-Dsimulate-preloader` or `-Dsimulate-preloader=4000` (with the MS time you want to test) and it will fake the progress and complete events. This may also be helpful when testing your preloader :smile:

**Comment by pozirk** [comment]
I see now.
Thank you for clarification.
