### ISSUE TITLE
Crash bug affecting Mac OS X 10.8.5 user

### ISSUE THREAD

**Issue by TerryCavanagh** [openfl/openfl#1419]
Heya,

I recently released a small game built in OpenFL/Starling, and it mostly appears very stable on Mac! However, one user reported that when they ran the application from the terminal, they got the following error:

```
Could not load module lime@lime_application_create__prime
logout
```

I'm not a mac user and I haven't a clue what might be causing this on their machine. Any thoughts?

(if needs be I can probably ask them to try some test programs, but beyond that this might be hard to reproduce)

**Comment by jgranick** [comment]
Does it work if they double-click it in Finder?

I have a feeling this may have to do with the current working directory of the application, (for some reason) we have had difficulty with detecting the location of the executable when we run, so most paths are relative, and rely on the current working directory being a certain value

**Comment by jgranick** [comment]
What version of OS X, and what kind of processor?

**Comment by TerryCavanagh** [comment]
He said it's Mac OS X 10.8.5, I don't know what kind of processor. I'll email and find out!

**Comment by jgranick** [comment]
Is he using a case-sensitive file system? Are we sure that all the required files for the application are there? Thanks :smile:

**Comment by TerryCavanagh** [comment]
I've emailed to ask. As for the application file, I've had a few thousand downloads for this on Mac and this is the first crash report ¯\_(ツ)_/¯

(have asked him to redownload the game, just in case)

**Comment by TerryCavanagh** [comment]
Ok! I asked the player about his processor, and got a `system_profiler | grep Processor` log:

```2017-01-05 19:05:19.632 system_profiler[15838:707] httpdEnabled is deprecated !!
      Processor Name: Intel Core i7
      Processor Speed: 3.4 GHz
      Number of Processors: 1
```

He says he's not using a case sensitive file system. He typed `diskutil info /` and got the following output:

```File System Personality:  Journaled HFS+
   Type (Bundle):            hfs
   Name (User Visible):      Mac OS Extended (Journaled)
```

Also, in `~/Library/Logs/DiagnosticReports/`, he found the following log:

```
1/5/17 7:34:41.738 PM com.apple.launchd.peruser.501[141]: ([0x0-0xb2db2d].com.distractionware.7drl[15904]) Exited with code: 255
```

(the package name for the game is com.distractionware.7drl)

**Comment by jgranick** [comment]
https://github.com/pyinstaller/pyinstaller/issues/1191

😦 

I used to use 10.7 for our builds (due to previous problems targeting old OS X versions) but had to upgrade recently to support newer iOS versions. We may have to have separate Mac and iOS build servers, now ☹️

**Comment by jgranick** [comment]
I have been able to get builds working properly on OS X 10.7, here are the steps that I needed to take to get them working on our build server:

 1. Download the "XcodeLegacy" script from https://github.com/devernay/xcodelegacy
 2. Download the Xcode 3.2.6 installer in the same directory https://developer.apple.com/devcenter/download.action?path=/Developer_Tools/xcode_4.6.3/xcode4630916281a.dmg
 3. Remove (or comment) this segment of the script: https://github.com/devernay/xcodelegacy/blob/master/XcodeLegacy.sh#L24-L62 (this was breaking the script for me on macOS Sierra)
 4. Run `./XcodeLegacy.sh -osx107 buildpackages`
 5. Run `sudo ./XcodeLegacy.sh -osx107 install`
 6. Patch HXCPP https://github.com/HaxeFoundation/hxcpp/commit/72cfda08d8986bda6acd9a1bf36bfdafbabee6bc (using a current development build from GIT or http://www.openfl.org/builds/hxcpp would also work)
 7. Run `lime rebuild mac -clean -DMACOSX_VER=10.7`
 8. Add `-DMACOSX_VER=10.7` when doing a C++ build of a project

I tried the 10.6 SDK, but it broke support for compiling SDL. I have feeling that the output may still run on OS X 10.6, but I have no way to confirm. Either way, this change brings us back to working properly on old Mac systems as originally intended.

The OpenFL Mac build server has been updated, and I will be releasing new builds with the corrected backward compatibility :smile: 


I had trouble with the top part of the script,

**Comment by Gaikov** [comment]
I have the same problem on my command line application:
https://github.com/Gaikov/GameTools/tree/master/SpritePackerConsole

**Comment by jgranick** [comment]
I guess this doesn't seem to be enough:

https://github.com/openfl/lime/blob/develop/include.xml#L68

I wonder if we should use `<setenv .../>` or force `MACOS_VER`, but then that requires legacy Xcode SDKs, which aren't simple to install ☹️

**Comment by TerryCavanagh** [comment]
So! Weirdly, I just got the same error message from another person! However:
 * It's on windows, not Mac
 * And it's a different game

Honestly, I have no idea!

![constellation - not working](https://user-images.githubusercontent.com/2874150/42545352-4caad42a-84af-11e8-9c4a-d56077b32575.png)

**Comment by jgranick** [comment]
Perhaps loading the DLL failed, like (maybe) the Lime NDLL file is incompatible with the version of Windows they are running? One is 32-bit, the other is 64-bit?

Wait... is he trying to execute it directly from a ZIP file? Perhaps he needs to extract it to a directory before he can run it?

**Comment by TerryCavanagh** [comment]
Hah! So they are! Have asked them that, will let you know if they reply.
