### ISSUE TITLE
Very gradual scale changes may never recalculate transform matrices in html5

### ISSUE THREAD

**Issue by dgrenzo** [openfl/openfl#1427]
in display.Graphics, the __update function will only recalculate an object's transform if its width or height changed by more than a certain amount since last frame

This is good for performance, but very gradual scale changes might never actually be applied. It would be great to have the option for this threshold to change based on the current / target FPS.

In this example, the fraction animation is from a .swf asset
![example](https://cloud.githubusercontent.com/assets/18463428/21809079/2cbb3294-d714-11e6-95ce-4b90705b9a78.gif)

**Comment by jgranick** [comment]
I think the math may be somewhat incorrect:

https://github.com/openfl/openfl/blob/develop/openfl/display/Graphics.hx#L867-L881

Causing `__dirty` to be true each frame resolves it, but I think that not constantly redrawing, but properly scaling should have the correct effect?

**Comment by dgrenzo** [comment]
I took a stab at it... 

		__renderTransform.a = scaleX;
		__renderTransform.d = scaleY;
		__worldTransform.a = scaleX;
		__worldTransform.b = 0;
		__worldTransform.c = 0;
		__worldTransform.d = scaleY;
		__worldTransform.tx = __bounds.x + (__bounds.width / 2 * (1.0-scaleX));
		__worldTransform.ty = __bounds.y + (__bounds.height / 2 * (1.0-scaleY));
		__worldTransform.concat (__owner.__renderTransform);`

**Comment by jgranick** [comment]
I believe this was resolved in recent versions, but if it still exists, example code would be super appreciated :smile:
