### ISSUE TITLE
Preloader gives percent loaded more than 1

### ISSUE THREAD

**Issue by xoopx** [openfl/openfl#1431]
With Pirate Pig html5 if i put trace in openfl.display.Preloader.hx:249 trace (bytesLoaded / bytesTotal); (onUpdate function), i get values more than 1. Here are trace
Preloader.hx:249: NaN
PiratePig.js:3901 Preloader.hx:249: 0
PiratePig.js:3901 Preloader.hx:249: 0.004235853122883357
PiratePig.js:3901 Preloader.hx:249: 0.04886727489173046
PiratePig.js:3901 Preloader.hx:249: 0.09748055253381499
PiratePig.js:3901 Preloader.hx:249: 0.15007825167792122
PiratePig.js:3901 Preloader.hx:249: 0.20299639785718684
PiratePig.js:3901 Preloader.hx:249: 0.25618701381334535
PiratePig.js:3901 Preloader.hx:249: 0.30971372714024753
PiratePig.js:3901 Preloader.hx:249: 0.3636250282219166
PiratePig.js:3901 Preloader.hx:249: 0.4177849387327846
PiratePig.js:3901 Preloader.hx:249: 0.47239049896348595
PiratePig.js:3901 Preloader.hx:249: 0.5319218098971696
PiratePig.js:3901 Preloader.hx:249: 0.5919957513187332
PiratePig.js:3901 Preloader.hx:249: 0.6554003920280782
PiratePig.js:3901 Preloader.hx:249: 0.7395076045237167
PiratePig.js:3901 Preloader.hx:249: 0.8352024794236571
PiratePig.js:3901 Preloader.hx:249: 1.8352024794236572
PiratePig.js:3901 Preloader.hx:249: 1.8352024794236572

In my projects i got values > 7.So in my projects 14 updates in preloader is useless.

openfl 4.5.3, lime 3.6.0

**Comment by jgranick** [comment]
Fixed, thank you :smile:

https://github.com/openfl/lime/commit/7623830d3b6aa3c86552873ca384efabbb42b0d8
