### ISSUE TITLE
Sound channel resolution is too granular

### ISSUE THREAD

**Issue by raould** [openfl/openfl#1437]
Audio sound channel time position doesn't update as fast as game loops do, I guess. I am using Haxe Flixel and am seeing similar behaviour as was reported at the start of this thread:

http://community.openfl.org/t/soundchannel-position-accuracy/438/8

Since I am on Flixel, I am stuck on older versions of everything of course. Are Flixel users out of luck until the Flixel people actually get on to newer libraries? Like, is it known for sure that OpenFL 4.5.2 has higher resolution / accuracy / precision / updating of the audio channel time position?

Haxe 3.2.1
Ubuntu 14.04 intel/amd 64 bit
$ haxelib list
actuate: [1.8.7]
box2d: [1.2.3]
flixel-addons: [2.2.0]
flixel-demos: [2.3.0]
flixel-templates: [2.1.0]
flixel-tools: [1.2.1]
flixel-ui: [2.2.0]
flixel: [4.2.0]
HaxePunk: [2.6.0]
hxcpp: [3.4.43]
hxmidilib: [1.0.1]
layout: [1.2.1]
lime: 3.5.2 [2.9.1]
openfl: [3.6.1] 4.5.2

**Comment by jgranick** [comment]
I wonder if there is a delay before it is able to calculate the current time (it has been playing) or if we should use something more accurate than AL.SEC_OFFSET (such as using a bytes offset)

https://github.com/openfl/lime/blob/develop/lime/_backend/native/NativeAudioSource.hx#L388

We haven't made a lot of releases since 3.6, I can't say what the Flixel team's plans are

**Comment by raould** [comment]
Thanks for your note. Is it *known* for a fact that in e.g. lime 3.6.2 + OpenFL 4.6.0 that the position value had more resolution? If yes, then I can stop using Flixel and be happier at least regarding audio. However if not, then it feels like a bug to me or perhaps something that should be adjustable via some configuration parameter maybe in the project.xml or some such.

**Comment by MSGhero** [comment]
Everyone from flixel is currently reviewing the PR for compatibility with latest openflime ✅

**Comment by raould** [comment]
Also I don't understand your link, I am not concerned about *setting* the position, I am only (at the moment) concerned about *reading* the position with high precision (and of course accuracy).

https://github.com/openfl/lime/blob/develop/lime/_backend/native/NativeAudioSource.hx#L349

**Comment by raould** [comment]
Random possibly useless thing I saw while searching about this, in case it has any relevance (I don't grok it I am just going off of pattern matching and keywords): "You'll probably want to use AL11.AL_SEC_OFFSET, but beware that it rounds the seconds as best it can to the bytes, so bytes and samples will be more accurate." http://forum.lwjgl.org/index.php?PHPSESSID=9idg0ckvvhse9a4ufg8hk8n681&topic=3590.msg20087#msg20087

**Comment by jgranick** [comment]
Yeah, so we should try and calculate a byte position based upon the file length, rather than using seconds. We need millisecond precision ;)

**Comment by jgranick** [comment]
I just created an issue https://github.com/openfl/lime/issues/898

**Comment by raould** [comment]
thanks!
