### ISSUE TITLE
Flash target is broken

### ISSUE THREAD

**Issue by kasparsj** [openfl/openfl#1439]
Stops at preloader screen.
```
openfl create NyanCat
cd NyanCat
openfl test flash
```
<img width="400" alt="screen shot 2017-01-23 at 12 11 27 pm" src="https://cloud.githubusercontent.com/assets/743481/22199802/2180b83a-e165-11e6-81b3-484c0c435936.png">
using openfl 4.6.0, lime 3.6.2, haxe 3.4.0

**Comment by jgranick** [comment]
This is now fixed in development, we don't have embedded SWF assets enabled at the moment, but I'm tracking that separately here:

https://github.com/openfl/openfl/issues/1428

Thanks :smile:
