### ISSUE TITLE
Larger HTML5 file size in 4.7

### ISSUE THREAD

**Issue by keesungz** [openfl/openfl#1450]
openfl 4.6.1 is very greate!  This version  has many significant improve for Html5，inculde high-DPI, text display clearly, practical attribute (stage.fullweight)  ect. , thanks so much to openfl team!

but I has a serious problem on  4.6.1 version (include 4.6.0 ) :  the size of  .js file compiled by DCE  increase extremely many. The size of  .js file on old version is 2261 kb, the size is 4396 kb on  on  4.6.1 version (include 4.6.0 ). Looking forward a useful advice, thanks for it.

**Comment by Gama11** [comment]
According to [haxelib](http://lib.haxe.org/p/openfl/versions/), there's no version 4.6.1, only 4.7.0. I guess you mean that?

**Comment by keesungz** [comment]
I am wrong，it's Version  4.7,so sorry for it.

**Comment by jgranick** [comment]
I've made some changes that reduced the size a bit. Have you been doing only `<haxeflag name="-dce" value="std" />` or `<haxeflag name="-dce" value="full" />`, or have you tried the `-final` target flag?

```bash
openfl test html5 -final
```

What version were you using before, so I can compare?

Thanks!

**Comment by keesungz** [comment]
Thank you for your reply ! My DCE config is  <haxeflag name="-dce" value="full" />.  The size of  H5 file  is right besides vesion 4.6.0 and version 4.7.0.  I will try  -final  target flag,thank you again!

**Comment by keesungz** [comment]
Thank you for your reply !
 My DCE config is  <haxeflag name="-dce" value="full" />  , the size of H5 file is right prior to openfl 4.6.0 and lime 3.6. I will try -final target flag,thank you again !

**Comment by keesungz** [comment]
I  can compile my project by  '-final' flag after updated java to 1.8. But the size of output file is 3544 KB, it is too bigger than I use DCE on old OpenFL vesion, the size of file is a significant KPI to my project, pls give me some advice.

Thank you !
