### ISSUE TITLE
Getting another MovieClip instance with Assets.getMovieClip() breaks previous instance (regression)

### ISSUE THREAD

**Issue by Tearff** [openfl/openfl#1451]
I use swf assets in my project (`type="swflite" preload="true"`), loading the entire timeline of every library:
```clip = Assets.getMovieClip('libraryName:');```

At some point in the last 1 or 2 public releases, the behavior of this changed: instead of being able to create multiple instances of the same clip (as expected), the previous instance now disappears from the screen and its children all become `null`.

**Comment by jgranick** [comment]
This is working for me:

```bash
openfl create NyanCat DuplicateTest
cd DuplicateTest
```

and editing "Main.hx"

```haxe
package;


import openfl.display.Sprite;
import openfl.Assets;


class Main extends Sprite {
	
	
	public function new () {
		
		super ();
		
		var cat = Assets.getMovieClip ("library:");
		cat.x = -100;
		addChild (cat);
		
		var cat2 = Assets.getMovieClip ("library:");
		cat2.x = 100;
		addChild (cat2);
		
	}
	
	
}
```

and running

```bash
openfl test neko
```

Do you know how I might replicate the problem? :smile:

Thank you!
