### ISSUE TITLE
Text autoSize problems

### ISSUE THREAD

**Issue by rmoretto** [openfl/openfl#1455]
Hello!

After the 4.7.0 update I noticed a strange behavior with the autoSize of TextFields.

Running the command `lime test cpp`, using the following code:
```haxe
import openfl.text.TextFieldAutoSize;
import openfl.text.TextField;
import openfl.display.Sprite;

class Main extends Sprite {
	public function new() {
		super();

		var textFieldWOSpace = new TextField();

		textFieldWOSpace.autoSize = TextFieldAutoSize.LEFT;

		textFieldWOSpace.text = "Test123";

		textFieldWOSpace.x = 10;
		textFieldWOSpace.y = 10;

		var textFieldWSpace = new TextField();

		textFieldWSpace.x = 10;
		textFieldWSpace.y = 50;

		textFieldWSpace.autoSize = TextFieldAutoSize.LEFT;

		textFieldWSpace.text = "Test 123";

		addChild(textFieldWOSpace);
		addChild(textFieldWSpace);
	}
}
```

I get this result:
![selection_002](https://cloud.githubusercontent.com/assets/12282955/22338955/be68e5c0-e3cf-11e6-950f-900c509aee06.png)

So, as can be seeing, if the text have a white space the autoSize feature crop the end of the text.

I'm using OpenFl 4.7.2 and Lime 3.7.0 with a Lubuntu 64-bit machine.

**Comment by jgranick** [comment]
Fixed by https://github.com/openfl/openfl/commit/18c2196aab89776eb2de1ac92cda70327e39c0c1

:shipit:
