### ISSUE TITLE
flash.net.FileReference missing

### ISSUE THREAD

**Issue by delahee** [openfl/openfl#146]
Hi, 

flash.net.FileReference is missing from the whole apis, it is not a big miss but you might want to task it.

++

**Comment by jgranick** [comment]
I would be happy to discuss this more on the forums or the OpenFL Slack, there are no plans (on my end) to implement this right now, but it could make a great pull request. I'd love to see dialog box / file browse support implemented in Lime 2. Until then, I'm closing this as it's not a bug, but a wishlist item :smile:
