### ISSUE TITLE
AGALMiniAssembler doesn't support .xyzw in Flash.

### ISSUE THREAD

**Issue by player-03** [openfl/openfl#1460]
Steps to reproduce:

1. Create the HelloTriangle sample.
2. Open Main.hx and change [line 64](https://github.com/openfl/openfl-samples/blob/master/features/display3D/HelloTriangle/Source/Main.hx#L64) to `"mov v0.xyzw, va1.xyzw"`.
3. Test in Flash, and you'll get "Error #3632: AGAL linkage: Varying 0 is read in the fragment shader but not written to by the vertex shader."

However, if you change line 64 to `"mov v0.rgba, va1.rgba"`, it will work normally again. Note that these are supposed to be synonyms: `x` and `r` both access index 0, `y` and `g` both access index 1, etc.

I'm using OpenFL 4.7.3, Lime 3.7.2, openfl-samples 4.7.0, and Haxe 3.4.0.

**Comment by player-03** [comment]
Update: this doesn't work well on Neko or Windows either. For instance:

```haxe
var vertexShader = assembler.assemble (Context3DProgramType.VERTEX,
	"m44 op, va0, vc0\n" +
	"mov v0.xyzw, va1.xzzw"
);
```

This produces a triangle with the correct colors (red-black-cyan), but it flickers wildly. I'm pretty sure it's ignoring the `w` property and just using whatever value was already there in memory. I think this because the following code solves it:

```haxe
var vertexShader = assembler.assemble (Context3DProgramType.VERTEX,
	"m44 op, va0, vc0\n" +
	"mov vt0, va1\n" +
	"mov vt0.xyz, va1.xzz\n" +
	"mov v0, vt0"
);
```

The second line (`mov vt0, va1`) copies everything, including the `w` property. Then the third line chooses the desired colors. The result is the desired red-black-cyan triangle, without any flickering.

**Comment by jgranick** [comment]
Could you try this patched version, and see if it makes a difference?

https://github.com/openfl/openfl/commit/7bbc61e10987d8ec980bfcc338b165b640ea6d53

This fixed some shaders in Away3D (I forget if they used swizzling)

Thanks :smile:

**Comment by player-03** [comment]
That fixed it on all three targets!

It doesn't affect #1461, but now I can work around it simply by substituting the letters.
