### ISSUE TITLE
AGALMiniAssembler doesn't support .rgba swizzling on any target.

### ISSUE THREAD

**Issue by player-03** [openfl/openfl#1461]
Any sequence starting with `r`, `g`, `b`, or `a` gets removed (as well as the dot in front). This means "`v0.r`" becomes just "`v0`," so even though I tried to access only the first component, all four end up being copied.

To test this, I replaced [line 64](https://github.com/openfl/openfl-samples/blob/master/features/display3D/HelloTriangle/Source/Main.hx#L64) with the following.

- `"mov v0.r, va1.r"`, which ought to throw an error.
- `"mov v0.rgb, va1.rrr"`, which ought to produce a grey-black-black triangle.
- `"mov v0.rgb, va1.rgg"`, which ought to produce a red-cyan-black triangle.
- `"mov v0.rzzz, va1.rzzz"`, which ought to produce erratic behavior as reported in issue #1460.

Instead of doing any of these things, every single example here produces the normal red-green-blue spinning triangle. I tested this on Flash, Neko, and Windows, and I assume it works the same everywhere else.

**Comment by jgranick** [comment]
I think this is the newest AGALMiniAssembler from the Adobe Gaming SDK:

https://github.com/Gamua/Starling-Framework/blob/master/starling/src/com/adobe/utils/AGALMiniAssembler.as

(which I think is the same as https://github.com/adobe-flash/graphicscorelib/blob/master/src/com/adobe/utils/v3/AGALMiniAssembler.as)

Do you think this supports rgba color accessors, or do you think we had an error in porting?

I see "xyzw" in the regexes, but nothing for "rgba" or similar 😕

**Comment by player-03** [comment]
Huh... looks like Adobe's documentation is [wrong](http://forum.starling-framework.org/topic/invert-color-in-agal#post-19874). Never mind, then!

**Comment by jgranick** [comment]
Do you think that they removed `rgba` from the AGAL specification, or do you think they just broke support in their assembler? We could patch it if the latter is the case

**Comment by player-03** [comment]
I suspect it was never in the specification in the first place, and whoever wrote the documentation got AGAL confused with GLSL.

That said, I wouldn't complain if you patched it in.

**Comment by jgranick** [comment]
Hmm, I'm on the fence about it.

From the looks of it, I think we'd need to add "rgba" as acceptable letters in the regexes here:

https://github.com/openfl/openfl/blob/develop/openfl/utils/AGALMiniAssembler.hx#L230-L236

Then I believe we would need to update the "maskmatch" routine here to map "rgba" to the correct indices:

https://github.com/openfl/openfl/blob/develop/openfl/utils/AGALMiniAssembler.hx#L480

Or do a string replace in advance to translate to "xyzw" format

**Comment by player-03** [comment]
The string replace sounds easier to do and a lot easier to debug.
