### ISSUE TITLE
iOS looping sound crashes

### ISSUE THREAD

**Issue by danielmar** [openfl/openfl#1463]
Using the PiratePig sample, if I change line 442 to IntroSound.play (0, 10), the game crashes as soon as the first or second iteration of the music completes. The error presented in xcode is:

libc++abi.dylib: terminating with unexpected exception of type int

Using Openfl 4.7.3, Lime 3.7.2 Hxcpp 3.4.43
Tested both .wav and .ogg files

**Comment by jgranick** [comment]
Tested here, seems stable. I believe we fixed this, but did not close the issue
