### ISSUE TITLE
Suggestion: ability to launch openfl apps from anywhere

### ISSUE THREAD

**Issue by IBwWG** [openfl/openfl#1464]
On openfl 4.7.3, lime 3.7.2, haxe 3.4.0rc2, and hxcpp 3.4.43 on Linux Mint 18.1 MATE x64, you can't launch an openfl app from somewhere other than its own directory:

```
/DisplayingABitmap $ Export/linux64/cpp/release/bin/DisplayingABitmap 
[DefaultAssetLibrary] WARNING: Could not load asset manifest (bytes was null)
[lime.utils.Assets] There is no IMAGE asset with an ID of "assets/openfl.png"
```

If OpenFL/Lime expect the local assets directory to be there, shouldn't they look for it relative to the binary's path?

(Note: I suppose this belongs in Lime's domain, but I can't verify because lime-samples is currently broken.)

**Comment by jgranick** [comment]
`Sys.executablePath` was unreliable, and caused things to break. Otherwise, we would definitely have this feature :smile:

However, the new Haxe 3.4 builds have `Sys.programPath`, which I hear is supposed to be better. If you want to test, add something such as `Sys.setCwd (Sys.programPath ())` to "lime/templates/haxe/ApplicationMain.hx" before it begins preloading.

Please let me know if you try this and it works! 😄

**Comment by IBwWG** [comment]
That didn't seem to do anything.

OTOH, neither did a `trace(Sys.programPath());` line, either.  Nor even a `trace("hello");`.  Do traces not work from within the hx template?

**Comment by IBwWG** [comment]
I seem to need help here.  Nothing I do to this file seems to have any effect, including deleting all its contents.

```
$ haxelib list
flixel-addons: [2.2.0]
flixel: [git]
hxcpp: [3.4.43]
lime-samples: 3.4.0 [git]
lime: 2.9.1 [3.7.2]
openfl-samples: [4.7.0]
openfl: 3.6.1 [4.7.3]
$ cat /usr/lib/haxe/lib/lime/3,7,2/templates/haxe/ApplicationMain.hx
$ rm -rf Export/
$ openfl test -debug linux
...
[no errors, working DisplayABitmap app window comes up]
```

OK, what obvious thing am I forgetting here?

**Comment by IBwWG** [comment]
Well as discovered in https://github.com/openfl/lime/issues/908#issuecomment-276501215 it seems neko outputs those trace() calls, but here with cpp somehow that whole ApplicationMain.hx seems to not matter (i.e. clearing the file makes no difference, or putting back the original file plus the trace calls also makes no difference.)

Anyway: on neko with lime 3.7.2, Sys.programPath() trace()'d blank.  That's all I could confirm so far.

**Comment by IBwWG** [comment]
Interesting: if I compile lime's HelloWorld (`lime test -debug linux`) and leave the traces in there, they actually output something.  On OpenFL's DisplayABitmap they don't.  I guess OpenFL overrides the ApplicationMain template with its own, then.

And, of greater interest: they actually output the correct path.

So let me try to find OpenFL's ApplicationMain template and modify *that* instead, and maybe I'll have a working app with this feature (at least on Linux).

**Comment by IBwWG** [comment]
Ah, it can work, but programPath gives you the binary, not just its home.  Regex will fix that...

Huzzah, it works!

The patch:

```
$ grep -C5 'EReg' /usr/lib/haxe/lib/openfl/4,7,3/templates/haxe/ApplicationMain.hx 
	}
	
	
	public static function create ():Void {
var p = Sys.programPath();
var r = new EReg("/[^/]+$", "");
p = r.replace(p,"");
Sys.setCwd(p);		
		var app = new openfl.display.Application ();
```

Now it launches correctly calling `$ Export/linux64/cpp/debug/bin/DisplayingABitmap`.

I guess to make it work on Windows too we'll need a conditional, unless Haxe provides the path separator in a variable somewhere.

**Comment by jgranick** [comment]
Perhaps you could try:

```haxe
var path = Sys.programPath ();
Sys.setCwd (Path.directory (path));
```

**Comment by IBwWG** [comment]
That's way more elegant than what I was about to do.  :)

**Comment by IBwWG** [comment]
AFAICT you'd only want this for cpp targets, right?  Neko complains, and I can imagine flash would, and it's not really needed on mobile, I don't think....

**Comment by jgranick** [comment]
What happens on Neko?

I imagine we would want to have `#if desktop`, as mobile won't need this feature, I assume

**Comment by IBwWG** [comment]
```
$ lime test neko
Called from ? line 1
Called from ApplicationMain.hx line 81
Called from ApplicationMain.hx line 89
Called from /usr/lib/haxe/std/neko/_std/Sys.hx line 87
Uncaught exception - std@set_cwd
```

And flash is sandboxed so probably can't set_cwd either / you don't need to for assets anyway.
