### ISSUE TITLE
loosing all URLRequest parameters

### ISSUE THREAD

**Issue by Celsyum** [openfl/openfl#1468]
While using openfl.display.Loader class I loose all URLRequest parameters (using both GET and POST methods)

here is simple example:
```
var loader:Loader = new Loader();
var url:URLRequest = new URLRequest("test.com?demo=12312");
loader.load(url);
```

also tried using URLVariables:
```
var loader:Loader = new Loader();
var url:URLRequest = new URLRequest("test.com");
url.method = "POST";
var pars:URLVariables = new URLVariables();
pars.demo = "123124";
url.data = pars;
loader.load(url);
```

in these cases no "demo" parameter is sent to requested URL.

**Comment by jgranick** [comment]
I just made changes to `Loader`, it should use `URLLoader` for loading, using the original `URLRequest` so that it can be parsed/used properly.

Please let me know if you have any more trouble :smile:
