### ISSUE TITLE
Clarify haxe version support

### ISSUE THREAD

**Issue by IBwWG** [openfl/openfl#1470]
I've seen threads like #1398 and seem to recall other openfl threads where things were fixed in openfl if you used haxe versions newer than 3.2.1 that imply that 3.2.1 is not the only supported version.  But I don't see any mention of haxe versions in the readme.  Just a link to the openfl installation page, which currently uses 3.2.1.

I'm not opening this in the same vein as https://github.com/openfl/openfl.org/issues/76 , more to say that it could be a bit clearer what the official support policy is.  (I had opened that issue, and had used 3.4.0rc2 and then official 3.4.0 recently on an openfl issue I opened, because of an assumption I had picked up that openfl users "should" be on 3.4.0 if possible instead of 3.2.1.  But now reading the readme I'm not so sure: will 3.2.1 continue to be supported now that 3.4.0 is out?  Or only for openfl's 3.x branch?  Or both for both?)

**Comment by jgranick** [comment]
We recommend Haxe 3.2.1, currently, but will move to 3.4 as the standard version once we're sure it's stable. Had trouble with RC releases

**Comment by IBwWG** [comment]
Should there be a note on http://www.openfl.org/learn/docs/getting-started/ in the interim?

**Comment by jgranick** [comment]
Getting feedback here:

http://community.openfl.org/t/poll-haxe-3-4-0-testing/8778/6
