### ISSUE TITLE
Implement anchorX and anchorY for Bitmap/Sprite/MovieClip/Text

### ISSUE THREAD

**Issue by alexandervrs** [openfl/openfl#1473]
In pixi.js there is an anchorX and anchorY property so to move the graphic's transformation origin, in the Flash IDE, you could move around a MovieClip's origin point and all further transformations were done relative to that.

Could OpenFL provide anchorX and anchorY properties built-in for Bitmaps, Sprites, MovieClips and Text, instead of having to mess with complex Matrix calculations to achieve this? Default values would be [0, 0] (top-left)
The values could be from 0 to 1, so [0.5, 0.5] would be the Sprite center, or pixel-based (I think pixi.js has another property for that)

**Comment by jgranick** [comment]
The Flash method of doing this is not to use complex matrix calculations (although you can), but to put your objects inside of another Sprite, like so:

```
var container = new Sprite ();
bitmap.x = bitmap.width / 2;
bitmap.y = bitmap.width / 2;
container.addChild (bitmap);
```

Then you can move, rotate, etc, with a new offset point

**Comment by jgranick** [comment]
More specifically, not that this is a bad idea, but the plan is to keep the API for OpenFL similar to Flash. However, I would be open to this in the new Tilemap API, I think we should have an offset value in the future there
