### ISSUE TITLE
Textfields don't report correct width value if the text is all spaces on HTML5

### ISSUE THREAD

**Issue by TaylorAnderson** [openfl/openfl#1475]
Fairly self-explanatory heading, but if I create a textfield on HTML5, set its text to be "    ", and trace out it's textWidth, it will give me 0.  By contrast, on Flash, it will give me 12.  I feel like I have seen a variation of this issue before so if you've already got this recorded somewhere please let me know.

**Comment by MintPaw** [comment]
I'm having a similar issue, ending a field with spaces causes them not to be counted either. Or sometimes putting to many spaces in a field will cause the rest of it to be cut off.

For example `"This is a                test"` won't work, it will be cut off to look something like `""This is a      "`, but `"This is a a a a a a a a a a a a a a a a test"` Will work.

**Comment by MintPaw** [comment]
So it looks like what we need to do is insert some kind of &nbsp; character, or wrap it in <pre> tags. (which doesn't work with htmlText)

Any suggestions of a temporary work around? Some sort of invisible character or something?
