### ISSUE TITLE
Bitmaps hitTest ignores scrollRect

### ISSUE THREAD

**Issue by mayakwd** [openfl/openfl#1476]
Version: 4.7.3
Tested targets: HTML5, Desktop

Bitmaps hitTest ignores scrollRect

**Comment by Gama11** [comment]
Do you have some example code for that?

**Comment by MintPaw** [comment]
It seems to ignore position as well.

**Comment by mayakwd** [comment]
@Gama11, sure:

```
package ;

import openfl.events.MouseEvent;
import openfl.geom.Rectangle;
import openfl.display.Bitmap;
import openfl.display.BitmapData;
import openfl.display.Sprite;

class BitmapBugTest extends Sprite {
    public function new() {
        super();

        var bitmapData:BitmapData = new BitmapData(500, 500, false, 0x123ABC);
        var bitmap = new Bitmap(bitmapData);
        bitmap.scrollRect = new Rectangle(0, 0, 100, 100);

        var sprite = new Sprite();
        sprite.addChild(bitmap);

        addChild(sprite);

        sprite.addEventListener(MouseEvent.CLICK, onMouseClick);
    }

    private function onMouseClick(event:MouseEvent):Void {
        trace(event);
    }
}
```

Console log:

`[MouseEvent type="click" bubbles=true cancelable=false localX=152 localY=171 relatedObject=null ctrlKey=false altKey=false shiftKey=false buttonDown=false delta=0]`

**Comment by MintPaw** [comment]
After pulling the develop branch I'm still having issues. I'm calling `bmp.bitmapData.hitTest(new Point(0, 0), 0, bmp.globalToLocal(myPoint)` Does the patch also address this case?

**Comment by jgranick** [comment]
@MintPaw Could you share a bigger code sample, to illustrate what you are seeing?

I assume that `bitmapData.hitTest` ignores the `bitmap` container and `scrollRect`, but if you share more code, perhaps we can recreate the discrepancy you are seeing.

Thanks

**Comment by MintPaw** [comment]
@jgranick Oh, actually this may be unrelated, here's a test case:
This program draw a red box and displayed "Clicked." or "Missed." depending on whether or not you click a solid pixel.

[In flash it works fine.](http://i.imgur.com/KHAgkHI.png)
[In html5 it's always true.](http://i.imgur.com/Lz1IksF.png)
)
```
package;

import openfl.display.*;
import openfl.events.*;
import openfl.geom.*;
import openfl.text.*;

class Main extends Sprite
{

	public function new() {
		super();
		var tf:TextField = new TextField();
		tf.mouseEnabled = false;
		addChild(tf);

		var bmp:Bitmap = new Bitmap(new BitmapData(stage.stageWidth, stage.stageHeight, true, 0));
		bmp.bitmapData.fillRect(new Rectangle(100, 100, 50, 50), 0xFFFF0000);
		addChild(bmp);

		stage.addEventListener(MouseEvent.CLICK, function(e:MouseEvent):Void {
			var myPoint:Point = new Point(stage.mouseX, stage.mouseY);
			var hit:Bool = bmp.bitmapData.hitTest(new Point(0, 0), 0, bmp.globalToLocal(myPoint));

			if (hit) tf.text += "Clicked.\n" else tf.text += "Missed.\n";
		});
	}
}
```

**Comment by MintPaw** [comment]
Nvm, this is just a minor discrepancy, for the alpha value of hitTest it's common in AS3 to put 0 to count all but fully transparent pixels. In html5 it seems you have to set it to at least 1 to get correct results.

**Comment by jgranick** [comment]
@MintPaw Do you know if the behavior should be `>` and not `>=` here?

https://github.com/openfl/openfl/blob/develop/openfl/display/BitmapData.hx#L1085

Or is there a special case in Flash if you use a threshold of zero?

**Comment by jgranick** [comment]
https://github.com/openfl/openfl/commit/fa1bce00add3fdd1e61d2fd792a0386821b46941

:shipit:
