### ISSUE TITLE
Generated swf does not work in browser, but only in Flash Player 

### ISSUE THREAD

**Issue by hopewise** [openfl/openfl#1480]
Hello,

I am using this simple html to view openfl generated swf file:

```html
<script type="text/javascript">
    swfobject.embedSWF("openfl.swf", "myContent", "1200", "800", "9.0.0");
</script>

</head>
<body>
<div id="myContent">
<p>Alternative content</p>
</div>
</body>
</html>
```

However, the swf file generated by openfl 4.7 will not be shown in html, but only gray color.
On the other hand, If double click the openfl.swf file, it will be opened and viewed normally in the flash player.

I am using:
lime: [3.7.2]
openfl: [4.7.3]

I tried to view the openfl.swf in html page served by a local server, the same great area, nothing else.

Is this a bug?

**Comment by RblSb** [comment]
@hopewise browser/console log? If it a Chome, try refresh page button, its works for me. Dont know, how to fix it.

**Comment by hopewise** [comment]
There is no console errors.
As it works for you, can you please list your libraries versions? openfl, lime, and haxe?

**Comment by hopewise** [comment]
Here is a snapshot in chrome, that shows the loading of libraries needed for the app when targeting flash: All are loaded normally, but the app will not start.
![screen shot 2017-02-07 at 9 25 31 pm](https://cloud.githubusercontent.com/assets/1061157/22707678/3b47bc5a-ed7c-11e6-876a-38059012b236.png)

It will only start using flash player without the browser.
May be if I embed all libraries into the generated swf? how would I do so?
Here is how I include the swf libraries:

```
<library path="assets-swf/led.swf" preload="true" generate="true" embed="true"  unless="html5"/>
<library path="assets-swf/library.swf" preload="true" generate="true" embed="true" unless="html5"/>
```

I hope I can fix this issue 😢

**Comment by hopewise** [comment]
Is there a proven haxe version to generate a working swf file that works in browser too?

**Comment by MintPaw** [comment]
Test if the swf works if you move it into a new directory, I'm having a similar issue where the swf only works with the lib directory next to it, embed in the project.xml seems to do nothing.

**Comment by visualife** [comment]
just bumping this guys.
Exactly the same issue, pure AS3 swf, embedded SWC (merged to code) - workins completely find as AIR, APK, SWF inside Animate/Flash.

BUT no code will run when put inside a browser.

No errors are thrown, everything is self contained in the swf, exactly the same result on Firefox and Chrome and on MacBook pro and Windows desktop machines.

**Comment by jgranick** [comment]
So no external asset files? Could it be something to do with the wmode, or with the browser? I have noticed some browsers that will trip the swfobject script, and simply not try to render the SWF, as the browser wants to disable Flash. You may have to go into your config and force Flash to be enabled?
