### ISSUE TITLE
Word wrap doesn't quite work correctly on HTML5

### ISSUE THREAD

**Issue by TaylorAnderson** [openfl/openfl#1482]
Hello,

I've noticed a peculiar behavior in HTML5 textfields (on canvas at least) --unlike flash textfields, a wordwrap-enabled textfield will not wrap unless a space exists in the text. 

![wordwrapping](https://cloud.githubusercontent.com/assets/5308535/22705224/b9bc64ee-ed38-11e6-9e48-530113ca1f53.gif)

The code:

```haxe
public function new() 
{
	super();
	var tf:TextField = new TextField();
	tf.type = TextFieldType.INPUT;
	tf.border = true; tf.borderColor = 0;
	tf.wordWrap = true;
	addChild(tf);
}
```

**Comment by MSGhero** [comment]
#1186 but I stopped because it didn't seem like textfield PRs were being merged
