### ISSUE TITLE
Textfield Selection Crash

### ISSUE THREAD

**Issue by aW4KeNiNG** [openfl/openfl#1498]
When you select all text and press backspace or some letter to replace the text, the application hangs up in an infinite loop in the `replaceText` method of `TextField`.

It occurs with OpenFL 4.8.0 and Lime 3.7.3.

**Comment by aW4KeNiNG** [comment]
It works with OpenFL 4.6.0 and Lime 3.6.2.

From OpenFL 4.7.0 and Lime 3.7.0 stops to work.

**Comment by aW4KeNiNG** [comment]
This is weird. It seems to be a HaxeUI/OpenFL bug. Here is the example.

The Main class set the text to "TEST". If you select all text and replace with other text, the application hangs up in the `replaceText` method. If you write your own text, it works. 

This behaviour occurs from OpenFL 4.7.0.

[bug_textfield_selection.zip](https://github.com/openfl/openfl/files/780235/bug_textfield_selection.zip)

**Comment by aW4KeNiNG** [comment]
Bug 100% replicated without HaxeUI. Here the code:

[bug_textfield_selection_openfl.zip](https://github.com/openfl/openfl/files/780765/bug_textfield_selection_openfl.zip)

```
class Main extends Sprite{

    private var textField:TextField;

    public function new()
    {
        super();

        textField = new TextField();
        textField.type = TextFieldType.INPUT;
        textField.width = 200;
        textField.height = 50;

        textField.text = "TEST";

        changeColor(0x000000);

        addChild(textField);

    }

    private function changeColor(value:Int):Void
    {
        var format:TextFormat = textField.getTextFormat();
        format.color = value;
        textField.setTextFormat(format);
    }

}
```

The next commits have introduced the problem:

1. https://github.com/openfl/openfl/commit/36ba8a66ecb3d03fbc9a240b30a67a480925f719 --> https://github.com/openfl/openfl/blob/develop/openfl/text/TextField.hx#L576-L580

2. https://github.com/openfl/openfl/commit/2fa4913ab8715b0b2e536851619a23e64023942e --> https://github.com/openfl/openfl/blob/develop/openfl/text/TextField.hx#L588

The problem is fixed if we delete 1 and change `<` to `<=` in 2. I don't know the exact reasons for these commits, so I think that it is best if @jgranick can fix it instead I create a PR

**Comment by jgranick** [comment]
Fixed :smile:

https://github.com/openfl/openfl/commit/d93ee37d49c2ac1e3b9849c378946b278a7310fd

**Comment by aW4KeNiNG** [comment]
Thanks. It works now 👍
