### ISSUE TITLE
TouchEvent issue on iphone with html5 target

### ISSUE THREAD

**Issue by lovedna** [openfl/openfl#1502]
touchPointID changed on touchbegin

[https://github.com/openfl/openfl/issues/745](url)

**Comment by lovedna** [comment]
another issue on iphone chrome browser
the first touch moved then other touch event never fire
on android chrome browser is ok

**Comment by jgranick** [comment]
Do you still have this issue with newer OpenFL and Lime versions? I haven't heard any other reports of this being a problem, I'm not sure if it is an issue with mobile Safari, or more general.

I see this open issue, but I don't see an issue in how we handle the `data.identifier` value in Lime:

https://stackoverflow.com/questions/25008690/javascript-ipad-touch-event-identifier-is-continually-incrementing
https://github.com/openfl/lime/blob/develop/src/lime/_internal/backend/html5/HTML5Window.hx#L834
