### ISSUE TITLE
BitmapData is buggy in HTML5

### ISSUE THREAD

**Issue by hopewise** [openfl/openfl#1506]
My app creates  thumbnails from bitmapdata, in version 4.8.1, created thumbnails has bigger area than before in version 4.2, look at created thumb here in 4.2:
![screen shot 2017-02-18 at 9 38 26 am](https://cloud.githubusercontent.com/assets/1061157/23091415/0f87fc48-f5be-11e6-8f86-8e8cfe34087e.png)
And in 4.8.1:
![screen shot 2017-02-18 at 9 39 11 am](https://cloud.githubusercontent.com/assets/1061157/23091419/2d0118cc-f5be-11e6-8072-9204ae08a90c.png)
Notice the gray color in the base64 format :`AAAAAAAAAA...`:
![screen shot 2017-02-18 at 9 40 18 am](https://cloud.githubusercontent.com/assets/1061157/23091426/4d6d7e34-f5be-11e6-92e2-5e2a38e8e054.png)

What I did, is using BitmapData of version 4.2 to fix the issue

**Comment by jgranick** [comment]
Could you share an example of the code you use to create the thumbnail? Thanks :smile:

**Comment by hopewise** [comment]
Here is:
```

var cropped_bitmapData:BitmapData = new BitmapData(end_x - start_x, end_y - start_y, false, Board.selectedBoard.color);

var source_rect:Rectangle = new Rectangle(start_x, start_y, cropped_bitmapData.width, cropped_bitmapData.height);

var dest_point:Point = new Point(0, 0);

cropped_bitmapData.copyPixels(bitmapData, source_rect, dest_point);
			
// create thumbnail:

// calculate scale:
var scale:Float;
scale = 120.0 / cropped_bitmapData.height;
var new_width:Float = scale * cropped_bitmapData.width;
if (new_width > 600.0)
{
	scale *= (600.0 / new_width);
}
			
			
var matrix:Matrix = new Matrix();
matrix.scale(scale, scale);

var smallBMD:BitmapData = new BitmapData(Std.int(cropped_bitmapData.width * scale), Std.int(cropped_bitmapData.height * scale), false, Board.selectedBoard.color);
smallBMD.draw(cropped_bitmapData, matrix, null, null, null, true);


var b:ByteArray = smallBMD.encode (bitmapData.rect, new openfl.display.PNGEncoderOptions ());

return b;
```

**Comment by hopewise** [comment]
The bug is still there in `4.9.2`

**Comment by jgranick** [comment]
Is this still an issue with current versions?
