### ISSUE TITLE
TextField setTextFormat and letterSpacing has something wrong.

### ISSUE THREAD

**Issue by hpgood** [openfl/openfl#1508]
var txt:TextField = new TextField();
		var tf:TextFormat = new TextFormat();
		tf.font = "KaiTi_GB2312"; //embed unicode font name
		tf.size = 80;
		tf.color = 0x0000ff;
		tf.letterSpacing = 0;
		
		var tf2:TextFormat = new TextFormat();
		tf2.font = "KaiTi_GB2312";//embed unicode font name
		tf2.size = 80;
		tf2.color = 0xff0000;
		tf2.letterSpacing = 80;
		
		var tf3:TextFormat = new TextFormat();
		tf3.font = "KaiTi_GB2312";//embed unicode font name
		tf3.size = 80;
		tf3.color = 0x00ff00;
		tf3.letterSpacing = 80;

		
		txt.defaultTextFormat = tf;
		
		txt.embedFonts = true;
		txt.text = "a○b123";
		txt.x = 0;
		txt.y = 100;
		txt.width = 500;
		txt.height = 500;
		

		this.addChild(txt);
		
		
		txt.setTextFormat(tf2, 0, 1);
		#if android
		txt.setTextFormat(tf3, 1, 4);// 4 5
		#end
		#if flash
		txt.setTextFormat(tf3, 1, 2);
		#end

 it is ok fine in flash platform,but it is wrong in android platform.

**Comment by hpgood** [comment]
![20170220](https://cloud.githubusercontent.com/assets/3827559/23113798/948d30e4-f775-11e6-8803-f9dfea9babd3.png)  it render in flash  platform.

but in android ,it is wrong.

openfl 4.7.3
lime    3.7.2
hxcpp 3.4.49
openfl test android -x -v -Dnext -debug

**Comment by hpgood** [comment]
i add a pull request to fix this:
https://github.com/openfl/openfl/pull/1509

**Comment by jgranick** [comment]
Closing in favor of https://github.com/openfl/openfl/issues/1700
