### ISSUE TITLE
loadPCMFromByteArray does not follow flash behaviour

### ISSUE THREAD

**Issue by delahee** [openfl/openfl#1523]
Hi guys!

loadPCMFromByteArray does not work as expected on double kick heroes. The passed bytes are not used properly or setup functions are not executed faithfully to the flash version.

target : windows

what we use in flash : 
```haxe
var wavReader = new format.wav.Reader( new haxe.io.BytesInput( haxe.io.Bytes.ofData( ba )));
var waveData :format.wav.Data.WAVE = wavReader.read();
var f = new flash.media.Sound();
var channels = waveData.header.channels;
var bytesPerSample = waveData.header.bitsPerSample >> 3;
var samples = Math.round( waveData.data.length / ( channels * bytesPerSample ) );
var ba = hxd.ByteConversions.bytesToByteArray(waveData.data);
ba.position = 0;
f.loadPCMFromByteArray( ba, samples, bytesPerSample == 2?"short":"float", channels >= 2, 44100 );
```

but 

```haxe
var buf = lime.audio.AudioBuffer.fromBytes( resLoader.fs.get("deathmetal2_nodrums.wav").getBytes()  );
```

works perfectly, 

so I think loadPCMFromByteArray does not pass the correct bytes, we have to pass the raw PCM data without the headers for this function to work in flash, openfl should follow the same convention.
Thanks a lot!

[deathmetal1_cymbal1.zip](https://github.com/openfl/openfl/files/833749/deathmetal1_cymbal1.zip)

**Comment by jgranick** [comment]
How recent of a version are you using?

This was unimplemented before, but we have an initial implementation in place here:

https://github.com/openfl/openfl/blob/develop/openfl/media/Sound.hx#L138

Would be glad if you took a look :smile:

**Comment by delahee** [comment]
Ola,

I use vanilla haxe lib version, the sound is playing...except it does not
well, it sound badly interleaved or played too fast.

++

**Comment by jgranick** [comment]
Had the wrong `bitsPerSample` value, the sample works now 😁
