### ISSUE TITLE
Hi i had problems winth the file Lib

### ISSUE THREAD

**Issue by reaperspeeds** [openfl/openfl#1525]
I had an issue that some variables like resume or load is not found in this class...
This was remove entirely or  this was passed to another class...

Class <openfl.Lib> has no field resume ...
Class <openfl.Lib> has no field load...

How can i fix this error ?

**Comment by jgranick** [comment]
I believe there is no `Lib.pause` and `Lib.resume`, as we automatically pause or resume based on the behavior CADisplayLink on iOS. These methods were used in the past to prevent problems when using fullscreen overlays on the platform, but I believe now they are supported without an additional call.

For CFFI, try `lime.system.CFFI.load` :wink:
