### ISSUE TITLE
Can't load swfs unless you specify a class

### ISSUE THREAD

**Issue by MintPaw** [openfl/openfl#1526]
When call Asset.getMovieClip("mySwf:") it will not work, you must provide a class after the colon or you will get the following error:
```
TypeError: Error #1009: Cannot access a property or method of a null object reference.
	at openfl._internal.swf::SWFLibrary/getMovieClip()[/usr/lib/haxe/lib/openfl/git/openfl/_internal/swf/SWFLibrary.hx:76]
	at openfl.utils::Assets$/getMovieClip()[/usr/lib/haxe/lib/openfl/git/openfl/utils/Assets.hx:220]
	at Main()[Source/Main.hx:24]
	at DocumentClass()[Export/flash/debug/haxe/ApplicationMain.hx:301]
	at ApplicationMain$/start()[Export/flash/debug/haxe/ApplicationMain.hx:209]
	at MethodInfo-4()[Export/flash/debug/haxe/ApplicationMain.hx:94]
	at lime.app::_Event_Void_Void/dispatch()[/usr/lib/haxe/lib/lime/git/lime/_macros/EventMacro.hx:101]
	at lime.app::Preloader/start()
	at openfl.display::Preloader/display_onUnload()[/usr/lib/haxe/lib/openfl/git/openfl/display/Preloader.hx:109]
	at flash.events::EventDispatcher/dispatchEventFunction()
	at flash.events::EventDispatcher/dispatchEvent()
	at openfl.display::DefaultPreloader/onLoaded()[/usr/lib/haxe/lib/openfl/git/openfl/display/Preloader.hx:229]
	at openfl.display::DefaultPreloader/this_onComplete()[/usr/lib/haxe/lib/openfl/git/openfl/display/Preloader.hx:290]
	at flash.events::EventDispatcher/dispatchEventFunction()
	at flash.events::EventDispatcher/dispatchEvent()
	at openfl.display::Preloader/start()[/usr/lib/haxe/lib/openfl/git/openfl/display/Preloader.hx:51]
	at lime.app::Preloader/updateProgress()
	at lime.app::Preloader/current_onEnter()
```

This was tested with the layout example [by changing the arg to just "layout:"](https://github.com/openfl/openfl-samples/blob/master/libraries/layout/SimpleSWFLayout/Source/Main.hx#L24)

Tested in the Flash target with openfl@b4c2ec96 at openfl/lime@c593fd21, newest as of posting.

**Comment by jgranick** [comment]
Do you know if this worked in an older version of OpenFL (without a separate "library.swf" file being generated in the export directory)?

I tried to embed another SWF inside of a parent SWF as bytes, but this appeared to not work when I was testing, but it would help if there is another OpenFL release that did work somehow.

The above use-case should work in the meantime if you use `embed="false"` on the `<library />` tag

**Comment by MintPaw** [comment]
Yes, it did used to at in lime 2.9.1 and openfl 3.6.1 (HaxeFlixel versions). Although it was broken in recent versions.

I do need to pack all of the assets into a single swf, I've been using bash to embed the swfs with haxe -resource args which looks a bit like this:
```IFS=$$'\n'; \
assetVar=""; \
for f in `find ../assets/swf/*.swf -type f`; do \
assetVar="$$assetVar -resource $$f@`basename $$f .swf`"; \
done; \
IFS=$$' '; \
out=`haxe -main ApplicationMain --macro "openfl._internal.utils.ExtraParams.include()" -cp $(HAXELIB_LOC)/openfl/git -D openfl=4.9.0 --macro "lime.Lib.extraParams()" -cp $(HAXELIB_LOC)/lime/git -D lime=4.0.0 -cp $(HAXELIB_LOC)/actuate/1,8,7 -D actuate=1.8.7 --macro "keep('IntIterator')" -cp $(HAXELIB_LOC)/hscript/2,0,7 -D hscript=2.0.7 -cp $(HAXELIB_LOC)/hxInflate/0,3,0 -D hxInflate=0.3.0 -cp ../assets/openflManifest/flash/debug/haxe/_generated -cp src -cp $(HAXELIB_LOC)/openfl/git/externs/core/flash -cp $(HAXELIB_LOC)/openfl/git/externs/core/openfl -D native-trace -D tools=4.0.0 -D swf=1 -D flash-use-stage -D advanced-telemetry -D no-compilation -D openfl-flash -D OPENFL_ENGINE -D verbose=1 -D web --macro "allowPackage('flash')" -swf-lib ../assets/openflManifest/flash/debug/obj/assets.swf -swf-version 12 -cp ../assets/openflManifest/flash/debug/haxe \
-swf ../bin/game.swf $$assetVar $(ARGS) 2>&1`
```
The manifest files were created previously with `openfl update`

I can get the bytes internally and pass it off to a Loader, but I don't want it to be async, so I'm investigating [weird methods](https://www.kirupa.com/forum/showthread.php?223798-ActionScript-3-Tip-of-the-Day&p=1939827#post1939827) to duplicate loaders.

Is there a work around where I could pass the bytes in or use the new `openfl process` thing?

**Comment by MintPaw** [comment]
Any update on this? This is really the only feature I really use. Is there no other way to have openfl generate MovieClips from swfs synchronously, like passing the results from `openfl process` somehow?

The process really needs to be broken up, I don't like doing this whole `openfl update` hack to get the asset manifest, but running `openfl build` more than doubles the compile time and I don't need the assets recompiled every build. We need a way to use only the parts of the API that are useful to us, not just all or nothing. I'm going back to 3.6.1 for now, but I would like to be able to test out the new webgl stuff sometime. For now I've built a pixi.js back end for my html5 release. At this point I'd really just use Haxe by itself if the `-resource` thing didn't have the same async problem and am considering going all the way back to the Flex compiler if it can solve this issue.

**Comment by jgranick** [comment]
Thanks, `-resource` is working fine. We'll keep an eye on it, but for now I think this is solved :wink:
