### ISSUE TITLE
Http.onError not called upon a block due to cors policy

### ISSUE THREAD

**Issue by jerobarraco** [openfl/openfl#1530]
When i do a request to an url that is not on the same server a cors policy can block my request (which is totally normal). 
But i DO expect to get a notification, that could be a call to onError or onStatus or onData. neither gets called.

No exception is raised either.

**Comment by jgranick** [comment]
You should open an issue at https://github.com/haxefoundation/haxe if you are having an issue with a Haxe core API (such as `haxe.Http`)

Do you have better success if you try the `openfl.net.URLLoader` or `lime.net.HTTPRequest` APIs?

**Comment by jerobarraco** [comment]
Oh thanks, sorry for the mistake.
I will try those out.
