### ISSUE TITLE
[CPP] Bitmaps are not displaying

### ISSUE THREAD

**Issue by mayakwd** [openfl/openfl#1532]
Found strange behavior. This code works good on flash/html5 targets, and showing blank screen on windows. It was tested on 4.9.1 and 4.8.1 versions.
```haxe
package ;
import openfl.display.StageAlign;
import openfl.display.StageScaleMode;
import openfl.events.Event;
import openfl.display.Sprite;
import openfl.display.Bitmap;
import openfl.display.BitmapData;
import openfl.display.DisplayObject;
import openfl.events.MouseEvent;
class MainTest extends Sprite {
    private static var count:Int = 100;
    private static var bitmapData:BitmapData = new BitmapData(10, 10, false, 0xFF5588);

    private var particles:Array<DisplayObject> = [];

    public function new() {
        super();

        if (stage == null) {
            addEventListener(Event.ADDED_TO_STAGE, onAddedToStage);
        } else {
            initialize();
        }
    }

    private function onAddedToStage(event:Event):Void {
        removeEventListener(Event.ADDED_TO_STAGE, onAddedToStage);
        initialize();
    }

    private function initialize():Void {
        stage.scaleMode = StageScaleMode.NO_SCALE;
        stage.align = StageAlign.TOP_LEFT;

        createObjects();
    }

    private function createObjects():Void {
        for (i in 0...count) {
            particles.push(createParticle());
        }
    }

    private function createParticle():Bitmap {
        var bitmap = new Bitmap(bitmapData);
        bitmap.x = Math.random() * stage.stageWidth;
        bitmap.y = Math.random() * stage.stageHeight;
        addChild(bitmap);

        return bitmap;
    }
}

```

**Comment by Gama11** [comment]
Is this with Haxe 3.4.0 by chance? It had a bug that affected rendering and should be fixed in the subsequent 3.4.1 and 3.4.2 releases.

**Comment by mayakwd** [comment]
@Gama11, ah, got it! Thank you!

**Comment by Gama11** [comment]
So updating fixed it?

**Comment by mayakwd** [comment]
@Gama11 nope :-( With 3.4.2 and latests hxcpp it's crashing right after starting without any exception, just closing (on windows)

**Comment by mayakwd** [comment]
Huh, funny thing that it's crashing because of this line:

`    private static var bitmapData:BitmapData = new BitmapData(10, 10, false, 0xFF5588);
`

**Comment by mayakwd** [comment]
I moved creating bitmapData in initialize method.

Now it work good. I guess and earlier it wasn't rendering anything because of creating bitmapData before context become available.

**Comment by Gama11** [comment]
Hm.. this sounds a lot like https://github.com/openfl/openfl/issues/964, and that is supposed to be fixed.

**Comment by mayakwd** [comment]
@Gama11 Well, it should be but it's not. You can reproduce it by yourself with the given code :-)

**Comment by Gama11** [comment]
I guess I'll reopen this then. If this is limitation, it maybe at least shouldn't fail silently.

**Comment by jgranick** [comment]
Tested

Affects Haxe 3.2.1 and Haxe 3.4.2, it's a cause of _static initialization order_

If you change the 12th line:

```haxe
private static var bitmapData:BitmapData;
```

...and move the construction to your `new` constructor

```haxe
bitmapData = new BitmapData(10, 10, false, 0xFF5588);
```

...it will work properly on desktop Neko and C++. It avoids a SEGFAULT on C++ and "Invalid Call" runtime error in Neko, on Linux

The call is made to create a new `BitmapData` before our CFFI bindings are initialized. If someone has an improvement to this, I'm all ears!

I'm marking as closed for now, as this is a "won't fix" style issue, but if we can fix static initialization with CFFI calls, that would be an awesome improvement :+1:
