### ISSUE TITLE
No help for openfl test command

### ISSUE THREAD

**Issue by techtonik** [openfl/openfl#1537]
```
>openfl test --help
Error: Incorrect number of arguments for command 'test'

>openfl test -h
Error: Incorrect number of arguments for command 'test'
```
Where to look for test command parameters?

**Comment by Gama11** [comment]
```
>openfl help
[...]
Usage: openfl clean|update|build|run|test|display <project> (target) [options]
```

There's a list of possible targets and options later on, too.

**Comment by techtonik** [comment]
`>openfl help` is larger than my screen, so I don't see it.

**Comment by Gama11** [comment]
Scroll up? :D

**Comment by techtonik** [comment]
It is a file manager with "full screen" console window without scrollbars.

**Comment by Gama11** [comment]
I'd recommend something like [cmder](http://cmder.net/) (on Windows at least, for Linux / Mac there should be similar tools).

**Comment by techtonik** [comment]
I use http://farmanager.com/ and clink already, but that's irrelevant. Subcommands needs their more specific help, like in git etc.

**Comment by jasonsturges** [comment]
Pipe output to more / less, then scroll by page or line:

    $ openfl help | more -R

![more](https://cloud.githubusercontent.com/assets/1213591/24629588/2a6fec44-187f-11e7-8db9-6c7949777e8c.gif)

**Comment by techtonik** [comment]
But I don't need generic `openfl` help, I just need a single command help, like it works with hg, git, lint and pretty much any command line tool written in Python.

**Comment by jgranick** [comment]
This was added several versions ago :wink:
