### ISSUE TITLE
[Violation] Long running JavaScript task..

### ISSUE THREAD

**Issue by hopewise** [openfl/openfl#1541]
Using version 4.9.2 in html5, I started notice warnings like:
![screen shot 2017-04-01 at 11 20 06 am](https://cloud.githubusercontent.com/assets/1061157/24576928/408108a0-16cd-11e7-9dbb-4cbc1e0dc06e.png)

Here is profile file for investigation: https://gist.github.com/hopewise/d27fe50c28056b8d7d9eafc497818b88

**Comment by hopewise** [comment]
Any one got similar slowness?

**Comment by jgranick** [comment]
Can you find any information by going to "Profiles" in your developer tools, hitting the record button, refreshing the page, then hitting stop after this error has occurred?

Maybe that will give us information about what function specifically is taking too much time?

**Comment by hopewise** [comment]
Here: https://s3.amazonaws.com/logs.dcaclab/CPU-20170407T203220.cpuprofile

**Comment by hopewise** [comment]
Hello, Did you have a chance to analyze the log file?

**Comment by mayakwd** [comment]
It's not an OpenFL issue, angular cause it.
