### ISSUE TITLE
Compilation speed decrease with the introduction of lime/utils/AssetLibrary.hx

### ISSUE THREAD

**Issue by infidel-** [openfl/openfl#1542]
Coming from #1395, I've checked the Haxe issue, downloaded the Haxe 3.4.2 and it doesn't fix the compilation speed problem (also it has some macro bugs so I can't reliably use it for testing). Now since I know that openfl/lime had much better compilation speed before the releases I've updated to I've decided to go through all of them and pinpoint which release introduced the problem. I managed to do that: I believe that lime 3.5.0 + openfl 4.5.0 has a good compilation speed, while the next release (3.5.1 + 4.5.1) brings the speed drop. It also introduces lime/utils/Asset* collection of classes which are probably the culprit. You might ask why this issue is opened in openfl repo, but compiling the lime test project BunnyMark does not bring any speed drops while compliling openfl's DisplayingABitmap does. Here are the results.

I used Haxe 3.2.1 for testing because of the macro bugs in the current compilation server (Haxe 3.4.2). Each command is ran 4 times, and then compilation server is restarted. 

Another issue (that might be a separate one) is that running openfl command is 2 seconds slower than running haxe on the resulting hxml (I've included the results). 2 seconds is pretty big for me during the iteration process so maybe something can be done about it?

```
openfl create DisplayingABitmap
```

Before AssetLibrary, etc is introduced (lime 3.5.0, openfl 4.5.0):
```
infidel@purplestar ~/p/DisplayingABitmap> time -p openfl build project.xml html5 --connect 6000
real 4.47
user 0.69
sys 0.53
infidel@purplestar ~/p/DisplayingABitmap> time -p openfl build project.xml html5 --connect 6000
real 2.65
user 0.49
sys 0.47
infidel@purplestar ~/p/DisplayingABitmap> time -p openfl build project.xml html5 --connect 6000
real 2.88
user 0.49
sys 0.42
infidel@purplestar ~/p/DisplayingABitmap> time -p openfl build project.xml html5 --connect 6000
real 2.41
user 0.48
sys 0.48
```

Approximately 4.5s -> 2.5s.

Restart haxe compilation server.

```
infidel@purplestar ~/p/DisplayingABitmap> time -p haxe Export/html5/release/haxe/release.hxml --connect 6000
real 3.43
user 0.03
sys 0.08
infidel@purplestar ~/p/DisplayingABitmap> time -p haxe Export/html5/release/haxe/release.hxml --connect 6000
real 0.81
user 0.05
sys 0.05
infidel@purplestar ~/p/DisplayingABitmap> time -p haxe Export/html5/release/haxe/release.hxml --connect 6000
real 0.70
user 0.02
sys 0.05
infidel@purplestar ~/p/DisplayingABitmap> time -p haxe Export/html5/release/haxe/release.hxml --connect 6000
real 0.78
user 0.03
sys 0.05
```

3.4s -> 0.7s.

First release with AssetLibrary (lime 3.5.1, openfl 4.5.1):

```
infidel@purplestar ~/p/DisplayingABitmap> time -p openfl build project.xml html5 --connect 6000
real 6.76
user 0.75
sys 0.50
infidel@purplestar ~/p/DisplayingABitmap> time -p openfl build project.xml html5 --connect 6000
real 4.89
user 0.50
sys 0.44
infidel@purplestar ~/p/DisplayingABitmap> time -p openfl build project.xml html5 --connect 6000
real 4.71
user 0.52
sys 0.44
infidel@purplestar ~/p/DisplayingABitmap> time -p openfl build project.xml html5 --connect 6000
real 3.90
user 0.48
sys 0.44
```

6s -> 4s.

Restart compilation server

```
infidel@purplestar ~/p/DisplayingABitmap> time -p haxe Export/html5/release/haxe/release.hxml --connect 6000
real 5.65
user 0.03
sys 0.03
infidel@purplestar ~/p/DisplayingABitmap> time -p haxe Export/html5/release/haxe/release.hxml --connect 6000
real 4.30
user 0.04
sys 0.09
infidel@purplestar ~/p/DisplayingABitmap> time -p haxe Export/html5/release/haxe/release.hxml --connect 6000
real 4.07
user 0.04
sys 0.03
infidel@purplestar ~/p/DisplayingABitmap> time -p haxe Export/html5/release/haxe/release.hxml --connect 6000
real 3.08
user 0.02
sys 0.04
```

5s->3s

Latest release, just to check the problem persists (lime 4.0.3, openfl 4.9.2):

```
infidel@purplestar ~/p/DisplayingABitmap> time -p openfl build project.xml html5 --connect 6000
real 8.34
user 0.78
sys 0.79
infidel@purplestar ~/p/DisplayingABitmap> time -p openfl build project.xml html5 --connect 6000
real 5.06
user 0.60
sys 0.41
infidel@purplestar ~/p/DisplayingABitmap> time -p openfl build project.xml html5 --connect 6000
real 6.36
user 0.50
sys 0.44
infidel@purplestar ~/p/DisplayingABitmap> time -p openfl build project.xml html5 --connect 6000
real 5.02
user 0.49
sys 0.48
```
8s ->5s, even worse than before.

Restart compilation server

```
infidel@purplestar ~/p/DisplayingABitmap> time -p haxe Export/html5/release/haxe/release.hxml --connect 6000
real 6.68
user 0.02
sys 0.08
infidel@purplestar ~/p/DisplayingABitmap> time -p haxe Export/html5/release/haxe/release.hxml --connect 6000
real 4.17
user 0.03
sys 0.08
infidel@purplestar ~/p/DisplayingABitmap> time -p haxe Export/html5/release/haxe/release.hxml --connect 6000
real 5.61
user 0.02
sys 0.08
```
Doesn't look like the compilation server helps much.

And here are the lime test results (Haxe 3.2.1 again):

```
lime create BunnyMark
```

Before AssetLibrary (lime 3.5.0):

```
infidel@purplestar ~/p/BunnyMark> time -p lime build project.xml html5 --connect 6000
real 2.70
user 0.52
sys 0.40
infidel@purplestar ~/p/BunnyMark> time -p lime build project.xml html5 --connect 6000
real 0.90
user 0.32
sys 0.32
infidel@purplestar ~/p/BunnyMark> time -p lime build project.xml html5 --connect 6000
real 0.90
user 0.34
sys 0.31
infidel@purplestar ~/p/BunnyMark> time -p lime build project.xml html5 --connect 6000
real 0.94
user 0.35
sys 0.31

```

Restart compilation server

```
infidel@purplestar ~/p/BunnyMark> time -p haxe Export/html5/release/haxe/release.hxml --connect 6000
real 1.85
user 0.02
sys 0.04
infidel@purplestar ~/p/BunnyMark> time -p haxe Export/html5/release/haxe/release.hxml --connect 6000
real 0.29
user 0.04
sys 0.02
infidel@purplestar ~/p/BunnyMark> time -p haxe Export/html5/release/haxe/release.hxml --connect 6000
real 0.34
user 0.04
sys 0.04
infidel@purplestar ~/p/BunnyMark> time -p haxe Export/html5/release/haxe/release.hxml --connect 6000
real 0.36
user 0.02
sys 0.08
```

First release with Asset* stuff (lime 3.5.1):

```
infidel@purplestar ~/p/BunnyMark> time -p lime build project.xml html5 --connect 6000
real 2.66
user 0.53
sys 0.43
infidel@purplestar ~/p/BunnyMark> time -p lime build project.xml html5 --connect 6000
real 0.86
user 0.34
sys 0.27
infidel@purplestar ~/p/BunnyMark> time -p lime build project.xml html5 --connect 6000
real 0.90
user 0.34
sys 0.28
infidel@purplestar ~/p/BunnyMark> time -p lime build project.xml html5 --connect 6000
real 0.96
user 0.40
sys 0.31
```
Restart compilation server

```
infidel@purplestar ~/p/BunnyMark> time -p haxe Export/html5/release/haxe/release.hxml --connect 6000
real 1.87
user 0.02
sys 0.03
infidel@purplestar ~/p/BunnyMark> time -p haxe Export/html5/release/haxe/release.hxml --connect 6000
real 0.33
user 0.03
sys 0.04
infidel@purplestar ~/p/BunnyMark> time -p haxe Export/html5/release/haxe/release.hxml --connect 6000
real 0.35
user 0.04
sys 0.04
infidel@purplestar ~/p/BunnyMark> time -p haxe Export/html5/release/haxe/release.hxml --connect 6000
real 0.41
user 0.04
sys 0.10
```

No compilation speed drop.

Latest release (lime 4.0.3):

```
infidel@purplestar ~/p/BunnyMark> time -p lime build project.xml html5 --connect 6000
real 3.87
user 0.61
sys 0.42
infidel@purplestar ~/p/BunnyMark> time -p lime build project.xml html5 --connect 6000
real 2.15
user 0.38
sys 0.30
infidel@purplestar ~/p/BunnyMark> time -p lime build project.xml html5 --connect 6000
real 2.36
user 0.38
sys 0.28
infidel@purplestar ~/p/BunnyMark> time -p lime build project.xml html5 --connect 6000
real 1.88
user 0.40
sys 0.24
```
Restart compilation server

```
infidel@purplestar ~/p/BunnyMark> time -p haxe Export/html5/release/haxe/release.hxml --connect 6000
real 2.99
user 0.04
sys 0.05
infidel@purplestar ~/p/BunnyMark> time -p haxe Export/html5/release/haxe/release.hxml --connect 6000
real 1.64
user 0.04
sys 0.05
infidel@purplestar ~/p/BunnyMark> time -p haxe Export/html5/release/haxe/release.hxml --connect 6000
real 1.73
user 0.05
sys 0.05
infidel@purplestar ~/p/BunnyMark> time -p haxe Export/html5/release/haxe/release.hxml --connect 6000
real 1.34
user 0.03
sys 0.07
```
No drop between the problematic versions but there is a significant one on the latest one. I'll try to find the problematic lime release for that one and create an issue in their tracker.

**Comment by jgranick** [comment]
Current OpenFL, before https://github.com/openfl/lime/commit/ead9ed12737e2183f5a2940c351be05c6cf389ab

```
name     | time(s) |   % |      # | info
-----------------------------------
analyzer |   0.340 |   7 | 121148 | 
filters  |   0.260 |   5 |      1 | 
generate |   0.910 |  18 |      1 | 
  neko   |   0.910 |  18 |      1 | 
macro    |   1.320 |  25 |    117 | 
other    |   0.370 |   7 |      1 | 
parsing  |   0.430 |   8 |   1280 | 
typing   |   1.550 |  30 |   3517 | 
-----------------------------------
total    |   5.180 | 100 |      0 | 
```

Current OpenFL, after https://github.com/openfl/lime/commit/ead9ed12737e2183f5a2940c351be05c6cf389ab

```
name     | time(s) |   % |      # | info
-----------------------------------
analyzer |   0.320 |  11 | 100697 | 
filters  |   0.370 |  13 |      1 | 
generate |   0.830 |  29 |      1 | 
  neko   |   0.830 |  29 |      1 | 
macro    |   0.500 |  17 |    117 | 
other    |   0.030 |   1 |      1 | 
parsing  |   0.280 |  10 |    761 | 
typing   |   0.530 |  19 |   3517 | 
-----------------------------------
total    |   2.860 | 100 |      0 | 
```

OpenFL 4.5.0

```
name     | time(s) |   % |     # | info
----------------------------------
analyzer |   0.350 |  12 | 85680 | 
filters  |   0.300 |  11 |     1 | 
generate |   0.750 |  27 |     1 | 
  neko   |   0.750 |  27 |     1 | 
macro    |   0.390 |  14 |   143 | 
other    |   0.310 |  11 |     1 | 
parsing  |   0.260 |   9 |   662 | 
typing   |   0.460 |  16 |  3158 | 
----------------------------------
total    |   2.820 | 100 |     0 | 
```

I'd say we have our culprit :wink:

**Comment by infidel-** [comment]
Glad you've found the thing. Can you say something about this, though? 

> Another issue (that might be a separate one) is that running openfl command is 2 seconds slower than running haxe on the resulting hxml (I've included the results). 2 seconds is pretty big for me during the iteration process so maybe something can be done about it?

So, I use directly compiling the hxml with haxe as a hack and it works fine in JS case but that begs the question what does the command do on top of that?

**Comment by jgranick** [comment]
Try `-verbose` when you run the OpenFL command, does anything appear to stand out as taking longer than other steps?

**Comment by infidel-** [comment]
I've recorded a video with -verbose and went over it frame by frame with avidemux. 
The second compilation is 3.53s total.

It takes 0.97s from the program start to this line:
```
Running command: BUILD
 - Running command: haxe Export/html5/release/haxe/release.hxml
```

And it's 2.43s from there on until the program finishes. I would say there must be something else in there because immediately after that I ran Haxe on the hxml file. It took 1.15s according to avidemux and 1.13s according to time.

**Comment by jgranick** [comment]
Here is the portion of `HTML5Platform` that executes during that step:

https://github.com/openfl/lime/blob/develop/lime/tools/platforms/HTML5Platform.hx#L56-L70

If it is performing minification, you should get an additional verbose message when it runs the closure minifier on it.

An average `openfl test html5` command will parse the project, copy files, call Haxe to build then will run a node HTTP server for testing. Perhaps 1.13 seconds is spent on this step, then afterward it is booting the web server, or does the Haxe build appear to take longer when executed through the Lime tools?

**Comment by infidel-** [comment]
> If it is performing minification, you should get an additional verbose message when it runs the closure minifier on it.

No minification, so no more messages after the build one.

> An average openfl test html5 command will parse the project, copy files, call Haxe to build then will run a node HTTP server for testing. 

I don't use openfl test command, only openfl build.

> Perhaps 1.13 seconds is spent on this step, then afterward it is booting the web server, or does the Haxe build appear to take longer when executed through the Lime tools?

Same times through lime.


I took some time to dig around the HTML5Platform.hx, then went on to ProcessHelper.hx and paradoxically the problem is this line:
```
result = Sys.command (command, args);
```
https://github.com/openfl/lime/blob/develop/lime/tools/helpers/ProcessHelper.hx#L226

Takes 7-8 seconds every time on my project and it just does "haxe .bin/html5/release/haxe/release.hxml", while the same command ran manually completes in 2.5 seconds. The only difference I see is that my custom build macro to get git release info is not executed with manual command. My guess is that somehow all the macros are recompiled and reran in the first case and that increases the compilation time. I have no clue why though, since the calls are identical. The environment variables from Sys.environment() only show two things that might do something:
```
HAXELIB_RUN => 1
LIME_CONFIG => /home/infidel/.lime/config.xml
```
The lime config sets some directories but that's it. So maybe haxe 3.2.1 in haxelib mode forces some different compilation pathway.

**Comment by jgranick** [comment]
Interesting

Can you try and disable the macro, and see if the performance is the same, or not? Perhaps there's an issue with `Sys.command` performance somehow, or something to do with the current working directory being different in both cases?

**Comment by infidel-** [comment]
Disabling my macro does not help with the performance. I've tried to make a Sys.command call from a different neko program, it works fine.

That's an interesting idea, but Sys.getCwd() returns that the working directory is of my project. I've noticed the PWD environment variable set to lime directory but changing that before the Sys.command call does not fix it.

**Comment by jgranick** [comment]
If you use `--times` does Haxe report the same compile-time, either way?

Also, if you edit your command-line tools, you can add a trace before and after the Haxe compilation call (with a time calculation) to see if the time delay you're seeing is completely on this one call, or is somehow occuring after/elsewhere

**Comment by infidel-** [comment]
I did add a trace when I commented about my project. Thanks for the --times suggestion, it shows some valuable info.

The code ("t" is set at the method start):
```
        trace('_runCommand t2a:' + (Sys.time() - t) + ' ' + args);
        Sys.command ("set", []);
		if (!dryRun) {
			if (args != null && args.length > 0) {
				result = Sys.command (command, args);
			} else {
				result = Sys.command (command);
			}
        trace('_runCommand t2b:' + (Sys.time() - t));
```

Running through lime command-line tool:
```
ProcessHelper.hx:231: _runCommand t2a:0.000154018402099609 [.bin/html5/release/haxe/release.hxml]
Total time : 7.190s
------------------------------------
  command : 0.060s, 1%
  filters : 2.380s, 33%
  generate js : 0.430s, 6%
  haxelib : 0.020s, 0%
  macro execution : 2.570s, 36%
  module cache check : 0.150s, 2%
  other : 0.180s, 3%
  parsing : 0.010s, 0%
  typing : 1.390s, 19%
ProcessHelper.hx:249: _runCommand t2b:7.50020623207092
```

With haxe:
```
infidel@purplestar ~/p/parasite> time -p haxe .bin/html5/release/haxe/release.hxml --times
Total time : 2.630s
------------------------------------
  filters : 1.780s, 68%
  generate js : 0.430s, 16%
  haxelib : 0.020s, 1%
  macro execution : 0.000s, 0%
  module cache check : 0.310s, 12%
  other : 0.090s, 3%
  typing : 0.000s, 0%
real 2.80
user 0.03
sys 0.09
```

"macro" and "typing" take zero seconds, and "filters" are a bit faster.

**Comment by jgranick** [comment]
Wow, I wish I had known about -Dmacro-times when we were debugging the performance earlier. 

Is it possible we have different versions of Haxe or Lime/OpenFL in play? It seems suspicious that the --times output has different items listed.

One shows "parsing" at 0%, the other does not even list "parsing", similarly, "command" is only present in the longer command as well.

Perhaps you could add another command in your tools, such as `Sys.command ("", "which", [ "haxe" ]);` and run it separately the same way you are executing the HXML directly. 

If there is a compilation server involved, it may also be valuable to test a clean update before running directly, such as:

```bash
openfl build html5 -clean --times
openfl update html5 -clean
haxe .bin/html5/release/haxe/release.hxml --times
```

**Comment by infidel-** [comment]
> Perhaps you could add another command in your tools, such as Sys.command ("", "which", [ "haxe" ]); and run it separately the same way you are executing the HXML directly.

/usr/bin/haxe in both cases.

> If there is a compilation server involved, it may also be valuable to test a clean update before running directly, such as:

I restarted the compilation server each time. These are the results from second or third run when it should kick in.

> One shows "parsing" at 0%, the other does not even list "parsing", similarly, "command" is only present in the longer command as well.

On that note, here's how it looks when haxe is executed for the first time directly after the compilation server restart:
```
infidel@purplestar ~/p/parasite> time -p haxe .bin/html5/release/haxe/release.hxml --times -D macro-times=1
git rev-list HEAD --count > COUNT
Total time : 9.420s
------------------------------------
  command : 0.060s, 1%
  filters : 3.260s, 35%
  generate js : 0.340s, 4%
  haxelib : 0.000s, 0%
  macro ApplicationMain.getEntryPoint : 0.000s, 0%
  macro ApplicationMain.getPreloader : 0.000s, 0%
  macro DocumentClass.build : 0.000s, 0%
  macro Version.getBuild : 0.040s, 0%
  macro Version.getVersion : 0.000s, 0%
  macro com.haxepunk.utils.HaxelibInfoBuilder.build : 0.010s, 0%
  macro haxe.macro.Compiler.keep : 0.000s, 0%
  macro haxe.ui.macros.BackendMacros.processBackend : 0.410s, 4%
  macro haxe.ui.macros.ComponentMacros.buildComponent : 0.010s, 0%
  macro haxe.ui.macros.Macros.addClonable : 0.230s, 2%
  macro haxe.ui.macros.Macros.buildBindings : 0.090s, 1%
  macro haxe.ui.macros.Macros.buildStyles : 0.090s, 1%
  macro haxe.ui.macros.ModuleMacros.processModules : 0.530s, 6%
  macro haxe.ui.macros.NativeMacros.processNative : 0.390s, 4%
  macro lime.Lib.extraParams : 0.000s, 0%
  macro lime._macros.AssetsMacro.cacheVersion : 0.000s, 0%
  macro lime._macros.AssetsMacro.embedBytes : 0.010s, 0%
  macro lime._macros.AssetsMacro.embedFont : 0.010s, 0%
  macro lime._macros.EventMacro.build : 0.030s, 0%
  macro lime._macros.HTTPRequestMacro.build : 0.010s, 0%
  macro lime.system.CFFI.build : 0.000s, 0%
  macro openfl._internal.macros.ShaderMacro.build : 0.010s, 0%
  macro openfl._internal.utils.ExtraParams.include : 0.000s, 0%
  macro typing (+init) : 0.630s, 7%
  module cache check : 0.090s, 1%
  other : 0.400s, 4%
  parsing : 1.360s, 14%
  typing : 1.410s, 15%
real 9.71
user 0.03
sys 0.06
```

So basically somehow when haxe runs through lime tool, it does not use the compilation server data. However the generated HXML file does contain the "--connect 6000" line and if I stop the compilation server before running the lime command, it will result in an error saying that it's not there. So it does connect to it but does not use it's cached thing.

Is there some way that the compiler considers that code different? For example the command-line tool moves the code somewhere? Or the tool changes the modification timestamp for some important files (ApplicationMain.hx or something like this) and compiler thinks that the code changed and does the full run?

For example, if I change a line in of my project files and run haxe, I see the following:
```
infidel@purplestar ~/p/parasite> time -p haxe .bin/html5/release/haxe/release.hxml --times -D macro-times=1
git rev-list HEAD --count > COUNT
Total time : 2.970s
------------------------------------
  command : 0.050s, 2%
  filters : 1.760s, 59%
  generate js : 0.390s, 13%
  haxelib : 0.010s, 0%
  macro ApplicationMain.getEntryPoint : 0.000s, 0%
  macro ApplicationMain.getPreloader : 0.000s, 0%
  macro DocumentClass.build : 0.000s, 0%
  macro Version.getBuild : 0.000s, 0%
  macro Version.getVersion : 0.000s, 0%
  macro haxe.macro.Compiler.keep : 0.000s, 0%
  macro haxe.ui.macros.ComponentMacros.buildComponent : 0.010s, 0%
  macro lime.Lib.extraParams : 0.000s, 0%
  macro openfl._internal.utils.ExtraParams.include : 0.000s, 0%
  macro typing (+init) : 0.010s, 0%
  module cache check : 0.300s, 10%
  other : 0.010s, 0%
  parsing : 0.010s, 0%
  typing : 0.420s, 14%
```
Parsing and command are there but half of the macros are not. Git line is from my macro recompiled and re-executed.

**Comment by jgranick** [comment]
Would you mind trying compilation without a compilation server, and comparing the times? That way we can eliminate any other possible issues.

If the times are the same without a compilation server, then it means we can focus only on what would cause the compilation server to invalidate its cache, rather than worrying about other aspects of the tools

Thanks :smile:

**Comment by infidel-** [comment]
Sure. They're roughly the same:

```
infidel@purplestar ~/p/parasite> lime build project.nmml html5 --times -Dmacro-times=1
Warning: Could not find generated font file "assets/font/Orkney-Regular.svg"
git rev-list HEAD --count > COUNT
Total time : 8.420s
------------------------------------
  filters : 2.500s, 30%
  generate js : 0.340s, 4%
  haxelib : 0.010s, 0%
  macro ApplicationMain.getEntryPoint : 0.000s, 0%
  macro ApplicationMain.getPreloader : 0.000s, 0%
  macro DocumentClass.build : 0.000s, 0%
  macro Version.getBuild : 0.040s, 0%
  macro Version.getVersion : 0.000s, 0%
  macro com.haxepunk.utils.HaxelibInfoBuilder.build : 0.000s, 0%
  macro haxe.macro.Compiler.keep : 0.000s, 0%
  macro haxe.ui.macros.BackendMacros.processBackend : 0.350s, 4%
  macro haxe.ui.macros.ComponentMacros.buildComponent : 0.010s, 0%
  macro haxe.ui.macros.Macros.addClonable : 0.230s, 3%
  macro haxe.ui.macros.Macros.buildBindings : 0.080s, 1%
  macro haxe.ui.macros.Macros.buildStyles : 0.220s, 3%
  macro haxe.ui.macros.ModuleMacros.processModules : 0.540s, 6%
  macro haxe.ui.macros.NativeMacros.processNative : 0.320s, 4%
  macro lime.Lib.extraParams : 0.000s, 0%
  macro lime._macros.AssetsMacro.cacheVersion : 0.000s, 0%
  macro lime._macros.AssetsMacro.embedBytes : 0.010s, 0%
  macro lime._macros.AssetsMacro.embedFont : 0.010s, 0%
  macro lime._macros.EventMacro.build : 0.100s, 1%
  macro lime._macros.HTTPRequestMacro.build : 0.000s, 0%
  macro lime.system.CFFI.build : 0.000s, 0%
  macro openfl._internal.macros.ShaderMacro.build : 0.030s, 0%
  macro openfl._internal.utils.ExtraParams.include : 0.000s, 0%
  macro typing (+init) : 0.450s, 5%
  other : 0.310s, 4%
  parsing : 1.480s, 18%
  typing : 1.390s, 17%
```

```
infidel@purplestar ~/p/parasite> haxe .bin/html5/release/haxe/release.hxml --times -D macro-times
git rev-list HEAD --count > COUNT
Total time : 8.590s
------------------------------------
  filters : 2.620s, 31%
  generate js : 0.330s, 4%
  haxelib : 0.000s, 0%
  macro ApplicationMain.getEntryPoint : 0.000s, 0%
  macro ApplicationMain.getPreloader : 0.000s, 0%
  macro DocumentClass.build : 0.000s, 0%
  macro Version.getBuild : 0.040s, 0%
  macro Version.getVersion : 0.000s, 0%
  macro com.haxepunk.utils.HaxelibInfoBuilder.build : 0.000s, 0%
  macro haxe.macro.Compiler.keep : 0.000s, 0%
  macro haxe.ui.macros.BackendMacros.processBackend : 0.170s, 2%
  macro haxe.ui.macros.ComponentMacros.buildComponent : 0.010s, 0%
  macro haxe.ui.macros.Macros.addClonable : 0.200s, 2%
  macro haxe.ui.macros.Macros.buildBindings : 0.100s, 1%
  macro haxe.ui.macros.Macros.buildStyles : 0.200s, 2%
  macro haxe.ui.macros.ModuleMacros.processModules : 0.530s, 6%
  macro haxe.ui.macros.NativeMacros.processNative : 0.370s, 4%
  macro lime.Lib.extraParams : 0.000s, 0%
  macro lime._macros.AssetsMacro.cacheVersion : 0.000s, 0%
  macro lime._macros.AssetsMacro.embedBytes : 0.060s, 1%
  macro lime._macros.AssetsMacro.embedFont : 0.000s, 0%
  macro lime._macros.EventMacro.build : 0.050s, 1%
  macro lime._macros.HTTPRequestMacro.build : 0.000s, 0%
  macro lime.system.CFFI.build : 0.000s, 0%
  macro openfl._internal.macros.ShaderMacro.build : 0.030s, 0%
  macro openfl._internal.utils.ExtraParams.include : 0.000s, 0%
  macro typing (+init) : 0.850s, 10%
  other : 0.370s, 4%
  parsing : 1.270s, 15%
  typing : 1.390s, 16%

```

**Comment by jgranick** [comment]
Okay, cool -- so the issue is then related to the Haxe compilation server.

On the "update" step, we copy new versions of templated files (such as ApplicationMain) over each build. Among other possible explanations, perhaps the time stamp on those files changing makes a difference?

You could try using `touch` then running the manual HXML build again, and see if that increases the build times

**Comment by infidel-** [comment]
Yep, touching ApplicationMain.hx makes the compilation server to re-run the full compilation. Touching DefaultAssetLibrary.hx does not.

Also, I've checked haxe 3.4.2 out of curiosity and this behavior seems to be a haxe 3.2.1 problem. In haxe 3.4.2 both subsequent runs of lime tool and haxe are fast (1.6s vs 3s for older haxe, btw). I'm also not getting the macro errors in my project which are happening when I'm trying to compile the test lime projects.

**Comment by jgranick** [comment]
You can try out these changes, and see if it helps:

https://github.com/openfl/lime/tree/feature/sparse-template-copy

This will only copy template files if they change, however `ApplicationMain.hx` changes each time because of the build number value

**Comment by infidel-** [comment]
Well, that seems to fix it.

```
infidel@purplestar ~/p/parasite> haxelib list lime
lime-samples: [3.4.0] 2.6.0
lime: 3.4.1 3.1.0 3.7.4 2.9.1 lime.git 3.4.0 4.0.3 4.0.0 3.7.0 3.5.1 3.5.0 2.7.0 3.0.0 2.6.0 2.8.0 3.5.2 [dev:/home/infidel/haxelib/lime/lime.git]
```

On the first run after compilation server restart:
```
infidel@purplestar ~/p/parasite> lime build project.nmml html5 --times -Dmacro-times=1 --connect 6000
Warning: Could not find generated font file "assets/font/Orkney-Regular.svg"
git rev-list HEAD --count > COUNT
Total time : 8.950s
------------------------------------
  command : 0.040s, 0%
  filters : 2.290s, 26%
  generate js : 0.380s, 4%
  haxelib : 0.000s, 0%
  macro ApplicationMain.getEntryPoint : 0.000s, 0%
  macro ApplicationMain.getPreloader : 0.000s, 0%
  macro DocumentClass.build : 0.000s, 0%
  macro Version.getBuild : 0.020s, 0%
  macro Version.getVersion : 0.000s, 0%
  macro com.haxepunk.utils.HaxelibInfoBuilder.build : 0.010s, 0%
  macro haxe.macro.Compiler.keep : 0.000s, 0%
  macro haxe.ui.macros.BackendMacros.processBackend : 0.590s, 7%
  macro haxe.ui.macros.ComponentMacros.buildComponent : 0.030s, 0%
  macro haxe.ui.macros.Macros.addClonable : 0.240s, 3%
  macro haxe.ui.macros.Macros.buildBindings : 0.110s, 1%
  macro haxe.ui.macros.Macros.buildStyles : 0.180s, 2%
  macro haxe.ui.macros.ModuleMacros.processModules : 0.720s, 8%
  macro haxe.ui.macros.NativeMacros.processNative : 0.590s, 7%
  macro lime.Lib.extraParams : 0.000s, 0%
  macro lime._macros.AssetsMacro.cacheVersion : 0.000s, 0%
  macro lime._macros.AssetsMacro.embedBytes : 0.010s, 0%
  macro lime._macros.AssetsMacro.embedFont : 0.000s, 0%
  macro lime._macros.EventMacro.build : 0.080s, 1%
  macro lime._macros.HTTPRequestMacro.build : 0.020s, 0%
  macro lime.system.CFFI.build : 0.000s, 0%
  macro openfl._internal.macros.ShaderMacro.build : 0.010s, 0%
  macro openfl._internal.utils.ExtraParams.include : 0.010s, 0%
  macro typing (+init) : 0.660s, 7%
  module cache check : 0.020s, 0%
  other : 0.390s, 4%
  parsing : 1.300s, 15%
  typing : 1.250s, 14%
```

On subsequent runs:
```
infidel@purplestar ~/p/parasite> lime build project.nmml html5 --times -Dmacro-times=1 --connect 6000
Warning: Could not find generated font file "assets/font/Orkney-Regular.svg"
Total time : 2.560s
------------------------------------
  filters : 1.740s, 68%
  generate js : 0.400s, 16%
  haxelib : 0.010s, 0%
  macro haxe.macro.Compiler.keep : 0.000s, 0%
  macro lime.Lib.extraParams : 0.000s, 0%
  macro openfl._internal.utils.ExtraParams.include : 0.000s, 0%
  macro typing (+init) : 0.010s, 0%
  module cache check : 0.400s, 16%
  other : 0.000s, 0%
  typing : 0.000s, 0%
```

**Comment by jgranick** [comment]
Merged into "develop", we'll improve from here. Thank you again for your help 👍

**Comment by infidel-** [comment]
Thank you, too :smile:
