### ISSUE TITLE
Smoothing issue in Stage3D HTML API

### ISSUE THREAD

**Issue by TomByrne** [openfl/openfl#1545]
I have found when using Starling 1.8 in HTML5 that using TextureSmoothing.BINLINEAR doesn't add any smoothing to the texture.

I have tracked this down to the RenderSupport class which writes the following AGAL based on this setting:

```       if (smoothing == TextureSmoothing.NONE)
        {
            options.push("nearest");
            options.push(mipMapping ? "mipnearest" : "mipnone");
        }
        else if (smoothing == TextureSmoothing.BILINEAR)
        {
            options.push("linear");
            options.push(mipMapping ? "mipnearest" : "mipnone");
        }
        else
        {
            options.push("linear");
            options.push(mipMapping ? "miplinear" : "mipnone");
        }
```

It seems that when "mipnearest" is used, no smoothing is applied to the texture (unlike when this same AGAL is used in AIR).
I'm guessing this is an issue with the AGAL > GLSL conversion, but I don't know enough about this code to say for sure.

**Comment by TomByrne** [comment]
I have added a temporary workaround for this to Starling 1.8:
https://github.com/openfl/starling/commit/0315a7fdbf1c8024a61490997698db2e10e0f5d1

**Comment by jgranick** [comment]
Does this fix it for you? https://github.com/openfl/openfl/commit/0582e302317808f3ae1fb365dec1a30e572daeab

**Comment by TomByrne** [comment]
Hi Joshua, thanks for the quick reply.
That did not appear to fix the issue for me.

Also, I have noticed that using 'mipnearest' causes artifacts in all browsers I tested (Chrome, Firefox, IE11).
This was the case with and without your proposed changes (0582e30).
Haven't been able to establish whether this is an Openfl, Lime or Starling issue yet.
For now the workaround above gives to only presentable results.

1. Trilinear/Miplinear    2. Bilinear/Mipnearest
![mipnearestbug](https://cloud.githubusercontent.com/assets/274228/24893036/17053ec0-1ec4-11e7-8418-6938958bb732.jpg)

**Comment by jgranick** [comment]
Is there a sample I could try (or modifications to a sample) that I could use to replicate this issue? I'd like to be able to see for myself, to experiment with changes. Thank you

**Comment by jgranick** [comment]
I did another sweep through our code, and found some places that were inconsistent. If I'm not understanding the meaning of `GL.LINEAR_MIPMAP_NEAREST` and `GL.NEAREST_MIPMAP_LINEAR`, then I believe it should work. I don't have a sample, but give it a try and see

https://github.com/openfl/openfl/commit/2054292a2aff1aed6b15d1a83ff263e5e6a681cd

If it is not right now, then I believe (perhaps) I am misunderstanding, and we just need to switch the meaning. I have taken `GL.LINEAR_MIPMAP_NEAREST` to mean linear smoothing, but nearest mipmap selection, but there's a chance the meaning is the reverse.

**Comment by TomByrne** [comment]
Sorry for the delay.
These changes do not appear to fix the issue.

Here's how to reproduce:
```
package;

import openfl.Assets;
import openfl.display.Sprite;
import starling.core.Starling;
import starling.display.Image;
import starling.events.Event;
import starling.textures.Texture;

class TestMipmap extends Sprite 
{
	var mStarling:Starling;
	
	public function new() 
	{
		super();
		
        mStarling = new Starling(starling.display.Sprite, stage);
        mStarling.stage.stageWidth = 500;
        mStarling.stage.stageHeight = 500;
        mStarling.addEventListener(Event.ROOT_CREATED, function():Void
        {
			var bitmap = Assets.getBitmapData("MontserratBold_1142.png");
			var texture = Texture.fromBitmapData(bitmap);
			var root:starling.display.Sprite = cast mStarling.root;
			var img = new Image(texture);
			img.scale = 0.05;
			root.addChild(img);
        });

        mStarling.start();
		
	}
	
}
```
When the image isn't scaled it appears fine, but as the scale reduces the mipmapping starts behaving weirdly.

Screenshot of the messed up result:
![mipmapissue](https://cloud.githubusercontent.com/assets/274228/26750631/23dbeda8-486b-11e7-992e-7fc07ced2dd6.JPG)


The texture used:
![montserratbold_1142](https://cloud.githubusercontent.com/assets/274228/26750623/049e0a2a-486b-11e7-9236-f403c2c37e3c.png)

**Comment by jgranick** [comment]
This looks correct to me now, but let me know if there's still an issue
