### ISSUE TITLE
transform.colorTransform doesn't work at all in windows

### ISSUE THREAD

**Issue by Knight52** [openfl/openfl#1550]
So, I'm developing a game for windows platform. I have a type of button that respond to player's cursor by making it brighter/darker, and I achieved that using transform.colorTransform.

I don't know which version it was, but it worked before upgrading to 4.9.2. Then it stopped working. Along with ColorMatrixFilter. I didn't use ColorMatrixFilter prior to the update, but it doesn't work when I try to use it.

No errors, no message box, no crash, nothing.

If anyone's got a workaround for this, that would be great too

`
Here's the code, from empty project:

	class Main extends Sprite 
	{
		public function new() 
		{
			super();
		
			var shape:Shape = new Shape();
			addChild(shape);
			shape.graphics.beginFill(0x00ff00);
			shape.graphics.drawRect(0, 0, 100, 100);
			shape.graphics.endFill();
			shape.transform.colorTransform = new ColorTransform(1, 1, 1, 1, 255, 0, 0);
		}

	}
`

**Comment by jgranick** [comment]
You can read more about this here:

https://github.com/openfl/openfl/issues/1403

There's a workaround by using `BitmapData`, you can do something like this:

```haxe
var shape = new Shape ();
shape.graphics.beginFill (0x00ff00);
shape.graphics.drawRect (0, 0, 100, 100);
var bitmapData = new BitmapData (100, 100);
bitmapData.draw (shape);
bitmapData.colorTransform (bitmapData.rect, new ColorTransform (1, 1, 1, 1, 255, 0, 0));
var bitmap = new Bitmap (bitmapData);
addChild (bitmap);
```

There is a "feature/color-transform" branch open on OpenFL which may have `ColorTransform` working for OpenGL, it is missing support for Cairo/HTML5 canvas, as well as some object types.

**Comment by Knight52** [comment]
I see. Thanks for the workaround. It's not perfect, but it'll do.
