### ISSUE TITLE
MovieClip HTML5 frame labels not loading

### ISSUE THREAD

**Issue by KnightMearh** [openfl/openfl#1553]
In the HTML5 target, a Movie Clip's frame labels list is empty. I have a MovieClip that has a main timeline with frame labels:

```
var future = AssetLibrary.loadFromFile ("myswf.bundle");
future.onComplete (library_onComplete);

//function library_onComplete
var clip = library.getMovieClip ("");
addChild (clip);
clip.gotoAndStop( "SomeFrameLabel" );
```

Upon tracing out clip information, `currentFrameLabel`, and `currentLabel` are null and `currentLabels` is empty []. `currentFrame` seems to accurately report the frame number. The frame label information seems to be contained in `swflite.dat` file, but perhaps not processed into the array of `FrameLabel`. Other than this, the logic looks like it should work at first glance.

target: HTML5
openfl: 4.9.2
lime: 4.0.3

**Comment by jgranick** [comment]
This also appears to be working, I updated my sample project from https://github.com/openfl/openfl/issues/1552 like this:

```haxe
var clip = library.getMovieClip ("");
		
		trace (clip.currentFrameLabel);
		trace (clip.currentLabel);
		trace (clip.currentLabels);
		
		addChild (clip);
		clip.gotoAndStop( "SomeLabel" );
		
		trace (clip.currentFrameLabel);
		trace (clip.currentLabel);
		trace (clip.currentLabels);
		
		clip.stop();
```

It's behaving as I would expect 😕
