### ISSUE TITLE
FileReference HTML5 target

### ISSUE THREAD

**Issue by varadig** [openfl/openfl#1554]
Hi, I read here the FileReference API is crossplatform(Available on all platform):
http://api.openfl.org/openfl/net/FileReference.html

but if I target OpenFL to HTML5, the dialog isn't appeared

here is a little sample what I tried:

```
package;


import openfl.events.MouseEvent;
import openfl.net.FileReference;
import openfl.display.Sprite;


class Main extends Sprite {


    public function new() {

        super();
        this.stage.addEventListener(MouseEvent.CLICK, this.onMouseClick);
    }

    private function onMouseClick(event:MouseEvent):Void {
        js.Browser.console.log("clicked");
        var reference:FileReference = new FileReference();
        reference.browse();
    }
}



```

**Comment by jgranick** [comment]
Under the hood, `openfl.net.FileReference` uses `lime.ui.FileDialog`, which is only implemented for desktop platforms at the moment.

Extending support for `FileDialog` to other environments (such as HTML5) would be awesome, I'm sorry this isn't available currently

**Comment by varadig** [comment]
Hmmm this is strange, because the in the API reference contain lime.FileDialog is Available on all platform. ;( 
http://api.openfl.org/lime/ui/FileDialog.html

Maybe the API reference is need to change if this is not working with html5 target

**Comment by jgranick** [comment]
The documentation library used for our documentation only checks if the class is present. In order to make it easier to cross-compile code, we usually avoid making classes available only on certain platforms. That way, if you have an `import lime.ui.FileDialog` it doesn't break all your code.

I'm sorry this makes it harder to understand the current status of support, though. If we have HTML5 dialog code, I would be glad to see it added. I've opened a new enhancement here:

https://github.com/openfl/lime/issues/963

**Comment by varadig** [comment]
I found a "hacked" way, maybe it's help for implement html5target  FileReference :)

```
package ;
import js.Browser;
import openfl.events.MouseEvent;
import openfl.display.Sprite;
class Program extends Sprite {
    public function new() {
        super();
        var button:Sprite = new Sprite();

        button.graphics.beginFill(0xFF0000);
        button.graphics.drawRect(0, 0, 200, 100);
        button.addEventListener(MouseEvent.CLICK, this.onButtonClicked);
        this.addChild(button);
    }

    private function onButtonClicked(event:MouseEvent):Void {
        var files = Browser.document.createInputElement();
        files.hidden = true;
        files.type = 'file';
        files.multiple = true;
        files.draggable = false;
        Browser.document.body.appendChild(files);
        var evt = Browser.document.createEvent("MouseEvents");
        evt.initEvent("click", true, true);
        files.dispatchEvent(evt);
        files.onchange = function() {
            Browser.document.body.removeChild(files);
        }
    }
}

```

**Comment by Snky** [comment]
@varadig does your hackish way produce a dialog, and a working method to save files? Wondering if you could clarify/provide a screenshot of your results

**Comment by RblSb** [comment]
@Snky Maybe you will find this useful
https://gist.github.com/RblSb/89ddad18453ffb6c7ba007381cc00b58
