### ISSUE TITLE
StageScaleModes

### ISSUE THREAD

**Issue by nerik** [openfl/openfl#156]
I'm updating an old NME project to OpenFL. It looks like stage scaling modes other than NO_SCALE cause some issues or at least behave differently.

The old behaviour was : specify a fixed resolution (eg 768 x 1024), the app will be automatically scaled (to retina resolutions for example), when using StageScaleMode.SHOW_ALL.

Now when I used any other mode than NO_SCALE, in a fresh project, all I got is a flashing blank screen.

Haxelib output:
nme: [4.0.2]
openfl: 1.0.4 1.0.5 1.0.6 [1.1.0]
openfl-compatibility: [1.0.1]
openfl-html5: 1.0.3 1.0.4 [1.0.5]
openfl-native: 1.0.4 1.0.6 1.0.7 1.0.8 [1.1.3]
openfl-nme-compatibility: [1.0.2]
openfl-samples: 1.0.0 1.0.0-rc.3 [1.1.0]
openfl-tools: [1.0.10] 1.0.8 1.0.9

**Comment by jgranick** [comment]
The current behavior is to use the full screen size if your window size (default for mobile) is 0 width and 0 height. Otherwise, it attempts to letterbox and scale your application automatically
