### ISSUE TITLE
String.create ocaml error (WebGL)

### ISSUE THREAD

**Issue by sbijoshj** [openfl/openfl#1561]
Running a project using openfl 5.0.0 (bug seems to have been introduced in this commit: eafae05abef0a31842740e1b27ad0163639cf28c) and lime 4.0.3 on a webgl project results in this error:
```
$ haxelib run openfl build -debug html5

Invalid_argument("String.create")
```

Our workaround is to roll back to lime 4.0.2 or less, but perhaps the newest develop on both openfl and lime would work as well?

**Comment by sbijoshj** [comment]
Related info:
https://github.com/HaxeFoundation/haxe/issues/6238#issuecomment-299545125

Seems like just adding "import lime.graphics.opengl.WebGLContext;" to BitmapData causes this error, when used with lime `4.0.3`.

**Comment by jgranick** [comment]
What version of Haxe is this? It works here, but perhaps I'm using a different version

Thank you :smile:

**Comment by sbijoshj** [comment]
Happens on 3.4.0 and 3.4.2 as far as we can tell.

**Comment by jgranick** [comment]
Strange, I'm running Haxe 3.4.2 (Linux) and it's working properly here.

Does this occur with any of the OpenFL samples, such as PiratePig? Does this occur with the standard OpenFL and Lime haxelib releases?

**Comment by sbijoshj** [comment]
Hmm strange I'm not able to repro any more. 4.0.3 with that commit in openfl, or newest openfl, all seem to work for our project and for PiratePig.
Closing, sorry about that. Hopefully the notes about changing versions are useful for others that run into this.

**Comment by sbijoshj** [comment]
As a new comment this error reappeared for us when our output js file exceeded 16 MB. Apparently somewhere that is a limit you can't go over for a single string:
`OCaml maximum string length in 32 bits which is quite low (~16MB)`
So you may have to repackage your output or otherwise reduce that string size, whatever it is for you (would be nice if it told you which string).

**Comment by mastef** [comment]
Just adding a comment for anybody finding this issue: Updating your haxe to a 64bit build should solve this. Issue should come up when your built .js file exceeds 16MB and hits the 32bit limit for String length
