### ISSUE TITLE
Embed asset for preloader broken on html5

### ISSUE THREAD

**Issue by miltoncandelero** [openfl/openfl#1568]
Hello everyone.

I updated openfl and now its failing to compile my code to HTML5 targets and tells me that a line in my preloader has "Too many arguments".

This is the line in question

`@:bitmap("assets/preloader/logo.png") class Splash extends BitmapData { }`

I am bound to think that this is an openfl issue since attempting to compile it with openfl 4,8,1 works and with the new openfl 5 it doesn't.

Thank you for your time!

**Comment by jgranick** [comment]
This appears to be working in our current development builds, I'll try and speed up the next release, and hopefully that should resolve your problem :grin:
