### ISSUE TITLE
OpenGLView is deprecated

### ISSUE THREAD

**Issue by Beeblerox** [openfl/openfl#1569]
Hello!
After updating to latest openfl i've found that `OpenGLView` is deprecated now.
I assume that this class will be removed soon, so my question is: what is recommended way for having your own custom class with its own opengl logic?
I assume that new correct way is to extend `DisplayObject` and override its `__renderGL()` method. Is it right?

And by the way, deprecation of this class will break HaxePunk engine which is using it for rendering all of the game objects. @HaxePunk team will have to add some other solution to work with OpenFl, and they are also using `OpenGLView` to work with NME. So they have to have and support 2 different renderers for both frameworks (but these renderers could still share some common logic).

**Comment by Beeblerox** [comment]
nevermind, i found this: https://github.com/openfl/openfl/blob/feature/native-render/openfl/display/NativeSprite.hx
So closing this issue.

**Comment by jgranick** [comment]
This was intended to be reverted for the short-term, before we have an official replacement:

https://github.com/openfl/openfl/commit/fd76cbee7dc81c8fc1d22325a30beefeaf4cd6b7

`openfl.gl.*` and `openfl.utils.ArrayBuffer` (etc) are obviously supported in the Lime API. I'm interested in an alternative to both `OpenGLView` and `DOMSprite` that is compatible with multiple renderers, but exposes less of OpenFL's internals, but I'm not sure if we can come up with a good balance that has enough power and flexibility, without exposing internal renderer methods.

The "feature/native-render" branch is one attempt at that, but I'm still unsure. Naming is hard, API is hard 😉

**Comment by bendmorris** [comment]
Thanks for the mention @Beeblerox. @jgranick, please keep our use case in mind and make sure there's a full parity replacement when OpenGLView is removed. HaxePunk does support NME which uses OpenGLView so I'd like to be able to render without too much framework-specific code.

Whatever you do, please just keep us in the loop! I'd prefer not to wake up to HaxePunk being totally broken one morning :smile:
