### ISSUE TITLE
blurry text under -Ddom caused by renderSession.roundPixels == false

### ISSUE THREAD

**Issue by chatziko** [openfl/openfl#1570]
Using -Ddom I very often get blurry text in Chrome (first screenshot below). After some digging I found that this is caused by decimal pixel numbers in the CSS ```transform: matrix3d(...)``` used for positioning elements.

If I uncomment the following line in ```DOMRenderer.hx```:
```
//renderSession.roundPixels = true;
```
the problem goes away (second screenshot below).

Is there any reason why this line is commented out?

Screenshot with ```roundPixes = false```:
![blurry](https://cloud.githubusercontent.com/assets/362089/26370261/8eeef72e-3ff7-11e7-864b-a8aa798348fb.png)

Screenshot with ```roundPixes = true```:
![good](https://cloud.githubusercontent.com/assets/362089/26370260/8eea31bc-3ff7-11e7-94b6-614d432b9193.png)

**Comment by jgranick** [comment]
It used to be enabled, but then we got reports like:

http://community.openfl.org/t/html5-circle-looks-horrible-when-rotate/9097/2
http://community.openfl.org/t/pixelsnapping-problem-in-html5/1271/20

I'm not sure if there's a better compromise we can do

**Comment by chatziko** [comment]
So I created a [simple project](https://github.com/openfl/openfl/files/1025919/test.tar.gz) demonstrating both issues related to roundPixels (mine and the one mentioned in those posts). Here's what my tests show:

* Issue 1: if ```roundPixels = true``` then ```Bitmap``` rotations look "shaky". This happens for all ```webgl, canvas, dom```.
* Issue 2: if ```roundPixels = false``` then TextFields with fractional coordinates look blurry in Chrome. This happens only for ```dom```.

So I guess a good compromise is to have ```roundPixels = false``` by default, and only use ```true``` for TextFields under ```-Ddom```.

#1571 implements this (not sure if it's the best way to do it, but it looks reasonably clean). With this fix both the text and the animation in my test project look good.

**Comment by chatziko** [comment]
Fixed by 4c71e55, so closing.
