### ISSUE TITLE
error with DisplayingABitmap on android

### ISSUE THREAD

**Issue by lalop** [openfl/openfl#1572]
I just come to discover openfl, I wanted to give it a try so I donwload and install it as described here http://www.openfl.org/learn/docs/getting-started/

I run `openfl setup android` and `openfl test android` but I get an error 

```
Creating /.../DisplayingABitmap/Export/android/release/obj/obj/android-v7/__pch/haxe/hxcpp.h.gch...
sh: /.../android-snk-macosx//toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-g++: Permission denied
Error: Could not create PCH
```

So I made `arm-linux-androideabi-g++` executable and retry but I get this new error 

```
Creating /.../DisplayingABitmap/Export/android/release/obj/obj/android-v7/__pch/haxe/hxcpp.h.gch...
arm-linux-androideabi-g++: error trying to exec 'cc1plus': execvp: No such file or directory
Error: Could not create PCH
```

**Comment by jgranick** [comment]
What version of the Android NDK do you have installed?

What version of Haxe and HXCPP?

Thanks!

**Comment by lalop** [comment]
I have 
have 3.4.2 
haxecpp 3.4.64
and android-ndk-r11c-darwin-x86_64

**Comment by lalop** [comment]
I think this is more an issue with lime than openfl, isn't it ?

**Comment by lalop** [comment]
I just come to manually download the last android ndk and all is working fine

**Comment by jgranick** [comment]
Strange, I guess we'll have to re-evaluate the `setup android` command

**Comment by lalop** [comment]
I think a part of the issue come from this https://github.com/openfl/lime/blob/f4d1df57ee74c99de20ae2ac67bf3ab046d5566c/tools/utils/PlatformSetup.hx#L241
All the files are unzip as readonly whatever are their permission in the zip
