### ISSUE TITLE
[Feature Request] MovieClip.__fromMovieClip(mc:MovieClip)

### ISSUE THREAD

**Issue by Alex-0000** [openfl/openfl#1580]
[Feature Request] MovieClip.__fromMovieClip(mc:MovieClip)

MovieClip already has a method __fromSymbol but this takes a SWFLite and a SpriteSymbol and is used with auto-generated classes from swfs:

`var swfLite = SWFLite.instances.get ("lib/library/library.dat");
var symbol = swfLite.symbols.get (164);	
__fromSymbol (swfLite, cast symbol);`

When I generate these classes myself and use Assets.getMovieClip, it would be useful if I can directly put this MovieClip into the MovieClip the class I am making is extending. Otherwise I'm only extending MovieClip for display object container access and for it to hint what its child is. (Right now I add the MovieClip I get from Assets as a child)

**Comment by jgranick** [comment]
I think this is possible now if you use the `generate="true"` option. For example, create a copy of the "NyanCat" sample:

```bash
openfl create NyanCat
```

...then edit the "project.xml" file, and add `generate="true"` to the `<library />` tag so it says `<library path="Assets/library.swf" preload="true" generate="true" />`

Then you should be able to `new NyanCatAnimation ()` to create a copy of the Nyan Cat animation. Similarly, you should be able to extend it with a new class:

```haxe
package;


class MyClass extends NyanCatAnimation {
	
	
	public function new () {
		
		super ();
		
		trace (totalFrames);
		
	}
	
	
}
```

This should display the animation, and trace 24:

```haxe
addChild (new MyClass ());
```
