### ISSUE TITLE
position flickers when accessing bounds onEnterFrame (html5)

### ISSUE THREAD

**Issue by kasparsj** [openfl/openfl#1582]
This is how to reproduce it with NyanCat, positioning it on `50,50`, and then tracing `height` on `ENTER_FRAME`:
```
public function new () {

            super ();

            var cat = Assets.getMovieClip ("library:NyanCatAnimation");
            cat.x = 50;
            cat.y = 50;
            addChild (cat);

            addEventListener(Event.ENTER_FRAME, function(event:Event) { trace(cat.height); });

}
```
Then:
`openfl test html5`
And the cat movie clip will flicker, between 0,0 and 50,50.

**Comment by kasparsj** [comment]
This is since 5.0.0

**Comment by jgranick** [comment]
Thank you for the simple test case. Previously, we did an update of all the matrix transforms immediately before rendering, but adding `cacheAsBitmap` has led to (surprise!) more caching. Please let me know if you experience anything else like this!
