### ISSUE TITLE
Very slow compile speeds on Windows using Visual Studio Express 2010

### ISSUE THREAD

**Issue by TerryCavanagh** [openfl/openfl#1583]
I recently did a reinstall of my laptop, and found that making a clean release build on windows of my current project took around 25 minutes (not a typo!). I asked in the slack, and was told to try using Visual Studio Express 2013 instead, which I did! A clean release build of my game went back down to around 3 minutes.

The issue here is that `openfl setup windows` currently installs 2010, which is clearly much slower than 2013. Maybe the script could be updated?

If that's not possible, perhaps <a href="http://www.openfl.org/lime/docs/advanced-setup/windows/">this page</a> could be updated to tell people about this problem, and suggest using 2013 instead?

**Comment by MSGhero** [comment]
When you downloaded VSE13, was it through Microsoft's (free) windows dev subscription page? '10 was only about 200mb, but '13 is seeming like a big download, plus it took a while to find.

"Visual Studio Express 2013 for Windows with Update 5"

**Comment by TerryCavanagh** [comment]
I honestly don't remember where I downloaded it from when I did it, but after looking around a bit this seems to be a link to the webinstaller, and it's on a microsoft site:

http://download.microsoft.com/download/7/2/E/72E0F986-D247-4289-B9DC-C4FB07374894/wdexpress_full.exe

**Comment by TerryCavanagh** [comment]
(also found this: http://download.microsoft.com/download/7/2/E/72E0F986-D247-4289-B9DC-C4FB07374894/wdexpress_full.exe)

**Comment by MSGhero** [comment]
@Beeblerox yeah I installed the big one. That version shouldn't be in the `openfl setup windows` script though because it took a long time to install for me.

**Comment by TerryCavanagh** [comment]
The web download version is only a megabyte! I don't think you need the entire 5gb iso.

I'm not sure which version should be installed by default, but SOMETHING should probably tell you that there's a 10x difference in speed between the two versions - either a help page, the setup script, or something else.

**Comment by MSGhero** [comment]
Oh for sure. Maybe without the 5 updates, it's much leaner. I doubt the `setup` command includes any updates in the download.

**Comment by MSGhero** [comment]
Oh man, "VSE 2013 for Windows" was the wrong download, I couldn't compile at all. "VSE 2013 for Windows **Desktop**" is correct, and that's what @TerryCavanagh 's link is for.

The install link is within Lime. It might just be a matter of replacing this link with yours: https://github.com/openfl/lime/blob/develop/tools/utils/PlatformSetup.hx#L62 It wasn't a fast download and install like VSE 10 is, but cpp compiles not taking a half hour is pretty good.

**Comment by jgranick** [comment]
I believe Visual Studio 2017 is supported in development builds of HXCPP, but I believe I use VS 2015 Community Edition personally
