### ISSUE TITLE
HL Target Support?

### ISSUE THREAD

**Issue by ashes999** [openfl/openfl#1588]
Hi,

Are there any plans to support the new(ish) HL target with Lime?

From what I can gather, this is an improved replacement for Neko, which is still much faster than building against HTML5.

**Comment by RblSb** [comment]
I think this is equivalent to adding a new platform by the level of work and now it is worth thinking about improving existing things.

**Comment by jgranick** [comment]
The first step is to learn more about the way that HashLink handles native C bindings.

https://github.com/HaxeFoundation/hashlink/blob/master/libs/sqlite/sqlite.c#L85

We use "CFFI Prime", which is compatible with Neko CFFI, older HXCPP CFFI and newer HXCPP high-performance bindings. Ideally, we will want to find a way to either create separate bindings for HL and for other runtimes, or create a macro that is compatible with all three binding styles.

If we can determine this for HL, then we should be able to then approach HL as we do Neko, where we use a precompiled Lime binary, but compile the Haxe code to HL and run in a VM at runtime. I'm very open to this, if we can sort out the more technical bit (above) first :smile:

**Comment by jgranick** [comment]
I'm going to close this in favor of tracking in the Lime project, here :smile:

https://github.com/openfl/lime/issues/979
