### ISSUE TITLE
OpenFL Breaks with thx.http

### ISSUE THREAD

**Issue by ashes999** [openfl/openfl#1590]
Hi,

I'm working on a small [analytics server/client solution](https://github.com/ashes999/proton-analytics-v4). For the client, I'm using Haxe. I need OpenFL because I need to use `SharedObject` to persist a GUID between invocations of the client.

Starting with a dummy/template project, I added a reference to [thx.http](https://github.com/fponticelli/thx.http). As soon as I add `using thx.http.Request` to my client, Neko ceases to work and crashes on startup with this error:

> Title: Entry Point Not Found
> The procedure entry point neko_kind_lookup could not be located in the dynamic link library D:\HaxeToolkit\neko\ssl.ndll.

`ssl.ndll` exists and is fine as far as I can tell. I went so far as to uninstall and reinstall Haxe 3.4.2 and install the latest Lime/OpenFL/thx.http to make sure.

Any idea what the problem might be or how I can fix this?

CC @fponticelli

**Comment by ashes999** [comment]
Sorry, it looks like it's environmental. I'm going to close this.

On my first Windows machine, with Haxe 3.4.2 and Neko 2.1.0, this breaks. On my second Windows machine, with Haxe 3.4.1 and Neko 2.1.0, this works. I don't know why. It's clearly not code-related though.

**Comment by ashes999** [comment]
For posterity, this is an issue with neko/lime. Lime ships with copies of `neko.dll` and a few `.ndll` files, which look to be a different version than the Neko 2.1 files. Replacing these with the Neko 2.1 binaries resolved the problem.  

(The copies live under `<haxelib path>\lime\2,9,1\legacy\templates\neko\ndll\windows` and similarly without `legacy` in the path.)

**Comment by jgranick** [comment]
Current Lime no longer ships with Neko binaries, in order to avoid Neko 2.0 / Neko 2.1 incompatibility :smile:

**Comment by ashes999** [comment]
@jgranick unfortunately, it looks like Haxeflixel is still using lime 2.9.1. I guess I'm stuck until they upgrade.
