### ISSUE TITLE
Reuse lineStyle break mouse events

### ISSUE THREAD

**Issue by RblSb** [openfl/openfl#1591]
Example:
https://gist.github.com/RblSb/4e3ae8bb88554ba9201135e82b631d9f

On the second square, onOver / mouseMove works only when you point to a cross in the corner of this square. On 1 and 3 square everything is fine.
Problem on all platforms except flash.
More detailed description: #1713

**Comment by jgranick** [comment]
This seems like a related sample that also does not work during hit testing:

```haxe
package;


import openfl.display.Sprite;


class Main extends Sprite {
	
	
	public function new () {
		
		super ();
		
		var switchBtn = new Sprite();
		switchBtn.graphics.beginFill(0x000000, 0.7);
		switchBtn.graphics.moveTo(0 , 0);
		switchBtn.graphics.lineTo(45, 0);
		switchBtn.graphics.curveTo(50, 0, 50,  5);
		switchBtn.graphics.lineTo(50, 30);
		switchBtn.graphics.lineStyle(1, 0xffffff);
		switchBtn.graphics.lineTo(0, 30);
		switchBtn.graphics.lineTo(0, 0);
		switchBtn.graphics.endFill();
		addChild (switchBtn);
		
		switchBtn.buttonMode = true;
		switchBtn.addEventListener ("click", function (_) { trace ("click"); });
		
	}
	
	
}
```

http://community.openfl.org/t/html5-webgl-lime-5-4-0-openfl-6-1-0-shapes-not-getting-mouseevents/9525
