### ISSUE TITLE
Slow asset embedding on flash target

### ISSUE THREAD

**Issue by starry-abyss** [openfl/openfl#1594]
The results are from empty test project, where I use copies of flashplayer_23_sa_debug.exe (15 Mb) to simulate asset folder size.

Assets are embedded with <assets path="assets" /> in project.xml.
I build with HaxeDevelop 5.2.0.3 in debug mode, Haxe 3.4.2.

debug.hxml during building is 
```
-main ApplicationMain 
--macro openfl._internal.utils.ExtraParams.include()
-cp D:/build/HaxeToolkit/haxe/lib/openfl/5,1,2
-D openfl=5.1.2
--macro lime.Lib.extraParams()
-cp D:/build/HaxeToolkit/haxe/lib/lime/5,0,3
-D lime=5.0.3
-cp D:/build/HaxeToolkit/haxe/lib/actuate/1,8,7
-D actuate=1.8.7
-cp src
-cp D:\build\HaxeToolkit\haxe\lib\openfl/5,1,2/externs/core/flash
-cp D:\build\HaxeToolkit\haxe\lib\openfl/5,1,2/externs/core/openfl
-D native-trace
-D tools=5.0.3
-D flash-use-stage
-D no-compilation
-D openfl-flash
-D fdb
-D web
--times
-swf-lib bin/flash/debug/obj/assets.swf
-swf-version 17
-swf bin/flash/debug/bin/runner.swf
-swf-header 800:480:60:000000
-cp bin/flash/debug/haxe
-debug
```

Times from pressing "build" to run, including the phase of lime update, are (for different 'assets' sizes):
60 Mb - 14 sec
105 Mb - 23 sec
150 Mb - 31 sec
195 Mb - 42 sec
240 Mb - 51 sec

Some more details about the last case:
```
240 Mb (51 sec per build), --times:
name     | time(s) |   % |     # | info
----------------------------------
analyzer |   0.129 |   1 | 44838 | 
filters  |   0.119 |   1 |     1 | 
generate |   0.096 |   0 |     1 | 
  swf    |   0.096 |   0 |     1 | 
macro    |   0.128 |   1 |    92 | 
other    |   0.011 |   0 |     1 | 
parsing  |   0.099 |   0 |   563 | 
read     |   1.532 |   7 |     2 | 
  swf    |   1.532 |   7 |     2 | 
typing   |   0.306 |   1 |   147 | 
write    |  20.387 |  89 |     1 | 
  swf    |  20.387 |  89 |     1 | 
----------------------------------
total    |  22.807 | 100 |     0 | 


240 Mb (4 sec per build), embed = false, --times:
name     | time(s) |   % |     # | info
----------------------------------
analyzer |   0.160 |  15 | 44685 | 
filters  |   0.129 |  12 |     1 | 
generate |   0.122 |  12 |     1 | 
  swf    |   0.122 |  12 |     1 | 
macro    |   0.135 |  13 |    92 | 
other    |   0.012 |   1 |     1 | 
parsing  |   0.163 |  16 |   563 | 
read     |   0.002 |   0 |     2 | 
  swf    |   0.002 |   0 |     2 | 
typing   |   0.289 |  28 |   147 | 
write    |   0.039 |   4 |     1 | 
  swf    |   0.039 |   4 |     1 | 
----------------------------------
total    |   1.051 | 100 |     0 | 
```

**Comment by jgranick** [comment]
This is caused by behavior in the Haxe compiler. I don't know if it can be sped up? We generate the `-swf-lib` assets SWF, but then it's the Haxe compiler that does the final link with your source code.

If you do not set `embed="true"` on your assets, you can load them at runtime using `Assets.loadBitmapData` (and other `load` methods) or use a custom asset library, to load them up. I outline how that approach can work, here: http://community.openfl.org/t/preloader-now-that-nmepreloader-is-depreciated/8437/65

If you definitely want it in the same SWF, perhaps you could report the issue on https://github.com/haxefoundation/haxe, and there might be something they can do speed up the compiler?

**Comment by starry-abyss** [comment]
Thank you for the tip, but how can one substitute Assets.getBitmapData() with Assets.loadBitmapData() to behave the same way? I.e. wait for it to complete in the same place where called. Apparently ```while (!future.isCompleted) {}``` doesn't work
