### ISSUE TITLE
adding a vector line through openFL.display.graphics doesn't update sprite width and height correctly

### ISSUE THREAD

**Issue by kevansevans** [openfl/openfl#1595]
https://github.com/kevansevans/openFL-Lime-sprite-issue

Reporting this to both Lime and OpenFL.

I noticed this bug a few days ago when starting a project from scratch. I needed my program to get the width and height of a sprite based on the lines that the player has drawn on the sprite. When I first got it working, adding any line whats so ever would needlessly increase the width and height of the sprite, even if the line added did not extend past the width and height. In the example I provided, it will occasionally reflect the problem I was illustrating, and any line that extends past the visual boundaries, the width and height of the canvas sprite I defined never appears to be adjusted correctly.

Video for the lazy: https://youtu.be/de8LqRKSLIo

**Comment by jgranick** [comment]
The behavior on OpenFL 5.1.3 and Lime 5.1.0 (just released) appears to be consistent between the desktop and Flash Player builds. I modified your code a little to include the `(x, y)` coordinates for the bounds, to make it a little clearer visually:

```haxe
package;

import openfl.display.Sprite;
import openfl.Lib;
import openfl.events.MouseEvent;

/**
 * ...
 * @author Kaelan Evans
 */
class Main extends Sprite 
{
	var canvas:Sprite;
	var x1:Float = 0;
	var x2:Float = 0;
	var y1:Float = 0;
	var y2:Float = 0;

	public function new() 
	{
		super();
		
		this.canvas = new Sprite();
		this.addChild(this.canvas);
		this.canvas.graphics.lineStyle(2, 0xCCCCCC, 1);
		
		this.stage.addEventListener(MouseEvent.MOUSE_DOWN, this.start_line);
	}
	
	private function start_line(e:MouseEvent):Void 
	{
		stage.addEventListener(MouseEvent.MOUSE_UP, this.add_line);
		this.x1 = this.canvas.mouseX;
		this.y1 = this.canvas.mouseY;
	}
	
	private function add_line(e:MouseEvent):Void 
	{
		this.removeEventListener(MouseEvent.MOUSE_UP, this.add_line);
		this.x2 = this.canvas.mouseX;
		this.y2 = this.canvas.mouseY;
		
		this.canvas.graphics.moveTo(x1, y1);
		this.canvas.graphics.lineTo(x2, y2);
		
		this.display_size();
	}
	
	function display_size() 
	{
		var canWidth = this.canvas.width;
		var canHeight = this.canvas.height;
		var bounds = this.canvas.getBounds(this);
		
		var x = bounds.x;
		var y = bounds.y;
		
		this.graphics.clear();
		this.graphics.lineStyle(2, 0xFFFFFF, 1);
		this.graphics.moveTo(x, y);
		this.graphics.lineTo(x + canWidth, y);
		this.graphics.lineTo(x + canWidth, y + canHeight);
		this.graphics.lineTo(x, y + canHeight);
		this.graphics.lineTo(x, y);
		
		trace(this.x1, this.y1, this.x2, this.y2, this.canvas.width, this.canvas.height, canHeight, canWidth);
	}

}
```

Let me know if you still have problems :smile:
