### ISSUE TITLE
Accessing SharedObject Data by Field Name

### ISSUE THREAD

**Issue by ashes999** [openfl/openfl#1596]
TL;DR: I'm trying to write a wrapper around `SharedObject` to expose a dictionary-like set of methods (`has`, `get`, and `set`). This is problematic, because the usual way to use an instance is `SharedObject.getLocal().data.foo`. 

This works, because `data` is dynamic.

Is there any way to achieve what I want, or is this just plain impossible right now?

[This post](https://stackoverflow.com/questions/15530645/how-can-i-iterate-dynamic-object-in-haxe) suggests how I can read fields from `dynamic` by name, but not how I can write them.

**Comment by MSGhero** [comment]
You could probably find a way to integrate this into what you're trying to do:
```haxe
var obj:haxe.DynamicAccess<Dynamic> = SharedObject.getLocal().data;
if (!obj.has("foo")) obj.set("foo", 25);
```

**Comment by ashes999** [comment]
@MSGhero thanks for this, it worked as expected. Sorry, this ended up being more of a "haxe" question than an OpenFL question.
