### ISSUE TITLE
Game Shutdown Event

### ISSUE THREAD

**Issue by ashes999** [openfl/openfl#1612]
Hi,

I'm working on a HaxeFlixel game and I need analytics integration. I need a consistent way (across HTML5 and desktop targets) to execute some of my code when the game terminates.

I opened a corresponding event on HaxeFlixel [here](https://github.com/HaxeFlixel/flixel/issues/2081), but it doesn't look like they have a way to do this; there is an event handler for mobile to capture the app start/end/suspend/resume, but I don't think it covers HTML5, and I know it doesn't cover Neko (and presumably desktop targets).

Is there a way to do this using lime or OpenFL?

**Comment by jgranick** [comment]
Let me move this to the [forums](http://community.openfl.org/t/game-shutdown-event/9223) 😄
