### ISSUE TITLE
URLLoader in OpenFL 5.1.4 Compile Issue

### ISSUE THREAD

**Issue by francoisvn** [openfl/openfl#1617]
Just tried upgrading to OpenFL 5.1.4 and Lime 5.2.0, but got the following error, which seems to be related to using `URLLoader` (I believe this is from our usage of `URLRequest`):

```
/usr/lib/haxe/lib/openfl/5,1,4/openfl/net/URLLoader.hx:112: characters 18-47 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
/usr/lib/haxe/lib/lime/5,2,0/lime/system/ThreadPool.hx:25: characters 21-48 : Unknown<0> cannot be constructed
```

AFAICT the 2nd error isn't important, but I include it for completeness sake. Should be an easy fix.

**Comment by jgranick** [comment]
Could you give this patch a try, and see if it helps?

https://github.com/openfl/openfl/commit/ebd0c53601d8cef6c8f84dfe9170ace7aa4c6392

Thank you :smile:

**Comment by francoisvn** [comment]
That seems to work, so closing this

**Comment by dzw** [comment]
encouting the same problem
![default](https://user-images.githubusercontent.com/1837380/37158628-cf704664-2326-11e8-9b53-3949825ffe14.png)

**Comment by jgranick** [comment]
@dzw Are you using haxelib, or did you build from source?

What version of Haxe are you using, what version of Windows? Thanks :smile:
