### ISSUE TITLE
SharedObject.getLocal Throws on Android

### ISSUE THREAD

**Issue by ashes999** [openfl/openfl#1629]
I'm using SharedObject to store a simple text string (unique user GUID). It works fine on HTML5 and Flash. On Android, I get this error:

```
/system/bin/sh: can't create C:UsersUserNameAppDataLocalTemp/temp_2690476: No such file or directory
```

My code then proceeds down the path of "couldn't load the data so generate a new GUID."

What am I doing wrong?

---

Vitals:
- OpenFL 3.6.1 (c/o HaxeFlixel)
- Lime 2.9.1 (ditto)
- Android SDK 24.0.2
- Android SDK Platform-tools 20
- Android SDK Build-tools 23.0.1

---

Sample code (more or less what I'm actually doing):

```
private var storage:SharedObject = SharedObject.getLocal("persisted client data");
var obj:haxe.DynamicAccess<Dynamic> = storage.data;
if (obj.exists("playerId")) { ... }
else { obj.set("playerId", "guid string"); }
storage.flush();
```

I'm not sure what line actually fails, because there's no clear message or line number; just a failure before any of my `trace` statements.

**Comment by MSGhero** [comment]
I recommend testing this on dev openfl in a sample project, might have already been fixed.

**Comment by ashes999** [comment]
Sorry, I was reading the logs wrong. I thought this log message appeared every time, but it only appears the first time. The actual functionality seems to be correct and working as expected. (I added a ton of `trace` calls and figured this out.)
