### ISSUE TITLE
Sound loop count difference between CPP and HTML5 targets

### ISSUE THREAD

**Issue by zatarus** [openfl/openfl#1638]
Using `Lime 5.2.0` and `OpenFL 5.1.5`

`sound.play(0, 3);` plays `wav` file only twice in CPP (mac) and three times in HTML5.

Similar PR from past: https://github.com/openfl/openfl/pull/571

**Comment by jgranick** [comment]
Resolved, probably a long time ago. Thanks for reporting, and sorry for not closing this :smile:
