### ISSUE TITLE
TileArray breaks when setting an object's visibility to false

### ISSUE THREAD

**Issue by jaredsain** [openfl/openfl#1654]
Let's say I have a tilemap with 10 tiles in it, indexed from 0...9. If I set the visibility of the tile at index 1 to false, that tile and ALL tiles indexed after it will no longer display. It looks like the issue is in the TileArray class, in the __updateGLBuffer function.

You check the visibility in a loop that goes through every tile, and if visibility is set to false you continue the loop:

```
visible = this.visible;

if (!visible || alpha <= 0) {
					
	__skipTile (i, offset);
	continue;
}
```
The problem is you don't update the "position" variable when you continue, since it is incremented at the bottom of the for loop. That position variable is used in the "get_visible" function, but it stays stuck on the index of the initial tile that had its visibility set to false.

I fixed this by adding "position = i;" at the top of the loop, but not sure if that's the preferred solution.

**Comment by jgranick** [comment]
Thank you! Yeah, this is a silly mistake :sweat:

Thank you for your help :smile:
