### ISSUE TITLE
[TextField] html tags doesn't work properly (Bounty 100EUR)

### ISSUE THREAD

**Issue by loudoweb** [openfl/openfl#1657]
Haxe 3.4.2
Openfl 6.0.1
Lime 5.3.0

Here is a sample of code that only works perfectly on flash:

```
var texts:Array<String> = ["A<font color='#ff0000'>R</font>A",
					"B <font color='#ff0000'>R</font>B ",
					"C<font color='#ff0000'>R</font> C",
					"DD<font color='#ff0000'>R</font>D",
					"E<font color='#ff0000'>R</font>EE",
					"F<font color='#ff0000'>RRRR</font>F"];
		
		for (i in 0...texts.length)
		{
			var t:TextField = new TextField();
			t.htmlText = texts[i];
			addChild(t);
			t.y = i * 50;
		}
```
As you can see the only working field is `C<font color='#ff0000'>R</font> C` in html5 or neko. There is a space between the closing tag and the next character. In flash, all R character are red as expected.

I really want this feature fixed for html5. I offer a bounty of 100 EUR.

**Comment by Misiur** [comment]
I can help a little with investigation. `openfl._internal.text.HtmlParser#parse` returns correct values. The problem is somewhere [in here](https://github.com/openfl/openfl/blob/0dd135691f5eb57d8910c5aecbc989bda5ce5ce3/openfl/_internal/text/TextEngine.hx#L939-L1244). Mere 350 lines of synchronizing arrays magic (inline functions defined little earlier don't count). I'll drop traces everywhere, maybe I'll smoke the problem out

**Comment by Misiur** [comment]
Working on 
```
var texts:Array<String> = ["BA<font color='#ff0000'>R</font>B"];
```
I've cut out all unused parts in [this part](https://github.com/openfl/openfl/blob/0dd135691f5eb57d8910c5aecbc989bda5ce5ce3/openfl/_internal/text/TextEngine.hx#L939-L1244)

And arrived at this:
```
while (textIndex < maxLoops) {
    trace("Iteration", text, textIndex, breakIndex, spaceIndex, formatRange.end);
    if ((breakIndex > -1) && (spaceIndex == -1 || breakIndex < spaceIndex) && (formatRange.end >= breakIndex)) {
    } else if (formatRange.end >= spaceIndex && spaceIndex > -1 && textIndex < formatRange.end) {               
    } else {
        trace(text, formatRange);   
        if (textIndex > formatRange.end) {
        } else if (textIndex < formatRange.end || textIndex == text.length) {                   
            advances = getAdvances (text, textIndex, formatRange.end);
            widthValue = getAdvancesWidth (advances);
            
            layoutGroup.advances = getAdvances (text, textIndex, formatRange.end);
            layoutGroup.offsetX = offsetX;
            layoutGroup.ascent = ascent;
            layoutGroup.descent = descent;
            layoutGroup.leading = leading;
            layoutGroup.lineIndex = lineIndex;
            layoutGroup.offsetY = offsetY;
            layoutGroup.width = getAdvancesWidth (layoutGroup.advances);
            layoutGroup.height = heightValue;
                                    
            offsetX += widthValue;
            textIndex = formatRange.end;
            
        }
        
        nextFormatRange ();
        
    }
    
}
```

So, the issue is, if there are no spaces at all, `nextLayoutGroup` is never called. Adding it after `widthValue` in my snippet shows some progress:
![image](https://user-images.githubusercontent.com/752692/29006634-d4b1b45e-7af3-11e7-9aa4-06a7135a10c4.png)

I'll dig deeper now

**Comment by MSGhero** [comment]
@Misiur It's been a while, but see if the changes in #1186 do something for you. A lot of textfield stuff has been changed since then, so it's probably no longer a clean merge.

**Comment by Misiur** [comment]
Thank you MSGhero, I took a quick peek and maybe that will help me pinpoint this problem.

So I was wrong and removed important condition - there *is* `nextLayoutGroup` call there. However I'm on the verge of breakthrough @loudoweb try this:

```diff
diff --git a/openfl/_internal/text/TextEngine.hx b/openfl/_internal/text/TextEngine.hx
index fcf4be7..54b1d65 100644
--- a/openfl/_internal/text/TextEngine.hx
+++ b/openfl/_internal/text/TextEngine.hx
@@ -1203,15 +1203,17 @@ class TextEngine {
 					advances = getAdvances (text, textIndex, formatRange.end);
 					widthValue = getAdvancesWidth (advances);
 					
-					if (layoutGroup != null && layoutGroup.startIndex != layoutGroup.endIndex) {
+					nextLayoutGroup (textIndex, formatRange.end);
+					
+					// if (layoutGroup != null && layoutGroup.startIndex != layoutGroup.endIndex) {
 						
-						layoutGroup.advances = layoutGroup.advances.concat (advances);
-						layoutGroup.width += widthValue;
-						layoutGroup.endIndex = formatRange.end;
+					// 	layoutGroup.advances = layoutGroup.advances.concat (advances);
+					// 	layoutGroup.width += widthValue;
+					// 	layoutGroup.endIndex = formatRange.end;
+						
+					// } else {
 						
-					} else {
 						
-						nextLayoutGroup (textIndex, formatRange.end);
 						
 						layoutGroup.advances = getAdvances (text, textIndex, formatRange.end);
 						layoutGroup.offsetX = offsetX;
@@ -1223,7 +1225,7 @@ class TextEngine {
 						layoutGroup.width = getAdvancesWidth (layoutGroup.advances);
 						layoutGroup.height = heightValue;
 						
-					}
+					// }
 					
 					offsetX += widthValue;
 					textIndex = formatRange.end;
```

![image](https://user-images.githubusercontent.com/752692/29006928-914373f0-7af9-11e7-8541-02220d5d5126.png)

Forcing new layout group seems to be a hack that is working. I guess it's really bad idea, as it will force new LG even when it is not needed, but that's something for me anyway. I'll try digging some more

**Comment by Misiur** [comment]
All right, I think this is first real attempt: https://github.com/Misiur/openfl/commit/bb436514308145e1c26c58dfb5fd6d71c486cc17

**Comment by loudoweb** [comment]
Oh Great! Thank you! I'll try today.

**Comment by loudoweb** [comment]
In you current proposal, `B <font color='#ff0000'>R</font>B` is not working (because of the space before the font tag I guess) but in your previous attempt, everything seems to work.

**Comment by Misiur** [comment]
Oh, overfitted again

**Comment by loudoweb** [comment]
Here are some traces I've get when compiling with **-Dopenfl_trace_text_layout_groups** : 

**### Current OpenFL git:**
```
Main.hx:54: A<font color='#ff0000'>R</font>AAAAAA AAAA
TextEngine.hx:1350: LG,0,line:0,w:15.474609375,x:2,y:2,"AR",0,2
TextEngine.hx:1350: LG,0,line:0,w:82.8515625,x:17,y:2,"AAAAAA AAAA",2,13

Main.hx:54: B <font color='#ff0000'>R</font>BBBBBB BBB
TextEngine.hx:1350: LG,0,line:0,w:18.046875,x:2,y:2,"B R",0,3
TextEngine.hx:1350: LG,0,line:0,w:71.12109375,x:20,y:2,"BBBBBB BBB",3,13

```
So as you can see I have 2 TextLayoutGroups for each text instead of 3. It doesn't work.

**### Misiur/openfl@bb43651:**
```
Main.hx:54: A<font color='#ff0000'>R</font>AAAAAA AAAA
TextEngine.hx:1350: LG,0,line:0,w:15.474609375,x:2,y:2,"AR",0,2
TextEngine.hx:1350: LG,0,line:0,w:82.8515625,x:17,y:2,"AAAAAA AAAA",2,13
Main.hx:54: B <font color='#ff0000'>R</font>BBBBBB BBB
TextEngine.hx:1350: LG,0,line:0,w:18.046875,x:2,y:2,"B R",0,3
TextEngine.hx:1350: LG,0,line:0,w:71.12109375,x:20,y:2,"BBBBBB BBB",3,13
```
As you can see, it's pretty the same. While this proposal fixes `A<font color='#ff0000'>R</font>A`, it doesn't fix` A<font color='#ff0000'>R</font>AAAAAA AAAA` because there is **hasAnySpaces**.

**### https://github.com/openfl/openfl/issues/1657#issuecomment-320531875:**
Main.hx:54: A<font color='#ff0000'>R</font>AAAAAA AAAA
TextEngine.hx:1350: LG,0,line:0,w:7.986328125,x:2,y:2,"A",0,1
TextEngine.hx:1350: LG,0,line:0,w:7.48828125,x:9,y:2,"R",1,2
TextEngine.hx:1350: LG,0,line:0,w:82.8515625,x:17,y:2,"AAAAAA AAAA",2,13
TextEngine.hx:1350: LG,0,line:0,w:0,x:100,y:2,"",13,13
Main.hx:54: B <font color='#ff0000'>R</font>BBBBBB BBB
TextEngine.hx:1350: LG,0,line:0,w:10.55859375,x:2,y:2,"B ",0,2
TextEngine.hx:1350: LG,0,line:0,w:7.48828125,x:12,y:2,"R",2,3
TextEngine.hx:1350: LG,0,line:0,w:71.12109375,x:20,y:2,"BBBBBB BBB",3,13
TextEngine.hx:1350: LG,0,line:0,w:0,x:91,y:2,"",13,13

It seems that there is one useless LayoutGroup at the end but it works. When @Misiur said that was a bad idea to force nextLayoutGroup I was afraid of having one LayoutGroup per character but there is only one more. It's easy to fix: 
[Here ](https://github.com/openfl/openfl/blob/db111ee147f4dbdd0e882a07c781ba7650271ed3/openfl/_internal/text/TextEngine.hx#L1298)`} else if (textIndex < formatRange.end || textIndex == text.length - 1) {`
@MSGhero is `textIndex == text.length` is needed to `breakLongWords()` ? or can we go with `textIndex == text.length - 1` ?


There is also a little regression on selected text (when you select the text with your mouse, the width of the black 'selector' is (sometimes) not of the correct size, try with this one : `A<font color='#ff0000'>R</font>A`). But anyway, it's really minor, so who cares? :)

**Comment by MSGhero** [comment]
I'll have to check, but probably not. I believe it's there to handle trailing `\n` characters, but you might hit an infinite while loop or something without it.

**Comment by MSGhero** [comment]
@loudoweb yeah I don't actually know why that line is like that. If you set `text = "\n"`, that line causes there to be two layout groups. I don't know if that's intentional, since it was intended only for `multiline` input text before my PR.

I believe it should be `textIndex == text.length - 1`, based on limited testing. I'm not sure what the intent was otherwise.

**Comment by loudoweb** [comment]
Thanks for your help.

It comes from this https://github.com/openfl/openfl/commit/5abe59155abffd568cf2a93e4597e789c82e9f7a by @vizanto 

> Fix: cursor not visible on the last empty line
Before this patch when typing ENTER in a multiline
 TextField in HTML5 or Native target, the cursor
 disappeared. As soon as any non-space character
 was entered after, the cursor would appear again.

> This patch fixes it by ensuring a TextLayoutGroup
 is created for the last empty line.

Indeed I have tested and if we do `textIndex == text.length - 1` it removes the last LayoutGroups which is necessary for the new line caret for whatever reason. Anyway it doesn't seem a perfect solution, I've seen a bug where the caret is on the previous line instead of the new line, I'll open an other issue for this.

@Misiur you can make your PR from your [first try](https://github.com/openfl/openfl/issues/1657#issuecomment-320531875), I've tested and it's ok. I'll send you an email for your bounty. Thanks again.

**Comment by Misiur** [comment]
I still don't think that's a good idea, we don't know why it was there in first place. @jgranick we need you here. Put the bounty towards openfl, or someone who can fix it in nicer way =)

**Comment by MSGhero** [comment]
Try this:

```haxe
var tf = new TextField();
tf.text = "aaa";
tf.setTextFormat(new TextFormat("Arial", 32), 1, 2);
addChild(tf);

trace(tf.textHeight);
```
The middle "a" should be large, and `textHeight` should be its height. Without this fix, on Neko, the second "a" doesn't even change formats. With this fix, it shows up large, but the ascents are all off, and `textHeight` is still just the height of the final character or something.

So I think formats are incorrect in general, and HTML tags see the result of that. This is extremely easy to see with the above example but `text = "aaa\naaa", where the existing and this fix are both incorrect.

**Comment by MSGhero** [comment]
I got it working, I just need to unbreak all other next now.

**Comment by loudoweb** [comment]
@Misiur OK!
