### ISSUE TITLE
BitmapData.draw(drawable) should ignore drawable's transform

### ISSUE THREAD

**Issue by jcward** [openfl/openfl#1668]
As reported by Guru AS3 on slack, and confirmed by me, the [docs](http://docs.openfl.org/openfl/display/BitmapData.html#draw) (and the Flash behavior) state that:

> The source display object does not use any of its applied transformations for this call. It is treated as it exists in the library or file, with no matrix transform, no color transform, and no blend mode.

This means the below should draw a round circle into the Bitmapdata. It does on the Flash target, but it draws an oval in neko (I didn't check other targets.)

```
    var circle = new Shape();
    circle.graphics.beginFill(0xff0000);
    circle.graphics.drawCircle(25,25,25);
    circle.scaleY = 0.25;
    var bd = new BitmapData(50,50,true,0x333333);
    bd.draw(circle);
    addChild(new Bitmap(bd));
```

**Comment by guruas3** [comment]
Well i found where it comes from: https://github.com/openfl/openfl/blob/develop/openfl/display/BitmapData.hx#L462

When i removed that copyMatrix it started working the same for both flash, html5 and windows.

I also found the commit of this particular feature: https://github.com/openfl/openfl/commit/4b7e96918ddb93251701a37d5b40674af815c543
by @jgranick. Not sure why you needed this but it really breaks the behavior on different platforms.

All that is just for simple matrix transform but there is also `__worldTransform, __worldColorTransform` and blend mode that are copied frome the original source.

**Comment by jgranick** [comment]
The matrix is fixed in the latest development branch, still need to fix alpha and colortransform
