### ISSUE TITLE
Graphics.drawpath with GraphicsPathWinding.NON_ZERO gives wrong results on html5 

### ISSUE THREAD

**Issue by Helgiii** [openfl/openfl#1672]
Currently NON_ZERO winding mode draws the same way as EVEN_ODD on html5. I checked renderers: webgl, canvas

Try this example targeting flash, then html5
`var i:Int;
var star_commands:Vector<Int> = new Vector<Int>();
for (i in 0 ... 5) star_commands.push(0);

star_commands[0] = GraphicsPathCommand.MOVE_TO;
star_commands[1] = GraphicsPathCommand.LINE_TO;
star_commands[2] = GraphicsPathCommand.LINE_TO;
star_commands[3] = GraphicsPathCommand.LINE_TO;
star_commands[4] = GraphicsPathCommand.LINE_TO;

var star_coord:Vector<Float> = new Vector<Float>();
for (i in 0...10) star_coord.push(0);

star_coord[0] = 66; //x
star_coord[1] = 10; //y 
star_coord[2] = 23; 
star_coord[3] = 127; 
star_coord[4] = 122; 
star_coord[5] = 50; 
star_coord[6] = 10; 
star_coord[7] = 49; 
star_coord[8] = 109; 
star_coord[9] = 127;

graphics.beginFill(0x003366);
graphics.drawPath(star_commands, star_coord, GraphicsPathWinding.NON_ZERO);
`

**Comment by jgranick** [comment]
This should be resolved in current releases :smile:
