### ISSUE TITLE
TextFormat breaks word wrapping

### ISSUE THREAD

**Issue by MSGhero** [openfl/openfl#1675]
Repro on latest dev:
```haxe
var tf = new TextField();
tf.text = "here is some fantastic\ntext";
tf.setTextFormat(new TextFormat(null, 8), 15, 16);
tf.wordWrap = true;
addChild(tf);
```

![image](https://user-images.githubusercontent.com/5033927/29301421-a2efdb40-8141-11e7-88a6-747c409d758a.png)
Flash vs Neko.

The issue is that the new format causes the ["word-wrap due to spaces in the text" while loop](https://github.com/openfl/openfl/blob/develop/openfl/_internal/text/TextEngine.hx#L1117-L1361) to exit early. It should either handle the new format itself (or call a function), or there should be a way for the overall loop to re-enter the space-wordWrap condition, even if there are no more spaces in the text.

**Comment by jgranick** [comment]
Here's an additional instance where this appears to be occurring:

http://community.openfl.org/t/openfl-6-1-0-textfield-issue-with-bold-text/9524/2

**Comment by MSGhero** [comment]
This one is tough. Looking at it again, the wordWrap loop should definitely also handle "format range end" instead of exiting and causing it to be handled elsewhere.

**Comment by larsiusprime** [comment]
I just want to say y'alls extremely close attention to all these little text edge cases over the years is one of my biggest reasons for continuing to use and love OpenFL

**Comment by MSGhero** [comment]
![image](https://user-images.githubusercontent.com/5033927/33160251-9ca8eee8-cfe8-11e7-9f9b-c9f20f7d14b6.png)

Again, I just need to unbreak everything else first.
