### ISSUE TITLE
Small TextFields don't wrap correctly

### ISSUE THREAD

**Issue by MSGhero** [openfl/openfl#1676]
Repro on latest dev:
```haxe
var tf = new TextField();
tf.text = "aaaaaaaa"; // 8 of them
tf.wordWrap = true;
tf.border = true;
tf.width = 14; tf.height = 10;
addChild(tf);
trace(tf.numLines);
```
4 lines on Flash, 8 on Neko. Looks like `breakLongWords()` has to leave at least two characters per line except for the last line, regardless of the `width` of the text field.

**Comment by RblSb** [comment]
Maybe this is not related to breaking a words?
```haxe
var test = new TextField();
test.autoSize = "left";
test.text = "aa";
		
var tf = new TextField();
tf.text = "aaaaaaaa"; // 8 of them
tf.wordWrap = true;
tf.border = true;
tf.width = test.width;
tf.height = 200;

trace(tf.width);
```

**Comment by MSGhero** [comment]
Add the textfield to the stage, and you get what I got. Seems like flash doesn't calculate wrapping and stuff until the text has been added. `numLines = 1` before addChild and `4` after.

**Comment by RblSb** [comment]
Sorry, I missed addChild in my example. I mean that tf.width has a different value for flash and neko with one font size. Is this related to breakLongWords()?

**Comment by MSGhero** [comment]
I'm getting like 14.6 on neko and 14 on flash, and that's really due to however fonts are implemented on cpp targets. Are you getting something different, and are you using the latest git version of OpenFL?

Although when I try `tf.width = test.width - 1`, `numLines = 8` on flash, which isn't consistent with my first assumption. It's possible my test case was flawed, where two characters can actually fit on Flash but not on Neko due to the font implementation details I just mentioned...

I guess it needs more testing.

**Comment by MSGhero** [comment]
Ok yeah I understand your first post more now. I'll do a bit more toying around, but I think this is a non-issue.

**Comment by RblSb** [comment]
Yes, there is a width difference even if you specify explicitly the font and size (depends on the font size). I also think that this is not a bug.

**Comment by MSGhero** [comment]
Hm, I guess 14 was just an unlucky random number to pick. Any other number would have made it clear.
