### ISSUE TITLE
Including a .txt file as an asset prevents already-connected gamepads from being detected on windows target 

### ISSUE THREAD

**Issue by dustinaux** [openfl/openfl#1678]
This sure was a fun one to hunt down this morning!  -_-

To reproduce:

- Plug in a controller.

- Load up the GamepadInput Sample and add a .txt file to the project folder.

- Include it with `<assets path="changelog.txt" />` in project.xml

- Compile for windows.

Observe that it doesn't work until you unplug and plug in the controller again.

Easy workaround:

- `<template path="changelog.txt" />`

Using openfl 6.0.1, lime 5.3.0 and an Xbox 360 controller.

**Comment by jgranick** [comment]
Based on timing, there is a chance the gamepad could be connected already by the time your application finishes the preload step and starts.

Can you tell if the "Gamepad connected" message does not display (but the gamepad input still traces out) or if no input from the device is reported at all on the GamepadInput sample? Thanks!

**Comment by dustinaux** [comment]
There's no message and no input at all, and Gamepad.devices returns 0 when queried at any time until the controller is unplugged and plugged back in, then everything works.

Tested html5 and there's no problem there at all.

**Comment by jgranick** [comment]
We listen to `SDL_CONTROLLERDEVICEADDED` on the native side, but I have a feeling that loading assets is causing our code to initialize (perhaps?) after SDL has available gamepads. As a result, the event is not dispatched, but calling `SDL_GetNumJoysticks` on startup may be needed, to check for any already available, where events were not dispatched

**Comment by jgranick** [comment]
It looks like the Gamepad device (in Lime) was already added, so I added changes so that a new `GameInput` object will dispatch `DEVICE_ADDED` events for any pre-existing devices :smile:
