### ISSUE TITLE
Add OGG support for Flash

### ISSUE THREAD

**Issue by steverichey** [openfl/openfl#168]
I suggest, and am willing to implement, Flash support for OGG files in OpenFL. At present, many devs have to create both MP3 and OGG versions of their sound files if they wish to release to both Flash and native versions of their OpenFL project.

I believe that Adobe's [Crossbridge](https://github.com/adobe-flash/crossbridge) project should make this relatively easy. However, this could be quite complicated, and I am not a frequent contributor to OpenFL, so some direction on how this could be accomplished would be appreciated.

**Comment by xraven13** [comment]
Any news about this feature ?

**Comment by jgranick** [comment]
I still think this could be interesting, but let's keep talking about this on the OpenFL Slack room or on the forums, I'm trying to tidy up the issue list to be bugs, not enhancements :smile:

Thanks guys
