### ISSUE TITLE
 OpenFL 6.1.0 asset alpha problem from swf  

### ISSUE THREAD

**Issue by 22Round** [openfl/openfl#1690]
have tested OpenFL 6.1.0 and discovers that asset's alpha from swf does't works properly, tested in HTML5 target

```haxe
package;

import openfl.display.Sprite;
import openfl.Assets;

class Main extends Sprite {
	
	public function new () {
		
		super ();
		
		var cube= Assets.getMovieClip ("cubeIU:UICube");
		addChild (cube);
		
	}
}
```

[cubeIU.zip](https://github.com/openfl/openfl/files/1274054/cubeIU.zip)

**Comment by jgranick** [comment]
Thanks! We'll try and look into it

**Comment by jgranick** [comment]
Awesome to hear this is resolved :smile:

http://community.openfl.org/t/assets-displayobject-alpha-bug-from-swf-in-openfl-6-1-0/9504
