### ISSUE TITLE
Add support for `SampleDataEvent.SAMPLE_DATA`

### ISSUE THREAD

**Issue by jgranick** [openfl/openfl#1705]
Adding support for `SampleDataEvent.SAMPLE_DATA` would be very valuable for generative audio. With OpenAL under the hood, there should be a way to do it.

**Comment by jgranick** [comment]
Related discussion:

http://community.openfl.org/t/is-sampledataevent-implemented-for-windows/9222/16

**Comment by scanline** [comment]
[https://github.com/openfl/openfl/pull/1716](url)

**Comment by joshtynjala** [comment]
Closing old issue that was implemented by a PR.

openfl/openfl@e379366ed3cffd60f7890c67a08f7e5ceac54dd4
