### ISSUE TITLE
copyPixels' destPoint issue on native

### ISSUE THREAD

**Issue by starry-abyss** [openfl/openfl#1707]
I have a problem with lime 5.4.0 and openfl 6.1.0 in BitmapData.copyPixels() on windows target.
1) `alphaPoint.__toLimeVector2 ()` seems to override the value of `destPoint.__toLimeVector2 ()` because they return static that is passed to the same function
2) when I change static to non-static, non-zero destPoint still doesn't work for me as expected. it either crops width/height of copied image without shifting it, or adds noise after shifting (depending if destPoint coordinates are positive/negative)

Here is the example project:
[openfl-copypixels-mask.zip](https://github.com/openfl/openfl/files/1287990/openfl-copypixels-mask.zip)

**Comment by starry-abyss** [comment]
Thank you, tried lime 5.5.0 and openfl 6.1.1, while destPoint with positive x and y now work as on flash, the negative x or y are still broken (Point(-20, -20) in my example):

native:
![default](https://user-images.githubusercontent.com/11571820/30384305-9dcab342-98ac-11e7-8de2-66ac928ca5c8.png)

flash:
![default](https://user-images.githubusercontent.com/11571820/30384420-e49fda72-98ac-11e7-9477-45abd4b78ac8.png)

**Comment by jgranick** [comment]
Thank you for your help!

I believe it should work after this change:

https://github.com/openfl/lime/commit/c5184e41bb90e4435f61be61a820104a9c208535

**Comment by jgranick** [comment]
Sorry, there's still a case that's not handled :confused:

**Comment by jgranick** [comment]
Okay, I think I got it :sweat: 

https://github.com/openfl/lime/commit/411f9d06686573063a02d1f2953c58090996cb45
