### ISSUE TITLE
Ascent in HTML5 text renderers

### ISSUE THREAD

**Issue by MSGhero** [openfl/openfl#1711]
`layoutGroup.ascent` is never taken into account in `CanvasTextField` and `DOMTextField`. It's fine in `CairoTextField`.

@jgranick I see notes about hacks (`// Hack, baseline "top" is not consistent across browsers`), so that's probably out of my depth.

Test case:

```haxe
var tf = new TextField();
tf.wordWrap = true;
tf.border = true;
tf.text = "bbbbb";
tf.setTextFormat(new TextFormat(null, 20), 2, 3);
addChild(tf);
```

The bottoms of the b's should align.

**Comment by jgranick** [comment]
We should have ascent hard-coded into our builds, now, on HTML5, so that we can use these values at runtime to help fix poor (read: non-existent) text measurement APIs at runtime
