### ISSUE TITLE
Can't run 'openfl test html5' due to "The system cannot find the path specified"

### ISSUE THREAD

**Issue by rb1147x** [openfl/openfl#1714]
I just installed openfl 6.1.2 and lime 5.5.0 and when I try testing the html5 target I receive:

`The system cannot find the path specified.
`

Running with -verbose I get this:

```
Running command: RUN
 - Starting local web server: http://localhost:3000
 - Running command: C:\Program Files\Haxe Toolkit\haxe\lib\lime/5^,5^,0/templates/bin/node/node-windows.exe "C:\Program Files\Haxe Toolkit\haxe\lib\lime/5,5,0/templates/bin/node/http-server/bin/http-server" Export/html5/bin -p 3000 -c-1 --cors -o
The system cannot find the path specified.
```

I feel like the culprit is in that first path - "..\lime/5^,5^,0/..". Odd since the second path listed get's it correct.

Is this a bug? A config issue or something I can fix?

Thanks

**Comment by jgranick** [comment]
I think this is caused by spaces

https://github.com/openfl/lime/commit/95410f563af5963bb117bc1c944f28766423ddb0

Perhaps this will work. If you modify your copy of Lime directly, run `haxelib install format && lime rebuild tools` before trying again, thanks :smile:

**Comment by rb1147x** [comment]
Running `haxelib install format` and `lime rebuild tools` did the trick, thanks!
