### ISSUE TITLE
Graphics.drawTriangles does not work without indices

### ISSUE THREAD

**Issue by ProPuke** [openfl/openfl#1719]
`Indices` are an optional (default null) parameter, however `drawTriangles` immediately aborts if they are missing:

https://github.com/openfl/openfl/blob/c2d593029ee9bc43e82531c9b4d7f170d128dc16/openfl/display/Graphics.hx#L531

Despite generating them if they were missing, further down:

https://github.com/openfl/openfl/blob/c2d593029ee9bc43e82531c9b4d7f170d128dc16/openfl/display/Graphics.hx#L541-L557

The first null check should not be there.

Also it aborts if `uvtData` is null, which is also an optional (default null) parameter.

It's not clear if this is legal or not. If not, this parameter should not be optional with a default value of null. If it is legal then this null check should also not be at the head.

**Comment by jgranick** [comment]
Thanks for the heads-up :smile:

This was an oversight. On my version, it worked after removing those parameters, but the fill did not work properly on our Cairo renderer. A few fixes and this basic sample works for me:

```haxe
package;


import openfl.display.Sprite;
import openfl.Vector;


class Main extends Sprite {
	
	
	public function new () {
		
		super ();
		
		graphics.beginFill (0xFF8000); 
		graphics.drawTriangles (Vector.ofArray([
			10,10,  100,10,  10,100, 
			110,10, 110,100, 20,100.]));
		
	}
	
	
}
```
