### ISSUE TITLE
[HTML5] TextField width with size 1px cause crash

### ISSUE THREAD

**Issue by flashultra** [openfl/openfl#1725]
I have my class which extend Textfield . At example : 
    class CommonLabel extends TextField
so when I create instance and init my class I set width = 1px , but the app freeze and not have any error or other indication for problem . If set width to be 4px or more, everything works. On flash there is no problem to set 1 px . Setting width on textfield to be 1px is only for initial creation on class.  Why there have problem to set < 4 px only for html5 target ?

**Comment by MSGhero** [comment]
This might have been fixed already. Is your OpenFL at the latest version? If so, try using the latest dev build.

**Comment by flashultra** [comment]
I'm using OpenFL 6.1.0 and Lime 5.4.0 . I will update to 6.1.2 and will try

**Comment by flashultra** [comment]
It's work with 6.1.2
Thank you.
