### ISSUE TITLE
Assets.getFont not work correctly 

### ISSUE THREAD

**Issue by flashultra** [openfl/openfl#1726]
Assets.getFont not work correctly  when have upper case in file extension for font name  ( embeded fonts ) .  At example:
  Assets.getFont("fonts/verdana.TTF")  will return  "There is no FONT with and ID ..... "
but same code 
  Assets.getFont("fonts/verdana.ttf")  will works correctly.

In my test I change embded font filename to verdana.TTF  and to verdana.ttf to respond on the name in Assets.getFont i.e. the problem is only with uppercase . 
I'm using OpenFL 6.2.0 and Lime  5.6.0

**Comment by jgranick** [comment]
Thanks, should be fixed now :smile:
