### ISSUE TITLE
Tilemap: Adding multiple times the same tile - Intended behavior?

### ISSUE THREAD

**Issue by miltoncandelero** [openfl/openfl#1730]
Hello. I was tinkering with tilemap and by accident I ended up adding twice the same tile.

```
		var t = new Tile(1);
		map.addTile(t);
		map.addTile(t);
```

This causes all sort of problems since the two are added to the list (map.numtiles is now 2) and if I manipulate the tile "t" only one of the two added instances actually updates.

Maybe this is an intended behavior (To use only one tile as some sort of "brush"?) but it would be nice if there was a "safe add" that checks if the tile I am adding isn't already added.

---

**To replicate this behavior:**

Add the same tile twice:

```
		t = new Tile(1,10,10);
		map.addTile(t);
		map.addTile(t);
```

Move the instance t (class variable) in an update loop:

```
	var spdx = 0.2;
	private function update(e:Event = null):Void 
	{
		/* DELTA */
		currentTime = Lib.getTimer ();
		dt = (currentTime - previousTime);
		previousTime = currentTime;
		
		t.x += dt * spdx;
		if (t.x > 800) { t.x = 799; spdx = -0.2;}
		if (t.x < 0) { t.x = 1;	spdx = 0.2;}
	}
```

**Observed behavior:**

One tile moves but another ones stays static.

**Intended behavior:**

???

---

EDIT: Sorry, Openfl 6.2.0

**Comment by jgranick** [comment]
We'll make a decision about how this should work, soon, and make it consistent :smile:

**Comment by jgranick** [comment]
Thanks again for reporting :smile:
