### ISSUE TITLE
BunnyMark fails with Dom-Renderer

### ISSUE THREAD

**Issue by hklindworth** [openfl/openfl#1731]
When starting openfl-samples BunnyMark with `openfl test html5 -Ddom`

it fails at:

https://github.com/openfl/openfl/blob/04e32ed1d18d413613ce887117859e2e14cfdd07/openfl/_internal/renderer/canvas/CanvasTilemap.hx#L33

with

```
Uncaught TypeError: Cannot read property 'setBlendMode' of null
    at openfl_display_Tilemap.__renderDOM (BunnyMark.js:66988)
```

It seems to be related to CanvasTilemap being used by the DOM Render and not having that field initialized.

**Comment by jgranick** [comment]
Thanks for the report! Just fixed it :+1:
