### ISSUE TITLE
Timeout for URLRequest

### ISSUE THREAD

**Issue by ben-farrant** [openfl/openfl#1733]
I need to override the default timeout for an URLRequest. What would be the easiest way to accomplish this? I tried this, but it doesn't work. `openfl.net.URLRequest has no field idleTimeout`
```
if (timeout > 0) {
    request.idleTimeout = timeout;
}
```

**Comment by jgranick** [comment]
This was just added yesterday (for all targets except Flash Player):

https://github.com/openfl/openfl/commit/dfff39f4378552be8219deeafa1d3afd62fa05d7
