### ISSUE TITLE
Tile (Tilemap) colorTransform

### ISSUE THREAD

**Issue by loudoweb** [openfl/openfl#1737]
The color output is wrong (I tried on neko and html5).

I've tried with pink : 0xea22b9
`ct = new ColorTransform();
ct.color = 0xea22b9;
tile.colorTransform = ct;`

And it outputs white color instead.

Also, it doesn't work at all on flash target.

**Comment by jgranick** [comment]
Thank you :smile:

It should be fixed: https://github.com/openfl/openfl/commit/2b2c892da454d2808725bd75799dc3576683c801

This field doesn't work (currently) on software renderers, as it is too expensive to apply to cairo and canvas. I think we could probably get a workaround in place for Flash, I'll take a look :smile:
