### ISSUE TITLE
can we hot load module from internet at runtime ?

### ISSUE THREAD

**Issue by loohoo** [openfl/openfl#1741]
I used to be a as3 programmer. on flash play and air, we can load swf module from local and internet and in which the code we can execute...
howevery, can openfl ? 
because I going to learn openfl and want to dev a game target at android/ios, and this game need hotfix ability...

**Comment by jgranick** [comment]
Sorry for the delay in responding! We do support HTML5 and AIR on mobile, which both support hot-loading like this. It is possible to do native hotloading for native, but we don't have that automatically implemented for Android, and it would be disallowed by Apple's restrictions (which requires loaded code to execute in Safari)
