### ISSUE TITLE
Masking translation incorrect if mask not direct child of object being masked

### ISSUE THREAD

**Issue by Greg209** [openfl/openfl#1754]
If the mask for an object is not a direct child of the object, the translation coordinates are incorrect compared to flash.  In the following code, there is a container sprite with a child redbox sprite which contains a child greenbox sprite. A mask (black circle) is added to redbox so will also mask the greenbox. 

Along first row shows the circle as a child of the redbox, the second is a child of the container and the third a child of the greenbox.

The top two rows show the object locations unmasked for HTML5 and Flash. The final two rows show the the same but with the redbox masked.

![masking](https://user-images.githubusercontent.com/550301/32659239-bc6ff41a-c615-11e7-859f-673454e892c0.png)

Here's the code....

```
	function build() {

		var container1 = new Sprite();
		container1.x = 50;
		container1.y = 75;
		var redBox1 = redBox();
		var greenBox1 = greenBox();
		var mask1 = maskCircle();

		// redBox1.mask = mask1;

		container1.addChild( redBox1 );
		redBox1.addChild( greenBox1 ); 
		redBox1.addChild( mask1 );  // mask is child of redbox - WORKS CORRECTLY
		addChild( container1 );

		var container2 = new Sprite();
		container2.x = 300;
		container2.y = 75;
		var redBox2 = redBox();
		var greenBox2 = greenBox();
		var mask2 = maskCircle();
		
		// redBox2.mask = mask2;

		container2.addChild( redBox2 );
		redBox2.addChild( greenBox2 ); 
		container2.addChild( mask2 );  // mask is child of container - INCORRECT MASKING!!!!!!!!
		addChild( container2 );

		var container3 = new Sprite();
		container3.x = 550;
		container3.y = 75;
		var redBox3 = redBox();
		var greenBox3 = greenBox();
		var mask3 = maskCircle();
		
		// redBox3.mask = mask3;

		container3.addChild( redBox3 );
		redBox3.addChild( greenBox3 ); 
		greenBox3.addChild( mask3 );  // mask is indirect child of redbox  - INCORRECT MASKING!!!!!!!!
		addChild( container3 );

	}

	function redBox():Sprite {
		var r = new Sprite();
		r.x = 50;
		r.graphics.beginFill(0xff0000);
		r.graphics.drawRect( 0, 0, 100, 150);
		r.graphics.endFill();
		return r;
	}

	function greenBox():Sprite {
		var g = new Sprite();	
		g.x = 100;
		g.y = -50;
		g.graphics.beginFill(0x008800);
		g.graphics.drawRect( 0, 0, 100, 150);
		g.graphics.endFill();
		return g;		
	}

	function maskCircle():Sprite {
		var m = new Sprite();
		m.x = 50;
		m.y = 25;		
		m.graphics.beginFill(0x0);
		m.graphics.drawCircle( 50, 50, 60 );
		m.graphics.endFill();
		return m;
	}
```

**Comment by jgranick** [comment]
Thanks! This should be resolved now :grin:

**Comment by Greg209** [comment]
Thanks Joshua - looks much better. There is still a little bug that I can see but in a slightly different example.  In this instance I've been able to recreate it in a SWF Movieclip and only seems to be apparent on the first render. 

In the attached SWF is a simple symbol (three coloured rectangles with an oval mask over them. If located at 0,0 the rendering is fine however if the symbols is positioned elsewhere, on the first render, the mask seems to be still located at 0,0 but the object is positioned correctly. 

The top pic is how it should look (in Flash), the second is how it appears on the first render (HTML5) and the last is after the page updates (typically by a mouse movement) and then looks correct (HTML5).

![masking2](https://user-images.githubusercontent.com/550301/32702782-af56ae98-c7e3-11e7-8822-3143ade36523.png)

Here is the SWF(zipped) and the code.

```
		icon = Assets.getMovieClip("test:IconButton");
		icon.x = 50;
		addChild( icon );
```

[test.zip](https://github.com/openfl/openfl/files/1465054/test.zip)
