### ISSUE TITLE
drawTriangles uvData not working

### ISSUE THREAD

**Issue by dustinaux** [openfl/openfl#1755]
After updating openfl, using drawTrianlges with uvData would only render the top-left portion of the texture, as if the x and y coords were always 0, but the width and height continued to work.

I reversed the movement of the line "cairo.source = fillPattern;" in this commit:

https://github.com/openfl/openfl/commit/e6787d3bf874dae323eaa2233075ac377f514d3f#diff-5c046efbf46f21e3672c16d6cabf95af

and the problem was solved.

I was wondering why that change was made though, because I don't want to inadvertently break something else. The other change in the commit appears to be the fix to the issue it references. @jgranick

**Comment by jgranick** [comment]
It looks like it might have intended to be an optimization to reduce the amount of code run regularly in the loop, but in the same test case I was fixing, I think there was only one triangle, so I guess the regression wasn't seen :sweat:

Maybe `cairo.fill ()` clears the source fill pattern, and `cairo.fillPreserve ()` would allow us to reduce repeated calls to set the source, but for now I'll revert that part of the change to help things work :smile:
