### ISSUE TITLE
Bug: TextField getCharBoundaries crashes on "\n"

### ISSUE THREAD

**Issue by jaredsain** [openfl/openfl#1765]
When calling textField.getCharBoundaries(x), where x is the index of a string whose value is "\n", TextField.hx will crash. An older implementation would return a null value instead of a hard crash, which is preferable to me.

Crash output:
Called from openfl.text.TextField::getCharBoundaries openfl/text/TextField.hx line 191
Error : Null Object Reference

**Comment by jgranick** [comment]
I think we should do further investigation, but for now, a `try`/`catch` should help make this return null
