### ISSUE TITLE
Invalid Mac OSX platform scaleMode

### ISSUE THREAD

**Issue by cjmxp** [openfl/openfl#1772]
target cpp
openfl 6.5.0
lime 5.8.2

Mac OSX platform scaleMode invalid windows platform not tested

**Comment by jgranick** [comment]
This is something that is not implemented currently, but is TODO. There were renderer improvements required to allow something like this to take place easily, and has not been a high priority, but we can track as an enhancement here: https://github.com/openfl/openfl/issues/136
