### ISSUE TITLE
Regression in location of TextField cursor

### ISSUE THREAD

**Issue by jgranick** [openfl/openfl#1778]
Cursor appears to stay on first line, when the user clicks on a line further down

Reference: http://community.openfl.org/t/direct-comparison-of-medium-sized-game-flash-as3-vs-openfl-haxe-issues/9777/14

**Comment by jgranick** [comment]
Also http://community.openfl.org/t/text-cursor-stucks-at-first-line/9916/3

**Comment by hopewise** [comment]
Is there any work around for this bug? what would be the reason behind it?
