### ISSUE TITLE
Crash on Flash target with latest OpenFL 6,5,2

### ISSUE THREAD

**Issue by pozirk** [openfl/openfl#1781]
Everything works fine with 6,5,1
Get that in openfl.display::Window/create
> [Fault] exception, information=TypeError: Error #1009: Cannot access a property or method of a null object reference.

**Comment by pozirk** [comment]
Ok, I see it's fixed with 6,5,3. :)
Thank you!

**Comment by jgranick** [comment]
Sorry for the trouble! I realized this too after the release :disappointed_relieved: 

Our CI doesn't catch runtime problems on the Flash target
