### ISSUE TITLE
Issue detecting changes on shader parameters 

### ISSUE THREAD

**Issue by diegogonzalez** [openfl/openfl#1787]
I tried to use a shader ([here is the code of the shader class](https://gist.github.com/anonymous/cae1ac9217c574dd75e80c534633474d)) that depends of time (so I pass the time through parameter) , but the changes only happen when I lost and gain focus again.  

Modifying the position of the bitmap the problem is "solved" assuming that sets __renderDirty and some other flags to true, forcing a re-render.

**Comment by jgranick** [comment]
In OpenFL 8 and creator, call `invalidate()` on an object to force it to render again
