### ISSUE TITLE
Regression in support for Actuate.transform().color()

### ISSUE THREAD

**Issue by jgranick** [openfl/openfl#1793]
If a single object is on the stage, but nothing is happening other than a color tween, it does not appear to update. This is a regression. Adding an animation to another property (such as x or y) causes the color tween to work properly

```haxe
package;


import motion.easing.Linear;
import motion.Actuate;
import openfl.display.Sprite;


class Main extends Sprite {
	
	
	public function new () {
		
		super ();
		
		var sprite = new Sprite ();
		sprite.graphics.beginFill (0x00FF00);
		sprite.graphics.drawRect (0, 0, 100, 100);
		addChild (sprite);
		
		// Actuate.tween (sprite, 2, { x: 100 });
		Actuate.transform (sprite, 2).color (0xFF0000).ease (Linear.easeNone);
		
	}
	
	
}
```

**Comment by Gama11** [comment]
Could this be related to https://github.com/openfl/openfl/issues/1787 / https://stackoverflow.com/questions/47774192/openfl-provide-time-to-shader?

**Comment by jgranick** [comment]
Fixed by https://github.com/openfl/openfl/pull/1803
