### ISSUE TITLE
TextField's bitmap cache does not update (showing old text)

### ISSUE THREAD

**Issue by chatziko** [openfl/openfl#1798]
When a `TextField` with `cacheAsBitmap` (eg with filters) is modified without changing its size, the cache is not updated, showing the old state. The following code demonstrates the problem ([project here](https://github.com/openfl/openfl/files/1620625/cacheBugDemo.zip)):

```
var txt = new TextField();
addChild(txt);	

txt.cacheAsBitmap = true;  // or add a filter

txt.text = "aaabbb";

// wait for rendering
haxe.Timer.delay(function() {

	// change the text to something _of the same size_
	txt.text = "bbbaaa";

}, 100);

```

In flash the text updates to "bbbaaa", but in html5 the old cache is used, still showing "aaabbb".

The culprit seems to be this line: 

https://github.com/openfl/openfl/blob/e00c839d2b2bea09507c367577538a4bdc25b56f/src/openfl/display/DisplayObject.hx#L1081

The TextField has no children, so the cache won't update even if `__renderDirty == true` (unless the size changes, which triggers an update later in the code).

I'm not sure what's the best solution. Add some force flag?

**Comment by PXshadow** [comment]
Yeah having the same issue, Only solution besides digging into the openfl source is set Bitmap cache false and then 1 frame later set it to true with a timer 😢
