### ISSUE TITLE
TextField rendering workaround for Firefox webgl/canvas

### ISSUE THREAD

**Issue by chatziko** [openfl/openfl#1801]
TextField webgl/canvas rendering is seriously broken on Firefox, due to a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=737852) that causes canvas text drawn with `baseline = "top"` to look different than in all other browsers (who's bug it is can be debated, but is irrelevant).

There's a hack that seems to be addressing exactly this issue, by moving down text by `size * 0.185`.

https://github.com/openfl/openfl/blob/4f4fa13b14c14eefffb70f7f6acae88dff4d3231/src/openfl/_internal/renderer/canvas/CanvasTextField.hx#L205-L209

However, the effectiveness of this hack is limited, the offset that needs to be applied depends on the font: some fonts need a higher, lower, or even negative offset! This often makes TextField almost unusable on Firefox, we need a better solution.

A much more reliable workaround, which however requires to know the font's `ascender`, is to draw with `baseline = "alphabetic"`, and apply an offset of `size * ascender`. I created a [demo page](https://chatziko.github.io/simulate-baselinetop.html) comparing `baseline = "top"` with this workaround (using opentype.js to get the font's ascender). The result appears identical on all browsers I tested (except firefox, of course).

I also implemented the workaround in `CanvasTextField.hx`, with the ascender hard-coded for my fonts, and it seems to work great!

To use this, of course, there's the major problem of finding the font's ascender. I see a few solutions:

1. Compute font metrics of embedded fonts during build, and make them available at runtime (they might actually be useful for other text-related math).

2. Compute the ascender at runtime. Not sure if there's an easy way though, and using opentype.js is probably an overkill).

3. Let the developper provide a map of ascender values for his fonts. Not great, but better than the current situation.

I'd go with (1), and I'm willing to implement it if I get some feedback about the best way to proceed.

**Comment by MSGhero** [comment]
Related to #1711 or something different? (I’m on my phone so I hope that’s the right one)

**Comment by jgranick** [comment]
Perhaps there's some way we could attempt to detect the ascender, and fallback to our hard-coded value if it is not found? It is rotten that the browser doesn't give us more information. It's important that we don't require more than just web fonts at runtime, since users can also generate their own fonts outside the build system

**Comment by chatziko** [comment]
I tried a [few](https://codepen.io/jakob-e/pen/QbvQoo/) [hacks](https://www.npmjs.com/package/measure-font) that I found but nothing computes what we want. And most approaches I saw compute metrics by drawing on a canvas and computing distances between pixels, but the ascender does not necessarily correspond to such a distance. The only accurate method is to read the font file (eg with opentype.js) but for externally loaded webfonts we don't have access to that.

On the other hand, font metrics are just a few numbers per font, and the developer knows the font's he's going to use, it would be trivial to set them manually and get pixel-perfect rendering. And I'm sure that we can use the font metrics to solve other issues, eg  #908.

So I propose the following: `lime.text.Font` already has metrics fields, we make them writable and allow the developer to simply do:

    var font = Assets.getFont("...");
    font.ascender = 600;
    font.unitsPerEM = 1000;

`CanvasTextField` can then get the info from `openfl.text.Font.__fontByName`.

To support fonts loaded at runtime, we can add a `registerFontInstance` method to `openfl.text.font` (similar to `registerFont` but accepting an instance instead of a class), so that we can do:

    var font = new Font(fontName);
    font.ascender = 600;
    font.unitsPerEM = 1000;
    Fonts.registerFontInstance(font);

If in the future we find a good way to compute the metrics at runtime, we just add it to `lime.text.Font`. Or we can even implement computing the metrics during build so that we get them automatically at least for known fonts.

I gave it a try implementing this solution, it's [here](https://github.com/openfl/openfl/compare/develop...chatziko:firefox-canvas-workaround) and [here](https://github.com/openfl/lime/compare/develop...chatziko:firefox-canvas-workaround).

With this implementation, I also created a [demo](http://chatziko.github.io/firefox-workaround/Export/html5/bin/) (here's the [source](https://github.com/chatziko/chatziko.github.io/tree/master/firefox-workaround)) showing two TextFields, one rendered with the old hack and the other with the new. The difference is huge for many fonts, and the new hack perfectly matches the rendering of other browsers.

**Comment by chatziko** [comment]
@MSGhero : I don't think they're related. From what I understand #1711 concerns multiformat on all browsers. This issue is for any text, only on Firefox.

**Comment by chatziko** [comment]
Some more progress:

1. I implemented including font metrics in html5 for embedded fonts. This was quite easy, I just had to set the properties in the generated `__ASSET__*` classes in `ManifestResources.hx`.

2. I changed `TextEngine` to take the font metrics into account in html5, if available. This seems to fix #908, I tested it with the app reported there. As a bonus, this makes the corresponding methods quasi-identical for html5 and lime_cffi, so less `#if`s.

The new branches are [here](https://github.com/openfl/openfl/compare/develop...chatziko:html5-font-metrics) and [here](https://github.com/openfl/lime/compare/develop...chatziko:html5-font-metrics).

So to summarize the changes:
- font metrics are automatically avaiable in html5 for fonts known at build time.
- for fonts not known at build time, metrics can be manually added via `openfl.text.Font.registerFontInstance` (as shown in the [demo](http://chatziko.github.io/firefox-workaround/Export/html5/bin/)).
  * if in the future we find a way to compute metrics automatically for web fonts, we can easily add it to `lime.text.Font`.
- if font metrics are available:
  * they are used to properly compute `textHeight` (fixing #908)
  * they are used to fix text positioning in Firefox (the current issue).

@jgranick : What do you think? Any chance of merging something along these lines?

**Comment by chatziko** [comment]
Just added PRs #1814, openfl/lime#1152 so that this is not forgotten.

**Comment by chatziko** [comment]
Just wanted to point out that, although this issue was closed, the problem is **not** fixed unless #1814 is also merged.

Currently (v7.1.2) font metrics are included in html5 (PR openfl/lime#1152) but they're not used anywhere!
