### ISSUE TITLE
bitmapdata.fillrect problem on html5

### ISSUE THREAD

**Issue by Helgiii** [openfl/openfl#1808]
when filling with zero opacity color, say 0x00ff0000
result is not visible instantly

how to check it:
create a Bitmap with BitmapData
draw opaque rect using fillrect in it
then onmouseclick draw same size rect but totally transparent (again 0x00ff0000)

expected behaviour is fill not draw.. i.e area should be filled(cleared) with transparent color
on flash target it works fine, on html5 not
thanx guys)

**Comment by jgranick** [comment]
This is working consistently for me on Flash, Neko and HTML5:

```haxe
package;


import openfl.display.Bitmap;
import openfl.display.BitmapData;
import openfl.display.Sprite;
import openfl.geom.Rectangle;


class Main extends Sprite {
	
	
	public function new () {
		
		super ();
		
		var bitmapData = new BitmapData (400, 400, true, 0xFFFF0000);
		var bitmap = new Bitmap (bitmapData);
		addChild (bitmap);
		
		bitmapData.fillRect (new Rectangle (100, 100, 100, 100), 0xFF00FF00);
		
		addEventListener ("click", function (_) {
			
			trace ("CLICK");
			bitmapData.fillRect (new Rectangle (100, 100, 100, 100), 0x00ff0000);
			
		});
		
	}
	
	
}
```

If you click on the white area (outside the bitmap), no click event is triggered, so nothing occurs. If you click on the object, then a click is triggered, and the bitmap is given a transparent fill

**Comment by Helgiii** [comment]
found it.. 
ImageCanvasUtil.hx fillRect
and this code there
if (rect.x == 0 && rect.y == 0 && rect.width == image.width && rect.height == image.height) {
//not drawing here 
}


example test code
package;


import openfl.Vector;
import openfl.display.Bitmap;
import openfl.display.BitmapData;
import openfl.display.GraphicsPathWinding;
import openfl.display.Sprite;
import openfl.geom.Matrix;
import openfl.geom.Point;
import openfl.geom.Rectangle;
import openfl.display.GraphicsPathCommand;
import openfl.display.*;


class Main extends Sprite {
	
	
	public function new () {
		
		super ();
		
		
		//sprite with drawn data
		var targetCast:Sprite = new Sprite();
		targetCast.graphics.beginFill(0xffff00, 1);
		targetCast.graphics.drawRect(0, 0, 300, 300);
		targetCast.graphics.endFill();
		
	
		//bd
		var bitmapData = new BitmapData (400, 400, true, 0x00888888);
		var bitmap = new Bitmap (bitmapData,"auto",false);
		addChild (bitmap);
		
		//draw sprite to bd
		bitmapData.draw(targetCast, new Matrix(), null, "normal");

		
		addEventListener ("click", function (_) {
			
			trace ("CLICK");
			//full size fill
			bitmapData.fillRect (new Rectangle (0, 0, 400, 400), 0x00ff0000);
			
		});
		
	}
	
	
}

**Comment by jgranick** [comment]
Looks like this was fixed without closing the issue
