### ISSUE TITLE
Classes generated from a swf library cannot have children of a type from that library

### ISSUE THREAD

**Issue by Geokureli** [openfl/openfl#1813]
I have a library assets set to export for actionscript (linkage Parent), with a nested child who is also set to export (linkage Child). both Parent and Child get generated but parent's child is typed as a MovieClip even though it's really a Child. 

the class headers in /Export/flash/haxe/_generated:
    
    class Child extends MovieClip {
    ...
and
    
    class Parent extends MovieClip {
        
        public var child(default, null):openfl.display.MovieClip;
        ...
I'm required to upcast in order to access Child specific properties
    
    trace (new Parent().child);//[object Child]
I was told this should work
I'm using openfl 7.0.0 on haxe 3.4.4

**Comment by jgranick** [comment]
This should be resolved in current versions :smile:
