### ISSUE TITLE
Weird behaviour of graphics.drawTriangles in HTML5

### ISSUE THREAD

**Issue by guruas3** [openfl/openfl#1818]
![2018-02-19_2028](https://user-images.githubusercontent.com/981231/36394381-528d8294-15b4-11e8-8984-12061309bb3e.png)
Basically in HTML5 when the last triangle is drawn using `graphics.drawTriangles()` something else is drawn above it.

I created a little project to test it. (see Flash vs HTML5)
[GraphicsDrawTrianglesBug.zip](https://github.com/openfl/openfl/files/1738008/GraphicsDrawTrianglesBug.zip)

**Comment by jgranick** [comment]
Thanks for the test! I found the issue, it's a matter of automatically closing shapes, with a pending fill. `drawTriangles` in this renderer already commits the result to the canvas, meaning we don't need a pending draw later

**Comment by guruas3** [comment]
Wow. That was quick. Thank you very much!
