### ISSUE TITLE
Recent change breaks flash compatibility on empty TextFields

### ISSUE THREAD

**Issue by chatziko** [openfl/openfl#1822]
f780534070631f4aa95f2b3321e20412fb3ddf7a changes the behaviour of `textHeight` for empty `TextFields`. However, the new behaviour is incompatible with flash's. This trivial example ([empty-textfield-test.zip](https://github.com/openfl/openfl/files/1742456/empty-textfield-test.zip)) demonstrates this.

* With f780534070631f4aa95f2b3321e20412fb3ddf7a
  - html5: `textHeight: 11.85`
  - flash: `textHeight: 0`
* Without f780534070631f4aa95f2b3321e20412fb3ddf7a
  - html5: `textHeight: 0`
  - flash: `textHeight: 0`

This is unfortunate when porting flash games.

**Comment by jgranick** [comment]
Thanks for the test case, and I'll try and compare this with the other test case we had that seemed to require this change

**Comment by jgranick** [comment]
This was fixed, thanks!
