### ISSUE TITLE
Context3D.enableErrorChecking has _huge_ performance overhead on Chrome

### ISSUE THREAD

**Issue by chatziko** [openfl/openfl#1826]
Setting `Context3D.enableErrorChecking = true` makes the app unusable on Chrome, while on other browsers the overhead is small.

It can be [tested here](http://chatziko.github.io/starling-demo-errorcheck/): it's the standard starling demo, simply compiled with

    _starling.enableErrorChecking = true;

On Chrome (tested on OSX / Ubuntu) CPU goes above 50%, and the demo's benchmark can't render a single object at 60fps. Profiling shows that almost all time is spent in

    openfl__$internal_stage3D_GLUtils.CheckGLError

Safari / Firefox have no such issue! I know that `enableErrorChecking` is supposed to have an overhead, still this is weird. I spent a lot of time trying to figure out what's wrong with my app on Chrome alone.

If it can't be fixed, maybe a debugging message can be added to warn developpers?

**Comment by jgranick** [comment]
The overhead is fixed now, we'll have to decide whether to add `gl.getError` again (with this flag) or not -- the HTML5 debugger still works without it
