### ISSUE TITLE
[html5] crash in IE

### ISSUE THREAD

**Issue by Klug76** [openfl/openfl#1835]
My project crash for the html5 target in windows at line
``
haxe\lib\openfl\7,1,2\src\openfl\_internal\renderer\canvas\CanvasGraphics.hx:
1170: context.resetTransform ();
``
According to [docs](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/resetTransform) this method is not supported by IE.
Instead `context.setTransform(1, 0, 0, 1, 0, 0);` can be used - then app works fine.

**Comment by nadako** [comment]
this is fixed by 8d07fcb4420e7ad37fdf726071c35f10dc164ba8, right?
