### ISSUE TITLE
Context3D available before Stage3D.requestContext is called

### ISSUE THREAD

**Issue by peteshand** [openfl/openfl#1837]
On non AIR/Flash targets Context3D appears to be available before Stage3D.requestContext is called. This is problematic when using sharedContexts. I've pushed a fix for Starling to work around this (https://github.com/openfl/starling/commit/65032a0860c896989b8246b6a1cab9dbea1eb6ff), but it would be good to have insight from you guys as to why the Context3D is available before it is requested.

**Comment by jgranick** [comment]
Resolved in current versions
