### ISSUE TITLE
Improve support for Arabic script in TextField

### ISSUE THREAD

**Issue by nightblade9** [openfl/openfl#1853]
Hi,

Similar to [this issue](https://github.com/openfl/openfl/issues/1327), I opened an issue on HaxeFlixel about Arabic text not rendering correctly ([link](https://github.com/HaxeFlixel/flixel/pull/2136)).

Gama11 posted some OpenFL code:

```haxe
package;

import openfl.display.Sprite;

class Main extends Sprite
{
	public function new()
	{
		super();
		var text = new openfl.text.TextField();
		text.text = "بِسم للَه";
		text.defaultTextFormat = new openfl.text.TextFormat("Arial", 48);
		stage.addChild(text);
	}
}
```

This generates disjointed text on Neko (and presumably Android):

![screenshot](https://camo.githubusercontent.com/e1ccbf153aa521a74f32bc143b474b9d08eecd02/68747470733a2f2f692e696d6775722e636f6d2f724476504733532e706e67)

From [this issue first](https://github.com/openfl/openfl/issues/1327), I presumed from the conclusion that this should work now. Am I doing something wrong?

To be clear, this is with OpenFL 8 with Lime 6.2.0:

> - install openfl dev via haxelib git openfl https://github.com/openfl/openfl
> - for Lime, the latest Haxelib release (6.2.0) should be fine

**Comment by nightblade9** [comment]
Thanks for this. I hope I will get a chance to work on this soon.

- I can live with no spaces for now (since I'm just using singular words)
- I have to figure out how to integrate OpenFL into a HaxeFlixel project (not that difficult I hope)
- I don't like using unreleased OpenFL/HaxeFlixel versions, but my game is very small, so I can live with it for this project.

Thanks for the prompt response and fix. I'll verify once things look good on my end and close this.

**Comment by nightblade9** [comment]
@jgranick I'm currently experiencing some problems getting the experimental Flixel branch to work with the latest lime and OpenFL. There's a commentary in the PR thread about it. If I resolve it, I will build (and ship) my game on Android and update you.

If you can take a quick look, maybe the answer is really obvious to you what the problem is.

**Comment by jgranick** [comment]
@nightblade9 I would recommend using the development version of OpenFL and the development version of Lime, together. However, using the release version, `lime.Lib.extraParams` should be available, but only in the macro context. Do you get the error when doing `openfl test neko`, or something else?

**Comment by nightblade9** [comment]
@jgranick I get the error when running `lime test neko` or `lime test html5` (I didn't tset other targets). I'll switch `lime` over to use Git also to see if that makes a difference.

**Comment by jgranick** [comment]
Also, try updating Haxe to a newer version? From what I recall, Haxe 3.4.0 was not stable for us, only Haxe 3.4.3 or greater

**Comment by nightblade9** [comment]
@jgranick I tried reinstlaling Haxe (3.4.7) with lime/openfl from Git; I now get a completely new error when I run `lime test <anything>`:

```
Called from ? line 1
Called from CommandLineTools.hx line 2084
Called from CommandLineTools.hx line 26
Called from CommandLineTools.hx line 140
Called from CommandLineTools.hx line 1869
Called from lime/project/ProjectXMLParser.hx line 25
Called from lime/project/ProjectXMLParser.hx line 58
Called from lime/project/ProjectXMLParser.hx line 2225
Called from lime/project/ProjectXMLParser.hx line 1370
Called from lime/tools/helpers/HaxelibHelper.hx line 255
Called from lime/tools/helpers/LogHelper.hx line 49
Called from lime/tools/helpers/LogHelper.hx line 140
Called from D:\HaxeToolkit\haxe\std/neko/Lib.hx line 42
Uncaught exception - load.c(237) : Failed to load library : lime.ndll
```

Lime 6.2.0 gives me a different error; any idea what this error means? Could it be something about the CPU architecture?

**Comment by nightblade9** [comment]
I'm going to stop right here. I'll wait for the HaxeFlixel branch to merge in, and hopefully these issues will be resolved.

Thanks for your help.

For posterity, here's the error I got (I think it means I'm missing `cl.exe` but I'm not interested in figuring this out right now):

```
Compiling group: lime
cl.exe -Iinclude -Ilib/cairo/include -Ilib/cairo/include/configs/windows/ -DLIME_CAIRO -DHAVE_CONFIG_H -DCAIRO_WIN32_STATIC_BUILD -DCAIRO_HAS_FT_FONT -Ilib/curl/include/ -DLIME_CURL -DCURL_STATICLIB -Ilib/efsw/include/ -DLIME_EFSW -Ilib/freetype/include -DLIME_FREETYPE -Ilib/harfbuzz/src -DLIME_HARFBUZZ -Ilib/jpeg/ -DLIME_JPEG -Ilib/lzma/src -DLIME_LZMA -Ilib/ogg/include/ -Ilib/vorbis/include/ -DLIME_OGG -Ilib/openal/include/ -DLIME_OPENAL -DLIME_OPENALSOFT -DAL_LIBTYPE_STATIC=1 -DAL_ALEXT_PROTOTYPES -DLIME_OPENGL -Ilib/png/ -Ilib/zlib/ -DLIME_PNG -Ilib/sdl/include/ -Ilib/sdl/include/configs/windows/ -DHAVE_LIBC -DLIME_SDL -Ilib/tinyfiledialogs/ -DLIME_TINYFILEDIALOGS -Ilib/ogg/include/ -Ilib/vorbis/include/ -DLIME_VORBIS -DLIME_ZLIB -nologo -DHX_WINDOWS -D_USING_V140_SDK71_
-GR -O2(optim-std) -Zi(debug) -FdD:\HaxeToolkit\haxelib\lime\project\obj/msvcxp/vc.pdb(debug) -Od(debug) -O2(release) -Os(optim-size) -Oy- -c -EHs -GS- -arch:SSE2 -ID:/Haxetoolkit/haxelib/hxcpp/3,4,188/include -DHXCPP_VISIT_ALLOCS(haxe) -DHXCPP_API_LEVEL=0(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -wd4996 ... tags=[haxe,static]
 - src/graphics/cairo/CairoBindings.cpp
 - src/net/curl/CURLBindings.cpp
 - src/ExternalInterface.cpp
Process creation failure : cl.exe
```

**Comment by nightblade9** [comment]
@jgranick if I may request one more thing: if it's possible, please expose these fields so that they can (eventually) be consumed by HaxeFlixel code. I assume detecting language is very tricky/difficult, and instead, we should expose constructor/method/property parameters that allow the user to specify that the language is indeed right-to-left.

**Comment by nightblade9** [comment]
Now that the HaxeFlixel change is merged, is there any way to get this to work without building OpenFL from source?
