### ISSUE TITLE
TextField is missing some navigation / selection shortcuts

### ISSUE THREAD

**Issue by Gama11** [openfl/openfl#1854]
Flash (and most text editors) allow jumping to the next word with <kbd>Ctrl</kbd>+<kbd>Left</kbd>/<kbd>Right</kbd>, and to _select_ until the next word with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Left</kbd>/<kbd>Right</kbd>:

![](https://i.imgur.com/XopsVNT.gif)

```haxe
package;

import openfl.display.Sprite;
import openfl.text.TextField;

class Main extends Sprite {
    public function new() {
        super();
        var textField = new TextField();
        textField.type = INPUT;
        addChild(textField);
        textField.border = true;
    }
}
```

This is currently not supported by OpenFL's `TextField` implementation.

**Comment by MSGhero** [comment]
Closing this when https://github.com/openfl/openfl/tree/text-all-fixes is merged in
