### ISSUE TITLE
TextField.htmlText doesn't handle char code entities

### ISSUE THREAD

**Issue by Gama11** [openfl/openfl#1855]
`TextField.htmlText` doesn't convert char code entities such as `&#62;` for `>` yet.

```haxe
package;

import openfl.display.Sprite;
import openfl.text.TextField;

class Main extends Sprite {
    public function new() {
        super();
        var textField = new TextField();
        textField.htmlText = "&#62;";
        addChild(textField);
    }
}
```

Result on Neko / HTML5:

![](https://i.imgur.com/3VGdZTA.png)

Flash (expected behavior):

![](https://i.imgur.com/FppSm56.png)

**Comment by joshtynjala** [comment]
Closing issue because it has been implemented:

openfl/openfl@27a93cda632edb1d36c1288babbb5f74160c91df
