### ISSUE TITLE
TextField not focused when pressing Tab

### ISSUE THREAD

**Issue by Gama11** [openfl/openfl#1856]
On Flash, pressing <kbd>Tab</kbd> when there's an input `TextField` focuses it. This doesn't work in OpenFL yet.

```haxe
package;

import openfl.display.Sprite;
import openfl.text.TextField;

class Main extends Sprite {
    public function new() {
        super();
        var textField = new TextField();
        textField.type = INPUT;
        addChild(textField);
    }
}
```

**Comment by MSGhero** [comment]
Does this affect something on Flixel's end? I'm starting to look into tab index

**Comment by Gama11** [comment]
I think this was about being able to use tab to focus the console's textfield in the debugger overlay.

**Comment by MSGhero** [comment]
Can you check out #1987 when you get a chance? My OpenFL branches are weird right now.

**Comment by MSGhero** [comment]
Double checked, and this is good now.
