### ISSUE TITLE
TextFormat ranges don't fall back to defaultTextFormat

### ISSUE THREAD

**Issue by Gama11** [openfl/openfl#1861]
```haxe
package;

import openfl.display.Sprite;
import openfl.text.TextField;
import openfl.text.TextFormat;
import openfl.text.Font;

class Main extends Sprite {
    public function new() {
        super();
        var textField = new TextField();
        textField.selectable = false;
        textField.defaultTextFormat = new TextFormat("Arial", 8, 0xffffff);
        textField.text = "foobar";
        textField.setTextFormat(new TextFormat(null, 24, 0xFF0000), 0, 3);
        textField.setTextFormat(new TextFormat(null, 24, 0xFFFF00), 3, 6);
        addChild(textField);
    }
}
```

The `defaultTextFormat` says that Arial should be used by default, and the `TextFormat` ranges don't specify a font. As a result, Arial should be used for those ranges as well, as can be seen on the Flash target:

![](https://i.imgur.com/oMTkQWl.png)

However, Neko and HTML5 seem to ignore the default font:

![](https://i.imgur.com/0pJXmA5.png)

This leads to some funny results in Flixel's FlxTextFormat demo:

![](https://i.imgur.com/aJbMHjD.png)

**Comment by larsiusprime** [comment]
Man you two are on fire lately

**Comment by Gama11** [comment]
Nice, that seems to completely fix the demo! :)

![](https://i.imgur.com/80vKoXX.png)
