### ISSUE TITLE
Npm openfl stage set height issue 

### ISSUE THREAD

**Issue by PXshadow** [openfl/openfl#1864]
![image](https://user-images.githubusercontent.com/9813078/38171636-8cc26232-3552-11e8-94f5-ca8e26ef74ef.png)
if you set height to 0 the div body element continually increases indefinitely. example code: 
```
	static function main () {
		
		var stage = new Stage (0, 0, 0xFFFFFF, App);
		js.Browser.document.body.appendChild (stage.element);
		
	}
```

**Comment by jgranick** [comment]
Currently, this only works if the parent DIV element has a hard width and height, otherwise it will keep resizing.

Happy for ideas/suggestions/code on making the behavior better here

**Comment by PXshadow** [comment]
Okay Thanks, I'll rethink of another way to create a responsive web page using npm 😄

**Comment by jgranick** [comment]
...and like I said, happy if we can think of a better way to handle the resizing logic. Currently it checks the parent element's width and height, which works well for when it has specific sizes, but can cause trouble if it's automatic
