### ISSUE TITLE
Inlining infinite loop in haxe 4

### ISSUE THREAD

**Issue by Misiur** [openfl/openfl#1888]
See https://github.com/HaxeFoundation/haxe/issues/6992

`TileContainer` extends `Tile`, and the `Tile#__setParentRender` causes an infinite inlining loop in haxe 4.

**Comment by jgranick** [comment]
How do I reproduce this? I don't see issues running BunnyMark in Haxe 4 RC3, even when adding a `TileContainer` to the sample. Thanks :smile:

**Comment by Gama11** [comment]
It's a regression on latest Haxe dev, doesn't affect preview 3.
