### ISSUE TITLE
Frame rate changes depending on monitor refresh rate on html5

### ISSUE THREAD

**Issue by vwr0527** [openfl/openfl#1896]
My monitor supports a 100hz refresh rate, which I use. I noticed that my game was playing faster when I compiled it to HTML5. So I devised a test.

```haxe
import openfl.display.Sprite;
import openfl.events.Event;
import haxe.Timer;

class Main extends Sprite 
{
	var counter = 0;
	var prevcount = 0;

	public function new() 
	{
		super();
		
		var timer:Timer = new Timer(1000);
		timer.run = function() { trace(counter - prevcount); prevcount = counter; }
		addEventListener(Event.ENTER_FRAME, update);
	}
	
	function update(e)
	{
		++counter;
	}
}
```
This should output the number of frames per second.

When my monitor refresh rate was 100, and the project framerate was set to 60, I got this output:

On flash:
```
Main.hx:15: 49
Main.hx:15: 61
Main.hx:15: 61
Main.hx:15: 61
```
On HTML5
```
Main.hx:15: 94
Main.hx:15: 100
Main.hx:15: 99
Main.hx:15: 100
```
On flash it's normal. On HTML5 it's updating 100 times per second.

Test # 2

Monitor refreshrate 100, project frame rate 50:
Flash output:
```
Main.hx:15: 47
Main.hx:15: 51
Main.hx:15: 50
Main.hx:15: 51
```
HTML5 output:
```
Main.hx:15: 44
Main.hx:15: 47
Main.hx:15: 45
Main.hx:15: 44
```
Close enough.

Test # 3 (control case)

Monitor refreshrate 60, project frame rate 60:
Flash output:
```
Main.hx:15: 52
Main.hx:15: 60
Main.hx:15: 61
Main.hx:15: 61
```
HTML5 output:
```
Main.hx:15: 57
Main.hx:15: 60
Main.hx:15: 60
Main.hx:15: 60
```
Works great!

Test # 4

Monitor refreshrate 60, project frame rate 50:
Flash output:
```
Main.hx:15: 47
Main.hx:15: 51
Main.hx:15: 51
Main.hx:15: 50
```
HTML5 output:
```
Main.hx:15: 30
Main.hx:15: 29
Main.hx:15: 30
Main.hx:15: 30
```
Huh?

Test # 5

Monitor refresh rate 60, project frame rate 100:
Flash output:
```
Main.hx:15: 49
Main.hx:15: 61
Main.hx:15: 61
Main.hx:15: 61
```
HTML5 output:
```
Main.hx:15: 62
Main.hx:15: 58
Main.hx:15: 60
Main.hx:15: 60
```
Ignores project framerate entirely, and uses monitor frame rate?

Test # 6

Monitor refresh rate 85, project frame rate 100:
Flash output:
```
Main.hx:15: 49
Main.hx:15: 60
Main.hx:15: 61
Main.hx:15: 61
```
HTML5 output:
```
Main.hx:15: 81
Main.hx:15: 85
Main.hx:15: 85
Main.hx:15: 85
```
Flash ignores all, uses 60, and HTML5 uses the monitor refresh rate.

Test # 7

In fact, this behavior can be noticed in real time. Set the project framerate to 60. I start the app with 60 hz on my monitor, then while it's running, I change my monitor refresh rate to 100 hz.
```
Main.hx:15: 62
Main.hx:15: 58
Main.hx:15: 60
Main.hx:15: 47
Main.hx:15: 60
Main.hx:15: 97
Main.hx:15: 100
Main.hx:15: 99
Main.hx:15: 100
```

This is pretty noticeable in my game. I can change my refresh rate, and immediately my game slows down or speeds up.

**Comment by jgranick** [comment]
`<window fps="" />` expects that 60+ means "full speed" on HTML5, less than that, it will drop frames to try and match the frame rate you request. Try `fps="30"` and see how it performs for you?

**Comment by vwr0527** [comment]
Thank you about that Lib.getTimer() hint! I somehow missed that!

(Monitor on 60hz) Dropping the project to 30 fps makes it hover between 21 and 22 fps on html5, oddly. It runs exactly 30 on any other target.

Monitor on 100hz, the html5 is running at a solid 25 fps. At 144hz, 28 fps.
