### ISSUE TITLE
Tilemap clipping option on openGL renderer

### ISSUE THREAD

**Issue by dustinaux** [openfl/openfl#1898]
The commit here [https://github.com/openfl/openfl/commit/f2b64368ad313396226398d21f72bf0c52468ad2](https://github.com/openfl/openfl/commit/f2b64368ad313396226398d21f72bf0c52468ad2)
appears to clip a tilemap to it's bounds. Before this commit I was enjoying the flexibility of moving tiles out of bounds or into negative coordinates if needed.

Would it be possible to have an option like `tilemap.clipping = false` to be able to place tiles out of bounds?

Is there any kind of performance drawback or bugs that can occur without the clipping mask in place?

**Comment by jgranick** [comment]
`Tilemap` is intended (right now) to clip on its bounds. On software targets (Flash, Cairo or canvas) it has to allocate a software surface based on the width/height. If we have no clipping, then these targets have to measure the tile contents and resize accordingly, which may really hurt performance.

Right now, the recommended way to "disable" clipping would be to use the full stage width/height for your tilemap dimensions. Happy to discuss on the forums, though, if we want to think of something else
