### ISSUE TITLE
TextField setSelection  Incorrect selection of cursor in Chinese content 

### ISSUE THREAD

**Issue by cjmxp** [openfl/openfl#1903]
TextField setSelection  Incorrect selection of cursor in Chinese content。
```
var test:TextField= new TextField()；
test.type=TextFieldType.INPUT;
test.text = "你好世界！"
test.setSelection(3,3)
```
![openflsetselection](https://user-images.githubusercontent.com/2855349/40638770-c585ec40-633f-11e8-9cba-255d61dce91a.png)

**Comment by MSGhero** [comment]
I think this is the same as #1805. I believe I know what the issue is, but I’m working on other things atm.

**Comment by cjmxp** [comment]
@MSGhero  Yes, it's really about Unicode

**Comment by MSGhero** [comment]
This is fixed on dev.
