### ISSUE TITLE
ByteArray performance improvements for starling cpp target 

### ISSUE THREAD

**Issue by maaniv** [openfl/openfl#1912]
Test on linux, standard starling demo benchmark.
Replace ByteArrayData readFloat function with
```
  public function readFloat ():Float {

    if (endian == LITTLE_ENDIAN) {

      if (position + 4 >= #if lime_bytes_length_getter l #else length #end) {

        throw new EOFError ();
        return 0;

      }

      var ret_val = getFloat(position);

      position += 4;

      return ret_val;

    } else {

      return FPHelper.i32ToFloat (readInt ());

    }

  }

```
Before replace:
  27316 with 60 fps
after:
  33621 with 60 fps
  38149 with 60 fps if made that function inline

**Comment by jgranick** [comment]
Done:

https://github.com/openfl/openfl/commit/10b8d4d932ef286d7de3e582bddbeaa9ed1fb554

I did `position++` first (and `position - 4` after) because I thought it might some of the benefits of being inlined (by not having a temporary variable) but I could be mistaken. Please feel free to test 😀
