### ISSUE TITLE
`cacheAsBitmap` display object with tilemap child dissapears when using a mask

### ISSUE THREAD

**Issue by Misiur** [openfl/openfl#1917]
```haxe
package;

import openfl.geom.Rectangle;
import openfl.display.Bitmap;
import openfl.display.BitmapData;
import openfl.display.Tile;
import openfl.display.Tileset;
import openfl.display.Tilemap;
import openfl.display.Sprite;

class Main extends Sprite
{    
    public function new()
    {
        super();

        var box = new Sprite();
        box.graphics.beginFill(0x800080, 1);
        box.graphics.drawRect(0, 0, 500, 500);
        box.graphics.endFill();
        box.cacheAsBitmap = true;
        addChild(box);

        var tileset = new Tileset(new BitmapData(25, 25, false, 0x0000FF), [new Rectangle(0, 0, 25, 25)]); 
        var tilemap = new Tilemap(100, 100, tileset);
        tilemap.addTile(new Tile());

        box.addChild(tilemap);

        var mask = new Bitmap(new BitmapData(500, 500, false, 0xFFFFFF));
        addChild(mask);

        stage.mask = mask;
    }
}
```
Works correctly when either:
1. `cacheAsBitmap` is disabled
2. The cached object has anything other than a tilemap as its child
3. Mask is disabled

Bisect shows [this commit](https://github.com/openfl/openfl/commit/0733fccc8539894189a66166848bd6ec872e6785) as the culprit, but there were some more changes to depth buffers so it might not be relevant anymore.

**Comment by Misiur** [comment]
Code in the first post no longer applies,
https://github.com/openfl/openfl/commit/7d5908051ed76eec00899a7eb5d0611c0946d9a4 or https://github.com/openfl/openfl/commit/faa058a8614097435775b6c60e9e8a62d6ccac62 fixed lack of rendering, however now the clipping mask applied to the parent of the tilemap does not apply to it when `cacheAsBitmap` is enabled.

```haxe
package;

import openfl.display.BitmapData;
import openfl.display.Tilemap;
import openfl.display.Tileset;
import openfl.display.Tile;
import openfl.display.Sprite;
class Main extends Sprite
{	
	public function new()
	{
		super();

		var bd = new BitmapData(200, 200, false, 0x0000FF);
		var ts = new Tileset(bd, [bd.rect]);
		var tm = new Tilemap(200, 200, ts);
		var t = new Tile(0);
		tm.addTile(t);

		var m = new Sprite();
		m.graphics.beginFill(0xFFFFFF);
		m.graphics.drawRect(0, 0, 100, 100);
		m.graphics.endFill();
		var s = new Sprite();
		s.graphics.beginFill(0xFF0000);
		s.graphics.drawRect(0, 0, 100, 100);
		s.graphics.endFill();
		s.mask = m;

		addChild(s);
		addChild(m);

		tm.x = 100;
		tm.y = 100;
		s.addChild(tm);

		this.cacheAsBitmap = true;
	}
}
```

Toggle `cacheAsBitmap` to see the difference

**Comment by jgranick** [comment]
Fixed! Thanks so much for the sample

https://github.com/openfl/openfl/commit/5fcfe0d9dca277f83afef45606e63b38b968f8f9

I misunderstood how stencil testing works with GL framebuffers. We need a stencil buffer on the FBO as well as our main one in order for it to work
