### ISSUE TITLE
Flash builds hang on preloader when running in browser over http

### ISSUE THREAD

**Issue by jan-niestadt** [openfl/openfl#1921]
It seems like any new Flash builds hang in the preloader stage when viewing them in a browser over http.

- Neither the default preloader nor custom preloaders seem to work
- Hangs only when viewing in a browser over http. Builds work normally in the local Flash player debugger or locally in the browser (in Firefox with about:config setting plugins.http_https_only set to false)
- Haxe 3.4.7, Lime 6.4.0, OpenFL 8.2.2, Flash player 30,0,0,113
- Tried openfl-samples BunnyMark and CustomPreloader as well as my own project
- Tried latest Firefox and Chrome
- Tried building on two different machines, one of which didn't have Haxe or Flash player installed yet
- Old builds (e.g. [/samples/bunny/ on openfl.org](http://www.openfl.org/samples/bunny/) or [my own project](http://gwtp.net/qwokgames/together-alone-2/)) still work properly, so the problem seems to be on the build side, not on the Flash player side

Here are the broken openfl-samples builds: http://gwtp.net/qwokgames/openfl-issue/

I'd like to do more debugging, but I'm not sure how to debug .swf running in the browser. Is there a way to get log information? (again, the problem doesn't occur in the Flash player debugger, so that's not an option)

**Comment by jgranick** [comment]
Thank you for reporting this issue! I believe this was resolved, I just tested the latest builds on an HTTP server, and it appears to be working fine (apart not wanting to allow Flash)
