### ISSUE TITLE
Npm version getter/setter broken

### ISSUE THREAD

**Issue by kevinresol** [openfl/openfl#1922]
Was trying to get `numControls` from `GameInputDevice` with this code `device.numControls`

But that won't work because getter/setter are haxe compile-time feature. Need to do `device.get_numControls()` for now

**Comment by jgranick** [comment]
Hi!

Is this still broken? In my tests, it appears that it should be working. Here's how it's implemented:

https://github.com/openfl/openfl/blob/develop/src/openfl/ui/GameInputDevice.hx#L53-L61

I'm going to close for now, but please open an issue if any properties are missing JS getter/setters :smile:
