### ISSUE TITLE
[HTML5] Fullscreen event not triggered when exiting

### ISSUE THREAD

**Issue by tour1st** [openfl/openfl#1927]
When exiting fullscreen (either when requested by a click, or by pressing ESC key), the FullScreenEvent is not triggered on HTML5.
Here is a sample code that works on FLASH, but not on HTML5 :

```haxe
import flash.Lib;
import flash.display.Sprite;
import flash.display.StageDisplayState;
import flash.events.MouseEvent;
import flash.events.FullScreenEvent;
import flash.text.TextField;

var stage:flash.display.Stage = Lib.current.stage;
var s:Sprite = new Sprite();
s.graphics.beginFill( 0xFF0000 );
s.graphics.drawRect( 0, 0, 800, 600 );
s.graphics.endFill();
s.graphics.beginFill( 0x0000FF );
s.graphics.drawRect( 50, 50, 700, 300 );
s.graphics.endFill();
var t:TextField = new TextField();
t.height = 600;
s.addChild( t );
stage.addEventListener( FullScreenEvent.FULL_SCREEN, function( e:FullScreenEvent )
	{
		trace( "FullScreenEvent=" + e.fullScreen );
		t.text += "FullScreenEvent=" + e.fullScreen + "\n";
	}
);
s.addEventListener( MouseEvent.MOUSE_DOWN, function( e:MouseEvent )
	{
		var fs:Bool = ( stage.displayState==StageDisplayState.NORMAL );
		stage.displayState = fs ? StageDisplayState.FULL_SCREEN : StageDisplayState.NORMAL;
	}
);
stage.addChild( s );
```

Click on the rectangle to switch between normal and fullscreen modes.
FLASH : text shows "FullScreenEvent=true" then "FullScreenEvent=false"
HTML5 : text shows "FullScreenEvent=false" (?) then nothing else

**Comment by YvesScherdin** [comment]
Since openfl version 8.3.0 the events seem to be fired reliably, but e.fullScreen in html5 is always the opposite to flash; true if it shall be false and vice versa.

**Comment by jgranick** [comment]
Thanks! It appears that OpenFL was handling this based on a resize event, but on HTML5, there wasn't necessarily a resize occurring. I've forced one for now

**Comment by tour1st** [comment]
I think it's now fixed, thanks to these commits :
15016c2f3250d56c4dca62c7f0d2d4e5de7ac681
2064678e2afd406041e7141aac672c6ac7eeb3bf
