### ISSUE TITLE
Some openfl.geom classes are missing API docs

### ISSUE THREAD

**Issue by Gama11** [openfl/openfl#1931]
http://api.openfl.org/openfl/geom/index.html - classes like `Matrix3D`, `Orientation3D`, `PerspectiveProjection`, etc don't have any API documentation.

There seem to be docs available on the official Adobe page, so this is probably just an oversight? Compare for instance:

- http://api.openfl.org/openfl/geom/Matrix3D.html
- https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/geom/Matrix3D.html

**Comment by jgranick** [comment]
Should be added now
