### ISSUE TITLE
Incorrect behavior of defaultTextFormat

### ISSUE THREAD

**Issue by MSGhero** [openfl/openfl#1935]
Setting `defaultTextFormat` also changes the first `TextFormat`. I believe this is because the `__textFormat` that gets modified in `dtf` is the exact same object as the initial format. Seems like there is a missing `__textFormat.clone()` or something.

**Comment by dustinaux** [comment]
I'm experiencing an issue that may be the same as this but I'm not sure... 

If I apply both a new color and different bold property to an existing TextField with a single TextFormat, it changes the color but bold is unchanged. I can however make every textfield in my game bold by default instead of unbolded which works, but then I cannot set an individual textfield to not bold.

Have you found any workarounds?

**Comment by MSGhero** [comment]
Can you share your relevant code? I’m also hitting an issue where I can’t unbold my text. Diving into the text code, I think it’s due to incorrect handling of TextFormat ranges, which is related to defaultTextFormat.

**Comment by dustinaux** [comment]
This reproduces it for me:

```
package;

import flash.text.TextFormat;
import openfl.display.Sprite;
import openfl.Lib;
import openfl.text.TextField;

class Main extends Sprite 
{

	public function new() 
	{
		super();
		
		var tf1:TextField = new TextField();
		var formatRedDefault = new TextFormat("_sans", 24, 0xffff0000);
		tf1.defaultTextFormat = formatRedDefault;
		tf1.width = 200;
		tf1.text = "red default";
		tf1.x = tf1.y = 50;
		this.addChild(tf1);
		
		var tf2:TextField = new TextField();
		var formatGreenBold = new TextFormat("_sans", 24, 0xff00ff00, true);
		tf2.defaultTextFormat = formatGreenBold;
		tf2.width = 200;
		tf2.text = "green bold";
		tf2.x = 50;
		tf2.y = 100;
		this.addChild(tf2);
		
		//var tf3:TextField = new TextField();
		//var formatBlueDefault = new TextFormat("_sans", 24, 0xff0000ff, false);
		//tf3.defaultTextFormat = formatBlueDefault;
		//tf3.width = 200;
		//tf3.text = "blue default";
		//tf3.x = 50;
		//tf3.y = 150;
		//this.addChild(tf3);
	}

}
```

Expected result should be normal red text and bold green text. Result is red and green text but both are bold. Uncomment the tf3 lines which should add unbolded blue text. This changes all textfields to unbold again. So colors work but bold seems to act as a global flag for all text somewhere. I haven't tested other properties.

**Comment by MSGhero** [comment]
Maybe not this issue then, but I had the same problem with bold. If it works on html5, then that’s honestly surprising... I was also testing cpp.

**Comment by MSGhero** [comment]
OP and first comment have both been fixed. I haven't seen any issues like 2nd comment in a while, but I'll keep an eye out
