### ISSUE TITLE
Drawing with BitmapData.draw() and a filter doesn't update more than once

### ISSUE THREAD

**Issue by francoisvn** [openfl/openfl#1945]
Latest OpenFL and Lime (8.3.0 and 6.4.0 respectively). I found a bug where the combination of:

- `Bitmap` with a filter, and
- Drawing to the associated `BitmapData` with `draw()` every frame,

Results in the visible display not updating after the first draw. If I override the `Bitmap` and set `force = true` for `__updateCacheBitmap` then it works again. The workaround I'm using now, which should be fractionally better is: `bitmap.filters[0].__renderDirty = true;`. If I remove the filter it updates again (but the filter is critical in my use case). It seems like a dirty flag somewhere is just not getting set correctly here.

FYI: yeah, for various reasons I need to `draw()` every frame, but it's been optimized so it's pretty quick, as long as it actually updates :D

**Comment by jgranick** [comment]
This should be resolved in the dev builds :smile:

Thank you!
