### ISSUE TITLE
Assets.getBitmapData returns lime.app.Future<BitmapData> and not BitmapData?

### ISSUE THREAD

**Issue by RubrumExPlaneta** [openfl/openfl#1946]
Nevermind, I was using loadBitmapData and not getBitmapData.

**Comment by jgranick** [comment]
You can use `Assets.loadBitmapData` like this:

```haxe
Assets.loadBitmapData ("image.png")
    .onProgress (function (bytesLoaded, bytesTotal) trace (bytesLoaded + "/" + bytesTotal))
    .onComplete (function (bitmapData) trace ("Image load complete!"))
    .onError (function (e) trace (e));
```

The progress and error callbacks are optional, but can be helpful. You'll want to at least have an `onComplete` handler to receive the `BitmapData` instance after it is loaded :smile:
