### ISSUE TITLE
Movieclip disappears when flipping with away3d

### ISSUE THREAD

**Issue by guruas3** [openfl/openfl#1957]
This is a weird bug i've found and it was hard to reproduce it.
When flipping movieclip by `scaleX = -1` or with matrix `matrix.a = -1` movieclip disappears for both HTML5 and Native. Flash is working fine. (it applies for both horizontal and vertical flipping)

It happens only if `view.render` is called on enterframe.
When disabling 3d it works fine.

This bug is present for more than 6 months and was tested with latest versions of openfl and lime from git.

Here is a sample project to reproduce it. (just click on the image to flip it)
[FlipBug.zip](https://github.com/openfl/openfl/files/2201732/FlipBug.zip)

**Comment by jgranick** [comment]
Fix: https://github.com/openfl/openfl/commit/b514f95b0f3b5ef2f469e840c06a02d434d7749a

We need to handle state between Stage3D and our core renderer better :sweat:

**Comment by guruas3** [comment]
Thank you!
