### ISSUE TITLE
Drawing a cached sprite not in the display tree causes invalid render

### ISSUE THREAD

**Issue by Misiur** [openfl/openfl#1968]
Prerequisites for the bug to occur:
1. A display object, which is not added to the main display object tree which has a display object child - I can confirm that a tilemap and normal sprite with graphics data will trigger this.
2. A bitmapdata on which `#disposeImage` is called, and onto which you draw the detached sprite
3. I'm not really certain why but I think only second draw after full render cycle causes the issue - maybe has to do with cache render?
(4). Toggling `cacheAsBitmap ` on the sprite in question will either make it not render at all (when false), or render upside down in the lower corner of the screen and with whole screen black (when true)/

Here's the simplest case I could come up with

```haxe
package;

import openfl.display.Bitmap;
import openfl.display.BitmapData;
import openfl.display.Sprite;
import openfl.events.Event;

class Main extends Sprite
{	
	public function new()
	{
		super();

		var foo = new Sprite();
		foo.graphics.beginFill(0x700070);
		foo.graphics.drawRect(0, 0, 200, 200);
		foo.graphics.endFill();
		var bar = new Sprite();
		bar.graphics.beginFill(0x007000);
		bar.graphics.drawRect(-50, -50, 100, 100);
		bar.graphics.endFill();
		bar.x = 150;
		bar.y = 150;
		foo.addChild(bar);

		foo.cacheAsBitmap = true;

		var foobarBD = new BitmapData(200, 200, false, 0x700707);
		var foobar = new Bitmap(foobarBD);
		foobarBD.disposeImage();
		addChild(foobar);
		foobarBD.draw(foo);
		addEventListener(Event.ENTER_FRAME, (e:Event) -> {
			foobarBD.draw(foo);
		});
	}
}
```

**Comment by mmauri** [comment]
I can confirm that this is also happening to us.
7.1.2 is working properly
8.3.0 is working properly
8.4.1 A transparent bitmap is drawn

**Comment by Misiur** [comment]
It was fixed recently, but be aware that the whole gl renderer context handling has been rewritten - check if latest git version works for you

**Comment by mmauri** [comment]
Thanks Misiur.
I know..., I opened another issue related to WebGL context lose with IE11, that is happening with the new renderer. For the time being we have switched to canvas.

**Comment by jgranick** [comment]
Looks good in current release :+1:
