### ISSUE TITLE
BitmapData.draw Unlike flash API

### ISSUE THREAD

**Issue by cjmxp** [openfl/openfl#1969]
@jgranick
A picture, B picture.
draw A Rectangle(10,10,50,50)to B point(20,20) Position

It's not the expected result。

```
var rect:Rectangle=new Rectangle(10,10,50,50);
var matrix:Matrix=new Matrix();
matrix.translate(20,20);
B.draw(A,matrix,null,null,rect);
```

**Comment by jgranick** [comment]
Works in current releases, thanks :grinning:
