### ISSUE TITLE
ByteArray, writeObject, Cannot return `null` from Void-function

### ISSUE THREAD

**Issue by Dimous** [openfl/openfl#1970]
return null at https://github.com/openfl/openfl/blob/develop/src/openfl/utils/ByteArray.hx#L927 causes error when compiling with latest nightly build 4.0.0-preview.4+dd5798e07

**Comment by Dimous** [comment]
https://github.com/openfl/openfl/blob/develop/src/openfl/utils/ByteArray.hx#L927

**Comment by Dimous** [comment]
resolved by d6c2e681c2398ede11437083a5b401a46949b335

**Comment by Gama11** [comment]
Ah, hadn't seen this issue. :)
