### ISSUE TITLE
Build Error when include .swf in project.xml

### ISSUE THREAD

**Issue by stein-D** [openfl/openfl#1977]
I try build samples project NyanCat with Openfl 8.4.0 and Lime 7.0.0 and I got this error : 
![1533893591850](https://user-images.githubusercontent.com/23498954/43950664-1ca4cdb6-9cbb-11e8-810a-bed6a9bc8b29.jpg)

**Comment by guruas3** [comment]
`openfl rebuild tools` should fix that

**Comment by stein-D** [comment]
Thanks, It's working now.
