### ISSUE TITLE
Stage 3D disappears in 8.4.0 release

### ISSUE THREAD

**Issue by guruas3** [openfl/openfl#1980]
It happens because of using the same stencil for both display list masks and stage 3d.

Here is a sample project to reproduce this issue.
[Stage3DBug.zip](https://github.com/openfl/openfl/files/2280197/Stage3DBug.zip)

**Comment by jgranick** [comment]
I just did a quick patch that fixes it, thinking about the longer-term fix to these GL state issues, though. Thank you :smile:
