### ISSUE TITLE
can't compile on openfl 8.4 (swf)

### ISSUE THREAD

**Issue by loudoweb** [openfl/openfl#1981]
```
Called from openfl/_internal/renderer/opengl/GLGraphics.hx line 43
Called from openfl/display/BitmapData.hx line 150
Called from openfl/display/BitmapData.hx line 300
Called from lime/graphics/Image.hx line 600
Called from lime/_internal/graphics/ImageDataUtil.hx line 394
Called from /usr/share/haxe/std/neko/Lib.hx line 42
Uncaught exception - load.c(237) : Failed to load library : lime.ndll
Error: Could not process asset libraries (swf)
Build halted with errors.

```

It doesn't compile only when using swf for what I know.

**Comment by shigimcp** [comment]
Temporary “solution”…

I used `haxelib set [project-name] [version]` to set the “current” version to the previous version.
To be safe, I did this for ALL the updates, including the samples.

Here’s a list of the projects I had to (re)set:
hxcpp: 3.4.188 [4.0.4]
lime-samples: 6.2.0 [7.0.0]
lime: 6.4.0 [7.0.0]
openfl-samples: 6.0.0 [8.4.0]
openfl: 8.2.2 8.3.0 [8.4.0]

RESULT:

> actuate: [1.8.7]
> as3hx: [1.0.6]
> box2d: [1.2.3]
> gsap: [1.0.4]
> hxcpp: [3.4.188] 4.0.4
> layout: [1.2.1]
> lime-samples: [6.2.0] 7.0.0
> lime: [6.4.0] 7.0.0
> openfl-samples: [6.0.0] 8.4.0
> openfl: 8.2.2 [8.3.0] 8.4.0
> 

NOTE the version numbers in brackets…

**Comment by jgranick** [comment]
Resolved, thank you :smile:
