### ISSUE TITLE
Flash target: 3 times of contstructor call

### ISSUE THREAD

**Issue by flashup** [openfl/openfl#1983]
Hi, after update to last libs versions (lime 7.0.0, openfl 8.4.0) i noticed that constructor of main app class was called 3 times.
If we add log in any test project `openfl-samples\8,4,0\haxelib\demos\TextMetrics\Source\Main.hx`
```haxe
public function new () {
	super ();
	Lib.trace("Constructor");
	Lib.current.stage.color = 0xA0A0A0;
...
```
and run `openfl test flash`
we will get following output:
```
$ openfl test flash
Lib.hx:282: Constructor
Lib.hx:282: Constructor
Lib.hx:282: Constructor
```
HTML5 target works fine.

**Comment by jgranick** [comment]
Try updating to OpenFL 8.4.1, released today

**Comment by flashup** [comment]
OpenFL 8.4.1 bug fixed.
Thanks!
