### ISSUE TITLE
TextField.htmlText splits words with html-formatting

### ISSUE THREAD

**Issue by YvesScherdin** [openfl/openfl#1984]
If a word at the textfield's border should be taken to the next line completely, but has some html-text-formatting applied, the word gets split.
The textfield adds all still-fitting letters of that word into that line and puts the rest into next line.

Example-Code:

```
myTextField.wordWrap = true;
myTextField.htmlText = "Test Teeeeest Teeeeeeeeeeestt <font color='#ffffff'>Teeeeeeeeeeeeeeeeeeeeeest</font>";
```

Result: (left side "with", right side "without" html-formatting)

![htmltextformattedwordlinebreak_short](https://user-images.githubusercontent.com/6424614/44104202-8b952c30-9fee-11e8-93bf-1ede7f489fb4.jpg)

**Comment by MSGhero** [comment]
Does it happen if you bold the text with a textformat instead?

**Comment by YvesScherdin** [comment]
yes. bold has no effect on the bug.

**Comment by YvesScherdin** [comment]
Here, I created a minimalistic app for testing:

[Test_TextFieldLineBreaks.zip](https://github.com/openfl/openfl/files/2289586/Test_TextFieldLineBreaks.zip)

**Comment by YvesScherdin** [comment]
And I also enhanced the app for testing... it provides live textfield content editing with a few test cases I encountered so far, which should make the testing easier, if that helps.

[Test_TextFieldLineBreaks.zip](https://github.com/openfl/openfl/files/2314604/Test_TextFieldLineBreaks.zip)

**Comment by MSGhero** [comment]
Oh I see. I might have fixed this in a PR I did already. It got merged and reverted, so I’ll have to re-PR it. It “broke” `defaultTextFormat`, which doesn’t behave correctly anyway, so I probably need to fix that first before my PR gets accepted.

**Comment by MSGhero** [comment]
I checked and #2003 fixes this, as far as I played with your example.

**Comment by YvesScherdin** [comment]
okay, cool. I tried this out with the development branch with my example. There it works for me too. Yet, I was unable to compile it with my bigger project. But I assume that just that branch is maybe not stable currently.

**Comment by MSGhero** [comment]
Is this one closed now?

**Comment by YvesScherdin** [comment]
Yes, thanks!
