### ISSUE TITLE
[html5] textField selectable bugs

### ISSUE THREAD

**Issue by DarthVan** [openfl/openfl#1986]
Hi! I tried to make selectable textField and apply glowFilter to it:

```
		var textField : TextField = new TextField();
		var textFormat : TextFormat = new TextFormat('Consolas', 14, 0xFF0000, false, false, null, null, null, 'center');
		textField.defaultTextFormat = textFormat;
		textField.embedFonts = true;
		textField.multiline = true;
		textField.wordWrap = true;
		textField.selectable = true;
		textField.mouseEnabled = true;
		textField.htmlText = text;
		textField.filters = [new GlowFilter(0xFF0000, 1, 4, 10, 0.75, toIndex + 1)];
		addChild(textField);
```
And its working like that:
![textfield_bugs](https://user-images.githubusercontent.com/5062893/44225749-f4430780-a196-11e8-99b1-437e2592edc6.gif)

I use html5 target, openFl 8.4.1 i lime 7.0.
ty!

ps: for reproduce can be used this sample project: https://www.dropbox.com/s/oy61fzww4gqmt9p/FilterBug.7z?dl=0

**Comment by bashaccount** [comment]
Its happening for any runtime changes on Textfields. 
eg., 
Scale in scale out text on roll over, both states stays.
Visible true and false fails
Changing text fails, both old and new text are stays.

Note : These all reproducible if the textfield have any filters like glow etc.,

**Comment by lmodlinski** [comment]
Selected text no longer stays on screen as presented on your gifs. I'm not sure whether that at least helps a bit with your issue. The only thing that can be improved in here is that offset between selection and base text with glow.

![1 selectable no selection](https://user-images.githubusercontent.com/5732018/47266723-db5e2600-d53a-11e8-9e40-219703985f3b.png)

![2 selectable selected all](https://user-images.githubusercontent.com/5732018/47266728-dc8f5300-d53a-11e8-8ab8-c58af60fa471.png)

![3 selectable deselected and selected patial](https://user-images.githubusercontent.com/5732018/47266730-de591680-d53a-11e8-8822-b6a5ac10f58c.png)

**Comment by MSGhero** [comment]
This is fixed in general, so I'll close this issue. There are edge cases here and there, but those are outside of the scope of this issue
