### ISSUE TITLE
The sound is played twice at the same time in HTML5

### ISSUE THREAD

**Issue by blacknotblack** [openfl/openfl#1988]
The sound is played twice at the same time in HTML5 when browser losing context for some time 

Open page, and roll up browser for 1 minute. Then click red circle to play sound and green to stop. And one copy of sound continue playing.
And code of sample:
class Main extends Sprite 
{
	var sound:Sound;
	var soundChannel:SoundChannel;
	var soundTransform:SoundTransform;
	var isPlaying:Bool;
		
	public function new() 
	{
		super();
		sound = Assets.getSound("assets/sound/winner.mp3");

		var sprite = new Sprite();
		sprite.graphics.beginFill(0x772200);
		sprite.graphics.drawCircle(100, 100, 20);
		addChild(sprite);
		sprite.addEventListener(MouseEvent.CLICK, function(e) {
			if (isPlaying) return;
			isPlaying = true;
			soundChannel = sound.play(0);
			soundChannel.addEventListener(Event.SOUND_COMPLETE, function(e) {
				isPlaying = false;
			}, true);
		});

		var sprite2 = new Sprite();
		sprite2.graphics.beginFill(0x007722);
		sprite2.graphics.drawCircle(200, 100, 20);
		addChild(sprite2);
		sprite2.addEventListener(MouseEvent.CLICK, function(e) {
			isPlaying = false;
			soundChannel.stop();
		});
	}
}

**Comment by blacknotblack** [comment]
It's problem with autoSuspend in howlerjs. May to set public settings of howler in the openfl context?

**Comment by blacknotblack** [comment]
Oh, it is possible to set via lime.media.howlerjs.Howler.autoSuspend

**Comment by jgranick** [comment]
Did you fix by setting to true, or false?
