### ISSUE TITLE
"manual" / "raw" installation and setup?

### ISSUE THREAD

**Issue by raould** [openfl/openfl#1989]
hi, I've used NME and OpenFL years ago via Haxe. Now I am trying to learn TypeScript. I already have a TS project set up with webpack etc., all just copied from some other project. I do not want to have to try to merge whatever the heck "yo openfl" does with what I already have. (That really is frankly either quite clueless, or quite disingenuous to say that is installing via "npm".)

Might anybody have instructions on how to add OpenFL to an already existing TS project? Thanks!

**Comment by raould** [comment]
oh hah found something way a the bottom of the very long README.md :-) 
https://github.com/openfl/openfl#using-openfl-with-npm

i think that would actually be good to mention at the end of option 1 on
http://www.openfl.org/download/

**Comment by jgranick** [comment]
If you haven't already, you may find looking at the OpenFL Samples for TypeScript helpful, as that has some example TS config and other values to help make sure that the imports work well:

https://github.com/openfl/openfl-samples-ts/tree/master/features/display/DisplayingABitmap

Happy to hear any further suggestions for improving the workflow, thanks :smile:
