### ISSUE TITLE
api docs != tutorials?

### ISSUE THREAD

**Issue by raould** [openfl/openfl#1990]
I am finding it disconcerting that the API docs don't seem to match what tutorials say to use at least for TypeScript. This leaves me somewhat at sea trying to figure things out. (Like, why a sprite has to be passed as App as a final argument for one concrete example of what I am trying to understand.) 

After a while of poking around I guess I figured out that there are (at least) _two completely separate sets of documentation_ and that I had better be lucky enough to figure that out and be looking at the right ones.

cf. http://api.openfl.org/openfl/display/Stage.html#new
vs.
http://www.openfl.org/learn/npm/api/classes/openfl.display.stage.html#constructor

I urge this distinction to somehow be better called out everywhere. E.g. all the docs in one group could say at the top of every page, "This is the doc set for {Haxe,TypeScript}. The other doc set for {TypeScript,Haxe} is available [here|link]."

**Comment by jgranick** [comment]
Thanks for the feedback

I'll try and see if we can figure out a way to handle the `Stage` constructor in the `api.openfl.org` documentation. This is the key difference between the NPM and Haxelib APIs -- the Haxelib version has no `Stage` constructor allowed.

That last argument is optional, it's the difference between the entry point _already_ being on the stage at the point of construction (`stage` is not `null`), or you could handle it after, like this

```ts
var stage = new Stage (550, 400);
var sprite = new Sprite ();
stage.addChild (sprite);
```
