### ISSUE TITLE
200$ Bounty. Huge performance difference on html5 with multiple meshes and merged in a single mesh.

### ISSUE THREAD

**Issue by xoopx** [openfl/openfl#1991]
Hi, with away3d, i used 200 balls and tested them as a single mesh, and as a separated meshes, with one material for all. On html5 android i got 60fps and 30fps. This is huge difference, every new mesh instance impacts performance. Here is profiler screen for both cases:
![44136769-b2b1f4e6-a076-11e8-94a3-8fd9bdea1aab](https://user-images.githubusercontent.com/13869467/44399949-19969380-a552-11e8-8107-3f65ce8db7e2.jpg)
Can it be optimized at least for static object?
I attached project with models in .max.
[PerformanceAway.zip](https://github.com/openfl/openfl/files/2306140/PerformanceAway.zip)

**Comment by xoopx** [comment]
I tried recreating this 200 balls with same geometry and material, no performance difference.

**Comment by xdeadmonkx** [comment]
Any way 200 different spheres is 200 draw calls

**Comment by jgranick** [comment]
Tracking here, thanks!

https://community.openfl.org/t/bounty-for-away3d-performance-optimization/11054
