### ISSUE TITLE
Documentation link redirects to foreign webpage

### ISSUE THREAD

**Issue by RNanoware** [openfl/openfl#1992]
I believe that the link should either be updated or removed, especially considering what seems to be adult content on the current destination.

https://github.com/openfl/openfl/blob/7532822d13e3ef4e0ac49d1626873ec0de56d45e/src/openfl/events/Event.hx#L40

**Comment by RNanoware** [comment]
Is this the appropriate link? http://tedpatrick.com/2005/07/19/flash-player-mental-model-the-elastic-racetrack/

**Comment by jgranick** [comment]
Goodness! Thank you, this file should be updated now. It's broken in Adobe's documentation too 😱
