### ISSUE TITLE
class function length on HTML5

### ISSUE THREAD

**Issue by flashup** [openfl/openfl#1994]
Hi, i faced in with strange bug in Starling library, when i didn't get progress number in onProgress callback from class `starling.assets.AssetManager`.

I've found that `starling.utils.Execute` counts number of arguments 0, but is must be 1 and pass `undefined` to callback.
Problem is in `untyped func.length;`

What is more, it works properly for anonymous functions.
Example:
```haxe
// in some class
private function classFunc(pr:Float) {
}

private function bar() {
  function anonymFunc(pr:Float) {
  }

  #if (flash || html5)
  var lenAnonym = untyped anonymFunc.length;
  var lenClass = untyped classFunc.length;
  Log.trace("lenAnonym = " + lenAnonym);
  Log.trace("lenClass = " + lenClass);
  #end
}
```
On HTML5 we'll get:
```
lenAnonym = 1
lenClass = 0
```
On Flash we'll get:
```
lenAnonym = 1
lenClass = 1
```
Thanks.

**Comment by jgranick** [comment]
This appears to be why:

https://try.haxe.org/#eAAfA

Should we just make it #if flash only in `starling.utils.Execute`?

Perhaps it could be `if (length == 0) length = -1` for JS
