### ISSUE TITLE
drawtriangles with uvs >1 or <0 different result when drawn to bitmapdata

### ISSUE THREAD

**Issue by Helgiii** [openfl/openfl#2001]
I made a kaleidoscope (kscope) and animated uv coords to make motion effect..
all looked nice but when I implemented screenshot functionality(draw to bitmapdata) it sometimes gave a different picture.. it turned out that when rendering to bitmapdata.. uv coords are clamped to [0,1] so picture differs.. sooo

so again I use a Sprite to draw kscope
beginBitmapFill
drawtriangles
endBitmapfill
add it to scene and it looks nice, but when I render this sprite to bitmapdata like this
mybitmapdata->draw(kscopeSprite)
it gives wrong result, i.e. the rendered image differes from whats drawn on the sprite

currently I just clamp uv coords myself always
I dont quite remember but I think this issue is present on both flash and html5 targets, on html5 for sure

**Comment by jgranick** [comment]
I believe this is resolved:

https://github.com/openfl/openfl/issues/2002

Let me know if you still have problems :smile:
