### ISSUE TITLE
graphics.drawTriangles + Bitmapdata.draw different results on flash,html5,native

### ISSUE THREAD

**Issue by guruas3** [openfl/openfl#2002]
I was testing old my samples from github issues and discovered that example from #1818 has a different output on 3 platforms(flash, html and windows)

Here are the screenshots
![2018-09-07_1455](https://user-images.githubusercontent.com/981231/45220349-21726980-b2ae-11e8-8248-f2abea285d27.png)

And here is the example project
[DisplayingABitmap.zip](https://github.com/openfl/openfl/files/2361098/DisplayingABitmap.zip)

This could be related to previous #2001 issue

**Comment by jgranick** [comment]
Looks correct in current release :smile:
