### ISSUE TITLE
[HTML5] Context3D.drawToBitmapData produces transparent BitmapData

### ISSUE THREAD

**Issue by mayakwd** [openfl/openfl#2007]
During developing Starling app I've faced with the problem of drawing starling sprites to `BitmapData. DisplayObject.drawToBitmapData` produces  transparent `BitmapData`. By the help of @peteshand we've discovered that `context3D.drawToBitmapData` producing same result on HTML5 target. 

@peteshand  created sample to reproduce this issue: [drawToBitmapdata.zip](https://github.com/openfl/openfl/files/2378373/drawToBitmapdata.zip)

Issue in starling project: https://github.com/openfl/starling/issues/110

**Comment by peteshand** [comment]
ok, down grading to Lime 6.4.0 and OpenFL 8.3.0 resolves the issue, so it must be a regression in the latest versions.

**Comment by peteshand** [comment]
One difference I've noticed within the drawToBitmapData function is the following line:

OpenFL 8.3.0
`var image = window.renderer.readPixels ();`

OpenFL 8.4.1
`var image = #if (lime >= "7.0.0") window.readPixels () #else window.renderer.readPixels () #end;`

**Comment by peteshand** [comment]
This issue has been resolved via this PR:
https://github.com/openfl/lime/pull/1240

**Comment by mayakwd** [comment]
Thank you, Pete! I'll try to compile with develop branch to check if it's resolved :-)

**Comment by mayakwd** [comment]
I done testing with latest develop + current starling version. I got total mess with masks and canvas rendering: 
1. Quad masks that are not added to displaylist stopped working, their positions attached to stage instead of local position of target, most content with masks is not displaying at all.
2. Rendering of canvas blinks like it's being erased every second frame.

Drawing into bitmapData still produces transparent pixels.

**Comment by jgranick** [comment]
I just built your sample, it appears to look the same on Flash, Neko and HTML5, using current latest dev of Lime, OpenFL and Starling.

It's tan and white and first, and then clicking any of the other buttons makes it tan instead, and it stays tan over a black background no matter what

**Comment by peteshand** [comment]
@mayakwd I'm guessing the Masking / Canvas problems you're seeing are a different issue to the drawToBitmapdata issue right? if so it might make sense to create a separate issue.

**Comment by mayakwd** [comment]
@peteshand, yup, I just need more time, to extract some samples, to illustrate new issues. Closing this.
