### ISSUE TITLE
lime 6.4.0 openfl 8.3.0 build android fail

### ISSUE THREAD

**Issue by cjmxp** [openfl/openfl#2008]
lime 6.4.0 openfl 8.3.0 build android fail
hxcpp 4.0.4

android SDK android-19
android NDK android-ndk-r13b

arm-linux-androideabi-g++: error: ws2_32.lib: No such file or directory
arm-linux-androideabi-g++: error: advapi32.lib: No such file or directory
arm-linux-androideabi-g++: error: crypt32.lib: No such file or directory
arm-linux-androideabi-g++: error: ws2_32.lib: No such file or directory
Error: Error while running command

**Comment by jgranick** [comment]
I'm not really sure what could cause this. Those are Windows libraries, so perhaps you have a native extension that needs to be updated to support Android better?
