### ISSUE TITLE
WebGL context lost in IE11 when it automatically switches to software renderer

### ISSUE THREAD

**Issue by mmauri** [openfl/openfl#2011]
Tested with OpenFl 8.4.1 & OpenFL development branch as of today.
Lime 7.0.

We are having a problem with IE11 when throwing it a lot of WebGL redraws (when maximizing a window for example and the layout is recalculated).
Chrome & Edge are working OK.

Unfortunately IE11 is still the default browser for big corps.

IE11 console log shows:
![image](https://user-images.githubusercontent.com/8304473/45875323-a0c86880-bd97-11e8-9f27-bbdf90284f5b.png)

**Comment by jgranick** [comment]
Resizing PiratePig works properly here on the latest development versions of OpenFL and Lime (and should also work with the latest releases). However, I have been getting `InvalidStateError` messages from howler.js, I created a patch to the upstream repository, and committed a patched version here:

https://github.com/openfl/lime/commit/efdc2fd3602f02c85168587848cf81f224b63987

**Comment by mmauri** [comment]
Thanks we don't embed howler.
But anyway I just upgraded openfl and it worked!!
openFL  8.5.1
Lime 7.1.0

In the interim we switched back to -Dcanvas, now we got to revert it ;)
Thank you very much Joshua!

**Comment by zebontheweb** [comment]
https://support.microsoft.com/fr-fr/help/3099259/update-to-add-a-setting-to-disable-500-msec-time-limit-for-webgl-frame

**Comment by rvanderspuy** [comment]
This can happen in IE 11 if anything in your code is toggling canvas visibility.
