### ISSUE TITLE
Update trouble

### ISSUE THREAD

**Issue by hereticByte** [openfl/openfl#2012]
Hello Joshua,

as I have already posted, I have trouble with the update of **openFl** to the current version _8.4.1_

I have updated the **lime lib** as well.

The trouble is caused by the **debugger plugin for IntelliJ** _(by Eric Bishton)_ based on the **hxcpp-debugger** version _1.1.0_. It's suppose not be the current version but excactly that specific version (otherwise the debugger, called by the plugin, would not work anymore).

If there is something, I should ask Eric for to update his plug-in and to make it compatible again with _openFl_, please let me know. Some hard facts would be great, as I do not have any insights...

Kind regards 
Arnim

**Comment by jgranick** [comment]
I'm trying to move the issue here:

https://github.com/HaxeFoundation/intellij-haxe/issues/884

Hopefully we can try and figure out more about what is going on

**Comment by EricBishton** [comment]
@hereticByte - Arnim, Where have you "already posted" the problem you are seeing?

**Comment by hereticByte** [comment]
@EricBishton 
Hello Eric,
let's continue the discussion on the new issue url.
