### ISSUE TITLE
Dragonbones Meshes disappeared in 8.5.0, HTML5, WebGL Renderer

### ISSUE THREAD

**Issue by lmodlinski** [openfl/openfl#2014]
Hi,

I've just updated OpenFL and Lime to 8.5.0 and 7.1.0 from 8.4.1 and 7.0.0 respectively and I've found out that part of my skeleton animations where meshes were used to modify image in Dragonbones editor disappeared with:

`GL ERROR :GL_INVALID_OPERATION : glDrawElements: range out of bounds for buffer`

warning message all over the browser console. Dragonbones library is 5.0.0.

Kind regards,
Łukasz

**Comment by jgranick** [comment]
Fixed by 8f1a476f7ce3078bf742cfda5963bc04362c6a8d :smile:
