### ISSUE TITLE
drawtriangles fails on openfl 8.5 html5, glDrawElements: range out of bounds for buffer

### ISSUE THREAD

**Issue by Helgiii** [openfl/openfl#2016]
sample code http://oleg-vorontsov.com/tests/haxe/drawtriangles-1/drawtriangles.zip
succeded in both html5/flash in prev version of openfl.
on openfl8.5 flash is ok, html5 fails with error:
GL ERROR :GL_INVALID_OPERATION : glDrawElements: range out of bounds for buffer

**Comment by jgranick** [comment]
Fixed by https://github.com/openfl/openfl/commit/8f1a476f7ce3078bf742cfda5963bc04362c6a8d

Thanks for the sample! :smile:
