### ISSUE TITLE
CPP/Neko does not show caret if input text field text is zero length

### ISSUE THREAD

**Issue by ianharrigan** [openfl/openfl#202]
Consider: 

```haxe
var tf:TextField = new TextField();
tf.x = tf.y = 100;
tf.border = true;
tf.type = TextFieldType.INPUT;
//tf.text = "Something";
addChild(tf);
```

When clicking the input field on cpp/neko (and initial text is zero length), then no caret appears indicating focus. Once a character is typed then caret appears. This causes problems with users not knowing they are being prompted for input. Having a single character for the text alleviates the issue, ie:

```haxe
tf.text = " ";
```

**Comment by shadowofsoul** [comment]
FYI, i could reproduce this problem, and in android, is not solvable by setting up a text nor by writing.  the caret never appears.
