### ISSUE TITLE
Wrong render of some fonts on linux chromium

### ISSUE THREAD

**Issue by maaniv** [openfl/openfl#2022]
On linux chromium cut top part of string occurs for some fonts:
![screenshot_20181005_090427](https://user-images.githubusercontent.com/6612937/46518656-f879d000-c87d-11e8-9bb9-63f1eac2d04c.png)
On windows, ios and linux firefox all is ok. Attach of simple project with font for reproduction:
[wrong-font-render.zip](https://github.com/openfl/openfl/files/2449112/wrong-font-render.zip)

**Comment by jgranick** [comment]
I think this is an issue with the font

![image](https://user-images.githubusercontent.com/833997/46704257-082b4880-cbdf-11e8-9f18-c925e1540bb2.png)

Here's the preview for the font on macOS:

![image](https://user-images.githubusercontent.com/833997/46704263-12e5dd80-cbdf-11e8-842c-e5d4df5440c3.png)

I am getting the same result on Flash and Neko as well
