### ISSUE TITLE
OpenFL 8.6.0 VideoTextures are no longer working

### ISSUE THREAD

**Issue by peteshand** [openfl/openfl#2027]
Hey there

After upgrading to 8.6.0 it seems that VideoTextures no longer work.
I've been investigating, however am yet to identify the root cause.

I have however create a barebones example to demonstrate the issue.

Openfl 8.4.1 and Lime 7.0.0 works as expected, an example can be viewed here:
http://peteshand.net/openfl/videoTexture/8.4.1/

Openfl 8.6.0 and Lime 7.1.1 throw a heap of WebGL expections, an example can be viewed here:
http://peteshand.net/openfl/videoTexture/8.6.0/

Source files for this test can be found here:
https://github.com/peteshand/openfl-tests

**Comment by jgranick** [comment]
Thanks for the code sample

The `openfl-samples` repository has a "PlayingVideo" sample that does work, so I think that the error here may be related to being a `CubeTexture`

Hope this helps identify the offending code, I'll try and look soon if I can, thanks for the sample code :smile:

**Comment by jgranick** [comment]
Found it, sample works now

**Comment by peteshand** [comment]
Awesome, thanks for taking a look
