### ISSUE TITLE
OpenFL 8.6.0 fullscreen problem with cpp target

### ISSUE THREAD

**Issue by GoKidGames** [openfl/openfl#2029]
On windows cpp target full screen is wrong. It resizes the game and window but crops the game to what the window size was before going full screen. It worked on 8.5.1 and older.

**Comment by GoKidGames** [comment]
I should note that this happened on a flixel project and I use FlxG.fullscreen to go fullscreen. Sorry, I don't have a pure openfl example.

**Comment by jgranick** [comment]
Fixed by 8c69ef48252e02157b4b893882e6ac34036620ff, thanks :smile:
