### ISSUE TITLE
[html5] Regression bug on textfield in recent openfl (BOUNTY 100$)

### ISSUE THREAD

**Issue by loudoweb** [openfl/openfl#2031]
If I use a Textfield from a swf, I have a regression bug (something that was working before but not anymore).
As soon as I try on Ipad or mobile, the bottom of the textfield disappears.

Result (left old working openfl, right recent not working openfl)
![bug_swf_textfield](https://user-images.githubusercontent.com/165190/46952709-ee30b080-d08b-11e8-97f1-fca8be62782c.jpg)

To be more precise, if I test on my browser with a resolution of 1024x768 it is working, but if I chose Ipad2 (same resolution) the bug occurs, so I think it has something to do with mobile. (I think the browser uses a different pixel density and different user-agent when I chose Ipad in my Adaptive View from the Developer Console).

This worked on openfl 7.1.2, lime 6.2.0.
This is not working on openfl 8.4.1, lime 7.0.0. This is also not working on openfl 8.6.0 and lime 7.1.1 and on openfl 8.3.0 and lime 6.4.0.
I did not tested on other version so I don't know when the bug was introduced.

I didn't test from a Textfield made by code, so maybe it has not something to do with swf.

Resolution of my app if it can help:
2048x1536

**Comment by loudoweb** [comment]
I've made a sample project so you can test.
[bountyTextfieldCrop.zip](https://github.com/openfl/openfl/files/2479275/bountyTextfieldCrop.zip)

Look at the p of ipsum. It's cutted.

![image](https://user-images.githubusercontent.com/165190/46959256-e8db6200-d09b-11e8-9eb7-d18e5be189d9.png)

I'll gladly pay 100$ :dollar:  for this bug fix :)

**Comment by loudoweb** [comment]
I confirm it occurs on all textfields not only from swf.

**Comment by jgranick** [comment]
I just sent a PM on Discord. Have a great day!

**Comment by loudoweb** [comment]
@Misiur oh? Seems ok! Great! I will make further test by tomorrow.

**Comment by jgranick** [comment]
Ah, I bet its from this:

https://github.com/openfl/openfl/blob/master/src/openfl/_internal/text/TextEngine.hx#L305-L320

See, the font might have the real ascent encoded. This occurs when we embed fonts, now.

Using a webfont from CSS won't have this data, and the hack makes the text look closer to correct. 

I guess we need a way to determine whether a hack is needed. Let me look at this

**Comment by jgranick** [comment]
I think I might have fixed this

I added

```haxe
@:access(openfl.text.TextFormat)
```

and

https://github.com/openfl/openfl/blob/eebd766df44ab802cf724bd318067b56d5411148/src/openfl/_internal/renderer/canvas/CanvasTextField.hx#L208-L217

I think this accounts for both cases

**Comment by loudoweb** [comment]
Ok I understand what the hack was for. Thanks ! I'll test that!
