### ISSUE TITLE
SOH binary word in openFl code, remove it plz

### ISSUE THREAD

**Issue by DarthVan** [openfl/openfl#2035]
Hi!
I found it in openfl.display.DisplayObject:
![2018-10-17 12 58 04](https://user-images.githubusercontent.com/5062893/47079406-0c261e80-d20e-11e8-9ad9-9e648a98df52.png)

I use FlashDevelop 5.3.4.217 and OpenFl 8.6.2

ty!

**Comment by jgranick** [comment]
I can't find this in any of the files on the repository. Could you please try identifying which file exactly has a control character in it?

For example, if it is https://github.com/openfl/openfl/blob/develop/src/openfl/display/DisplayObject.hx, try downloading the "raw" version to your machine, and double check if it has the character. If not, let's figure out what's going on. If it does, please remove it in your editor, then click the "Edit" button back in Github online to edit the document, then paste your version and click the remaining buttons to turn that into a pull request

**Comment by DarthVan** [comment]
Yes, you're right :)
I downloaded raw code and no 'SOH' symbols in it. Also, i reupdated my openFl lib via console:
![2018-10-17 22 20 26](https://user-images.githubusercontent.com/5062893/47111221-9ba5ee80-d25b-11e8-9543-681c344d2eac.png)
When i opend it in FD, it looks fine now. It seems, FD sometimes inserts 'SOH' character at random place, i already wrote an issue before... to FD repo: https://github.com/fdorg/flashdevelop/issues

thanks:)

**Comment by DarthVan** [comment]
I tried to downgrade manualy my openFl from 8.6.2 → 8.6.1 and reupdated it:
![2018-10-17 22 42 36](https://user-images.githubusercontent.com/5062893/47112653-a5c9ec00-d25f-11e8-8dea-170e5e03c055.png)

When i see openfl.display.DisplayObject via notepad++, it looks fine, also i downloaded all repo as *.zip and there all fine too:
![2018-10-17 22 46 38](https://user-images.githubusercontent.com/5062893/47112693-c42fe780-d25f-11e8-902a-1f5366fa9848.png)

But when i launched FD and uses ctrl+click at import row 'openfl.display.DisplayObject;' to see it code, 'SOH' was added again at that placce :)
![2018-10-17 12 58 04](https://user-images.githubusercontent.com/5062893/47112732-ddd12f00-d25f-11e8-8aab-33ddeb0bed08.png)

Idk, why it happens, i wrote an issue before, to FD thread, sometimes FD inserts 'SOH' character at random place.. but only when i edit something in file or renaming/replacing. Now i just opend a class and got 'SOH' in it...

Think, this is a FD's problem, not openFl, thanks :)
