### ISSUE TITLE
CPP/Neko: Incorrect chars on input text field

### ISSUE THREAD

**Issue by ianharrigan** [openfl/openfl#204]
Eg: Impossible to enter an "=" into an input text field via keyboard (using a spanish keyboard layout).

If i change my layout to english layout then i can enter an "=" symbol (by using the "¡" key), but does not correspond to what the keyboard displays. 

(Note: can be reproduced with on screen keyboard in windows 8)

**Comment by Tumetsu** [comment]
Is there any progress on this issue since last year?
