### ISSUE TITLE
-Ddom not working

### ISSUE THREAD

**Issue by hx02** [openfl/openfl#2067]
Since 8.4.1 (8.5.x and 8.6.x), -Ddom (<haxedef name="dom" if="html5" />) doesn't seem to work anymore. The target of HTML5 is always canvas.

**Comment by hx02** [comment]
Just saw you close this. Did the way to specify DOM target change in 8.4? In 8.3, I define <haxedef name='dom'> in my project.xml. If I compile the project by 8.3, everything seems to be fine. If I can compile the same project.xml using 8.4 and up, the project gets compiled to canvas target. Any tip?

**Comment by jgranick** [comment]
I think you could override this file:

https://github.com/openfl/openfl/blob/master/assets/templates/haxe/ApplicationMain.hx#L86

and use "dom" for the context type
