### ISSUE TITLE
keyDown event showing wrong keyCOde on Mac HTML5

### ISSUE THREAD

**Issue by hx02** [openfl/openfl#2068]
openfl 8.3 on  HTML5 target, if press CMD key alone, event generated shows:
command key: true
keyCode: 291  ('[')

It's unclear why it shows keyCode to be 291 which is clearly a bug. Pressing CMD and '[' together also produces the same keyCode.

**Comment by jgranick** [comment]
It looks like we have improvements to the key code handling on HTML5, that's not released yet, in the Lime project:

https://github.com/openfl/lime/commit/4a8125e03641d1dc7bf18b6e6d779b1d24e7d3cb#diff-5f4ea7a1bc77d2611bd3abce960fc726

I'd be happy to know/hear if this resolves your issue, or if we still need additional cases to handle this on macOS

**Comment by hx02** [comment]
thanks! I will let you know once this enhancement is released with Lime
