### ISSUE TITLE
Multiline Text with Chinese Characters results in a freeze on latest builds

### ISSUE THREAD

**Issue by dustinaux** [openfl/openfl#2073]
(Windows target)

I'm using:
haxe 4.0.0 preview 5
latest dev openfl and lime
hxcpp 4.0.4

See the following edit of the TextMetrics sample for the freeze:

[TextMetrics.zip](https://github.com/openfl/openfl/files/2587973/TextMetrics.zip)

There is an incomplete list of commented out lines that cause the crash after a multiline text field is set with enough chinese characters to extend to a second line. 

However either just a single line of chinese characters, or multi-line latin characters both do work.

I tried to take a look but am too unfamiliar with the code and latest commits to make any progress on solving it.

**Comment by dustinaux** [comment]
Update: An infinite loop occurs with the while loop in `src/openfl/_internal/text/TextEngine.hx` at line 1106 from this commit: [https://github.com/openfl/openfl/commit/ab2b1c1330e803c02e2338a7d9dfde9f4341f65b](https://github.com/openfl/openfl/commit/ab2b1c1330e803c02e2338a7d9dfde9f4341f65b)

I've reverted TextEngine.hx to just before that commit for my own use currently since I'm not familiar with that code enough to figure out a solution - maybe @MSGhero can take a look?

**Comment by MSGhero** [comment]
Yeah I’ll check it out today or tomorrow.

**Comment by MSGhero** [comment]
@dustinaux Are there any spaces in your Chinese text? Where I start debugging depends on if it's a Unicode issue or a lack of spaces issue. I'll get to it tonight

**Comment by MSGhero** [comment]
Ok try this: f95903a675fab3864d0b9f172cf2013122a9200f

**Comment by dustinaux** [comment]
That fixed it, thank you!

**Comment by MSGhero** [comment]
Cool, definitely let me know if you find other issues in the text layout area. We pushed my changes to dev knowing that not every edge case could be taken care of without spending forever on the PR. So this kind of testing is super helpful, thanks!
