### ISSUE TITLE
MovieClip with Bitmaps not playing properly

### ISSUE THREAD

**Issue by jackie-t** [openfl/openfl#2076]
I don't know exactly how to reproduce this, but this is a minimum breaking example of an animation not playing properly:

http://69.162.85.87/AnimTest/Export/html5/bin/

Note the huge jump a second or so in.

If you check the flash file (http://69.162.85.87/AnimTest/Assets/test.swf, source http://69.162.85.87/AnimTest/Assets/test.fla), you'll see that the animation should barely move.

If 
- I replace the bitmap with a Shape, it works (it has to be a bitmap for it to break)
- I replace the bitmap in each Anim* movieclip with the same bitmap, it works (it has to be different bitmaps for it to break).

Any ideas?

You can download the full directory from http://69.162.85.87/AnimTest.tgz

**Comment by jackie-t** [comment]
From what I can see, the SWFLiteExporter finds placeTag.matrix set for the first object:

ShapeBitmapExporter.hx:89: - processNewBitmap: BitmapID=1, transform: matrix(1, 0, 0, 1, -22.5, -18.5)
SWFLiteExporter.hx:591: - - Object Create (2), null
SWFLiteExporter.hx:609: - - - Matrix matrix(1, 0, 0, 1, 22.5, 26.5)
SWFLiteExporter.hx:551: - Frame 1
SWFLiteExporter.hx:551: - Frame 2

But not for the other two:
SWFLiteExporter.hx:551: - Frame 61
ShapeBitmapExporter.hx:89: - processNewBitmap: BitmapID=3, transform: matrix(1, 0, 0, 1, -22.5, -18.5)
SWFLiteExporter.hx:591: - - Object Create (4), null
SWFLiteExporter.hx:551: - Frame 62
ShapeBitmapExporter.hx:89: - processNewBitmap: BitmapID=5, transform: matrix(1, 0, 0, 1, -22.5, -18.5)
SWFLiteExporter.hx:591: - - Object Create (6), null
SWFLiteExporter.hx:551: - Frame 63
SWFLiteExporter.hx:551: - Frame 64


Seems like an error in tag parsing / handling?

**Comment by jackie-t** [comment]
This appears to be an oversight in format.swf.timeline.Frame - and the classes that touch it.

in placeObject:

> 				// A character id is defined:
>				// This means that the previous character is replaced 
>				// (possible transforms defined in previous frames are discarded)

That's actually incorrect. If a character id is defined, the transforms are not necessarily discarded. If the move- and the character-bits are set, you mustn't discard the transforms (unless a matrix is set), and rather carry them over.

There might be better ways to fix this, but I hacked in the following into the processDisplayListTag function of format.swf.SWFTimelineContainer, which will fix the problem.

>			case TagPlaceObject.TYPE, TagPlaceObject2.TYPE, TagPlaceObject3.TYPE:
>				var po_tag:TagPlaceObject = cast tag;
>				if (po_tag.hasMove && po_tag.hasCharacter && !po_tag.hasMatrix) {
>					var oldFrameObject = currentFrame.objects.get(po_tag.depth);
>					if (oldFrameObject != null) {
>						var oldTag = tags[(oldFrameObject.lastModifiedAtIndex == 0 ? oldFrameObject.placedAtIndex : oldFrameObject.lastModifiedAtIndex)];
>						if (oldTag != null) {
>							switch(cast (oldTag.type, Int)) {
>								case TagPlaceObject.TYPE, TagPlaceObject2.TYPE, TagPlaceObject3.TYPE:
>									var oldPo_tag:TagPlaceObject = cast oldTag;
>									po_tag.matrix = oldPo_tag.matrix;
>							}
>						}
>					}
>				}
>				currentFrame.placeObject(currentTagIndex, cast tag);

Cleaner code appreciated of course, but I wanted to make sure this actually fixes it before claiming I know the fix ;)

**Comment by jgranick** [comment]
Thank you!

I've just made improvements to resolve SWF class generation for your sample SWF, and also merged your fixes. At first, I thought we should look at a solution in the SWF Lite exporter instead of the underlying SWF parsing, but this works and I'm much happier seeing your sample animation work correctly than fussing too much :wink:

**Comment by jackie-t** [comment]
As long as it works, I'm happy with either solution. Thanks! We'll find all those bugs :D
