### ISSUE TITLE
how  to openfl  abstract class TypeScript declaration file generator  ? 

### ISSUE THREAD

**Issue by longde123** [openfl/openfl#2077]
i try https://github.com/nadako/hxtsdgen/

but err~d.ts~abstract class

**Comment by jgranick** [comment]
I have used https://github.com/kevinresol/hxgenjs before, it does not have a robust type generator (it generates everything as dynamics) but that's been suitable for me to get things building.

I'd like to see a combination of both projects, better/more accurate types, while leaving dynamics in place when things are unknown.

A Haxe abstract does not translate to TypeScript properly, if you rely on the automatic type conversion features and such, but generally a Haxe abstract boils down to a more fundamental type, which would/could work in Typescript. For example, `abstract MyInt(Int) from Int to Int` could be handled as a plain integer, again, so long as you don't need any of the extra fancy features Haxe abstracts offer

Are you generating TypeScript declarations for OpenFL, or something else? We already have an NPM release of OpenFL with full TypeScript definitions (created by hand)
