### ISSUE TITLE
WebGL: drawElements - Feedback loop detected with ColorMatrixFilter

### ISSUE THREAD

**Issue by jackie-t** [openfl/openfl#2079]
When using ColorMatrixFilters on lime: [7.1.1] openfl: [8.6.4], I run in the following error:

Chrome:
> [.WebGL-000000B06C63C820]GL ERROR :GL_INVALID_OPERATION : glDrawElements: Source and destination textures of the draw are the same.

Firefox:
> Error: WebGL warning: drawElements: Feedback loop detected between tex target 0x0de1, tex unit 0, levels 0-0; and framebuffer attachment 0x8ce0, level 0.

Chrome doesn't give a line, but Firefox refers to Context3D.hx:486.

The content then begins to flicker or stops displaying entirely.
Once this error occurs, it occurs again on every animation frame, until the maximum reported error count is exceeded. 

This appears to be timing based - I usually manage to trigger it with the debug console open, clicking around on the website, and dragging around - sometimes switching to a different app, and coming back a bit later. It seems to be more prone to occurring the more clips / ColorMatrixFilters I use. Adding a trace before and after the line that Firefox mentions stops the error from occurring, but of course crashes the browser due to the large amount of lines in the console.

Example:
http://69.162.85.87/CMTest/Export/html5/bin/

Source:
[CMTest.zip](https://github.com/openfl/openfl/files/2610741/CMTest.zip)

**Comment by jackie-t** [comment]
As mentioned in the report, you need to open the console, click around in the website, tab out and in for the error to occur.

**Comment by jgranick** [comment]
I can't reproduce this here, using the latest OpenFL develop branch. Perhaps this is something we fixed?

**Comment by jackie-t** [comment]
That would be awesome let me try real quick. So update openfl to dev?

**Comment by jackie-t** [comment]
It really does seem to be fixed in the development build! That's a relief. Thank you!
