### ISSUE TITLE
[HTML5] openfl.display.SimpleButton cant be disabled

### ISSUE THREAD

**Issue by DarthVan** [openfl/openfl#2081]
Hi! I tried to disable a button, but code

`button.enabled = false;`

has no effect...

also, i tried to do this:

`button.mouseEnabled = false;`

but it brings no effect too.

OpenFl/Lime 8.6.4/7.1.1
Thanks!

**Comment by DarthVan** [comment]
upd: i solved this problem by adding an if() to __hitTest methood:
```
@:noCompletion private override function __hitTest (x:Float, y:Float, shapeFlag:Bool, stack:Array<DisplayObject>, interactiveOnly:Bool, hitObject:DisplayObject):Bool {
		
		if (!enabled || !mouseEnabled)
			return false;
```
but not sure, that its good, and will not bring an another problems :)

**Comment by m0rkeulv** [comment]
Not sure if that `!enabled` part of your if check is a good idea idea. it would most likely break  mouse events. in Flash you can still add eventListeners and listen to mouse events even if the  button.enabled is set to false.  this boolean only disable the buttonState (up, over, down) change as far as i know. 
(this us useful if you want to show a tool-tip etc for a disabled button)

`__hitTest`  is an "internal" function as far as i can tell,  and its used  by Stage in __onMouse which again test all children  with `if (__children[i].__hitTest (x, y, shapeFlag, stack, false, cast __children[i])) {` so by overriding it and adding your if check you effectively prevents stage from detecting hits and dispatching MouseEvents.  

(note that i have not tested this, its just how i interpretate the code)

**Comment by m0rkeulv** [comment]
I have done some quick testing, and it looks like its `mouseEnabled ` that's not working properly.

I would suggest moving the following line out of the `if-else` (maybe put it above the first `if`) so that `interactiveOnly && !MouseEnabled` is checked in all  hitTest situations.

```
if (!hitObject.visible || __isMask || (interactiveOnly && !mouseEnabled)) return false;
```
https://github.com/openfl/openfl/blob/develop/src/openfl/display/SimpleButton.hx#L307

any thoughts @jgranick

**Comment by DarthVan** [comment]
Thanks, it ineresting... I did as u say, and it works fine too for me.
But i have to use "mouseEnabled = false" to disable a button instead "enabled = false". Aafter this it stops to change states and dispatch events.
So, "enabled" property still bugged, and do nothing :)
Sry for my english...

**Comment by m0rkeulv** [comment]
`enabled = false` should prevent it from changing states unless you have implemented this yourself using eventListeners.

**Comment by DarthVan** [comment]
Got it, thanks :)

**Comment by jgranick** [comment]
Could you take a look at my fixes here:

https://github.com/openfl/openfl/commit/f4939c044e04b36f3589611d68b218c61638bfc3

...and see if that behaves as you want?

drmelzie on the forums also has a tweak, but I'm not sure if this is needed on top of my change, or if it was a workaround without my changes:

https://community.openfl.org/t/how-to-stop-simplebutton-animation-when-enabled-false/11130/9?u=singmajesty

Let me know what you find!

**Comment by jgranick** [comment]
On the same topic, just merged this pull, which looks like good changes for `movieClip.buttonMode = true` having button behavior:

https://github.com/openfl/openfl/pull/2083

**Comment by DarthVan** [comment]
Ok, i tested it on html5 target. [](https://github.com/openfl/openfl/commit/f4939c044e04b36f3589611d68b218c61638bfc3)
Prop "enabled = false" stops changing states,"mouseEnabled = false" disables event dispatching :)
Think, its good now. Will you include this fix to the next release?
Thanks!

**Comment by jgranick** [comment]
Yep! This will be in the next release :smile:
