### ISSUE TITLE
[HTML5] textField.htmlText ignores <li>, <ul> tags

### ISSUE THREAD

**Issue by DarthVan** [openfl/openfl#2082]
Hi again:)

If this is not a bug, can someone add this tags to the next releases?

thanks!

**Comment by joshtynjala** [comment]
Closing issue because `<li>` has been implemented in htmlText.

openfl/openfl@39052789f7b644d62273230ad748ea5f9344d12e
openfl/openfl@8db59ad478125cd4d62203bf8c588b94bb7685d5
