### ISSUE TITLE
Alpha set from Animate doesn't work properly with canvas

### ISSUE THREAD

**Issue by dpomier** [openfl/openfl#2084]
Here a comparaison between canvas and webgl:

![swf-alpha-bug](https://user-images.githubusercontent.com/18221324/49237574-c3fa3e80-f3fe-11e8-9478-17736ae4cfd2.png)

Built with openfl `8.6.4`/`dev` and lime `7.1.1`

You can find the test project here: [_alphaTest.zip](https://github.com/openfl/openfl/files/2630065/_alphaTest.zip)

Setting the alpha property via script afterwards (at run-time) doesn't fix the difference between canvas and webgl/flash. You can test this by pressing `space` in the attached test project.

**Comment by jgranick** [comment]
Thanks, I found two fixes.

First, we're now ignoring alpha multipliers when doing a cacheAsBitmap (which is required for color transforms). 

I also noticed that there was a difference between Cairo and canvas where canvas did not respect the renderer's alpha setting, which is used for cacheAsBitmap.

Altogether, WebGL, GL, cairo and canvas are looking the same for me now :smile:

**Comment by dpomier** [comment]
Great 👍
