### ISSUE TITLE
BlendMode ignored on MovieClip with Bitmap on HTML5 target

### ISSUE THREAD

**Issue by jackie-t** [openfl/openfl#2088]
When I load a MovieClip with a bitmap that has, for example, BlendMode.ADD applied to it, it will display as if there was no BlendMode.

See http://69.162.85.87/AddTest/Export/html5/bin/
The cherry should be really light, but instead is completely solid. This is how Flash displays it:

![image](https://user-images.githubusercontent.com/17299143/49333095-3020a200-f5b9-11e8-8584-abe58965800a.png)

If you use Shapes within the MovieClip, the BlendMode does work - just with Bitmaps it doesn't seem to.
The second cherry is a MovieClip within the addition layer, that has also BlendMode.ADD applied to it, which should display the same way.

The bottom MovieClip has BlendMode.ADD applied to the entire MovieClip (set from within openfl), which is also ignored.

I put the source here: [AddTest.zip](https://github.com/openfl/openfl/files/2636337/AddTest.zip)

Any ideas what might be happening?

**Comment by jackie-t** [comment]
This might be a bug in DisplayObject.hx: 

`				if (__blendMode == null || __blendMode == NORMAL) {`
`					// TODO: Handle multiple blend modes better`
`					__worldBlendMode = renderParent.__blendMode;`
`				} else {`
`					__worldBlendMode = __blendMode;`
`				}`

I assume the intention is to carry the blendMode down to the leaf, in that case you will lose the __blendMode after one recursion:

`DisplayObject.hx:1896:  - Blend Mode: Me=[object MovieClip], mine=add / RenderParent=[object MovieClip], theirs=normal -> result: add`
`DisplayObject.hx:1896:  - Blend Mode: Me=[object MovieClip], mine=normal / RenderParent=[object MovieClip], theirs=add -> result: add`
`DisplayObject.hx:1896:  - Blend Mode: Me=[object Bitmap], mine=normal / RenderParent=[object MovieClip], theirs=normal -> result: normal`
...
`Context3DBitmap.hx:40: Final blend mode = normal Bitmap = [object Bitmap]`

Changing

`					__worldBlendMode = renderParent.__blendMode;`
to
`					__worldBlendMode = renderParent.__worldBlendMode;`

will take the BlendMode from the parent, and draw the child in the same BlendMode.

I'm not sure the general approach is correct, however. Wouldn't all objects at a certain nesting level need to be drawn in their correct blendMode, and then only the resulting group would need to be drawn in addition mode? 

Like, for example, if you have two opaque objects overlapping each other, then it would make a difference if (1) they're both BlendMode.ADD (you could see one of the objects behind the other), or (2) they're both BlendMode.NORMAL and their parent is BlendMode.ADD (you couldn't see the second object behind the first, even through the result is "see-through").

Flash does handle that correctly, OpenFL doesn't seem to (with this quick-fix it's displayed as described in (1) - without this quick-fix BlendMode.ADD is discarded altogether, which shows up as even more wrong).

![image](https://user-images.githubusercontent.com/17299143/49651618-0095ed80-fa30-11e8-835e-e9c02a6bf7d4.png)

OpenFL displays both as shown in the left - without the fix here it doesn't display any of them as BlendMode.ADD.

 It would be more correct to first draw all normal children elsewhere, and then draw them on increasingly bigger surfaces, applying the BlendModes as needed, until the top level, which would then be the final "surface" that is displayed. I probably explained it badly, but I hope it's good enough for folk to understand what I mean.

**Comment by jgranick** [comment]
Thank you! That's a really good catch on `__blendMode` instead of `__worldBlendMode`, I've applied that fix to the `develop` branch.

Well, the difference is we would need to render to an intermediate object first in order to apply a blend mode to an entire group of objects. This occurs when you do `cacheAsBitmap = true` on an object. We (perhaps?) can do something similar with the `LAYER` mode, but its definitely a performance hit. The only other alternative would be if we somehow batched the draws into one call and removed overlapping pixels, but I don't know how practical it would be to try

**Comment by jackie-t** [comment]
Yeah, I've skimmed through the code and noticed `cacheAsBitmap = true` is somewhat more along the lines of what I was expecting to see. I can definitely live with setting that to true when needed - especially because usually the difference would be too subtle to justify a major performance hit. 

For correctness' sake, you'd only need to do it in certain situations anyway (multiple blend modes - e.g. multiply and addition - as you go deeper, or more than one object in a different blend mode than what you deviated from `NORMAL `with, if they overlap). You wouldn't have to do it if there's just one object (it gets the blend mode that you set, this would cover a Bitmap within a MovieClip that's set to `ADD`).

Removing overlapping pixels sounds like opening another can of worms, seeing that objects might be arbitrarily complex (with alpha values and all that).

There still seems to be an issue with multiple objects (only some seem to get `BlendMode.ADD`, some stay at normal), but that could be something about the `MovieClip` too. I'll report back once I isolate this more.

**Comment by jackie-t** [comment]
Seems to be working fine. I'll let you know if I run into anything else.
