### ISSUE TITLE
Error in MovieClip animation

### ISSUE THREAD

**Issue by 0xA3** [openfl/openfl#2091]
This issue may be related to #1702 but I have a very simple example file that may help to find the bugs more quickly.

I created a MovieClip that is used as a button with a normal state and a rollover state. 
This is the expected behaviour. Works in Flash and HTML5
![flash](https://user-images.githubusercontent.com/33229542/49515825-4c159380-f898-11e8-984a-8b5bac0cbce3.gif)

But is wrong in CPP and Neko. The rectangle disappears after the first rollover
![cpp](https://user-images.githubusercontent.com/33229542/49515935-8da63e80-f898-11e8-98da-3dbcedb73a63.gif)

My library versions are: openfl 8.7.0 and lime 7.2.0

I think it has something to do with the normal and rollover states of the rectangle being only in one frame of the movieclip.
![layers](https://user-images.githubusercontent.com/33229542/49516395-cf83b480-f899-11e8-8f7d-0d55a6059e33.png)

This is the link to the [source files](https://www.dropbox.com/s/c8a49h0cwj0ujsz/FrameTest.zip?dl=0)

Thank you

**Comment by m0rkeulv** [comment]
took a quick look at this one, looks to me like the  graphics  is never set dirty after the first render or something related to the __dirty property.  CairoGraphics render method is always getting graphics.__dirty = false.

**Comment by m0rkeulv** [comment]
@0xA3 The fix I wrote yesterday should now be in the develop branch.  If you're using Haxe it should be fairly easy to check out the develop branch if you want to test it :)

Just follow the instructions in the README.md
https://github.com/openfl/openfl#development-builds

Or out use haxelib git feature 
https://lib.haxe.org/documentation/using-haxelib/#git

**Comment by 0xA3** [comment]
I just upgraded to OpenFl 8.8.0 and Lime 7.2.1. Now it works on all targets.
Thanks
