### ISSUE TITLE
TextField shifted upwards in Chrome

### ISSUE THREAD

**Issue by ValentinRadoi** [openfl/openfl#2101]
Hello!

I've noticed that after some Chrome update, all the textfields in my HTML5 app where shifted upwards with a couple of pixels (I'm quite sure it wasn't like that some time ago, but I can't point to the exact moment when this happened). Checking the same build in Firefox and Edge confirmed that this happens in Chrome only.

I've made a simple test app to prove this. Given the code below:

```
import openfl.display.Sprite;
import openfl.text.TextField;
import openfl.text.TextFormat;
import openfl.text.TextFormatAlign;

class Main extends Sprite
{
	public function new()
	{
		super();
		
		var format:TextFormat = new TextFormat();
		format.font = "Verdana";
		format.align = TextFormatAlign.LEFT;
		format.size = 30;
		
		var txtText:TextField = new TextField();
		txtText.defaultTextFormat = format;
		txtText.border = true;
		txtText.text = "Hello World";
		txtText.width = 200;
		txtText.height = 50;
		txtText.x = 50;
		txtText.y = 50;
		addChild(txtText);
		
		var textArea:Sprite = new Sprite();
		textArea.graphics.beginFill(0xFF0000);
		textArea.graphics.drawRect(0, 0, txtText.textWidth, txtText.textHeight);
		textArea.graphics.endFill();
		textArea.x = txtText.x;
		textArea.y = txtText.y;
		addChildAt(textArea, 0);
	}
}
```

The output looks like this https://prnt.sc/luf61q 
 
![download](https://user-images.githubusercontent.com/4222110/49935923-134e6d80-fedb-11e8-9189-f2779dd1f086.png)

in Chrome, Firefox, Edge and stand-alone Flash Player (in this order, from left to right). You can see that Firefox, Edge and Flash Player display the text almost identically, closer to the bottom edge of the red area, which is given by `drawRect(0, 0, txtText.textWidth, txtText.textHeight)`, while Chrome renders it closer to the upper edge. They all return the same txtText.textWidth and txtText.textHeight values, it's the positioning of the text inside that space that's different.

Now we can argue which one is the "correct" rendering, but the main problem is that they differ and that means textfields look misaligned at runtime, in our apps, in one browser or the other.

I've tried with different fonts and text formats configurations, they all behave the same. I'm using OpenFL 8.7.0 and Lime 7.2.0, but the issue is present with older versions too.

Does this has anything to do with font ascent/descent? What can we do to fix it? Ideally for me it should look like in Flash Player everywhere, because I'm using Animate CC to setup the GUI layout for my game and that's where I load my positioning information. Haven't tested on mobile yet, but I suspect Chrome is the only odd one.

Incidentally I'm using Starling, but the problem is the same there too for TrueTypeCompositor textfields, as they are rendered to texture by OpenFL, that's why I'm posting the issue here.

Thanks!

**Comment by Neborya** [comment]
The results will be different in Chrome on Windows, Chrome on iOS, and Chrome on Linux (which will also depend on DE).
I wonder, if text rendering is a general HTML5 issue, or OpenFL is lacking accurate font metrics detection.

**Comment by dpomier** [comment]
I found similar results only with the version 71.0.x of Chrome on Windows

**Comment by jgranick** [comment]
Can anyone help test the latest development build of OpenFL? It includes a fix that may resolve this for Chrome and for other browsers that behave similarly:

https://github.com/openfl/openfl/commit/b81a38328217c4f42943a1e7cc58b78a201f132d

**Comment by lmodlinski** [comment]
I can confirm that for Chrome 71 texts looks OK. I've also noticed that some texts were shifted down on iOS, Chrome 70 and now they're in correct position. Can't post screenshots but maybe someone else can confirm so we're sure they're OK.

**Comment by Neborya** [comment]
I can confirm too.

Side effect: text underline got shifted upwards (close to the text).

**Comment by Neborya** [comment]
For underline distance to be identical with Flash:
`var y = Math.floor (group.offsetY + scrollY + group.ascent - bounds.y) + 0.5;`
->
`var y = Math.floor (group.offsetY + scrollY + group.ascent - bounds.y) + 2.5;`

**Comment by ValentinRadoi** [comment]
Yes, I can confirm as well that the text is not shifted upwards anymore in Chrome after the fix. Thanks!

![screenshot_1](https://user-images.githubusercontent.com/4222110/50173171-59eb0000-02ff-11e9-9eb3-8bf4fbdcb818.png)
