### ISSUE TITLE
HTML5 Canvas BitmapData.draw ignores smoothing in Chrome

### ISSUE THREAD

**Issue by YvesScherdin** [openfl/openfl#2102]
In a small test application we use a Tilemap to draw a image. The image itself is scaled and drawn onto a tileset's BitmapData.
The quality differs significantly between Chrome and other browsers. Chrome ignores smoothing.

![bugreport_smoothing](https://user-images.githubusercontent.com/6424614/50001638-c4b5d780-ff9d-11e8-88ed-f81fd5df390b.jpg)

Here you have a Test-Application.

[Test_TilemapTextureQuality.zip](https://github.com/openfl/openfl/files/2679936/Test_TilemapTextureQuality.zip)

When playing around a bit, I found out that the value context.imageSmoothingEnabled is falsely false in all browsers, but only in Chrome it takes effect.

I investigated further: renderer.__allowSmoothing and context.imageSmoothingEnabled are async in BitmapData::draw

In BitmapData::draw, Line 997 a CanvasRenderer instance is created.
`var renderer = new CanvasRenderer (image.buffer.__srcContext);`

The default value of __allowSmoothing is true, but in the context it is still false.

In the following canvas-drawing calls the code assumes, that the default value is true. In the class CanvasBitmap the flag context.imageSmoothingEnabled will only be reset if either renderer.__allowSmoothing or bitmap.smoothing is false, which will never be the case. So the flag context.imageSmoothingEnabled will stay false while renderer.__allowSmoothing is true all the time. And image.smoothing being true is ignored.

CanvasBitmap::render (...)
```
if (!renderer.__allowSmoothing || !bitmap.smoothing) {
	
	context.imageSmoothingEnabled = false;
	
}

// [...]  drawing code

if (!renderer.__allowSmoothing || !bitmap.smoothing) {
	
	context.imageSmoothingEnabled = true;
	
}
```

----

Simple solution:

Also calling applySmoothing with the passed context directly after creating the renderer.

```
var renderer = new CanvasRenderer (image.buffer.__srcContext);
renderer.applySmoothing (image.buffer.__srcContext, renderer.__allowSmoothing);
```

or within CanvasRenderer's constructor add:

```
if (context != null)
	context.applySmoothing (context, __allowSmoothing);
```

This solves the issue for Chrome, and in other browsers it still works well, also with webgl.

**Comment by Egis86** [comment]
YvesScherdin, thank you very much! Now my bitmap font scales perfect in chrome :)
