### ISSUE TITLE
HTML5 word wrap issues

### ISSUE THREAD

**Issue by Neborya** [openfl/openfl#2103]
I've encountered 2 issues with multiline text in HTML5.

1)  Spacing between lines is inconsistent. For example, with Verdana size 12 lines will sometimes be 7px and sometimes 8px away from each other.

![text](https://user-images.githubusercontent.com/27854329/50052220-ffe90f80-0131-11e9-8c6e-f690ae71bdc4.png)

2) Wrapping of words of another color can break line formatting, see the example below (click to trigger).

```
import openfl.display.Sprite;
import openfl.text.TextField;

class Main extends Sprite {
	
	public function new () {
		
		super ();
		
		var textField = new TextField ();
		textField.multiline = true;
		textField.wordWrap = true;
		textField.htmlText = "<font face='Verdana' size='12' color='#FFFF00'>1111 222 33333333 444444 5 666666666 AAAAA-BBBBB and some other characters.</font>";
		textField.width = 250;
		addChild(textField);
		
		var border:Sprite = new Sprite();
		border.graphics.lineStyle(5, 0xFFFF00);
		border.graphics.drawRect(textField.width, 0, 0, 500);
		addChild(border);
		
		stage.addEventListener ("click", function (_) {
			textField.htmlText = "<font face='Verdana' size='12' color='#FFFF00'>1111 222 33333333 444444 5 666666666 <font color='#FF0000'>AAAAA-BBBBB</font> and some other characters.</font>";
		});
	}
}
```

**Comment by MSGhero** [comment]
1) 12pt Verdana has non-integer ascents and descents, so it's likely a floating point subpixel thing. On OpenFL's end, every line is sent to the browser the same, and there is no rounding/etc involved.

2) What does "break line formatting" mean?

**Comment by MSGhero** [comment]
Assuming what I saw is what you saw, try the latest dev OpenFL out: https://github.com/openfl/openfl/commit/50bc7066379c3ad13ac7750d43033e514d2613e3

**Comment by Neborya** [comment]
Thanks, it is now fixed.

>and there is no rounding/etc involved.

I see. Well, texts with multiple lines would definitely look better if some kind of rounding was performed then, as there is no such issue with Flash target.

**Comment by MSGhero** [comment]
@jgranick what do you think here? Rendering is a step out of my domain

**Comment by jgranick** [comment]
It probably comes from the "ascent" and "descent" calculations (which really should be ascender/descender, which are a bit different) in here:

https://github.com/openfl/openfl/blob/master/src/openfl/_internal/text/TextEngine.hx

It factors into calculations like:

https://github.com/openfl/openfl/blob/master/src/openfl/_internal/text/TextEngine.hx#L741-L742

Then it is now used in the canvas rendering, like here:

https://github.com/openfl/openfl/blob/master/src/openfl/_internal/renderer/canvas/CanvasTextField.hx#L189

**Comment by Neborya** [comment]
I tested with another font, it also has this 1px difference.

![px](https://user-images.githubusercontent.com/27854329/50284710-f251c380-046a-11e9-9341-622be9dc9e9c.png)

> It would be interesting to see what `ascent` and `descent` values we are getting, and consider if it should be a bit different.

In https://github.com/openfl/openfl/blob/master/src/openfl/_internal/renderer/canvas/CanvasTextField.hx#L189 all `ascent` values are integers. `offsetY` is integer for the 1st line and float for all subsequent lines.

I found that I could fix it by changing https://github.com/openfl/openfl/blob/master/src/openfl/_internal/text/TextEngine.hx#L1240 to
`offsetY += Math.floor(maxHeightValue);`

**Comment by MSGhero** [comment]
The first offsetY is always 2, so it’s no surprise all of the rest are floats. We could round the lineHeights, but we’d have to see what Flash does since that may be an incorrect thing to do. 

Flash aligns everything on twips, so maybe render code should too. That wouldn’t completely remove all decimals like you’re suggesting but place it on the nearest 0.05 multiple.

**Comment by MSGhero** [comment]
Based on `textField.getCharBoundaries()`, it looks like Flash puts text on integer pixels. So your fix would work, and I can PR that since I know TextEngine well, but I'll have to look at `ceil` vs `floor` vs `round`. Fonts in Flash and CPP don't scale the same way, so we might just be able to pick whichever.

**Comment by MSGhero** [comment]
https://try.haxe.org/#3FDa2

In addition to integer line heights, it does also look like Flash renders text on ints or something. The try.haxe example shows a visible difference between a tf at `y=10.7` and another at `y=10.8` and no difference between 10.7 and 10.6. I have a commit for integer heights, but this is also something to look at.

![image](https://user-images.githubusercontent.com/5033927/50501261-7b916900-0a1c-11e9-9e6f-1ff492231c7d.png)
