### ISSUE TITLE
Builds for mac looks upscaled

### ISSUE THREAD

**Issue by Tembac** [openfl/openfl#2111]
openfl-samples: [8.7.0]
openfl: [8.7.0]
lime: [7.2.0]

I'm testing flixel and openfl demos on a mac book pro using lime test mac. 

![image](https://user-images.githubusercontent.com/2808285/50489953-546d7400-09e9-11e9-9fda-3da84ba6f541.png)

All the demos look upscaled and the window only shows the lower left corner.

Pirate pig:
![image](https://user-images.githubusercontent.com/2808285/50489972-72d36f80-09e9-11e9-9760-fab2193b8303.png)

MODE:
![image](https://user-images.githubusercontent.com/2808285/50489978-7961e700-09e9-11e9-8962-ec5aa14dcbd7.png)

BunnyMark:
![image](https://user-images.githubusercontent.com/2808285/50489981-7f57c800-09e9-11e9-94d6-28d231b09102.png)

On the flixel forums more people are having the same issue.

http://forum.haxeflixel.com/topic/890/mac-builds-are-displaying-the-image-wrong

**Comment by jgranick** [comment]
Does this work differently if you allow high DPI on these samples?

I think the option is `openfl test mac --window-allow-high-dpi=true`

Are you testing the macOS target, Neko, Flash or another target? Thank you :smile:

**Comment by Tembac** [comment]
Yes, it works fine using that command! I think it is not on the documentation. I'm testing mac os target.

**Comment by jgranick** [comment]
This should be resolved with recent Lime development updates (fixes for macOS Mojave by upgrading SDL to 2.0.9) :smile:
