### ISSUE TITLE
Crash in OpenFL TextLayout when HaxeFlixel debugger is resized after stage gets focus

### ISSUE THREAD

**Issue by Tw1ddle** [openfl/openfl#2126]
I get this crash when printing text out to the HaxeFlixel FlxDebugger console in a debug build of an Android app.

I'm calling _FlxG.log.warn_ and _FlxG.log.notice_ which print text to the graphical console. At the same time, I have a popover window separate from OpenFL stuff (a Google Mobile Ads SDK GDPR consent popover) taking focus from the OpenFL stage.

When I dismiss the popover, focus is returned to the OpenFL stage and it crashes in OpenFL's internal TextLayout code with this logcat output:

>  E/HXCPP   (14391): Called from hxcpp::__hxcpp_main
> E/HXCPP   (14391): Called from ApplicationMain::main ApplicationMain.hx line 30
> E/HXCPP   (14391): Called from ApplicationMain::create ApplicationMain.hx line 147
> E/HXCPP   (14391): Called from lime.app.Application::exec lime/app/Application.hx line 167
> E/HXCPP   (14391): Called from lime._internal.backend.native.NativeApplication::exec lime/_internal/backend/native/NativeApplication.hx line 163
> E/HXCPP   (14391): Called from lime._internal.backend.native.NativeApplication::handleWindowEvent lime/_internal/backend/native/NativeApplication.hx line 643
> E/HXCPP   (14391): Called from lime.app._Event_Void_Void::dispatch lime/_internal/macros/EventMacro.hx line 101
> E/HXCPP   (14391): Called from openfl.display.Stage::__addWindow openfl/display/Stage.hx line 1564
> E/HXCPP   (14391): Called from openfl.display.Stage::onWindowFocusIn openfl/display/Stage.hx line 1327
> E/HXCPP   (14391): Called from openfl.display.Stage::__broadcastEvent openfl/display/Stage.hx line 1606
> E/HXCPP   (14391): Called from openfl.display.DisplayObject::__dispatch openfl/display/DisplayObject.hx line 1237
> E/HXCPP   (14391): Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 443
> E/HXCPP   (14391): Called from flixel.FlxGame::onFocus flixel/FlxGame.hx line 389
> E/HXCPP   (14391): Called from flixel.FlxGame::onResize flixel/FlxGame.hx line 461
> E/HXCPP   (14391): Called from flixel.FlxGame::resizeGame flixel/FlxGame.hx line 474
> E/HXCPP   (14391): Called from flixel.system.debug.FlxDebugger::onResize flixel/system/debug/FlxDebugger.hx line 329
> E/HXCPP   (14391): Called from flixel.system.debug.FlxDebugger::resetLayout flixel/system/debug/FlxDebugger.hx line 312
> E/HXCPP   (14391): Called from openfl.display.DisplayObject::get_height openfl/display/DisplayObject.hx line 2674
> E/HXCPP   (14391): Called from openfl.display.DisplayObject::__getLocalBounds openfl/display/DisplayObject.hx line 1404
> E/HXCPP   (14391): Called from openfl.display.DisplayObjectContainer::__getBounds openfl/display/DisplayObjectContainer.hx line 761
> E/HXCPP   (14391): Called from openfl.text.TextField::__getBounds openfl/text/TextField.hx line 1727
> E/HXCPP   (14391): Called from openfl.text.TextField::__updateLayout openfl/text/TextField.hx line 2379
> E/HXCPP   (14391): Called from openfl._internal.text.TextEngine::update openfl/_internal/text/TextEngine.hx line 1854
> E/HXCPP   (14391): Called from openfl._internal.text.TextEngine::getLayoutGroups openfl/_internal/text/TextEngine.hx line 1424
> E/HXCPP   (14391): Called from openfl._internal.text.TextLayout::get_positions openfl/_internal/text/TextLayout.hx line 206
> E/HXCPP   (14391): Called from openfl._internal.text.TextLayout::__position openfl/_internal/text/TextLayout.hx line 182
> E/Exception(14391): Null Object Reference

I don't have a minimal repro case yet, but I can work on one. I am currently printing a lot of stuff to the FlxDebugger console, a few dozen lines at once, but it's all boring alphanumeric stuff.

Relevant haxelib versions:

> openfl: [8.8.0]
> lime: [7.2.1]
> flixel: [git] - latest dev branch
> hxcpp: [4.0.7]

Haxe version is 4.0.0-preview.5.

**Comment by jgranick** [comment]
Would you mind adding some traces, or testing some changes to the OpenFL internal `TextLayout` class?

https://github.com/openfl/openfl/blob/master/src/openfl/_internal/text/TextLayout.hx#L163-L185

Perhaps the `info` and `positions` arrays are different lengths? Perhaps we should iterate over the length of `positions` (or the smaller of the two arrays)?

Perhaps one of the info or position values are null?

**Comment by Tw1ddle** [comment]
Thanks, I added these checks to ``_position()`` and see it crash in any of these three cases when the game regains focus. I haven't noticed a pattern to it one it hits yet:

> 			if (_info == null && _positions == null) {
> 				trace("text is: '" + text + "'");
> 				trace("both _info and _positions were null");
> 				throw "_info and _positions were null";
> 			}
> 			
> 			if (_info == null) {
> 				trace("text is: '" + text + "'");
> 				trace("_positions is how long: " + _positions.length);
> 				throw "_info was null";
> 			}
> 			
> 			if (_positions == null) {
> 				trace("text is: '" + text + "'");
> 				trace("_positions was null, and _info was how long: " + _info.length);
> 				throw "_positions was null";
> 			}
> 			
> 			for (i in 0..._info.length) {

It crashed several times when ``text`` was a single space, but sometimes ``text`` was a word like "checking" or "=>" etc:

> I/trace   (31588): openfl/_internal/text/TextLayout.hx:188: text is: ' '
> I/trace   (31588): openfl/_internal/text/TextLayout.hx:189: _positions was null, and _info was how long: 1

I also see some related-looking crashes in lime, but the stacks weren't symbolicated except for this:

> 2/libApplicationMain.so (lime::text::harfbuzz::HB_obj::shape(Dynamic, Dynamic, Array<Dynamic>)+184)

I might try to make a standalone repro case. I don't see this problem when the HaxeFlixel debugger is disabled.

**Comment by jgranick** [comment]
We have `-Dlime-debug` or `-Dopenfl-debug` defines in order to make OpenFL and Lime's internal classes compiled for debug on debug builds (we don't by default to improve performance). That may help when investigating something like this. 

Oh, if `_positions` is null and `_info` has a length of 1, that would cause a crash here:

```haxe
			for (i in 0..._info.length) {
				
				info = _info[i];
				position = _positions[i];
```

**Comment by Tw1ddle** [comment]
Thanks, using that commit I'm not seeing the crash in ''TextLayout::_position'' anymore. Now it's always this crash in lime/HarfBuzz which looks like the crash in lime I mentioned above:

> signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)

> pc 003d0360  /data/app-lib/uk.co.the.app-2/liblime.so (hb_ot_shape_internal(hb_ot_shape_context_t*)+612)
> pc 003d0528  /data/app-lib/uk.co.the.app-2/liblime.so (_hb_ot_shape+200)
> pc 003d829c  /data/app-lib/uk.co.the.app-2/liblime.so (hb_shape_plan_execute+268)
> pc 003d944c  /data/app-lib/uk.co.the.app-2/liblime.so (hb_shape_full+116)
> pc 003d94b8  /data/app-lib/uk.co.the.app-2/liblime.so (hb_shape+48)
> pc 002909c0  /data/app-lib/uk.co.the.app-2/liblime.so (af_shaper_get_cluster+476)
> pc 002818c0  /data/app-lib/uk.co.the.app-2/liblime.so (af_cjk_metrics_init_blues+280)
> pc 002820bc  /data/app-lib/uk.co.the.app-2/liblime.so (af_cjk_metrics_init+96)
> pc 00285a1c  /data/app-lib/uk.co.the.app-2/liblime.so (af_face_globals_get_metrics+356)
> pc 0028e918  /data/app-lib/uk.co.the.app-2/liblime.so (af_loader_load_glyph+380)
> pc 002901d4  /data/app-lib/uk.co.the.app-2/liblime.so (af_autofitter_load_glyph+276)
> pc 0029a7a8  /data/app-lib/uk.co.the.app-2/liblime.so (FT_Load_Glyph+972)
> pc 00291b44  /data/app-lib/uk.co.the.app-2/liblime.so (FT_Get_Advances+460)
> pc 00291960  /data/app-lib/uk.co.the.app-2/liblime.so (FT_Get_Advance+292)
> pc 0033ff5c  /data/app-lib/uk.co.the.app-2/liblime.so (hb_ft_get_glyph_h_advance(hb_font_t*, void*, unsigned int, void*)+60)
> pc 00359d50  /data/app-lib/uk.co.the.app-2/liblime.so (hb_font_t::get_glyph_h_advance(unsigned int)+60)
> pc 0035bf20  /data/app-lib/uk.co.the.app-2/liblime.so (hb_font_get_glyph_h_advances_default(hb_font_t*, void*, unsigned int, unsigned int*, unsigned int, int*, unsigned int, void*)+72)
> pc 0035b230  /data/app-lib/uk.co.the.app-2/liblime.so (hb_font_t::get_glyph_h_advances(unsigned int, unsigned int*, unsigned int, int*, unsigned int)+96)
> pc 003cf934  /data/app-lib/uk.co.the.app-2/liblime.so (hb_ot_position_default(hb_ot_shape_context_t*)+132)
> pc 003cfe7c  /data/app-lib/uk.co.the.app-2/liblime.so (hb_ot_position(hb_ot_shape_context_t*)+32)
> pc 003d03a4  /data/app-lib/uk.co.the.app-2/liblime.so (hb_ot_shape_internal(hb_ot_shape_context_t*)+680)
> pc 003d0528  /data/app-lib/uk.co.the.app-2/liblime.so (_hb_ot_shape+200)

It doesn't seem to be crashing on a particular piece of text, and doesn't reproduce consistently. However it is often happening when I display the FlxDebugger with warning/notice text in it. Anyway, I can try making a minimal repro case for this if that'll help.

**Comment by jgranick** [comment]
A minimal repro case would be helpful, if you don't mind! Something's funny here, it's hard to know what

**Comment by Tw1ddle** [comment]
There's now a repro case here, which I will make into a full haxelib/demo later: https://github.com/Tw1ddle/samcodes-consent-demo

I think I diagnosed the issue now. I had wrongly assumed that calling ```Extension.callbackHandler.post``` from a Java extension would run Haxe callbacks on the same thread as the main game. I had ```FlxG.log.warning``` calls in these callbacks. The crashing above happened as I tried to add text to the FlxDebugger on two different threads simultaneously.

So this is invalid, sorry for the false start. Is there a better way to post callbacks from an Android extension, and (ideally) run them on the main game thread? Looking around, I see there are some older links about that: https://github.com/openfl/openfl-native/issues/145#issuecomment-357779237 and also #983.

**Comment by Tw1ddle** [comment]
Closing as I think this issue was a threading bug due to me tripping over https://github.com/openfl/lime/issues/983 and adding text to the FlxDebugger from multiple threads at once. So I'll move my attention over to https://github.com/openfl/lime/issues/983
