### ISSUE TITLE
Converting URLLoader.data to String adds extra lines to the content, on Android

### ISSUE THREAD

**Issue by ValentinRadoi** [openfl/openfl#2132]
Hello!

I found a strange issue with latest OpenFL + Lime combination:

I want to load an XML file from a remote URL with URLLoader, but do it in URLLoaderDataFormat.BINARY (this is what Starling's new AssetManager does via DataLoader). Then I need to convert the loaded data to String and parse it via Xml.parse(). The parsing fails, but that's because the string I obtain when typecasting from the loader's data is incorrect. Here is what happens:
 - My original XML file has 288 lines and 26790 bytes in size and sits at this URL https://pphx.devqublixaws.com/assets/common/common_mobile.xml
 - I download it with an URLLoader in BINARY mode and loader.bytesTotal reports correctly 26790. But then when I typecast loader.data to ByteArray, the obtained bytes have 32302 length or bytesAvailable. And if I do a bytes.toString() and then split it by "\n" and count the lines I get 346 lines. If I print the lines one by one to trace logs, I can see that the file shows the first 288 lines correctly, and then for some reason starts to repeat a bunch of extra lines, in the same order as in the original, only duplicated at the end, finishing with one line cut in the middle at character 72.
- I've built this code using Lime 7.2.1 and OpenFL 8.8.0 and targeting Android. If I target anything else, it works fine.
- If I run the exact same project, changing just Lime to 6.4.0 and OpenFL to 8.3.0, then everything works fine on Android as well (after doing a full project clean-up), and I get 288 lines as expected in the final string, not 346.

I've tested on 2 different Android devices, cleaned-up the project (deleted bin folder) before each build and looked into my XML file for clues, like special characters or anything fishy with a Hex Editor, but couldn't find nothing at all. Tried with a different XML, of similar length, same bug. Then switched to a smaller XML (only 10 lines) and this one worked correctly, having just 10 lines in the final string. So the size does matter to some extent, but I don't understand why. It seems that anything having more then a couple lines starts to display this bug, of adding extra lines by duplicating some part of the content again at the end.

The problem seems to originate when typecasting loader.data to ByteArray. I've tried using Std.string(loader.data) but I get the same result.

I've attached here the test project I used, just a couple of lines of code really.
[AndroidTest.zip](https://github.com/openfl/openfl/files/2818601/AndroidTest.zip)

If you want, you can try loading data from the following URLs by changing the strings in the code:
https://pphx.devqublixaws.com/assets/common/common_mobile.xml
https://pphx.devqublixaws.com/assets/common/common_web.xml
https://pphx.devqublixaws.com/assets/map/map4.xml
https://pphx.devqublixaws.com/assets/game/game.xml
https://pphx.devqublixaws.com/assets/firstRun/firstRun_web.xml

Any idea where to start looking for answers on this? 
Thanks!

**Comment by jgranick** [comment]
I think I might have resolved it in this commit:

https://github.com/openfl/lime/commit/864dcf74ccbd1eacb3fc7d54c87fe30dc68a8538

Are you running a dev version of Lime? Is it possible to test again with this change in place?

Thank you :smile:

**Comment by ValentinRadoi** [comment]
Excellent, the fix does work!

I've switched to latest dev versions of Lime and OpenFL from GitHub, and managed to recompile Lime's NDLLs, and now the sample app coverts that string correctly, with no added lines anymore, so XML parsing can proceed with no problem.

Previously it was failing on both Android and Windows targets, so I'm guessing all C++ backed targets where affected.

I have another problem now with frequent "Fatal signal 11 (SIGSEGV), code 1, fault addr 0x118 in tid 25197 (SDLThread), pid 25154" crashes that appear quite randomly while I use my app, but I suppose those are unrelated, so we can close the issue now.

Thanks a lot for your help!

**Comment by jgranick** [comment]
`Fatal signal 11 (SIGSEGV)` might be a null reference somewhere, like:

```haxe
var sprite:Sprite = null;
sprite.x = 100;
```
