### ISSUE TITLE
can't use atf anymore (Texture should be openfl.display3D.textures.RectangleTexture)

### ISSUE THREAD

**Issue by loudoweb** [openfl/openfl#2134]
Since this commit : https://github.com/openfl/openfl/commit/74bc398870cbf10a0739c7d5c05bc464799c718c#diff-3b89aba7307d5ed5685f67b71dd0384d

I can't do the following:

```haxe
var tex:Texture = context.createTexture(4096, 4096, Context3DTextureFormat.COMPRESSED_ALPHA, false);
tex.uploadCompressedTextureFromByteArray(Assets.getBytes('assets/atlas/atf3.atf'), 0);
var bm2 = BitmapData.fromTexture(tex);//this throws Texture should be openfl.display3D.textures.RectangleTexture
```

I don't know what is the difference between `Texture `and `RectangleTexture`, but if we can't use `Texture `as a paremeter in `BitmapData.fromTexture`, we should add `uploadCompressedTextureFromByteArray` in `RectangleTexture`.

**Comment by loudoweb** [comment]
So if I copy the whole `uploadCompressedTextureFromByteArray `method from `Texture `to `RectangleTexture`, it's working.

But now I have **duplicate** code in Texture and RectangleTexture. Can I move `uploadCompressedTextureFromByteArray `to `TextureBase` so we can share the code??

```haxe
var tex:RectangleTexture = context.createRectangleTexture(4096, 4096, Context3DTextureFormat.COMPRESSED_ALPHA, false);
tex.uploadCompressedTextureFromByteArray(Assets.getBytes('assets/atlas/atf3.atf'), 0);
var bm2 = BitmapData.fromTexture(tex);
```

**Comment by rainyt** [comment]
I have the same problem and hope to fix it.
