### ISSUE TITLE
Font rendering discrepancies on Hashlink

### ISSUE THREAD

**Issue by Eiyeron** [openfl/openfl#2138]
Hello. I'm currently trying the Hashlink backend to see if it's better than neko and I have a few issues relating to non-ASCII characters
- spacing after those characters seems broken 
- some glyphs are not working
- the last character's glyph can't be found if it's a non-ascii character

Here's a test I did with `AddingText`'s sample with another font ([Haeccity DW](https://dtw42.deviantart.com/art/Haeccity-a-pixel-font-78727302)) with the following test string : `"α space β space γ space δ space Ω"`.

On Neko, everything seems to work properly
![image](https://user-images.githubusercontent.com/936086/52717709-fb11d200-2fa1-11e9-8fa3-02cdf31b52b3.png)

On hashlink, the issues seen earlier are visible there:
![image](https://user-images.githubusercontent.com/936086/52717763-1846a080-2fa2-11e9-8db9-8bd71cb7da0c.png)

I'm using Haxe-4.0-rc1, last stable version of openfl and the develop branch of lime (cac8250)

Here's the code of the sample, with the minimal changes (spacing removed for brevity), haeccity's font file is dropped as-is in the asset folder:
```haxe
package;
import openfl.display.Sprite;
import openfl.text.Font;
import openfl.text.TextField;
import openfl.text.TextFormat;
class Main extends Sprite {
	public function new () {
		super ();
		var format = new TextFormat ("Haeccity DW", 30, 0x7A0026);
		var textField = new TextField ();
		textField.defaultTextFormat = format;
		textField.embedFonts = true;
		textField.selectable = false;
		textField.x = 50;
		textField.y = 50;
		textField.width = 800;
		textField.text = "α space β space γ space δ space Ω a";
		addChild (textField);
	}
}
```

Have a nice day

**Comment by manjav** [comment]
Hi
In my projects not shown texts and are hidden

**Comment by loudoweb** [comment]
Do you load your fonts with project.xml or are you trying to read a device font?
Fonts are working for me right now, except device fonts.

**Comment by MSGhero** [comment]
This should be working now. Proper Unicode support was added to HL's text code, and most of the text format bugs have been fixed (I hope).

If you still have issues, feel free to reopen this with an updated test case, or create a new issue
