### ISSUE TITLE
Playing sound with flash.media.Sound.loadPCMFromByteArray generates clicks

### ISSUE THREAD

**Issue by delahee** [openfl/openfl#2144]
Hello !

I tried multiple entry points for sound playing api, so far it works realllly well.

One minor hiccups is loadPCMFromByteArray, when I load a file and play it with this API on windows - debug, there is a "click" on sound startup ( I guess some buffers or setup is not okay )
Other entry points like :

new lime.media.AudioSource( lime.media.AudioBuffer.fromBytes( ))
flash.media.Sound.fromFile()
new lime.media.AudioSource( lime.utils.Assets.getAudioBuffer())
flash.media.Sound.fromAudioBuffer( lime.media.AudioBuffer.fromBytes( ))

Do work flawlessly withut glitch/click though so it's really a loadPCMFromByteArray  thing.

I'll change my sound path but you may want to have a look at loadPCMFromByteArray 
Thanks a lot.

ps : I use openfl for lime-switch stuff

Keep me posted if you want a full reproducible example with source, I'll upload something
Bye and thanks a lot for the awesome work.

[gallop_loop.zip](https://github.com/openfl/openfl/files/2936456/gallop_loop.zip)

**Comment by jgranick** [comment]
Thanks for letting us know :smile:

You said it works if you use `AudioBuffer`, does your code look at all like this code from `loadPCMFromByteArray`?

https://github.com/openfl/openfl/blob/develop/src/openfl/media/Sound.hx#L500-L504

**Comment by delahee** [comment]
Sorry I havent understood clearly :)

The source with the glitch is the one you linked.

Me, I l fell back on :

flash.media.Sound.fromAudioBuffer( AudioBuffer.fromBytes( ... ))

So I kinda guess something diverges in the loadpcm scenario :)

Keep me posted if you want a full sample.
Bye :)



Le mer. 6 mars 2019 à 19:37, Joshua Granick <notifications@github.com> a
écrit :

**Comment by jgranick** [comment]
Okay! Thank you :smile: 

Using your description, I reproduced the problem. Flash has the same problem!

_Turns out,_ the `loadPCMFromByteArray` method does _not_ expect the WAV file container. When try copying the bytes for your sound to position 736 (which appears to be the offset to the initial data), the click goes away.

Use the `loadCompressedDataFromByteArray` method and we'll use `AudioBuffer.fromFile` internally to decode the file and advance automatically around the file headers :wink:

**Comment by delahee** [comment]
Oh okay I never heard the glitch/click in my flash version of Dkh, it is
interesting.

Thank you for your time. ❤

Le mer. 6 mars 2019 à 22:00, Joshua Granick <notifications@github.com> a
écrit :

**Comment by delahee** [comment]
After checking I skipped the header in my actual code.

Nevermind I ll submit a full example after a few checks around your lead.

Thanks!

**Comment by jgranick** [comment]
I did just add some code to handle the number of samples specified. Perhaps we were adding a click at the end of the file, not before, or weren't handling the offset properly. Does Flash respect the `position` of the incoming byte object?

**Comment by delahee** [comment]
Yep position is respected in flash.

I ll reproduce tomorrow and will keep you posted if we have to reopen.

Thanks :)

Le mer. 6 mars 2019 à 22:09, Joshua Granick <notifications@github.com> a
écrit :

**Comment by jgranick** [comment]
I just made some commits that I think may help :smile:

**Comment by delahee** [comment]
Aww thanks

Le mer. 6 mars 2019 à 22:26, Joshua Granick <notifications@github.com> a
écrit :

**Comment by delahee** [comment]
Okay I confirm that the bug was caused by position not taken into account. I am testing the fix right now.

**Comment by delahee** [comment]
Something else I just discovered, on cpp target haxe.io.input does not advance bytearray position, which was the cause of the bug on my side. I'll investigate.

**Comment by delahee** [comment]
And okay I fixed my wav reader to retain byteinput pos rather than byte array pos and everything works.
Thank you very much :)
