### ISSUE TITLE
flash.utils.ByteArray not implemeting IDataOutput ?

### ISSUE THREAD

**Issue by llavayssiere** [openfl/openfl#215]
Why flash.utils.ByteArray is not implemeting IDataOutput ?

AS3 documentation :
Package	flash.utils
Classe	public class ByteArray
Héritage	ByteArray Inheritance Object
Implémente	IDataInput, IDataOutput
Sous-classes	ByteArrayAsset

line 32 of ByteArray.hx 
extern class ByteArray /*implements IDataOutput,*/ implements IDataInput implements ArrayAccess<Int> {

I need to uncomment "implements IDataOutput," to compile.

line 32 is modified to :
extern class ByteArray implements IDataOutput implements IDataInput implements ArrayAccess<Int> {

**Comment by ibilon** [comment]
It does now.
