### ISSUE TITLE
SimpleOpenGLView - compiling for HTML5 using Lime not working

### ISSUE THREAD

**Issue by MattGuerrette** [openfl/openfl#218]
I'm not sure if this was answered before, but I was under the impression that compiling to WebGL with Lime for the OpenFL samples was working? But, when I try to test using the command:

lime test html5

I am met with an error stating that  Class not found : GLUniformLocation

Can anyone comment on why this is??

**Comment by darmie** [comment]
@jgranick  just curious, is WebGL supported now?
