### ISSUE TITLE
[Html5] TextField font size bug

### ISSUE THREAD

**Issue by DarthVan** [openfl/openfl#2189]
Hi again☺
I use some texts from json in my app, and found this problem:

when i assign this text (value) to .htmlText property of the textField, last part looks like a superscript:
![Скриншот 2019-05-23 13 29 46](https://user-images.githubusercontent.com/5062893/58246820-bf389680-7d60-11e9-8224-6691d8ccbed7.png)
![Скриншот 2019-05-23 13 30 04](https://user-images.githubusercontent.com/5062893/58246835-c9f32b80-7d60-11e9-9ba3-41b289ebddd4.png)

but if i remove "DEVICE ", textField looks correctly:
![Скриншот 2019-05-23 13 30 19](https://user-images.githubusercontent.com/5062893/58246919-0f175d80-7d61-11e9-95c5-2e69e23e7dcd.png)
![Скриншот 2019-05-23 13 30 32](https://user-images.githubusercontent.com/5062893/58246932-150d3e80-7d61-11e9-9cb1-5d5a00b41e79.png)

I use BebasNeueBold font. Also tried Arial Narrow, same problem.
my textField has 36 size by default.

openfl/lime are 8.9.1/7.5.0
ty!

**Comment by DarthVan** [comment]
Lol, i solved this for my case by replacing whitespaces to empty symbol (alt+255)
It seems, whitespace breaks formatting

**Comment by MSGhero** [comment]
I definitely fixed this in the past, so something might have happened since then. Can you try like neko target, anything but flash or html5?

**Comment by MSGhero** [comment]
Also try doing it with normal `text` and TextFormats, to see if it’s an issue with layout in general or just with htmlText.

**Comment by DarthVan** [comment]
Ok, i tried to build this to neko, and got same bug again (with whitespaces in my text 'set' written as superscript)

Also i disabled applying .defaultTextFormat property:
![Скриншот 2019-05-23 15 20 58](https://user-images.githubusercontent.com/5062893/58252789-979cfa80-7d6f-11e9-9526-e28a34c0c855.png)
no changes :(

If i apply text via .text property, textField ignores html tags
![Скриншот 2019-05-23 15 22 45](https://user-images.githubusercontent.com/5062893/58252956-fbbfbe80-7d6f-11e9-87d9-eb4ba2e59f3e.png)

**Comment by DarthVan** [comment]
Upd: in neko build also found another problem: if text contains cirilyc symbols, tag <font size='20'>brings no effect:
![Скриншот 2019-05-23 15 56 39](https://user-images.githubusercontent.com/5062893/58254641-d8970e00-7d73-11e9-9d80-96dedcc2ed4e.png)

**Comment by MSGhero** [comment]
Ok I figured it out. `alignBaseline` isn't called on the final line of word wrapped text. Yet another edge case eliminated...

I'm working on a different change, but I'll make note to update this one when my branches are clean. Please put the Cyrillic thing in a new issue, since I imagine that's a 100% different issue.

**Comment by DarthVan** [comment]
Ok. thanks!
