### ISSUE TITLE
[Neko] Cyrilic symbols break text formatting in textField.htmlText

### ISSUE THREAD

**Issue by DarthVan** [openfl/openfl#2190]
Hi!
When i apply this text `"ЩИТ: MC<font size='25'>set</font>"` to `myTextField.htmlText`, tag `<font size='25'>`brings no effect...
But if i remove cyrillic word 'ЩИТ' from the text, formatting works (not correctly yet - last part "set" looks like a superscript cause whitespaces in text. see https://github.com/openfl/openfl/issues/2189)

openfl/lime are 8.9.1/7.5.0
ty!

**Comment by MSGhero** [comment]
Works for me now.
