### ISSUE TITLE
[html5] TextField htmlText <font color=... bug

### ISSUE THREAD

**Issue by Klug76** [openfl/openfl#2195]
TextField.htmlText incorrectly displays text with a font color tag:
```haxe
class App extends Sprite {
  constructor() {
    super();
    var t = new TextField();
    var s = "<p><font color='#ff0000'>foo</font></p>";
    s += "<p><font color='#00ff00'>bar</font></p>";
    s += "<p><font color='#0000ff'>foobar</font></p>";
    t.htmlText = s;
    this.addChild(t);
  }
}
```
see
https://codesandbox.io/s/orgopenflsamplessandboxes6-0li0u?fontsize=14
![openfl_bug_htmltext](https://user-images.githubusercontent.com/1420061/58704758-1cb29000-83be-11e9-8890-094348681138.png)

**Comment by MSGhero** [comment]
Does it work if you replace the p tags with `\n`? If so, I know where the problem is...

**Comment by MSGhero** [comment]
Double checked and fixed it, without breaking the original intended fix
