### ISSUE TITLE
Animating TextField position is extremely slow

### ISSUE THREAD

**Issue by joshtynjala** [openfl/openfl#2204]
With the following code, and targeting HTML5, OpenFL cannot run faster than about 30 FPS on my relatively new desktop PC running Windows 10. The more TextFields being animated, the slower it gets.

However, change the `BASE_VELOCITY` constant to `11.0` instead, and it easily hits 60 FPS.

It seems that re-positioning a TextField to a non-integer position has a huge impact on performance.

I could be wrong, but I think OpenFL may be uploading a new texture to the GPU every time that the position of a TextField changes to a non-integer value. Obviously, that should not be happening unless something like the text or TextFormat has changed.

```hx
import openfl.display.FPS;
import openfl.events.Event;
import openfl.text.TextField;
import openfl.display.Sprite;

class Main extends Sprite
{
	private static final BASE_VELOCITY = 11.5;

	public function new()
	{
		super();

		for(i in 0...10)
		{
			var tf = new TextField();
			tf.text = "Hello OpenFL";
			tf.y = 30 + (i * 10);
			this.addChild(tf);
			textFields[i] = tf;
			left[i] = false;
		}

		var fps = new FPS();
		this.addChild(fps);

		this.addEventListener(Event.ENTER_FRAME, enterFrameHandler);
	}

	private var textFields:Array<TextField> = [];
	private var left:Array<Bool> = [];

	private function enterFrameHandler(event:Event):Void
	{
		for(i in 0...textFields.length)
		{
			var tf = textFields[i];
			var velocity = BASE_VELOCITY - (i % 10);
			if(left[i])
			{
				velocity = -velocity;
			}
			tf.x += velocity;
			if(tf.x < 0 || tf.x > stage.stageWidth)
			{
				left[i] = !left[i];
			}
		}
	}
}
```

**Comment by MSGhero** [comment]
Flash text only renders on integer y positions, wonder if it should for x as well...

**Comment by joshtynjala** [comment]
I should mention that I was also seeing this same issue when animating the `y` position of the TextFields.

**Comment by jgranick** [comment]
This seems to help here:

https://github.com/openfl/openfl/commit/a6177e94130d656b7de6bc18ff6f177cd7aff1db

Let me know what you think

**Comment by rainyt** [comment]
<define name="openfl-disable-graphics-upscaling" />
This may help

**Comment by joshtynjala** [comment]
@jgranick That change does not seem to help much for me. Still sitting around 30 FPS when running my example in Firefox.

I wasn't testing in Chrome before, but it *might* make a difference there. It's kind of hard to say for sure. Chrome seems to sit closer to 60 FPS both before and after the change, but the FPS may be a bit less stable before the change. So maybe that helped somewhat.

Ultimately, I'm not sure that I understand why changing the x/y position only would make the TextField dirty. I guess it makes sense when rendering in software, where sub-pixels need to be considered. However, when rendered in GL, I would expect the texture to remain exactly the same and simply moved to a new location on screen. Is that something that can be done instead? Or is there some requirement that I'm not considering that makes it impossible?

**Comment by joshtynjala** [comment]
By the way, I just tried bumping the number of TextFields from 10 up to 40, and that helps illustrate the performance impact better in Chrome. Smooth as butter when snapped to integer pixels, and down to 30-40 FPS on non-integer pixels.

**Comment by joshtynjala** [comment]
I just committed a change where we add 1 to width/height instead of adding the value of tx/ty. This makes the calculation of newWidth/newHeight consistent, regardless of the current position. Sometimes, there will be an extra unused pixel, but I don't think that should cause any issues.
