### ISSUE TITLE
[HTML5] Overlapping content with Loader.loadBytes

### ISSUE THREAD

**Issue by spanvega** [openfl/openfl#2210]
When using the method loadBytes from Loader class like below with the HTML5 target, the images are not replaced but stacked, so they are overlapping. This is something that don't happen with the Flash target.

var stream : ByteArray;

private function fileComplete (e : Event) : Void
{
	stream = cast (e.target, FileReference).data;

	loader.loadBytes (stream);
}

**Comment by jgranick** [comment]
I just made a pass on `Loader` to fix this issue and some others I saw

https://github.com/openfl/openfl/commit/32258a2ed691084e16f560e7b5e3111279f4ba6d

 * Calling `loader.load()` should now dispatch an `Event.UNLOAD` event
 * Calling `loader.load()` should remove any loaded content immediately
 * `addChild`, `addChildAt`, `removeChild`, `removeChildAt` and `setChildIndex` are no longer allowed like Flash
