### ISSUE TITLE
[Textfield] last line doesn't appear on justified text

### ISSUE THREAD

**Issue by loudoweb** [openfl/openfl#2217]
On justified textfield, the last line doesn't appear when a space is the last character of the text.
It doesn't appear but `numlines `property is ok while `textHeight `and `height `are not.

Please find attaced a sample project:
[justifyBug.zip](https://github.com/openfl/openfl/files/3386230/justifyBug.zip)

**Comment by MSGhero** [comment]
Not sure when this was fixed, but I can't replicate on dev
