### ISSUE TITLE
TextField::bottomScrollV returning incorrect results?

### ISSUE THREAD

**Issue by ianharrigan** [openfl/openfl#2220]
So, i _think_ that bottomScrollV is returning incorrect results, reading the AS3 docs it states:

> [read-only] An integer (1-based index) that indicates the bottommost line that is currently visible in the specified text field.

However in my tests it always returns 102... i may be wrong but i would have expected that value to change as the textfield scrolls? Heres a test app:

```haxe
        var tf:TextField = new TextField();
        tf.type = TextFieldType.INPUT;
        tf.selectable = true;
        tf.mouseEnabled = true;
        tf.autoSize = TextFieldAutoSize.NONE;
        tf.multiline = true;
        tf.wordWrap = true;
        tf.width = 300;
        tf.height = 300;
        tf.background = true;
        tf.backgroundColor = 0xFFFFCC;
        tf.border = true;
        tf.borderColor = 0x000000;
        addChild(tf);
     
        var text = "";
        for (i in 0...100) {
            text += "Line " + i + "\n";
        }
        tf.text = text;
        
        tf.addEventListener(Event.SCROLL, function(e) {
            trace(tf.bottomScrollV);
        });
```

The main reason this would be good to have would be able to calculate the number of lines that are currently visible (good for page sizes in a UI), something like `tf.bottomScrollV - tf.scrollV`

Cheers,
Ian

**Comment by MSGhero** [comment]
I'll check this out, but I did get all the scrollVs working at one point...

**Comment by ianharrigan** [comment]
Git commit `d01a31086eac14edbfef4389765b7c50351d4b94` - just a few behind develop

**Comment by MSGhero** [comment]
Oh wow I added something incorrect. Thanks for noticing, let me figure out what this line is supposed to be...

**Comment by MSGhero** [comment]
In addition, the order of setting the scrollVs and dispatching the SCROLL event is also incorrect, which I never tested for.

**Comment by MSGhero** [comment]
My branches are a little weird and I want to test this a bit and add units, but here are the changes:

`openfl.text.TextField.hx`:
```haxe
	@:noCompletion private function set_scrollV(value:Int):Int
	{
		__updateLayout();

		if (value > 0 && value != __textEngine.scrollV)
		{
			__dirty = true;
			__setRenderDirty();
			__textEngine.scrollV = value;
			dispatchEvent(new Event(Event.SCROLL));
		}

		return __textEngine.scrollV;
	}
```
`openfl._internal.text.TextEngine.hx, line 1786ish`:
```haxe
var ret = scrollV;
```

**Comment by MSGhero** [comment]
https://github.com/openfl/openfl/commit/76182cfedf9b0499135a6135439b21be4d7ea8a9 should have fixed the last bit of this. I tested locally and got the correct numbers for scrollV, bottomScrollV, and numLines
