### ISSUE TITLE
Specifying a root dir for openfl resources

### ISSUE THREAD

**Issue by ianharrigan** [openfl/openfl#2221]
When targeting html5 if an openfl application is in a different directory to the server root it seems it cant load the resources. 

I found this: https://community.openfl.org/t/set-root-url-for-resources-on-html5-backend/580

But couldnt see how to actually use it... strangely a previous application works fine in a server sub dir, so its possible this is a regression of some kind. Test app:

```haxe
var data:BitmapData = openfl.Assets.getBitmapData("img/test.png");
var bitmap:Bitmap = new Bitmap(data);
addChild(bitmap);
```
Cheers,
Ian

**Comment by intoxopox** [comment]
Hoped the following would fix this, but no such luck (for me at least).
https://github.com/openfl/lime/pull/1342

**Comment by jgranick** [comment]
Does this help? 

https://github.com/openfl/lime/commit/d0f15395a564470e89b333e4d919272c03072b4b

**Comment by intoxopox** [comment]
Sure did!
