### ISSUE TITLE
Ordering of rendered graphics commands inconsistent between targets

### ISSUE THREAD

**Issue by nialltl** [openfl/openfl#223]
Created a function to draw a clipped circle arc by first drawing a circular outline, then overlaying a white pie-chart-like circle segment. Behaviour is as-expected in Flash, yet when it comes to windows the output is decidedly different. Better explained visually, here is the Flash output with a darker overlay circle: 
![untitled](https://cloud.githubusercontent.com/assets/6987884/2933560/453caa7e-d7c0-11e3-8b79-71137ae18b68.png)

And Windows output:
![untitled](https://cloud.githubusercontent.com/assets/6987884/2933562/52c09f02-d7c0-11e3-8f44-7120d004bd41.png)

The code in question:

	graphics.lineStyle(8, 0xFF6699);
	graphics.drawCircle(px, py, radius - 5);

	graphics.beginFill(0x006699);
	graphics.moveTo(px, py);
	graphics.lineStyle(0, 0);

	var startAng = Math.PI;
	var endAng = 2 * Math.PI;

	var resolution = 20;
	var step = ( Math.PI * 2 ) / resolution;

	var i = startAng;
	while ( i < endAng) {
		var cx = px + radius * Math.cos(i);
		var cy = py + radius * Math.sin(i);

		graphics.lineTo(cx, cy);

		i += step;
	}
	graphics.lineTo( px + radius * Math.cos( endAng ), py + radius * Math.sin( endAng ) );

	graphics.endFill();

It appears that OpenFL processes ALL line operations on a higher depth than any fill commands when not building to flash, resulting in some pretty weird behaviour!

**Comment by jgranick** [comment]
This should be fixed :smile:
