### ISSUE TITLE
Double-click selectable textfield should select charachters under

### ISSUE THREAD

**Issue by intoxopox** [openfl/openfl#2230]
Double-clicking inside a textfield should select any contiguous characters beneath the point clicked. Currently, it does not on non-flash targets.

**Comment by intoxopox** [comment]
Any status updates or insights on this?

**Comment by MSGhero** [comment]
It's just not implemented yet. I imagine the solution would be to add a double click event, use getCharIndexAtPoint in the callback, look for the previous and next space/newline/etc, and then setSelection on those indices to highlight the text.

**Comment by intoxopox** [comment]
Thinking about tackling this, if no one else is on it yet.

**Comment by MSGhero** [comment]
Go for it

**Comment by intoxopox** [comment]
Think I got it. Do I just submit a PR and reference this issue number?

**Comment by MSGhero** [comment]
Yep and you're in luck, I just hooked up the internet to my dev PC. So I'll be able to test your changes once you post the PR (and generally code more often).
