### ISSUE TITLE
Problem with cyrillic symbols on Android

### ISSUE THREAD

**Issue by flashup** [openfl/openfl#2237]
Hello, I've updated lime, openfl and haxe to the last versions and tried to run TextMetrics project from `openfl-samples`.
I added some cyrillic text to strings in sources.
Flash, html5, neko render text properly, but android renders wrong.
```
Haxe RC-3
Lime 7.6.0
OpenFL 8.9.2
HXCPP 4.0.19
```
Flash:
![flash](https://user-images.githubusercontent.com/2893619/63424747-c29ef500-c417-11e9-81f4-085398ec0817.jpg)

Neko:
![neko](https://user-images.githubusercontent.com/2893619/63424748-c468b880-c417-11e9-85c4-3dd5ab472b62.jpg)

Android:
![android](https://user-images.githubusercontent.com/2893619/63424751-c6327c00-c417-11e9-98a4-41924d12960a.jpg)

**Comment by MSGhero** [comment]
Can you try a Windows/Mac compile with your current versions? There's an issue with rc4 and 5, and I want to see if this is the same or different.

**Comment by flashup** [comment]
@MSGhero what I need to do?

**Comment by MSGhero** [comment]
Instead of building android, build windows or Mac and see if the same problem happens

**Comment by flashup** [comment]
Same lib versions, couldn't compile iOS:
```
Compiling group: runtime
xcrun --sdk iphoneos12.4 clang++ -D_CRT_SECURE_NO_DEPRECATE -DHX_UNDEFINE_H -c -stdlib=libc++ -O2 -arch armv7 -isysroot /Applications/Xcode_10.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.4.sdk -miphoneos-version-min=5.0 -fobjc-arc -DOBJC_ARC -DENABLE_BITCODE=YES -fembed-bitcode -Wno-parentheses -Wno-null-dereference -Wno-unused-value -Wno-overflow -Wno-trigraphs -Wno-bool-conversion -fno-stack-protector -DIPHONE=IPHONE -DIPHONEOS=IPHONEOS -DSTATIC_LINK(static) -DHXCPP_ARMV7 -DHXCPP_VISIT_ALLOCS(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -I/usr/local/lib/haxe/lib/hxcpp/4,0,19/include -fexceptions -fstrict-aliasing ... tags=[haxe]
 - src/hx/Date.cpp
 - src/hx/CFFI.cpp  [haxe,static]
 - src/hx/Boot.cpp
 - src/hx/Interface.cpp
 - src/hx/Anon.cpp
 - src/hx/Object.cpp
 - src/Enum.cpp
 - src/Array.cpp
 - src/hx/Class.cpp
 - src/Dynamic.cpp
 - src/hx/gc/GcRegCapture.cpp  [haxe,gc]
Error: /usr/local/lib/haxe/lib/hxcpp/4,0,19/src/Array.cpp:390:28: error: use of undeclared identifier 'u'
            memcpy(buf+pos,u"null",8);
                           ^
```
---
Tried to update libs and haxe to:
```
lime 7.6.3
openfl 8.9.5
4.0.0-rc.5+4a745347f
```
And compiled android:
```
Error: ./src/haxe/ds/StringMap.cpp: In member function 'void haxe::ds::StringMap_obj::clear()':
./src/haxe/ds/StringMap.cpp:150:16: error: '::__string_hash_clear' has not been declared
 HXDLIN( 103)   ::__string_hash_clear(this->h);
```

**Comment by MSGhero** [comment]
I think this is the same as #2256, and I notified Joshua to look into it

**Comment by MSGhero** [comment]
@flashup can you try out the fix in #2300 and let me know if it works for you?

**Comment by flashup** [comment]
@MSGhero 
```
haxe 4.0.3
hxcpp 4.0.64
lime 7.6.3
openfl git develop branch
```
HTML5:
![html5](https://user-images.githubusercontent.com/2893619/70861717-c8769400-1f3a-11ea-87d8-5b5aa733253c.png)
FLASH:
![flash](https://user-images.githubusercontent.com/2893619/70861718-cb718480-1f3a-11ea-8fdb-734e52cb9cb1.png)
NEKO:
![neko](https://user-images.githubusercontent.com/2893619/70861720-cd3b4800-1f3a-11ea-8719-2afa98ef576b.png)
ANDROID:
![android](https://user-images.githubusercontent.com/2893619/70861721-cf050b80-1f3a-11ea-8f57-457c0d07a3d6.jpg)

**Comment by MSGhero** [comment]
I can’t test Android unfortunately so I can’t be much help. My PR fixes it on Windows, but I’m not sure which targets the ifdef covers or needs to cover. You can try playing with it, because that’s where the solution needs to go.

**Comment by flashup** [comment]
@MSGhero I apologize, I didn't notice that changes aren't merged into develop branch. I used `develop` branch for test. I repeated the test with the `utf16` branch and text was rendered correctly.
ANDROID:
![android_new](https://user-images.githubusercontent.com/2893619/71020039-4043ea80-2104-11ea-9563-2a9d3430b966.jpg)

**Comment by MSGhero** [comment]
Oh perfect, thanks for checking
