### ISSUE TITLE
removeEventListener() doesn't work with HashLink target

### ISSUE THREAD

**Issue by joshtynjala** [openfl/openfl#2238]
Code:

```hx
var dispatcher = new EventDispatcher();
dispatcher.addEventListener(Event.CHANGE, methodListener);
dispatcher.dispatchEvent(new Event(Event.CHANGE));
dispatcher.removeEventListener(Event.CHANGE, methodListener);
dispatcher.dispatchEvent(new Event(Event.CHANGE));
```

The listener must be a method on a class (it seems to work correctly with a local function):

```hx
private function methodListener(event:Event):Void {
	trace(event.type);
}
```

Expected output:

```
change
```

Actual output:

```
change
change
```

**Comment by m0rkeulv** [comment]
As far as i can tell this is a bug in HashLink.
I have made an issue over at the HashLink repo.
https://github.com/HaxeFoundation/hashlink/issues/301

**Comment by jgranick** [comment]
https://github.com/openfl/openfl/commit/a8605d7d6d248f513687523516739a0ec3f3eab5

**Comment by joshtynjala** [comment]
Confirmed fixed. Thanks!
