### ISSUE TITLE
Does OpenFL8.9.2 load the library by default?

### ISSUE THREAD

**Issue by rainyt** [openfl/openfl#2239]
![image](https://user-images.githubusercontent.com/9693090/63479228-f2a1d300-c4bf-11e9-971a-32037485975b.png)
Generated a Demo project that runs errors on the Android platform.

**Comment by rainyt** [comment]
I found the location of the problem.
Lime7.6.0 templates/haxe/ManifestResources.hx 38 line.
Here "./" is used as the path and a crash occurs. I updated it to the following code after it was fixed:
```haxe
if (rootPath == null) {

			#if (ios || tvos || emscripten)
			rootPath = "assets/";
			#elseif console
			rootPath = lime.system.System.applicationDirectory;
			#elseif cpp
			rootPath = "";
			#else
			rootPath = "./";
			#end

		}
```

**Comment by jgranick** [comment]
This should be resolved here:

https://github.com/openfl/lime/commit/80867b3f629fcdc691511164f79f91e424cc9217
