### ISSUE TITLE
Multiline selection of centered text seems broken

### ISSUE THREAD

**Issue by dpomier** [openfl/openfl#2254]
While 04363c6b504ddafe8a67bae03f29b3ba7ce98e5a fixes normal multiline selections, it seems like centered texts are still broken in OpenFL 8.9.5.

For instance for this with the HTML5 target:
![firefox_2l1N3Oi2ZH](https://user-images.githubusercontent.com/18221324/64855682-b6761400-d620-11e9-88a1-bb566746600f.png)

We still get that:
![firefox_GkscYC7ASZ](https://user-images.githubusercontent.com/18221324/64855694-bc6bf500-d620-11e9-9dc4-151f4c0305de.png)

**Comment by MSGhero** [comment]
Seems fixed now, tried HTML5, Neko, and Windows.
