### ISSUE TITLE
Wrong text with accents in Haxe 4 >= rc3

### ISSUE THREAD

**Issue by aW4KeNiNG** [openfl/openfl#2256]
The original issue was posted here: https://github.com/HaxeFoundation/hxcpp/issues/831

But it seems to be a problem in OpenFL.

Here the minimum example with the problem:

```haxe
package;

import openfl.display.Sprite;
import openfl.text.TextField;
import openfl.text.TextFieldAutoSize;


class Main extends Sprite {
		
	public function new () {
		
		super ();
		
		stage.color = 0xA0A0A0;

		var textField = new TextField();				
		textField.width = 700;
		textField.multiline = true;
		textField.wordWrap = true;
		textField.autoSize = TextFieldAutoSize.NONE;
		
		textField.text = "Inicie sesión como usuario";
		
		addChild (textField);
	}
}
```

Project: https://www.dropbox.com/s/uwi7azysrxae9to/openfl_text_problem.zip?dl=0

Using Haxe 4 rc4 + hxcpp 4.0.52 + openfl 8.9.4 + lime 2.6.2

Windows: `openfl test windows`

![image](https://user-images.githubusercontent.com/1063719/64693193-fe692f80-d496-11e9-8485-b2ac4dc69250.png)

HTML5: `openfl test html5`

![image](https://user-images.githubusercontent.com/1063719/64693218-0cb74b80-d497-11e9-9107-de2aae170637.png)

It works if you change to Haxe 4 rc2 and hxcpp 4.0.8

**Comment by MSGhero** [comment]
This is the same as #2264, so I'm gonna close this one since I already pointed out the problem lines to Joshua.
