### ISSUE TITLE
[html5]TextField.height is too big when using autoSize

### ISSUE THREAD

**Issue by Klug76** [openfl/openfl#2273]
TextField.height is too big when using autoSize.
Code to reproduce:
```
class Main extends Sprite {
	public function new() {
		super();
		var tf = new TextField();
		tf.background = true;
		tf.backgroundColor = 0xc0c0c0;
		tf.wordWrap = true;
		tf.width = 200;
		tf.autoSize = TextFieldAutoSize.LEFT;
		tf.htmlText = "<p align='center'>Attention!\nPerforming daily tasks this month you can win a grand prize:</p>";
		addChild(tf);
	}
}
```
Result:
![tf_wrong_height](https://user-images.githubusercontent.com/1420061/66751114-51237600-ee9f-11e9-9b81-d1ed53143484.PNG)

Expected result:
![tf_expected_height](https://user-images.githubusercontent.com/1420061/66750988-f9850a80-ee9e-11e9-9fa8-7ccc424fab4e.PNG)

**Comment by MSGhero** [comment]
Seems fixed on dev.
