### ISSUE TITLE
[html5]TextField ignores mouseWheelEnabled=false

### ISSUE THREAD

**Issue by Klug76** [openfl/openfl#2274]
TextField ignores ``mouseWheelEnabled=false``.
Code:
```
class Main extends Sprite {
	public function new() {
		super();
		var tf = new TextField();
		tf.background = true;
		tf.backgroundColor = 0x60c0c0;
		tf.wordWrap = true;
		tf.width = 200;
		tf.autoSize = TextFieldAutoSize.LEFT;
		tf.mouseWheelEnabled = false;
		tf.htmlText = "<p align='center'>Attention!\nPerforming daily tasks this month you can win a grand prize:</p>";
		addChild(tf);
	}
}
```
If you spin the mouse wheel, then this happens:
![tf_wheel_bug](https://user-images.githubusercontent.com/1420061/66751836-0571cc00-eea1-11e9-80b7-16819d9184b0.gif)
(In this case, it is impossible to return the scroll position to the first line, even if you turn the wheel in the opposite direction).
OpenFL version: 
https://github.com/openfl/openfl/commit/be31d8825f35356f08910ff0d71b307c854b6bbd

**Comment by MSGhero** [comment]
Fixed here: https://github.com/openfl/openfl/commit/d2f99928436e012956e8f99574e8d8b1c5100afe

I had no idea this Boolean existed, thanks!
