### ISSUE TITLE
[html5]DisplayObject::scrollRect doesn't work

### ISSUE THREAD

**Issue by Klug76** [openfl/openfl#2275]
In recent OpenFL versions (https://github.com/openfl/openfl/commit/be31d8825f35356f08910ff0d71b307c854b6bbd) ``DisplayObject::scrollRect`` doesn't clip the viewable area of the display object.
Code to reproduce:
```
class Main extends Sprite {
	public function new() {
		super();
		var sp: Shape = new Shape();
		sp.graphics.beginFill(0x6080a0, 1);
		sp.graphics.drawCircle(100, 100, 100);
		sp.graphics.endFill();
		addChild(sp);
		sp.scrollRect = new Rectangle(0, 20, 60, 40);
	}
}
```
Result:
![scroll_rect_bug](https://user-images.githubusercontent.com/1420061/66752936-aeb9c180-eea3-11e9-8042-23ff97137fff.PNG)
Expected result:
![scroll_rect_expected](https://user-images.githubusercontent.com/1420061/66752946-b4afa280-eea3-11e9-8218-02971005c25d.PNG)

**Comment by Beeblerox** [comment]
@Klug76 should be working after [this commit](https://github.com/openfl/openfl/commit/e9f04643a893b08102e30ec22e76bfb34f3a7335)

**Comment by Klug76** [comment]
fixed, thanks.
