### ISSUE TITLE
Lib.getURL() doesn't work in Ubuntu

### ISSUE THREAD

**Issue by larsiusprime** [openfl/openfl#2276]
Reproduction case:

```haxe
var request  = new URLRequest("https://www.google.com");
Lib.getURL(request, "_blank");
```
What I expected:
- For google.com to open in a new browser window (this is the behavior on windows)

What happened instead:
- No window opened, and this was printed to the console I launched the application from:
```
xdg-open: unexpected argument '&'
Try 'xdg-open --help' for more information.
```

Using Ubuntu 18.04.2 LTS

**Comment by larsiusprime** [comment]
Just tried both these directly on the command line:
`xdg-open https://www.google.com`
`xdg-open https://www.google.com &`

Both of them work, the latter however also returns some stuff:
`[1] 27835`

So that's presumably the point of the "&" parameter ... but I guess it's getting mangled on the way over?

**Comment by jcward** [comment]
Removing the `"&"` makes it work -- when typed at the end of a command, that will launch a command in the background. I'm not sure if it's necessary here...

**Comment by larsiusprime** [comment]
I'm all for getting rid of it if that's the solution, but in the name of [Chesteron's Fence](https://en.wikipedia.org/wiki/Wikipedia:Chesterton%27s_fence) I'd like to find out why it was stuck there in the first place, if that's something we can figure out. Gonna check the blame history to see if there's a useful commit message...

**Comment by larsiusprime** [comment]
Cool. Well I'll make a quick bodge locally to fix my build, and let's ping @jgranick to get an answer on whether we can just remove this "&" parameter.

**Comment by larsiusprime** [comment]
@jcward you're right on the money. That's the issue
```
xdg-open "https://www.google.com" "&"
xdg-open: unexpected argument '&'
Try 'xdg-open --help' for more information.
[1]+  Done                    xdg-open https://www.google.com
```

```
xdg-open https://www.google.com &
[1] 27980
```

**Comment by larsiusprime** [comment]
(I'm using Haxe 3.4.7 for the record)

**Comment by jcward** [comment]
Ah -- I seem to be using Haxe 4 rc5, so perhaps chances are, `Sys.command`'s hasn't changed.

**Comment by larsiusprime** [comment]
Well, this is probably a little-used enough feature that we're the first to notice it? I haven't seen any other relevant bug reports about this. How often do you launch URL's from a native app, *in linux*?

The problem is definitely caused by quoting the "&" sign. So either this has been broken on Linux from the start, or an even earlier version of Haxe had unescaped parameters.

Relevant question for us is -- how do we fix this behavior? It's easy enough to drop the &, but I suspect this auto quoting thing might be causing trouble elsewhere so it might be smart to figure out how to get around it now.

**Comment by jcward** [comment]
Well, & is technically not an argument. Yeah, the docs for [`Sys.command`](https://api.haxe.org/Sys.html#command) specifically says htey'll be quoted, which is correct behavior.

I know I've used an `&` before... ah yes, hxScout had a splash screen that launched the main app:

```
var code = Sys.command(Sys.getCwd()+"hxScoutMain &");
```

But if you use it there, you have to supply (and escape) your own arguments.

One could argue that if `'&'` is the final "argument", that it should not be quoted, to give the desired effect on OSX and Linux (launch in the background). But that's assuming you always want that behavior. It'd be better to be an optional parameter to `Sys.command` (on OS's that support it.)

**Comment by larsiusprime** [comment]
So the issue is that we need to swap out the linux implementation with a call to Process instead of Sys.command, the latter being for more simple use cases?

**Comment by jcward** [comment]
Well... if `xdg-open` is expected to be a long-running process, then yes. But it _appears_ that `xdg-open` returns immediately. In other words, there could be no reason to background it, which would mean, just remove the `"&"`.

**Comment by joshtynjala** [comment]
Closing old issue, which appears to be fixed.

openfl/lime@6900d189718de3b25605fb73e4a402d7e7ac454f
