### ISSUE TITLE
SharedObject IOS clean only when app closes fully

### ISSUE THREAD

**Issue by alagatar** [openfl/openfl#230]
Hi,
I found issue with SharedObject on IOS platform. Saves not cleared after clear() command only if app closes.
//Save data
var dataObject:SharedObject;
dataObject=SharedObject.getLocal("test1");
dataObject.data.testKey="testValue";
dataObject.flush();

trace(dataObject.data);//{ testKey => testValue }

dataObject.clear();
trace(dataObject.data);//{ testKey => testValue }
If you close app from processes it cleared.

**Comment by jgranick** [comment]
This should be resolved in newer builds :smile:
