### ISSUE TITLE
TextFormat doesn't clear in html5 @8.9.6

### ISSUE THREAD

**Issue by Continuities** [openfl/openfl#2315]
Applying a `TextFormat` to a `TextField` doesn't properly unset the format after the end index. This appears to be a regression in OpenFL 8.9.6.

Reproduction code:
```haxe
package;

import openfl.text.TextFormat;
import openfl.display.Sprite;
import openfl.text.TextField;

class Main extends Sprite
{
  public function new()
  {
    super();

    var text = new TextField();
    text.defaultTextFormat = new TextFormat('serif', 24, 0x000000);
    text.text = "The default format for this text should make it all black";
    text.width = text.textWidth;
    text.x = 10;
    text.y = 50;
    addChild(text);

    var newFormat = new TextFormat();
    newFormat.color = 0xff0000;
    text.setTextFormat(newFormat, 12, 17);
  }
}
```

Expected: All the text is black, except for the word "format" which is red.
Actual: All text after the word "format" is also red.

**Comment by MSGhero** [comment]
So this was broken here: https://github.com/openfl/openfl/commit/db5613912968a68eb0933dfcaa4e11e84943268a

It looks like the intent was to clean up the code. My first thought broke the layout code, so I'll have to look into it some more.

**Comment by MSGhero** [comment]
See https://github.com/MSGhero/openfl/commit/0d59058b3b7cefbdcb73ea8a3f5e66015a157870

**Comment by MSGhero** [comment]
Leaving this open so I remember to add unit tests. Fixed on a sub-branch that I'll work on merging into dev
