### ISSUE TITLE
TextField does not render in neko, hl, or cpp targets on macOS

### ISSUE THREAD

**Issue by joshtynjala** [openfl/openfl#2316]
The textWidth always seems to be 0.

```hx
import openfl.text.TextFormat;
import openfl.text.TextField;
import openfl.display.Sprite;

class Main extends Sprite {
	public function new() {
		super();

		var tf = new TextField();
		tf.autoSize = LEFT;
		tf.defaultTextFormat = new TextFormat("_sans", 20);
		tf.text = "Hi there";
		addChild(tf);

		trace(tf.width, tf.height, tf.textWidth, tf.textHeight);
	}
}
```

Run `openfl test neko` and no text will be rendered on macOS. The same code works fine on Windows.

Output (macOS):

```
src/Main.hx:15: 4, 27.7, 0, 23.7
```

Output (Windows):

```
src/Main.hx:15: 76, 26.34375, 72, 22.34375
```

Even if you remove the `autoSize`, still no text is rendered on macOS and the textWidth remains 0.

I also tried different font names than "_sans", like "Arial", but it did not make a difference.

macOS Catalina 10.15.2, OpenFL 8.9.6

**Comment by jgranick** [comment]
Is this a regression specific to Catalina? I've never heard this issue before

**Comment by joshtynjala** [comment]
I don't know for sure if it's a regression or not. My main desktop platform is Windows, so I haven't spent as much time testing Feathers UI on macOS. Most likely, I never tried OpenFL on any version of macOS before Catalina.

**Comment by joshtynjala** [comment]
Thanks!
