### ISSUE TITLE
Umlauts break TextField rendering

### ISSUE THREAD

**Issue by And-0** [openfl/openfl#2318]
Affected target: Hashlink
Versions: Haxe 4.0.5, OpenFL 8.9.6, Lime 7.7.0

When a string contains umlauts, the last character of that string is not rendered in a `TextField`. However, if a space is added after the umlaut, the string is rendered correctly.

So:   "abcüabc" -> abcüab
But: "abcü abc" -> abcüabc

```haxe
import openfl.text.TextFormat;
import openfl.text.TextField;
import openfl.display.Sprite;

class Main extends Sprite {
	public function new() {
		super();

		var tf = new TextField();
		tf.defaultTextFormat = new TextFormat("_sans", 20, 0xff0000);
		tf.text = "abcüabc";
		addChild(tf);
	}
}
```

**Comment by 0xA3** [comment]
Another affected target: Windows
Versions: Haxe 4.0.5, OpenFL 8.9.6, Lime 7.7.0
```
import openfl.text.TextField;
import openfl.display.Sprite;

class Main extends Sprite {

	public function new() {
		super();

		final textfield = new TextField();

		textfield.text = "McChicken® Classic\nohne Eiswürfel";
		addChild( textfield );
	}
}
```
Output:
**McChicClassic
ohne Eisw**
Special Characters like the ® and umlauts are not rendered. Characters around the special characters are sometimes also not rendered.
The behaviour is a little different to the Hashlink target.
abcüabc -> abc
abcü abc -> abcabc

**Comment by MSGhero** [comment]
I don't have time like I used to to look at these issues, but this seems like a general Unicode issue, where the extra positions of the Unicode characters "eat up" the other surrounding characters as text layout happens in TextEngine. I thought I had all this fixed at least on Windows, but I haven't kept up with OpenFL PRs in a while.

**Comment by restorer** [comment]
I have the same problem, and I'm trying to figure out how to solve it. PR to track progress - https://github.com/haxelime/lime/pull/1391

Feel free to add ideas / code / fixes in the comments.

**Comment by MSGhero** [comment]
@And-0 @0xA3 @restorer can you all check this again, making sure you have https://github.com/openfl/openfl/pull/2300/files? I'm not getting this issue on Windows, and #2328 fixes it on several other targets.

@And-0 if it still fails on HL, look at that link and try deleting `hl` from the ifdef and recompiling.

**Comment by restorer** [comment]
Sorry, have no time to check this now. As quick-n-dirty solution, I resolve my issue by reverting to Haxe 3 :smiley_cat:

**Comment by nixbody** [comment]
This [#2351](https://github.com/openfl/openfl/pull/2351) fixes it for me on Hashlink target.

**Comment by MSGhero** [comment]
Will close once the contents of the PR have been merged into dev.
