### ISSUE TITLE
UTF-8 TextField Problem (Win, Android, iOS)

### ISSUE THREAD

**Issue by barisyild** [openfl/openfl#2337]
UTF-8 TextField not working correctly on CPP Target.
I'm tried disable font but same problem with system font.

I'm trying write "abcüabc" on following example:

![image](https://cdn.discordapp.com/attachments/415682986877386762/705246904744673351/gif04.gif)

**Comment by pozirk** [comment]
It s fixed here: https://github.com/openfl/openfl/issues/2264
