### ISSUE TITLE
SyntaxError: Identifier 'init' has already been declared

### ISSUE THREAD

**Issue by intoxopox** [openfl/openfl#2338]
When using `-D js-es=6`, latest Lime, latest OpenFL from develop branch,  and Haxe 4.1, I'm seeing the following error:
`SyntaxError: Identifier 'init' has already been declared`
This happens even on the simplest of projects. Here are the offending lines:
```
let init = lime__$internal_backend_html5_HTML5Application;
let init = lime_app_Application;
```
It seems this was always kind of happening, but was hiding behind the fact that, before Haxe 4.1, these were to consecutive _vars_ rather than _lets_.

**Comment by RealyUniqueName** [comment]
This is a Haxe issue: https://github.com/HaxeFoundation/haxe/issues/9426

**Comment by intoxopox** [comment]
I'll buy that, but I still don't understand why these are consecutively declared, making the 1st call needless as it is trumped by the second.
```
let init = lime__$internal_backend_html5_HTML5Application;
let init = lime_app_Application;
```
Previous to Haxe 4.1, this was:
```
var init = lime__$internal_backend_html5_HTML5Application;
var init = lime_app_Application;
```

**Comment by RealyUniqueName** [comment]
Ah, right. That's an Openfl issue :)

**Comment by intoxopox** [comment]
Anyone have a notion as to where these lines are coming from? I poked around in Lime and OpenFl for a bit and didn't spot any obvious places these lines are generated from.

**Comment by intoxopox** [comment]
Now that I know a bit more about it, I tried it in just Lime without OpenFL. Same trouble exists there, as makes sense based on the above. I'm going to post this in Lime issues.

**Comment by intoxopox** [comment]
Closing this issue, as it's really a Lime issue.
https://github.com/haxelime/lime/issues/1398
