### ISSUE TITLE
MOUSE_MOVE (buttonDown) - HTML5 backend

### ISSUE THREAD

**Issue by starburst997** [openfl/openfl#235]
When targeting HTML5:

If you add a listener to the stage for the MOUSE_MOVE event, drag the mouse from inside to outside of the browser window, release the mouse button outside and then move the mouse back inside the browser, it will read buttonDown as true.

It was working before (1.4.0), just did a haxelib upgrade today and this was broken (2.0.0 beta 2).

Also, is there any way to know if the mouse button was release outside of the window?

**Comment by jgranick** [comment]
This should've been fixed in newer builds, just didn't close the issue, sorry about that! :smile:
