### ISSUE TITLE
Dawn, a WebGPU implementation  

### ISSUE THREAD

**Issue by longde123** [openfl/openfl#2363]
https://github.com/boberfly/dawn

Is there a plan to bind a backend

**Comment by jgranick** [comment]
OpenFL is currently written for the WebGL API, Lime currently provides this for native platforms and on HTML5 (obviously) this is provided automatically

This could be discussed as a possible enhancement in the Lime issue tracker. I currently I do not know of someone working on WebGPU + Lime
