### ISSUE TITLE
Confirm SWF libraries still work

### ISSUE THREAD

**Issue by jgranick** [openfl/openfl#2381]
Temporarily add the "scripts/Tools.hx" code back into OpenFL and compile against `-lib swf` directly in order to get things operable again for a stable OpenFL 9 release

**Comment by nanjizal** [comment]
Could OpenFL provide 'AwayCpp' for 'AwayFL' stuff like the ts parsers of swf bytecode code would need porting maybe the ts2haxe could help atleast create a working js approach and externs base to start a possible port to for c++ target?

**Comment by jgranick** [comment]
The swf library has a full SWF bytecode parser written in Haxe, what is the benefit of using the AwayFL parser? Thanks 😄

**Comment by nanjizal** [comment]
Joshua

I believe that OpenFL parser ignores Haxe code within swf's, in my tests some swf's with Haxe code are supported by AwayFL parser, same with as3 ( as2 and as1 ). So the haxe code in the bytecode is not only read but it's also run. Forget which Haxe coded swf worked (  I think it may have been justTriangle early test ), I think my flip triangle one with lots of complex bitmap copying failed, also perlin noise as3 failed, inlining and partially parsing embeded xml within class properties in as3 also failed, my blitting in as3 failed. But quite a lot worked.
Specifically see https://github.com/awayfl  avm1 and avm2 repo's I believe they parser the code and run it as js, it does not matter if the code is haxe, as3, as2, as1 it will run depending on current feature support.
AwayFL is more like the actual flash player than OpenFL swf reader. Likely OpenFL may do somethings a lot better, some of the internal tech in AwayFL seems to come from other swf tech projects.
Is that useful clarification. It's only been visible public for a short while as far as I can see and quite active.
I don't think Rob ( away3D ) is really fully aware of full OpenFL capabilities, I have explained a bit but I expect in cases where AIR was not suitable they have had to run the js code on a server and send result back to Java land, so likely they should have used OpenFL had they realized it has some child access control and stop play code and frame labels feasiblity.

Best
Justin

**Comment by nanjizal** [comment]
I think using haxe 2.1 or something you can probably code avm1 which is likely very well supported by AwayFL, shame that avm1 ( as2 ) was discontinued by haxe compiler, but like I said it does do some haxe avm2 well.

**Comment by jgranick** [comment]
Another approach would be to get the SWF library up and running and released with OpenFL 9

**Comment by jgranick** [comment]
Relies on #2390

**Comment by jgranick** [comment]
Relies on openfl/swf#3

**Comment by barisyild** [comment]
In my opinion OpenFL can execute avm3 bytecode and can use own libraries instead of flash libraries.
So your flash application can work in a partially native environment!

Example creation of sprite.

AVM Interpeter => (flash.display.Sprite Redirect openfl.display.Sprite) => Execute

Assuming that there is no stable emulator for Actionscript 3.0, almost all of the internet world will use this emulator.

Any development made for OpenFL will positively affect this application, so it can be obtained in serious donations.

**Comment by jgranick** [comment]
I just confirmed that the OpenFL "NyanCat" sample is working properly for me on Neko, Windows and HTML5

I also just tried the PBS Kids "Pick'M Stick'M" game (which uses SWF assets extensively) and it is also working fine

I'd appreciate if another developer can confirm that SWF assets are working properly in other projects, otherwise I will close this task
