### ISSUE TITLE
Colors incorrect when drawing tiles with scale set in software

### ISSUE THREAD

**Issue by wmarsh** [openfl/openfl#239]
See example code: https://gist.github.com/wmarsh/3dd9082c1cee6644dbc8

Only happens in software mode. Happens in neko and Android (at least) - basically anything using native.

Scale = wrong colors (random on each run)
Scale + alpha = fine

**Comment by jgranick** [comment]
Sounds like this is related to https://github.com/openfl/openfl/issues/350
