### ISSUE TITLE
setTextFormat() doesn't respect endIndex when specified

### ISSUE THREAD

**Issue by Gulvan0** [openfl/openfl#2399]
**Description**
When setTextFormat() is used with all three arguments, the formatting is applied to the very end of the TextField. _openfl 8.9.5 hasn't this bug whereas openfl 8.9.7 has._

**Minimal example**
```
package;

import openfl.display.Sprite;
import openfl.text.TextFormat;
import openfl.text.TextField;

/**
 * @author Gulvan
 */
class Repro extends Sprite
{

	public function new() 
	{
		super();
		var tf1:TextField = new TextField();
		var tf2:TextField = new TextField();
		var baseFormat:TextFormat = new TextFormat(null, 25, 0x000000);
		var specFormat:TextFormat = new TextFormat(null, 25, 0xFF0000);
		tf1.text = tf2.text = "Testtesttest";
		tf1.setTextFormat(baseFormat);
		tf2.setTextFormat(baseFormat);
		tf2.setTextFormat(specFormat, 3, 5);
		tf1.x = tf1.y = tf2.x = 100;
		tf2.y = 200;
		addChild(tf1);
		addChild(tf2);
	}
}
```
**Screenshots**
![Аннотация 2020-08-14 155129](https://user-images.githubusercontent.com/16256911/90251223-0d462800-de46-11ea-9ee9-afae40e8773a.png)

**OpenFL Targets**
Windows, HashLink

**Comment by MSGhero** [comment]
I have this fixed, just working on unit tests before I publish the changes. The branch isn't up to date, but it's here if you want to try it https://github.com/openfl/openfl/tree/text-all-fixes
