### ISSUE TITLE
Flash target mp3 with ID3v2

### ISSUE THREAD

**Issue by andrew-git** [openfl/openfl#240]
When using mp3 files with ID3v2 tags and compiling flash target I got warning and can't use this asset:
Warning: Could not embed "assets/snd/file.mp3" (Flash only supports Layer-III MP3 files, but file is Layer1).

After removing ID3v2 tags embeding ok.
Similair problem described in forum:
http://www.openfl.org/archive/community/bugs/nme-355-very-picky-about-mp3s-especially-compiling-flash/

**Comment by T1mL3arn** [comment]
I just get the same error right now. How it can be fixed? It is possible to do something with mp3 file?

**Comment by T1mL3arn** [comment]
Manually removing (I used hex-editor) id3 tag from mp3 file helps.

**Comment by ibilon** [comment]
Anybody got a mp3 that doesn't pass embeding by the lime tool?

**Comment by andrew-git** [comment]
coin2.mp3 same as coin.mp3 but with ID3v2 tag
When trying to build got :
> Warning: Could not embed "Assets/snd/coin2.mp3" (Flash only supports Layer-III MP3 files, but file is Layer1)

Thanks
[snd.zip](https://github.com/openfl/openfl/files/243009/snd.zip)

**Comment by jgranick** [comment]
Migrated to https://github.com/openfl/lime/issues/749
