### ISSUE TITLE
Caret doesn't disappear after a TextField loosing a focus.

### ISSUE THREAD

**Issue by NipponSunrise** [openfl/openfl#2409]
Caret doesn't disappear after a TextField loosing a focus. In case of multiple TextFields on the stage there is a situation when multiple carets are blinking at the same time.

openfl 8.9.7 and 9.0.2
lime 7.8.0

**Expected behavior**
Caret disappears after the field loosing focus. 

**Screenshots**
![image](https://user-images.githubusercontent.com/941814/94333522-08959780-ffe0-11ea-8d42-4a5c4c02e6aa.png)

**OpenFL Targets**
html5

**Comment by MSGhero** [comment]
Should be fixed in #2431, thanks!
