### ISSUE TITLE
[HashLink] URLRequest / URLLoader no response in HashLink only

### ISSUE THREAD

**Issue by B-Interactive** [openfl/openfl#2451]
**Describe the bug**
A basic GET request fails to elicit an API response, when build targets **HashLink**.
The same request (identical code) results in the correct response when build targets **C++** (Windows), or **Neko**.

**To Reproduce**

1. Create a new Haxe project, using the code below.  The target URL for the purposes of this test is using an [httpbin.org](https://httpbin.org/) API endpoint and only a basic response is expected:
```
package;

import openfl.display.Sprite;
import openfl.events.Event;
import openfl.net.URLLoader;
import openfl.net.URLRequest;
import openfl.net.URLRequestMethod;

class Main extends Sprite {
	public function new() {
		super();

		var urlRequest:URLRequest = new URLRequest("https://httpbin.org/get");
		urlRequest.method = URLRequestMethod.GET;
		var urlLoader:URLLoader = new URLLoader(urlRequest);
		urlLoader.addEventListener(Event.COMPLETE, function(e:Event) {
			var urlLoader:URLLoader = cast(e.target, URLLoader);
			trace(urlLoader.data);
		});
	}
}
```
2. From project root, run `openfl test hl`.
Output is empty:
```
```

**Expected behavior**
When build targets C++ or Neko, the expected behaviour is produced.
`openfl test windows`
`openfl test neko`

Output:
```
Source/Main.hx:18: {
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Host": "httpbin.org",
    "User-Agent": "libcurl-agent/1.0",
    "X-Amzn-Trace-Id": "Root=1-5fed6af0-3379aa1230dc4d482ba10c99"
  },
  "origin": (removed),
  "url": "https://httpbin.org/get"
}
```

**OpenFL Targets**
HashLink fails.
C++ (Windows) works.
Neko works.

**Additional context**
Haxe 4.1.4
OpenFL 9.0.2
HL 1.11.0

**Comment by jgranick** [comment]
My first guess would be on String handled to/from Haxe and HashLink. I'm not 100% sure that the current implementation is really correct. It could be related to this issue: https://github.com/haxelime/lime/issues/1441

I wonder if the requested URL string is being passed properly into project/src/net/curl/CURLBindings.cpp

Can you tell if networking at all works with HashLink? It might help if we could decide how far it works until it fails

**Comment by tour1st** [comment]
Not sure why HashLink behaves differently (maybe related to threading), but I managed to make your sample work by triggering the load request **after** adding the event listener :
```
		var urlLoader:URLLoader = new URLLoader();
		urlLoader.addEventListener(Event.COMPLETE, function(e:Event) {
			var urlLoader:URLLoader = cast(e.target, URLLoader);
			trace(urlLoader.data);
		});
		urlLoader.load(urlRequest);
```

**Comment by B-Interactive** [comment]
Thanks @tour1st , that's a simple enough workaround!
