### ISSUE TITLE
Right aligned selection text is displayed incorrectly on html5 canvas

### ISSUE THREAD

**Issue by NipponSunrise** [openfl/openfl#2453]
Selected texts' coordinates differ from original text's coords when using `TextFormatAlign.RIGHT`.

**To Reproduce**

1. Create `TextField` with `defaultTextFormat.align = TextFormatAlign.RIGHT`
2. Enter some text
3. Try to select parts of that text

**Expected behavior**
Selected text is displayed correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/941814/103450465-247f9800-4cb7-11eb-96d4-e84ab48dc479.png)

**OpenFL Targets**
`html5-canvas`

**OpenFL Version**
`9.0.2`

**Comment by dimensionscape** [comment]
which version of openfl? try the latest dev and see if you still have a problem, I may have already fixed this. I know I did for cpp.

**Comment by NipponSunrise** [comment]
> 
> 
> which version of openfl? try the latest dev and see if you still have a problem, I may have already fixed this. I know I did for cpp.

`9.0.2`. Just added this info to initial post.

I cannot easily check latest `dev` because it's incompatible with `swf` `v3.0.2` and with `swf` `master` as well. But since I see no changes in this [block of code](https://github.com/openfl/openfl/blob/f4f9b8e5f5e555ea5d64a979cf228098f82b22b8/src/openfl/display/_internal/CanvasTextField.hx#L266), I can suppose that it's still here.

**Comment by dimensionscape** [comment]
https://github.com/openfl/openfl/pull/2429 I think I resolved it here.

**Comment by NipponSunrise** [comment]
> 
> 
> #2429 I think I resolved it here.

According to code seems to be done. Thanks. I'll make my own ad-hoc patch later this day (EU timezone) and let you know.

**Comment by dimensionscape** [comment]
No problem -- be sure to let me know! If its still behaving incorrectly I'll take another look.

**Comment by NipponSunrise** [comment]
Could not wait. Applied it. Works perfect. Thank you very much.
