### ISSUE TITLE
Tilemap compilation error on Flash

### ISSUE THREAD

**Issue by fedor-strelkov** [openfl/openfl#2454]
I cannot build a project on Flash target against the current 'develop' branch due to this compilation error:
`openfl-dev/src/openfl/display/Tilemap.hx:120: characters 3-17 : Unknown identifier : __drawableType`

Supposedly, the problem was introduced in the 'Simplify library' commit - cd2086d332dd236161f867a48a89aa18ababfb27.

**Comment by joshtynjala** [comment]
Fixed in 7862f9f1162561ec0c3810e446b6a01a6ff033ab
