### ISSUE TITLE
Mac (native) TextField missing characters and other native targets have character spacing issues

### ISSUE THREAD

**Issue by Greg209** [openfl/openfl#2469]
**Describe the bug**
When rendering TextFields on native Mac sometimes lines are truncated, other times characters are just missing and on other native targets (tested iOS, Android and Mac) there are certain characters such as 'T' that have extra trailing space that makes it look odd within a word. This is useing the latest development branches of OpenFL and Lime - but other earlier branches exhibited similar issues. This is using the _sans font but _serif and other fonts show the same problem.

**To Reproduce**
Example code: 
```haxe
package;

import openfl.display.Sprite;
import openfl.events.Event;
import openfl.events.MouseEvent;
import openfl.text.Font;
import openfl.text.FontType;
import openfl.text.FontStyle;
import openfl.text.TextField;
import openfl.text.TextFormat;
import openfl.text.TextFormatAlign;
import openfl.Assets;

class Textty extends Sprite {

	var format:TextFormat;

	var X = 50;
	var Y = 50;
	var STEP = 30;

	public function new () {

		super ();

		// format = new TextFormat(Assets.getFont("fonts/Roboto-Regular.ttf").fontName);
		format = new TextFormat("_sans");
		// format = new TextFormat("_serif");

		createTF( "FONT = "+format.font );
		createTF( "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789,./;'\\[]`§~±" );
		createTF( "abcdefghijklmnopqrstuvwxyz!@£$%^&*()-=_+{}:\"|<>?" );
		createTF( "ABCDEFGHIJKLMNOPQRS TUVWXYZ0123456789 ,./;'\\[]`§~±" );
		createTF( "abcdefghijklmnopqrs tuvwxyz!@£$%^&*() -=_+{}:\"|<>?" );
		createTF( "GHIJKLMNOPQRSTUVWXYZ0123456789,./;'\\[]`§~±" );
		createTF( "ghijklmnopqrstuvwxyz!@£$%^&*()-=_+{}:\"|<>?" );
		createTF( "TUVWXYZ0123456789,./;'\\[]`§~±" );
		createTF( "tuvwxyz!@£$%^&*()-=_+{}:\"|<>?" );
		createTF( "TEXTTEST © texttest" );
		createTF( "SPACE ©" );
		createTF( "space ©" );
		createTF( "NOSPACE©" );
		createTF( "nospace©" );
		createTF( "THIRD Third third" );
		createTF( "SECOND Second second" );
	}

	function createTF( txt:String, size:Int = 20, color:Int = 0 ):TextField {
		var textfield = new TextField();
		textfield.embedFonts = true;
		format.size = size;
		format.color = color;
		textfield.defaultTextFormat = format;
		textfield.text = txt;
		textfield.x = X; 
		textfield.y = Y;
		textfield.width = textfield.textWidth + 20;
		textfield.height = textfield.textHeight + 5;
		textfield.background = true;
		textfield.backgroundColor = 0xe0e0e0;
		addChild( textfield );
		Y += STEP;
		return textfield;
	}
}
```

**Expected behavior**
HTML formatting seems fine and can be seen on the left of the screenshot. In the middle is Android that shows some of the character spacing issues - especially 'T' both upper and lowercase. The right-hand side shows the Mac version. I've highlighted in red the missing texts/characters.

**Screenshots**
![TextIssues](https://user-images.githubusercontent.com/550301/109694399-ac343680-7b82-11eb-8996-441d5fd7f292.png)

**OpenFL Targets**
Mac (native) mainly but other native targets such as iOS and Android.

**Additional context**
None

**Comment by MSGhero** [comment]
Can you add the following to your project.xml, after where you include openfl?:

`<haxedef name="openfl_trace_text_layout_groups" />`

This will trace some text metrics that will be helpful for us in debugging the issue. It'll be easiest if you reduce your text to the minimum that still shows an issue, like `tf.text = "THIRD Third third;`.

Edit: likely not the issue, but it is possible that kerning isn't a part of your Android default font

**Comment by MSGhero** [comment]
Sorry my brain is processing this in streams. Mac currently doesn't support Unicode (#2450), and I don't have a Mac to try to figure out a solution with. That's probably borking up your test there at least.

**Comment by Greg209** [comment]
Thanks for getting back to me. As requested, here are the outputs from the layer group metrics:

**For HTML5**
LG 0,line:0,w:130.595703125,h:24,x:2,y:2,"FONT = _sans",0,12
LG 0,line:0,w:546.640625,h:24,x:2,y:2,"ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789,./;'\[]`§~±",0,48
LG 0,line:0,w:156.689453125,h:24,x:2,y:2,"THIRD Third third",0,17

**For native Mac**
LG 0,line:0,w:132.640625,h:23,x:2,y:2,"FONT = _sans",0,12
LG 0,line:0,w:688,h:23,x:2,y:2,"ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789,./;'\[]`§~±",0,48
LG 0,line:0,w:161,h:23,x:2,y:2,"THIRD Third third",0,17

Note: there were a few more duplicates of these lines for both.

In terms of the font kerning, when using an embedded font, the same problems with kerning are apparent on native but not HTML5 - so it should be the same font being used on all targets and not a font specific problem that I can see.

Yeah - looking at some of the situations where the text seemingly get chopped - it may be likely due to subsequent multibyte UTF8 chars and stopping a couple a chars previous - e.g. §, £ or the copyright symbol.

**Comment by MSGhero** [comment]
I will say, our Harfbuzz text shaper is several years and at least hundreds of commits behind the latest. The fact that the kerning isn't happening on Android either means the kerning info isn't present in the loaded font OR there's a bug in that library on Android or something to that effect. The first still seems more likely to me tbh, but we can't rule out the latter.

On an experimental target, we found that loading a font left out the height info, and it was a problem at the SDK level. That's why I'm leaning that way. We can prioritize updating Harfbuzz, since we're more than a major version behind now.

**Comment by barisyild** [comment]
I am having the spacing problem with Windows, Mac and Android targets

**Comment by MSGhero** [comment]
Oh y'know what, this might be caused by a recent change. I'll look into it.

**Comment by Greg209** [comment]
Any further updates on this. Especially updating to the latest Harfbuzz version?
