### ISSUE TITLE
Matrix in beginBitmapFill (html5)

### ISSUE THREAD

**Issue by neurofuzzy** [openfl/openfl#248]
I am drawing graphics from a tilesheet and using beginBitmapFill, while reusing a Matrix object to align each texture. It appears that html5 does some sort of batch rendering which, when I reuse my matrix, causes all graphics on the screen to use the last settings of the matrix.

So... most likely beginBitmapFill should either grab the values of the matrix and store them as scalar values or clone the matrix. That is, if you don't want different behavior across targets.

**Comment by jgranick** [comment]
pretty sure this is fixed :smile:
