### ISSUE TITLE
[Textfield] Textfield not show the last row when set autoSize

### ISSUE THREAD

**Issue by flashultra** [openfl/openfl#2484]
The last row with the text is not visible ( in the textfield ) when the ```textField.autoSize = TextFieldAutoSize.LEFT;```

Example:
```haxe
        var defaultFormat = new TextFormat();
	defaultFormat.color = 0x000000;
	defaultFormat.size = 25;
	defaultFormat.leading = 0;
	defaultFormat.letterSpacing = 0;
	defaultFormat.align = TextFormatAlign.LEFT;
	defaultFormat.font = "Arial";

	var textField = new TextField();
    textField.x = 100;
	textField.y = 100;    
	textField.background = true;
	textField.backgroundColor = 0xe3e3e3;
	textField.border = true;
	textField.borderColor = 0xd8d8d8;
	
	textField.multiline = false;
	textField.wordWrap = true;
	textField.autoSize = TextFieldAutoSize.LEFT;
	textField.height = 50;
	textField.width = 300;
	textField.type = TextFieldType.INPUT;
	textField.defaultTextFormat = defaultFormat;

	this.addChild(textField);
```

**Expected behavior**
When reach the end of the textfield part of the text is moved on new row , but it's not visible. It should be visible

**Video**
 After the first lien , I still typing, but characters are not visible on screen. 
![TextFieldTest](https://user-images.githubusercontent.com/13473027/114227689-fa0c3d80-997d-11eb-8ece-52a85984a230.gif)

**OpenFL Targets**
HTML5 and  CPP ( windows ) 

**Versions**
OpenFL 9.1.0-LqBuHo ( latest from the Github)
Lime 7.9.0
Hxcpp  4.2.1

**Comment by dimensionscape** [comment]
Thanks, I'll investigate this today.

**Comment by flashultra** [comment]
Thank you !
I'm not sure is this a other bug , but textfield cursor looks a bit off   ( and a more bigger than the letters).
I made two tests with ```defaultFormat.leading = 0;``` and ```defaultFormat.leading = -5;``` ( target HTML5 ( chrome) and cpp) .
Here is a screenshot:

![image](https://user-images.githubusercontent.com/13473027/114262891-11354480-99eb-11eb-858d-c31d634ddf1e.png)

Cpp target is only with ```leading = -5```, but should the letters start at the bottom of the cursor position ? 

Haxe versions: 4.1.4  , OpenFL 9.1.0

**Comment by flashultra** [comment]
One more example Flash vs HTML5 . Flash have a correct position of the cursor. 

![image](https://user-images.githubusercontent.com/13473027/114264503-029f5b00-99f4-11eb-8d51-4dff8457e97e.png)
