### ISSUE TITLE
[Textfield] scrollV and bottomScrollV not update ( backspace)

### ISSUE THREAD

**Issue by flashultra** [openfl/openfl#2494]
**Describe the bug**
When have multiline lines and delete the last characters using backspace, ( removing the whole last row)  the scorllV and bottomScrollV are not updated . Arrows up and down update scrollV/ bottomScorllV with correct values. 

**To Reproduce**
1. Create multiline textfield (at example with height 65px ( it's two rows).
2. Enter three rows which will update the ScrollV =  2 and BottomscrollV =  3
3. Use backspace to remove all characters from the last row , so will remain only two rows
4. For html5 target scrollv still show ScrollV =  2 . Show correct result for Flash target.

**Expected behavior**
Update scorllV and bottomScrollV 

**Screenshots**
![ScrollVBug](https://user-images.githubusercontent.com/13473027/118117431-4838b480-b3f4-11eb-88f7-41b4c5d13ba4.gif)

**OpenFL Targets**
HTML5   
Openfl 9.1.0-LqBuHo
Lime 7.9.0

**Comment by MSGhero** [comment]
Well, the fact that your TextField is updating when you backspace means the values are changing. Are you using an event listener for `Event.SCROLL`? Because maybe that's not firing on backspace.

**Comment by flashultra** [comment]
Yes, I'm listening for ```Event.SCROLL```

Here is example of the code:
```haxe
        var defaultFormat = new TextFormat();
	defaultFormat.color = 0x000000;
	defaultFormat.size = 25;
	defaultFormat.leading = 0;
	defaultFormat.letterSpacing = 0;
	defaultFormat.align = TextFormatAlign.LEFT;
	defaultFormat.font = "Arial";

	textField = new TextField();
        textField.x = 100;
	textField.y = 100;    
	textField.background = true;
	textField.backgroundColor = 0xe3e3e3;
	textField.border = true;
	textField.borderColor = 0xd8d8d8;
	
	textField.multiline = true;
	textField.wordWrap = true;
	textField.autoSize = TextFieldAutoSize.NONE;
	textField.height = 65;
	textField.width = 300;
	textField.type = TextFieldType.INPUT;
	textField.defaultTextFormat = defaultFormat;

	textField.addEventListener(Event.SCROLL, onTextScroll);

	traceField = new TextField();
        traceField.x = 100;
	traceField.y = 300;  
	traceField.width = 400;
	traceField.defaultTextFormat = defaultFormat;
	traceField.autoSize = TextFieldAutoSize.NONE;
	this.addChild(traceField);  

	this.addChild(textField);


        private function onTextScroll(e:Event):Void
	{
		trace("scrollV: "+textField.scrollV);
		trace("BottomscrollV: "+textField.bottomScrollV);
		traceField.text = "ScrollV: "+textField.scrollV+" , "+"BottomscrollV: "+textField.bottomScrollV;
	}
```

**Comment by MSGhero** [comment]
Right, so the issue is that backspace doesn't dispatch a scroll event. There should be a `setSelection` in there somewhere, maybe also on DELETE, although that may be automatically taken care of. 

Because the caret is still on the original line when you backspace the text (the selection index is on the previous line), it doesn't recognize it as a scroll. Calling `setSelection` would force a scroll.

**Comment by flashultra** [comment]
```setSelection``` didn't help  ( I set ```textField.setSelection(textField.caretIndex-1,textField.caretIndex)```).
Other thing, when remove characters with backspace and after that insert new ones scrollV and bottomScrollV did not change , if not reach the previous max scrollV  ( Example:  for 5 rows remove the last three ( with backspace) and start to type again  )

**Comment by MSGhero** [comment]
The setSelection call I am thinking of needs to be placed internal to OpenFL's text handling

**Comment by flashultra** [comment]
Adding ```setSelection(__selectionIndex, __caretIndex);```  at the end of ```case BACKSPACE:```  in  ```function window_onKeyDown``` on  ```openfl.text.TextField``` didn't help .
 Strange , but delete works correctly . The code is same/similar  as backspace.

**Comment by dimensionscape** [comment]
@flashultra try the latest dev source and close the issue if we're good now.

**Comment by flashultra** [comment]
The problem is still there when delete 1-2 lines of text.  This fix also introduce the new bug.
Now when cursor goes to the new line it always select the last character which require to enter again the last character.
Example:

https://user-images.githubusercontent.com/13473027/120305085-0905d100-c2d9-11eb-9ba6-add44a17885a.mp4

**Comment by dimensionscape** [comment]
> 
> 
> The problem is still there when delete 1-2 lines of text. This fix also introduce the new bug.
> Now when cursor goes to the new line it always select the last character which require to enter again the last character.
> Example:
> bugtextfield.mp4

I can not reproduce this, are you sure you arent doing textField.setSelection(textField.caretIndex-1,textField.caretIndex) somewhere? I didn't do anything that would select the last character but this bit of code you mentioned earlier would...

**Comment by dimensionscape** [comment]
![gif](https://i.gyazo.com/37775935099207a6a487c87679989ece.gif)

I am also getting proper scroll property traces.... did you try the latest dev?

**Comment by flashultra** [comment]
It's very possible the problem to be in some kind of cache of Openfl and Lime. I removed the whole directories of Openfl and Lime , run haxelib remove openfl and lime , install  again openfl/lime  and  it didn't help.  It's same for me, but as I say it's very possible some kind of cache to keep the old changes which I did.  Don't know how this is possible .
 I will close the task

**Comment by dimensionscape** [comment]
If you're building html5, this can certainly happen.
