### ISSUE TITLE
Oddities with htmlText in textfields

### ISSUE THREAD

**Issue by ianharrigan** [openfl/openfl#2498]
There seems to be some oddities and inconsistences with textfields, i realise textfields are being actively worked on but, unless im mistaken, these issues are new (i think i probably would have noticed / heard about them before otherwise - maybe not)

Maybe something with how these are being used (below) is incorrect now? 

```haxe
class Main extends Sprite {
    public function new() {
        super();
        
        var tf = new TextField();
        tf.htmlText = '<font size="26"><b>BOLD</b> not bold</font>';
        Lib.current.stage.addChild(tf);
        
        var tf = new TextField();
        tf.x = 60;
        tf.y = 30;
        tf.htmlText = '<font size="26"><b>BOLD</b> not bold</font>';
        Lib.current.stage.addChild(tf);
        
        var tf = new TextField();
        tf.x = 0;
        tf.y = 60;
        tf.htmlText = '<font color="#ff0000">RED</font> <font color="#00ff00">GREEN</font> <font color="#0000ff">BLUE</font>';
        Lib.current.stage.addChild(tf);
        
        var tf = new TextField();
        tf.x = 0;
        tf.y = 90;
        tf.htmlText = '<font size="26"><font color="#ff0000">RED</font> <font color="#00ff00">GREEN</font> <font color="#0000ff">BLUE</font></font>';
        Lib.current.stage.addChild(tf);
        
        var tf = new TextField();
        tf.x = 90;
        tf.y = 90;
        tf.htmlText = '<font size="26"><font color="#ff0000">RED</font> <font color="#00ff00">GREEN</font> <font color="#0000ff">BLUE</font></font>';
        Lib.current.stage.addChild(tf);
    }
}
```

![image](https://user-images.githubusercontent.com/3024242/120222997-2ab37980-c241-11eb-993b-ab31979b5098.png)

Latest git openfl, but also confirmed on 9.1.0

Cheers,
Ian

**Comment by dimensionscape** [comment]
@ianharrigan Thanks for pointing this out Ian. I'm glad someone is awake out there. I'll try to sort this out as soon as I get the chance. Either there is something wrong with text formatting or theres a measurement issue, or a combination of the two.

**Comment by dimensionscape** [comment]
actually it is neither. 
![gif](https://i.gyazo.com/2703bb5f7cc5517e755b250c496cb368.gif)

Everything is rendering correctly, the caret index is just not being reset properly. I'll make the simple fix later this evening.

**Comment by ianharrigan** [comment]
Nice one - thanks, sounds great... i wont pretend to understand much of openfls text internals (new or old) but sounds like its an easy fix (if you know where to look and what it all means ofc :D )

Thanks again,
Ian

**Comment by dimensionscape** [comment]
Yeah no problem. The road is a little bumpy at the moment. We managed to squeezed out a nice performance leap without having to rewrite the whole thing(which really needs to be done at some point to get to performance parity with competing technology). There's a lot of moving parts and its pretty spaghettified, so some hiccups are to be expected. Unfortunately, 9.1.0 was a little rushed due to being somewhat blindsided by haxe 4.2 changes to abstracts. I'm expecting another minor release soon.

**Comment by ianharrigan** [comment]
Hey Chris,

Did you try the example above in the OP? It still looks off... 

![image](https://user-images.githubusercontent.com/3024242/120232702-61df5600-c254-11eb-930b-ee27dd8ebd7c.png)

(Just pulled latest openfl, maybe i need lime too, but looking at the fix it didnt look like it)

**Comment by dimensionscape** [comment]
what looks off about it? I'm not sure I follow. Are you talking about the text being cut off?

**Comment by ianharrigan** [comment]
thats one thing, yeah, though now i think about it, thats probably just auto size / inital size - the other issue is that bold `<b>` seems to have been applied to the whole thing

**Comment by dimensionscape** [comment]
Yeah the cutoff is just the initial width (100px I believe). I didn't notice the bold issue! Ok.

**Comment by Gulvan0** [comment]
@Dimensionscape Hey, just noticed that \<p\> in .htmlText with align equal to either "center" or "right" makes the entire paragraph vanish. Also, "justify" works the same as "left" (default alignment). Is it unimplemented? 

Minimal example:
```
package;

import openfl.text.TextField;
import openfl.display.Sprite;

class Main extends Sprite
{

    public function new()
    {
        super();
        var firstLabel:TextField = new TextField();
        firstLabel.htmlText = '<p><b>Gulvan:</b> pururu</p><p><b>Kaz:</b> pupu</p><p align="center"><i>Spectator connected</i></p><p><b>Gulvan:</b> wow</p>';
        firstLabel.x = 200;
        firstLabel.width = 600;
        addChild(firstLabel);
    }
}
```
![image](https://user-images.githubusercontent.com/16256911/120333468-62312d00-c2f8-11eb-8a14-da21a4d13b53.png)

**Comment by dimensionscape** [comment]
Justify isn't implemented yet. As far as the html text it looks like there are a lot of issues here. I haven't done anything that's really affected html text yet....But I will definitely be looking into some fixes after everything else is stable.

**Comment by dimensionscape** [comment]
Ok so, the html tags `<b> <i> and <p>` are broken as far as I can tell. Its a really perplexing issue because one textfield will effect every other textfield that is added afterwards! This is especially weird because every textfield is isolated completely.... I'll have to take a really deep look into this....

**Comment by MSGhero** [comment]
I would also consider an issue at the font level, as I've run into this a number of times in the past. It seemed like the whole font family would be stuck, but it could be something else since I usually ignored it.

**Comment by ShaharMS** [comment]
Solving this might be easier then expected, when I made the markdown interpreter which includes lots of textformats it worked fine. If this approach isn't taken, we might want to do so.

(I can do it myself too, we might be best doing what I did here:
https://github.com/ShaharMS/texter/blob/9e3d4b36acccde15f4d988c5d8ec9d519a2a508d/src/texter/general/markdown/MarkdownVisualizer.hx#L129
)
