### ISSUE TITLE
When textfield text is clipped entire line is hidden

### ISSUE THREAD

**Issue by ianharrigan** [openfl/openfl#2499]
So im not sure if this is by design of a bug, but i feel like on previous version of openfl this was working. 

Basically, if you create a multiline textfield and set its height so it will clip the last line of text then the whole line is hidden. I could be wrong, but this feels like incorrect / odd behaviour (i would expect the line to show, but clipped).

```haxe
            var tf = new TextField();
            tf.text = "Line 1\nLine 2\nLine 3\nLine 4";
            tf.border = true;
            tf.x = 100;
            tf.y = 100;
            tf.type = TextFieldType.DYNAMIC;
            tf.selectable = false;
            tf.mouseEnabled = false;
            tf.autoSize = TextFieldAutoSize.LEFT;
            Lib.current.stage.addChild(tf);

            var tf = new TextField();
            tf.text = "Line 1\nLine 2\nLine 3\nLine 4";
            tf.border = true;
            tf.x = 140;
            tf.y = 100;
            tf.type = TextFieldType.DYNAMIC;
            tf.selectable = false;
            tf.mouseEnabled = false;
            tf.height = 55;
            Lib.current.stage.addChild(tf);

            var tf = new TextField();
            tf.text = "Line 1\nLine 2\nLine 3\nLine 4";
            tf.border = true;
            tf.x = 240;
            tf.y = 100;
            tf.type = TextFieldType.DYNAMIC;
            tf.selectable = false;
            tf.mouseEnabled = false;
            tf.height = 60;
            Lib.current.stage.addChild(tf);
```

![image](https://user-images.githubusercontent.com/3024242/122638130-bdce2980-d0f2-11eb-8765-8c0c969741c7.png)

**Comment by flashultra** [comment]
Did you try with latest ( dev) OpenFL  version ? 
I think it's similar as this one : https://github.com/openfl/openfl/issues/2484

**Comment by ianharrigan** [comment]
Yeah, im on latest openfl:

```
c:\SDK\openfl\openfl>git branch -vv
* develop 7f09386c0 [origin/develop] Set extension property
```

Cheers,
Ian

**Comment by dimensionscape** [comment]
Sadly, this is actually the correct flash behavior. I would love to come to some kind of consensus to go beyond mimicking flash behavior and improving upon the flash expectations, but this is still under some amount of debate.

This is your sample code built with flash/air. 

![screenshot](https://i.gyazo.com/7c14bae1c68f2f7cd4e95f753d9e57d8.png)

**Comment by ianharrigan** [comment]
Fair enough... ive worked around it in haxeui-openfl so it doesnt have any "serious" impact... I do agree with you about the flash api... its a little outdated, and who knows, maybe this is a bug there - so wouldnt make sense to repro bugs in openfl... but, then where do you draw the line... ... 

anyways, thanks for the clarification!

Ian

**Comment by dimensionscape** [comment]
No problem. I closed the issue but I've made an internal memo to address this at some point in time.
