### ISSUE TITLE
TextField restrict bug

### ISSUE THREAD

**Issue by alexander982** [openfl/openfl#2503]
**Describe the bug**
Not documented behavior for restrict field of openfl.text.TextField with following restrict string `"^|#"`. After that I can enter only symbos `^` and `#`.

**To Reproduce**
In AddingText sample add lines:
```
	textField.selectable = true;
	textField.type = TextFieldType.INPUT;
	textField.restrict = "^|#";
        // and change
       textField.text = "";
```

**Expected behavior**
I want to restrict user from entering symbols `#` and `|`.

**OpenFL Targets**
HTML5, Hashlink, HXCPP

Haxe 4.2.2, OpenFL 9.1.0

**Comment by joshtynjala** [comment]
This issue appears to have been fixed at some point, so I am closing.

I am guessing that it is commit openfl/openfl@06a823acbac01f2a7e988845aeb00ce43059ff98
