### ISSUE TITLE
openfl 9 input textfield and Gboard keyboard doesnt work well in html5

### ISSUE THREAD

**Issue by piratejet** [openfl/openfl#2506]
**Describe the bug**
after updating the openfl to 9th version in html input textfields work strangely with Gboard (google keyboard) on mobile.
when you type, some letters are not visible until you press remove or "." or "@" or some other symbols.

i noticed that before openfl 9 it wasnt showing suggestions on the Gboard. maybe that is causing it.

**To Reproduce**
1.  activate Gboard keyboard on mobile
2. compile openfl project in html  and open it with mobile browser
3. type in input textfield
4. check how it behaves

**Expected behavior**
when you type on keyboard, the letters should be visible in the textfield right away.

**OpenFL Targets**
openfl 9

**Comment by spielepalast** [comment]
Is there any update regarding this issue?

**Comment by joshtynjala** [comment]
Closed with openfl/lime@e03cc18d31392b40f8079c4d53b17830abbc9dca
