### ISSUE TITLE
I get 'Uncaught exception - Invalid field access : get_x', why?

### ISSUE THREAD

**Issue by katashisano** [openfl/openfl#2516]
I started learning Haxe with OpenFL, so, to challenge myself, I wanted to make a Flappy Bird copy, I tried to delete obstacles by getting its x position, but when I tested it, I got this:
```
Called from Main.hx line 116
Called from openfl/events/EventDispatcher.hx line 402
Called from a C function
Called from openfl/display/DisplayObject.hx line 1399
Called from openfl/display/Stage.hx line 1159
Invalid field access : get_x
Called from ? line 1
Called from ApplicationMain.hx line 25
Called from ApplicationMain.hx line 130
Called from lime/app/Application.hx line 150
Called from lime/_internal/backend/native/NativeApplication.hx line 146
Called from a C function
Called from lime/_internal/backend/native/NativeApplication.hx line 370
Called from lime/_internal/macros/EventMacro.hx line 91
Called from openfl/display/Stage.hx line 1950
Called from openfl/display/Stage.hx line 1163
Called from openfl/display/Stage.hx line 1423
Called from openfl/display/Stage.hx line 1159
Called from openfl/display/DisplayObject.hx line 1399
Called from a C function
Called from openfl/events/EventDispatcher.hx line 402
Called from Main.hx line 116
Uncaught exception - Invalid field access : get_x
```
I tried many things to try to solve it, but nothing worked, could someone please help me?
Here's the source:
https://github.com/katashisano/flappy_fly

Code Editor: Visual Studio Code
Haxe version: 4.2.4
OpenFL version: 9.1.0
Lime version: 7.9.0

**EDIT:** I got the game to work, but, I still don't understand what was the problem, so, could you please solve this issue?

**Comment by joshtynjala** [comment]
This is the code on line 116:

> if (obstacles[0].x < this.x-64)

My guess is that `obstacles.length` is 0, so `obstacles[0]` is `null`. That would cause the invalid field access error.

**Comment by barisyild** [comment]
> This is the code on line 116:
> 
> > if (obstacles[0].x < this.x-64)
> 
> My guess is that `obstacles.length` is 0, so `obstacles[0]` is `null`. That would cause the invalid field access error.

Yeah you are right, i tested.

```haxe
if (obstacles[0].x < this.x-64)
```

can be changed to

```haxe
if (obstacles.length != 0 && obstacles[0].x < this.x-64)
```

**Comment by katashisano** [comment]
Oh, thank you guys!!
