### ISSUE TITLE
GC causes crashing in iOS15

### ISSUE THREAD

**Issue by Continuities** [openfl/openfl#2519]
**Describe the bug**
Random crashes on iOS15. Research suggests it's GC-related, as described in this hxcpp issue: https://gitmemory.cn/repo/HaxeFoundation/hxcpp/issues/969?page=3

**To Reproduce**
1. Build for iOS15
2. Deploy to a release build to a physical device
3. Wait for random crashes

**Expected behavior**
No crashing

**OpenFL Targets**
iOS 15

**Additional context**
Investigation seems to have already been completed over at hxcpp (https://gitmemory.cn/repo/HaxeFoundation/hxcpp/issues/969?page=3). Should be an easy fix?

**Comment by justin-espedal** [comment]
The fix for that specific issue was already merged into Lime. https://github.com/haxelime/lime/pull/1485

If the version of Lime you're using doesn't include that fix, please update. If it does, you're facing a different issue.

**Comment by Continuities** [comment]
Ah, sorry! I see that the fix just hasn't made it into a Lime release yet. Guess I'll build it myself in the meantime.
Thanks!
