### ISSUE TITLE
[Neko] Mojibake (garbled characters) in TextField

### ISSUE THREAD

**Issue by mandel59** [openfl/openfl#256]
Unicode characters in TextField are garbled when the target is Neko VM.

Neko VM:
![Screenshot-Neko](https://cloud.githubusercontent.com/assets/1079715/3208262/92295524-ee24-11e3-8bd6-b0383c8d6048.png)

Comparison C++:
![Screenshot-Mac](https://cloud.githubusercontent.com/assets/1079715/3208251/0dcc22c0-ee24-11e3-8b82-5646fa42f8c1.png)
(Since the font doesn't support hiragana and kanji, they are represented as small boxes, and so it isn't a bug.)

The test code:

``` haxe
package;

import openfl.display.Sprite;
import openfl.text.TextField;

class Main extends Sprite {
    public function new () {
        super ();

        var tf = new TextField();
        tf.textColor = 0x000000;
        tf.text = "hello world/áåé/あいう/𩸽/";
        this.addChild(tf);
    }
}
```

**Comment by jgranick** [comment]
Moved to https://trello.com/c/xI2A76zD/14-improve-utf-8-text-support-in-openfl-text-textfield

**Comment by jgranick** [comment]
https://github.com/openfl/openfl/issues/1402
