### ISSUE TITLE
class type check?

### ISSUE THREAD

**Issue by katashisano** [openfl/openfl#2563]
Working on my game engine and making a component system like Unity's, I wanted to make a getComponent() function to get components by its type (e.g.: Physics Body, Collider, Animator...)

__so the questions are ->__
Is it possible to do this without an enumerator? how?
Is there a way to check equality for a subclass type? (e.g.:  if (component).class == PhysicsBody)
If not, how can I check if a component is part of a subclass?

__EDIT:__
Haxe version: 4.2.4
Lime version: 7.9.0
OpenFL version: 9.1.0

Target: neko

**Comment by dpomier** [comment]
You may want to check [Std.isOfType](https://api.haxe.org/Std.html#isOfType) and [Std.downcast](https://api.haxe.org/Std.html#downcast). You can also do `if (component is Collider)`.

This is more a question for [the Haxe forum](https://community.haxe.org/) :)

**Comment by katashisano** [comment]
It worked, thanks.
