### ISSUE TITLE
Openfl 9.1.0 textfield bug on html5 target mobile

### ISSUE THREAD

**Issue by piratejet** [openfl/openfl#2564]
**Describe the bug**
when you type on a mobile keyboard, letters are not shown right away in the text input.

**To Reproduce**
1. enable google Gboard as a default keyboard. (it also happens on swift keyboard but not always
2. click input textfield
3. start typing

**Expected behavior**
letters should be shown right away

**Screenshots**
here I created a sample project for both openfl 8.9.6 and 9.1.0. the difference between them is that in 8.9.6 there is no suggestion texts on the keyboard:

openfl 9.1.0

<img src="https://user-images.githubusercontent.com/15813644/171351676-2d5c801f-9b1c-4fb7-83c5-1ef5ff103914.gif" width="300"/>

openfl 8.9.6

<img src="https://user-images.githubusercontent.com/15813644/171351617-1b191b60-3587-4f3f-9ac0-43fd4f419183.gif" width="300"/>

**OpenFL Targets**
html5

**Comment by spielepalast** [comment]
Hi there,

is there any status update regarding this ticket. Do we have the possibility to push this ticket or giva a bounty on this.

BR,
Spiele Palast

**Comment by joshtynjala** [comment]
Have you tried the latest OpenFL code from Github? A number of TextField issues have been fixed, but I don't know for sure if this one has.

**Comment by piratejet** [comment]
> 

unfortunately it didn't help

**Comment by piratejet** [comment]
i beleive it has a bug from this commit cd2086d332dd236161f867a48a89aa18ababfb27

**Comment by spielepalast** [comment]
Is there any update on this ticket?

**Comment by joshtynjala** [comment]
I can reproduce this issue in Chrome on Android, but not in Safari on iOS.

**Comment by joshtynjala** [comment]
In Lime's `HTML5Window` class, it returns early from the "input" event listener here:

https://github.com/openfl/lime/blob/8.0.0/src/lime/_internal/backend/html5/HTML5Window.hx#L544

That line was added in the following commit:

openfl/lime@8e7ab67745ceee17f61d2ff0a8f186a63c4fd5dc

It seems that something on Android is behaving as an input method editor (IME), which is strange.

**Comment by joshtynjala** [comment]
So it turns out that almost all keyboards on Android act as IMEs. Including English and other Latin alphabet languages that don't normally require IME. Either that commit needs to be reverted, or Lime needs to expose IME events that `TextField` can listen for.
