### ISSUE TITLE
`openfl_pool_events` shouldn't work anymore, but is still a valid define

### ISSUE THREAD

**Issue by ShaharMS** [openfl/openfl#2571]
I'm making a list containing all openfl's compile arguments (or defines).

While checking the purpose of `openfl_pool_events`, i noticed those instances all point to `Event.__pool` and do their "event stuff" on there:
![image](https://user-images.githubusercontent.com/88977041/177138231-71c3d958-dd2a-4a5a-ba9a-a5751d9434bb.png)

Problem is: this field has been commented about 1.5 years ago (!)
![image](https://user-images.githubusercontent.com/88977041/177138500-f1419683-62b2-4d6e-9fa8-e1335c4bd230.png)

(I know i only gave one example, but from the various instances i checked, all event classes have `__pool` commented out, and the `openfl_pool_events` option)

Should this be removed?

**Comment by joshtynjala** [comment]
I recently fixed `openfl_pool_events` in commit 65cfc2d5fb8cc417bb0232f4c5123822c58aed10

**Comment by ShaharMS** [comment]
nice, ill close this then
