### ISSUE TITLE
Instantiating a new URLLoader causes a segmentation fault

### ISSUE THREAD

**Issue by ShaharMS** [openfl/openfl#2573]
## **Describe the bug**
When instantiating a new URLLoader with a new URLRequest, like this:
```haxe
var request = new URLLoader(new URLRequest('https://spacebubble.io/apps/ezworksheet/program/Windows/alpha-0.0.0.zip'));
```

I'm getting an Access violation (segfault):
```txt
Uncaught exception: Access violation
Called from lime.net.curl.CURLMulti.perform(lime/net/curl/CURLMulti.hx:67)
Called from lime._internal.backend.native.$NativeHTTPRequest.multiThreadPool_doWork(lime/_internal/backend/native/NativeHTTPRequest.hx:508)
Called from lime.app._Event_Dynamic_Void.dispatch(lime/_internal/macros/EventMacro.hx:91)
Called from lime.system.ThreadPool.runWork(lime/system/ThreadPool.hx:150)
Called from lime.system.ThreadPool.queue(lime/system/ThreadPool.hx:95)
Called from lime._internal.backend.native.NativeHTTPRequest.loadData(lime/_internal/backend/native/NativeHTTPRequest.hx:327)
Called from lime._internal.backend.native.NativeHTTPRequest.loadText(lime/_internal/backend/native/NativeHTTPRequest.hx:345)
Called from lime.net._HTTPRequest_String.load(lime/net/HTTPRequest.hx:140)
Called from openfl.net.URLLoader.load(openfl/net/URLLoader.hx:313)
Called from openfl.net.$URLLoader.__constructor__(openfl/net/URLLoader.hx:169)
Called from _Config.$Config_Fields_.startDownloadWithSaveAndBar(Config.hx:27)
Called from fun$4091(AutoUpdater.hx:59)
Called from haxe.$Timer.~delay.0(haxe/Timer.hx:244)
Called from lime._internal.backend.native.NativeApplication.updateTimer(lime/_internal/backend/native/NativeApplication.hx:586)
Called from lime._internal.backend.native.NativeApplication.handleApplicationEvent(lime/_internal/backend/native/NativeApplication.hx:173)
Called from lime._internal.backend.native.NativeApplication.exec(lime/_internal/backend/native/NativeApplication.hx:146)
Called from lime.app.Application.exec(lime/app/Application.hx:150)
Called from $ApplicationMain.create(ApplicationMain.hx:135)
Called from $ApplicationMain.main(ApplicationMain.hx:26)
Called from .init(?:1)
```

I tested again in a separate project, and still, the same error.

## **To Reproduce**

Create a new project, and place this line in `Main`:
```haxe
var request = new URLLoader(new URLRequest('https://spacebubble.io/apps/ezworksheet/program/Windows/alpha-0.0.0.zip'));
```

## **Expected behavior**
OpenFL should download the zip file the domain points to.
You can check that domain, and see for yourself that it does exist

## **Screenshots**
![image](https://user-images.githubusercontent.com/88977041/177509967-e7abb021-0a1e-459b-95df-c46f05ac14ba.png)

## **OpenFL Targets**
Effects:
 - `hl/debug`
 - `hl/final`
Doesnt Effect:
 - `hl`

**Comment by ShaharMS** [comment]
# Update

In Hashlink, the app doesnt crash, but the request doesnt load anything/throw any error

**Comment by ShaharMS** [comment]
# Another Update

Running the same thing in `neko` & `neko/debug` does install the file, but crashes right before it finishes downloading:
```
Called from sys.thread.Lock::$statics line 1
Called from ApplicationMain::main line 26
Called from ApplicationMain::create line 135
Called from lime.app.Application::exec line 150
Called from lime._internal.backend.native.NativeApplication::exec line 146
Called from a C function
Called from lime._internal.backend.native.NativeApplication::handleApplicationEvent line 175
Called from lime.app._Event_Int_Void::dispatch line 91
Called from lime.system.ThreadPool::__update line 185
Called from lime.app._Event_Dynamic_Void::dispatch line 91
Called from lime._internal.backend.native.NativeHTTPRequest::multiThreadPool_onProgress line 574
Called from lime.app.Promise_haxe_io_Bytes::complete line 108
Called from lime._internal.backend.native.NativeHTTPRequest::loadText line 352
Called from lime._internal.backend.native.NativeHTTPRequest::buildBuffer line 367
Called from haxe.io.BytesBuffer::getBytes line 204
Uncaught exception - std@buffer_string
```

**Comment by joshtynjala** [comment]
Try this:

```haxe
var request = new URLLoader();
request.dataFormat = URLLoaderDataFormat.BINARY;
request.addEventListener(Event.COMPLETE, event -> {
	trace("Complete");
});
request.load(new URLRequest('https://spacebubble.io/apps/ezworksheet/program/Windows/alpha-0.0.0.zip'));
```

By default, `dataFormat` is `URLLoaderDataFormat.TEXT`, so it tries to interpret your .zip file as a text file.

**Comment by ShaharMS** [comment]
Yeah, didn't update the issue but I spoke about that issue with @Dimensionscape and he told me to do that. we came to the conclusion that simply doesn't work on HL, but does work on neko

**Comment by ShaharMS** [comment]
So the issue should remain open

**Comment by joshtynjala** [comment]
Hmmm... but it worked on HL for me. I see the `trace("Complete")` output in my console when I run that code.

**Comment by ShaharMS** [comment]
Hl/debug

Hl just doesn't start downloading data

**Comment by joshtynjala** [comment]
I was able to reproduce on HL initially, but not after I changed the code. Did you switch to calling `load()`, or do you still pass the `URLRequest` to the `URLLoader` constructor? It works for me using `load()`. I think that using `load()` is necessary because you need to configure the appropriate `dataFormat` _before_ it tries to start loading anything.

**Comment by joshtynjala** [comment]
Actually, I figured out how to reproduce. If I run `openfl test hl -debug`, I get the exception you mention. Without `-debug`, it works correctly.

**Comment by joshtynjala** [comment]
I deleted my _lime.hdll_ and _lime-debug.hdll_ files and ran `lime rebuild hl -release`, and now it works for `openfl test hl -debug`. No exception anymore.

**Comment by ShaharMS** [comment]
The question is - does it download anything, or just not crash?

**Comment by joshtynjala** [comment]
The `Event.COMPLETE` listener is called, and the value of `bytesAvailable` is 9192260.

```haxe
var request = new URLLoader();
request.dataFormat = URLLoaderDataFormat.BINARY;
request.addEventListener(Event.COMPLETE, event -> {
	trace("Complete: " + cast(request.data, ByteArray).bytesAvailable);
});
request.load(new URLRequest('https://spacebubble.io/apps/ezworksheet/program/Windows/alpha-0.0.0.zip'));
```

**Comment by ShaharMS** [comment]
Nice! I'll document this error when i have the time, and I'm closing this issue

**Comment by ShaharMS** [comment]
Reopening because Event.PROGRESS isnt called, and its a pretty big part that makes URLLoader more useful than haxe's Http

**Comment by ShaharMS** [comment]
actually closing cause its confusing, oops😂
