### ISSUE TITLE
BitmapData.draw(stage) gives wrong output

### ISSUE THREAD

**Issue by bendmorris** [openfl/openfl#260]
I'm using HaxePunk on Linux/C++ with drawTiles for rendering. I'm trying to take in-game screenshots and have a strange problem.

To take a screenshot, I use the following code:

    var screenshotBuffer:BitmapData = new BitmapData(HXP.windowWidth, HXP.windowHeight);
    screenshotBuffer.draw(HXP.stage);

...and then save screenshotBuffer to a file.

Here's the screen I'm taking a screenshot of (the debug console, hitboxes, etc. will be hidden prior to saving the screenshot):

![screenshot 2014-06-13 20 43 45-2](https://cloud.githubusercontent.com/assets/544977/3277462/8e08dae4-f376-11e3-8b38-daf37af62f8d.png)

...and here's what is saved:

![screenshot 2014-06-13 20 43 45](https://cloud.githubusercontent.com/assets/544977/3277463/9d9b0ee6-f376-11e3-9609-3932367c45c3.png)

This is exactly the same scene at the same time and the game is paused so nothing has changed. The bullet trail and explosion are identical, but some objects (the ship, various asteroids) are rotated and/or translated from how they were actually drawn to the screen.

Any idea what could be causing this? If anyone can point me in the right direction, I'm happy to try to fix this myself.

**Comment by jgranick** [comment]
This should be resolved in newer builds, we're pushing hard to have consistency in software and hardware for this :smile:
