### ISSUE TITLE
ColorMatrixFilter properties won't change dynamically except on flash target

### ISSUE THREAD

**Issue by MatseFR** [openfl/openfl#2604]
**Describe the bug**
Once applied to a DisplayObject instance, changing ColorMatrixFilter won't do anything after a frame passed (even when reassigning `displayObject.filters = [myFilter]` )

**To Reproduce**
1. Click on "apply grayscale"
2. Nothing happens visually

**Expected behavior**
the image on the right should turn to grayscale (it does on flash target)

**OpenFL Targets**
I have tested the issue on Neko, Windows and html5 targets (here is an html5 demo of it : https://matse.skwatt.com/haxe/debug/ColorMatrixFilter/ )

**Additional context**
the sample file uses FeathersUI as it was easier for me, if that's a problem I can create another sample file
[ColorMatrixFilter_test.zip](https://github.com/openfl/openfl/files/10020286/ColorMatrixFilter_test.zip)

**Comment by dimensionscape** [comment]
https://github.com/openfl/openfl/commit/5b295db7003f38c77c152943b1a041b343f85beb Should resolve this issue.
