### ISSUE TITLE
MouseEvent.DOUBLE_CLICK is not firing

### ISSUE THREAD

**Issue by Dimous** [openfl/openfl#2606]
**Describe the bug**
It is simply not firing. All others are firing, but not DOUBLE_CLICK.

**To Reproduce**
```haxe
class Main extends Sprite {
	public function new() {
		super();

		this.addEventListener(MouseEvent.DOUBLE_CLICK, (event) -> {
			trace("TEST");
		});
	}
}
```

**OpenFL Targets**
html5, windows

**Comment by joshtynjala** [comment]
You need to set [`doubleClickEnabled`](https://api.openfl.org/openfl/display/InteractiveObject.html#doubleClickEnabled) to `true` for `MouseEvent.DOUBLE_CLICK` to work. It defaults to `false`.

If that doesn't work, there are also other properties that can affect this event. You may need to set `mouseChildren = false` or `buttonMode = true`.

**Comment by Dimous** [comment]
You are right. Thanks!
