### ISSUE TITLE
openfl with royale compiler to port AS games to JS

### ISSUE THREAD

**Issue by flashmandv** [openfl/openfl#2625]
Hello guys,

I was AS developer for a long time and since the browsers dropped flash support in 2020, I had many games left to die.
But thanks to the Royale SDK and ASJS compiler it is kind of possible to revive some old games.

I took the ambitious path of restoring 2 of my old games by "compiling" the AS directly to JS without rewriting the entire codebase to Haxe (that was my goal).
I've seen that openfl has npm package so the npm openfl + royale asjs compiler produces html5 JS output..but so many things weren't working and required rewriting. 
MovieClip loading from Animate(Flash) fla/swf file wasn't supported in the last npm version 8.9.6...so I decided to extend the OpenFL JS library to include this. 
I took the JS source from the Haxe OpenFL JS and migrated `swf_exporters_animate_AnimateLibrary` related code  to the npm version of OpenFL. 
Now is possible to load swf (after openfl process command) and I also added dynamic MovieClip access (movie.child.subChild..) and basic timeline functionality to auto stop when 'stop' label is shown.
I also fixed one mp3 audioplay bug (some mp3 file were not playing because of that bug).

Now I finally have my 2 games ported to JS, but there are still things that are not working (**hitTest** methods are always returning false).
Here is my repository with ready to run demo project: [@flashmandv/openfl-royale](https://github.com/flashmandv/openfl-royale)
Starling is also fully working (but FeathersUI is not). I could use the GreenSock library by making gsap.as dummy file and it was all working in the JS output. WebSockets work as well.
Any help is welcome. Ideally some of my fixes would be good to be added to a new version of the npm openfl library.
![image](https://user-images.githubusercontent.com/2466808/226324958-e0b93fe9-c53a-44ab-a9f8-e32e5044abaf.png)

Cheers

**Comment by joshtynjala** [comment]
Adding the following Royale compiler options to the `additionalOptions` section of your asconfig.json file may improve things a bit:

`-js-getter-prefix=get_`
`-js-setter-prefix=set_`

Royale's default naming for JS getters and setters doesn't match Haxe's. These options allow you to override that behavior so that Royale can target OpenFL better.

**Comment by flashmandv** [comment]
Thank you @joshtynjala , that is super helpful. I remember when trying to make feathersui to work it had compile errors about gettters and setters not properly overriding DisplayObject. I guess this will fix it and feathers ui may work.

Do you have any suggestion about the hitTest method? I tried to debug it and I got to the point where bitmap data is compared with low level bit shift checks to the matrix..but It is super confusing to debug.  
For instance, hitTest between point and BitmapData comes down to lime.graphics.ImageDataUtil.getPixel32 function..which is always returning false (0).

I assume the code itself is working but maybe there is some incompatibility between the format (bitrate) of the exported from flash bitmap data and the one the JS code expects...I don't know.

**Comment by joshtynjala** [comment]
> Do you have any suggestion about the hitTest method?

Sorry. No idea.

**Comment by flashmandv** [comment]
Maybe regarding this I have to ask [jgranick](https://github.com/jgranick)
