### ISSUE TITLE
Openfl TextField::stage_onMouseUp() issue

### ISSUE THREAD

**Issue by piratejet** [openfl/openfl#2627]
**Describe the bug**
i found some strange lines of code in stage_onMouseUp function. and in some cases it failed for me to get stage.focus. 

this is first strange thing: 
`var stage:Stage = cast event.currentTarget;`

why stage is event.currentTarget which is Textfield not Stage.

then it checks 
`if (this.stage == null) return;`

and directly after that it checks stage.focus which is not the stage focus but the textfield focus and the textfield soesnt have focus method. and this in some cases created an exceptions for me 

`if (stage.focus == this)`

![Code_3cfH4qsqQt](https://user-images.githubusercontent.com/15813644/228536313-ed264e9e-ad6a-4139-95fa-5c54464a0d8f.png)

**OpenFL Targets**
9.2

**Comment by joshtynjala** [comment]
> why stage is event.currentTarget which is Textfield not Stage.

`MouseEvent.MOUSE_UP` is a bubbling event. When an event bubbles, it initially gets dispatched by `event.target`. Then it gets dispatched by the parent of `event.target`, then that object's parent, and so on, until it reaches to the stage. In an event listener, `event.currentTarget` refers to the object where you called `addEventListener()`. In this case, the listener was added to the stage, here:

`stage.addEventListener(MouseEvent.MOUSE_UP, stage_onMouseUp);`

https://github.com/openfl/openfl/blob/9.2.1/src/openfl/text/TextField.hx#L3290

With that in mind, inside `stage_onMouseUp`, `event.target` is the `TextField` and  `event.currentTarget` is the stage.

> Then it checks if (this.stage == null) return;

If the `TextField` was removed from its parent with `removeChild()` in another listener to `MouseEvent.MOUSE_UP` that was called before the one in `TextField`, it won't prevent the listener in `TextField`  from being called. However, if the `TextField` is no longer on stage, we don't want to run the rest of the code in the listener.

To determine whether the `TextField` is no longer on stage, we check if  the value of `this.stage` is `null` or not. If null, we should return without running the rest of the code.

> and directly after that it checks stage.focus which is not the stage focus but the textfield focus and the textfield soesnt have focus method.

I'm not sure that I understand what this means. Can you explain in more detail, please?

> and this in some cases created an exceptions for me

Which exceptions do you get? If you get an exception, it's always a good idea to provide the details, such as its message  and stack trace (if available). It's virtually guaranteed that someone will ask you for them.

**Comment by piratejet** [comment]
> > why stage is event.currentTarget which is Textfield not Stage.
> 
> `MouseEvent.MOUSE_UP` is a bubbling event. When an event bubbles, it initially gets dispatched by `event.target`. Then it gets dispatched by the parent of `event.target`, then that object's parent, and so on, until it reaches to the stage. In an event listener, `event.currentTarget` refers to the object where you called `addEventListener()`. In this case, the listener was added to the stage, here:
> 
> `stage.addEventListener(MouseEvent.MOUSE_UP, stage_onMouseUp);`
> 
> https://github.com/openfl/openfl/blob/9.2.1/src/openfl/text/TextField.hx#L3290
> 
> With that in mind, inside `stage_onMouseUp`, `event.target` is the `TextField` and `event.currentTarget` is the stage.
> 
> > Then it checks if (this.stage == null) return;
> 
> If the `TextField` was removed from its parent with `removeChild()` in another listener to `MouseEvent.MOUSE_UP` that was called before the one in `TextField`, it won't prevent the listener in `TextField` from being called. However, if the `TextField` is no longer on stage, we don't want to run the rest of the code in the listener.
> 
> To determine whether the `TextField` is no longer on stage, we check if the value of `this.stage` is `null` or not. If null, we should return without running the rest of the code.
> 
> > and directly after that it checks stage.focus which is not the stage focus but the textfield focus and the textfield soesnt have focus method.
> 
> I'm not sure that I understand what this means. Can you explain in more detail, please?
> 
> > and this in some cases created an exceptions for me
> 
> Which exceptions do you get? If you get an exception, it's always a good idea to provide the details, such as its message and stack trace (if available). It's virtually guaranteed that someone will ask you for them.

why not like this

![Code_3T88yTx1mb](https://user-images.githubusercontent.com/15813644/231109109-b8347458-c07a-4370-a0b6-e75679f70441.png)

**Comment by piratejet** [comment]
I'm facing an issue with some input text fields where a single click selects text when I move the mouse. I'm uncertain whether this issue stems from OpenFL or my code. While making a patch, I sometimes need to call stage_onMouseUp with private access. However, if I set it to null, it fails for sure. If I get the click event and pass it to stage_onMouseUp, it also fails. This happens because the event.currentTarget is a text field, but it's perceived as a stage, and the stage.focus method doesn't work on text fields. It's possible that I am missing something, but this is my current understanding of the issue. 

but for me the modified version in the picture above works great

**Comment by joshtynjala** [comment]
We definitely need to cast `event.currentTarget` as `Stage` in this listener because `this.stage` could be set to `null` before the listener is called (more common than you think), or the `TextField` could have been removed from stage and added to a different stage (rare, but technically possible if you have multiple windows on desktop). The listeners must be removed from the `Stage` that is stored in `currentTarget`.

Manually calling `stage_onMouseUp` with a `MouseEvent` that has a different `type` or `currentTarget` is not supported.

Looking back at the original code, I think that this line could change a bit:

```haxe
if (this.stage == null) return;
```

This is probably better:

```haxe
if (this.stage != stage) return;
```

**Comment by piratejet** [comment]
@joshtynjala 

I discovered an issue related to the MouseUtil class I created, which caused problems with the mouse up events. Specifically, the events were not being properly removed, resulting in unintended behavior such as automatic text selection when clicking once and moving the mouse. In light of this, I recommend modifying the code as follows. What are your thoughts on this proposed solution?

so the problem here is that for me in some cases event.currentTarget is MouseUtil class and it doesnt remove the event listener which causes the problem for me. for others it might not be a problem but anyway why not get the textfield stage itself it the event.currentTarget is not a stage

```
var stage:Stage;
if (event.currentTarget is Stage)
	stage = cast event.currentTarget;
else 
	stage = this.stage;
```

**Comment by joshtynjala** [comment]
@piratejet You're calling a private API in a way that it was not intended to be called. Its implementation could change in the future, and there's no guarantee that a special workaround created only for you will be preserved, if that happens. I'm afraid I don't think it's a good idea.

Have you tried dispatching an an actual MouseEvent.MOUSE_UP event from the stage, so that this listener gets called normally? That will ensure that currentTarget is the stage, instead of something else. I think a lot of people don't realize that MouseEvent can be manually dispatched, and that it isn't restricted to OpenFL internals only. You probably shouldn't do it often, but it's technically possible, and I think that this would be cleaner than calling a private API directly.
