### ISSUE TITLE
Wrong scrollH when updating caret/cursor position for TextField

### ISSUE THREAD

**Issue by flashultra** [openfl/openfl#2633]
When enter text in Textfield and move the cursor to the end of the field, the cursor doesn't  keep the positon and move backwards
. This was tested with different Openfl and Lime versions (openfl 9.1.0, 9.2. 9.3.0-dev and lime 7.9.0. 8.0.0, 8.2.0-dev)

**To Reproduce**
I'm using Feathersui for test as the have a working versions with openfl 8.9.6 . My code is the following:
```haxe
        var input = new TextInput();
        input.text = "Type something for test here or something not to test";
        addChild(input);
        input.x = 200;
        input.y = 100;
```

Here is the working version using Openfl 8.9.6 :   https://feathersui.com/learn/haxe-openfl/samples/text-input.html

Video with the wrong cursor postion ( varios Openfl versions >= 9.1.0) 

https://user-images.githubusercontent.com/13473027/233835512-d53ee7ec-c84a-48c6-aad6-e9f9e6025c85.mp4

Video with the expected behaviour ( form the Feathersui page with openfl 8.9.6 ) 

https://user-images.githubusercontent.com/13473027/233835457-55205f43-a652-4149-83f1-86692513c041.mp4

**Comment by joshtynjala** [comment]
Based on your videos, it appears to me that the `caretIndex` is updating correctly, and it's actually `scrollH` that is behaving differently.

Interestingly, I just tried Adobe AIR, and the behavior looks much closer to OpenFL 9.2 than to 8.9.6. With that in mind, this doesn't seem like a bug to me. It seems like OpenFL is actually more closely emulating Flash.

**Comment by joshtynjala** [comment]
> Interestingly, I just tried Adobe AIR, and the behavior looks much closer to OpenFL 9.2 than to 8.9.6. With that in mind, this doesn't seem like a bug to me. It seems like OpenFL is actually more closely emulating Flash.

I tested that with Haxe, but I just confirmed the same behavior with pure AS3:

```as3
package
{
	import flash.display.Sprite;
	import flash.text.TextField;
	import flash.text.TextFieldType;

	public class Main extends Sprite
	{
		public function Main()
		{
			stage.nativeWindow.visible = true;
			
			var inputTF:TextField = new TextField();
			inputTF.type = TextFieldType.INPUT;
			inputTF.border = true;
			inputTF.text = "Type something for test here or something not to test";
			addChild(inputTF);
		}
	}
}
```

**Comment by flashultra** [comment]
I haven't tested with Adober AIR or AS3, but this behavior is different from the pure  ```<input .../>``` element in HTML5 ( both videos above are OpenFL --> HTML5) .

For me, the old way (with 8.9.6) is more natural. I checked how it is in HaxeUI ( http://haxeui.org/explorer/#basic/text_inputs ) and it looks like they decided to use 8.9.6 approach.  

If Flash is the expected behavior, I can close the issue.

**Comment by joshtynjala** [comment]
Matching Flash is indeed generally what we're aiming for.

**Comment by flashultra** [comment]
Thank you for your time!

For anyone interested in this issue , the change was introduced in this commit [Simplify library](https://github.com/openfl/openfl/blob/cd2086d332dd236161f867a48a89aa18ababfb27/src/openfl/text/TextField.hx#L2264-L2271) with updating ```tempScrollH``` with +24/-24. 
 
If someone wants to restore the previous behavior, they should change the code to something like this:
```haxe
while (caret.x < tempScrollH && tempScrollH > 0)
{
	tempScrollH = Math.floor(caret.x - 2);
}
if (caret.x > scrollH + width)
{
	tempScrollH = Math.ceil(caret.x - width - 2);
}
```

**Comment by joshtynjala** [comment]
Actually, it was this commit where the change was introduced: a695c3b58792644c1b7940b83a53dec2edd6e89c
