### ISSUE TITLE
Add type check because AIR 50 no longer allows null parameters to Vector constructor

### ISSUE THREAD

**Issue by mallyskies** [openfl/openfl#2634]
In https://github.com/airsdk/Adobe-Runtime-Support/discussions/2522, the Harman AIR team made the decision to throw an exception if the Vector constructor isn't passed UInt as the first parameter. The openfl.Vector class constructor passes null, which throws now throws an exception when Haxe is used to target ActionScript.

**To Reproduce**
1. Install Harman AIR 50.2.2.2 SDK
2. Using Haxe, build a swc or swf target that calls the openfl.display.Tileset constructor (which itself calls the openfl.Vector constructor). Or simply call the openfl.Vector constructor directly.
3. Note the as3 code generated passes in a null object to both parameters of new Vector.<Number>:

```haxe
    var _loc3_:Object = null;
    var _loc4_:Object = null;
    var _loc5_:Array;
    if((_loc5_ = null) != null) {
       _loc6_ = Vector.<Number>(_loc5_);
    }
    else {
       _loc6_ = new Vector.<Number>(_loc3_,_loc4_);
    }
```

**Desired behavior**
Change openfl/src/Vector.hx from:

```haxe
	public inline function new(?length:Int, ?fixed:Bool, ?array:Array<T>):Void
	{
		if (array != null)
		{
			...
		}
		else
		{
			this = new VectorData<T>(length, fixed);
		}
	}
```

to this (adding a type check for both parameters):

```haxe
	public inline function new(?length:Int, ?fixed:Bool, ?array:Array<T>):Void
	{
		if (array != null)
		{
			...
		}
		else
		{
			this = new VectorData<T>((length : Int), (fixed : Bool));
		}
	}
```

The type checks act explicitly coerce null values to 0 (for Int) and false for Bool.

The reason I reference openfl.display.Tileset is because we can fix our own code to always add 0 for length, but we cannot modify openfl to work around its own calls without branching the project. While we may be in the minority of developers still targeting ActionScript, Harman AIR continues to be a robust development platform and we rely on several legacy ANEs that would not be trivial to reproduce.

**Comment by joshtynjala** [comment]
Thanks! You are definitely not the only one still targeting AIR.

**Comment by kidsacademyteam** [comment]
Thanks!

Thinking how to fix the issue in a better way, decided to check repo and voila! 

Agree with Josh.

P.S. Root cause of this ticket - https://github.com/airsdk/Adobe-Runtime-Support/discussions/2522

**Comment by kidsacademyteam** [comment]
Root cause of this ticket - https://github.com/airsdk/Adobe-Runtime-Support/discussions/2522
