### ISSUE TITLE
There's no memory usage profiler for HashLink during runtime

### ISSUE THREAD

**Issue by TheHENOOB** [openfl/openfl#2640]
https://github.com/HaxeFlixel/flixel/issues/2800
![image](https://github.com/openfl/openfl/assets/74883505/12ee5bb6-4351-410d-9279-32e94ea73038)

The bug has been found on HaxeFlixel, this image is from a blank HaxeFlixel project running on HashLink.
The stats utilize the `openfl.system.System.totalMemory` property to get the memory usage during runtime, other compliation targets that isn't Javascript, Native (C++), Neko or Flash will get the property return 0.

OpenFL does not have an memory usage profiler for HashLink yet.
https://github.com/openfl/openfl/blob/develop/src/openfl/system/System.hx#L256

**Comment by joshtynjala** [comment]
Just merged in #2561, which adds support for System.gc() and System.totalMemory in HL.
