### ISSUE TITLE
[HashLink] Explicit cast from the OpenGLRenderer class

### ISSUE THREAD

**Issue by Sword352** [openfl/openfl#2655]
While I was debugging my project, I got a crash telling me that a FloatVector was getting casted to `i32`, which I don't really understand?
Here is the crash log:
![image-3](https://github.com/openfl/openfl/assets/99792114/2a316634-63a6-4a17-8e9a-0360a12ba3fa)
This seems to only happen on the HashLink target.
What do?

**Comment by joshtynjala** [comment]
I would guess that `i32` means `Int`. So something seems to be trying to cast `Vector<Float>` to `Int`, for some reason.

It seems to be related to drawing graphics, so you might try commenting out some of your code with drawing commands to see if you can narrow it down. Like `graphics.drawRect()` or` graphics.lineTo()`, etc.

**Comment by Sword352** [comment]
Thanks, I'll check it out.
