### ISSUE TITLE
Rounded Rectangle swf asset renders incorrectly  

### ISSUE THREAD

**Issue by masqueanthony** [openfl/openfl#2663]
This rounded rectangle asset started rendering incorrectly at certain scale values with the commit mentioned below (between 9.2.0 and 9.2.1)

1. Run sample program
2. You will see issue as shown in screen shot

Run sample app with the display.rotation = 0.001; line uncommented to see how it looks (and our current workaround)

![image](https://github.com/openfl/openfl/assets/6988825/9a06aa63-409d-4210-8e90-40333386d37d)

Issue started in this commit: https://github.com/openfl/openfl/commit/bb8a97d717c819769d21d8019b4f6fe355cdbe34
html5 target.

**Additional context**
Demo project
[RRectDemo.zip](https://github.com/openfl/openfl/files/12717384/RRectDemo.zip)

**Comment by joshtynjala** [comment]
Can you add a screenshot that shows how it's supposed to look too? Thanks!

**Comment by masqueanthony** [comment]
![image](https://github.com/openfl/openfl/assets/6988825/bcfdfe6b-afe1-4269-b832-23fdfba5bc8f)
Modify sample code as follows to show correct rendering:
		Assets.loadLibrary ("WCCmessageUI.swf").onComplete (function (_) {
			var message = Assets.getMovieClip ("WCCmessageUI.swf:WCCsysMsg");
			mc = getClip(message);
			mc.rotation = 0.001;
			addChild(mc);

**Comment by joshtynjala** [comment]
Thanks!

**Comment by joshtynjala** [comment]
This appears to be fixed in commit b630fb80ae5e2ca7b2bba7f9ad6139cc82bf0264. The fix will be included in the next update.
