### ISSUE TITLE
Sounds over a certain length do not play properly.

### ISSUE THREAD

**Issue by Jaduplex** [openfl/openfl#2666]
I originally posted this on the HaxeFlixel repository, but it turned out to be an issue with OpenFL and lime.

Sounds over a certain length, seemingly around 25 minutes, do not play properly. An acquaintance discovered the details regarding the reason for this, and how to fix it:

![image](https://github.com/openfl/openfl/assets/65635932/a86970bd-71cd-4aac-bacf-7e0a89d779a9)

Read below for additional details:
https://github.com/HaxeFlixel/flixel/issues/2899

**Comment by joshtynjala** [comment]
> An acquaintance discovered the details regarding the reason for this, and how to fix it:

Unfortunately, this screenshot does not make clear "how to fix it" at all. If I had to guess, the "how to fix it" part is in the thumbnails that are cropped? Please ask your acquaintance to explain in a bit more detail (without images) what needs to be changed, or to submit a pull request with the necessary changes.

**Comment by Jaduplex** [comment]
Alright, I'll do a pull request.

**Comment by CyndaquilDAC** [comment]
Pull requests are open: 

https://github.com/openfl/openfl/pull/2667
https://github.com/openfl/lime/pull/1716

**Comment by Jaduplex** [comment]
Apparently, the fix has been merged.
