### ISSUE TITLE
[html5] FileReferenceList doesn't dispatch Event.CANCEL

### ISSUE THREAD

**Issue by MatseFR** [openfl/openfl#2672]
When calling <FileReferenceList>.browse() and cancelling the file dialog, the FileReferenceList instance should dispatch Event.CANCEL : right now it doesn't

OpenFL 9.3.1 + Lime 8.1.0

**Comment by joshtynjala** [comment]
Copying my reply from the forums:

> As I recall, there isn’t a consistent way to detect that the file dialog displayed by FileReference has been cancelled on the html5 target. The current implementation in FileReference can detect certain situations where 0 files are selected, but not necessarily when the Cancel button is clicked. It’s unfortunate, but I don’t think it can be made any better than it currently is.

Source: https://community.openfl.org/t/openfl-9-3-0-and-lime-8-1-0-release/13807/21?u=joshtynjala

I found commit b93476ba8fc9f3488e110ce14e6cdc0318fb077f where I specifically mentioned this limitation.
