### ISSUE TITLE
Custom fonts don't support bold or italic variants on Windows

### ISSUE THREAD

**Issue by Starmapo** [openfl/openfl#2682]
**Describe the bug**
When using a custom font on a text field and compiling to a desktop target, changing the `bold` and `italic` values of the format doesn't change the visual display at all, and it instead stays in the regular form.

**To Reproduce**
This code snippet reproduces the issue:
```haxe
package;

import openfl.Assets;
import openfl.display.Sprite;
import openfl.text.Font;
import openfl.text.TextField;
import openfl.text.TextFormat;

class Main extends Sprite {
	public function new() {
		super();

		var font = Assets.getFont("assets/fonts/Roboto-Regular.ttf");
		Font.registerFont(font);

		createFontSet(font.fontName, 5);
		createFontSet(null, 105);
	}

	function createFontSet(font:String, x:Float) {
		function createTextField(y:Float, bold:Bool = false, italic:Bool = false) {
			var text = new TextField();
			text.x = x;
			text.y = y;
			text.text = "Hello world!";

			var format = new TextFormat();
			format.font = font;
			format.bold = bold;
			format.italic = italic;
			text.setTextFormat(format);

			addChild(text);
		}

		createTextField(5);
		createTextField(35, true);
		createTextField(65, false, true);
	}
}
```
Link to the font: https://github.com/haxeui/component-explorer/raw/master/assets/fonts/Roboto-Regular.ttf

**Expected behavior**
The font displays as the bold and italic variants.

**Screenshots**
On HTML5:
![msedge_U37qi3bGev](https://github.com/openfl/openfl/assets/85134252/4bf460bd-0a52-4532-9016-519e7c5e7f0e)

On C++:
![OpenFLTesting_KEH7IVFqLM](https://github.com/openfl/openfl/assets/85134252/c8bea9a5-1bf2-4cc5-b890-619ff2ef3426)

**OpenFL Targets**
C++, HashLink, and Neko on Windows have this issue. HTML5 works correctly. I am unsure if macOS and Linux have this issue.

**Additional context**
I'm using Haxe 4.3.3, Lime 8.1.1, and OpenFL 9.3.2. I tested it on the default project template, and I'm not embedding the assets or fonts folder through the Project.xml file.

**Comment by joshtynjala** [comment]
Does the file Roboto-Regular.ttf also contain bold and italic variants? Usually, there are separate .ttf files for the variants.

>  C++, HashLink, and Neko on Windows have this issue. HTML5 works correctly. I am unsure if macOS and Linux have this issue.

If I had to guess, HTML5 is probably just using the installed font on your system, and probably isn't even using your .ttf custom font.

**Comment by Starmapo** [comment]
Update: After searching online, I discovered [this StackOverflow answer](https://stackoverflow.com/a/45903810) that says browsers just recreate the bold and italic variants on their own. OpenFL uses the browser's canvas to draw text fields by default, so this seems to be why it only displays the variants there.

I imagine the solution for desktop targets would indeed be to have separate files for the variants, so this issue should be closed unless there's a possibility that automatic bolding/italicizing can be implemented for the Cairo render system (though I have no clue how to do it myself).

> If I had to guess, HTML5 is probably just using the installed font on your system, and probably isn't even using your .ttf custom font.

I do not have the font installed, though it's possible that my testing browser (Microsoft Edge) does include it. Just to be sure, I tried it with a font that definitely shouldn't be there already (https://github.com/haxeui/component-explorer/raw/master/assets/fonts/custom1.ttf), and it still displayed the variants on HTML5:

![msedge_Ywd8gnMyJ3](https://github.com/openfl/openfl/assets/85134252/7e51f27f-f420-419f-ad5c-ada0ad933c91)

**Comment by joshtynjala** [comment]
> browsers just recreate the bold and italic variants on their own

Interesting! I didn't know browsers did that. Well, that explains why html5 vs native targets behave differently. If you want bold and italic to work on all targets, you need to include the .ttf files for those variants too.
