### ISSUE TITLE
Linking to `utest` or `munit` breaks HTML5 target

### ISSUE THREAD

**Issue by Herschel** [openfl/openfl#2687]
**Describe the bug**
If an OpenFL project happens to link to `utest` or `munit`, the application ends up being instantiated twice:
1) from the `embed` call in the HTML5 template: https://github.com/openfl/openfl/blob/c114edd36b6e8118533b664001d68b89eda3833b/assets/templates/html5/template/index.html#L51
2) from an `embed` call in the `ApplicationMain` template, which seems to be specifically for handling test runners: https://github.com/openfl/openfl/blob/c114edd36b6e8118533b664001d68b89eda3833b/assets/templates/haxe/ApplicationMain.hx#L21-L25

This causes havoc as the preloader ends up running twice, loading all assets twice but failing, etc.

**To Reproduce**
1. Unzip this minimal sample: [utest-test.zip](https://github.com/openfl/openfl/files/14300974/utest-test.zip)
2. `haxelib install utest`
3. `openfl test html5`
4. Observe in the browser console output that `Running` is traced twice.

**Expected behavior**
The application is only instantiated once, and `Running` would only print once.

One solution is to avoid linking in these libraries for a non-test build, but it's easy to end up transitively depending on them from other libraries. (In my case we linked to `hmm` to parse some library info, which ended up depending on `utest`, and then the HTML5 target suddenly broke.)

The conditional `#if utest` lines in `ApplicationMain` seem to assume that this is an actual test suite using a different HTML5 template that doesn't embed the application itself, such as `https://github.com/joshtynjala/openfl-utest-sample`. One solution might be for test runners to use a define such as `-D test` to determine if this is an actual test suite as opposed to checking `#if (utest || munit)`. I didn't investigate further to see how feasible this might be.

**OpenFL Targets**
HTML5

**Comment by joshtynjala** [comment]
When I find some time, I intend to clean up this conditional so that tests work with the default html5 template.

I've wondered about that conditional for a number of years, and I just can't come up with a plausible reason why it is there. My best guess is that it's something related to older versions of munit/utest, or older versions of OpenFL/Lime, that has since changed.
