### ISSUE TITLE
openfl.net.FileReference.download(..) do not opens file-browsing dialog in browser

### ISSUE THREAD

**Issue by rat-moonshine** [openfl/openfl#2704]
**Environment**
Lime: Git (origin/develop)
Openfl: Git (origin/develop)
Browser: Windows Edge

**Problem**
I'm trying to download a file from server in a fashioned manner using `FileReference.download(..)` which suppose to open a file-browsing dialog on saving file. (Ref: https://api.openfl.org/openfl/net/FileReference.html#download)

I can see the `ProgressEvent.PROGRESS` outputs in browser console, but neither it opens a file-browsing-dialog, nor the file gets downloaded to user's machine.

**Additional context**
Using `FileReference` codes are basic:

```
class FileDownloaderUsingFileReference extends EventDispatcher
{
    private var callerSuccessHandler:(?output:Dynamic, args:Rest<Dynamic>) -> Void;
    private var callerFailureHandler:(?output:Dynamic, args:Rest<Dynamic>) -> Void;

    private var fileRef:FileReference;

    public function new()
    {
        super();
    }    

    public function download(remoteLocation:String, callerSuccessHandler:(?output:Dynamic, args:Rest<Dynamic>) -> Void, callerFailureHandler:(?output:Dynamic, args:Rest<Dynamic>) -> Void):Void 
    {
        if (this.fileRef != null) {
            configureListeners(false);
        }

        this.callerFailureHandler = callerFailureHandler;
        this.callerSuccessHandler = callerSuccessHandler;

        this.fileRef = new FileReference();
        configureListeners(true);
        this.fileRef.download(new URLRequest(remoteLocation), "Somefile.zip");
    }

    public function dispose():Void
    {
        this.configureListeners(false);
        this.callerFailureHandler = null;
        this.callerSuccessHandler = null;
    }

    private function configureListeners(value:Bool):Void
    {
        if (value)
        {
            this.fileRef.addEventListener(ProgressEvent.PROGRESS, progressHandler, false, 0, true);
            this.fileRef.addEventListener(IOErrorEvent.IO_ERROR, ioErrorHandler, false, 0, true);
            this.fileRef.addEventListener(Event.COMPLETE, completeHandler, false, 0, true);
        }  
        else if (fileRef != null)
        {
            this.fileRef.removeEventListener(ProgressEvent.PROGRESS, progressHandler);
            this.fileRef.removeEventListener(IOErrorEvent.IO_ERROR, ioErrorHandler);
            this.fileRef.removeEventListener(Event.COMPLETE, completeHandler);   
            this.fileRef = null;
        }
    }

    private function progressHandler(event:ProgressEvent):Void 
    {
        var file = cast(event.target, FileReference);
        trace("progressHandler: name=" + file.name + " bytesLoaded=" + event.bytesLoaded + " bytesTotal=" + event.bytesTotal);
    }
    
    private function ioErrorHandler(event:IOErrorEvent):Void 
    {
        this.callerFailureHandler("ioErrorHandler: " + event.toString());
        this.dispose();
    }
    
    private function completeHandler(event:Event):Void 
    {
        this.callerSuccessHandler("File downloaded successfully.");
        this.dispose();
    }
}
```
While trying to download the file from server, I can record the `ProgressEvent.PROGRESS` _trace_ statement, in browser console:

![image](https://github.com/openfl/openfl/assets/24370870/bc26980c-ed65-4a43-9e08-19453649db9f)

**Comment by joshtynjala** [comment]
If your browser is configured to automatically save files to your Downloads directory without asking, I don't think that there is any way in JS for force a file dialog to be displayed.

**Comment by rat-moonshine** [comment]
I checked and I can confirm that nothing been downloaded in Downloads directory during the event. It also wonders me if the bytes get downloaded to any physical file - other than in-memory (that we traced in `ProgressEvent.PROGRESS`).

**Comment by rat-moonshine** [comment]
I checked and I can confirm that nothing been downloaded in Downloads directory during the event. It also wonders me if the bytes get downloaded to any physical file - other than in-memory (that we traced in `ProgressEvent.PROGRESS`). 

UPDATE:

For a safe test, I ran a search in my system (where I was testing) for a file named `Somefile.zip` (that is how the file-name was [suppose](https://github.com/openfl/openfl/issues/2704#issue-2256410780) to be saved), and I found no trace of any. 

I can provide browser's "Network" detail, if that may help.

**Comment by JoelProminic** [comment]
Checking the Firefox debug console, I see that the URL was considered successful.  However, it does not show up in the browser Downloads listing. 

The same URL works as expected in a new tab.  Here is a comparison of the headers:
![image](https://github.com/openfl/openfl/assets/24532731/e65bd1e4-f655-4d99-b9bb-796e45ea4468)

Is the API intercepting the response in this case?

**Comment by joshtynjala** [comment]
Hmm... looking through the code, it appears that `FileReference.download()` is not implemented on the html5 target at this time.

However, it appears that `FileReference.save()` may work. You could try downloading the file with `URLLoader` and then passing the `ByteArray` data to `FileReference.save()`.

**Comment by rat-moonshine** [comment]
I shall check that @joshtynjala . I'll let you know once I done that.

**Comment by rat-moonshine** [comment]
@joshtynjala I confirm following things -

1. When using `FileReference.download`, at `Event.COMPLETE` the `fileReference.data` has _null_ - it appears nothing being stored in the `FileReference` object
2. Used `URLLoader` to download data/ByteArray, and used with `FileReference.save` - saves the file in user's Downloads directory

**Comment by dimensionscape** [comment]
> @joshtynjala I confirm following things -
> 
>     1. When using `FileReference.download`, at `Event.COMPLETE` the `fileReference.data` has _null_ - it appears nothing being stored in the `FileReference` object
> 
>     2. Used `URLLoader` to download data/ByteArray, and used with `FileReference.save` - saves the file in user's Downloads directory

I just included a fix for this in the dev branch. If we're exposing the api, it should at least do something. With the change it works as much as it can in the browser setting. 

It may be possible to support the dialog window in the future. Currently its an experimental feature in Chromes [FileSystem API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_API), but I've been watching it slowly get adopted by other browsers.
