### ISSUE TITLE
Changing "soundTransform.volume" doesn't work for HTML5

### ISSUE THREAD

**Issue by bkhtrv** [openfl/openfl#2713]
In HTML5, the volume of a NetStream video cannot be changed via **soundTransform.volume**

getting **netStream.soundTransform.volume** always returns 1, even if I set it to 0 before that

Am I doing something wrong?

The only workaround I could find is to replace the whole soundTransform with a new SoundTransform:

someVideo.netStream.soundTransform = new SoundTransform(0, 0); // where the first "0" is the volume

**Comment by joshtynjala** [comment]
@bkhtrv Try this to change the volume:

```haxe
var transform = netStream.soundTransform;
transform.volume = 0;
netStream.soundTransform = transform;
```
