### ISSUE TITLE
Apostrophe is not decoded in htmlText for TextField

### ISSUE THREAD

**Issue by alexk74** [openfl/openfl#2716]
Steps to reproduce:
```
var tf:TextField = new TextField();
tf.htmlText = "&apos;";
addChild(tf);
```
It will display `&apos;` instead of `'`.
Tested on the latest openfl develop branch, on html5 target.

File causing the bug: [https://github.com/openfl/openfl/blob/develop/src/openfl/text/_internal/HTMLParser.hx](url)

Possible fix:
`StringTools.htmlUnescape` does not unescape the apostrophe.
We can create a static helper method `__htmlUnescape` which will unescape the `&apos;` and then replace all the `StringTools.htmlUnescape` calls from the file with `__htmlUnescape`.
```
	private static function __htmlUnescape(value:String):String
	{
		value = __regexEntities[1].replace(value, "'");
		return StringTools.htmlUnescape(value);
	}
```

**Comment by joshtynjala** [comment]
Good find! I see that Flash specifically supports the named entities `&gt;`, `&lt;`, `&amp;`, `&quot;`, and `&apos;`. It looks like `Stringtools.htmlUnescape()` supports all of them except `&apos;`, and it uses use `&#039;` instead, for some strange reason.

**Comment by alexk74** [comment]
Ha, somehow I did not see the &#039; used in StringTools.htmlUnescape.
It looks like &apos; is not recognized in HTML4.

Here's a more detailed discussion:
https://stackoverflow.com/questions/2083754/why-shouldnt-apos-be-used-to-escape-single-quotes
