### ISSUE TITLE
URLRequest fails to attach cookie by manipulating its header

### ISSUE THREAD

**Issue by rat-moonshine** [openfl/openfl#2717]
As per API doc for [URLRequest.manageCookies](https://api.openfl.org/openfl/net/URLRequest.html#manageCookies), it is possible to send cookies by adding into its header. One need to set `urlRequest.manageCookies=false` if works on Windows to able to send cookie, but this not requires on other operating system. 

Tested on Windows in different browsers, adding a named property in the request's header as "Cookie" - never sends; However, if I alter the name to anything but "Cookie", it sends. 

**To Reproduce**
Create a project that does a server request - we basically needs to check whether adding a "Cookie" property through request's header - can be send or not.

```
var loader = new URLLoader();
var request = new URLRequest();
request.url = "http://mywebsite.com";
request.manageCookies = false;
request.header = [
    new URLRequestHeader("Cookie", "JSESSIONID=4DdDFD343434E355CA5B9")
];
loader.send(request);
```

**Expected behavior**
In the browser console, against the request, one should see that "Cookie" named property sends in "Request Headers":
![image](https://github.com/openfl/openfl/assets/24370870/f90de0ff-8a1e-4f2d-b3ec-5addbcb3246d)

**Current behavior**
In the browser console, against the request, it's showing no "Cookie" name field attached:
![image](https://github.com/openfl/openfl/assets/24370870/ff170004-6d7b-4f59-88c6-1b1dd19687fa)

However, if I slightly change the name "Cookie" to "Cookie1" - it gets added:
![image](https://github.com/openfl/openfl/assets/24370870/0eb29deb-5c97-486c-be47-a27f94a755ff)

**OpenFL Targets**
HTML5

**Additional context**
OpenFL: GitHub - 9.4.0-Dev
Haxe: 4.3.4
Windows: 10
Browsers: Mozilla, Edge

**Comment by joshtynjala** [comment]
It appears that Cookie is considered a "forbidden header name" in JavaScript/browsers, so it cannot be set programmatically.

https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name

I'll ensure that the docs get updated with this restriction for a future version of OpenFL.

**Comment by dimensionscape** [comment]
If you need to set cookies for the html5 target, consider https://api.haxe.org/js/Cookie.html#set. 

It's important to note that cookies are set for the domain where they are set and limited to same origin policy due to security considerations in the browser - this is why we can not set cookies arbitrarily in request headers. 

If a cookie is set on an application running at `www.example.com`, they should be injected automatically every time a new request is sent, until they expire.
