### ISSUE TITLE
Graphics: calling `lineStyle()` after `curveTo()` reverts drawing position

### ISSUE THREAD

**Issue by player-03** [openfl/openfl#2740]
**Describe the bug**
If you call `curveTo()`, the next line you draw starts from the end of the curve. However, if you call `curveTo()` followed by `lineStyle()`, the next line you draw starts from the _beginning_ of the curve.

**To Reproduce**
Create a new project and insert this code:

```haxe
graphics.lineStyle(1, 0x000000);
graphics.curveTo(100, 0, 100, 100);
graphics.lineStyle(1, 0x000000); //<-- problem
graphics.lineTo(200, 100);
```

Both the curve and the line will be drawn starting from the origin:

![Actual result](https://github.com/user-attachments/assets/8b10b873-17ae-403c-bbc2-b2f17cddbbb8)

**Expected behavior**
The line should start from the end of the curve, as happens when you don't call `lineStyle()` in between.

```haxe
graphics.lineStyle(1, 0x000000);
graphics.curveTo(100, 0, 100, 100);
graphics.lineTo(200, 100);
```

![Expected behavior](https://github.com/user-attachments/assets/19f8a9ae-30ce-437f-be09-7e8aea82ee2e)

**OpenFL Targets**
Reproduced on C++, HL, Neko, and HTML5, all on Linux.

**Comment by nanjizal** [comment]
I had a look at the code, my guess is that is relates to ```__dirty = true;``` being reset to false by lineStyle? But I did not see where. Possibly in lineStyle... ```if( __isDirty == true ) endLineStyle();``` may fix?

**Comment by nanjizal** [comment]
may need some caution with fills
