### ISSUE TITLE
Amazon Fire TV: Gamepads/remotes not recognized

### ISSUE THREAD

**Issue by steverichey** [openfl/openfl#278]
Attempting to find a gamepad always fails. Not sure how easy this would be to fix.

**Comment by MJameShort** [comment]
Are you including their SDK and then importing their class?https://developer.amazon.com/public/solutions/devices/fire-tv/docs/gamecontroller-api

**Comment by ibilon** [comment]
Since then lime introduced a new gamepad API with way better support
http://api.openfl.org/lime/ui/Gamepad.html

If that issue is still there please open an issue at lime https://github.com/openfl/lime/issues
