### ISSUE TITLE
Websocket

### ISSUE THREAD

**Issue by zorend** [openfl/openfl#279]
The socket behave as intended on all platforms except Javascript where it works as Websocket.
I think creating a seperate Websocket class & disabling Socket for js would be better.
Creating a crossplatform multiplayer game would be better created using websocket on all platforms. Here is a link to the new Class I want to add:
https://github.com/dynestudio/openfl-lib

**Comment by jgranick** [comment]
Sorry for drumming an old topic

I think that openfl.net.Socket support on all targets is ideal for compatibility, but I don't think we need to limit support to only those features if Websocket has unique features we want to take advantage of. I believe the implementation we have is consistent across platforms, which is good :smile:
