### ISSUE TITLE
Embed=false not working for flash target.

### ISSUE THREAD

**Issue by ProG4mr** [openfl/openfl#283]
When using embed = false for flash target, assets are not copied to the bin folder.

Using:
openfl 2.0.1
lime 1.0.1

eg: 
Project.xml contains 
<assets path="assets" embed="false" />

For other targets than flash the folder assets gets copied.

**Comment by jgranick** [comment]
I believe this was resolved, let me know if there is a still an issue with this, thank you! :smile:

**Comment by ZwickTheGreat** [comment]
*unsubscribe git*
