### ISSUE TITLE
MouseEvent.MOUSE_OVER and MouseEvent.MOUSE_OUT dosen't work on html5 target

### ISSUE THREAD

**Issue by Kickerua** [openfl/openfl#284]
Actually MouseEvent.ROLL_OVER and MouseEvent.ROLL_OUT dosen't work too.

Here is modified HandlingMouseEvents example:
https://dl.dropboxusercontent.com/u/17378315/haxe/mouseOverExample.zip

**Comment by vizanto** [comment]
Um this is closed, but the patch doesn't implement `ROLL_OVER` or `ROLL_OUT`...
