### ISSUE TITLE
BitmapData.draw doesn't take blendmode into account on native

### ISSUE THREAD

**Issue by bendmorris** [openfl/openfl#286]
When using BlendMode.ADD, it seems that the result is the same as using BlendMode.NORMAL.

**Comment by ibilon** [comment]
Implemented in 9a67595fbef2bf14ed2ea891ba54f70b13d80b69.

Some blend modes didn't have obvious cairo counterpart,
I'll check later if they do have one and if the current ones work the same as in flash (at least ADD does).

**Comment by ibilon** [comment]
The one currently implemented seemed to work,
currently missing: ALPHA, ERASE, INVERT, SHADER, SUBTRACT.

Some of them won't be too hard to implement, added them to the list of things to do.

**Comment by Misiur** [comment]
As of today (https://github.com/openfl/openfl/tree/4f5c42375f3215dc3e077f5fe7f748cf616899a8), draw doesn't do anything with `blendMode` parameter - [this line](https://github.com/openfl/openfl/commit/9a67595fbef2bf14ed2ea891ba54f70b13d80b69#diff-3a74718cc507a2ef05e34482f859d81fR497) dissapeared somewhere
