### ISSUE TITLE
openfl.display.BitmapData.fillRect behaviour is "blend" instead of "replace"

### ISSUE THREAD

**Issue by YellowAfterlife** [openfl/openfl#287]
On Flash and native the following will produce an inner rectangle (blue) and outer rectangle (red) of same opacity. On HTML5 rectangles are blend one over other instead. This makes it impossible to use default backend to erase parts of BitmapData's.
```haxe
class Main {
	@:keep static function main() {
		var v = new openfl.display.BitmapData(320, 320, true, 0x80ff0000);
		v.fillRect(new openfl.geom.Rectangle(80, 80, 160, 160), 0x800000ff);
		openfl.Lib.current.addChild(new openfl.display.Bitmap(v));
	}
}
```

**Comment by jgranick** [comment]
Pretty sure this is fixed :smile:

**Comment by jerobarraco** [comment]
Not working on latest version. 
It blends the alpha channel instead of replacing them.
using a call to clearRect does the expected behavior.
