### ISSUE TITLE
[HTML5] TextField.textHeight

### ISSUE THREAD

**Issue by RealyUniqueName** [openfl/openfl#288]
In html5 target TextField.textHeight gives me wrong value.
After some experiments i've came to this hack:

``` haxe
var tf      = txt.defaultTextFormat;
var lines = txt.numLines;
var h : Float = Std.int(tf.size * 1.185 * lines);
var textHeight = (Std.int(h) - h + 1) * lines + 1 + (lines - 1) * tf.leading + h;
```

These calculations gives me the same textHeight as  TextField.textHeight in flash/native targets

**Comment by 62316e** [comment]
Any fixes?

**Comment by vroad** [comment]
TextField measures its height with different method when I call get_textHeight() second time.
First time with DOM, and second time with canvas.
I think that there is no need to use different method for measuring text height, as there is no accurate way for measuring text height with canvas.

https://github.com/openfl/openfl/blob/master/openfl/text/TextField.hx#L1640

**Comment by vroad** [comment]
These lines of code makes textHeight double sometimes.
https://github.com/openfl/openfl/blob/36947aea25d2b92f0f5221ede8e18b9c1b0045d8/openfl/text/TextField.hx#L1094

**Comment by 62316e** [comment]
Still does not work as expected

**Comment by vroad** [comment]
With DOM text measurement, text looks nice on Chrome and IE11, but not on Firefox...

There should be some other ways for this, but I haven't tried those yet.
http://stackoverflow.com/questions/1134586/how-can-you-find-the-height-of-text-on-an-html-canvas

**Comment by jgranick** [comment]
Current builds should hard-code text ascent/descent/height while compiling, so we have this information at runtime
