### ISSUE TITLE
[HTML5] Cannot modify BitmapData from Assets.getBitmapData()

### ISSUE THREAD

**Issue by starburst997** [openfl/openfl#291]
When using a BitmapData from Assets.getBitmapData() in the HTML5 backend, it is impossible to modify it (copyPixels, etc.) because "__sourceContext" is null. Using .clone() does not work either.

A workaround is to call __convertToCanvas() on the BitmapData (use "@:access(openfl.display.BitmapData)" at the top of the class to enable access to private methods)

**Comment by ibilon** [comment]
Was fixed.
