### ISSUE TITLE
url request does nothing on ios/ mac

### ISSUE THREAD

**Issue by Tembac** [openfl/openfl#296]
I'm trying to do a simple url request to post to facebook and twitter. It works on Android, Windows, blackberry and Neko. On ios and mac it does not work but it doesn't crash neither.

The code is really simple. I uploaded a demo here:

https://github.com/Tembac/HaxeFlixelSocialMediaDemo/tree/master

**Comment by jgranick** [comment]
This is fixed in newer builds
