### ISSUE TITLE
LineScaleMode=NONE not working for neko and cpp targets

### ISSUE THREAD

**Issue by tiagolr** [openfl/openfl#304]
Hi, i noticed the following code does not work anymore for cpp and neko targets:

```
graphics.lineStyle(1, 0xFF0000, 1, true, LineScaleMode.NONE);
``` 

any lines drawn using LineScaleMode.NONE are invisible on neko and cpp targets (flash still works), not sure when this happened but it worked fine at most a couple of months ago.

Using openfl 2.0.1 and lime 1.0.1

**Comment by ibilon** [comment]
Was fixed.

If you still have the issue with the latest version feel free to reopen this issue.
