### ISSUE TITLE
How can i locate mouse cursor's position

### ISSUE THREAD

**Issue by jjr2930** [openfl/openfl#310]
I am making a fps game

now days, I make the camera for fps, 

but mouse leave from the app

app doesn't track mouse

so i want to locate mouse cursor in application's center position

How can i do?

**Comment by ibilon** [comment]
Was added to lime http://api.openfl.org/lime/ui/Mouse.html#warp (window can be accessed from here http://api.openfl.org/openfl/display/Stage.html#window).
