### ISSUE TITLE
too slow URLLoader.load() + crash on Neko

### ISSUE THREAD

**Issue by raivof** [openfl/openfl#319]
When I'm downloading 19 mb CSV file from localhost, this download progresses quite slow…

Results using URLLoader.load():
on Windows/CPP: downloads for 29 seconds, which yields about 655 KB/s on my hardware
on Windows/Neko: crashes (I tested – exactly URLLoader.load() causes it)
on Android emulator: ~90 s – about 3x slower than Win/CPP (I suppose it's normal because emulator itself is very slow)

I looked up URLLoader source on github and I see it uses lime curl implementation. I'm not ready to dig deeper.

So I created simple HTTP downloader using a socket:
https://gist.github.com/raivof/dcdb1d74f93d17132a1e/b4faba409f477ff55c708f17011acf639cc18f1b
(I have copied this source from my project and removed any code which is unneeded for representation of this problem)

Results using 1 MB buffer:
on Windows/CPP: 0.26 s
on Windows/Neko: 0.42 s
on Android emulator: 3.81 s

Results using 64 KB buffer:
on Windows/CPP: 3.65 s
on Windows/Neko: crashes when reaches 69% , I tried 128 KB buffer, it crashes little bit later, on ~89%
on Android emulator: 46 s

I found that socket/Neko crash was caused by this line:
https://gist.github.com/raivof/dcdb1d74f93d17132a1e/d18fdd04854f2cc5d61de6254d4626f91225fed4#file-gistfile1-hx-L92
- it constructs resulting string by incrementally adding part from block-sized bytes buffer.

I changed code so that I allocate one large byte buffer, and then incrementally read in data directly from socket, and construct final string only when download is completed. This solves Neko crash AND it makes downloads even faster, on all platforms:
https://gist.github.com/raivof/dcdb1d74f93d17132a1e/b4faba409f477ff55c708f17011acf639cc18f1b#file-gistfile1-hx-L79-L99

Results using 1 MB buffer:
on Windows/CPP: 0.08 s
on Windows/Neko: 0.04 s
on Android emulator: 1.13 s

Results using 64 KB buffer:
on Windows/CPP: 0.71 s
on Windows/Neko: 0.34 s
on Android emulator: 2.16 s

Conclusions:
* URLLoader crashes on Neko
* Neko itself crashes when doing string concat with contents of byte buffer
* URLLoader slowness lies in lime/curl implementation, possibly related to buffer size

**Comment by ibilon** [comment]
Not crashing or slow anymore.
