### ISSUE TITLE
ColorMatrixFilter wraps values on Android (native?) target

### ISSUE THREAD

**Issue by initialize** [openfl/openfl#321]
Color components should be limited to 0x00 to 0xFF. When compiling to Flash they are, but when compiling to Android results get psychedelic, as in that values wrap or overflow.

**Comment by ibilon** [comment]
Flash documentation doesn't mention any wrapping,
and experimentation shows the same result between flash and native.

Bitmap with a ColorMatrixFilter didn't appear on android though.
