### ISSUE TITLE
Audio problems when not using Assets.getSound/getMusic

### ISSUE THREAD

**Issue by jacobalbano** [openfl/openfl#327]
My app necessitates a lot of runtime-loaded data, from user-generated content to custom soundtracks. As such, using `openfl.Assets` isn't viable since it can only access files that exist (and can be enumerated) at compile time. I'm aware that these problems don't exist when using the `Assets.getSound()` and `Assets.getMusic()`, but that doesn't help me in any way so please don't suggest that I use them.

*deep breath*

I use the following code to load sound effects, which are loaded completely into memory.

```
var result = new Sound();
var bytes = File.getBytes(path);
var array:ByteArray = ByteArray.fromBytes(bytes);
result.loadCompressedDataFromByteArray(array, array.length);
```

After this completes, the `length` property of the created sound object is **1000x what it should be.** This has always worked in the past and only recently started giving me problems.

Another issue is with streaming audio. Here's the code I use to load my music files.

```
var s = new Sound();
s.load(new URLRequest(path), null, true);
```

The problem here is that if I grab my game's window and move it around, or toggle between fullscreen/windowed mode, the audio halts until I release the window or the transition is complete. This behavior is not present when using `Assets.getMusic()`.

If this needs to be broken into two issues, let me know.

**Comment by ibilon** [comment]
Either the length problem was fixed or you were expecting seconds instead of the miliseconds the length is in.

Cannot reproduce your problem with `s.load(new URLRequest(path))`, hopefully fixed.

If you still have issues with the latest version don't hesitate to reopen.
