### ISSUE TITLE
Setting matrix causes wrong rotation/scale values

### ISSUE THREAD

**Issue by ProG4mr** [openfl/openfl#341]
Using the following code inside a sprite: 

```actionscript
// mtx is a matrix containing random scale and rotation
this.transform.matrix = mtx
```

works well for flash target, however for neko and cpp targets, the resulting values of ```rotation```, ```scaleX```and ```scaleY``` are not correct in some cases.

For example if the scaleY of the original matrix is negative, the resulting rotation after assigning that matrix will be the same but the scaleY value will be positive.
Also the rotation will vary with the scales, for eg: a sprite with scaleX:4 and scaleY:1 will not have the correct rotation at 45 degrees and will be worse if scaleX is 10 and scaleY is 0.5.

Here is a work around:

```actionscript
public function setMatrix(mtx:Matrix) {

	var sx = Math.sqrt(mtx.a * mtx.a + mtx.b * mtx.b);
	var sy = Math.sqrt(mtx.c * mtx.c + mtx.d * mtx.d);
	var r = Math.atan2(mtx.b, mtx.a) * 57.2957795130823;
	var signX = (mtx.a < 0 ? -1 : 1);
	var signY = (mtx.d < 0 ? -1 : 1);
	
	// use determinant to deal with improper rotations
	var det = mtx.a * mtx.d - mtx.b * mtx.c;
	if (det < 0) {
		if (signX < 0 || signY < 0) {
			sy *= -1;
		} 
	}
	
	this.x = mtx.tx;
	this.y = mtx.ty;
	this.scaleX = sx;
	this.scaleY = sy;
	this.rotation = r;
}
		

```

This way the resulting scale and rotation are consistent with the matrix and (by coincidence) are the same as the flash target, I can't explain too well or give matrix examples to test the bug since I'm using an interactive app and my algebra background is a bit weak.

Took me sometime to figure this out with a bit of trial and error, but it works and seems like a good fix.

**Comment by icek** [comment]
Thanks for this fix! I have many problems with importing assets from swf and this fixes everything. 
I applied this inside openfl.geom.Transform.set_matrix()

	if (__displayObject != null) {
		var det = value.a * value.d - value.b * value.c;
		var fix = (det < 0 && (value.a < 0 || value.d < 0)) ? -1 : 1;

		__displayObject.x = value.tx;
		__displayObject.y = value.ty;
		__displayObject.scaleX = Math.sqrt ((value.a * value.a) + (value.b * value.b));
		__displayObject.scaleY = Math.sqrt ((value.c * value.c) + (value.d * value.d)) * fix;
		__displayObject.rotation = Math.atan2 (value.b, value.a) * (180 / Math.PI);
	}

**Comment by icek** [comment]
Thanks for that. I checked other matrix issues and this commit seems to close all related to negative scale, but there are others like #555 which are caused by architecture. Transform.set_matrix forces __displayObject to get rotation and ignores possibility of skewing. Also DisplayObject.__update() forces rotation in similar way.

**Comment by jgranick** [comment]
Yeah, I am planning on looking at a matrix-based solution to this, in order to fully support skewing, I'll need to be sure this does not hurt our performance, but its the only reasonable solution I can think of :)
