### ISSUE TITLE
FocusEvent.FOCUS_OUT not always fired.

### ISSUE THREAD

**Issue by tiagolr** [openfl/openfl#342]
For flash target, focus out works well but for cpp/neko focus out event is only fired when switching from one input text field to another, even tho stage.focus changes correctly (to null) on other occasions.

Also when input text field becomes invisible (either by setting visible property or parent visibility to false) it should no longer be focused, this works well for flash target, not for cpp/neko.

**Comment by jgranick** [comment]
This is fixed in newer builds
