### ISSUE TITLE
Pixel values inconsistency

### ISSUE THREAD

**Issue by azrafe7** [openfl/openfl#345]
I was getting different results by manipulating pixels values cross target. 

Investigating it suggests that they actually differ based on target when the alpha value is not 0 or 255 (but lies in between).

Using this test https://gist.github.com/azrafe7/1a7b22f271addf37ce9f/e6feb401d4b3c251fe1b7023ce552f2587d12c95 to dump pixel values of images like this one:

![pirate_small](https://cloud.githubusercontent.com/assets/1266447/4290730/5655d5a6-3dbe-11e4-81da-3f3ceca3a3a4.png)

resulted in

```
// FLASH
bytearray [85248]:  08DFBF9F 1300D7AE 38FAC889 4A00CF8A 6DFCD59D B5FDE2C1 C0FEE6C6 C1FDE4C6 BDFDE6C5 B4FCE4C2 A5FDE0BC 81FDD7A8 7200D4A1 55FCCF90 18F4B560
vector    [21312]:  08DFBF9F 1300D7AE 38FAC889 4A00CF8A 6DFCD59D B5FDE2C1 C0FEE6C6 C1FDE4C6 BDFDE6C5 B4FCE4C2 A5FDE0BC 81FDD7A8 7200D4A1 55FCCF90 18F4B560

// CPP
bytearray [85248]:  08FFDFBF 1304DCB4 38FFCD8D 4A00D08B 6DFED69E B5FFE5C3 C0FFE7C7 C1FFE6C8 BDFFE8C7 B4FEE5C4 A5FFE1BE 81FFDAAA 7200D7A2 55FED192 18FFBF6A
vector    [21312]:  08FFDFBF 1304DCB4 38FFCD8D 4A00D08B 6DFED69E B5FFE5C3 C0FFE7C7 C1FFE6C8 BDFFE8C7 B4FEE5C4 A5FFE1BE 81FFDAAA 7200D7A2 55FED192 18FFBF6A

// NEKO
bytearray [85248]:  FF272625 FF1E2E2B FF514638 FF17533F FF7F6E56 FFBEAC94 FFC8B69E FFC9B69F FFC5B49C FFBDAB94 FFB09D86 FF917E66 FF12725A FF6A5B46 FF352F27
vector    [21312]:  FF272625 FF1E2E2B FF514638 FF17533F FF7F6E56 FFBEAC94 FFC8B69E FFC9B69F FFC5B49C FFBDAB94 FFB09D86 FF917E66 FF12725A FF6A5B46 FF352F27
```

It seems that neko sets them to full alpha and dims/interpolates the rgb, while cpp is slighlty off in respect to flash, but retains the same alpha.

Maybe this post http://stackoverflow.com/questions/24987165/sdl2-sdl-image-strange-png-behavior-with-rgb-values can lead into the right direction.

EDIT: I must add that another quirk affects how pixel with 0 alpha are treated. For a pixel with value 0x00202020 flash is reporting it as 0x00000000 (masking out the rgb), while neko and cpp will leave the rgb unchanged. This may or may be not what the user expects.

Tested on Win7:
openfl 2.0.0
lime 1.0.1

**Comment by ibilon** [comment]
Original issue resolved, if you have specific cases where pixel manipulation is too slow don't hesitate to open a new issue.

Late, but if you still want to look behind the scene all of openfl's function are coded in lime and a BitmapData uses a lime Image.
