### ISSUE TITLE
Mix OpenGLView &  Classic displaylist

### ISSUE THREAD

**Issue by shoebox** [openfl/openfl#35]
Hi.

Is it possible to mix an openglview and the classic displaylist ?

When i try to add a sprite over or under a OpenGlView, nothing is showing without errors.

**Comment by Tiago-Ling** [comment]
Looks like this is still a problem with OpenFL 3.6.1 / Lime 2.9.1

TextFields won't appear if you call either `GL.enable(GL.DEPTH_TEST)` or `GL.enable(GL.CULL_FACE)`.

Any way around this?

**Comment by player-03** [comment]
I use those versions with `DEPTH_TEST` enabled, and text fields work fine for me.

As a workaround, try enabling `DEPTH_TEST` at the start of your render function and disabling it at the end.

**Comment by Tiago-Ling** [comment]
@player-03 Strange, it does not work for me, regardless of the order i create them (view first then text or vice-versa). Is there anything special that you have to do with either the view or the Textfield that made it work for you? 

Btw, enabling and disabling DEPTH_TEST at the beginning and end of the render does work, but i'm interested in knowing how to make them work without this

**Comment by player-03** [comment]
Turns out, I do disable `DEPTH_TEST`. I disable it for an entirely unrelated reason, which is why I didn't remember it.

**Comment by Tiago-Ling** [comment]
Oh, ok then - thanks for the tip about disabling it at the end of the render pass!
