### ISSUE TITLE
Rotation breaks Tilesheet when rendering to a BitmapData (on Native, but works on Flash/HTML5)

### ISSUE THREAD

**Issue by fserb** [openfl/openfl#350]
On current haxelib head and on latest dev build, if you try to draw a tilesheet to a bitmapdata (via a sprite), it only works if there's no rotation involved (otherwise the rotation matrix seems broken). Also, if you set no alpha the image gets rendered black.

Also, the Flash target works fine for the haxelib version but tilesheet seems to be completely broken on the latest build for Flash. (EDIT: fixed)

**Comment by jgranick** [comment]
Thank you for reporting this, and including a test case. I apologize for the delay in testing.

I have just resolved in the Flash renderer, when using the TILE_ROTATION flag. Running your sample test, it now looks correct in both HTML5 in Flash.

The issues appears to be in the Lime legacy software render for the Tilesheet type, it must be using a bad matrix transform of some sort.

The offending file is likely this:

https://github.com/openfl/openfl/issues/148

It might also be possible to report this issue on the NME issue tracker, as I'm sure it has the same issue, perhaps Hugh has an idea.

Thanks :smile:
