### ISSUE TITLE
Capabilities.screenResolutionX/Y is returning 0 with -Dnext

### ISSUE THREAD

**Issue by RafaelOliveira** [openfl/openfl#363]
the old native is working, but with -Dnext it's giving me 0.

Looking on the code, the Capabilities version that is returning 0 is outside of _v2 directory, and the version that calls a lime function is inside. It seems that the classes are being swapped somewhere.
(I'm assuming that the new code is in the _v2 directory)

**Comment by ibilon** [comment]
It was implemented.
