### ISSUE TITLE
TextField.getCharIndexAtPoint() just throws NotImplemented

### ISSUE THREAD

**Issue by tienery** [openfl/openfl#377]
This is in relation to [this](http://stackoverflow.com/questions/26743694/getcharindexatpoint-gets-an-error-in-neko) post regarding the fact that the Neko target seems to think the said function does not exist. Is there a reason why? Does that mean there is absolutely no way to interact with TextField's other than without using this function?

How is it possible otherwise?

    haxelib run openfl build "C:\Users\Brutal\Downloads\StoryDev Development\Dev\application.xml" neko
    src/game/GameState.hx:778: characters 16-46 : openfl.text.TextField has no field getCharIndexAtPoint
    Build halted with errors (haxelib.exe).

I am currently using OpenFL 2.0.1, by the way. Until 2.1 is up-to-date, stable and actually has features I need.

**Comment by jgranick** [comment]
implemented now
