### ISSUE TITLE
Double-click doesn't work in the latest release for html5 target

### ISSUE THREAD

**Issue by pqyptixa** [openfl/openfl#383]
This project: https://github.com/dox187/HaxeMaps should zoom in when double clicking in the map, but for some reason (unknown cause), it doesn't when compiling for html5. Tested in firefox and chromium (linux), and confirmed by an user (filt3rek) in the IRC channel in freenode (#openfl).

**Comment by jgranick** [comment]
The `MouseEvent.DOUBLE_CLICK` event has been added to OpenFL HTML5 and native "next", I have also improved the behavior of `DOUBLE_CLICK` on the existing native v2 implementation as well. Thanks :)

https://github.com/openfl/openfl/commit/1a61cf10a70d658b9bbeef902e014fbb495a7c11
