### ISSUE TITLE
Touches event binding is wrong

### ISSUE THREAD

**Issue by Masadow** [openfl/openfl#385]
On some devices, especially IOS ones, touches events are never fired.

The problem is caused within flash.display.Stage initialization part which produced code is as follow

    var o = window;
    o.addEventListener("touchmove",this.getOnTouch(0));

(I cut the code so only interesting lines appears)

Bind touches events to the window simply doesn't work on many devices. Instead, it should be bind to document.

We obviously can't replace `window` by `document`, a new var should be added.

**Comment by jgranick** [comment]
This is fixed in newer builds, thanks :smile:
