### ISSUE TITLE
HTML5 bitmapdata.copypixels applies incorrect alpha (aquired from previous .draw calls)

### ISSUE THREAD

**Issue by Penry** [openfl/openfl#394]
when compiling for the HTML5 target, bitmapdata.draw and bitmapdata.copypixels are as yet incomplete, and only partial functionality is available.
A bigger issue exists, in that, there is very strange behaviour is occuring currently with bitmapdata.copypixels effectivly collecting the alpha value from pervious calls to bitmapdata.draw.

The code below demonstrates this issue precisely - (greensquare is given alpha 0.5, this alpha value is also applied to the blue square)

```
var canvasbmp:Bitmap;
var canvasbitmapdata:BitmapData;
var redsquare:Bitmap;
var greensquare:Bitmap;
var bluesquare:Bitmap;

function init() { 
	canvasbitmapdata = new BitmapData(300, 150, true, 0xff000000);
	canvasbmp = new Bitmap(canvasbitmapdata);
	addChild(canvasbmp);
	
	redsquare = new Bitmap (new BitmapData(20, 20, true, 0xffff0000));
	greensquare = new Bitmap(new BitmapData(20, 20, true, 0xff00ff00));
	bluesquare = new Bitmap (new BitmapData(20, 20, true, 0xff0000ff));

	greensquare.alpha = 0.5;
	
	canvasbitmapdata.copyPixels(redsquare.bitmapData, new Rectangle(0, 0, 20, 20), new Point(50, 50) , null, null, true);
	
	var matrix:Matrix = new Matrix();
	matrix.translate(100, 50);
	canvasbitmapdata.draw(greensquare, matrix, null, null, null, true);
	
	canvasbitmapdata.copyPixels(bluesquare.bitmapData, new Rectangle(0, 0, 20, 20), new Point(150, 50) , null, null, true);	
}
```

**Comment by ibilon** [comment]
`copyPixels` only calls lime so most likely a bug from there.

Also strangely on flash the green square is drawn at full alpha,
not sure what's the expected behavior here.
