### ISSUE TITLE
[iOS]: Cannot find xml file relarive to project root in build/macro time

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [openfl/openfl#395]
I have a builder macro, that reads information from the gui xml files during macro time. So I do this:

```
@:build(Builder.buildController("gui/mainmenu.xml"))
```

where the gui directory is in the root of my project. In the builder macro, the file is tested for with:

```
sys.FileSystem.exists(fileName)
```

It works fine on linux/android/macosx/flash but for ios it cannot find the file. I can correct it on ios with:

```
@:build(Builder.buildController("../../../../gui/mainmenu.xml")
```

(so searching in 4 directories upwards). But is there a solution that works an ios and all other platforms?

**Comment by ibilon** [comment]
`Context.resolvePath` is the way to go.
