### ISSUE TITLE
[Android] Keyboard closing when using latest Google Keyboard

### ISSUE THREAD

**Issue by phil-allcock** [openfl/openfl#396]
I have been working on getting a flash project onto android and came across an issue where attempting to input text into a textfield will close the keyboard down without inputting any text . I thought that it may have been an issue with stablexui, but I create a small test project with just a textfield which is added to the stage using both flash.text and openfl  textfield imports and neither worked. I tried an older project which was compiled 2 months ago and the same issue persists.

I saw that a few days ago there was an update to Google Keyboard which automatically downloaded. I removed this and installed swiftkey which allowed me to type in the textfield again. To make sure this fixed the issue, I removed swiftkey and reinstalled Google Keyboard and the text input returned to the original issue. 

[Edit] I have emailed Google to pass this onto them as it seems to be an issue with the latest version of the app (reverting to factory default of the app, which is version 2, fixes the issue)

**Comment by SavedByZero** [comment]
This isn't the only keyboard issue with the android target.  A tester of my project bought a new Samsung tablet and some of the characters he types in just don't show up.  This issue doesn't happen on the iphone version of the game.   Of course, there's no way of telling if OpenFL has any control over this.

**Comment by jgranick** [comment]
I believe the disappearing keyboard issue should be resolved, using a different IME setting in the release of Lime I'm making today
