### ISSUE TITLE
Missing support for arbitrarily rotated TextFields

### ISSUE THREAD

**Issue by grapefrukt** [openfl/openfl#398]
![flashplayer_11_8_sa_debug 2014-11-18 12-00-14-12](https://cloud.githubusercontent.com/assets/158901/5086332/6a8631b8-6f1b-11e4-9df0-117fb3302a10.gif)

Native targets do not allow for arbitrary rotation of `TextField`, there are workarounds, but I can't see any reason this should not be a relatively easy thing to support?

Test case here: https://dl.dropboxusercontent.com/u/32925/openfl-bug-fontrotate.zip

```haxe
package;

import openfl.Assets;
import openfl.display.Sprite;
import openfl.text.TextField;
import openfl.text.TextFormat;
import openfl.events.Event;

class Main extends Sprite {
	
	var textfield:TextField;

	public function new() {
		super();
		
		#if flash 
			var font:String = Assets.getFont('assets/junction.ttf').fontName;
		#else 
			var font:String = Assets.getFont('assets/junction.otf').fontName;
		#end
		
		var textFormat = new TextFormat(font, 48, 0xffffff);
		
		textfield = new TextField();
		textfield.x = 100;
		textfield.y = 100;
		textfield.defaultTextFormat = textFormat;
		textfield.embedFonts = true;
		textfield.text = 'test';
		addChild(textfield);
		
		addEventListener(Event.ENTER_FRAME, handleEnterFrame);
	}
	
	function handleEnterFrame(e:Event){
		textfield.rotation += 1;
	}
}

```

**Comment by jgranick** [comment]
This should be supported now that Hugh implemented the Lime legacy / NME TextField using drawTiles under the hood instead of the BlitRect implementation that was there before :smile:

**Comment by jgranick** [comment]
BTW, I love your animated GIF example images, you A+ student
