### ISSUE TITLE
Window's fps with enabled HXCPP_FLOAT32

### ISSUE THREAD

**Issue by eliasku** [openfl/openfl#399]
reproduced on Mac, just add HXCPP_FLOAT32 and set 
```
<window fps="100" /> 
```
or just set
```
Lib.current.stage.frameRate = 60;
```
application freezes and not responding

**Comment by jgranick** [comment]
Hi!

I apologize for bringing up this old issue.

Our native API calls on Lime have expectations in place about the data size of passed values. `-DHXCPP_FLOAT32` breaks this functionality. We could consider a feature improvement to Lime to handle this, but either way, it isn't a bug in OpenFL.

Thank you :smile:
