### ISSUE TITLE
[android] JNI ERROR (app bug): local reference table overflow (max=512)

### ISSUE THREAD

**Issue by nitrobin** [openfl/openfl#400]
I have a problem with openfl.utils.JNI, when developing extension for android.
I get function reference with JNI.createStaticMethod. And application crash with "JNI ERROR" after a certain number of function calls.
Probably that the problem is in implementation of "lime_jni_call_static". 
Maybe there is missing a call "env->DeleteLocalRef".

Library property ["SystemPath.userDirectory"](https://github.com/openfl/openfl/blob/master/openfl/_v2/utils/SystemPath.hx#L57) implemented through JNI on android platform, and problem can be easily reproduced using the code below.

Source:
```haxe
package ;
import openfl.utils.SystemPath;

class Main {
    public static function main() {
        for(i in 0...1000) {
            trace(SystemPath.userDirectory);
        }
    }
}
```
Logcat output:
<pre>
E/dalvikvm(25503): JNI ERROR (app bug): local reference table overflow (max=512)
W/dalvikvm(25503): JNI local reference table (0x5b58f4f8) dump:
W/dalvikvm(25503):   Last 10 entries (of 512):
W/dalvikvm(25503):       511: 0x4194b6a0 libcore.io.Posix
W/dalvikvm(25503):       510: 0x41c3b358 java.lang.String "/storage/emulate... (69 chars)
W/dalvikvm(25503):       509: 0x41c3b0d8 java.lang.String "/storage/emulate... (69 chars)
W/dalvikvm(25503):       508: 0x41c3ae58 java.lang.String "/storage/emulate... (69 chars)
W/dalvikvm(25503):       507: 0x41c3abd8 java.lang.String "/storage/emulate... (69 chars)
W/dalvikvm(25503):       506: 0x41c3a958 java.lang.String "/storage/emulate... (69 chars)
W/dalvikvm(25503):       505: 0x41c3a6d8 java.lang.String "/storage/emulate... (69 chars)
W/dalvikvm(25503):       504: 0x41c3a458 java.lang.String "/storage/emulate... (69 chars)
W/dalvikvm(25503):       503: 0x41c3a1d8 java.lang.String "/storage/emulate... (69 chars)
W/dalvikvm(25503):       502: 0x41c39f58 java.lang.String "/storage/emulate... (69 chars)
W/dalvikvm(25503):   Summary:
W/dalvikvm(25503):         2 of java.lang.Class (2 unique instances)
W/dalvikvm(25503):       509 of java.lang.String (509 unique instances)
W/dalvikvm(25503):         1 of libcore.io.Posix
E/dalvikvm(25503): Failed adding to JNI local ref table (has 512 entries)
I/dalvikvm(25503): "GLThread 14550" prio=5 tid=14 RUNNABLE
I/dalvikvm(25503):   | group="main" sCount=0 dsCount=0 obj=0x41bd4d18 self=0x5c2b9ad8
I/dalvikvm(25503):   | sysTid=25525 nice=0 sched=0/0 cgrp=apps handle=1546362664
I/dalvikvm(25503):   | state=R schedstat=( 0 0 0 ) utm=14 stm=9 core=1
I/dalvikvm(25503):   at libcore.io.Posix.access(Native Method)
I/dalvikvm(25503):   at libcore.io.ForwardingOs.access(ForwardingOs.java:39)
I/dalvikvm(25503):   at java.io.File.doAccess(File.java:283)
I/dalvikvm(25503):   at java.io.File.exists(File.java:363)
I/dalvikvm(25503):   at android.app.ContextImpl.getExternalFilesDir(ContextImpl.java:832)
I/dalvikvm(25503):   at android.content.ContextWrapper.getExternalFilesDir(ContextWrapper.java:204)
I/dalvikvm(25503):   at org.haxe.lime.GameActivity.getSpecialDir(GameActivity.java:369)
I/dalvikvm(25503):   at org.haxe.lime.Lime.onResize(Native Method)
I/dalvikvm(25503):   at org.haxe.lime.MainView$Renderer.onSurfaceChanged(MainView.java:721)
I/dalvikvm(25503):   at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1514)
I/dalvikvm(25503):   at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1242)
I/dalvikvm(25503): 
E/dalvikvm(25503): VM aborting
F/libc    (25503): Fatal signal 11 (SIGSEGV) at 0xdeadd00d (code=1), thread 25525 (Thread-14550)
</pre>

I found some information [here](http://www.openfl.org/archive/community/bugs/jni-error-local-reference-table-overflow/) and [here](https://github.com/openfl/openfl-native/issues/145) ,
As I understand it, I can create native module and invoke Java code from ndll, as workaround. But it is not handy. 

Current sources "JNI" contain conditions ["android && !openfl_next"] (https://github.com/openfl/openfl/blob/dc4471081ccda19ac0b07ebae137d0d07bf2dbf6/openfl/utils/JNI.hx) 
What is the future of "openfl.utils.JNI" class? It will be removed/replaced/[updated](https://github.com/openfl/lime/issues/6#issuecomment-30249953)?

**Comment by ibilon** [comment]
Looked quickly at the lime JNI class and couldn't find any obvious source of leak,
if the problem still happen with the latest lime please open an issue over there.

Here's the file https://github.com/openfl/lime/blob/75bb6905af1b64b01af68892134afc00550846e0/project/src/system/JNI.cpp
