### ISSUE TITLE
[TextFormat] kerning and letterSpacing works on Flash, not on Android

### ISSUE THREAD

**Issue by smwht** [openfl/openfl#403]
1. textFormat.letterSpacing does not seem to work on Android target.
2. textFormat.kerning for flash expects Bool, while on Android it expects Null\<Float\>

openfl: [2.1.6]
lime: [2.0.0]

```
var textFormat1 = new TextFormat();
textFormat1.letterSpacing = 0;

var textField1 = new TextField();
textField1.text = 'text';
textField1.setTextFormat( textFormat1 );
textField1.y = 100;
addChild( textField1 );

var textFormat2 = new TextFormat();
textFormat2.letterSpacing = 10;
// textFormat2.kerning = 10; // makes no difference

var textField2 = new TextField();
textField2.text = 'text';
textField2.setTextFormat( textFormat2 );
textField2.y = 200;
addChild( textField2 );
```

**Comment by Type1J** [comment]
The TextFormat.kerning field should be a Null<Bool> I think. It's already that way in non-legacy mode. I've had to make this change to make some things compile with lime-hybrid.

**Comment by bmfs** [comment]
letter spacing also doesn't work in canvas
