### ISSUE TITLE
Add `byteArray.readObject/writeObject` support

### ISSUE THREAD

**Issue by MSGhero** [openfl/openfl#416]
I noticed read and writeObject were left out of the OpenFL roadmap entirely. The [AMF3](https://github.com/HaxeFoundation/format/tree/master/format/amf3) lib in haxe.format encodes to and decodes from AMF3, which is what a flash ByteArray uses for write/readObject under the hood.

If I made a pull eventually, would it go into OpenFL's ByteArray _and_ Lime's ByteArray or just the one? The code can't be copied directly due to haxe.format's weird enums, and it's also like 300-400 lines long.

Or is gonna be something that shouldn't get added to OpenFLime at all?

**Comment by Type1J** [comment]
@jgranick I think that if Flash uses AMF, then OpenFL should use AMF, but as for other protocols, can't this be done with static extension? That would make it extensible enough to handle either protocol, or more. You could even split the reader and writer, if needed. The Haxe Serializer static extension could be included with Lime or OpenFL if there's a strong desire for it.

**Comment by MSGhero** [comment]
I found a full as3 version of amf3 that could be as3hx'ed as a full solution. https://code.google.com/p/cvlib/source/browse/#svn%2Ftrunk%2Fas3%2Fcom%2Fcoursevector%2Famf

Honestly, none of the complicated junk ever happened during my testing for the format lib, but it's there.

**Comment by larsiusprime** [comment]
@MSGhero: that library is under GPL v3 license rather than MIT -- is that an issue?

**Comment by jgranick** [comment]
It looks like they got the classes from AMFPHP, and it seems that AMFPHP is using the new BSD license now, perhaps we could get the functionality from there?

https://github.com/silexlabs/amfphp-2.0/blob/master/license.txt

**Comment by jgranick** [comment]
but actually, is there a problem with this?

https://github.com/HaxeFoundation/format/tree/master/format/amf3

**Comment by MSGhero** [comment]
I wrote it, and it's not perfect. It doesn't do associative arrays (never came across them in testing), and reading an object gives you a string map rather than a typed or even dynamic object. I could edit it if it'll be used, didn't have much need on my end to.

**Comment by jgranick** [comment]
Well, implementing this using "format" would give us a standard place to contribute improvements, but also to move beyond not having this function at all, but having something that works in at least certain scenarios. On the other hand, if AMFPHP is under the BSD license, that may be good enough to borrow from there to have a fuller implementation

**Comment by MSGhero** [comment]
@jcward can we steal your amf3 implementation from hxscout? I'd be ok with replacing my one in format lib with a fuller version.

**Comment by jcward** [comment]
I got mine from @cambiata cx repo [here](https://github.com/cambiata/cx/tree/master/src/nekoserver/amf/io). Looks like there's no licensing info on the repo or in the files... I probably should have asked him first! Jonas, any idea what the license is on your `nekoserver.amf.io` package is?

It works great, but I think I made a fix or two -- look at git history on those files in both my [hxscout](https://github.com/jcward/hxScout/tree/master/lib/amf/io) (reader) and [hxtelemetry](https://github.com/jcward/hxtelemetry/blob/master/amf/io/Amf3Writer.hx) (writer) repos (I might have copied the writer over to hxScout repo).

**Comment by jgranick** [comment]
Actually should we consider using Haxe serialization instead of AMF for this? The core concept here is to encode and decode between clients or client and server, and Haxe serialization fits that bill (likely) with better performance than an AMF implementation. We could add something to the `ObjectEncoding` class, like `ObjectEncoding.HAXE` or `ObjectEncoding.HSF`?

**Comment by MSGhero** [comment]
My biggest thing back then was having flash and not-flash be able to understand the same save file. But even the current implementation of `writeInt` isn't in line with the AMF3 spec [like here](https://github.com/HaxeFoundation/format/blob/master/format/amf3/Writer.hx).

For a truly consistent ByteArray, including ones created with AS3/AMF3, all of the reads and writes would have to change. Otherwise, the flash ByteArray would have to be overridden with the `Serializer` implementation, and then maybe note somewhere that it won't work with AS3 swfs.

I'm trying to think of any APIs that expect AMF3 data, but my experience is with Newgrounds which can do any binary nowadays.

**Comment by jgranick** [comment]
Wow, your code is a lot shorter than I expected!

Now that we have discussed it more, I am thinking we should support AMF3 as well as Haxe serialization -- particularly if Haxe serialization has performance or interoperability improvements.

> For example, if an object has the objectEncoding property set to ObjectEncoding.DEFAULT, AMF3 encoding is used. If, in the future, a later version of Flash Player or Adobe AIR introduces a new AMF version and you republish your content, the application will use that new AMF version. You can use this constant only if you're not concerned at all about interoperability with previous versions.

I think it makes sense for us to use a serialization format that's most optimal for the current runtime (which I suspect will be Haxe serialization), but the user can always change `byteArray.objectEncoding`, so no harm there. I'll think about it more from the Flash Player side

**Comment by MSGhero** [comment]
It's not complete complete, but also a lot of that was putting the code into format's weird 4-file enum format.

The 3 issues left are associative arrays and string reuse, `readObject` doesn't create an object or type it (a la `registerClassAlias`), and `string.charCodeAt` probably has issues at the haxe level as far as UTF support.

**Comment by jgranick** [comment]
I would like to move this topic to Trello, as I'm trying to gather enhancements there: https://trello.com/c/b1oVEHcu/15-add-bytearray-readobject-writeobject-support

**Comment by jcward** [comment]
FYI: This is strangely suddenly relevant to me again, as we port an AS3 project to Haxe (targeting JS). We have AMF3 serializations that we'll want to translate to Haxe serializations. It would be nice to support AMF3 to load old serializations, and certainly the idea of supporting both via `byteArray.objectEncoding` is nice.

As a short-term solution (and idea for others), we may end up writing an AS3 tool just to deserialize our old AMF3 serializations, loading a Haxe-SWC library to write them out in the new Haxe-serialization format.

Or we might use a structured, JSON-based format. IIRC, both Haxe serialization and AMF3 serialization write data into an output pipe in a linear/recursive format, which means if you hit a class or data type you don't know about (or haven't ported yet), the serialization becomes unreadable beyond that point. But if it's structured JSON, missing classes could at least be ignored, skipped, or translated on the fly. Maybe a combination of the two -- class-based objects in structured JSON, and simple-type parameters as Haxe serialization? I dunno, we'll see...

**Comment by hoseyjoe** [comment]
@jcward . Did anything get created on your end? We are needing a amf3 parser (custom classes in particular).

**Comment by jcward** [comment]
It's been a long time since I looked at this, but no, I think it turned out that our serialized data was entirely JSON (objects, arrays, and simple data types.) No custom classes.

**Comment by MSGhero** [comment]
Just noticed the amf3 implementation in the format lib has been updated. It might be actually usable now.

**Comment by jgranick** [comment]
Hey guys, added an initial (blind) implementation of `byteArray.writeObject`/`byteArray.readObject`, please give it a try, and we can continue to chat about improvements to the code :grinning:

**Comment by MSGhero** [comment]
Blast from the past
