### ISSUE TITLE
Offstage event dispatching

### ISSUE THREAD

**Issue by jasonsturges** [openfl/openfl#418]
As discussed at [OpenFL Community](http://community.openfl.org/t/offstage-event-dispatching/242), I'd like to log this feature request for OpenFL.

My rendering engines rely on capturing events from display objects not on the display list. This enables a controller fully decoupled from the display list. Monitoring timing and managing lifecycle, there's no root entry point or attachment to the display list.

Use case aside, one difference between OpenFL and Flash is that display objects off the display list don't receive events.

For example, in Flash runtime you can create a display object and receive events even though it's not on the display list:

**ActionScript**

    package {
        import flash.display.Shape;
        import flash.display.Sprite;
        import flash.events.Event;
    
        public class Main extends Sprite {
    
            private var shape:Shape;
    
            public function Main() {
                super();
    
                shape = new Shape();
                shape.addEventListener(Event.ENTER_FRAME, frameHandler);
            }
    
            protected function frameHandler(event:Event):void {
                trace("frame handler");
            }
        }
    }

Above, frame handler is called.

However, translated to Haxe below, the handler will not be called:

**Haxe**

    package;
    import openfl.display.Shape;
    import openfl.display.Sprite;
    import openfl.events.Event;
    
    class Main extends Sprite {
    
        private var shape:Shape;
    
        public function new() {
            super();
    
            shape = new Shape();
            shape.addEventListener(Event.ENTER_FRAME, frameHandler);
        }
    
        private function frameHandler(event:Event):Void {
            trace("frame handler");
        }
    }

My understanding of Flash event dispatching was order listeners were added.  I've always believed listeners were just ordered sets, in which callbacks are appended. As in, when an event listener is added it just `+=` the function callback handler.

**Comment by jasonsturges** [comment]
@jgranick Likewise, any change to ponder this?

Mark and sweep garbage collection should prevent the sprite from being garbage collection with the listener attached.  

Specifically to my interests, I'm looking for a reliable cross-platform approach to when rendering is taking place.  Or, `Event.ENTER_FRAME` if other frame constructed, render, and exit frame events are not present.

Presumably some proxy to the stage, but I really don't want to rely on passing a reference to an initialize function.

**Comment by jgranick** [comment]
This was resolved in recent versions :smile:
