### ISSUE TITLE
drawing api force closePath for HTML5 target

### ISSUE THREAD

**Issue by postite** [openfl/openfl#420]
this line
https://github.com/openfl/openfl/blob/master/openfl/_internal/renderer/canvas/CanvasGraphics.hx#L107
force the lineTo to be closed even if it's not requested.

**Comment by bkorcsog** [comment]
This is a common scenario for drawing graphics in Flash. The lineTo doesn't close until you close by Drawing to the end point.

Here's an example from wonderful:

http://wonderfl.net/c/q8jR

But in this case they use the drawPath command rather than a sequence of moveTo/lineTo/curveTo events.
