### ISSUE TITLE
Add fullscreen support with desktop target

### ISSUE THREAD

**Issue by dmitryhryppa** [openfl/openfl#421]
In old OpenFL it was a few methods for switching the game into fullscreen mode on the desktop targets:

https://github.com/openfl/openfl-native/blob/b8de6cbfbd97f162c632541f68a600032ad5ef42/flash/display/Stage.hx#L161

https://github.com/openfl/openfl-native/blob/b8de6cbfbd97f162c632541f68a600032ad5ef42/flash/display/Stage.hx#L151

In OpenFL next they gone. Please, add them again :) This methods are very useful. 

PS. Sorry for my English
Thanks!
-Dmitry

**Comment by jgranick** [comment]
They're added now :smile:
