### ISSUE TITLE
Line stroke improperly drawn on iOS or Mac

### ISSUE THREAD

**Issue by orignaux** [openfl/openfl#428]
I think I ran into a bug on Mac and iOS targets. I've tested it on HTML5 and Flash as well but both works as expected. Basically I'm drawing a rectangle with a thick border and the bottom right corner is for some reason not drawn straight.

It's easy to replicate with the following code:
```haxe
var background:Sprite;
background = new Sprite();
background.x = 0;
background.y = 0;
background.graphics.lineStyle(20, 0x37B89E);
background.graphics.beginFill(0x47C8AE, 1.0);
background.graphics.drawRect(0, 0, 960, 640);
background.graphics.endFill();
addChild(background);
```
If I set LineScaleMode.NONE it draws the line straight though so perhaps it's something related to that.

I'm using:
hxcpp 3.1.39
openfl 2.1.7
openfl-native 1.4.0
lime 2.0.1

### iOS
![ios](https://cloud.githubusercontent.com/assets/409595/5470549/3e9f90e6-85e9-11e4-9506-b8d0034a71ed.png)
### OSX
![osx](https://cloud.githubusercontent.com/assets/409595/5470550/446619b4-85e9-11e4-91f8-7fbfd43e8fed.png)
### Flash
![flash](https://cloud.githubusercontent.com/assets/409595/5470551/499a772c-85e9-11e4-9f24-8348a4f84b87.png)
### HTML5
![html5](https://cloud.githubusercontent.com/assets/409595/5470552/4f6bcee4-85e9-11e4-8eaf-586712a791c2.png)

**Comment by ibilon** [comment]
Merging with #1104
