### ISSUE TITLE
BitmapData.paletteMap() not using alphaArray

### ISSUE THREAD

**Issue by azrafe7** [openfl/openfl#429]
Tha `alphaArray` parameter is never used, instead a fully opaque value for alpha is assumed.

See https://github.com/openfl/openfl/blob/5546b5a15fd662b1eb87be8b33410a336ce89673/openfl/display/BitmapData.hx#L975

**Comment by azrafe7** [comment]
Haven't tested it yet, but thanks to you for addressing this!

**Comment by jgranick** [comment]
If you `haxelib upgrade`, it's in the release I made yesterday :smile:
