### ISSUE TITLE
Errors in openfl.geom Matrix and Point

### ISSUE THREAD

**Issue by drezabek94** [openfl/openfl#447]
On line 187 of openfl.geom.Matrix in the createBox method, `b = rotation;` should be `rotate(rotation);`. This should be applied to openfl._v2.geom.Matrix also.

In openfl.geom.Point, the method copyFrom is missing. It could easily be copied over from openfl._v2.geom.Point.

**Comment by drezabek94** [comment]
Another issue with openfl(._v2).geom.Matrix in createBox, identity() should be called at the beginning of the method, [see here](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/geom/Matrix.html#createBox%28%29).

**Comment by jgranick** [comment]
Thanks!

I just updated it, based on that documentation. I tried to decompose it to gain a little bit of performance. Please give it a try, to make sure I didn't miss something:

https://github.com/openfl/openfl/commit/79fd4c1ec5f346e33c0b900af88a1b772f62e913

**Comment by jgranick** [comment]
Looks like it is, I'll mark this as closed :)
