### ISSUE TITLE
HTML5-Canvas TextField Align CENTER / RIGHT not working

### ISSUE THREAD

**Issue by starburst997** [openfl/openfl#453]
This commit breaks align CENTER / RIGHT (nothing is displayed)

https://github.com/openfl/openfl/commit/1d13c06a64035c8aafcd7bc98daa66776e2c1635

**Comment by jgranick** [comment]
Sorry about that, the first line is the only one that was intentional, the rest got included by accident. Does this help? :smile:

**Comment by starburst997** [comment]
Yes perfect
