### ISSUE TITLE
CPP SWF font embedding not working

### ISSUE THREAD

**Issue by ivodopiviz** [openfl/openfl#455]
Tested on Mac and Windows, using a SWF-embedded font, no text gests drawn. This is a fairly recent issue, I can confirm it didn't happen a month ago or so.

Font rendering itself seems to be working fine, given I can see the FPS display.

![screen shot 2015-01-06 at 12 51 10 pm](https://cloud.githubusercontent.com/assets/250464/5631153/00d0c978-95a3-11e4-8a92-b9010e42dd5a.png)

![screen shot 2015-01-06 at 12 51 31 pm](https://cloud.githubusercontent.com/assets/250464/5631158/06f862f2-95a3-11e4-9f96-21d1ebed3320.png)

**Comment by jgranick** [comment]
This was fixed, thank you! :smile:
