### ISSUE TITLE
SWF embedding doesn't work on Windows Neko

### ISSUE THREAD

**Issue by ivodopiviz** [openfl/openfl#456]
Using an SWF library and embedding a font in it seems to work fine on Neko OSX but seems to use the default "sans" font on Neko Windows. Interestingly, CPP Windows didn't have this issue before it stopped rendering altogether.

![screen shot 2015-01-06 at 12 54 42 pm](https://cloud.githubusercontent.com/assets/250464/5631591/79475130-95a6-11e4-90e1-046a287db3d7.png)

![screen shot 2015-01-06 at 1 12 53 pm](https://cloud.githubusercontent.com/assets/250464/5631593/7b9a3f6a-95a6-11e4-82cb-69b4e89f489e.png)

**Comment by jgranick** [comment]
This was also fixed, thanks again for sharing your project so we could get it resolved :smile: :shipit:
