### ISSUE TITLE
SWF motion tween not working on Neko

### ISSUE THREAD

**Issue by ivodopiviz** [openfl/openfl#457]
We're loading a SWF library with some simple motion tween based animations. Unfortunately, it doesn't seem to work properly with Neko either under OSX or Windows:

![luzsxav6kh](https://cloud.githubusercontent.com/assets/250464/5631746/b0edb40c-95a7-11e4-8478-e36f6f4e3309.gif)
It seems to just jump to the final frame instead of tweening.

The same thing but CPP version:
![ldhdxx4evg](https://cloud.githubusercontent.com/assets/250464/5631800/2fe43128-95a8-11e4-93ae-9a15423d862f.gif)
While the gif recording seems to have destroyed the framerate, the real thing works fine.

**Comment by jgranick** [comment]
Fixed :smile:
