### ISSUE TITLE
SimpleButton intsances only show upstate on HTML5 target

### ISSUE THREAD

**Issue by dimumurray** [openfl/openfl#458]
Over and Down states fail to appear for SimpleButton instance on HTML5 target. Works on windows target.

**Comment by kevinresol** [comment]
I got this issue too. You cannot "reuse" a DisplayObject instance on html5. You have to use 4 individual DisplayObject instances for each state of SimpleButton.

**Comment by kevinresol** [comment]
Btw, seems that the "overState" is being shown (it should be "upState" instead) after mouse being over and out. (html5 only)

**Comment by dimumurray** [comment]
>I got this issue too. You cannot "reuse" a DisplayObject instance on html5. You have to use 4 individual DisplayObject instances for each state of SimpleButton.

I did use distinct DisplayObjects for each state but that's not the issue. Turns out that MouseOver and MouseOut events aren't implemented for the HTML5 target; see the following link for details:
http://community.openfl.org/t/simplebutton-woes/465
