### ISSUE TITLE
Text on Flash

### ISSUE THREAD

**Issue by mbrezu** [openfl/openfl#462]
After upgrading to the latest version of OpenFL, my application suddenly doesn't display text at all in Flash (everything fine in Neko). 

I use the following function to create text fields for messages:

	public static function getTextField(): TextField {
		var result = new TextField();
		result = new TextField();
		if (textFormat == null) {
			#if flash
			textFormat = new TextFormat("assets/fonts/CarterOne");
			#else
			textFormat = new TextFormat("assets/fonts/CarterOne.ttf");
			#end
		}
        result.defaultTextFormat = textFormat;
		result.autoSize = TextFieldAutoSize.LEFT;
		result.selectable = false;
		result.wordWrap = false;
		#if flash
        result.embedFonts = true;
        #end
		return result;
	}

This function isn't working anymore, I don't see any text unless I set result.embedFonts to false (then I see text, but displayed with the default font, not Carter One). Am I doing something wrong?

Thanks!

haxelib list output
actuate: 1.7.5 [1.8.0]
HIDE: [0.4.7]
hxcpp: 3.1.39 [3.1.48]
lime-tools: [1.5.7]
lime: 1.0.1 [2.0.4]
node-webkit: [1.0.7]
openfl-samples: 1.3.0 [2.2.0]
openfl: 2.0.1 [2.2.1]

**Comment by mbrezu** [comment]
Note: using `@:font("assets/fonts/CarterOne.ttf") class DefaultFont extends Font {}` works well, so this is not a vital issue.

**Comment by jgranick** [comment]
There were recent updates to fix the font name behavior, you'll want to either use `Assets.getFont ("path/to/font.ttf").fontName` for backwards-compatible behavior, or now you should be able to use the proper font name, as you normally would in Flash, like "Carter One" or whatever the font defines :smile:
