### ISSUE TITLE
Capabilities.lang crashes the app on ios ARM64

### ISSUE THREAD

**Issue by TBaudon** [openfl/openfl#464]
Hi,

Big thank for enabling arm64 build for openfl and lime!

I'm currently triing to port my game for this architecture, and I'm having some troubles.
When built for arm64 the games crash as soon as launched. i firstly thought it was due to my extensions but after a bit of investigation it seems that using 

```
openfl.system.Capabilities.language
```

makes the app crash in 64 bit. 
It works fine for armv7.

I'm using openfl 2.2.1 and lime 2.0.4.
Is there anything special to do for 64bit whle compiling?
All I do to run the game is 
```
lime update project.xml ios 
```
And then run it from xcode. Do I have any parameter to change in xcode or do you think it's a lime/openfl problem ?

Thank you.

**Comment by jgranick** [comment]
Thanks for bringing this up! It looks like we were releasing something we didn't need to, should be fixed in this commit :smile: https://github.com/openfl/lime/commit/c45e1a4db0214bd42a10b1f7ef89d294c667d30b
