### ISSUE TITLE
[mac] Class not found : flash.system.TouchscreenType

### ISSUE THREAD

**Issue by fzzr-** [openfl/openfl#471]
On mac
````haxe
trace(Capabilities.touchscreenType); // returns "finger"
````
I think that "finger" is `flash.system.TouchscreenType.FINGER`.

Need to create `openfl.system.TouchscreenType` for capability. Currently we can't simply test `if(Capabilities.touchscreenType == TouchscreenType.FINGER)` :(

**Comment by jgranick** [comment]
Thanks I'll look into this :)
