### ISSUE TITLE
openfl_next get/setVector of openfl.display.BitmapData implemented in terms of get/setPixels

### ISSUE THREAD

**Issue by Type1J** [openfl/openfl#473]
Being that getVector() and setVector() should be faster than getPixels() and setPixels() due to the aligned 32-bit access that Vector provides, these should have a direct call to lime, like getPixels() and setPixels() does.

Currently, a copy operation happens as part of getVector() and setVector(), and they use getPixels() and setPixels() to get access to what they're copying, which means that there's no chance of the *Vector() functions ever being faster than the *Pixels() functions.

**Comment by ibilon** [comment]
BitmapData aren't stored as vector so it's expected that get/setVector will be slower.

Should be the same in flash since the documentation mentions "Converts a Vector" and "Generates a vector".
