### ISSUE TITLE
TouchEvent.TOUCH_TAP not implemented on native?

### ISSUE THREAD

**Issue by kevinresol** [openfl/openfl#481]
I am not very sure but seems that TOUCH_TAP is not implemented on native (mobile).

Until the problem being fixed, the quick solution I used is to keep a bool on TOUCH_BEGIN and check that bool again on TOUCH_END to tell that the touch has both begun and ended within the sprite.

**Comment by pozirk** [comment]
Yep, having the same problem.

I've tried ToucheEvent and it seems not working properly on native platform.
I've tested it on Android and had the following problems:
1. TOUCH_TAP never fires, while TOUCH_BEGIN and TOUCH_END works fine.
2. TouchEvent.pressure is always 1, while Android Developer options has touch data info, and it shows different pressure on different touches.
