### ISSUE TITLE
Linux installation script doesn't work

### ISSUE THREAD

**Issue by chronosyndrome** [openfl/openfl#482]
I've discovered that neko site (http://nekovm.org/) is not available at the moment. It returns 404, so the installation script fails on this step and doesn't proceed. Is there any place where neko binaries can be downloaded from?

Thanks.

**Comment by jgranick** [comment]
Try this one, it sounds like the site will be up soon, it's changing hands at the moment

http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/neko/

**Comment by chronosyndrome** [comment]
Thank you for the quick response, got it working! Hope the neko website will also be back soon.

**Comment by tjrhodes** [comment]
grab it from here and build it

https://github.com/HaxeFoundation/neko
