### ISSUE TITLE
Sounds from Ogg files: seeking accuracy problem.

### ISSUE THREAD

**Issue by Horsetopus** [openfl/openfl#486]
Related to this forum post:
http://community.openfl.org/t/soundchannel-position-accuracy/438/4

When using sound.play( position ) with a sound coming from an Ogg file, the position seeked isn't accurate.

soundChannel = sound.play( position );
trace( position, soundChannel.position, soundChannel.position / position );

It seems that the resulting position is proportionally off from what was asked.
If position 1000 is asked and 1001 is obtained, then if you ask 2000 you will get 20002.

This ratio seems to depend on the file ( different for different Ogg files, constant for the same file on different runs).

Tested on Windows and Android targets.

**Comment by jgranick** [comment]
I think this has been resolved in the newest versions, OpenAL seeking is relative to the current play position, not relative to the start of the file, thus the file :smile:
