### ISSUE TITLE
ByteArray (_v2) does not have "length" setter.

### ISSUE THREAD

**Issue by Type1J** [openfl/openfl#489]
In flash, a flash.utils.ByteArray has a length property, which is settable. In OpenFL, there is a "setLength()" public function, however that function is not available in flash. In other words, for portable Haxe code, one has to

    #if flash
    byteArray.length = 0x10000;
    #else
    byteArray.setLength(0x10000);
    #end

when one should be able to

    byteArray.length = 0x10000;

in both cases.

**Comment by ibilon** [comment]
The legacy ByteArray extends directly `haxe.io.Bytes`,
nothing we can do.
