### ISSUE TITLE
html5 - addChild not rendering added child to screen in certain condition + possible fix

### ISSUE THREAD

**Issue by nndovo** [openfl/openfl#490]
When creating a new display object but adding it as a child only several frames later,
if nothing else is changed in the stage, the call to addChild doesn't cause the stage to update.

sample code to recreate the issue (used the DisplayABitmap sample and changed the Main a bit):
```
package;

import openfl.events.Event;
import openfl.display.Bitmap;
import openfl.display.BitmapData;
import openfl.display.Sprite;
import openfl.Assets;

class Main extends Sprite {
	
	private var _bitmap:Bitmap;
	private var _isFirst:Bool;

	public function new () {
		super ();

		_bitmap = new Bitmap (Assets.getBitmapData ("assets/openfl.png"));
		_bitmap.x = (stage.stageWidth - _bitmap.width) / 2;
		_bitmap.y = (stage.stageHeight - _bitmap.height) / 2;
		_isFirst = true;
		addEventListener(Event.ENTER_FRAME, handleFrame);
	}
	
	private function handleFrame(e:Event):Void {
		if (!_isFirst) {
			removeEventListener(Event.ENTER_FRAME, handleFrame);
			addChild(_bitmap); // THIS LINE IS NOT WORKING
		}
		_isFirst = false;
	}
}
```
All I do here is create the bitmap first, then wait for at least one frame to pass,
then add the child.
In the html5 target, the child isn't shown.
In other targets (flash, neko) it is.

A possible fix is to change the code in the html5 codebase of the class DisplayObjectContainer,
In the function addChild, change the line:
```
child.__setRenderDirty ();
```
into:
```
var prevWorldRenderDirty:Int = DisplayObject.__worldRenderDirty;
child.__setRenderDirty ();
if (prevWorldRenderDirty == DisplayObject.__worldRenderDirty) {
	DisplayObject.__worldRenderDirty++;
}
```

**Comment by jgranick** [comment]
This is fixed in the current version, thank you :smile:
