### ISSUE TITLE
Bugged font after update

### ISSUE THREAD

**Issue by restorer** [openfl/openfl#492]
Finally able to reproduce this bug with minimal code - http://blog.zame-dev.org/pub/textfieldbug.zip

Illustration:
![screen shot 2015-02-04 at 16 36 27](https://cloud.githubusercontent.com/assets/85473/6041401/20974cf4-ac8d-11e4-93fc-eb41b568a615.png)

Fine on flash and html5 (both canvas and dom modes), but wrong font on native and neko.

To reproduce bug:

 1. set text
 2. call setTextFormat, change anything, but font    
 3. call setTextFormat, with changed font

Reverting https://github.com/openfl/openfl/commit/94193db04829ce9df201f5f0727316852fb68646 has no effect since latest openfl / lime updates (previously it "fixes" fonts)

**Comment by jgranick** [comment]
This was fixed, thanks :smile:
