### ISSUE TITLE
ColorTransform

### ISSUE THREAD

**Issue by kevinresol** [openfl/openfl#493]
From this [link](http://www.openfl.org/documentation/technical-overview/feature-matrix/) I learned that `ColorTransform` and `Transform` are available on native. But the following codes seems not working on native targets.

``` haxe
movieClip.transform.colorTransform.blueMultiplier = 0;
```

**Comment by mrcdk** [comment]
You need to apply a new `ColorTransform` object to be applied, try something like:
```haxe
var ct = new ColorTransform();
ct.blueMultiplier = 0;
movieClip.transform.colorTransform = ct;
```

**Comment by kevinresol** [comment]
Doesn't seem to work either. Even Actuate.transform().color() is not working

**Comment by kevinresol** [comment]
Seems that the colorTransform does not apply on mc created by `Assets.getMovieClip()`

**Comment by jgranick** [comment]
I've partially fixed this on HTML5, using alpha:

https://github.com/openfl/openfl/commit/d074a4fbe81b1b676a8269717bc78ed056583469

This was affecting content flowing from the SWF library.

I'm not immediately sure how color transform might work on canvas, should be possible on GL :smile:

**Comment by Horsetopus** [comment]
Does it work when you stop() the movie clip before you apply the colorTransform?

**Comment by jgranick** [comment]
Moving this topic to https://trello.com/c/jEkE8r1B/16-add-support-for-sprite-transform-colortransform

**Comment by jgranick** [comment]
Tracking here: https://github.com/openfl/openfl/issues/493

**Comment by kevinresol** [comment]
Seems you are linking back to this issue

**Comment by jgranick** [comment]
Haha, whoops, I meant this one 😊 https://github.com/openfl/openfl/issues/1403
