### ISSUE TITLE
Assets.getBitmapData does not work as expected in HTML5

### ISSUE THREAD

**Issue by 62316e** [openfl/openfl#498]
var bmp1:Bitmap = Assets.getBitmapData("assets/ui/normal.png");
var bmp2:Bitmap = Assets.getBitmapData("assets/ui/normal.png");

bmp1.x = 0;
bmp2.x = 100;

addChild(bmp1);
addChild(bmp2);

On Flash: i see 2 bitmaps.
On HTML5: I see only 1 bitmap (chrome, firefox)

**Comment by jgranick** [comment]
This is working properly for me:

````haxe
package;


import openfl.display.Bitmap;
import openfl.display.Sprite;
import openfl.Assets;


class Main extends Sprite {
	
	
	public function new () {
		
		super ();
		
		var bmp1 = new Bitmap (Assets.getBitmapData("assets/openfl.png"));
		var bmp2 = new Bitmap (Assets.getBitmapData("assets/openfl.png"));
		
		bmp1.x = 0;
		bmp2.x = 100;
		
		addChild(bmp1);
		addChild(bmp2);
		
	}
	
	
}
````

I'm using an openfl.png graphic from one of the samples.

**Comment by jgranick** [comment]
I'm closing this for now, but please let me know if there is a case that does cause problems :)

**Comment by 62316e** [comment]
The problem is next line of code:
<set name="html5-backend" value="openfl-bitfive" />

Sorry.
