### ISSUE TITLE
BitmapData.threshold() issues

### ISSUE THREAD

**Issue by azrafe7** [openfl/openfl#502]
Short desc: it doesn't work consistently across targets (tested with openfl 2.2.6 + lime 2.1.1 on win7).

Now for the long one:

I've written some visual tests' code to see in which cases it wouldn't work (see https://gist.github.com/azrafe7/b1acee98175c98504ce1).
The results of the tests can be summed up by looking at these screenshots (green text -> test passed, red text -> test failed):

 - [flash](https://dl.dropboxusercontent.com/u/32864004/dev/FPDemo/openfl-threshold/flash.png) (i.e. what to be expected - all green!)
 - [js](https://dl.dropboxusercontent.com/u/32864004/dev/FPDemo/openfl-threshold/js.png)
 - [neko](https://dl.dropboxusercontent.com/u/32864004/dev/FPDemo/openfl-threshold/neko.png)
 - [cpp](https://dl.dropboxusercontent.com/u/32864004/dev/FPDemo/openfl-threshold/cpp.png)

The good news is that js seems to be easily fixed (passing all tests) by just commenting out these two lines calling `__flipPixel()`: https://github.com/openfl/openfl/blob/950f9e151e15d0e68f4e88fda15854e797137004/openfl/display/BitmapData.hx#L1280-L1281.

For cpp/neko I haven't been able to find a fix, but it's interesting to note that `setPixel32()` doesn't seem to work right on neko when involving alpha, while it does on cpp! (confront the bottommost test in the screenshots for neko and cpp).

Somehow related to this:
 - `BitmapData.clone()` has some issues in js, f.e. it won't work with the tests mentioned above (see https://gist.github.com/azrafe7/b1acee98175c98504ce1#file-thresholdtests-hx-L125)
 - setting the font to `_typewriter` fails on js, but works on other targets

**Comment by jgranick** [comment]
I think this may be resolved now?

**Comment by azrafe7** [comment]
Don't know (yet), but I'll probably have time tomorrow to retest this against latest git. ;)

**Comment by azrafe7** [comment]
I've just tested with the gist I posted above (against both haxelib and git versions of the libs), and unfortunately the issues are still there. :c

Not sure it's only on my end but it could be (must admit I've also other issues, especially with native crashing on start _unless using legacy_ - even hybrid fails me now, but worked some weeks ago). 

I'm really open to suggestions on how to fix these ones, so if you're around (tomorrow night) on irc/gitter/something, we can try to go through this together and maybe find a solution.

By the way here's the steps I've gone through (in case you can spot something wrong):

 - I've haxelib git both openfl and lime (being sure they're set as `git` reviewing `haxelib list` output)
 - recompiled lime with `openfl rebuild windows -Dlegacy` (as the ndll wasn't there)
 - tested the gist on various targets

BTW I'm on Win7 64bit

**Comment by jgranick** [comment]
I just checked, it looks the same now :smile:

**Comment by azrafe7** [comment]
Well... now for me js works correctly (and even the font issue seems resolved), but the output for cpp and neko is the same wrong one of the first post.

I can only run the gist in -Dv2 mode, as the app crashes on start if I omit it (and that's probably because I have an old Intel GPU - still wonder why noone has shown up with the same problem on the forum).

I'd be glad if you can run it (here's the little [test project](https://dl.dropboxusercontent.com/u/32864004/dev/FPDemo/openfl-threshold/OpenFlThreshold.zip)) and see if the output is the same as the flash one in both legacy and next.

**Comment by jgranick** [comment]
The output is the same in native legacy because the fixes are for OpenFL 3 and Lime, not legacy. Does your project work if you use "--window-hardware=false"?

**Comment by azrafe7** [comment]
Yes, it works. :open_mouth: That's great! :smiley: 

Never heard of that flag, what does it do? Falls back to software rendering I could guess?!

Anyway, can the fix be backported to legacy?

**Comment by jgranick** [comment]
Yep, that flag forces software rendering. Are you running a system that has trouble with OpenGL 2 features? We need to add something to detect this case and fallback to software automatically, when GL is supported but not the version we're looking for

**Comment by azrafe7** [comment]
Well... GLView says the driver supports OpenGL 2.1 at 100%:

![opengl](https://cloud.githubusercontent.com/assets/1266447/10070421/aaa3fe16-62b2-11e5-82eb-7b57ede51db9.jpg)


but I recall having the same crash-at-start problem with luxe (haven't retried in a while though).
