### ISSUE TITLE
Incorrect filling of paths with collinear points

### ISSUE THREAD

**Issue by isohedral** [openfl/openfl#503]
Some non-convex paths containing collinear points are filled incorrectly in OpenFL when using the standard openfl.display classes.  Here's a simple example.

    package;

    import openfl.display.Sprite;

    class Main extends Sprite {
        public function new () {
            super();

            graphics.lineStyle( 2.0 );
            graphics.beginFill( 0x8080ff );
            graphics.moveTo( 100, 100 );
            graphics.lineTo( 150, 100 );
            graphics.lineTo( 150, 150 );
            graphics.lineTo( 200, 150 );
            graphics.lineTo( 200, 100 );
            graphics.lineTo( 250, 100 );
            graphics.lineTo( 250, 150 );
            graphics.lineTo( 250, 200 );
            graphics.lineTo( 200, 200 );
            graphics.lineTo( 150, 200 );
            graphics.lineTo( 100, 200 );
            graphics.lineTo( 100, 150 );
            graphics.endFill();
        } 
    }

It's easy to see that the stroked path doesn't match the filled region.  If you remove the collinear points (I think there are four of them), the shape fills correctly.

**Comment by ibilon** [comment]
Can't reproduce anymore,
if you still have this problem on latest openfl please reopen.
