### ISSUE TITLE
Issue using sound samples from memory that are 32-bits per sample

### ISSUE THREAD

**Issue by jgranick** [openfl/openfl#511]
Details: https://github.com/openfl/lime/issues/307

We may also need to work out code to try and figure out the audio type without headers?

**Comment by zaynyatyi** [comment]
there are also none of parameters except bytes are used. Such as sampleRate, stereo, etc. How can you detect from PCM data if it's 44100 Hz 16 bit stereo or 44100 Hz 32 bit mono?
