### ISSUE TITLE
iOS audio does not resume after a phone call interruption

### ISSUE THREAD

**Issue by jgranick** [openfl/openfl#512]
Details: https://github.com/openfl/lime/issues/284

**Comment by starburst997** [comment]
I would like to add that it is not only wav sounds but all audio that stops working, the whole app become silent after a phone call, any attempt to play a sound afterward result in silence.

**Comment by PaulGene** [comment]
This also happens on Android, and any kind of interruption seems to cause it not just phone calls.

**Comment by joonjoonjoon** [comment]
This happens on iOS with any sound (music or sfx) in my game, with alarms or phone calls or timers.
Easiest way to test is to set a timer to 10 sec and launch your app, it will get interrupted.

I tried to write a native extension to fix this, based on some StackOverflow posts.
It seems that you have to manually tell the AVAudioSession to resume after an interruption. I'm able to detect the interruption, but not resume.

I added the following to one of my existing extensions. The NSLog shows up, but the sound stays muted.
```
@interface GlitchIOSWrapper : NSObject {
}
- (void)onAudioSessionEvent: (NSNotification *) notification;
@end

@implementation GlitchIOSWrapper

- (void) onAudioSessionEvent: (NSNotification *) notification
{
	//Check the type of notification, especially if you are sending multiple AVAudioSession events here
	if ([notification.name isEqualToString:AVAudioSessionInterruptionNotification]) {
		NSLog(@"Interruption notification received!");

		//Check to see if it was a Begin interruption
		if ([[notification.userInfo valueForKey:AVAudioSessionInterruptionTypeKey] isEqualToNumber:[NSNumber numberWithInt:AVAudioSessionInterruptionTypeBegan]]) {
			NSLog(@"Interruption began!");

		} else {
			NSLog(@"Interruption ended!");
		AVAudioSession *session = [AVAudioSession sharedInstance];
		[session setActive: YES error: nil];
		}
	}
}

@end
```

**Comment by grapefrukt** [comment]
The current version of rymdkapsel (using Lime 2.1.3 and OpenFL 2.2.8) also suffers from this exact issue.

**Comment by jgranick** [comment]
I think every version of NME/OpenFL has not handled audio interruption yet

**Comment by joonjoonjoon** [comment]
well so getting the interruption event it pretty easy, as I've detailed above, but I'd need to understand more of how OpenFL does audio to look into it further

**Comment by PaulGene** [comment]
**Bump**
If somebody could point me in the right direction to fix this that would be great. I can't release until it's fixed.

**Comment by PaulGene** [comment]
Does this also effect Next?

**Comment by xerosugar** [comment]
+1 this should definitely be fixed.

**Comment by grapefrukt** [comment]
I did some digging on this last night and made great progress. I'm not too well read on how the sound works in regular OpenFL (as opposed to legacy) but I suspect this issue might be present there as well. 

Anyway, it turns out you need to subscribe to an audio interruption event. When this comes in, set the OpenAL audio session to inactive and set the current session to null. 
Once the event for reactivation comes in, you do the opposite. 

I'm doing experiments with this in an extension, but if this turns out to work reliably (and it seems it does) I think this should go into Lime itself. 

Here's the code in question: https://github.com/grapefrukt/extension-ios-audio/compare/interrupt

**Comment by all360** [comment]
Can you post a code example of how you where able to make it work. Thanks

**Comment by grapefrukt** [comment]
I did. Right here: https://github.com/grapefrukt/extension-ios-audio/compare/interrupt
I'm about to clean that up and make it a proper part of that extension, so give it a couple of hours (days maybe) and you can just drop that in and go.

**Comment by all360** [comment]
Your extension works GREAT! it fixed the issue.

**Comment by PaulGene** [comment]
Fantastic!

Would be great if this was built into lime and a similar fix found for Android.

**Comment by grapefrukt** [comment]
Yeah, the extension should be ready to just drop in now. I'm short on time (parental leave) so I don't have  the time to integrate this into Lime proper or to give it the testing it deserves once integrated. 
But, now the code is there, so it should be very possible for someone else to pick up where I left it.
