### ISSUE TITLE
Second call Textfield.defaultTextFormat crash app on windows

### ISSUE THREAD

**Issue by alagatar** [openfl/openfl#514]
Libs:
Openfl 2.2.7
Lime 2.1.2 
This is when use haxeflag name="-dce full"
Second call Textfield.defaultTextFormat crash app on windows.
Sample:
var format:TextFormat=new TextFormat(12, 0x000000);
format.align=TextFormatAlign.LEFT;
var t:TextField=new TextField();
t.defaultTextFormat=format;
t.setTextFormat(format);

trace(t.defaultTextFormat);

**Comment by jgranick** [comment]
Fixed :smile:

https://github.com/openfl/openfl/commit/27b98b27d1d2bf231ccccea0f7f849c07572e5c3
