### ISSUE TITLE
Lines not drawing with CapsStyle.NONE

### ISSUE THREAD

**Issue by raggy** [openfl/openfl#518]
After updating to the latest builds of OpenFL/Lime (from openfl.org/builds) lines won't draw with CapsStyle.NONE. Interestingly, drawCircle() works, where moveTo() then lineTo() doesn't.

This was working in lime 2.0.5 / openfl 2.2.3 (and possibly newer versions too).

```haxe
package;


import openfl.display.CapsStyle;
import openfl.display.LineScaleMode;
import openfl.display.Sprite;


class Main extends Sprite {
	
	
	public function new () {
		
		super ();

		graphics.lineStyle(10, 0x000000, 1., false, LineScaleMode.NORMAL, CapsStyle.NONE);
		graphics.moveTo(100, 200);
		graphics.lineTo(200, 300);
		
		
	}
	
	
}
```

**Comment by ibilon** [comment]
Was fixed.
