### ISSUE TITLE
Masks Not Working

### ISSUE THREAD

**Issue by ediblebird** [openfl/openfl#52]
when adding a 300 x 300 mask to the actuate example, it worked as expected on neko and cpp:
![image](https://f.cloud.github.com/assets/4746096/725636/a44de50e-e087-11e2-9cdb-8cf46358406e.png)
but on flash does this (occasionally one or two sprites will be temporarily masked) :
![image](https://f.cloud.github.com/assets/4746096/725637/ea0acf3a-e087-11e2-9e40-e3016b961608.png)
and on html5 does this:
![image](https://f.cloud.github.com/assets/4746096/725646/9a6f7e84-e088-11e2-9520-a573a8d69afc.png)

**Comment by jespertheend** [comment]
I was having this issue as well and using
`Sprite.cacheAsBitmap = true;` fixed it for me.
It seems like masks are not supported on WebGL but they are using the canvas 2D context.
Using cacheAsBitmap seems to force using the 2D context.
