### ISSUE TITLE
Custom([file_write,stderr]) and 'Not Sound"

### ISSUE THREAD

**Issue by Jacic** [openfl/openfl#521]
I've been working on a game for some time now, developing and testing on Linux. Yesterday, I built a Windows version and tested it. I'm using the HaxePunk engine, and randomly (as far as I can tell) when switching scenes, a dialog box would pop up. It says "Custom([file_write,stderr])" and has an "OK" buttton, which ends the program when clicked. I did more testing in debug mode with HXCPP_DEBUGGER enabled, and got this stack trace when the problem occurred.

Error after opening sound data
Not Sound
Called from extern.cffi (C:/HaxeToolkit/haxe/lib/hxcpp/3,1,68/src/hx/Lib.cpp lin
e 133)
Called from openfl._v2.media.Sound.loadCompressedDataFromByteArray (openfl/_v2/m
edia/Sound.hx line 122)
Called from __ASSET__sfx_shoot_wav.new (openfl/_v2/Assets.hx line 1928)
Called from Type.createInstance (C:\HaxeToolkit\haxe\std/cpp/_std/Type.hx line 8
2)
Called from DefaultAssetLibrary.getSound (DefaultAssetLibrary.hx line 1183)
Called from openfl._v2.Assets.getSound (openfl/_v2/Assets.hx line 481)
Called from com.haxepunk.Sfx.new (com/haxepunk/Sfx.hx line 39)
Called from LevelEndScene.new (LevelEndScene.hx line 328)
Called from PlayScene.update (PlayScene.hx line 346)
Called from com.haxepunk.Engine.update (com/haxepunk/Engine.hx line 129)
Called from com.haxepunk.Engine.onEnterFrame (com/haxepunk/Engine.hx line 304)
Called from openfl._v2.events.EventDispatcher.dispatchEvent (openfl/_v2/events/E
ventDispatcher.hx line 98)
Called from openfl._v2.display.DisplayObject.__dispatchEvent (openfl/_v2/display
/DisplayObject.hx line 182)
Called from openfl._v2.display.DisplayObject.__broadcast (openfl/_v2/display/Dis
playObject.hx line 161)
Called from openfl._v2.display.DisplayObjectContainer.__broadcast (openfl/_v2/di
splay/DisplayObjectContainer.hx line 280)
Called from openfl._v2.display.DisplayObjectContainer.__broadcast (openfl/_v2/di
splay/DisplayObjectContainer.hx line 256)
Called from openfl._v2.display.DisplayObjectContainer.__broadcast (openfl/_v2/di
splay/DisplayObjectContainer.hx line 256)
Called from openfl._v2.display.Stage.__render (openfl/_v2/display/Stage.hx line
1058)
Called from openfl._v2.display.Stage.__checkRender (openfl/_v2/display/Stage.hx
line 333)
Called from openfl._v2.display.Stage.__pollTimers (openfl/_v2/display/Stage.hx l
ine 1043)
AL lib: (EE) alc_cleanup: 1 device not closed

The sound file exists, and it's being used before this point, and it is usually loaded at this point, as the error happens randomly. I read that others were having issues with a "Custom([file_write,stderr])" error that may have been caused by using dead code elimination, but I never specified dce when compiling. I am also embedding assets. This problem only occurs in the Windows build. Does anyone know would could be causing this and how to fix it?

**Comment by grapefrukt** [comment]
FWIW the `Custom([file_write,stderr])` is a message that appears when an exception is thrown and not caught. OpenFL then somehow tries to write that error to disk or something, but fails in the process and that dialog box appears. So, that means that any error that would throw an exception will give that same dialog box.

**Comment by Jacic** [comment]
Alright, that makes sense. The part I'm not understanding is how a .wav sound file could sometimes not be valid sound data, and sometimes be fine. The file is being loaded successfully earlier on, and can even play correctly, but sometimes it fails to load at a later point, as displayed in the stack trace. Any idea why this happens or how to fix it?

**Comment by jgranick** [comment]
There was a file handle leak that could occur before (depending on which code paths your project followed down), which could lead to valid sounds not loading. Resolved in newer versions :smile:
