### ISSUE TITLE
TextField returns different value on second get_textHeight() call

### ISSUE THREAD

**Issue by vroad** [openfl/openfl#523]
TextField measures its height with different method when I call get_textHeight() second time.
First time with DOM, and second time with canvas.
I think that there is no need to use different method for measuring text height, as there is no accurate way for measuring text height with canvas.

https://github.com/openfl/openfl/blob/master/openfl/text/TextField.hx#L1640

**Comment by vroad** [comment]
Maybe I should comment on existing issue.
https://github.com/openfl/openfl/issues/288

**Comment by 62316e** [comment]
Reopen please!
Such bugs must be priority number 1.
