### ISSUE TITLE
HTML5 target addEventListener useCapture doesn't bubble

### ISSUE THREAD

**Issue by peteshand** [openfl/openfl#525]
HTML5 addEventListener useCapture doesn't bubble.

If you running the following code with the Flash and HTML5 targets you will see different results:

```
package com.imag.useCaptureExample;

import com.imag.robotlegsHaxe.view.AddTest;
import openfl.display.Sprite;
import openfl.events.Event;

/**
* ...
* @author P.J.Shand
*/
class Main extends Sprite
{
public function new() 
{
super();

	var test:AddTest = new AddTest();
	test.name = 'AddTest';
	test.addEventListener(Event.ADDED_TO_STAGE, onViewAddedToStage, true);
	addChild(test);
}

private function onViewAddedToStage(e:Event):Void 
{
	removeEventListener(Event.ADDED_TO_STAGE, onViewAddedToStage);
	trace("Main onViewAddedToStage = " + e.target.name);
}
}
```

```
package com.imag.useCaptureExample;

import flash.events.Event;
import openfl.display.Sprite;

/**
* ...
* @author P.J.Shand
*/
class AddTest extends Sprite
{

public function new() 
{
	super();

	trace("AddTest");

	addEventListener(Event.ADDED_TO_STAGE, onViewAddedToStage);

}

private function onViewAddedToStage(e:Event):Void 
{
	removeEventListener(Event.ADDED_TO_STAGE, onViewAddedToStage);

	trace("AddTest onViewAddedToStage");

	var test:Sprite = new Sprite();
	test.name = "child";
	addChild(test);
}	
}
```

Trace Results:

AS3 Flash
>AddTest onViewAddedToStage
Main onViewAddedToStage = child
Main onViewAddedToStage = child

OpenFL Flash Target:
>AddTest.hx:23: AddTest onViewAddedToStage
Main.hx:25: Main onViewAddedToStage = child
Main.hx:25: Main onViewAddedToStage = child

OpenFL HTML5 Target:
>AddTest.hx:23: AddTest onViewAddedToStage

This pull request resolves the Event.ADDED_TO_STAGE, however more work is required to create a more robust and general solution.
https://github.com/openfl/openfl/pull/524

Any help getting this fix or a more complete one into the main release of openFL would be greatly appreciated as I have public libraries that heavily rely on useCapture / bubbling when children are added to the displaylist to function correctly.

**Comment by jgranick** [comment]
I believe this is fixed, thank you :smile:

**Comment by peteshand** [comment]
that was fast, only took a year ;)

**Comment by jgranick** [comment]
I spoke too soon :frown:

I ran your test, I get these results:

```bash
AddTest.hx:18: AddTest
AddTest.hx:28: AddTest onViewAddedToStage
```

We'll have to look deeper into this.

Are you on Slack chat? We're working on better Stage3D/Starling support, and I'd like to talk to you

**Comment by NenadBojkovski** [comment]
Hi,
working on haxe port of robotlegs 1.5.2 (don't ask why :)) I found an edge case where this fix could cause a weird behaviour. Namely, I think that `parent.__targetDispatcher = this;` has to be changed with 
                          
	if(this.__targetDispatcher != null) {
		parent.__targetDispatcher = this.__targetDispatcher;
	} else {
		parent.__targetDispatcher = this;
	}

This will prevent changing of event.target to some of the event target's ancestors and hence unnecessary dispatch of the event to that ancestor.

Here is what I'm talking about. If we slightly modify the example above like so:

```
package;
import openfl.display.Sprite;
import openfl.events.Event;

/**
* ...
* @author P.J.Shand
*/
class Main extends Sprite
{
	public function new()
	{
		super();

		addEventListener(Event.ADDED_TO_STAGE, onViewAddedToStage, false, 0, true);
		addEventListener(Event.ADDED_TO_STAGE, onViewAddedToStageCapture, true, 0, true);
	}

	private function onViewAddedToStageCapture(e:Event):Void
	{
		trace("Main onViewAddedToStage[Capture Phase] = " + e.target.name);
	}
	private function onViewAddedToStage(e:Event):Void
	{
		addEventListener(Event.ADDED_TO_STAGE, onViewAddedToStage, false, 0, true);
		trace("Main onViewAddedToStage = " + e.target.name);
		var test:AddTest = new AddTest();
		test.name = 'AddTest';
		addChild(test);
	}
}
```

and the other class:

```
import openfl.events.Event;
import openfl.display.Sprite;

/**
* ...
* @author P.J.Shand
*/
class AddTest extends Sprite
{

	public function new()
	{
		super();

		trace("AddTest");
		var test:Sprite = new Sprite();
		test.name = "child";
		addEventListener(Event.ADDED_TO_STAGE, onViewAddedToStage);

		addChild(test);
	}

	private function onViewAddedToStage(e:Event):Void
	{
		trace("AddTest onViewAddedToStage");
	}
}
```
      
the trace log will be:

>Main onViewAddedToStage = null
>AddTest
>Main onViewAddedToStage[Capture Phase] = null
>AddTest onViewAddedToStage
>Main onViewAddedToStage[Capture Phase] = null
>AddTest onViewAddedToStage    

Note that we have two `AddTest onViewAddedToStage` logged twice. So the AddTest's `onViewAddedToStage` is performed twice which could cause a weird behaviour(as it did in my case). One would expect that this listener will be performed only once.
Setting `parent.__targetDispatcher` as it is stated above fixes this issue.
I hope you guys will have this edge case in mind when you do a proper fix.
Good luck!
