### ISSUE TITLE
Class<flash.text.Font> has no field __fromLimeFont

### ISSUE THREAD

**Issue by T1mL3arn** [openfl/openfl#537]
Both Lime and OpenFl is last dev version. Haxe 3.1.3 and some of latest build (but not 3.2.0 rc1). Only for flash.
Errors
```
C:/HaxeToolkit/openfl-dev/openfl/Assets.hx:159: characters 14-33 : Class<flash.text.Font> has no field __fromLimeFont
C:/HaxeToolkit/openfl-dev/openfl/Assets.hx:587: characters 16-35 : Class<flash.text.Font> has no field __fromLimeFont
```

I tried to use ``` import openfl.text.Font in OpenflFont``` but it didn't help.

**Comment by T1mL3arn** [comment]
Also, reverting the changes to b9aa2e9 for OpenFl and https://github.com/openfl/lime/commit/3d740424d572ed3f2e422926a11e883dbc20a96d for Lime temporary solves the problem.

**Comment by delahee** [comment]
+1 on this one, pleaaase :)
