### ISSUE TITLE
Inconsistent Anti-aliasing bitmapData.draw(shape) between iOS and other native platforms.

### ISSUE THREAD

**Issue by grisevg** [openfl/openfl#538]
Hi, 

I've noticed that on legacy (_v2 nme) iOS shapes are not anti-aliased when drawn on bitmap, unless they have `cacheAsBitmap=true` while on other native legacy (_v2 nme) platforms bitmapdata.draw(shape) always results in anti-aliased image.

It would be nice to make behaviour consistent across all native platforms.

**Comment by ibilon** [comment]
No more big work is done on legacy,
if you still need it then you should use `cacheAsBitmap=true`.

If that is still an issue on next feel free to reopen.
