### ISSUE TITLE
[android][haxe 3.2.0-rc1] Can't build project on Android target

### ISSUE THREAD

**Issue by Hitek55** [openfl/openfl#541]
class Main {
	    public function new()
	    {
	   	    trace("hello world!");
	    }
    }

cmd: "C:\HaxeToolkit\haxe/haxelib" run lime build "application.xml" android -debug -Dfdb
Error: Could not find build target "HXCPP_ARMV7=1"
Build halted with errors.

openfl 2.2.8
lime 2.1.3
hxcpp 3.2.27

**Comment by jgranick** [comment]
You need to use dev versions of OpenFL and Lime, though be aware you may need to add "-Dlegacy" when testing in order to use Android

**Comment by Hitek55** [comment]
Thank you! It works for me!
