### ISSUE TITLE
SoundChanel stop only last sound, not all

### ISSUE THREAD

**Issue by alagatar** [openfl/openfl#542]
Hi,
openfl 2.2.8
lime 2.1.3
Target, html5, platform, c++
SoundChanel stop(), stop only last sound but must stop all chanel sounds

**Comment by jgranick** [comment]
Shouldn't that stop only the channel? Is there a Sound.stop() as well?

**Comment by alagatar** [comment]
I think right is, if you call stop on soundchanel, all sounds that plays on this chanel need be stoped

**Comment by alagatar** [comment]
Sound no have stop() function

**Comment by jgranick** [comment]
Does it work the same as the Flash target?

As I understand it, you have one sound, which can be played multiple times at once, each instance is a SoundChannel. You need to stop each sound channel individually if you want to stop all playing sounds

**Comment by alagatar** [comment]
Yes on Flash target it same. About issue, i have few sounds, different length. I play it on one chanel, and when i need stop sounds, i call chanel.stop(); but it stop playing only last sound which play on this chanel.

**Comment by Sunjammer** [comment]
This is not a bug. The soundchannel instance is a reference to ONE playing sound. When you call Sound.play you get ONE soundchannel for that specific playback instance. If you want to stop all instances of a playing sound you need to manage a list of soundchannels yourself.

**Comment by alagatar** [comment]
I think, better was 1 chanel for sfx, and if you can stop it, stop playing all sound on it.

**Comment by Sunjammer** [comment]
That's not how the API is designed though :)

**Comment by alagatar** [comment]
I understand now, sound play generate chanel, and you cant play sound on some specified chanel... Becouse of that need handler all soundchanels, if you need stop all sound, need stops all chanels..
