### ISSUE TITLE
$haxelib error Class not found

### ISSUE THREAD

**Issue by katopz** [openfl/openfl#543]
I should missing something here, `$ haxe` is fine btw but  `$ haxelib` give me this error.
```shell
$ haxelib install openfl
/usr/lib/haxe/std/Map.hx:136: lines 136-138 : Class not found : V
```
Please help.

**Comment by jgranick** [comment]
What version of Haxe/haxelib do you have installed, what platform?

**Comment by katopz** [comment]
@jgranick 
I'm on Mac OSX Yosemite 10.10.2 
haxe 3.2.0

but for haxe lib I just install it and i just can't find the way to get it versions because... 
```shell
$ haxelib
/usr/lib/haxe/std/Map.hx:136: lines 136-138 : Class not found : V
```
also return error

i'm trying reinstall with 3.1.3 (http://www.openfl.org/documentation/getting-started/installing-openfl/) but still get 3.2.0 btw

This is weird, should be only me tho, never have this problem on windows before.
Is this a way to clean uninstall?

**Comment by katopz** [comment]
oh! I know what's wrong here, I'm install haxe with `$ brew install haxe` with head revision
and suddenly `$ haxkelib` acting weird after that

now i'm revert back by `$ brew uninstall haxe` and use installer 3.13 instead now everything seem to be fine.

**Comment by jgranick** [comment]
This is good to know, I wonder why is in charge of that script
