### ISSUE TITLE
Calling getPixels causes a segmentation fault in Linux cpp

### ISSUE THREAD

**Issue by MintPaw** [openfl/openfl#545]
Title sums it up, when running:

```haxe
var bmp:BitmapData = new BitmapData(200, 200);
bmp.getPixels(new Rectangle(10, 10, 10, 10));
```
I get:

> mintpaw@MintPaw-PC:~/MapEditor$ Export/linux64/cpp/bin/MapEditor 
> Could not find primitive lime_set_package__4.
> Could not find primitive lime_set_package__4.
Segmentation fault (core dumped)

I'm compiling using:
> hxcpp: [3.2.37] 
> lime: [2.2.1]
> openfl: [2.2.8]

Compiling with "openfl build cpp -debug"
It works fine using neko("openfl build neko -debug") and also work in Windows

**Comment by jgranick** [comment]
Are you using the OpenFL command to build? This seems like a mismatch. "lime_set_package" is a legacy Lime 1 call, it does not exist in the Lime 2 API. I'm not sure what code might be calling this?

**Comment by MintPaw** [comment]
Yeah, I said I'm compiling with "openfl build cpp -debug"
What info do you need?

**Comment by jgranick** [comment]
Would you mind trying a plain OpenFL sample project or Lime sample project, and see if they work on your system?

Oh, I have not tested OpenFL 2.2.8 with Lime 2.2.1, been using OpenFL 3.0.0 beta

**Comment by MintPaw** [comment]
I used the DisplayingABitmap test and added the getPixels line. It fails regardless of openfl version.
Compiled with "openfl build cpp"

openfl 2.2.8 - http://i.imgur.com/QqKYIYW.png
openfl 3.0.0 - http://i.imgur.com/jRQJAmx.png

**Comment by jgranick** [comment]
I just tested a new project using the following code:

```haxe
package;


import openfl.display.BitmapData;
import openfl.display.Sprite;
import openfl.geom.Rectangle;


class Main extends Sprite {
	
	
	public function new () {
		
		super ();
		
		var bmp:BitmapData = new BitmapData(200, 200);
		var pixels = bmp.getPixels (new Rectangle (10, 10, 10, 10));
		trace (pixels.length);
		pixels.position = 0;
		trace (StringTools.hex (pixels.readUnsignedInt (), 8));
		
	}
	
	
}
```

It worked properly on Flash, HTML5, Neko and C++, though the native targets returned a ByteArray that was too large. I fixed this issue just now on Lime.

So this seems fixed, let me know if you have more trouble, thank you!
