### ISSUE TITLE
keydown event returning weird keyCode/charCode on v3

### ISSUE THREAD

**Issue by fserb** [openfl/openfl#551]
Not sure if this is on purpose or not.
But on v3, when I press the left "command" key on my Mac, I get the following event:
```
[KeyboardEvent type=keyDown bubbles=true cancelable=false charCode=1073742051 keyCode=1073742051 keyLocation=0 ctrlKey=false altKey=false shiftKey=false]
```

on v2, I'd get:
```
[KeyboardEvent type=keyDown bubbles=true cancelable=true charCode=0 keyCode=15 keyLocation=1 ctrlKey=false altKey=false shiftKey=false]
```

Seems weird.

**Comment by jgranick** [comment]
It should be equal to `KeyCode.LEFT_META` or `KeyCode.RIGHT_META` from Lime but I don't see a mapping in `openfl.display.Stage` to a Flash equivalent. What does the command/meta key do on Flash Player? Does it dispatch? Does it have a value in the `flash.ui.Keyboard` class?
