### ISSUE TITLE
[android][haxe 3.2.0-rc.2] Generic error

### ISSUE THREAD

**Issue by Hitek55** [openfl/openfl#553]
package;

    class Test {
	    public function new() {}
    }

    class Main {
	    public static function main() {
		    new Generic<Test>();
	    }
    }

    @:generic
    class Generic<T:({function new():Void;})> {
	    var t:T;
	
	    public function new() {
		    t = new T();
	    }
    }

Error: ./src/Generic.cpp: In member function 'Void Generic_obj::__construct()':
./src/Generic.cpp:13: error: '__new' is not a member of 'Dynamic'
Build halted with errors.

openfl from git, lime from git, hxcpp 3.2.37

**Comment by Simn** [comment]
This is a haxe/hxcpp issue.
