### ISSUE TITLE
liblime.iphoneos.a on version 3.0.0-beta

### ISSUE THREAD

**Issue by CherryAnt** [openfl/openfl#554]
When I compile with 3.0.0-beta for ios i got the next issue:
Error:Source path "/usr/lib/haxe/lib/lime/2,2,1/ndll/IPhone/liblime.iphoneos.a" does not exist
If i change current version to 2.2.8 it works perfect

**Comment by mourlamstudios** [comment]
Looks like they are still working on the new iOS lib. For now you can add "-Dlegacy" argument to your lime command

**Comment by jgranick** [comment]
I got the iOS target working today, it will be in the builds for the next beta release :smile:
