### ISSUE TITLE
Odd Point() addition issue when exporting to windows [3.0.0-beta]

### ISSUE THREAD

**Issue by hoseyjoe** [openfl/openfl#556]
package;
import openfl.geom.Point;
import openfl.display.Sprite;
import openfl.Lib;
class Main extends Sprite {
	public function new() 	{
		super();
		var offset:Point = new Point(0, 0);   
        trace(offset.x +"," + offset.y + 6);
        trace( offset.y + 6);
	}
}

This Traces
Main.hx:9: 0,06
Main.hx:10: 6

I thought it was causing a crash but it does seem to cause issue

**Comment by Hasufel** [comment]
This seems like normal behavior.
If you do trace(0.0 + "," + 0.0 + 6); it will trace 0,06 as you mingle a string inside your params.
If you want addition, add parenthesis to tell trace that you're doing so, like:  (0.0 + "," + (0.0 + 6)) -> will trace 0,6

**Comment by hoseyjoe** [comment]
Seems fair enough.  Works same in Flash output to.  I would close this as not an issue
