### ISSUE TITLE
Graphics.drawRoundRect crashing c++ target [3.0.0-beta]

### ISSUE THREAD

**Issue by hoseyjoe** [openfl/openfl#557]
This crashes when compiling to windows/android

package;
import openfl.geom.Point;
import openfl.display.Sprite;
import openfl.Lib;
class Main extends Sprite {
	public function new() 	{
		super();
                this.graphics.lineStyle();
                this.graphics.beginFill(0xffffff); 
                this.graphics.drawRoundRect( 0,  0, 100,100,5,5);
	}
}

Crash happens on drawRoundRect

**Comment by mrcdk** [comment]
I'm not having any problem with it, what version are you using?

```
haxe: 3.1.3
hxcpp: 3.2.37
lime: 2.2.1
openfl: 3.0.0-beta
```

**Comment by hoseyjoe** [comment]
Ya, I dont know why I keep crashing.  I upgrade and it says downloading lime 2.2.1 but when I list it says 2.0.5..I am getting fresh install
