### ISSUE TITLE
Got IO.Overflow("write_ui16") error when -swf-lib somelib.swc

### ISSUE THREAD

**Issue by kevinresol** [openfl/openfl#567]
To reproduce:

Download a swc [here](https://github.com/crossbridge-community/crossbridge-swc-lua/blob/master/release/crossbridge-lua.swc)

Create a new OpenFL project
Put a picture in assets/img
Add the following to project.xml
```xml
<assets path="assets/img" rename="img" />
<haxeflag name="-swf-lib" value="/full/path/to/crossbridge-lua.swc"/>
```

Then `lime build flash` gives me `IO.Overflow("write_ui16") Build halted with errors.`

However, I successfully used the swc if I do not use lime/openfl(i.e. pure Haxe/Flash project)
So I suppose this is openfl or lime problem, I dunno......

**Comment by jgranick** [comment]
I'm going to close this one, we'll track on the Haxe Foundation Github, thanks! :smile:
