### ISSUE TITLE
Dox + Chxdoc issue with generated xml file under OpenFL 3.0.0-beta.3

### ISSUE THREAD

**Issue by aurodev** [openfl/openfl#568]
Generated xml file causes issues for dox and chxdoc under OpenFL 3.0.0-beta.3
Both work properly under OpenFL 2.2.8

Dox

Parsing myGeneratedDocs.xml
Dox.hx:124: Error while parsing myGeneratedDocs.xml
Called from ? line 1
Called from dox/Dox.hx line 138
Called from dox/Dox.hx line 125
Uncaught exception - xml.c(80) : Xml parse error : Expected > at line 36289 : ...\\&*()[]{}<>|:;_-+=?,. '">
        <c...

chxdoc

ChxDoc Generator 1.3.0 - (c) 2008-2012 Russell Weir
Called from ? line 1
Called from chxdoc/ChxDocMain.hx line 407
Called from chxdoc/ChxDocMain.hx line 1012
Called from chxdoc/ChxDocMain.hx line 1028
Called from /usr/lib/haxe/std/neko/_std/Xml.hx line 119
Uncaught exception - xml.c(80) : Xml parse error : Expected > at line 36289 : ...\\&*()[]{}<>|:;_-+=?,. '">
        <c...

xml Generated with:
haxeflag name="-xml" value="myGeneratedDocs.xml" 

Environment:

Win8.1

actuate: [1.8.3]
box2d: [1.2.3]
chxdoc: [1.3.0]
dox: [1.0.0]
flixel-addons: [1.1.0]
flixel-demos: [1.1.1]
flixel-templates: [1.0.2]
flixel-tools: [1.0.5]
flixel-ui: [1.0.2]
flixel: 3.3.6 [3.3.8]
hxcpp: [3.2.37]
hxcs: [3.2.0]
hxjava: [3.2.0]
iap: [1.0.6]
layout: [1.2.0]
lime-samples: [2.2.0]
lime-tools: [1.5.7]
lime: 2.1.2 2.2.1 [2.3.0]
openfl-bitfive: 2.1.6 [3.0.0]
openfl-samples: [2.2.2]
openfl: 2.2.8 [3.0.0-beta.3]
swf: [1.8.2]

**Comment by ibilon** [comment]
Could you pass your xml file through this validator? http://www.w3schools.com/xml/xml_validator.asp
We'll see if it's a problem with the xml file or the xml reader.

What version of haxe are you using? If you're trying the new 3.2 chxdoc probably won't work (I'm not even 100% sure it still work with the latest 3.1)

**Comment by jgranick** [comment]
Haxe 3.2 has some improvements to the XML generation which should help escape this

**Comment by aurodev** [comment]
For now it works under 2.2.8   will check,  brb...
Ok here's the result building under OpenFL 3.0.0-beta.3 from the xml validator site:

"XML Parsing Error: not well-formed
Location: http://www.w3schools.com/xml/xml_validator.asp
Line Number 36290, Column 145:
		<getGlyphs public="1" set="method" line="107"><f a="?characters" v="'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^`'\"/\\&*()[]{}<>|:;_-+=?,. '">
--------------------------------------------------------------------------------------------------------------------------------------------------------------^"
