### ISSUE TITLE
Sound length always 0 on html5

### ISSUE THREAD

**Issue by T1mL3arn** [openfl/openfl#572]
Property length does not sets. SoundJs not allows to read duration in simple way. For this is need to play sound and then read duration from SoundInstance object. Temporary solution for this (inside Sound.play() ):

``` Haxe
var instance = SoundJS.play (__soundID, SoundJS.INTERRUPT_ANY, 0, Std.int (startTime), 0, sndTransform.volume, sndTransform.pan);

this.length = instance.getDuration();

return new SoundChannel (instance);
```

But before play() calls is not possible to read property - it is always null. I tried to add play-stop hack into SoundJS_onFileLoad() but it doesn't helps.

**Comment by jgranick** [comment]
This works properly now, once the sound is loaded :smile:
