### ISSUE TITLE
[HTML5] haxe 3.2-rc2 with lime 2.3.0 and openfl 2.3.0 build fails

### ISSUE THREAD

**Issue by skylerparr** [openfl/openfl#573]
created a brand new project:
$ openfl create project sample

Build output:
$ lime test html5
/usr/lib/haxe/lib/openfl/2,2,8/openfl/text/TextField.hx:1185: characters 30-50 : js.html.Window has no field event
/usr/lib/haxe/lib/openfl/2,2,8/openfl/text/TextField.hx:1167: characters 30-50 : js.html.Window has no field event
/usr/lib/haxe/lib/openfl/2,2,8/openfl/text/TextField.hx:1083: characters 3-47 : js.html.DOMElement should be js.html.Element
/usr/lib/haxe/lib/openfl/2,2,8/openfl/display/Application.hx:512: lines 512-516 : Field onMouseMove overloads parent class with different or incomplete type
/usr/lib/haxe/lib/openfl/2,2,8/openfl/display/Application.hx:512: lines 512-516 : Different number of function arguments

tried legacy too:
$ lime test html5 -Dlegacy
Export/html5/haxe/ApplicationMain.hx:4: characters 11-20 : Class not found : lime.Lime

NOTE:
flash, neko, mac work

**Comment by skylerparr** [comment]
Sorry that's openfl 2.2.8

**Comment by jgranick** [comment]
Fixed in newer versions :smile:
