### ISSUE TITLE
[CPP/Neko] OpenFL 3.0.0-beta.3

### ISSUE THREAD

**Issue by alijaya** [openfl/openfl#576]
TextField behaviour changes in CPP / Neko.

It will compile, but crash in runtime if TextField doesn't have embeded Font.
The TextField can't be selected, and can't be edited.

**Comment by jgranick** [comment]
TextField is stable in current releases, the newer implementation has input on HTML5, but not native yet, but there's an issue open for it, and it will happen. Thank you! In the meantime, you can use `-Dlegacy` when compiling your project to use the older behavior :smile:
