### ISSUE TITLE
[OpenFL 3] Loading font from file

### ISSUE THREAD

**Issue by void616** [openfl/openfl#577]
Hi. I'm trying to load several fonts from the file with next code:
`var ba:ByteArray = ByteArray.readFile("some.ttf");`
`var font:Font = Font.fromBytes(ba);`

But now I have trouble with font registration. 
I've tried to involve the Lime (before 3.0.0 released):
`var lime_font_register_font = Lib.load("lime", "lime_font_register_font", 2);`
`lime_font_register_font(font.fontName, ba);`
`Font.registerFont(Type.getClass(font));`

So...
Is there any way to load and register font without diving into the Lime library?
In my case I can't embed fonts in my app.
Thanks.

**Comment by vance** [comment]
Have you tried loading with assets instead of reading the file directly?  http://www.openfl.org/archive/community/bugs/fonts/

**Comment by void616** [comment]
As I said, there is no way to use assets in my case, so I'll just get:
[Assets] There is no Font asset with an ID of _path_

**Comment by jgranick** [comment]
I think you can use `Font.fromFile` if I recall properly, or you may be able to use the font as the font name, like `textFormat.name = "path/to/my/font.ttf";`
