### ISSUE TITLE
libneko.* is not needed and may lead to crash in neko target

### ISSUE THREAD

**Issue by andyli** [openfl/openfl#579]
See the discussion over https://github.com/andyli/hxSerial/issues/7.

Probably OpenFL should not add libneko.* by default, and then provide a way to opt-in it.

**Comment by jgranick** [comment]
Does this affect using Neko builds standalone, with no Neko installed on the system? I had assumed this was a core Neko file that was needed, but if not (and it causes problems) then we could remove it

**Comment by ibilon** [comment]
libneko.* is required if the user doesn't have neko installed, without it the app won't start.

**Comment by andyli** [comment]
The interesting thing is, if libneko.* is present together with a "NEKO_COMPATIBLE" ndll, the app will crash. I'm not sure so I will let @hughsando to explain the technical detail.

**Comment by jgranick** [comment]
Perhaps it is the opposite? Wasn't it crashing without being NEKO_COMPATIBLE?

OpenFL and Lime use NEKO_COMPATIBLE, and haven't experienced crashes

**Comment by andyli** [comment]
The hxSerial.ndll is NEKO_COMPATIBLE, compiled with hxcpp 3.1.39.
