### ISSUE TITLE
On CPP, using transparent bitmap as mask is ineffective

### ISSUE THREAD

**Issue by scriptorum** [openfl/openfl#580]
I'm able to use a Shape as a mask, but not a Bitmap with an alpha layer, at least not on non-Flash targets. Here is [an example gist](https://gist.github.com/scriptorum/7b8a7cfd2bfed7ef4621). 

Given a transparent Bitmap with a black circle, added over a red Shape square:
![no-mask](https://cloud.githubusercontent.com/assets/3144427/7055356/cc671c08-de10-11e4-86c9-5eadb914a2f0.png)

Applying the mask shows correctly on Flash:
![flash-mask](https://cloud.githubusercontent.com/assets/3144427/7055154/650779aa-de0f-11e4-8904-2aa58362a4ad.png)

But not on CPP or Neko, which just hides the Bitmap.
![cpp-mask](https://cloud.githubusercontent.com/assets/3144427/7055318/969ef7bc-de10-11e4-9f62-6e3eb0b98629.png)

Note that [this example](https://gist.github.com/scriptorum/7b8a7cfd2bfed7ef4621) converts a shape into a transparent bitmap, which is bugged on CPP, unless you run `-Dlegacy` or use the latest OpenFL build where it's reputedly fixed. See https://github.com/openfl/lime/issues/403. To eliminate this conversion step, the gist has commented out code that applies the mask straight from an image file, with the same results.

**Comment by mrcdk** [comment]
There is no cacheAsBitmap implemented, and masks don't work over graphics.

**Comment by scriptorum** [comment]
> There is no cacheAsBitmap implemented

Okay, but I have to put cacheAsBitmap on or the Flash example doesn't work.

> masks don't work over graphics.

They do, but the mask has to be a graphic as well. For example, this circle shape is masking the rect shape successfully on CPP (`-Dlegacy`) and Flash:

```haxe
		var rect = new Shape();
		rect.graphics.beginFill(0xFF0000);
		rect.graphics.drawRect(0, 0, width, height);
		sprite.addChild(rect);

		var circle = new Shape();
		circle.graphics.beginFill(0);
		circle.graphics.drawCircle(width/2, height/2, width/2);
		sprite.addChild(circle);	
		rect.mask = circle;
```
In fact that's the only masking I can get to work. This example uses two loaded bitmaps, one masking the other, and they do not get the masking effect except on Flash:
```haxe
		var bm1:BitmapData = Assets.getBitmapData("assets/redBox.png");
		var interior = new Bitmap(bm1);
		interior.cacheAsBitmap = true;
		sprite.addChild(interior);

		var bm2:BitmapData = Assets.getBitmapData("assets/blackCircleAlpha.png");
		var mask = new Bitmap(bm2);
		mask.cacheAsBitmap = true;		
		sprite.addChild(mask);
		interior.mask = mask;
```

[Full gist here](https://gist.github.com/scriptorum/36616b23d8170afaf9b5). Graphics for the above demo:
![blackcirclealpha](https://cloud.githubusercontent.com/assets/3144427/7070639/3590e842-deae-11e4-9423-c3a2b92ca390.png)
![redbox](https://cloud.githubusercontent.com/assets/3144427/7070640/35a38f2e-deae-11e4-96d4-243c64c33a69.png)

**Comment by mrcdk** [comment]
I know it works on flash, I was talking about `next` Bitmap alpha masking won't be supported on `next`. It might be supported with a filter but don't quote me on that.

**Comment by scriptorum** [comment]
Hrm, okay. I didn't see bitmap alpha masking on the [openfl.org roadmap](http://www.openfl.org/learn/resources/contributors/roadmap/).

>  It might be supported with a filter but don't quote me on that.

Oops. :smirk:

**Comment by aaulia** [comment]
+1 for this.

**Comment by jgranick** [comment]
Moved to https://trello.com/c/mYoXqS0S/18-example-sprite-mask-support

**Comment by cletrix** [comment]
Hello,
Sorry for reopening this Thread, but I did some tests with the version:
actuate: [1.8.9]
box2d: [1.2.3]
hxcpp: [4.1.15]
layout: [1.2.1]
lime-samples: [7.0.0]
lime: [7.8.0]
openfl-samples: [8.7.0]
openfl: [8.9.7]
spritesheet: [1.2.0]
And I still notice the same problem, the mask has no effect with CPP. Any suggestion?

**Comment by cletrix** [comment]
```haxe
        var mask:Sprite = new Sprite();
        mask.graphics.beginFill(1);
        mask.graphics.drawRect(0, 0, 270, 800);
        mask.graphics.endFill();    
        mask.x = mask.y = 0;
        mask.cacheAsBitmap = true;
        addChild(mask);
        icons = new Array<Cell>();
        var temp_cell : Cell;

        for (i in 0...(count_columns * count_lines)) {
            temp_cell = new Cell(items_positions[i][0] - x , items_positions[i][1] - y, count_items);
            temp_cell.show(Std.random(count_items));
            temp_cell.cacheAsBitmap = true;
            addChild(temp_cell);
            icons.push(temp_cell);
        }

        icons[0].mask = mask;
        icons[5].mask = mask;
        icons[10].mask = mask;
```

HTML5 works.
