### ISSUE TITLE
[Neko/CPP] TextFormatAlign.CENTER not supported [3.0.1]

### ISSUE THREAD

**Issue by yupswing** [openfl/openfl#583]
TextFormatAlign.CENTER on multiline (\n) TextField has unexpected behaviour.

- if draw the TextField on a Graphics it is always aligned on the left
- if added the TextField to stage the first and second line are not centered but slightly on the left (I suppose problems on the elaboration of the glyphs size)

**Comment by Pinpickle** [comment]
I can confirm a similar behaviour:
Mac Target
![image](https://cloud.githubusercontent.com/assets/3238878/7245823/c3281710-e846-11e4-88a3-207b7480ff84.png)


Flash Target
![image](https://cloud.githubusercontent.com/assets/3238878/7245825/d193d2f8-e846-11e4-9955-d7289ce466e6.png)

**Comment by larsiusprime** [comment]
Are you guys using the latest version of openfl/lime from git? We recently worked on this issue:
https://github.com/openfl/openfl/issues/599

It looks like there's a 3.0.2 version of OpenFL up on github already, perhaps try that and see if this fixes it for you?

**Comment by Pinpickle** [comment]
@larsiusprime I have tried this on 3.0.2 and master branch without success. `-Dlegacy` doesn't give proper results either (text is centre aligned, but offset to the right)

**Comment by larsiusprime** [comment]
@Pinpickle Can you upload a minimal reproduction test case somewhere?

**Comment by Pinpickle** [comment]
Well, I thought I could, but that other test case has started working all of a sudden. 

On a slightly different not, I have noticed a discrepancy between legacy and next with the positioning of the text though. I think in this case next has it right and I don't know if that's fixing old behaviour or new problems have been introduced with legacy.

However, legacy manages to find the system font 'Arial' where next can't, which isn't related to this issue but worth pointing out.

Legacy (unexpected)
![image](https://cloud.githubusercontent.com/assets/3238878/7259041/9b0c30a4-e8b4-11e4-9b0a-4870f3155af4.png)

Next (expected)
![image](https://cloud.githubusercontent.com/assets/3238878/7259076/dc13122a-e8b4-11e4-919b-bbcc88316583.png)


Main.hx test case
````
package;


import openfl.display.Sprite;
import openfl.Assets;
import flash.text.TextFormat;
import flash.text.TextFormatAlign;
import flash.text.TextFieldAutoSize;
import flash.text.TextField;

class Main extends Sprite {
	
	
	public function new () {
		
		super ();
		
        var format = new TextFormat('Arial', 20, 0xAAAAAA);
        format.align = TextFormatAlign.CENTER;
        var bigFormat = new TextFormat('Arial', 180, 0xAAAAAA);
        bigFormat.align = TextFormatAlign.CENTER;

        var scoreText = new TextField();
        scoreText.defaultTextFormat = bigFormat;
        scoreText.autoSize = TextFieldAutoSize.CENTER;
        scoreText.text = '100';
        scoreText.x = 300;
        scoreText.y = 70;

        var points = new TextField();
        points.defaultTextFormat = format;
        points.autoSize = TextFieldAutoSize.CENTER;
        points.text = 'Your high score is 100\nWant to try again? Just press space';
        points.x = 300;
        points.y = 300;

        stage.addChild(scoreText);
        stage.addChild(points);
		
	}
	
	
}
````
