### ISSUE TITLE
Tilesheet.drawTiles fails to draw on negative coordinates in HTML5 

### ISSUE THREAD

**Issue by tpspoons** [openfl/openfl#588]
Edit: sorry this is a duplicate, I didn't see this issue: https://github.com/openfl/openfl/pull/434

If you specify negative coordinates in the drawTiles array, in HTML5 anything up to the origin is not rendered. Works fine in Windows (haven't tested on other platforms).

Example code:
		var c:Sprite = new Sprite ();
		var cont:Sprite = new Sprite ();
		
		c.graphics.beginFill (0xffffff);
		c.graphics.drawCircle (100, 100, 100);
		c.graphics.endFill ();
		
		var bd:BitmapData = new BitmapData (200, 200, true, 0);
		bd.draw (c);
		
		var tilesheet:Tilesheet = new Tilesheet (bd);
		tilesheet.addTileRect (new Rectangle (0, 0, 200, 200));
		
		addChild (cont);
		cont.x = cont.y = 50;
		
		tilesheet.drawTiles (cont.graphics, [ -50, -50, 0], false);

Result on Windows target (same with -Dlegacy and without):
![windows-result](https://cloud.githubusercontent.com/assets/11801387/7092448/e87d5af2-dfa9-11e4-87f5-0f51b8c1d0a9.PNG)

Result on HTML5:
![html5result](https://cloud.githubusercontent.com/assets/11801387/7092452/ee7d7ca2-dfa9-11e4-86a6-fdb5027b1218.PNG)

**Comment by jgranick** [comment]
This has been resolved, though in testing I found that HTML5 drawTiles does not appear to respect the parent transform, so it is not clipped, but it is not positioned where desired. We'll look into that, but as for negative coordinates, that's fixed now that we calculate the actual drawTiles bounds :smile:
