### ISSUE TITLE
CPP/NEKO: TextField discrepancies

### ISSUE THREAD

**Issue by larsiusprime** [openfl/openfl#589]
These are causing some regressions on flixel. Here's my best attempt to catalogue them all in an easily reproducible way.

See this gist:
https://gist.github.com/larsiusprime/558e081f0e651ed1319e

Legacy:
![text_legacy](https://cloud.githubusercontent.com/assets/739064/7093653/b008ad76-df80-11e4-8567-38c0f8771781.png)

Output:
Main.hx:29: width = 465
Main.hx:30: height = 43
Main.hx:31: textWidth = 460
Main.hx:32: textHeight = 38

----------

Next:
![text_next](https://cloud.githubusercontent.com/assets/739064/7093654/b2aeb624-df80-11e4-8672-fc086984391d.png)

Output:
Main.hx:29: width = 4
Main.hx:30: height = 100
Main.hx:31: textWidth = 0
Main.hx:32: textHeight = 0

**Comment by larsiusprime** [comment]
After latest openfl commit:

(legacy same)

next:

![text_next2](https://cloud.githubusercontent.com/assets/739064/7093741/72365c4a-df81-11e4-9d15-539c70311597.png)


Output:
Main.hx:29: width = 461.27734375
Main.hx:30: height = 100
Main.hx:31: textWidth = 457.27734375
Main.hx:32: textHeight = 28.44

**Comment by larsiusprime** [comment]
Results from Flash:

![text_flash](https://cloud.githubusercontent.com/assets/739064/7093809/0ab34942-df82-11e4-99e4-fbf5abbd5e28.png)

(doesn't get papyrus font loaded at all)

Output:
Main.hx:28: width = 438
Main.hx:29: height = 31
Main.hx:30: textWidth = 434
Main.hx:31: textHeight = 27

**Comment by jgranick** [comment]
It's not perfect, but it should be better now

https://github.com/openfl/openfl/commit/d5b2ebf441ea656a4cff8922fad06d3b0208e6ec

**Comment by larsiusprime** [comment]
Confirmed! Looks like it's working now :D

**Comment by larsiusprime** [comment]
Some quick thoughts:

Next:

width = 461.27734375
height = 100
textWidth = 457.27734375
textHeight = 28.44

Legacy:

width = 465
height = 43
textWidth = 460
textHeight = 38

Std.int(next) - legacy == 
width = -4
height = 57
textWidth = -3
textHeight = -10

I can't really account for the discrepancies in height, but the width values are very close to being off by exactly 4, which is the exact size of the gutter around all text fields specified in the Flash API (2 pixels on each side, top down left bottom)

**Comment by larsiusprime** [comment]
A few more notes just so you have them:

Difference map between legacy and next:

![text_diff](https://cloud.githubusercontent.com/assets/739064/7094016/973a5756-df83-11e4-9c93-bce908ce21b1.png)

And a more in-depth chart:

![text_diff_compare](https://cloud.githubusercontent.com/assets/739064/7094117/6d44f0f4-df84-11e4-9580-789545418ef5.png)

**Comment by jgranick** [comment]
interesting. Possible to check against Flash?

**Comment by larsiusprime** [comment]
Flash:

![text_flash](https://cloud.githubusercontent.com/assets/739064/7094207/fe262da4-df84-11e4-992b-282ec76d71a4.png)

Output:
Main.hx:32: width = 464
Main.hx:33: height = 42
Main.hx:34: textWidth = 460
Main.hx:35: textHeight = 38

**Comment by larsiusprime** [comment]
Next - Flash (int)
461 - 464 = -3
100 - 42 = 58
457 - 460 = -3
28 - 38 = -10

Legacy - Flash (int)
465 - 464 = -1
43 - 42 = 1
460 - 460 = 0
38 - 38 = 0

**Comment by larsiusprime** [comment]
Arguably this isn't fixed *quite* yet.

Here's the canonical page from Adobe on how everything should be:
http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/TextLineMetrics.html

![text-metrics](https://cloud.githubusercontent.com/assets/739064/7121376/c82e14e4-e1d9-11e4-85bc-5f9fe24b0e72.jpg)

**Comment by larsiusprime** [comment]
(This is now definitely fixed)
