### ISSUE TITLE
[OpenFL 3.0.1] TextField is taller than expected.

### ISSUE THREAD

**Issue by yuigoto** [openfl/openfl#591]
Been having some issues with TextFields in the latest builds, with most targets (save for Flash).

I'm running right now: Haxe 3.1.3, OpenFl 3.0.1 and Lime 2.3.1 on Win 8.1 Pro x64, if it helps. 

And the code I'm using here to test this issue is this one:
<code><pre>var Field:TextField = new TextField();
var Looks:TextFormat = new TextFormat( Assets.getFont( "fonts/arial.ttf" ).fontName, 64 );
Field.border = true;
Field.autoSize = TextFieldAutoSize.LEFT;
Field.antiAliasType = AntiAliasType.ADVANCED;
Field.multiline = false;
Field.selectable = false;
Field.textColor = 0xe0f7f5;
Field.text = "your text";
Field.type = TextFieldType.DYNAMIC;
Field.setTextFormat( Looks );
addChild( Field );</pre></code>

What happens is, if I'm targeting CPP/Windows or Neko, the TextField's dimensions render taller than expected, while with Flash the TextField's size renders normally.

I ran some tests with a few OTF (Dekar, Montserrat, Bebas Neue) and TTF (Arial, Verdana, Source Sans Pro) fonts to see if this issue was font-related, but it wasn't the problem.

I also tried not to use `multiline`, `selectable`, `type` or `autoSize`, but didn't work. As a plus, I also saw that, when targeting HTML5, if I use AutoSize.CENTER/RIGHT on the TextField, the text gets squashed and that it does nothing in CPP/Neko targets here. :confused:

This doesn't happen in legacy mode or in v2.2.8 (except in HTML5 target, where TextField height always renders taller than "normal").

**Comment by jgranick** [comment]
I think I fixed this earlier today :)

https://github.com/openfl/openfl/commit/d5b2ebf441ea656a4cff8922fad06d3b0208e6ec

This affects desktop GL targets when using autoSize left

**Comment by yuigoto** [comment]
Thanks for answering. :smile:

Just did a lazy file swap on "GLTextField.hx" :stuck_out_tongue_winking_eye:

And, now, it's rendering like this on Neko/CPP:
![textheight](https://cloud.githubusercontent.com/assets/346572/7100241/049f96e6-dfeb-11e4-846f-155ce5fe8930.png)

I'm a total noob, so I don't know how much I can help with this, sorry...:sweat_smile:...

**Comment by jgranick** [comment]
@yuigoto Oh, it also builds on this one :smile:

https://github.com/openfl/openfl/commit/3bccd2ce367728fc13283a9fa69eddbd61d56f2e

**Comment by yuigoto** [comment]
Oh sorry, didn't see that one! :persevere: :sweat_drops: Won't do a lazy swap again, I promise! :sweat_smile:

Works perfectly now! Thanks You! :+1:

**Comment by yuigoto** [comment]
Reopening this issue, to avoid creating too many topics :sweat_smile:

On OpenFl 3.0.3, while targeting HTML5/Windows Native/Neko TextFields some problems happened.

For example, using this code:

    var fields:TextField = new TextField();
    fields.defaultTextFormat = new TextFormat( "_sans", 12 );
    fields.selectable = false;
    fields.text = "On flash, this textField has 19px height.";
    fields.textColor = 0xef2020;
    fields.autoSize = TextFieldAutoSize.LEFT;
    fields.border = true;
    fields.type = TextFieldType.DYNAMIC;
    fields.antiAliasType = AntiAliasType.ADVANCED;
    fields.multiline = false;
    fields.selectable = false;
    addChild( fields );
    trace( fields.height );

On **flash**, the value from `trace` in the output is 19. While on **cpp/html5/neko** this value is 100.

On CPP/Neko targets, this TextField's border on screen has the proper size of 19px, but its height is considered as 100px, when logged into the console.

I don't see anything wrong with the code here. This started happening on 3.0.3, and it doesn't happen on CPP/Neko on legacy mode.

**Comment by T1mL3arn** [comment]
That happens because TextField does not makes internal update when you reading the some properties. Full update of TextField for canvas html5 target is going in the CanvasTextField.update() (it is a part of the rendering) method. If you need correct values, you can do
```Haxe
#if html5
CanvasTextField.update(textField);
#end
trace(textField.height);
```

**Comment by yuigoto** [comment]
Thanks for answering, sorry I took a little bit to see the answer.  :sweat_smile:

I tried doing what you wrote about and the code became like this:

```
var fields:TextField = new TextField();
fields.defaultTextFormat = new TextFormat( "_sans", 12 );
fields.selectable = false;
fields.text = "On flash, this textField has 19px height.";
fields.textColor = 0xef2020;
fields.autoSize = TextFieldAutoSize.LEFT;
fields.border = true;
fields.type = TextFieldType.DYNAMIC;
fields.antiAliasType = AntiAliasType.ADVANCED;
fields.multiline = false;
fields.selectable = false;
addChild( fields );

#if ( html5 )
    CanvasTextField.update( fields );
#end

trace( fields.height );
```

Expected value would be something close to 19px, but still outputs 100px :confused:

Will try to see if I can get it to work, somehow. :stuck_out_tongue_winking_eye:

But thanks! :grin:
