### ISSUE TITLE
Sound.hx:101: Error: Could not load “my music.ogg”

### ISSUE THREAD

**Issue by TommyX12** [openfl/openfl#592]
Hi,

I have been trying to play musics in my project, but sometimes randomly when I run my project (without re-compiling) this error happens and my file could not be played.

I am using OpenFL 3.0.0-beta3 legacy, and have tried every version of lime I had. In lime legacy 2.3.1 this problem seems to be more uncommon comparing to 2.1.2, but still happened a couple of times during test.

Thanks.

**Comment by jgranick** [comment]
I believe this has been resolved :smile:

**Comment by TommyX12** [comment]
Oh, I thought it's only solved for Lime 2 not legacy..

**Comment by jgranick** [comment]
Sorry about that, I didn't catch that this was on legacy. I've opened the issue again :smile:
