### ISSUE TITLE
Blurry Bitmap rendering on half-pixel positions with -Dnext

### ISSUE THREAD

**Issue by Gama11** [openfl/openfl#594]
```haxe
package;

import openfl.Assets;
import openfl.display.Bitmap;
import openfl.display.Sprite;

class Main extends Sprite
{
	public function new()
	{
		super();
		
		var bitmap = new Bitmap(Assets.getBitmapData("assets/test.png"));
		bitmap.y = 0.5;
		addChild(bitmap);
	}
}
```

This graphic:

![test](https://cloud.githubusercontent.com/assets/2620907/7106728/9db43b82-e14b-11e4-81b7-9b81fd9ea5a4.png)

isn't rendered correctly whenever the position is set to a half-pixel value:

![](http://i.imgur.com/8HriQGS.png)

Not sure if it's strictly limited to that, but anything else I tried (`0.501`, `0.499` etc) looked fine. This also seems to affect `y` way more than `x` (for this particular image anyway), although with `x = 0.5` it also isn't 100% correct:

![](http://i.imgur.com/jJV9mOM.png)

`-Dlegacy` doesn't have this issue.

Tested on neko and windows with Haxe 3.1.3, OpenFL 3.0.1 and Lime 2.3.1.

**Comment by sruloart** [comment]
That seems too specific, like a missing rounding somewhere...

**Comment by mrcdk** [comment]
I can't reproduce the error on latest git

**Comment by larsiusprime** [comment]
Let me try to reproduce as well.

**Comment by Gama11** [comment]
You could also just open the flixel debugger, that's where I discovered the issue originally:

![](http://i.imgur.com/BlwsX1j.png)

**Comment by larsiusprime** [comment]
Tested with neko/release and windows/release with latest stuff (openfl,lime,etc) from Git and latest Haxe RC (3.2 something). 

Can't reproduce, it just renders correctly.

**Comment by larsiusprime** [comment]
WAIT A MINUTE.

I wonder if this is related to this series of ephiphenomenal, hard-to-reproduce things I'm seeing in Defender's Quest (but only for my tester and not me):
https://github.com/larsiusprime/tdrpg-bugs/issues/271

**Comment by larsiusprime** [comment]
This seems to be cropping up in next for me on various flixel demos, especially anything that uses flixel-ui:

Legacy:
![blendmodes_legacy](https://cloud.githubusercontent.com/assets/739064/7143205/bbdf3a9a-e2a3-11e4-9c0e-d1b902e82e77.png)

Next:
![blendmodes_next](https://cloud.githubusercontent.com/assets/739064/7143214/c23acda0-e2a3-11e4-9ffc-15e20b7d7574.png)

Note how the text edges are smeared and that the buttons look weird.

**Comment by sruloart** [comment]
This reminds me of an old issue that I had with the old OpenFL-html5 (deprecated) target....found it: https://github.com/openfl/openfl-html5/issues/24...could be related...

**Comment by mrcdk** [comment]
@larsiusprime that error is not related to this

**Comment by larsiusprime** [comment]
@mrcdk: Haha, sorry that probably was a sort of misleading example :P Certain blend modes not being implemented is another issue entirely...

**Comment by larsiusprime** [comment]
@mrcdk:

I have a solid reproduction case now.

https://gist.github.com/larsiusprime/41b7907de0a0193841cb

You'll need this image asset:
![blurtest](https://cloud.githubusercontent.com/assets/739064/7325319/37705b44-ea83-11e4-9122-88af3dd75df8.png)

Reproduction:
1. Compile using "lime test neko -debug -Dnext"
2. Open the debugger with ` key
3. Look at what's in the bitmapLog

![blurry](https://cloud.githubusercontent.com/assets/739064/7325357/80cdfd50-ea83-11e4-86ad-df6ca65b6159.png)

I disabled the "drawBoundingBox()" call in BitmapLog.hx to get a clearer picture:
![blurrynooutline](https://cloud.githubusercontent.com/assets/739064/7325380/a8919b44-ea83-11e4-89d7-418e38b51df4.png)

Here's an upscale:
![blurrybig](https://cloud.githubusercontent.com/assets/739064/7325384/ab8ca082-ea83-11e4-902d-92b56cc766a9.png)

BitmapLog.hx has this in refresh canvas:
```
// find the window center
_point.x = (_canvas.width / 2) - (_curBitmap.width * zoom / 2);
_point.y = (_canvas.height / 2) - (_curBitmap.height * zoom / 2);
```

If I wrap those point sets in Std.int() it doesn't have the bluriness.

That said, this represents a regression from the previous API -- OpenFL should be able to render Bitmap objects on half-pixel locations without blurring, it should either floor, ceil, or round for rendering purposes, not sure what the desired behavior is but it should be easy to deduce from testing flash target.

**Comment by mrcdk** [comment]
can someone try if this commit fixes the problem? https://github.com/mrcdk/openfl/tree/hacky_fix_594 
I don't have it :confused:

**Comment by larsiusprime** [comment]
Comin right up

**Comment by larsiusprime** [comment]
Yup, that fixes it for me.

**Comment by larsiusprime** [comment]
@mrcdk: This doesn't seem like a permanent fix (I understand it was just a shot in the dark anyways) -- it causes some other issues (such as bitmaps meant to be smooth-scaled looking jaggy thanks to the nearest-neighbor filtering), etc.

I know you can't reproduce the bug, if you want to discuss it (on slack or here) I'm happy to be your test guinea pig if you have any ideas. I think the ultimate solution requires identifying when a displayObject is a bitmapdata, and if so making sure that it's coordinates (for rendering purposes only) are rounded before drawing.

**Comment by Rythe** [comment]
Let me predicate this by saying I once hoped, years ago, to never have to mire myself in matrix transformations and I don't know the codebase enough to know what I'm talking about.  

But decided to check up on things, then look into things, and maybe I found a suggestion that could lead to a way forward?

OpenGL talk (where the 0.375 hack shows up) says that polygon vertices and pixel image positions should be placed at whole pixels for predictable rendering whereas point vertices, line vertices, and bitmap positions should be placed at .5 pixel positions. (I don't know the difference between pixel images and bitmaps at this point <.<) via http://glprogramming.com/red/appendixg.html#name1 or https://msdn.microsoft.com/en-us/library/ms537007(VS.85).aspx

It doesn't look like there's an easy way for your SpriteBatch class to know the difference either, which leads me to three ideas.

1)Turn the texture smoothing back on and keep the 0.375 hack in place.

2)Pass a Flag through the SpriteBatch rendering pipeline for Sprites that need to be placed at whole pixel positions vs Sprites that don't.

3)Convert the BitmapData class to a Bitmap class at some point and set the pixelSnapping property before rendering.

**Comment by larsiusprime** [comment]
Ah, interesting!

1) This is a good guess; I already tried it myself and unfortunately it leads to other artifacts, as the 0.375 hack creates incorrect positioning for certain images; this makes sense as it was likely just a guess in the first place.

2) This might be a viable option. We already have the option of just doing an Std.is() on the passed in display object to get whether it's a Bitmap object or not, but we really, really, really want to avoid doing any kind of expensive calls like that in the renderer. So, if there's a way to pass in a "isBitmap" or other such flag early enough in the process that might be viable; the question is whether there's any way in the pipeline to deduce that information without having to call Std.is() at any point.

3) I don't think BitmapData can ever be directly rendered on the display list unless it's contained inside a Bitmap wrapper object already; that said flixel uses the drawTiles rendering path instead, and I should look into whether that uses "naked" BitmapData objects or not. As for pixelSnapping, on the native side the implementation is entirely up to us, so it's worth checking into whether we've a) actually implemented that method, and b) whether we implemented it correctly :P

**Comment by Rythe** [comment]
Well, if you haven't looked it up by now, the Tilesheet class is constructed with the naked BitmapData, and has a drawTiles method that asks for everything it probably needs to render, so I'm guessing it's likely that that rending path doesn't look at a Bitmap object proper at any point.

**Comment by mrcdk** [comment]
ok, can someone test the PR https://github.com/openfl/openfl/issues/642 and see if that fixes the problem?
