### ISSUE TITLE
Sounds do not loop in Flixel using Windows target + Dnext

### ISSUE THREAD

**Issue by larsiusprime** [openfl/openfl#595]
(Flixel uses legacy unless -Dnext is defined, in which case it uses next/standard)

Reproduction case:

- Compile Flixel's "mode" demo using "lime test windows -Dnext"

Expectations:

- Sound & music should continue playing throughout the entire game

Actuality:

- Music ceases playing after ~15 seconds or so.
- Sounds continue to fire (gun, expolosions, etc) as expected.

The most likely cause is that this listener's event is not fired (?):
https://github.com/HaxeFlixel/flixel/blob/dev/flixel/system/FlxSound.hx#L536

This might be related to this issue, though this person says they got it to work on pc target:
https://github.com/openfl/openfl/issues/410

**Comment by sruloart** [comment]
Maybe it's the file format fault...

**Comment by larsiusprime** [comment]
Nah, has nothing to do with that. It looks really clearly like no error is ever being fired.

Digging into it some more, it looks like looping hasn't been implemented yet on next. Here's what I found:

- The standard API setup we have waits for an event before looping the audio (replaying it)
- OpenAL has no mechanism for alerting the user when an audio file is finished playing

So there's a few options:

1. Manually keep track of where the audio playback position is in OpenAL's guts, fire an event when it gets to the end, OR
2. Use OpenAL's native looping functionality from the very start for looping sounds

Since the API needs audio SOUND_COMPLETE events anyways, 1. will have to be done in some form no matter what, but perhaps using 2. as well will create better auditory results.

**Comment by larsiusprime** [comment]
Okay, so reading some more on it, I think we'll have to handle looping separately from SOUND_COMPLETE notifications.

Fortunately OpenAL has an API for looping that doesn't require us to catch when a sound ends and then replay it manually, so I think "under the hood" that's how we should do it.

For SOUND_COMPLETE it looks like we'll have to do some kind of workaround, but that should probably be okay.

**Comment by larsiusprime** [comment]
Created a Flixel demo to test this.

https://github.com/HaxeFlixel/flixel-demos/pull/169

I added rudimentary looping to openfl-next on my own branch, still need to make sure pausing works correctly, then I'll issue a PR to openfl.

**Comment by larsiusprime** [comment]
I've got looping mostly sorted:
https://github.com/larsiusprime/openfl/tree/audio

I still don't have pause/resume working quite yet because it allocates a new openAL audio source every time the music asset resumes playing, rather than re-using the old one. I should have it working soon.

**Comment by larsiusprime** [comment]
PR's issued:

**Comment by larsiusprime** [comment]
Sounds good to me. Can't tell if there's gapping in the loop or not, if there is that's a separate issue.
