### ISSUE TITLE
Windows: Input text does not work

### ISSUE THREAD

**Issue by larsiusprime** [openfl/openfl#598]
Reproduction case:

- Compile flixel's ["mode" demo](https://github.com/HaxeFlixel/flixel-demos/tree/dev/Platformers/Mode) with "lime test windows -debug -Dnext"
- Press "~" or "\" to bring up the debug console
- On the bottom of the screen click on the "console" tray

Expectations:

- You should be able to input a command

Results:

- You can't. It works on legacy but not on next.

**Comment by larsiusprime** [comment]
Looks like @MattTuttle is on the job!
https://github.com/openfl/lime/compare/text-input

**Comment by MattTuttle** [comment]
I still don't like the way Flash is handled for text input. It requires a hidden TextField that needs focus for it to work. Any ideas?

**Comment by larsiusprime** [comment]
Wait so flash target handles input text by... creating another input text?

**Comment by MattTuttle** [comment]
As far as I could tell there isn't an event that can be used for text input like native/html5 has. The event `TextEvent.TEXT_INPUT` only seems to work on TextField and not on the stage...

**Comment by larsiusprime** [comment]
You can't drive it directly off of low-level keyboard events?

**Comment by jgranick** [comment]
If we have to, we could listen to Flash KeyboardEvent and use the charCode. This isn't as good/accurate as unicode input, but who knows, perhaps it's more accurate than we think

**Comment by MSGhero** [comment]
Would this allow alt codes to be typed in? I'm not sure if flash's tfs handle them, but you'd have to manually do them I would think.

**Comment by Tiago-Ling** [comment]
Might be related to this discussion:
https://github.com/HaxeFlixel/flixel-ui/issues/70#issuecomment-99484782

**Comment by MSGhero** [comment]
Just tried it, and it works. Although the demo itself was buggy, the console worked on -Dnext.

**Comment by jgranick** [comment]
:smile:
