### ISSUE TITLE
DisplayObjectContainer.contains() should be recursive

### ISSUE THREAD

**Issue by MSGhero** [openfl/openfl#600]
https://github.com/openfl/openfl/blob/master/openfl/display/DisplayObjectContainer.hx#L292

Flash's is recursive, and the description says grandchildren, etc should be included.

**Comment by MSGhero** [comment]
I can work on this now, but is there a way to check if a DisplayObject is a DisplayObjectContainer besides Std.is? Like is there some private variable somewhere I can look at?

**Comment by jgranick** [comment]
Perhaps DisplayObject could have a private @:noCompletion `__contains` method that returns true or false. Default is to `return (child == this);`. `DisplayObjectContainer` overrides and loops through all children, breaking the loop and returning if any children return true, otherwise returns false

**Comment by jgranick** [comment]
Actually, perhaps it would be faster to iterate through the `parent` property of the target `child` object, to see if any `parent` is equal to the `DisplayObjectContainer`

**Comment by MSGhero** [comment]
The parent route is what I did and is probably faster than traversing children.
