### ISSUE TITLE
Error while compiling for neko/html5 with OpenFL 3.0.1

### ISSUE THREAD

**Issue by sebastiencarceles** [openfl/openfl#601]
Hello,
When I target html5 or neko with OpenFL 3.0.1, I have the following error:

> /Users/sebastien/haxelib/openfl/3,0,1/openfl/display/BitmapData.hx:333: characters 11-27 : Unknown identifier : ImageChannel
> /Users/sebastien/haxelib/openfl/3,0,1/openfl/display/BitmapData.hx:334: characters 11-29 : Unknown identifier : ImageChannel
> /Users/sebastien/haxelib/openfl/3,0,1/openfl/display/BitmapData.hx:335: characters 11-28 : Unknown identifier : ImageChannel
> /Users/sebastien/haxelib/openfl/3,0,1/openfl/display/BitmapData.hx:336: characters 11-29 : Unknown identifier : ImageChannel
> /Users/sebastien/haxelib/openfl/3,0,1/openfl/display/BitmapData.hx:343: characters 11-27 : Unknown identifier : ImageChannel
> /Users/sebastien/haxelib/openfl/3,0,1/openfl/display/BitmapData.hx:344: characters 11-29 : Unknown identifier : ImageChannel
> /Users/sebastien/haxelib/openfl/3,0,1/openfl/display/BitmapData.hx:345: characters 11-28 : Unknown identifier : ImageChannel
> /Users/sebastien/haxelib/openfl/3,0,1/openfl/display/BitmapData.hx:346: characters 11-29 : Unknown identifier : ImageChannel

Please note that I'm using lime 2.3.1. Any idea?
Thanks

**Comment by jgranick** [comment]
This might be fixed in Lime 2.3.2 and OpenFL 3.0.2, have you given it a try?

**Comment by sebastiencarceles** [comment]
I upgraded everything:
> pc28:tikids sebastien$ haxelib list
> actuate: [1.8.4]
> box2d: [1.2.3]
> ganalytics: [0.0.3]
> hxcpp: [3.2.81]
> layout: [1.2.0]
> lime-samples: [2.3.0]
> lime: 2.2.0 2.3.1 [2.3.3]
> openfl-samples: [2.2.2]
> openfl-share: [1.2.0]
> openfl: 2.2.5 3.0.1 [3.0.3]
> spritesheet: [1.2.0]
> svg: [1.0.8]
> swf: 1.8.4 [1.8.6]

And now html5 and neko targets compile well.

Now I have another issue with neko, at runtime:
> pc28:tikids sebastien$ openfl test neko -Dtoddlerstairs
> Called from ? line 1
> Called from ApplicationMain.hx line 122
> Called from ApplicationMain.hx line 55
> Called from lime/app/Application.hx line 158
> Called from lime/_backend/native/NativeApplication.hx line 102
> Called from a C function
> Called from lime/app/Event.hx line 59
> Called from lime/app/Application.hx line 519
> Called from openfl/display/Stage.hx line 884
> Called from openfl/display/DisplayObjectContainer.hx line 641
> Called from openfl/display/DisplayObjectContainer.hx line 641
> Called from openfl/display/DisplayObjectContainer.hx line 641
> Called from a C function
> Called from openfl/display/DisplayObject.hx line 986
> Called from a C function
> Called from openfl/events/EventDispatcher.hx line 266
> Called from com/tikids/toddlerstairs/ToddlerStairsActivity.hx line 76
> Called from com/tikids/toddlerstairs/game/Fox.hx line 85
> Called from a C function
> Called from com/tikids/main/game/Piece.hx line 60
> Uncaught exception - Invalid operation (-)

Here is the code:
```haxe
	public function animate() {
 		var time = Lib.getTimer();
 		var delta = time - lastTime;
 		update(delta);
 		lastTime = time;
	}
```
Where lastTime is an Int. Any idea?

Thanks for your help

**Comment by jgranick** [comment]
Make sure you set `lastTime` to 0 in your constructor, or somewhere before this function is called. On Neko, `lastTime`, if not initialized, will be `null`, so `time - null` does not make sense, and is an "Invalid operation"

**Comment by jgranick** [comment]
This could also work, I think

```haxe
#if neko
if (lastTime == null) lastTime = time;
#end
```

**Comment by sebastiencarceles** [comment]
OK I initialized lastTime to 0. It works well, thanks for your help!

Le ven. 24 avr. 2015 à 18:38, Joshua Granick <notifications@github.com> a
écrit :
