### ISSUE TITLE
systools OpenDialog makes screen black [ONLY Mac]

### ISSUE THREAD

**Issue by yupswing** [openfl/openfl#602]
When OpenFileDialog (the openfolder and savefile are all right) gives the control back to the OpenFL app the window become black.
(in a haxe app without openfl everything works fine)

The app still retain Listeners and console output but the "stage" get "detached" (if there is an opengl view the program crashes).

An example here https://dl.dropboxusercontent.com/u/683344/akifox/git/opendialog-openfl-test-mac.zip

(I've submitted the bug to the systools issue tracker as well, but the project is quite abandoned)

**Comment by jgranick** [comment]
The Lime library supports file dialogs, if systools is incompatible, I would recommend `lime.ui.FileDialog` instead :smile:
