### ISSUE TITLE
BitmapData.fillRect before BitmapData.draw() causes inconsistent visuals

### ISSUE THREAD

**Issue by larsiusprime** [openfl/openfl#608]
Flash (Correct) :

![fillrectflash](https://cloud.githubusercontent.com/assets/739064/7211371/c529cc0e-e51f-11e4-96ea-06461fdf1090.png)

Neko+Next (Incorrect) :

![fillrectneko](https://cloud.githubusercontent.com/assets/739064/7211375/cfc17ef0-e51f-11e4-826a-2264f88cd314.png)

Code:
```Haxe
public function new () {
        
        super ();
        
        
        var data = new BitmapData(100, 100, true);
        data.fillRect(new Rectangle(0, 0, 50, 50), 0xFFFF0000);
        data.fillRect(new Rectangle(0, 50, 50, 50), 0xFF0000FF);
        data.fillRect(new Rectangle(50, 0, 50, 50), 0xFF00FF00);
        data.fillRect(new Rectangle(50, 50, 50, 50), 0xFFFFFF00);
        
        var thing = new BitmapData(50, 50, true);
        thing.fillRect(new Rectangle(0, 0, 50, 50), 0xFF000000);
        thing.fillRect(new Rectangle(2, 2, 46, 46), 0x00000000);
        thing.fillRect(new Rectangle(10, 10, 30, 30), 0xFFFFFFFF);
        
        var bitmap = new Bitmap (data);
        addChild (bitmap);
        
        bitmap.x = (stage.stageWidth - bitmap.width) / 2;
        bitmap.y = (stage.stageHeight - bitmap.height) / 2;
        
        var matrix:Matrix = new Matrix();
        matrix.translate(25, 25);
        
        var data2 = new BitmapData(100, 100, true);
        data2.draw(data);
        data2.draw(thing,matrix);
        
        data2.fillRect(data2.rect, 0xFF808080);
        data2.draw(thing, matrix);
        
        var bitmap2 = new Bitmap (data2);
        addChild(bitmap2);
        
        bitmap2.x = bitmap.x + bitmap.width + 10;
        bitmap2.y = bitmap.y;
    }
```

**Comment by larsiusprime** [comment]
Any ideas @mrcdk ?

**Comment by larsiusprime** [comment]
I have done a deep dive into the fillRect() logic, all the way down to the c++ code, and verify it is correct. If you remove the last draw() command, both targets draw the grey square correctly. It is only after you draw ON TOP OF THAT, that neko will revert to the colored background.

My guess is a pointer gets unstuck somewhere, or something, in any case it is probably in BitmapData.draw(), perhaps it is not recognizing the state created by the fillRect() command somehow.

**Comment by jgranick** [comment]
My guess that this is a case where the .draw does not draw over the entire BitmapData. Perhaps (if it is not done already), the BitmapData itself needs to be added to the render operation, as a layer underneath the other content, so that any existing pixels in the BitmapData can blend with what's drawn above. I suppose this depends on the `mergeAlpha` property

**Comment by larsiusprime** [comment]
mergeAlpha is a copyPixels() parameter, not a draw() parameter, IIRC. Or am I misunderstanding?

**Comment by jgranick** [comment]
Hmm, perhaps I am remembering wrong, so it always merges, then

**Comment by larsiusprime** [comment]
Yeah, draw() just draws straight on top and is always aware of the background.

**Comment by jgranick** [comment]
Oh, hah

https://github.com/openfl/openfl/blob/master/openfl/display/BitmapData.hx#L576

`true` fixes it

**Comment by larsiusprime** [comment]
Heh :) Great job!

**Comment by larsiusprime** [comment]
https://github.com/openfl/openfl/pull/609
