### ISSUE TITLE
filter does not working.

### ISSUE THREAD

**Issue by musou1500** [openfl/openfl#611]
I try to apply DropshadowFilter on Git and and 3.0.2 version.
But filter seems does not works.
Here is code.
```
var canvas:Sprite = new Sprite();
canvas.graphics.beginFill(0xED1A3D);
canvas.graphics.drawRect(0, 0, 100, 100);
canvas.graphics.endFill();
addChild(canvas);
canvas.filters = [new DropShadowFilter(2, 45, 0, .3, 5, 5)];
```

**Comment by vroad** [comment]
It does not seem to be implemented... It only works on Flash for now I think.

**Comment by musou1500** [comment]
Oh... I found '"Available on all platforms" in DropShadowFilter api page....
Thank you.

**Comment by musou1500** [comment]
ほしいもの

**Comment by cforcloud** [comment]
This works in Neko too. But its not working in Android. Is is wrong in the api page
