### ISSUE TITLE
Crashing on Android

### ISSUE THREAD

**Issue by Pinpickle** [openfl/openfl#613]
Just trying to run a game on Android to see how it would run but I can't seem to get it to run without crashing. With `-Dlegacy` I just get a blank screen.

I've tried in the 3.0.2 release with Lime 2.3.2 and with the master branch of OpenFL and Lime. I get no useful traces when the app crashes, the app just crashes. I ran `adb logcat` and I think I found the stack trace of the crash:

```
W/ActivityManager(  811): Force removing ActivityRecord{1618c1 u0 com.example.app/.MainActivity t169}: app died, no saved state
W/WindowManager(  811): Failed looking up window
W/WindowManager(  811): java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@3e2ad716 does not exist
W/WindowManager(  811): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8510)
W/WindowManager(  811): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8501)
W/WindowManager(  811): 	at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1111)
W/WindowManager(  811): 	at android.os.BinderProxy.sendDeathNotice(Binder.java:551)
I/WindowState(  811): WIN DEATH: null
```

**Update** I forgot to turn the `-debug` flag on first, silly me. It runs successfully when I do that, which makes it very difficult to find out what's going on. I do have this trace, however:

````
--------- beginning of crash
F/libc    ( 6067): Fatal signal 7 (SIGBUS), code 1, fault addr 0xa146e519 in tid 6101 (SDLThread)
F/libc    ( 6345): Fatal signal 7 (SIGBUS), code 1, fault addr 0xa146e459 in tid 6366 (SDLThread)
F/libc    ( 6383): Fatal signal 7 (SIGBUS), code 1, fault addr 0xa0b6da79 in tid 6403 (SDLThread)
F/libc    ( 6421): Fatal signal 7 (SIGBUS), code 1, fault addr 0xa146c939 in tid 6442 (SDLThread)
F/libc    ( 8002): Fatal signal 7 (SIGBUS), code 1, fault addr 0xa148ce49 in tid 8025 (SDLThread)
F/libc    (10689): Fatal signal 7 (SIGBUS), code 1, fault addr 0xa148bf51 in tid 10733 (SDLThread)
F/libc    (11635): Fatal signal 6 (SIGABRT), code -6 in tid 11668 (SDLThread)
````
The game I'm trying to compile is https://github.com/Pinpickle/ld32

**Comment by jeichelbaum** [comment]
hey I think our issues are related. I checked if you were trying to call TextField.text = "whatever"; at some point and you do. That crashes my app at least.
https://github.com/openfl/openfl/issues/650

**Comment by Pinpickle** [comment]
Thanks for the pointer @jeichelbaum. I commented out the text bits and that stopped the crashing. Closing this issue as your #650 is more specific and has made more progress - thanks!
