### ISSUE TITLE
BitmapData.draw() before BitmapData.fillRect() causes inconsistent visuals

### ISSUE THREAD

**Issue by larsiusprime** [openfl/openfl#616]
BitmapData.draw() still has lingering issues with drawSelf.

Some quick screengrab crops-

Correct (flash):
![flash](https://cloud.githubusercontent.com/assets/739064/7303198/7351aae8-e9b4-11e4-9a80-bf2124098f46.png)

Next (drawSelf = false)
![next_drawself_false](https://cloud.githubusercontent.com/assets/739064/7303199/73532d96-e9b4-11e4-8633-fa1888bb396f.png)

Next (drawSelf = true)
![next_drawself_true](https://cloud.githubusercontent.com/assets/739064/7303200/7353f618-e9b4-11e4-83f6-6f39932913ca.png)

(Do not next uses Georgia font and Flash uses Times New Roman, that's a separate thing)

Code to reproduce:

```
	private var _matrix:Matrix;
	
	public function new () {
		
		_matrix = new Matrix();
		
		super ();
		textTest();
	}
	
	private function textTest():Void
	{
		var text:TextField = new TextField();
		addChild(text);
		
		text.textColor = 0xFFFF0000;
		text.text = "Hello, World!";
		
		text.x = 5;
		text.y = 5;
		
		var data = new BitmapData(Std.int(text.textWidth+4), Std.int(text.textHeight+4), true);
		var r = new Rectangle(0, 0, data.width, data.height);
		
		// WORKS if drawSelf = true  (text on yellow bkg)
		//!WORKS if drawSelf = false (text on !exist bkg)
		data.draw(text);
		data.fillRect(r, 0xFFFFFF00);
		data.draw(text);
		
		var b = new Bitmap(data);
		b.x = text.x + text.textWidth + 10;
		b.y = text.y;
		addChild(b);
		
		var data2 = new BitmapData(data.width, data.height, true);
		var r2 = new Rectangle(0, 0, data2.width, data2.height);
		
		// WORKS if drawSelf = false (text on yellow bkg)
		// WORKS if drawSelf = true  (text on yellow bkg)
		data2.fillRect(r, 0xFFFFFF00);
		data2.draw(text);
		
		var b2 = new Bitmap(data2);
		b2.x = b.x + b.width + 10;
		b2.y = b.y;
		addChild(b2);
		
		var data3 = new BitmapData(data.width, data.height, true);
		var r3 = new Rectangle(0, 0, data3.width, data3.height);
		
		// WORKS if drawSelf = false (yellow text outlined blue)
		//!WORKS if drawSelf = true  (yellow text)
		drawTextWithBorder(text, data3, 0xFFFFFF00, 0xFF0000FF, 1);
		
		var b3 = new Bitmap(data3);
		b3.x = b2.x + b2.width + 10;
		b3.y = b2.y;
		addChild(b3);
	}
	
	private function drawTextWithBorder(txt:TextField, bmp:BitmapData, color:Int, outlineColor:Int, border:Int)
	{
		drawOutline(txt, bmp, border, outlineColor);
		var oldcolor = txt.textColor;
		txt.textColor = color;
		bmp.draw(txt);
		txt.textColor = oldcolor;
	}
	
	private function drawOutline(txt:TextField, bmp:BitmapData, offset:Int, color:Int)
	{
		_matrix.identity();
		
		var oldcolor = txt.defaultTextFormat.color;
		
		txt.textColor = color;
		
		copyTextWithOffset( -offset, -offset, txt, bmp);
		copyTextWithOffset( offset, 0, txt, bmp);
		copyTextWithOffset( offset, 0, txt, bmp);
		copyTextWithOffset( 0, offset, txt, bmp);
		copyTextWithOffset( 0, offset, txt, bmp);
		copyTextWithOffset( -offset, 0, txt, bmp);
		copyTextWithOffset( -offset, 0, txt, bmp);
		copyTextWithOffset( 0, -offset, txt, bmp);
		
		_matrix.translate(offset, 0);
		
		txt.textColor = oldcolor;
	}
	
	private function copyTextWithOffset(x:Float, y:Float, txt:TextField, bmp:BitmapData)
	{
		_matrix.translate(x, y);
		bmp.draw(txt, _matrix);
	}
```

**Comment by larsiusprime** [comment]
Argh, spoke too soon. I had
```var drawSelf = true``` 
Set to false in BitmapData. That said, I know there's another issue in play here, let me find it.

**Comment by larsiusprime** [comment]
Yup, I knew it. Text outlines as rendered in flixel don't work if we set 
```var drawSelf = true```
in BitmapData.draw().

Neko-Next (drawSelf = false)
![next_drawself_false](https://cloud.githubusercontent.com/assets/739064/7302703/ccd7b444-e9b0-11e4-9009-93a3db22cece.png)

Neko-Next (drawSelf = true)
![next_drawself_true](https://cloud.githubusercontent.com/assets/739064/7302714/ed2828be-e9b0-11e4-851d-202225e04374.png)

Code:
```
private function textTest():Void
	{
		var text:TextField = new TextField();
		addChild(text);
		
		text.textColor = 0xFFFF0000;
		text.text = "Hello, World!";
		
		text.x = 5;
		text.y = 5;
		
		var data = new BitmapData(Std.int(text.textWidth+4), Std.int(text.textHeight+4), true);
		var r = new Rectangle(0, 0, data.width, data.height);
		
		data.draw(text);
		data.fillRect(r, 0xFFFFFF00);
		data.draw(text);
		
		var b = new Bitmap(data);
		b.x = text.x + text.textWidth + 10;
		b.y = text.y;
		addChild(b);
		
		var data2 = new BitmapData(data.width, data.height, true);
		var r2 = new Rectangle(0, 0, data2.width, data2.height);
		
		data2.fillRect(r, 0xFFFFFF00);
		data2.draw(text);
		
		var b2 = new Bitmap(data2);
		b2.x = b.x + b.width + 10;
		b2.y = b.y;
		addChild(b2);
		
		var data3 = new BitmapData(data.width, data.height, true);
		var r3 = new Rectangle(0, 0, data3.width, data3.height);
		
		drawTextWithBorder(text, data3, 0xFFFFFF00, 0xFF0000FF, 1);
		
		var b3 = new Bitmap(data3);
		b3.x = b.x + b.width + 10;
		b3.y = b.y;
		addChild(b3);
	}
	
	private function drawTextWithBorder(txt:TextField, bmp:BitmapData, color:Int, outlineColor:Int, border:Int)
	{
		drawOutline(txt, bmp, border, outlineColor);
		var oldcolor = txt.textColor;
		txt.textColor = color;
		bmp.draw(txt);
		txt.textColor = oldcolor;
	}
	
	private function drawOutline(txt:TextField, bmp:BitmapData, offset:Int, color:Int)
	{
		_matrix.identity();
		
		var oldcolor = txt.defaultTextFormat.color;
		
		txt.textColor = color;
		
		copyTextWithOffset( -offset, -offset, txt, bmp);
		copyTextWithOffset( offset, 0, txt, bmp);
		copyTextWithOffset( offset, 0, txt, bmp);
		copyTextWithOffset( 0, offset, txt, bmp);
		copyTextWithOffset( 0, offset, txt, bmp);
		copyTextWithOffset( -offset, 0, txt, bmp);
		copyTextWithOffset( -offset, 0, txt, bmp);
		copyTextWithOffset( 0, -offset, txt, bmp);
		
		_matrix.translate(offset, 0);
		
		txt.textColor = oldcolor;
	}
	
	private function copyTextWithOffset(x:Float, y:Float, txt:TextField, bmp:BitmapData)
	{
		_matrix.translate(x, y);
		bmp.draw(txt, _matrix);
	}
```

**Comment by larsiusprime** [comment]
Assuming that drawSelf should be set to true by default, we can look at the issue like this:

When you do multiple bitmapData.draw(textField)'s to the same canvas, only the last draw()'s results appear, everything before it is erased.

Let me test whether this is a general issue or related solely to text fields...

**Comment by larsiusprime** [comment]
Kay, simpler reproduction case!

Correct (flash):
![flash_2text](https://cloud.githubusercontent.com/assets/739064/7303441/4aec9aa2-e9b6-11e4-820f-e79dd2d55157.png)

Incorrect (next, drawSelf=true):
![next_2text](https://cloud.githubusercontent.com/assets/739064/7303440/4aec5cf4-e9b6-11e4-9261-8a52cd8b50f3.png)

```
private var _matrix:Matrix;
	
	public function new () {
		
		_matrix = new Matrix();
		
		super ();
		textTest();
	}
	
	private function textTest():Void
	{
		var text:TextField = new TextField();
		addChild(text);
		
		text.textColor = 0xFFFF0000;
		text.text = "Hello, World!";
		
		text.x = 5;
		text.y = 5;
		
		var data = new BitmapData(Std.int(text.textWidth+4), Std.int(text.textHeight+4), true);
		var r = new Rectangle(0, 0, data.width, data.height);
		
		data.draw(text, _matrix);
		_matrix.translate(2, 2);
		data.draw(text, _matrix);
		
		var b = new Bitmap(data);
		b.x = text.x + text.textWidth + 10;
		b.y = text.y;
		
		addChild(b);
	}
```

**Comment by larsiusprime** [comment]
Doesn't seem like it's limited to text, here's calling draw() using a bitmapdata as the source:

Flash (correct):
![flash_box](https://cloud.githubusercontent.com/assets/739064/7303480/a056d2b4-e9b6-11e4-8c11-828675deed96.png)

Next+drawSelf=true (incorrect):
![next_box](https://cloud.githubusercontent.com/assets/739064/7303481/a05ae3c2-e9b6-11e4-979d-bb5ecb6ea08f.png)

```
var b:BitmapData = new BitmapData(10, 10, false, 0xFF0000FF);

data.draw(b, _matrix);
_matrix.translate(2, 2);
data.draw(b, _matrix);
```

**Comment by larsiusprime** [comment]
I'm leaning towards the case that drawSelf should = false by default now, and we correct the outlier there.

Anyways, look at this:

Correct (flash):
![flash](https://cloud.githubusercontent.com/assets/739064/7303198/7351aae8-e9b4-11e4-9a80-bf2124098f46.png)

Next (drawSelf = false)
![next_drawself_false](https://cloud.githubusercontent.com/assets/739064/7303199/73532d96-e9b4-11e4-8633-fa1888bb396f.png)

Notice here how the erroneous text is not only missing a background, but appears **bold**? That's not a text formatting issue. It's the result of the text being drawn twice on top of itself with nothing in between.

I just tested, and if you remove the fillRect() call, you get the same results. 

So draw(text)+fillRect()+draw(text) is the same as just draw(text)+draw(text).

So this suggests to me maybe fillRect isn't operating on the same set of pixels, or some buffer doesn't get updated. Or something.

**Comment by jgranick** [comment]
Just to test, what if there was something like:

```haxe
private static var drawing = 0;

...

if (drawing == 0) drawSelf = true;
drawing++;

...

drawing--;
```

So if it is the top-level of the draw, it draws self, otherwise (for recursive BitmapData beneath) it does not draw self

**Comment by larsiusprime** [comment]
where exactly would I put drawing--? I tried that just now, but also with a trace out of drawing's value, and it's always 0. (I put the decrement just before the "default: //TODO")

**Comment by jgranick** [comment]
maybe we should do `drawing--` and `if (drawing == 0) __spritebatch = null;`

**Comment by jgranick** [comment]
at the end there

**Comment by larsiusprime** [comment]
drawing's always equal to 0. I guess we could also perhaps add a drawing increment to fillRect() and other "draw-like" calls to try this method?

**Comment by larsiusprime** [comment]
actually....

setting __spriteBatch = null after a fillRect call seems to do the trick. Not sure what crazy other effects that might have tho!

**Comment by mrcdk** [comment]
I've already solved it on https://github.com/mrcdk/openfl/tree/cacheAsBitmap2

**Comment by larsiusprime** [comment]
@mrcdk: ah, cool! What was the solution?

**Comment by mrcdk** [comment]
it was using the uploaded texture and not the modified texture

**Comment by larsiusprime** [comment]
is cacheAsBitmap2 branch stable?

**Comment by mrcdk** [comment]
if you don't use `cacheAsBitmap` then... yes :sweat_smile:

**Comment by larsiusprime** [comment]
Ah, cool. Is there a simple fix we can cherry-pick in to the main branch to fix this issue without pulling all of cacheAsBitmap2 in?

**Comment by larsiusprime** [comment]
This is confirmed as fixed in @mrcdk's branch:

![cacheasbmp2](https://cloud.githubusercontent.com/assets/739064/7304613/2e0bdfda-e9be-11e4-8c60-4234b2f75b57.png)

When that gets merged in or cherry picked, this can be closed.
