### ISSUE TITLE
Class not found : lime.graphics.ImageChannel

### ISSUE THREAD

**Issue by zauberparacelsus** [openfl/openfl#619]
Today I updated all my haxelibs so that I could try to get started on a game project, but just like last time, I find myself unable to build/test anything right away due to something missing.

In this case, the lime.graphics.ImageChannel class:

```
[zauber@manjaro hxParacosm]$ lime test cpp
/home/zauber/haxelib/openfl/3,0,3/openfl/display/BitmapData.hx:8: characters 7-33 : Class not found : lime.graphics.ImageChannel
```

Currently using an up-to-date Manjaro Linux installation, and running with OpenFL 3.0.3

**Comment by zauberparacelsus** [comment]
Actually, disregard my post.  I think I posted in the wrong area.

**Comment by zauberparacelsus** [comment]
Okay, so here's my (apparent) problem.  I am using Lime 2.1.2.  When I try to update it, it keeps redownloading Lime 2.3.3, and then haxelib reports "Current version is now 1.0.0".  When I try to run the set version command, it acts like 2.3.3 has not yet been downloaded even though it has already been downloaded several times.  I go into haxelib's repository path and find that 2.1.2 is there.

**Comment by zauberparacelsus** [comment]
Okay, close this issue.  The underlying problem (which I found after wiping haxe from my system and doing a clean reinstall) is that the current version of lime is silently failing to install.

**Comment by larsiusprime** [comment]
There are some known issues with haxelib... perhaps that has something to do with it.

**Comment by zauberparacelsus** [comment]
Oh, I found the *real* underlying issue.  Whoever is in charge of the Haxe package on AUR decided to use an upstream bleeding-edge version (3.2.0).  Installing the Haxe3-bin package (3.1.3) fixes the problem.

**Comment by MSGhero** [comment]
Yeah I tried installing (for the first time) haxe/lime/openfl on my tablet, and installing lime came back with an "unknown lib version 1.0.0" issue (openfl and other libs worked). Upgrading lime on my laptop went fine, though.

**Comment by zauberparacelsus** [comment]
@MSGhero Make sure you're not using Haxe 3.20rc2, as that is what was causing the "unknown lib version 1.0.0" issue for me.

**Comment by jgranick** [comment]
The real issue is that haxelib is broken, I think that it has been fixed in a later haxelib release, but `haxelib selfupdate` is also broken.

If you use Haxe 3.2 RC2 (which I've been using, it's great) do something like this:

```bash
cd /usr/lib/haxe
cp haxelib haxelib2
haxelib2 selfupdate
rm haxelib2
```

Otherwise it tries to replace itself and gets an access violation
