### ISSUE TITLE
"openfl setup linux" fails on fresh install

### ISSUE THREAD

**Issue by ArtBIT** [openfl/openfl#627]
$ openfl setup linux
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ia32-libs-multiarch
Called from ? line 1
Called from CommandLineTools.hx line 1359
Called from CommandLineTools.hx line 25
Called from a C function
Called from CommandLineTools.hx line 94
Called from CommandLineTools.hx line 1374
Called from utils/PlatformSetup.hx line 406
Called from utils/PlatformSetup.hx line 442
Called from utils/PlatformSetup.hx line 1769
Called from a C function
Called from lime/tools/helpers/ProcessHelper.hx line 172
Called from lime/tools/helpers/ProcessHelper.hx line 242
Uncaught exception - Error running: sudo apt-get install ia32-libs-multiarch gcc-multilib g++-multilib []

$ uname -a
Linux ubuntovnik 3.13.0-49-generic #83-Ubuntu SMP Fri Apr 10 20:11:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ haxe -version
3.1.3

$ openfl
OpenFL Command-Line Tools (3.0.3-LNyxj2)

**Comment by ibilon** [comment]
If you redo the command manually `sudo apt-get install ia32-libs-multiarch gcc-multilib g++-multilib` what happens?

**Comment by ArtBIT** [comment]
$ sudo apt-get install ia32-libs-multiarch gcc-multilib g++-multilib
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ia32-libs-multiarch

This meta package was removed in 13.10
I am running 14.04

**Comment by ibilon** [comment]
The script should probably be updated,
in the meantime it's not really a problem for you, this command is just to make sure you have all the packages needed to build linux app, rerun the command without the missing package `sudo apt-get install gcc-multilib g++-multilib` and you'll be good to go.

**Comment by ArtBIT** [comment]
Ok, awesome. Thanks Valentin.
