### ISSUE TITLE
segmentation fault on linux build

### ISSUE THREAD

**Issue by LaurentTreguier** [openfl/openfl#630]
I tried using Openfl samples to test it. I'm using Archlinux 64bit, haxe 3.2.0-rc2, haxelib 3.2.0-rc3 and OpenFL 3.0.3. I simply build one of the samples (DisplayingABitmap and NyanCat) with `openfl build linux`, and it then compiles the target as C++ for linux64 correctly. But after that, when I try to launch the executable, I only get :
`[1]    14308 segmentation fault (core dumped) ./Export/linux64/cpp/bin/DisplayingABitmap`

I tried using GDB and I got this :

```
(gdb) run
Starting program: /home/laurent/Hubic/haxe/openfl/DisplayingABitmap/Export/linux64/cpp/bin/DisplayingABitmap 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff55e9700 (LWP 19021)]
[New Thread 0x7ffff5dea700 (LWP 19020)]
[New Thread 0x7ffff65eb700 (LWP 19019)]
[New Thread 0x7ffff6dec700 (LWP 19018)]
[New Thread 0x7fffd7ffe700 (LWP 19025)]
[New Thread 0x7ffff419b700 (LWP 19024)]
[New Thread 0x7fffe4d41700 (LWP 19023)]

Program received signal SIGSEGV, Segmentation fault.
0x00007fffffffcd10 in ?? ()
```

It seems there is a problem when using `libthread_db`. Is it related to haxe 3.2.0, or is it a real bug in OpenFL ? I think it would be hard to introduce such a bug in an OpenFL release...

**Comment by ibilon** [comment]
Could you retry with `openfl build linux -debug`?
Maybe we'll get a bit more information as to where did the segfault occurred.

**Comment by LaurentTreguier** [comment]
The output is the same. I already used `-debug` to see if I could get more info with GDB, but nothing seems to change.

**Comment by larsiusprime** [comment]
Have you tried using crashdumper? (
https://github.com/larsiusprime/crashdumper)

Also, what version of lime are you using?

On Mon, Apr 27, 2015 at 10:04 AM, LaurentTreguier <notifications@github.com>
wrote:

> The output is the same. I already used -debug to see if I could get more
> info with GDB, but nothing seems to change.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openfl/openfl/issues/630#issuecomment-96693516>.
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by LaurentTreguier** [comment]
Lime is version 2.3.3 ; I'm struggling with crashdumper : it seems that in order to [use it](https://github.com/larsiusprime/crashdumper#usage), code must be run inside the program... but when I try to do that it doesn't do anything. In fact, I added a `trace("test")` at the very beginning and even this didn't get executed.

**Comment by LaurentTreguier** [comment]
I should really look up how to use a tool correctly before posting n issue... I didn't even notice that there were openfl commands to run a project; running the executable manually results in a core dump but `openfl run` works perfectly fine.

**Comment by IBwWG** [comment]
Wait, isn't that a bug?  Shouldn't one be able to run from any directory and have it work correctly?  (Like, shouldn't openfl cd to the directory the game lives from?)

**Comment by ibilon** [comment]
That was fixed since then, https://github.com/openfl/lime/commit/9d51809c0d21505bf2a106817a6b7491cca4d118

**Comment by IBwWG** [comment]
Ah, thanks for clarifying!

**Comment by jgranick** [comment]
This will fail if `Sys.programPath` does not return properly, I've seen it fail in Linux. Has anyone else had trouble with this?

**Comment by ibilon** [comment]
@jgranick the problem with programPath in the template seems to be because it's called in `__init__`, otherwise it seems to work correctly.
