### ISSUE TITLE
BitmapData.copyPixels() merge alpha glitch

### ISSUE THREAD

**Issue by larsiusprime** [openfl/openfl#631]
Reproduction code:

```Haxe
private function testMergeAlpha():Void
{
	var asset = Assets.getBitmapData("assets/openfl.png");
	var bmp = new BitmapData(asset.width, asset.height, true, 0x00000000);
	bmp.copyPixels(asset, asset.rect, new Point(), null, null, true);
	addChild(new Bitmap(bmp));
}
```

(The DisplayingABitmap template works fine for this)

Expected correct result (-Dlegacy):
![mergealpha_legacy](https://cloud.githubusercontent.com/assets/739064/7353378/ad2a3a88-ecd8-11e4-8db3-27f44e5d2792.png)

Actual result (-Dnext):
![mergealpha_next](https://cloud.githubusercontent.com/assets/739064/7353387/b5965634-ecd8-11e4-9d7f-8bfa8caa82c1.png)

**Comment by larsiusprime** [comment]
CC @mrcdk @jgranick

**Comment by mrcdk** [comment]
It's weird, the haxe version works as expected, it's only the cpp version that doesn't

**Comment by larsiusprime** [comment]
Let me try some fancy printf'ing to debug.

Like, it could work to grab the alpha value at a place where it's known to be, say, 0.46 in photoshop and printf in the c++ and Sys.println in the haxe and compare?

**Comment by mrcdk** [comment]
nah, I already got it

**Comment by larsiusprime** [comment]
Ah cool :)
