### ISSUE TITLE
BitmapData.draw() when passed a TextField to draw doesn't always work.

### ISSUE THREAD

**Issue by Type1J** [openfl/openfl#636]
This problem was found when porting an Away3D app. Please try looking at the Basic_View stats panel for an example.

**Comment by Type1J** [comment]
I think that this is due to Stage3D not restoring the GL state after a render.

**Comment by Type1J** [comment]
The Stage3D not restoring the state problem may be only some of the issue, but from what I've observed, it may be the sole contributor of this issue.

This is the normal Basic_View Away3D example with the modification that the FPS is passed the color green. The white rectangles are where the green characters should be.
![image](https://cloud.githubusercontent.com/assets/413028/7389128/0cbe1882-ee39-11e4-8454-5ab0e59a0973.png)

This is the same app with

    _view.render();

in the frame callback commented out.
![image](https://cloud.githubusercontent.com/assets/413028/7389221/f648e2ca-ee39-11e4-9290-deaea58d23a0.png)

Although this TextField doesn't render into a BitmapData, this sort of behavior is what I was seeing.

**Comment by Type1J** [comment]
Just to confirm, I changed the render function to

	private static var frame_counter = 0;
	private function _onEnterFrame(e:Event):Void
	{
		_plane.rotationY += 1;
		++frame_counter;
		if (frame_counter < 300) {
		  return;
		}
		if (frame_counter > 600) {
		  return;
		}
		_view.render();
	}

For 3 seconds, I see the white screen with the correct green text.
Then, I see the plane spinning with the incorrect white blocks in place of the text.
3 seconds later, the screen goes white, and the incorrect white blocks render on a white background (you can't see them, but they're there).

I originally said that this was Stage3D not setting all of the GL state back to any values that may have changed, but that seems like it would be a heavy task to keep track of changed GL state just to restore it later.
This could also be viewed as the TextField (spicifically, the openfl._internal.renderer.opengl.utils.GraphicsRenderer) not setting all of the required GL state for its own rendering.

I haven't figured out what state we're talking about, yet. If anybody knows, then please point me in the right direction.

**Comment by Type1J** [comment]
I found that the problem occurs when GL.useProgram (); is called and it isn't set back to the OpenFL renderer program. I'm looking into where that was initially set.

**Comment by Type1J** [comment]
It seems that the problem is with openfl/_internal/renderer/opengl/utils/ShaderManager.hx

If any GL activity changes the shader by calling GL.useProgram(), then the ShaderManager isn't notified, and the call to setShader() doesn't call the GL.useProgram().

I don't know what the "after all OpenFLViews have rendered" function is for OpenFL, but I think I need to find that, and then call setShader(null), which will cause the next call to setShader() to work properly.

**Comment by larsiusprime** [comment]
Just gotta say I've been watching this and I'm impressed by your detective work! You can do it!

**Comment by Type1J** [comment]
@larsiusprime Thanks! I hope the patch that I'm making benefits you.

I have the shaders happy, but it looks like the shader isn't the only state that's not getting set correctly if any rendering happens.

Using the same render function as before, but using a blue background:

First 3 seconds:
![image](https://cloud.githubusercontent.com/assets/413028/7400817/90f2d83c-ee8d-11e4-95bc-94f73b367f7b.png)

Second 3 seconds:
![image](https://cloud.githubusercontent.com/assets/413028/7400794/6685792e-ee8d-11e4-9ed1-51deaeb9ae2f.png)

Afterward
![image](https://cloud.githubusercontent.com/assets/413028/7400703/c937d914-ee8c-11e4-8d5d-ef61a713d0d0.png)

I'm guessing blend mode is the cause here, but I'd bet that if the other state managers behave the same way, then they'll need a similar change.

**Comment by Type1J** [comment]
The pull fixes everything that I've shown above, and many cases of bad text rendering in Away3D and Starling apps.

**Comment by Type1J** [comment]
I should also say that the problem wasn't specific to Stage3D, it was specific to OpenGLView. Any app that uses OpenGLView along with a TextField would have had similar problems, but this patch fixes that.

**Comment by larsiusprime** [comment]
Way to go!

**Comment by Type1J** [comment]
@larsiusprime Thanks! I'm trying to flip all of my projects over to next. I think that you're trying to do the same with Flixel. Hopefully we'll benefit each other.

**Comment by larsiusprime** [comment]
Yeah, we're making good progress. We also just got ANGLE support working on windows thanks to a forum user!
http://community.openfl.org/t/how-to-use-angle-library-on-old-machines/1158/39?u=larsiusprime

So hopefully we'll finish knocking all these little things out one by one.

**Comment by Type1J** [comment]
I missed a case. See https://github.com/openfl/openfl/pull/657
