### ISSUE TITLE
BitmapData Causing Crash - Windows

### ISSUE THREAD

**Issue by hoseyjoe** [openfl/openfl#637]
package;
import openfl.display.*;
class Main extends Sprite 
{
	public function new() 
	{
		super();
		var bitmapdata = new BitmapData(1024, 1024, true, 0);  
	}
}

lime: 2.3.0 git [dev:D:\SDKs\haxe3\haxe\lib/lime/git]
openfl: 3.0.0-Beta3 git [dev:D:\SDKs\haxe3\haxe\lib/openfl/git]

Called from ApplicationMain::main ApplicationMain.hx line 122
Called from ApplicationMain::create ApplicationMain.hx line 30
Called from lime.app.Preloader::create lime/app/Preloader.hx line 61
Called from openfl.display.Preloader::start openfl/display/Preloader.hx line 93
Called from NMEPreloader::onLoaded NMEPreloader.hx line 107
Called from openfl.display.DisplayObject::dispatchEvent openfl/display/DisplayObject.hx line 784
Called from openfl.events.EventDispatcher::dispatchEvent openfl/events/EventDispatcher.hx line 266
Called from openfl.display.Preloader::display_onComplete openfl/display/Preloader.hx line 129
Called from lime.app.Preloader::start lime/app/Preloader.hx line 234
Called from ApplicationMain::init ApplicationMain.hx line 86
Called from ApplicationMain::start ApplicationMain.hx line 152
Called from Type::createInstance D:\SDKs\haxe3\haxe\std/cpp/_std/Type.hx line 82
Called from DocumentClass::new ApplicationMain.hx line 210
Called from Main::new Main.hx line 8
Called from openfl.display.BitmapData::new openfl/display/BitmapData.hx line 197
Called from lime.graphics.Image::new lime/graphics/Image.hx line 129
Called from lime.graphics.Image::fillRect lime/graphics/Image.hx line 365
Called from lime.graphics.utils.ImageDataUtil::fillRect lime/graphics/utils/ImageDataUtil.hx line 292

**Comment by larsiusprime** [comment]
I wonder if this is related to this:
https://github.com/openfl/openfl/pull/639

**Comment by larsiusprime** [comment]
What target are you using? CPP I imagine?

**Comment by hoseyjoe** [comment]
Yes CPP.  Using Flash Develop to compile openfl based Haxe program to
Windows

Sincerely,
*Joe Williamson*
*Chief Technology Officer*
*Joe.Williamson@RealityCharting.com* <Joe.Williamson@RealityCharting.com>
 <https://www.realitycharting.com>
(Direct) 206-922-7912
(US) 877-722-2770
*www.RealityCharting.com* <http://www.realitycharting.com/>

**Comment by hoseyjoe** [comment]
I updated after the merge from jgranick and it did not fix this issue

**Comment by mrcdk** [comment]
I can't reproduce it using latest git versions of lime and openfl

**Comment by hoseyjoe** [comment]
I was using haxe 3.2 rc2.  Downgraded to 3.1.3 and it didn't resolve the issue. project.xml below

<?xml version="1.0" encoding="utf-8"?>
<project>
	<meta title="Crap" package="Crap" version="1.0.0" company="" />
	<app main="Main" file="Crap" path="bin" />	
	<window background="#000000" fps="60" />
	<window width="800" height="480" unless="mobile" />
	<window orientation="landscape" vsync="false" antialiasing="0" if="cpp" />
	<source path="src" />
	<haxelib name="openfl" />
</project>

This is the full output from FD
Running process: D:\SDKs\haxe3\haxe\haxelib.exe run lime run "project.xml" windows -debug
Could not find primitive lime_image_data_util_color_transform__3.
Could not find primitive lime_image_data_util_copy_channel__MULT.
Could not find primitive lime_image_data_util_copy_pixels__5.
Could not find primitive lime_image_data_util_fill_rect__3.
Could not find primitive lime_image_data_util_flood_fill__4.
Could not find primitive lime_image_data_util_get_pixels__3.
Could not find primitive lime_image_data_util_merge__MULT.
Could not find primitive lime_image_data_util_multiply_alpha__1.
Could not find primitive lime_image_data_util_resize__4.
Could not find primitive lime_image_data_util_set_pixels__4.
Could not find primitive lime_image_data_util_unmultiply_alpha__1.
Called from ApplicationMain::main ApplicationMain.hx line 122
Called from ApplicationMain::create ApplicationMain.hx line 30
Called from lime.app.Preloader::create lime/app/Preloader.hx line 61
Called from openfl.display.Preloader::start openfl/display/Preloader.hx line 93
Called from NMEPreloader::onLoaded NMEPreloader.hx line 107
Called from openfl.display.DisplayObject::dispatchEvent openfl/display/DisplayObject.hx line 784
Called from openfl.events.EventDispatcher::dispatchEvent openfl/events/EventDispatcher.hx line 266
Called from openfl.display.Preloader::display_onComplete openfl/display/Preloader.hx line 129
Called from lime.app.Preloader::start lime/app/Preloader.hx line 234
Called from ApplicationMain::init ApplicationMain.hx line 86
Called from ApplicationMain::start ApplicationMain.hx line 152
Called from Type::createInstance D:\SDKs\haxe3\haxe\std/cpp/_std/Type.hx line 82
Called from DocumentClass::new ApplicationMain.hx line 210
Called from Main::new Main.hx line 8
Called from openfl.display.BitmapData::new openfl/display/BitmapData.hx line 197
Called from lime.graphics.Image::new lime/graphics/Image.hx line 129
Called from lime.graphics.Image::fillRect lime/graphics/Image.hx line 365
Called from lime.graphics.utils.ImageDataUtil::fillRect lime/graphics/utils/ImageDataUtil.hx line 292

**Comment by mrcdk** [comment]
have you done a lime rebuild after pulling the changes? there are a a few `Could not find primitive ...` there
Use the command: `lime rebuild windows -clean`

**Comment by hoseyjoe** [comment]
damnit.  yes, that was it
