### ISSUE TITLE
Suppress the libpng iccp warning

### ISSUE THREAD

**Issue by larsiusprime** [openfl/openfl#638]
I'm not sure if this is a lime or an openfl thing, but my command window is literated with:

```
libpng warning: iCCP: known incorrect sRGB profile
```

Googling around this doesn't seem to be a big issue, can a flag be set to just suppress the warning?

**Comment by jgranick** [comment]
I looked into it, but there is not one, that I am aware of. An option might be (not sure if this would be a good idea?) remove the ICCP information in the build tools, but that might be more time-consuming (and complex) than its worth

**Comment by larsiusprime** [comment]
I think I'd settle for knowing what I can do to properly strip the information from my images.

**Comment by jgranick** [comment]
I think it can be done by opening and re-saving files, depending on the editor.

Anyway, I don't know if we should break libpng to force this off, or leave it as-is?
