### ISSUE TITLE
Next graphics - Linestyle with alpha renders the wrong color (OpenFLNextShapeTest #1)

### ISSUE THREAD

**Issue by jcward** [openfl/openfl#643]
Test case: https://github.com/jcward/OpenFLNextShapeTest

Linestyle with alpha = 0.5 is the wrong color in Next, both the red rectangle and the green circle

[<img src="https://raw.githubusercontent.com/jcward/OpenFLNextShapeTest/master/compare.png" width=1168>](https://raw.githubusercontent.com/jcward/OpenFLNextShapeTest/master/compare.png)

**Comment by jcward** [comment]
Tested with latest source and html5 target, this problem seems fixed:

[<img src="https://raw.githubusercontent.com/jcward/OpenFLNextShapeTest/master/openfl_next_flash_html5.png">](https://raw.githubusercontent.com/jcward/OpenFLNextShapeTest/master/openfl_next_flash_html5.png)

**Comment by jcward** [comment]
Oh, the issue still exists on cpp/neko...  I'll reopen for that reason, but I presume @jgranick asked the try html5 becasue it has the latest code?

**Comment by larsiusprime** [comment]
It's complicated I think; Basically in next all the various targets are unified, with the small exception of rendering, which has various pathways:

* Flash: Just fall through to flash's native rendering/drawing calls, which we can't (and don't want to) override.
* CANVAS: In HTML5, use canvas to do the rendering
* DOM: In HTML5, use DOM to do the rendering
* GL: In CPP, Neko, and optionally in HTML5 is a certain flag is set, use OpenGL/WebGL to do the rendering

So I think you're probably seeing the results of the (correctly implemented) HTML5 Canvas renderer, but the GL renderer isn't quite there yet.

**Comment by larsiusprime** [comment]
I get even weirder results in neko+next!

![shape_neko_next](https://cloud.githubusercontent.com/assets/739064/7414328/8d88f9f8-ef17-11e4-9ad1-e3969bf0dc03.png)

Legacy is fine:

![shape_neko_legacy](https://cloud.githubusercontent.com/assets/739064/7414330/91d43978-ef17-11e4-8041-66f2e9341457.png)

I'm wondering if I've got OpenGL driver issues? Perhaps ANGLE support could help that part at least.

**Comment by mrcdk** [comment]
well, I've been all day trying to get what flash is doing with graphics, what I found is that my flash output is totally different to yours :confused: anyway, I'll fix the `draw()` issue tomorrow.

![http://puu.sh/hwZtb/82e6823c99.png](http://puu.sh/hwZtb/82e6823c99.png)
