### ISSUE TITLE
Next graphics - Gradient fill is missing (OpenFLNextShapeTest #2)

### ISSUE THREAD

**Issue by jcward** [openfl/openfl#644]
Test case: https://github.com/jcward/OpenFLNextShapeTest

Gradient fill is missing in Next, note the blue-to-red fill is just missing.

[<img src="https://raw.githubusercontent.com/jcward/OpenFLNextShapeTest/master/compare.png" width=1168>](https://raw.githubusercontent.com/jcward/OpenFLNextShapeTest/master/compare.png)

**Comment by jcward** [comment]
Tested against latest source, html5 target, gradient is there, but gradient positioning is off:

[<img src="https://raw.githubusercontent.com/jcward/OpenFLNextShapeTest/master/openfl_next_flash_html5.png">](https://raw.githubusercontent.com/jcward/OpenFLNextShapeTest/master/openfl_next_flash_html5.png)

**Comment by larsiusprime** [comment]
I get the same results:

![shape_html5](https://cloud.githubusercontent.com/assets/739064/7414255/1a099168-ef17-11e4-8d15-a7bb44cdcd2f.png)

**Comment by jcward** [comment]
Well, @larsiusprime your text is positioned better, but the red rectangle is wrong, and the gradient is too red.

**Comment by larsiusprime** [comment]
Ah right you are. The text box I can fix I think -- that might be the same across all targets. The gradient looks incorrectly implemented on whatever renderer this is using (presumably canvas).

**Comment by larsiusprime** [comment]
@jcward: Text is fixed now (see here: https://github.com/openfl/openfl/issues/646), gradient still broken for me. I'll leave that to smarter folks. ScrollRect I miiiight be able to take care of.

**Comment by jgranick** [comment]
If anyone wants to take a crack at this, the code for the HTML5 gradient fill is currently here:

https://github.com/openfl/openfl/blob/7c0b0236eb66c32d35c77ebf624440a39efefcee/openfl/_internal/renderer/canvas/CanvasGraphics.hx#L465-L480

If we get it right in HTML5, it should help us implement it properly for native as well

**Comment by larsiusprime** [comment]
@jgranick: I might give it a shot, but where on earth are you getting those 1638.4 magic numbers from?

**Comment by jcward** [comment]
Right, not the Shape's position matrix, but when you define a gradient, there's a different matrix that controls the coloring size/positioning via createGradientBox. I believe this is where this bug stems from. e.g. from the testcase:

    // Gradient helper
    private static var GRADIENT_M:flash.geom.Matrix = new flash.geom.Matrix();
    public static function begin_gradient(g:openfl.display.Graphics,
                                          w:Float,
                                          h:Float,
                                          c1:UInt=0x444444,
                                          c2:UInt=0x535353,
                                          angle:Float=-1.5757963):Void
    {
      GRADIENT_M.identity();
      GRADIENT_M.createGradientBox(w, h, angle);
      g.beginGradientFill(openfl.display.GradientType.LINEAR,
                          [c1,c2],
                          [1,1],
                          [0,255],
                          GRADIENT_M);
    }

**Comment by larsiusprime** [comment]
ah interesting, soon as I have a chance I'll look into that.

**Comment by jgranick** [comment]
I have a feeling that the linear gradient fill code in the canvas graphics class is not handling either scale or rotation quite properly. It's a bit tricky

**Comment by jcward** [comment]
Where's the source code for this?

**Comment by jgranick** [comment]
https://github.com/openfl/openfl/blob/master/openfl/_internal/renderer/canvas/CanvasGraphics.hx#L235-L244

**Comment by jcward** [comment]
Ok, interesting, it's not handling offsets, either, but looks like it could (via matrix.tx / matrix.ty). Hoever the underlying context.createLinearGradient API doesn't seem to support rotation.  Still, supporting cardinal rotation would be great.

**Comment by jgranick** [comment]
I believe it does, I think the underlying `createLinearGradient` call takes two points, and the difference between them gives you the length and rotation of the gradient. The trick is converting the Flash gradient box matrix into something that gives us those two points, that's where I'm trying to use the transform point calls to push something that makes sense to the canvas context

**Comment by larsiusprime** [comment]
Okay, interesting results. If I manually set [this line](https://github.com/openfl/openfl/blob/master/openfl/_internal/renderer/canvas/CanvasGraphics.hx#L244) to this:

```
gradientFill = context.createLinearGradient(0, 80, 0, 0);
```

It looks correct. The shape is 80 pixels tall, so that makes sense. So that's my goal -- see what the inputs are normally, and find out what trivial correct-looking transformation (x2, x0.5, etc) gets them to wind up there.

**Comment by larsiusprime** [comment]
Alright!

So this is promising. I'm tracing this out for variables point 1 & point 2:
```
point1 = (x=40.19999809488524, y=40.19999809488524)
point2 = (x=39.80000190511476, y=-39.79900191791598)
```

The values I need are:
```
point1 = (x=0, y=80)
point2 = (x=0, y=0)
```

I notice that if you subtract point 2 from point1 & point2 you get that.

point1 = (40,40)
point2 = (40,-40)

point1 - point2 = (40-40, 40--40) = (0,80)
point2 - point2 = (40-40, -40--40) = (0,0)

**Comment by jcward** [comment]
Ok, but also try [this line](https://github.com/jcward/OpenFLNextShapeTest/blob/master/Source/Main.hx#L44) with a shape not drawn from 0,0 -- eg, a circle centered at 0,0:

    shape2.graphics.drawCircle(0,0,80);

And compare Flash to Next.

**Comment by larsiusprime** [comment]
Cool, will give it a shot.

**Comment by larsiusprime** [comment]
Yup, same results as far as the linear gradient is concerned. The position of the circle itself is a bit off between HTML5 & legacy/flash, but the gradient is correct with the hard test-fix.

**Comment by larsiusprime** [comment]
![openflgradients](https://cloud.githubusercontent.com/assets/739064/7422206/9b6ae660-ef50-11e4-9861-831b198dcb0f.png)

Incidentally, is there a way to force the HTML5 target to keep the canvas at its "true" size so I don't have to manually scale it?

The fix I applied was simply this:

```
point1.x -= point2.x;
point1.y -= point2.y;
					
point2.x -= point2.x;
point2.y -= point2.y;							
```

Which seems a bit sloppy arithmetic; I'm sure it can be reduced to a more elegant form as doing it this way means point2 is basically always just 0,0. Also should probably test it out a bit more.

**Comment by larsiusprime** [comment]
https://github.com/openfl/openfl/pull/649

**Comment by jgranick** [comment]
Hey guys,

I got this fixed in HTML5. Magic numbers!

**Comment by jgranick** [comment]
This is also done in the Cairo renderer, so we should pipe the Cairo rendering through the GL renderer to see this resolved
