### ISSUE TITLE
Next graphics - scrollRect doesn't work (OpenFLNextShapeTest #3)

### ISSUE THREAD

**Issue by jcward** [openfl/openfl#645]
Test case: https://github.com/jcward/OpenFLNextShapeTest

scrollRect doesn't work

Potentially related to #529

[<img src="https://raw.githubusercontent.com/jcward/OpenFLNextShapeTest/master/compare.png" width=1168>](https://raw.githubusercontent.com/jcward/OpenFLNextShapeTest/master/compare.png)

**Comment by jcward** [comment]
Tested with latest source and html5 target, this problem seems fixed:

[<img src="https://raw.githubusercontent.com/jcward/OpenFLNextShapeTest/master/openfl_next_flash_html5.png">](https://raw.githubusercontent.com/jcward/OpenFLNextShapeTest/master/openfl_next_flash_html5.png)

**Comment by larsiusprime** [comment]
Did it also work on cpp/neko?

**Comment by jcward** [comment]
Oh, no, the issues all still exist on cpp/neko...  I'll reopen for that reason, but I presume @jgranick asked the try html5 becasue it has the latest code?

**Comment by larsiusprime** [comment]
Ping @mrcdk

**Comment by jgranick** [comment]
When we test in HTML5, it helps confirm if this works in "next" at all.

The canvas renderer (which is default in HTML5) is more mature than the newer OpenGL renderer, though it is simpler to write a canvas renderer, probably, anyway :wink:

It helps us drill down on what's really going on. For example, the bounds check was wrong in HTML5 as well -- we knew it wasn't (likely) a renderer-related problem. scrollRect was tricky to get right, but I think HTML5 has it fully done and working :smile:

**Comment by larsiusprime** [comment]
Yeah makes sense! But just to be clear: the closing state of this issue is works in cpp/neko AND html5 tho, right?

**Comment by jcward** [comment]
FYI, here again, there should be a matrix that controls the positioning and size of the gradient.

**Comment by larsiusprime** [comment]
Hmmm, good point. Let's test what happens if we put the object at 0,0 and don't rotate it. It'd be handy if all it was, was a matrix not being passed in. Doubt we're that lucky tho :P

**Comment by larsiusprime** [comment]
Okay, on HTML5 position & rotation of the shape doesn't seem to affect gradient wrong-ness any more than it already is, so that easy check is taken care of.

**Comment by jcward** [comment]
Right, not the Shape's position matrix, but when you define a gradient, there's a different matrix that controls the coloring size/positioning via createGradientBox. I believe this is where this bug stems from. e.g. from my testcase:

    // Gradient helper
    private static var GRADIENT_M:flash.geom.Matrix = new flash.geom.Matrix();
    public static function begin_gradient(g:openfl.display.Graphics,
                                          w:Float,
                                          h:Float,
                                          c1:UInt=0x444444,
                                          c2:UInt=0x535353,
                                          angle:Float=-1.5757963):Void
    {
      GRADIENT_M.identity();
      GRADIENT_M.createGradientBox(w, h, angle);
      g.beginGradientFill(openfl.display.GradientType.LINEAR,
                          [c1,c2],
                          [1,1],
                          [0,255],
                          GRADIENT_M);
    }

**Comment by larsiusprime** [comment]
ah interesting, soon as I have a chance I'll look into that.

**Comment by jcward** [comment]
Oops - this is the wrong bug, the gradient issue is #644 - this bug is the scrollRect issue.  I've moved my above comment there.

**Comment by tienery** [comment]
Recreating a new Rectangle over the old `scrollRect` is one way to workaround this until it is fixed.

Someone suggested fixing it (via #529) by removing the if statement to call `__setTransformDirty()` every time it is changed. Unless this has been resolved in a patch that has not yet been released some other way.

**Comment by ibilon** [comment]
I tried and I actually have it working on native but not html5.

**Comment by Leander1P** [comment]
#901 related at all?

**Comment by jgranick** [comment]
should be fixed, thanks :smile:
