### ISSUE TITLE
Next graphics - getBounds wrt parent (OpenFLNextShapeTest #4)

### ISSUE THREAD

**Issue by jcward** [openfl/openfl#646]
Test case: https://github.com/jcward/OpenFLNextShapeTest

`text.getBounds(this)` returns top-left (instead of proper text .x and .y position) in Next, red outline should be around text.

[<img src="https://raw.githubusercontent.com/jcward/OpenFLNextShapeTest/master/compare.png" width=1168>](https://raw.githubusercontent.com/jcward/OpenFLNextShapeTest/master/compare.png)

**Comment by jcward** [comment]
Tested with latest source, html5 target. This problem still exists, and another problem is that the text is mis-positioned:

[<img src="https://raw.githubusercontent.com/jcward/OpenFLNextShapeTest/master/openfl_next_flash_html5.png">](https://raw.githubusercontent.com/jcward/OpenFLNextShapeTest/master/openfl_next_flash_html5.png)

**Comment by larsiusprime** [comment]
The text thing I might be able to solve.

**Comment by larsiusprime** [comment]
Alrighty:

**Flash**
x = 86.5
y = 3.4
w = 201.7
h = 62.5

**Legacy**
x = 87
y = 5
width = 201
height = 62

**Next**
x = 0
y = 0
width = 201.68
height = 62.569

Looks like Next has properly good width/height values, closer than legacy even. So let me see if I can deduce a proper X/Y for this. I tightened up the renderer a while back so I should be able to figure this out...

**Comment by larsiusprime** [comment]
Oh wow this is a *simple* fix I think. I think you can just plug x,y in to the x,y for that rectangle instead of 0,0: 
https://github.com/openfl/openfl/blob/master/openfl/text/TextField.hx#L1009

**Comment by larsiusprime** [comment]
https://github.com/openfl/openfl/pull/647

**Comment by larsiusprime** [comment]
Try grabbing that branch yourself and see if it fixes everything?

**Comment by larsiusprime** [comment]
I now get these values:

x = 83
y = -0.79
width = 201.68
height = 62.569

So the x,y values don't match up with flash/legacy, although they're close. That said, VISUALLY they look right. Also I ran a test on flash and legacy, and found that the x,y values of the TextField itself exactly matched the x,y values from getBounds, so any discrepancy in x,y values lies elsewhere.

**Comment by larsiusprime** [comment]
**Neko-next**

Before:
![shape_neko_next](https://cloud.githubusercontent.com/assets/739064/7414667/c849f658-ef19-11e4-93b0-517cf10b4de4.png)

After:
![shape_neko_next2](https://cloud.githubusercontent.com/assets/739064/7414664/c510fee6-ef19-11e4-86cc-1a64ba6031da.png)

**HTML5-next**

Before:
![shape_html5](https://cloud.githubusercontent.com/assets/739064/7414693/eb2aa870-ef19-11e4-8dea-71cd8a7d7ca8.png)

After:
![shape_html5_2](https://cloud.githubusercontent.com/assets/739064/7414699/f2dd6f12-ef19-11e4-8d55-d575bc7a488f.png)

**Comment by jcward** [comment]
Well, careful, technically you can ask for the bounds from any other coordinate space. X,y may be too simple, it should have something to do with the matrix passed in, I'll retest and improve the test case tonight.

**Comment by larsiusprime** [comment]
Okay, cool. Let me know if my assumptions are wrong and I'll continue to dial it in.

Might post a quick comment on the PR itself if you think it's best to be cautious for now.

**Comment by larsiusprime** [comment]
Okay, from the Flash API:

```
     var container:Sprite = new Sprite();
     container.x = 100;
     container.y = 100;
     this.addChild(container);
     var contents:Shape = new Shape();
     contents.graphics.drawCircle(0,0,100);
     container.addChild(contents);
     trace(contents.getBounds(container));
      // (x=-100, y=-100, w=200, h=200)
     trace(contents.getBounds(this));
      // (x=0, y=0, w=200, h=200)
```

**Comment by jcward** [comment]
Yes, OpenFL's implementation looks good - it involves both my transform and the world transform. This will handle all rotation/etc and give correct bounds from any coordinate space.

**Comment by larsiusprime** [comment]
Okay, so help a dummy out -- how do I apply the matrix transforms to an (x,y) pair?

**Comment by larsiusprime** [comment]
Actually... I suppose we'd need to apply the matrix not just to the point, but to the naive (0-space, unrotated, unscaled) bounds?

**Comment by larsiusprime** [comment]
Okay, so the textField level bounds function looks like this before any changes from me:

```Haxe
    @:noCompletion private override function __getBounds (rect:Rectangle, matrix:Matrix):Void {
		
		var bounds = new Rectangle (0, 0, __width, __height);
		bounds.transform (__worldTransform);
		
		rect.__expand (bounds.x, bounds.y, bounds.width, bounds.height);
		
	}
```

Now is this correct?

```Haxe
    @:noCompletion private override function __getBounds (rect:Rectangle, matrix:Matrix):Void {
		
		var bounds = new Rectangle (0, 0, __width, __height);
		bounds.transform (__worldTransform);
		bounds.transform (matrix);
		rect.__expand (bounds.x, bounds.y, bounds.width, bounds.height);
		
	}
```

IE, should the matrix transform come before or after the __worldTransform? And that's assuming that the __worldTransform isn't redundant if the matrix is also applied?

**Comment by jcward** [comment]
Wait, that's `DisplayObject.getBounds()`, while the `TextField` is overriding `__getBounds`, which appears to be the internal bounds, since `getBounds()` takes care of all the coordinate matrix operations.

So why isn't TextField's getBounds doing what DisplayObject's getBoudns does?  Or is it?  Would a Shape give the same problem?

If TextField's __getBounds should be based on what happens in DisplayObject's __getBounds / Graphics' __getBounds, but starting with new Rectangle(0,0,width,height), I'd think it might should look like:

	@:noCompletion private function __getBounds (rect:Rectangle, matrix:Matrix):Void {
		var bounds = new Rectangle (0, 0, __width, __height);
		bounds.transform (matrix != null ? matrix : __worldTransform);
		rect.__expand (bounds.x, bounds.y, bounds.width, bounds.height);
	}

**Comment by larsiusprime** [comment]
Okay so DisplayObject's generic __getBounds is this (used internally in the bigger getBounds):

```Haxe
@:noCompletion private function __getBounds (rect:Rectangle, matrix:Matrix):Void {
	
	if (__graphics != null) {
	
		__graphics.__getBounds (rect, matrix != null ? matrix : __worldTransform);
		
	}
	
}
```

So I agree your edit makes sense. I'll go ahead and do that, any idea what a good test case for this would look like?

**Comment by larsiusprime** [comment]
Ah, you have to do this instead:

```Haxe
@:noCompletion private override function __getBounds (rect:Rectangle, matrix:Matrix):Void {
		
		var bounds = new Rectangle (0, 0, __width, __height).transform (matrix != null ? matrix : __worldTransform);
		rect.__expand (bounds.x, bounds.y, bounds.width, bounds.height);
	}
```

because Rectangle.transform() returns a new rectangle, it doesn't modify the existing one. Wonder if Flash does that too or not...

**Comment by larsiusprime** [comment]
Looks like the standard Flash API just doesn't have a Rectangle.transform() function! So we should be good.

**Comment by jgranick** [comment]
Fixed now :smile:
