### ISSUE TITLE
Building Windows-Neko from Linux doesn't work.

### ISSUE THREAD

**Issue by mauvecow** [openfl/openfl#648]
Currently, if you try to create a Windows version from Linux(I am currently using a 32-bit install) using 'openfl build windows', it creates an unusable Neko binary that, when run, spits out this:

> Uncaught exception - load.c(237) : Failed to load library : std.ndll

The binary files included with the built executable are:

> ProjectName.exe lime.ndll neko.dll regexp.dll std.dll zlib.dll gc.dll manifest icon.ico

The dll files that are already there do not load, and are not used. Renaming them to .ndll files causes them to fail to load correctly in a diferent way, so they're basically not usable.

Copying std.ndll, regexp.ndll, and zlib.ndll from a working Windows Neko install allows the project to run as normal, without problem, even on systems without such an install. So the build here is just bundling the wrong files, it seems.

**Comment by Type1J** [comment]
The 'openfl build windows' command does not build a Neko binary; it builds a PE/COFF executable (.exe file) for Windows.

A policy in Haxe is that dynamic libraries are given no prefix (like "lib" in Linux) and the extension ".ndll", which I think means "Native DLL" (specifically, it means native code, not Neko), regardless of the target platform. If you build for Neko in Linux with 'openfl build neko', then you will still get a Neko binary, but any ".ndll" files are Linux ELF binaries (".so" files), not Windows PE/COFF binaries (".dll" files).

Preforming a 'openfl build windows' might use MinGW in Linux to compile a Windows ".exe" file, and I think that's what you mean here. In that case, you're saying that std.ndll is copied from the Linux Haxe distro, and that would make it -not- a Windows binary.

I agree that the copy shouldn't happen. I'm not sure what should be done, however. You might need to be prevented from compiling until you provide the "openfl" or "lime" command with a static or dynamic binary location for the Haxe standard library.

That's assuming that all of what I've said above is correct. Someone, please correct me if I'm wrong.

**Comment by mauvecow** [comment]
It's building to Export/windows/neko/bin, and there is no compilation output as there is in a native cpp build. Also ditching the neko dll breaks it. I do have MingW installed on the system, but AFAIK crosscompilation is not available in openfl. At least, it sure doesn't do it, if there's a way to enable it, I would like to know for exportation purposes.

The dll files it copies over to the binary directory are native Windows, a quick run through objdump or a hex editor shows that, but seemingly incompatible and renaming to ndll does not allow them to load, citing the following error:

> Could not link plugin to process (hxCFFILoader.h 782)

No idea what's up with that.

**Comment by ibilon** [comment]
`openfl build windows` does indeed build an exe, if you are on windows.

For windows, linux and mac target if you aren't on the target you are trying to build then it switches to a "cross compilation" neko application.

> Copying std.ndll, regexp.ndll, and zlib.ndll from a working Windows Neko install allows the project to run as normal, without problem, even on systems without such an install. So the build here is just
bundling the wrong files, it seems.
It seems they are copied from the `bin/Windows/` folder of hxcpp, if you replace them with those in this folder does it work? (will tell us if the file are corrupted or if it copies from the wrong directory)

**Comment by Type1J** [comment]
@ibilon I see. Thanks for the correction. :-)

**Comment by mauvecow** [comment]
Copied the dlls from /usr/lib/haxe/lib/hxcpp/3,2,37/bin/Windows, no go, renamed to ndll files, also no go.

Running it through wine/strace confirms that it is not looking for files with the .dll extension, only .ndll. Considering the files I copied to make it work came from the Windows Neko install, not Haxe or hxcpp itself, this makes sense to me. This seems like a mix-up between hxcpp and neko builds, at least from my perspective.

Relatedly, building the Windows/Neko version from Linux has the warning/error:
> sh: 1: /usr/lib/haxe/lib/lime/2,3,3/templates/bin/ReplaceVistaIcon.exe: Permission denied

Can't run exe files on Linux, haha.

**Comment by jgranick** [comment]
You could try skipping the ReplaceVistaIcon.exe step, and copy all the correct NDLL files, but I recall that Neko was having trouble finding the binaries locally, which defeats the purpose of being able to distribute builds done on another system (and thus, cross-compiling too)

**Comment by mauvecow** [comment]
Having the correct ndll files causes it to work correctly even on systems that do not have a neko install themselves; I've tested this with a fresh Wine install just to make sure. There's no pathing issue as far as I can tell, or if there was it's been patched out awhile ago.
