### ISSUE TITLE
Colors are weird on android

### ISSUE THREAD

**Issue by jeichelbaum** [openfl/openfl#651]
Code should be self explanatory:

class Main extends Sprite 
{

	public function new() 
	{
		super();
		
		graphics.beginFill(0x00ff00);	// colors off, black is red, green is purple etc...
		graphics.drawRect(0, 0, 100, 100);
		graphics.endFill();
	}
}

**Comment by mrcdk** [comment]
I can't reproduce the problem in any of my devices (Sony Xperia Neo V, Nvidia Shield Tablet, Nexus 7 2012)
can you give more information?

**Comment by Reintjuu** [comment]
I think it's the screen of OP's device. I can't reproduce the problem either.

**Comment by jeichelbaum** [comment]
Im using a Samsung Galaxy S3, will upgrade openfl this afternoon and check if it is still happening

**Comment by Yanrishatum** [comment]
Had similiar problem (on Samsung Galaxy Note 8). In my case Red component became transparent and Green/Blue components are switched.
I got this:
Left - actual image. Right - what displays on device.
![Example](http://i.imgur.com/l50Im5k.png)

**Comment by jeichelbaum** [comment]
Yanrishatum's bug sounds just like mine, when I pressed the home button, for an instant I had the correct colors before it closed the app

**Comment by mastef** [comment]
@jeichelbaum @Yanrishatum did it look something like this ? ( see 2nd minute mark )

https://www.youtube.com/watch?v=XvquQjmNcBE

openfl 3.6.1 on android

**Comment by jeichelbaum** [comment]
for me it didnt, but I eventually realized that our test device's monitor was slightly broken =)
