### ISSUE TITLE
Setting the shapeflag on hitTestPoint doesn't work. 

### ISSUE THREAD

**Issue by championchap** [openfl/openfl#654]
I've drawn a circle to a sprite with the graphics api, and am trying to do a shape flagged hitTestPoint against it, but the shape flag is ignored and instead it checks for collisions against the sprites bounding box.

I've tested this on Neko and C++ targets for the Mac and it is the case on both. 

Setting my project to build in openfl-legacy mode fixes the issue.

**Comment by jgranick** [comment]
This should be implemented now
