### ISSUE TITLE
Bitmaps display as black on android

### ISSUE THREAD

**Issue by altef** [openfl/openfl#655]
[All images display as black](http://community.openfl.org/t/all-images-are-black-in-android/1337) on android, although transparency is preserved with PNGs.
Probably related: [BitmapData.draw() has no effect](http://community.openfl.org/t/bitmapdata-draw-and-android/1334/7).

Both work as expected in legacy mode.

**Comment by fserb** [comment]
Been able to reproduce that on real devices.

**Comment by mrcdk** [comment]
The problem is in this function https://github.com/openfl/lime/blob/master/project/src/graphics/utils/ImageDataUtil.cpp#L405-L421 I don't know why it works on everything else but android :confused:

**Comment by jgranick** [comment]
I just made a couple changes to try and guard this if the buffer is not transparent, but I'm not sure if (in this case) it is set to false. Worth a try to see if it helped, though I'm concerned, because even in cases where it is fully visible, it should not be ending up with bad values like this (perhaps we need an explicit type cast?)

**Comment by mrcdk** [comment]
Nope, it breaks semitransparent images on everything. It "fixes" it on android but the real problem is still there.

**Comment by jgranick** [comment]
before my changes, or before casting?

**Comment by mrcdk** [comment]
before your changes and after your changes. The pirate image is modified with paint.net to have 0.5 alpha

**Comment by jgranick** [comment]
I guess we need to make sure that `transparent` is set to true in the right places

**Comment by jgranick** [comment]
and defaults to true

**Comment by mrcdk** [comment]
But still, the problem is there, premultiplyAlpha is broken on android but only the cpp implementation the Haxe implementation works. If you comment out these lines https://github.com/openfl/lime/blob/master/lime/graphics/utils/ImageDataUtil.hx#L811-L813 it uses the Haxe implementation.

**Comment by mrcdk** [comment]
oh, found it... it's... damn... https://github.com/openfl/lime/pull/450
can you revert the changes you did until we find a better way? they are breaking stuff

**Comment by gabriellevy** [comment]
Hi
I use openfl et lime last official releases and I still have this problem. And I can't find the file you are talking about. Should I use the github version of lime ? I'd prefer not to ...
