### ISSUE TITLE
URLLoader not working at all (except when using -Dv2)

### ISSUE THREAD

**Issue by TheSHEEEP** [openfl/openfl#661]
Here is the forum topic:
http://community.openfl.org/t/urlloader-not-triggering-any-events-or-errors/1399

Basically, the URLLoader does absolutely nothing. No events, no errors, no crash, no success.

The problem can be resolved by going into legacy mode using -Dv2, which is why I am sure there is a bug somewhere in the newer URLLoader implementation.

**Comment by jgranick** [comment]
This is resolved on the repository :smile:
