### ISSUE TITLE
problems with clean mac install and HAXE/OPENFL

### ISSUE THREAD

**Issue by lewislepton** [openfl/openfl#662]
this is a problem i have ran into after a clean install of my computer.

i have followed exactly everything and have what i need installed. i had a flixel install before i wipe the computer, but am choosing to just use openfl instead.
it had worked before i had done the clean install.

but on running, both in terminal and in sublime [using the HAXE build system], am running into trouble and dont know what they are or how to fix. ive followed everything on the sites given. but the same thing
here are some screenshot to show
im also using HAXE 3.2.0 and have tried 3.2.0r2 but both do not work

also have ran the openFL install and it has lime inside, but see that lime is the problem

thanks

![screen shot 2015-05-13 at 16 36 06](https://cloud.githubusercontent.com/assets/11299322/7614694/6b11679c-f990-11e4-9230-65dda557ac72.png)

![screen shot 2015-05-13 at 16 46 01](https://cloud.githubusercontent.com/assets/11299322/7614700/6fb0fd30-f990-11e4-8d1b-2f7eeb4fb67f.png)

**Comment by vance** [comment]
have you tried building with -DLegacy flag? I've had issues with the latest release.

**Comment by lewislepton** [comment]
i got it to work thanks to this here

http://community.openfl.org/t/running-openfl-error-on-mac/1409/14

thanks again ;)

**Comment by ChangJoo-Park** [comment]
thanks @lewislepton
