### ISSUE TITLE
URLLoader doesn't send the data field from the URLRequest

### ISSUE THREAD

**Issue by fserb** [openfl/openfl#663]
Bumped from [openfl-native #201](https://github.com/openfl/openfl-native/issues/201).

```
    var request = new URLRequest(_url);
    request.method = URLRequestMethod.GET;
    request.data = requestVars;
    var loader = new URLLoader(request );
````

doesn't send any CGI params.

**Comment by fserb** [comment]
I think it seems to work on Flash but for sure doesn't work on native.

**Comment by fserb** [comment]
It seems things got solved a couple hours ago, but they are still broken in Legacy.
Is there any hope to back port the fix?
A tempo solution for now is to use POST instead of GET on Legacy, which works fine.

**Comment by ibilon** [comment]
This was the commit mentioned https://github.com/openfl/openfl/commit/1185f542f61f571191afaf757efa5d7391112b26
