### ISSUE TITLE
EnterFrame stops working after added enterFrame listener to stage ?

### ISSUE THREAD

**Issue by T1mL3arn** [openfl/openfl#668]
```Haxe
class Main extends Sprite 
{

	public function new() 
	{
		super();
		
		// Assets:
		// openfl.Assets.getBitmapData("img/assetname.jpg")
			
		addChild(new FPS());
		var cstage = Lib.current.stage;
		cstage.addEventListener(Event.ENTER_FRAME, foo );
	}
	
	private function foo(e:Event):Void {}
}
```
If comment the line with addEventListener - FPS works correctly, but with that line - no update for frames. But few minor version ago it works fine. Problem discovered for Html5 and Neko

Haxe 3.2.0, Lime 2.4.1, OpenFl 3.0.5

**Comment by jgranick** [comment]
Please upgrade to 3.0.6 :smile:

**Comment by T1mL3arn** [comment]
Oh, how I can miss that fix ?! :disappointed:
