### ISSUE TITLE
Improve PNG loading code in order to support 8 bit ( and not expand to 32 )

### ISSUE THREAD

**Issue by ispebo** [openfl/openfl#672]
As well as updating the pixel format code to be ARGB32, RGB8, etc ..

**Comment by nicof03** [comment]
I hope this modification will be set up soon, because I did some optimization with TinyPNG...

**Comment by jgranick** [comment]
I believe that loading support for 8-bit PNG was done some time ago, but at runtime, I would like to see us being able to reduce the memory footprint of 8-bit or 24-bit images as well

https://trello.com/c/4qz08zQd/39-enable-support-for-8-bit-images-to-reduce-memory-use

Thanks :smile:

**Comment by jgranick** [comment]
This issue was moved to openfl/lime#872
