### ISSUE TITLE
Why is TextFormat.size Float instead of Int?

### ISSUE THREAD

**Issue by vroad** [openfl/openfl#673]
According to flash API reference it's "An integer that indicates the size in pixels".
Also, should other values (leftMargin, rightMargin, indent) be integer?

http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/TextFormat.html#TextFormat()

**Comment by jgranick** [comment]
To be honest, I'm not sure. The ActionScript documentation suggests that these are Objects (for some reason, perhaps because they are nullable?) I have used float values for this for a long time, but perhaps it's rounded

**Comment by MSGhero** [comment]
`size`, `leftMargin`, `rightMargin`, `leading`, and `indent` are all ints. As3's accepts floats to truncate automatically and nulls to assign default values to.

**Comment by hypersurge** [comment]
Despite the documentation, Float is the valid type for TextFormat.size.  To verify render a SWF with text set at a non integer size over the top of a duplicate set to the closest integer.  Also see the Flash IDE: size expects a Float (to one decimal figure).

Please revert Int back to Float.

**Comment by jgranick** [comment]
I just tested, a size of 17.5->18 in my test looks the same as using 18, 17->17.49 looks the same as 17.

Importing `flash.text.TextFormat` and using a float value for the size, I still get a rounded decimal size back when I use `textField.getTextFormat ()`

I'm not sure why I didn't think of this before. We can use `getTextFormat ()` to see how (and if) values change. For size, it definitely appears to be a decimal.

I can also confirm it is an integer when I look at the SWF specification for dynamic text symbols published from Flash CC (perhaps this is different for static text from the IDE, which generates flat shapes differently based on decimal values?)

**Comment by hypersurge** [comment]
You are correct.  I confirm 50.5 renders same as 50, 50.51 renders same as 51 (i.e. Math.round()) for classic text.

I was wrong - only TLF text renders non integer values, and uses its own classes to do so.

That said, if I was to put up a case that Float be reverted I would mention:
1) It is an accepted input (albeit rounded inside the function)
2) Round is not the same result as Int / Floor
3) The Haxe Std flash.text.TextFormat uses Float (not saying this is correct, but we should be consistent)
