### ISSUE TITLE
Stage3D depth test problem on latest from git

### ISSUE THREAD

**Issue by Type1J** [openfl/openfl#677]
After pulling, Away3D apps stopped displaying (black screen only). I found that this doesn't happen until render() is called on a View3D, and if depth testing is disabled, everything seems to render correctly, just without depth testing. I'm only looking at apps that aren't using depth testing right now, but somehow have it enabled. I haven't checked, but I believe that more involved apps that use depth testing are unaffected. (The problem seems to be that depth testing might be enabled when it wasn't desired.)

Basic_View from the away3d-examples will not display, for example.

**Comment by jgranick** [comment]
Fixed some time ago, sorry for the delay in closing the issue :smile:

**Comment by Type1J** [comment]
Awesome.
