### ISSUE TITLE
Can't load PNG via URL when ".png" is missing (Windows, Neko)

### ISSUE THREAD

**Issue by ratkingsminion** [openfl/openfl#681]
This code crashes at "loader.load(request)" when the target is set to Windows or Neko:

		var request = new openfl.net.URLRequest("https://dl.dropboxusercontent.com/u/10650964/_trash/example1");
		request.contentType = "image/png";
		var loader = new openfl.display.Loader();
		loader.load(request);

The file in the URLRequest exists and really is a PNG. Just add ".png" to the URL to confirm - if I use this file instead, the code works. Both files work with the Flash target.

The problem might be that OpenFL seems to need ".png" as suffix, otherwise it fails.

**Comment by jgranick** [comment]
This is fixed :smile:
