### ISSUE TITLE
scrollRect render problem on android and events on html5

### ISSUE THREAD

**Issue by shadowofsoul** [openfl/openfl#694]
Hi,

this report includes 2 bugs (that are related with scrollRect):

1) on html5, if you have a container with scrollRect, and a the content of it, goes into a negative space, anything that would cover it, will not fire any mouse or touch events

2) on android, same settings, content goes in a negative space, anything that would cover it, would not be rendered in the screen ( is not covered by the content itself, the clip of scrollRect works, but at the same time, "erase" all the elements that would be covered by it)

as a example, here is a red sprite of 100x100, inside a scrollRect container of 50x50. the position of the red is  y = -50. the green section is a button of 50x100. so, it means that the red section would cover the green button if the scrollRect didn't exist. in html5 is rendered correctly but events are screw up. in android, the render is incorrect and event's doesn't work either.

html5:

![screenshot-16](https://cloud.githubusercontent.com/assets/375696/7884132/151d259c-05f2-11e5-8b68-dac64b6ebf6d.png)

android:

![screenshot-19](https://cloud.githubusercontent.com/assets/375696/7884158/4b3a4d12-05f2-11e5-9424-5b894b1629a0.png)

here is the project for the test case:

https://drive.google.com/file/d/0B4ORAawuQOukczRPelVBdzV2VTA/view?usp=sharing

**Comment by mrcdk** [comment]
1. the events should be fixed in the PR I opened (#695)
2. I don't see any problem testing it in a real device.
