### ISSUE TITLE
Matrix/render bug (HTML5 Canvas)

### ISSUE THREAD

**Issue by T1mL3arn** [openfl/openfl#696]
```Haxe
class Main extends Sprite 
{

	public function new() 
	{
		super();
		
		var bmd1 = new BitmapData(100, 100, true, 0xFF55EE55);
		bmd1.fillRect(new Rectangle(10, 10, 10, 10), 0xFFFF0000);
		
		var img1 = new Bitmap(bmd1, PixelSnapping.AUTO, true);
		var matrix = new Matrix();
		
		matrix.translate( -img1.width, 0);
		matrix.scale( -1, 1);
		matrix.translate(50, 50);
		
		img1.transform.matrix = matrix;
		
		addChild(img1);
	}
}
```
Flash result on the left, Html5 on the right
![matrix_bug](https://cloud.githubusercontent.com/assets/9349164/7909682/82e72644-0891-11e5-912b-b57fe5a2f243.PNG)

OpenFl 3.0.8 Lime 2.4.2 Haxe 3.2.0

**Comment by Anheurystics** [comment]
The same happens when running it in Neko. However, running it in legacy mode (on Neko) makes it render the same way as the one on the left. I'm guessing its a difference in the Matrix code of the legacy vs the next implementations.

**Comment by jgranick** [comment]
This is fixed now :smile:
