### ISSUE TITLE
TextFormat.italic renders text invisible (neko), TextFormat.underline does not underline text (neko, html5)

### ISSUE THREAD

**Issue by dstrekelj** [openfl/openfl#702]
I was playing around with text in OpenFL when I stumbled upon two issues. I'm not sure if everyone's aware of them or not (_or if they even are an issue_), but I feel it's best to speak up regardless. Setting the text format to bold works without issue.

**Version information:**
- Haxe 3.2.0
- OpenFL 3.0.8
- Lime 2.4.3

**Case:** Rendering italicised text on screen.

``` haxe
import openfl.display.Sprite;
import openfl.text.TextField;
import openfl.text.TextFormat;

class TextExample extends Sprite
{
    public function new() 
    {
        super();

        var textFormat : TextFormat = new TextFormat();
        textFormat.italic = true;

        var textField : TextField = new TextField();
        textField.defaultTextFormat = textFormat;
        textField.text = 'this text is italic';

        this.addChild(textField);
    }
}
```

**Expected:**

The italicised text "_this text is italic_" on screen.

**Result:**

**Neko.**  Nothing. No text visible at all.

**HTML5 (Canvas / DOM / WebGL).** Text is rendered as expected.

---

**Case:** Rendering underlined text on screen.

``` haxe
import openfl.display.Sprite;
import openfl.text.TextField;
import openfl.text.TextFormat;

class TextExample extends Sprite
{
    public function new() 
    {
        super();

        var textFormat : TextFormat = new TextFormat();
        textFormat.underline = true;

        var textField : TextField = new TextField();
        textField.defaultTextFormat = textFormat;
        textField.text = 'this text is underlined';

        this.addChild(textField);
    }
}
```

**Expected:**

The underlined text "this text is underlined" on screen.

**Result:**

**Neko.** The text "this text is underlined", but with no underline.

**HTML5 (Canvas / DOM / WebGL).** The text "this text is underlined", but with no underline.

**Comment by jgranick** [comment]
Moved here: https://trello.com/c/PE87GhfS/22-add-support-for-related-font-groups-italic-bold
