### ISSUE TITLE
Joystick issues with Lime 2.4.3 and openfl 3.0.8

### ISSUE THREAD

**Issue by GildasP** [openfl/openfl#706]
Hi.
Don't know if it's a relevent issue or if I'm a lonely case, but I'm not able to detect any joystick input on Windows 8.1 (Neko, C++).
You may find more details here : http://community.openfl.org/t/solved-issues-with-joystick-on-new-openfl/1554
My builds didn't detect any joystick on other computers neither.
I had to downgrade to Lime 2.2.2 + openFL 2.2.8 to get back joystick inputs.

**Comment by jgranick** [comment]
The current releases have been focusing on gamepad APIs, Lime has a new gamepad API which should be much stronger than the old joystick API. The plan is to deprecate the added joystick events, and to probably stick with allowing direct access to Lime's events or use of the Flash GameInput API, whatever one finds preferable :smile:

**Comment by GildasP** [comment]
Ok.
I'll be glad to follow this evolution, but as of now I'm not able to work with the Lime joystick API, which doesn't get me any signal neither...
Lib.application.window.onGamepad[...] seems dead to me, even if it works well for others :/

**Comment by larsiusprime** [comment]
@GildasP Hey there, we were able to set up an API in HaxeFlixel that was able to correctly gather signals from both the legacy joystick api and the new gamepad API:

https://github.com/HaxeFlixel/flixel/tree/dev/flixel/input/gamepad

Maybe that could be of some help? I wonder if this is a code issue, or a weird interaction with your gamepad, or perhaps both.

**Comment by GildasP** [comment]
@larsiusprime Ok, many thanks.
I'll look at it and see if I'm able to understand what you did :smile:
Maybe it's just the kind of rare bug that happens only on one particular configuration... as I said others have manage to make Lib.application.window.onGamepad[...] work successfully.
I'll keep you informed.

**Comment by larsiusprime** [comment]
If you're able to compile the latest flixel we have a handy gamepad manager demo to test things out:
https://github.com/HaxeFlixel/flixel-demos/tree/dev/Input/GamepadTest

I wonder if some of this flixel code could work it's way down to the OpenFL layer. It is a big blob of logic but it's verrrry handy.

**Comment by GildasP** [comment]
Long story short : I had a hard time to find out flixel's gamepad handling works fine because its in legacy mode.
Now I've got my joysticks working as long as I stay in legacy, but nothing in hybrid mode from openfl.events.JoystickEvent or Lime's Lib.application.window.onGamepad[...].

Don't know if it's an issue or a work-in-progress thing, I will continue testing with the next versions !

**Comment by jgranick** [comment]
Both use SDL2, SDL has a joystick API, and a smarter (better) gamepad API that works on top of the joystick API. If your device works as a joystick, but not a gamepad, I would guess that there is no profile for your hardware to provide button mappings. SDL has an API so we can add more, maybe there's a way to figure this out

**Comment by larsiusprime** [comment]
If you are not getting a hardware profile, flixel will default to assuming it's a 360 pad. The easiest way to get a test of what's going on is to override a few functions to provide debug trace data:

https://github.com/HaxeFlixel/flixel/blob/dev/flixel/input/FlxInput.hx#L25

Here you want to add this after that line:
```Haxe
if(current == JUST_PRESSED)
{
   trace("just pressed : " + ID);
}
```

And here:
https://github.com/HaxeFlixel/flixel/blob/dev/flixel/input/gamepad/FlxGamepadManager.hx#L92

You want to trace the "Model" enum to see what model it's trying to use.

Then you connect your gamepad and just start pressing buttons. Note what model it says it is, and then for each physical input note what comes out of the "Just Pressed" trace so we can use that to build a mapping.

**Comment by jgranick** [comment]
If there's no profile, does it still detect and report as a gamepad?

**Comment by larsiusprime** [comment]
You mean if there's no string identifier? I *THINK* it should return an "UNKNOWN" in the Model enum, and when it constructs a FlxGamepad object it should default to the 360.

**Comment by larsiusprime** [comment]
OH FYI: @GildasP, yeah flixel defaults to legacy mode. If you compile in Flash you should get something that works (fall-through to Flash API) or use the -Dnext define you'll get lime's new Gamepad API behavior.
