### ISSUE TITLE
SharedObject can be instantiated via constructor, even though constructor is private

### ISSUE THREAD

**Issue by cactusanctuary** [openfl/openfl#711]
Running on both v3 and v2, it's possible to instantiate a SharedObject by calling new SharedObject(). It should be only possible by calling SharedObject.getLocal(). SharedObject.new() is properly scoped to private, so I don't see why this works. 

I created a test class with a private constructor, and when trying to instantiate it outside the class, the compiler properly complains that the constructor is private. 

You can repro this by adding this line anywhere: 
v2: `var so:openfl.net.SharedObject = new openfl.net.SharedObject("testSO", "localPath", false);`
v3: `var so:openfl.net.SharedObject = new openfl.net.SharedObject();`

This *should* complain when compiling, but does not.

**Comment by brutalexcess** [comment]
That's actually a problem with the Haxe language in general. The keyword `private` isn't actually private access, it's technically more of a `protected` accessor field, which causes annoying confusion which I pointed out to a friend of mine a while back.

[This article](http://haxe.org/manual/class-field-visibility.html) explains the difference between private and public field accessor.

**Comment by cactusanctuary** [comment]
The issue is that you can instantiate using a private constructor from *any* class, not just from a class extending it. 

So I can use SharedObject's private constructor from Main, which extends Sprite. 

Personally I like the `private`/`protected` distinction, and wish we had `protected` scope in Haxe :)

**Comment by brutalexcess** [comment]
https://github.com/openfl/openfl/blob/master/openfl/net/SharedObject.hx#L188

That is `private` access, yes. Which means that if you extended SharedObject and tried to create private functions in that derived class, then instantiate that class versus instantiating SharedObject, you would no longer have access to the private variables in that derived class:

    class SomeObject extends SharedObject {
        private function new() { }
    }

    class Main extends Sprite {
        private var myObject:SomeObject;

        public function new() {
            myObject = new SomeObject(); //Error
            myObject = new SharedObject(); //okay
        }
    }

This is very confusing, I know... `protected` variable access means that you can only access them via its derived class, which in the example above, the `SomeObject` is derived from `SharedObject`. Only then can you truly make it "private". I haven't tested that example, so I could be wrong, the Haxe language might have some kind of differences between instantiation and variable access, but from what I can tell there is none.

**Comment by frabbit** [comment]
i guess it's because of the defines, are you using the flash target, because in flash the constructor is not private.

https://github.com/openfl/openfl/blob/master/openfl/net/SharedObject.hx#L557

**Comment by cactusanctuary** [comment]
@brutalexcess I don't understand what you mean. I think we're talking past each other. I'm raising what I see as a bug: you can directly create a new SharedObject via its constructor, even though the constructor is private. And you can do this from any class. 

@frabbit I'm using Mac target. Maybe the defines are interfering with the compiling somehow... Actually no, because I put in a trace in the private constructor of OpenFL SharedObject, and it traces out when I call `new SharedObject()`.

**Comment by jgranick** [comment]
I found some more information, and have posted an issue on Haxe: https://github.com/openfl/openfl/issues/711

Let's follow it there :smile:

**Comment by cactusanctuary** [comment]
@jgranick I think you meant to link an issue in Haxe but you linked to this same issue :P

**Comment by tienery** [comment]
lol, @jgranick I did explain earlier how `protected` accessor fields work, and that `private` acts as `protected` in Haxe. Using the `@:noPrivateAccess` will actually prevent the use of `private`/`public` accessor fields/functions.

**Comment by jgranick** [comment]
@cactusanctuary Oh, right :wink: 

https://github.com/HaxeFoundation/haxe/issues/4550

**Comment by jgranick** [comment]
@tienery I tried `@:noPrivateAccess` as a band-aid, but `openfl.net.SharedObject` uniquely still allows object creation :confused:

**Comment by tienery** [comment]
Was SharedObject's constructor private or public?

    public class Object {
        @:privateAccess
        private function new()
        { }
    ..

    public class Main
    {
        public function new()
        {
            var obj = new Object(); //error
        }
    }

Tried it just now myself, and it seemed to work...

**Comment by jgranick** [comment]
You'll see in my Haxe issue I opened, there's some strange exception that happens for the `SharedObject` that I don't understand. If I extend `EventDispatcher2` instead of `EventDispatcher` (with otherwise identical contents) then it prevents `new SharedObject ()` from occurring. I think it hits some strange edge-case in the compiler?
