### ISSUE TITLE
Capabilities.screenDPI is 0 (tested in Neko, Windows, Android) 3.1.0

### ISSUE THREAD

**Issue by ustutz** [openfl/openfl#718]
In Flash it is 72 and HTML5 96 for my screen. Shouldn't it be the same?

In Legacy mode it is 96 for Neko and Windows, 72 in Flash, 249.38... on my Android phone.

**Comment by ibilon** [comment]
Partially fixed by a718b35c0efbc5c9394be7602b647ad3f8e05c51,
now desktop isn't 0.

It's still not the same everywhere, but that's a lime issue.
