### ISSUE TITLE
BitmapData.draw failed with Intel HD4600 integrated graphic Card.

### ISSUE THREAD

**Issue by osoker** [openfl/openfl#720]
following Code on a NVCard will run successful.  But if i change my Card to Intel integrated graphic Card, The same code will output a wholeblack png file:
The code is very simple as follow:

		var s:Sprite = new Sprite();
		s.graphics.beginFill(0xFF00ffff, 1);
		s.graphics.drawRect(0, 0, 121, 20);
		s.graphics.endFill();

		// Making a BitmapData from the Sprite
		var ptrimage:BitmapData = new BitmapData( Std.int( s.width ), Std.int( s.height ), false, 0x00000000);
		ptrimage.draw(s);
		var t_barr : ByteArray = null;
		t_barr = ptrimage.encode(new Rectangle( 0, 0, Std.int( ptrimage.width), Std.int(ptrimage.height ) ), new PNGEncoderOptions(), t_barr );
		var t_str : String = "pic/testSimple.png";
		t_barr.writeFile( t_str );

**Comment by osoker** [comment]
Btw, The target is Neko

**Comment by aW4KeNiNG** [comment]
I have the same problem with the Windows target using Intel HD4000. I have changed the default graphics processor to NVidia Geforce, but my customers could have the same problem.

**Comment by willsonstar** [comment]
same problem hear, its been backing my noodle the last couple days

**Comment by toastytentacles** [comment]
still nothing on this? its breaking development on my laptop; which is very inconvenient.

**Comment by jgranick** [comment]
I believe this is an issue of frame buffers not being supported properly (which is used in bitmapData.draw)

We need to implement the Cairo version of bitmapData.draw, and probably use it by default

Hope to have this ready soon

**Comment by toastytentacles** [comment]
seems to have resolved on my end, thanx a lot <3
