### ISSUE TITLE
Issue compiling an HaxeFlixel project using "openfl update+openfl display+haxe" commands

### ISSUE THREAD

**Issue by remogatto** [openfl/openfl#734]
I'm playing with HaxeFlixel and I'm experiencing the following issue on any HaxeFlixel project:

    $ flixel tpl -n "HelloWorld"
    $ cd HelloWorld
    $ openfl update linux
    $ openfl display linux
    -main ApplicationMain 
    -cp /usr/lib/haxe/lib/flixel/3,3,8
    -D flixel=3.3.8
    -cp /usr/lib/haxe/lib/openfl/3,1,0
    -D openfl=3.1.0
    -cp /usr/lib/haxe/lib/lime/2,4,3
    -D lime=2.4.3
    -cp source
    -D openfl-next
    -D tools=2.4.3
    -D FLX_NO_DEBUG
    -D no-compilation
    -D NAPE_RELEASE_BUILD
    -D native
    -D lime-native
    -D openfl-native
    -D FLX_RENDER_TILE
    -D linux
    -D desktop
    --remap flash:openfl
    -cp export/linux64/cpp/haxe
    -cpp export/linux64/cpp/obj/
    --macro keep("Main")
    $ openfl display linux > project.hxml
    $ haxe project.hxml
    export/linux64/cpp/haxe/ApplicationMain.hx:25: characters 2-22 : Class<openfl.Lib> has no field setPackage
    export/linux64/cpp/haxe/ApplicationMain.hx:41: characters 2-18 : Class<openfl.Lib> has no field create
    export/linux64/cpp/haxe/ApplicationMain.hx:87: characters 4-28 : Class<openfl.Assets> has no field initialize
    export/linux64/cpp/haxe/ApplicationMain.hx:122: characters 11-29 : Class<openfl.Lib> has no field HARDWARE
    export/linux64/cpp/haxe/ApplicationMain.hx:123: characters 12-35 : Class<openfl.Lib> has no field ALLOW_SHADERS
    export/linux64/cpp/haxe/ApplicationMain.hx:124: characters 12-37 : Class<openfl.Lib> has no field REQUIRE_SHADERS
    export/linux64/cpp/haxe/ApplicationMain.hx:125: characters 12-34 : Class<openfl.Lib> has no field DEPTH_BUFFER
    export/linux64/cpp/haxe/ApplicationMain.hx:126: characters 12-36 : Class<openfl.Lib> has no field STENCIL_BUFFER
    export/linux64/cpp/haxe/ApplicationMain.hx:127: characters 11-30 : Class<openfl.Lib> has no field RESIZABLE
    export/linux64/cpp/haxe/ApplicationMain.hx:128: characters 12-32 : Class<openfl.Lib> has no field BORDERLESS
    export/linux64/cpp/haxe/ApplicationMain.hx:129: characters 11-26 : Class<openfl.Lib> has no field VSYNC
    export/linux64/cpp/haxe/ApplicationMain.hx:130: characters 12-32 : Class<openfl.Lib> has no field FULLSCREEN
    export/linux64/cpp/haxe/ApplicationMain.hx:131: characters 13-34 : Class<openfl.Lib> has no field HW_AA_HIRES
    export/linux64/cpp/haxe/ApplicationMain.hx:132: characters 13-28 : Class<openfl.Lib> has no field HW_AA
    export/linux64/cpp/haxe/DefaultAssetLibrary.hx:593: characters 45-54 : Class<openfl._Assets.AssetType_Impl_> should be Enum<Unknown<0>>
    export/linux64/cpp/haxe/DefaultAssetLibrary.hx:593: characters 45-54 : { TEXT : openfl.AssetType, TEMPLATE : openfl.AssetType, SOUND : openfl.AssetType, MUSIC : openfl.AssetType, MOVIE_CLIP : openfl.AssetType, IMAGE : openfl.AssetType, FONT : openfl.AssetType, BINARY : openfl.AssetType } should be Enum<Unknown<0>>
    export/linux64/cpp/haxe/DefaultAssetLibrary.hx:593: characters 45-54 : For function argument 'e'
    export/linux64/cpp/haxe/DefaultAssetLibrary.hx:230: characters 14-29 : Class<openfl.display.BitmapData> has no field load
    export/linux64/cpp/haxe/DefaultAssetLibrary.hx:330: characters 14-68 : Too many arguments
    export/linux64/cpp/haxe/DefaultAssetLibrary.hx:330: characters 14-68 : Function 'new' requires arguments : ?stream, ?context
    export/linux64/cpp/haxe/DefaultAssetLibrary.hx:369: characters 14-86 : Too many arguments
    export/linux64/cpp/haxe/DefaultAssetLibrary.hx:369: characters 14-86 : Function 'new' requires arguments : ?stream, ?context
    /usr/lib/haxe/lib/flixel/3,3,8/flixel/util/loaders/CachedGraphics.hx:77: characters 3-18 : flash.display.BitmapData has no field dumpBits
    /usr/lib/haxe/lib/flixel/3,3,8/flixel/text/FlxText.hx:926: characters 10-31 : openfl.text.TextFormatAlign should be String
    /usr/lib/haxe/lib/flixel/3,3,8/flixel/text/FlxText.hx:930: characters 10-32 : openfl.text.TextFormatAlign should be String
    /usr/lib/haxe/lib/flixel/3,3,8/flixel/text/FlxText.hx:934: characters 10-33 : openfl.text.TextFormatAlign should be String
    /usr/lib/haxe/lib/flixel/3,3,8/flixel/text/FlxText.hx:938: characters 10-30 : openfl.text.TextFormatAlign should be String
    /usr/lib/haxe/lib/flixel/3,3,8/flixel/text/FlxText.hx:331: characters 2-66 : String should be openfl.text.TextFormatAlign
    /usr/lib/haxe/lib/flixel/3,3,8/flixel/text/FlxText.hx:608: characters 2-66 : String should be openfl.text.TextFormatAlign
    export/linux64/cpp/haxe/DefaultAssetLibrary.hx:154: lines 154-206 : Field exists overloads parent class with different or incomplete type
    export/linux64/cpp/haxe/DefaultAssetLibrary.hx:154: lines 154-206 : id : String -> type : openfl.AssetType -> Bool should be id : String -> type : String -> Bool
    export/linux64/cpp/haxe/DefaultAssetLibrary.hx:154: lines 154-206 : openfl.AssetType should be String
    export/linux64/cpp/haxe/DefaultAssetLibrary.hx:209: lines 209-234 : Field getBitmapData is declared 'override' but doesn't override any field
    export/linux64/cpp/haxe/DefaultAssetLibrary.hx:426: lines 426-440 : Field isLocal overloads parent class with different or incomplete type
    export/linux64/cpp/haxe/DefaultAssetLibrary.hx:426: lines 426-440 : id : String -> type : openfl.AssetType -> Bool should be id : String -> type : String -> Bool
    export/linux64/cpp/haxe/DefaultAssetLibrary.hx:426: lines 426-440 : openfl.AssetType should be String
    export/linux64/cpp/haxe/DefaultAssetLibrary.hx:443: lines 443-459 : Field list overloads parent class with different or incomplete type
    export/linux64/cpp/haxe/DefaultAssetLibrary.hx:443: lines 443-459 : type : openfl.AssetType -> Array<String> should be type : String -> Array<String>
    export/linux64/cpp/haxe/DefaultAssetLibrary.hx:443: lines 443-459 : openfl.AssetType should be String
    export/linux64/cpp/haxe/DefaultAssetLibrary.hx:462: lines 462-492 : Field loadBitmapData is declared 'override' but doesn't override any field
    export/linux64/cpp/haxe/ApplicationMain.hx:205: characters 2-7 : Field get_stage is declared 'override' but doesn't override any field

Please note that running:

    openfl test linux

works as expected.

I'm using OpenFL version 3.1.0 and HaxeFlixel version 3.3.8.

Am I missing something?

Thanks in advance,
Andrea

**Comment by jeremyfa** [comment]
Having the same issue with latest flixel/openfl/lime, reproduced with the Atom lime plugin.

Seems like the `-cp export/*` is messing up the lime display command.

**Comment by jgranick** [comment]
OpenFL is designed to provide code completion for the new code, not for -Dlegacy. Perhaps there's a way to patch the legacy ApplicationMain/DefaultAssetLibrary templates for #if display

**Comment by jeremyfa** [comment]
Well, currently, the Atom lime plugin is using the `lime display` hxml output for both autocomplete and linting. Autocomplete works fine but linting doesn't.

The linting is just running a normal haxe compilation with the hxml arguments taken from `lime display` (and ensure there is a `-no-output` arg). But maybe there is a better way to achieve this? (like a `lime build` command with some kind of `no output` argument?)
