### ISSUE TITLE
Unwanted Sprite size results when using Tilesheet in native target

### ISSUE THREAD

**Issue by tienery** [openfl/openfl#737]
When using Flash, the result of using a Tilesheet to draw to the graphics component of any Sprite object results (in the following example) in [this](http://prntscr.com/7po54r).

Using the same code, the following results in native targets results in [this](http://prntscr.com/7po5j9).

Here is the subject code:

http://pastebin.com/RhApqmMc

**Comment by mrcdk** [comment]
Using `drawTiles()` on `next` will make the object return the size of the stage

**Comment by jgranick** [comment]
Fixed :smile:
