### ISSUE TITLE
Haxe(OpenFL)+Nape - strange movement

### ISSUE THREAD

**Issue by scorp2007** [openfl/openfl#738]
I throw a rectangle 4 squares and rectangles (Monster) continues to move ... From what it is and how to remove it? All the friction materials are at 0. speaking through a translator, sorry. I hope you can help me, i use Haxe(OpenFL)+Nape, target - HTML5.

 Here's the video: https://www.screenr.com/EheN

 Thank.

**Comment by MSGhero** [comment]
Friction should be bigger than 0.

**Comment by scorp2007** [comment]
Thanks :)
