### ISSUE TITLE
version 3.1.1 Loader bug

### ISSUE THREAD

**Issue by lovedna** [openfl/openfl#740]
on html5 target
3.1.1 Loader can not load image with the function load and loadBytes
must be BackgroundWorker can't dispatch complete event

neko and windows target  is ok

**Comment by jgranick** [comment]
Thank you! I'm sorry for the regression, this change in Lime has just fixed the issue:

https://github.com/openfl/lime/commit/233447d6c0b7ce2e6b3d9f7f13c18db387cc1871

I'll have to think more about whether there should be an "auto-complete" behavior in BackgroundWorker (for simplicity) or not. In cases like Loader, though, it obviously can't assume it's complete until the data is finished downloading :smile:

Thanks!
