### ISSUE TITLE
[Android] Image not visible

### ISSUE THREAD

**Issue by scorp2007** [openfl/openfl#742]
I'm trying to compile a simple program for android and it's not working. The text is displayed and the pictures does NOT appear, why? And you call OpenFL cross platform engine, which can not even make the working APK with 2 lines of code !? I can imagine how many problems with large projects.
P.S.: I tested on a real device

	public function new() 
	{
		super();
		//
		var scoreFormat:TextFormat = new TextFormat("Tahoma", 12, 0xFFFFFF, true);
		scoreFormat.align = TextFormatAlign.LEFT;	
		text1 = new TextField();
		text1.width = 200;
		text1.y = 10;
		text1.x = 10;
		text1.text = "DDDDDDDDDDDDDDDDDDDDDD";
		text1.defaultTextFormat = scoreFormat;
		addChild(text1);
		//
		var spr = new Sprite();
		var img = new Bitmap(Assets.getBitmapData("img/vrag1.png"));
		spr.addChild(img);
		spr.x = 50;
		spr.y = 50;
		addChild(spr);
		//
		var spr = new Sprite();
		var img = new Bitmap(Assets.getBitmapData("img/image.jpg"));
		spr.addChild(img);
		spr.x = 150;
		spr.y = 50;
		addChild(spr);
		// Assets:
		// openfl.Assets.getBitmapData("img/assetname.jpg");
	}

**Comment by jgranick** [comment]
Does the "DisplayingABitmap" sample work for you?

Also, does your code work if you use `openfl test android -Dlegacy` instead of `openfl test android`?

Thanks!

**Comment by scorp2007** [comment]
DisplayingABitmap - the picture is not displayed on my device.

"openfl test android -Dlegacy" - the code is compiled and pictures are displayed like, and how to specify this when I compile a project in FlashDevelop?

Thanks.

**Comment by jgranick** [comment]
Strange, I wonder if the device prints any type of error in the ADB output

The target drop-down in FlashDevelop is actually editable, I change it to say something like "android -Dlegacy", then you will be able to choose not only between the traditional targets (flash, html5, windows, etc) but also choose between legacy or non-legacy output quickly :)

**Comment by scorp2007** [comment]
I do not know where to look output ADB, that's the outputthe command line when I compile the file. Something's wrong here? Thank you for your answers :)

K/sources/cxx-stl/gnu-libstdc++/4.4.3/libs/armeabi/include" -DHXCPP_VISIT_ALLOCS
 -DHXCPP_API_LEVEL=321 -ID:/HaxeToolkit/haxe/lib/hxcpp/3,2,102/include -Iinclude
 -fpic -fvisibility=hidden -ffunction-sections -funwind-tables -fstack-protector
 -fno-short-enums "-D_LINUX_STDDEF_H " -Wno-psabi -D__ARM_ARCH_5__ -D__ARM_ARCH_
5T__ -D__ARM_ARCH_5E__ -D__ARM_ARCH_5TE__ -march=armv7-a -mfpu=vfpv3-d16 -mfloat
-abi=softfp -fomit-frame-pointer -fexceptions -fno-strict-aliasing -finline-limi
t=10000 -DANDROID=ANDROID -DHX_ANDROID -DHXCPP_ANDROID_PLATFORM=14 -Wa,--noexecs
tack -O2 -DNDEBUG -c -x c++ -Wno-invalid-offsetof -frtti D:/HaxeToolkit/haxe/lib
/hxcpp/3,2,102/src/Dynamic.cpp -oobj/android-v7/82b53a69_Dynamic.obj
arm-linux-androideabi-g++ -D_CRT_SECURE_NO_DEPRECATE -DHX_UNDEFINE_H "--sysroot=
C:\Development\Android NDK/platforms/android-9/arch-arm" "-IC:\Development\Andro
id NDK/sources/cxx-stl/gnu-libstdc++/4.4.3/include" "-IC:\Development\Android ND
K/sources/cxx-stl/gnu-libstdc++/4.4.3/libs/armeabi/include" -DHXCPP_VISIT_ALLOCS
 -DHXCPP_API_LEVEL=321 -ID:/HaxeToolkit/haxe/lib/hxcpp/3,2,102/include -Iinclude
 -fpic -fvisibility=hidden -ffunction-sections -funwind-tables -fstack-protector
 -fno-short-enums "-D_LINUX_STDDEF_H " -Wno-psabi -D__ARM_ARCH_5__ -D__ARM_ARCH_
5T__ -D__ARM_ARCH_5E__ -D__ARM_ARCH_5TE__ -march=armv7-a -mfpu=vfpv3-d16 -mfloat
-abi=softfp -fomit-frame-pointer -fexceptions -fno-strict-aliasing -finline-limi
t=10000 -DANDROID=ANDROID -DHX_ANDROID -DHXCPP_ANDROID_PLATFORM=14 -Wa,--noexecs
tack -O2 -DNDEBUG -c -x c++ -Wno-invalid-offsetof -frtti D:/HaxeToolkit/haxe/lib
/hxcpp/3,2,102/src/Enum.cpp -oobj/android-v7/82b53a69_Enum.obj
arm-linux-androideabi-g++ -D_CRT_SECURE_NO_DEPRECATE -DHX_UNDEFINE_H "--sysroot=
C:\Development\Android NDK/platforms/android-9/arch-arm" "-IC:\Development\Andro
id NDK/sources/cxx-stl/gnu-libstdc++/4.4.3/include" "-IC:\Development\Android ND
K/sources/cxx-stl/gnu-libstdc++/4.4.3/libs/armeabi/include" -DHXCPP_VISIT_ALLOCS
 -DHXCPP_API_LEVEL=321 -ID:/HaxeToolkit/haxe/lib/hxcpp/3,2,102/include -Iinclude
 -fpic -fvisibility=hidden -ffunction-sections -funwind-tables -fstack-protector
 -fno-short-enums "-D_LINUX_STDDEF_H " -Wno-psabi -D__ARM_ARCH_5__ -D__ARM_ARCH_
5T__ -D__ARM_ARCH_5E__ -D__ARM_ARCH_5TE__ -march=armv7-a -mfpu=vfpv3-d16 -mfloat
-abi=softfp -fomit-frame-pointer -fexceptions -fno-strict-aliasing -finline-limi
t=10000 -DANDROID=ANDROID -DHX_ANDROID -DHXCPP_ANDROID_PLATFORM=14 -Wa,--noexecs
tack -O2 -DNDEBUG -c -x c++ -Wno-invalid-offsetof -frtti D:/HaxeToolkit/haxe/lib
/hxcpp/3,2,102/src/Math.cpp -oobj/android-v7/82b53a69_Math.obj
arm-linux-androideabi-g++ -D_CRT_SECURE_NO_DEPRECATE -DHX_UNDEFINE_H "--sysroot=
C:\Development\Android NDK/platforms/android-9/arch-arm" "-IC:\Development\Andro
id NDK/sources/cxx-stl/gnu-libstdc++/4.4.3/include" "-IC:\Development\Android ND
K/sources/cxx-stl/gnu-libstdc++/4.4.3/libs/armeabi/include" -DHXCPP_VISIT_ALLOCS
 -DHXCPP_API_LEVEL=321 -ID:/HaxeToolkit/haxe/lib/hxcpp/3,2,102/include -Iinclude
 -fpic -fvisibility=hidden -ffunction-sections -funwind-tables -fstack-protector
 -fno-short-enums "-D_LINUX_STDDEF_H " -Wno-psabi -D__ARM_ARCH_5__ -D__ARM_ARCH_
5T__ -D__ARM_ARCH_5E__ -D__ARM_ARCH_5TE__ -march=armv7-a -mfpu=vfpv3-d16 -mfloat
-abi=softfp -fomit-frame-pointer -fexceptions -fno-strict-aliasing -finline-limi
t=10000 -DANDROID=ANDROID -DHX_ANDROID -DHXCPP_ANDROID_PLATFORM=14 -Wa,--noexecs
tack -O2 -DNDEBUG -c -x c++ -Wno-invalid-offsetof -frtti D:/HaxeToolkit/haxe/lib
/hxcpp/3,2,102/src/String.cpp -oobj/android-v7/82b53a69_String.obj
arm-linux-androideabi-g++ -olibApplicationMain-v7.so -frtti -nostdlib -Wl,-share
d,-Bsymbolic -Wl,--no-undefined -Wl,-z,noexecstack "--sysroot=C:\Development\And
roid NDK/platforms/android-9/arch-arm" "-LC:\Development\Android NDK/platforms/a
ndroid-9/arch-arm/usr/lib" @obj/android-v7/all_objs "C:\Development\Android NDK/
sources/cxx-stl/gnu-libstdc++/4.4.3/libs/armeabi/libgnustl_static.a" "C:\Develop
ment\Android NDK/platforms/android-9/arch-arm/usr/lib/crtbegin_so.o" "C:\Develop
ment\Android NDK/toolchains/arm-linux-androideabi-4.4.3/prebuilt/windows/lib/gcc
/arm-linux-androideabi/4.4.3/libgcc.a" "C:\Development\Android NDK/platforms/and
roid-9/arch-arm/usr/lib/libc.so" "C:\Development\Android NDK/platforms/android-9
/arch-arm/usr/lib/libm.so" -llog -ldl
C:/Development/Android NDK/toolchains/arm-linux-androideabi-4.4.3/prebuilt/windo
ws/bin/../lib/gcc/arm-linux-androideabi/4.4.3/../../../../arm-linux-androideabi/
bin/ld.exe: Warning: C:\Development\Android NDK/platforms/android-9/arch-arm/usr
/lib/crtbegin_so.o: Unknown EABI object attribute 44
arm-linux-androideabi-strip libApplicationMain-v7.so
Buildfile: D:\HTML5\Herovig\bin\android\bin\build.xml

-set-mode-check:

-set-debug-files:

-check-env:
 [checkenv] Android SDK Tools Revision 24.3.3
 [checkenv] Installed at C:\Development\Android SDK

-setup:
     [echo] Project Name: Herovig
  [gettype] Project Type: Application

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:

-build-setup:
[getbuildtools] Using latest Build Tools: 19.1.0
     [echo] Resolving Build Target for Herovig...
[gettarget] Project Target:   Android 4.1.2
[gettarget] API level:        16
     [echo] ----------
     [echo] Creating output directories if needed...
    [mkdir] Created dir: D:\HTML5\Herovig\bin\android\bin\bin\rsObj
    [mkdir] Created dir: D:\HTML5\Herovig\bin\android\bin\bin\rsLibs
     [echo] ----------
     [echo] Resolving Dependencies for Herovig...
[dependency] Library dependencies:
[dependency]
[dependency] ------------------
[dependency] Ordered libraries:
[dependency]
[dependency] ------------------
     [echo] ----------
     [echo] Building Libraries with 'debug'...

nodeps:

-set-mode-check:

-set-debug-files:

-check-env:
 [checkenv] Android SDK Tools Revision 24.3.3
 [checkenv] Installed at C:\Development\Android SDK

-setup:
     [echo] Project Name: OpenFLExtension
  [gettype] Project Type: Android Library

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:

-build-setup:
[getbuildtools] Using latest Build Tools: 19.1.0
     [echo] Resolving Build Target for OpenFLExtension...
[gettarget] Project Target:   Android 4.1.2
[gettarget] API level:        16
[gettarget] WARNING: No minSdkVersion value set. Application will install on all
 Android versions.
     [echo] ----------
     [echo] Creating output directories if needed...
     [echo] ----------
     [echo] Resolving Dependencies for OpenFLExtension...
[dependency] Library dependencies:
[dependency] No Libraries
[dependency]
[dependency] ------------------

-code-gen:
[mergemanifest] Found Deleted Target File
[mergemanifest] Merging AndroidManifest files into one.
[mergemanifest] Manifest merger disabled. Using project manifest only.
     [echo] Handling aidl files...
     [aidl] No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
     [aapt] Found new input file
     [aapt] Generating resource IDs...
     [echo] ----------
     [echo] Handling BuildConfig class...
[buildconfig] No need to generate new BuildConfig.

-pre-compile:

-compile:
    [javac] Compiling 5 source files to D:\HTML5\Herovig\bin\android\bin\deps\ex
tension-api\bin\classes
    [javac] warning: [options] source value 1.5 is obsolete and will be removed
in a future release
    [javac] warning: [options] target value 1.5 is obsolete and will be removed
in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use
-Xlint:-options.
    [javac] 3 warnings
     [echo] Creating library output jar file...
      [jar] Building jar: D:\HTML5\Herovig\bin\android\bin\deps\extension-api\bi
n\classes.jar

-post-compile:

-obfuscate:

-dex:
     [echo] Library project: do not convert bytecode...

-crunch:
   [crunch] Crunching PNG Files in source dir: D:\HTML5\Herovig\bin\android\bin\
deps\extension-api\res
   [crunch] To destination dir: D:\HTML5\Herovig\bin\android\bin\deps\extension-
api\bin\res
   [crunch] Crunched 0 PNG files to update cache

-package-resources:
     [echo] Library project: do not package resources...

-package:
     [echo] Library project: do not package apk...

-post-package:

-do-debug:
     [echo] Library project: do not create apk...
[propertyfile] Updating property file: D:\HTML5\Herovig\bin\android\bin\deps\ext
ension-api\bin\build.prop
[propertyfile] Updating property file: D:\HTML5\Herovig\bin\android\bin\deps\ext
ension-api\bin\build.prop
[propertyfile] Updating property file: D:\HTML5\Herovig\bin\android\bin\deps\ext
ension-api\bin\build.prop
[propertyfile] Updating property file: D:\HTML5\Herovig\bin\android\bin\deps\ext
ension-api\bin\build.prop

-post-build:

debug:

-code-gen:
[mergemanifest] Found Deleted Target File
[mergemanifest] Merging AndroidManifest files into one.
[mergemanifest] Merging manifests from project and 1 libraries.
     [echo] Handling aidl files...
     [aidl] No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
     [aapt] Found Deleted Target File
     [aapt] Generating resource IDs...
     [echo] ----------
     [echo] Handling BuildConfig class...
[buildconfig] Generating BuildConfig class.

-pre-compile:

-compile:
    [javac] Compiling 5 source files to D:\HTML5\Herovig\bin\android\bin\bin\cla
sses
    [javac] warning: [options] source value 1.5 is obsolete and will be removed
in a future release
    [javac] warning: [options] target value 1.5 is obsolete and will be removed
in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use
-Xlint:-options.
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 3 warnings

-post-compile:

-obfuscate:

-dex:
      [dex] input: D:\HTML5\Herovig\bin\android\bin\bin\classes
      [dex] input: D:\HTML5\Herovig\bin\android\bin\deps\extension-api\bin\class
es.jar
      [dex] Pre-Dexing D:\HTML5\Herovig\bin\android\bin\deps\extension-api\bin\c
lasses.jar -> classes-1e8df1f607b70502c6f3c44031a665e1.jar
      [dex] Found Deleted Target File
      [dex] Converting compiled files and external libraries into D:\HTML5\Herov
ig\bin\android\bin\bin\classes.dex...
       [dx] Merged dex A (41 defs/53.8KiB) with dex B (5 defs/5.6KiB). Result is
 46 defs/69.0KiB. Took 0.1s

-crunch:
   [crunch] Crunching PNG Files in source dir: D:\HTML5\Herovig\bin\android\bin\
res
   [crunch] To destination dir: D:\HTML5\Herovig\bin\android\bin\bin\res
   [crunch] Crunched 0 PNG files to update cache

-package-resources:
     [aapt] Creating full resource package...
     [aapt] Warning: AndroidManifest.xml already defines debuggable (in http://s
chemas.android.com/apk/res/android); using existing value in manifest.

-package:
[apkbuilder] Current build type is different than previous build: forced apkbuil
der run.
[apkbuilder] Creating Herovig-debug-unaligned.apk and signing it with a debug ke
y...

-post-package:

-do-debug:
 [zipalign] Running zip align on final apk...
     [echo] Debug Package: D:\HTML5\Herovig\bin\android\bin\bin\Herovig-debug.ap
k
[propertyfile] Creating new property file: D:\HTML5\Herovig\bin\android\bin\bin\
build.prop
[propertyfile] Updating property file: D:\HTML5\Herovig\bin\android\bin\bin\buil
d.prop
[propertyfile] Updating property file: D:\HTML5\Herovig\bin\android\bin\bin\buil
d.prop
[propertyfile] Updating property file: D:\HTML5\Herovig\bin\android\bin\bin\buil
d.prop

-post-build:

debug:

BUILD SUCCESSFUL
Total time: 26 seconds
/system/bin/sh: can't create C:\Users\idol\AppData\Local\Temp/temp_5930337: No s
uch file or directory
433 KB/s (4606763 bytes in 10.368s)
        pkg: /data/local/tmp/Herovig-debug.apk
Success
Starting: Intent { act=android.intent.action.MAIN cmp=com.BerezaGames.Herovig/.M
ainActivity }
--------- beginning of /dev/log/system
--------- beginning of /dev/log/main
