### ISSUE TITLE
[AS3 -> OpenFL] Help translate Obj["string"+i]

### ISSUE THREAD

**Issue by scorp2007** [openfl/openfl#744]
Hello, help me translate this ActionScript3 code to OpenFL:

mySharedObject.data['lev'+tlevel]=1000;

How will it be on OpenFL? Thanks.

**Comment by jgranick** [comment]
Try:

Reflect.setField (mySharedObject.data, "lev" + tlevel, 1000);

Have you seen http://community.openfl.org? It might be a better place for questions :smile:

**Comment by scorp2007** [comment]
Oh, thank you, Joshua, it works. Well in the future I will be there to ask :)
