### ISSUE TITLE
TouchEvent bug

### ISSUE THREAD

**Issue by lovedna** [openfl/openfl#745]
neko target

touchPointID is a increase number 
everytime touchPointID will add 1 number when TouchEvent.TOUCH_BEGIN dispatched

and i restart the application the touchPointID is the last number,maybe the touchPointID  saved in A file

i just test it in neko and html5 target and html5 is ok

by theway ,i can not build windows target ,a lot error like this:
D:/haxelib/openfl/3,1,2/openfl/display3D/textures/Texture.hx:123: characters 2-38 : Invalid null expression: null.id

the error line code is : GL.bindTexture (GL.TEXTURE_2D, null);

**Comment by jgranick** [comment]
I believe the touchpoint ID is given by SDL (from the operating system?) and is not intended to be used as anything other than a unique ID. It may or may not have some order to it.

I think that error you are having may be fixed in more recent versions of OpenFL?

**Comment by lovedna** [comment]
hi,this issue comeback
