### ISSUE TITLE
openfl.net.Socket (ver 3.1.1) - should check whether can read before call _socket.input.readBytes() ?

### ISSUE THREAD

**Issue by joelam789** [openfl/openfl#747]
"openfl.net.Socket" (openfl version: 3.1.1)  does not work when build target is windows ... 
in function onFrame() , should check whether can read before call _socket.input.readBytes() ?

**Comment by joelam789** [comment]
Updated to 3.1.2,  the issue still exists

**Comment by joelam789** [comment]
Hello~
Can somebody help me?
Updated to 3.2.0, but the issue still exists.
I used  openfl.net.WebSocket  in my current project.
But it could not work when built to Windows exec file because of the issue of openfl.net.Socket.
I know i can fix it myself by modifying the source code of openfl.net.Socket ... 
but i really wouldn't like to do that.
Hope someone of the developers could have a look, it should not be difficult to fix the issue.

**Comment by Hasufel** [comment]
Hi joelam, maybe you could share with us a simple snippet of what you're doing?
Have you tried sys.net.Socket ?

**Comment by joelam789** [comment]
oh... sorry, my bad :p 
maybe my case is not a simple one.
I tested the basic sample code of openfl-websocket, it works well both in SWF & Windows exe format.
But in my case, it failed when built to Windows exe file.
Here is the code of my case:

    private function clickLogin():Void
	{
		var loginmsg =  { 
							playerName: "p0", 
							loginToken: "1234", 
							key: "" 
						};
		
		var httpRequest = new haxe.Http("http://192.168.0.101:8080/login/login.php");
		for (fname in Reflect.fields(loginmsg))
		{
			httpRequest.setParameter(fname, Reflect.field(loginmsg, fname));
		}
		
		httpRequest.onData = function(data:String) {
			
			var msg = haxe.Json.parse(data);
			
			if (msg.error == 0)
			{
				trace("Login OK, Game Server: " + msg.ip + ":" + msg.port);
				
				var ws = new WebSocket("ws://" + msg.ip + ":" + msg.port + "/game");

				ws.onOpen.add(function(evt:Dynamic) {
					
					trace("opened");
					
					var joinmsg =  { 
							msg: "JoinGameServerRequest", 
							player: msg.player, 
							session: msg.session
						};
						
					var strmsg = haxe.Json.stringify(joinmsg);

					ws.sendText(strmsg);
					
				});
				ws.onClose.add(function(evt:Dynamic) {
					trace("closed");
				});
				ws.onError.add(function(evt:String) {
					trace("error");
				});
				ws.onTextPacket.add(function(text:String) {
					trace(text);
				});
				
			}
			else
			{
				trace("Fail to login, error code: " + msg.error);
			}
			
		};
		
		httpRequest.request(true);
	}

**Comment by mumeka** [comment]
I received same issue in openfl 3.2.2. However, this issue seems to be fixed with commit https://github.com/openfl/openfl/commit/f05af93fcd5dad1abe91b7a9302555b7a059fa4c and Socket seems to be working in openfl 3.3.0.

**Comment by joelam789** [comment]
Updated to 3.3.2, but unfortunately it still does not work for me.
Did you test this issue with the code i posted above ?
I don't think it's difficult to reproduce the issue when build to Windows exe format.

Here is my way to fix this issue:

1. open  "openfl.net.Socket.hx"

2. find this line 
l = _socket.input.readBytes(_buf,0,_buf.length);

3. replace it with these two lines:
var r = sys.net.Socket.select([_socket], null, null, 0);
l = r.read[0] == _socket ? _socket.input.readBytes(_buf, 0, _buf.length) : 0;

just for reference, may have a try
