### ISSUE TITLE
Input textfield not working properly in windows legacy

### ISSUE THREAD

**Issue by loudoweb** [openfl/openfl#755]
On flash it's ok but on windows legacy I've got something weird.

When I press on the key **8_\** I should have **_** in my textfield but I've got **8** instead.
When I press SHIFT and the key **8_\**  I should have **8** but I have * instead. I don't even have * in this key :/

![image](https://cloud.githubusercontent.com/assets/165190/8825821/291e892c-3082-11e5-9c99-8fc0a96f1159.png)

Is this a problem of bad support of AZERTY keyboard, or somebody is having the same issue in QWERTY keyboard?

**Comment by tienery** [comment]
https://github.com/openfl/lime/blob/master/legacy/project/src/sdl/SDLStage.cpp#L937-L954

There is also a comment https://github.com/openfl/lime/blob/master/legacy/project/src/sdl/SDLStage.cpp#L946-L947 which says "SDL does not provide unicode on key up" so it may be likely that you need to turn on full unicode support for SDL to capture the key correctly.

Although, I don't know much about the AZERTY layout so I wouldn't be 100% sure.

**Comment by loudoweb** [comment]
Thank you for the details tienery.

It seems that it's already use unicode https://github.com/openfl/lime/blob/master/legacy/project/src/sdl/SDLStage.cpp#L942

**Comment by jgranick** [comment]
Would you mind testing to see if it works properly with the newer OpenFL code?

**Comment by loudoweb** [comment]
Just upgraded openfl and lime.

It works now in **next** :)
but it's not working in **legacy**

**Comment by jgranick** [comment]
SDL 1.2 had key events that attempted to map what ASCII character they represented, as well as the code. However, multiple languages don't map one key to one input value when you look at IMEs and other input methods

SDL 2 divided key and text inputs into different APIs. I don't have an AZERTY keyboard, I would like to know that we handle key codes properly there (and the Flash compatibility code conversion)

I have added support both types of events in the new OpenFL, legacy relies only on keyboard events and not text input events. Adding text input support there would not be impossible, but it's not something I'm interested in doing :smile:

**Comment by loudoweb** [comment]
Totally fair :) Thx for the new code.
