### ISSUE TITLE
[HTML5] Event.ADDED infinitely triggered on addChild

### ISSUE THREAD

**Issue by jonnym1p** [openfl/openfl#757]
lime 2.5.0
openfl 3.1.4
target: HTML5

I am seeing Event.ADDED trigger infinitely when a child is added to the object with the event...

class MySprite extends Sprite {

function new() {
    super();
    addEventListener( Event.ADDED, init );
}

function init( e:Event ) {
   removeEventListener( Event.ADDED, init );
   addChild( someSprite );
}

init is then called infinitely, so it seems adding children is causing Event.ADDED to trigger again (even though the event is being removed and it shouldn't bubble to its parent anyway). If I comment addChild() or addEventListener() (and call init() directly) then the problem doesn't happen. Also, if I change my lib versions back to lime 2.3.3 and openfl 3.0.3 the issue doesn't occur.

I haven't tested other targets than HTML5.

**Comment by jonnym1p** [comment]
Forgot to mention that this all causes the call stack to overflow and crash the app.

**Comment by Hasufel** [comment]
Maybe update to lime 2.5.1 and openfl 3.2.0?

**Comment by jonnym1p** [comment]
Still seeing the same behavior with lime 2.5.1 and openfl 3.2.0.

**Comment by jgranick** [comment]
Thanks! This should be fixed now :smile:
