### ISSUE TITLE
BitmapData.threshold Bug

### ISSUE THREAD

**Issue by amidos2006** [openfl/openfl#760]
I think that's a potential bug in the BitmapData threshold function I tried to remove a certain color using the following code from the image:

    bitmapData.threshold(bitmapData, new Rectangle(0, 0, bitmapData.width, bitmapData.height), new Point(), "==", backColor, 0, 0x00FFFFFF);

but it didn't work frowning going in the code of BitmapData I found that the color and threshold are flipped using these lines:

    threshold = __flipPixel (threshold);
    color = __flipPixel (color);

removing these lines the code worked properly which was a bit weird but I think reversing threshold and color and anding it with the mask will remove some components.

**Comment by larsiusprime** [comment]
can you post the image you were using too? that way we can try to reproduce the effect.

**Comment by jgranick** [comment]
I think this is fixed now. I added a threshold test to the "UsingBitmapData" sample, and made a number of recent fixes

**Comment by amidos2006** [comment]
Okay will check the new OpenFL 3.2.2 as I found I still have version 3.1.4 :) Thanks sorry for that

**Comment by jgranick** [comment]
If you still have issues (or if it works great!) please let me know :smile:

**Comment by amidos2006** [comment]
@jgranick it works great really thanks :+1:
