### ISSUE TITLE
Next compile failed on Linux, XInput2.h missing, requires libxi-dev

### ISSUE THREAD

**Issue by jcward** [openfl/openfl#769]
I'm not sure if OpenFL has a dependency list, but building hxScout in next required me to install `libxi-dev` as I hit this error:

```
Error: In file included from ./lib/sdl/src/video/x11/SDL_x11clipboard.c:28:0:
./lib/sdl/src/video/x11/SDL_x11video.h:41:36: fatal error: X11/extensions/XInput2.h: No such file or directory
```

After installing the lib, it worked fine. On Ubuntu, that's: `sudo apt-get install libxi-dev`

**Comment by ibilon** [comment]
Was that when doing `lime rebuild linux`?

**Comment by jcward** [comment]
Ha, I have no idea what I was doing then. :) I'll just close this.
