### ISSUE TITLE
the URLLoader not work on Android

### ISSUE THREAD

**Issue by githubigssan** [openfl/openfl#772]
URLLoader not work and IoErrorEvent tips "Problem with curl: 6"

openfl version: 3.2.2
lime version: 2.5.2

help...

**Comment by jgranick** [comment]
I just tried the following and it worked:

```haxe
var urlLoader = new URLLoader ();
		urlLoader.addEventListener (Event.COMPLETE, function (_) {
			
			trace (urlLoader.data);
			
		});
		urlLoader.load (new URLRequest ("http://www.google.com"));
```

If you continue to have problems, please feel free to post more details so we can reproduce :smile:
