### ISSUE TITLE
GL.readPixels on windows and  android

### ISSUE THREAD

**Issue by lovedna** [openfl/openfl#775]
i want read color from GLFramebuffer
code:
_colorData = new UInt8Array(4);
GL.readPixels(x, height - y, 1, 1, GL.RGB, GL.UNSIGNED_BYTE, cast  _colorData );

neko and html5 target is ok
but windows and android target _colorData  always [0,0,0,0]

is a bug or the wrong way to get color
help me! thanks

**Comment by GimmickyApps** [comment]
I'd love to know this too, so that I can use it in a cross-platform rendering unit-test.
