### ISSUE TITLE
ColorTransform is "baked in" to bitmap caches

### ISSUE THREAD

**Issue by raggy** [openfl/openfl#777]
The expected behaviour is that the circle fades between red and black. This happens on the flash target or on other targets when the two commented-out lines are uncommented. It behaves the same when `shape` itself is the target of the ColorTransform.

```haxe
package;


import openfl.display.Shape;
import openfl.display.Sprite;
import openfl.events.Event;
import openfl.geom.ColorTransform;


class Main extends Sprite {
	
	
	public function new () {
		
		super ();
		
		var shape = new Shape();
		shape.graphics.beginFill(0xFF0000);
		shape.graphics.drawCircle(100, 100, 25);
		shape.cacheAsBitmap = true;
		addChild(shape);

		addEventListener(Event.ENTER_FRAME, function(e:Event) {

			transform.colorTransform = new ColorTransform(.5 + .5 * Math.sin(haxe.Timer.stamp()));

			// Force bitmap cache to update
			//shape.visible = false;
			//shape.visible = true;

		});
		
	}
	
	
}
```

**Comment by jgranick** [comment]
This is Flash Player's behavior, we aren't in charge of this. I guess `cacheAsBitmap` does include the color transform. Perhaps you could use `bitmapData.draw` and then a color transform on the bitmap?
