### ISSUE TITLE
DisplayObject.transform.matrix doesn't handle negative scales

### ISSUE THREAD

**Issue by jskuse** [openfl/openfl#783]
We use negative scales in transform matrices to flip DisplayObjects along the x and y axis. So, for example -1, 0, 0, 1, 0, 0 would be expected to flip the object horizontally. I've noticed that on native targets flipping things in this manner results in them being upside down. This differs from the established Flash behaviour.

Looking at: https://github.com/openfl/openfl/blob/master/openfl/geom/Transform.hx#L193

This looks like a result of the matrix decomposition you're applying:
```
__displayObject.scaleX = Math.sqrt ((value.a * value.a) + (value.b * value.b));
__displayObject.scaleY = Math.sqrt ((value.c * value.c) + (value.d * value.d));
__displayObject.rotation = Math.atan2 (value.b, value.a) * (180 / Math.PI);
```
Taking our theoretical -1, 0, 0, 1, 0, 0 matrix this will be:
```
x = Math.sqrt(-1 * -1) + Math.sqrt(0 * 0);
y = Math.sqrt(0 * 0) + Math.sqrt(1 * 1);
rot = Math.atan2(0, -1) * (180 / Math.PI);
```
Resulting in:
```
x = 1
y = 1
rot = 180
```

You can compare the flash and native behaviours using the following snippet
```
var t1 = new openfl.display.Sprite();
flash.Lib.current.stage.addChild(t1);
trace (t1.scaleX, t1.rotation); 
t1.transform.matrix = new flash.geom.Matrix(-1, 0, 0, 1, 0, 0);
trace (t1.scaleX, t1.rotation);
```

Native will result in:
```
Main.hx:8: 1,0
Main.hx:10: 1,180
```

Whereas Flash will result in:
```
Main.hx:8 1,0
Main.hx:10: -1,0
```

**Comment by jgranick** [comment]
Fixed in https://github.com/openfl/openfl/commit/97471551186f0ad6cb4b1ffb6ae3fb28ef3856b7 :smile:
