### ISSUE TITLE
HTML5 target text field size render issue

### ISSUE THREAD

**Issue by jonnym1p** [openfl/openfl#785]
openfl 3.2.2
lime 2.5.2
iOS Safari

Am seeing an issue where the bottom of my text fields are getting cut off (not rendering) while using TextFieldAutoSize.LEFT. This is happening for all characters that drop below the line, such as 'p' or 'g'. If I increase their y position, they get further cut off by that offset. So the bottom of the letter 'a' will start getting cut off along with 'p' now getting more cut off. This issue ONLY seems to occur on iOS Safari.

myTxt.height is always reporting exactly 4 px larger than myTxt.textHeight (and same for width) on all platforms. Rendering looks good on all platforms except iOS Safari where it is getting cut off.

If I remove autoSize = LEFT and manually set the field's height to textHeight, I see the same issue.

It seems to me that width/height and/or textWidth/textHeight are reporting bad values (at least on iOS Safari). It is also weird that if I increase the y position, it shifts the text further into the cut-off zone, almost as if there's a tight rect that isn't updating with the actual content or property changes. Maybe related to those text field bounds updates?

**Comment by larsiusprime** [comment]
There were some recent commits that addressed this, when did you last pull?

**Comment by jonnym1p** [comment]
Just with the 2.5.2 release. When I try latest master openfl+lime it fails to compile.

**Comment by larsiusprime** [comment]
Cool, there's a good chance the next release (which is probably coming soon now that we finally stabilized text) will fix this, but I'll let @jgranick confirm for sure.

**Comment by jonnym1p** [comment]
Thanks! You guys rock.

**Comment by jgranick** [comment]
I'm going to close this issue, and we can keep tracking on https://github.com/openfl/openfl/issues/797, thank you! :smile:
