### ISSUE TITLE
TextEngine using width and height before updating

### ISSUE THREAD

**Issue by mcheshkov** [openfl/openfl#789]
TextField.__updateLayout calls TextEngine.update, which updates textWidth and textHeight, and use width and height to update scroll values, i.e.
Then TextField.__updateLayout use textWidth and textHeight to set width and height for autosize.
So values used for TextEngine.update is incorrect, and for simple one-line TextFields with autosize no text is shown (bottomScrollV remains 0, less that scrollV)

Possible workaround is to call __updateLayout twice:

		__layoutDirty = true;
		__updateLayout();
		__layoutDirty = true;
		__updateLayout()

Possible proper solution is to update textWidth/textHeight, then update width/height, then update scroll

**Comment by jgranick** [comment]
Are you using `autoSize` when the text is smaller than the original width, or larger?

I think that if the text was smaller than the field width, the layout will not change. When `wordWrap` is `true` the width is not resized, so `autoSize` is really trimming the width and height values, and should not be changing the `scrollV` at all (though I suppose `scrollH` could be affected?)

Though I suppose if it is expanding the width, that's another issue. Do you have a small sample of code I could use to see what you're seeing?

**Comment by mcheshkov** [comment]
It's expanding:

```haxe
		var tf = new flash.text.TextField();
		trace(tf.height, tf.textHeight, tf.scrollV, tf.bottomScrollV);
		// flash: 100, 0, 1, 1
		// html5: 100, 0, 1, null
		tf.autoSize = flash.text.TextFieldAutoSize.CENTER;
		trace(tf.height, tf.textHeight, tf.scrollV, tf.bottomScrollV);
		// flash: 4, 0, 1, 1
		// html5: 4, 0, 1, null
		tf.text = "text";
		trace(tf.height, tf.textHeight, tf.scrollV, tf.bottomScrollV);
		// flash: 18, 14, 1, 1
		// html5: 18.22, 14.219999999999999, 1, 0

		untyped tf.__layoutDirty = true;
		untyped tf.__updateLayout();
		trace(tf.height, tf.textHeight, tf.scrollV, tf.bottomScrollV);
		// html5: 18.22,14.219999999999999,1,2
```

Notice that after setting text `bottomScrollV` is 0, which cause `CanvasTextField.render` to break on line 214: `if (group.lineIndex > textField.scrollV + textEngine.bottomScrollV - 2) break;` and not render any text at all.

But after second layout update bottomScrollV it's not breaking and rendering that line.

**Comment by jgranick** [comment]
It looks like `bottomScrollV` has been fixed already. I'm testing now, and it looks consistent with Flash here. Please let me know if you see more issues, thanks! :smile:
