### ISSUE TITLE
Socket crash app on android x86

### ISSUE THREAD

**Issue by AxGord** [openfl/openfl#790]
```<architecture name="x86" if="android" />```
```Fatal signal 11 (SIGSEGV) at 0x7a5ed44f (code=1), thread 15765 (Thread-725)```

**Comment by mumeka** [comment]
Commit https://github.com/openfl/openfl/commit/f05af93fcd5dad1abe91b7a9302555b7a059fa4c seems to fixed the issue, can you try openfl 3.3.0 or above?
