### ISSUE TITLE
HTML5 target text field size render issue

### ISSUE THREAD

**Issue by mtari** [openfl/openfl#797]
openfl 3.3.0
lime 2.5.3
Chrome, Firefox

It seems to me that textWidth/textHeight are reporting bad values (for example เล่นอัตโนมัติ). I tested it with openfl 3.2.2 and it works correctly.

**Comment by jgranick** [comment]
Does this appear to affect only unicode text? Are there issues with ANSI (a-z, 0-9) text that you can tell?

**Comment by jonnym1p** [comment]
Also having an issue with this.

openfl 3.2.2
lime 2.5.2
safari

In Chrome and IE, the text fields look alright as far as their render size goes. They are centered vertically. In Safari, the text is bottom aligned and characters that drop, like g or p, get cut off.

I used the backgroundColor/background properties of TextField to draw the background region to the screen in these cases.

Chrome/IE results:
![chrome_bounds](https://cloud.githubusercontent.com/assets/12087773/9555442/1e121496-4d9b-11e5-85d9-cbac88d4d286.png)

Safari results:
![apple_bounds](https://cloud.githubusercontent.com/assets/12087773/9555446/22987028-4d9b-11e5-9ef6-a305085e8c8e.png)

**Comment by larsiusprime** [comment]
from the looks like it's not taking the descender metric into account, or something?

**Comment by jgranick** [comment]
@jonnym1p Could you take a look at this code? https://github.com/openfl/openfl/blob/master/openfl/_internal/renderer/canvas/CanvasTextField.hx#L225

Does setting this to true in Safari fix it?

**Comment by jonnym1p** [comment]
I believe that line was added after the openfl version that my project was on (it doesn't exist in my source code, but does in openfl 3.3.3). I'll see if I can recompile with openfl's latest so I can modify that condition to true. That said, I use that same regex elsewhere in my code and it seems to work just fine. 

You'll also notice in my above images that the render rect is shifted up, opposed to it just cutting off the descender.

**Comment by jgranick** [comment]
I think this was resolved, if not please open a new issue with some sample code we can use to reproduce :smile:
