### ISSUE TITLE
Automatic NME/OpenFL build by FDBuild is deprecated.

### ISSUE THREAD

**Issue by LouisSong** [openfl/openfl#807]
I have installed :
haxe3.2 
latest openfl and lime 
the i run openfl setup and lime setup.after all have done,I create a new openfl project use flash develop 5.0.1,when i build or run ,i get the infomation：”Automatic NME/OpenFL build by FDBuild is deprecated.“there is noting generate in lib directory.(any taret can get the same error).how can i resolve this problem?

**Comment by Gama11** [comment]
In my experience that's just a warning that shouldn't cause any issues... Or are you having trouble compiling as well?

Either way, if anything this is a FlashDevelop issue.

**Comment by LouisSong** [comment]
yes,it just a warning.I want to get a swf file after click the "run" button,but nothing generate in the lib directory.I guess the warning may be the cause.
