### ISSUE TITLE
OpenFL 3.3.1 HTML5 image smoothing is enabled even when smoothing set to false in Firefox

### ISSUE THREAD

**Issue by Tw1ddle** [openfl/openfl#809]
I am seeing scaled images getting smoothed/blurred when imageSmoothingEnabled is set false on canvas elements when using dev HaxeFlixel with HTML5 canvas rendering.

In the openfl.display.BitmapData draw method I noticed it was setting imageSmoothingEnabled.

```
if (!smoothing) {

	untyped (buffer.__srcContext).imageSmoothingEnabled = false;
			
}
```

 I read about this and it appears that Firefox 40.0.2 doesn't handle the imageSmoothingEnabled flag. See: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingEnabled - so should the code be changed to something like this so that it works for more browsers?

```
if (!bitmap.smoothing) {
	
	untyped (buffer.__srcContext).mozImageSmoothingEnabled = false;
	untyped (buffer.__srcContext).webkitImageSmoothingEnabled = false;
	untyped (buffer.__srcContext).msImageSmoothingEnabled = false;
	untyped (buffer.__srcContext).imageSmoothingEnabled = false;
				
}
```

Setting the moz* flag disabled smoothing as expected in Firefox.

**Comment by jgranick** [comment]
Thanks! Should be fixed :smile:
