### ISSUE TITLE
Full-screen interactive display modes

### ISSUE THREAD

**Issue by jasonsturges** [openfl/openfl#813]
OpenFL API is missing full-screen interactive mode functionality, added in Flash Player 11.3.

Per Flash, [`flash.display.Stage`](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/Stage.html) read-only property [`allowsFullScreenInteractive`](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/Stage.html#allowsFullScreenInteractive) specifies whether the stage allows use of the full screen with text input mode.

[`openfl.display.Stage`](https://github.com/openfl/openfl/blob/master/openfl/display/Stage.hx) does not include the `allowsFullScreenInteractive` property; however, [`openfl.display.StageDisplayStage`](https://github.com/openfl/openfl/blob/master/openfl/display/StageDisplayState.hx) includes the `FULL_SCREEN_INTERACTIVE` mode.

It would be great if OpenFL could return a value whether keyboard interactivity is enabled.

**Comment by jgranick** [comment]
Hi!

Just added it, I assume that it's true right now, because we have no full screen mode with text input disabled, but let me know if it seems like this should be different :smile:
