### ISSUE TITLE
windows target complie error

### ISSUE THREAD

**Issue by lovedna** [openfl/openfl#814]
when i was complie windows target always the same error:
D:/haxelib/openfl/3,3,2/openfl/display3D/textures/Texture.hx:123: characters 2-38 : Invalid null expression: null.id
code line is :
GL.bindTexture (GL.TEXTURE_2D, null);
i change code to:
GL.bindTexture (GL.TEXTURE_2D, cast null);
there's no error

i find windows 10 have this error
windows 7 not have this error

**Comment by Gama11** [comment]
What Haxe version are you on (`haxe -version`)?

**Comment by lovedna** [comment]
sorry,i use a wrong version of haxe
thanks
