### ISSUE TITLE
Mac & Neko (on mac) stage.mouseX/Y erratic readings

### ISSUE THREAD

**Issue by Greg209** [openfl/openfl#815]
When tracing the stage.mouseX and stage.mouseY in an ENTER_FRAME function give erratic data causing problems when acting on that data. This problem certainly is apparent on a Mac targetting CPP and Neko - this is also using 'next' and not '-Dv2'

Example code:

    package;

    import openfl.display.Sprite;
    import openfl.events.Event;
    import openfl.Lib;

    class MouseTest extends Sprite {

    	public function new() {
    		super();

    		Lib.current.stage.addEventListener( Event.ENTER_FRAME, onEnterFrame );
    	}

    	function onEnterFrame( e:Event ) {
    		trace("Stage.mouse:"+stage.mouseX+"/"+stage.mouseY);
    	}
    }

Output (this is just moving the mouse around the window):

MouseTest.hx:16: Stage.mouse:83/47
MouseTest.hx:16: Stage.mouse:83/47
MouseTest.hx:16: Stage.mouse:83/47
MouseTest.hx:16: Stage.mouse:83/47
MouseTest.hx:16: Stage.mouse:83/47
MouseTest.hx:16: Stage.mouse:83/47
MouseTest.hx:16: Stage.mouse:83/47
MouseTest.hx:16: Stage.mouse:83/47
MouseTest.hx:16: Stage.mouse:502.21875/343.313598632812
MouseTest.hx:16: Stage.mouse:502.21875/343.313598632812
MouseTest.hx:16: Stage.mouse:502.21875/343.313598632812
MouseTest.hx:16: Stage.mouse:502.21875/343.313598632812
MouseTest.hx:16: Stage.mouse:502.21875/343.313598632812
MouseTest.hx:16: Stage.mouse:502.21875/343.313598632812
MouseTest.hx:16: Stage.mouse:502.21875/343.313598632812
MouseTest.hx:16: Stage.mouse:83/48
MouseTest.hx:16: Stage.mouse:83/49
MouseTest.hx:16: Stage.mouse:84/50
MouseTest.hx:16: Stage.mouse:85/51
MouseTest.hx:16: Stage.mouse:85/52
MouseTest.hx:16: Stage.mouse:86/54
MouseTest.hx:16: Stage.mouse:517.09375/214.060974121094
MouseTest.hx:16: Stage.mouse:518.328125/215.225219726562
MouseTest.hx:16: Stage.mouse:519.5625/216.400146484375
MouseTest.hx:16: Stage.mouse:520.796875/217.564392089844
MouseTest.hx:16: Stage.mouse:522.046875/218.15185546875
MouseTest.hx:16: Stage.mouse:522.65625/218.739318847656
MouseTest.hx:16: Stage.mouse:523.28125/219.316101074219
MouseTest.hx:16: Stage.mouse:523.28125/219.316101074219
MouseTest.hx:16: Stage.mouse:523.28125/219.316101074219
MouseTest.hx:16: Stage.mouse:523.90625/219.316101074219
MouseTest.hx:16: Stage.mouse:524.515625/220.491027832031
MouseTest.hx:16: Stage.mouse:524.515625/220.491027832031
MouseTest.hx:16: Stage.mouse:525.140625/221.078491210938
MouseTest.hx:16: Stage.mouse:90/58
MouseTest.hx:16: Stage.mouse:527/222.830200195312
MouseTest.hx:16: Stage.mouse:91/58
MouseTest.hx:16: Stage.mouse:91/58
MouseTest.hx:16: Stage.mouse:91/58
MouseTest.hx:16: Stage.mouse:529.46875/224.581909179688
MouseTest.hx:16: Stage.mouse:529.46875/224.581909179688
MouseTest.hx:16: Stage.mouse:529.46875/224.581909179688

The correct values are the integer values, whilst the floating point values are wrong - maybe offset somehow.

**Comment by Greg209** [comment]
It appears that the differences are being triggered by a combination of __onMouse and __onTouch methods being called in Stage.hx.

If you move the mouse into the window from the top-left corner, the mouseX/Y increment normally for a while, via __onMouse then at some point, __onTouch calls seem to kick in.

Here are some details of the stack trace for each.

Stage.hx:1293: __onMouse mouse:87/82 
stack=[FilePos(null,openfl.display.Stage::__onMouse,1293),FilePos(null,openfl.display.Stage::onMouseMove,756),FilePos(null,lime.app.Application::onMouseMove,333),FilePos(null,lime.app.Application::createWindow,182),FilePos(null,lime._backend.native.NativeApplication::handleMouseEvent,58),CFunction,FilePos(null,lime._backend.native.NativeApplication::exec,100),FilePos(null,lime.app.Application::exec,218),FilePos(null,ApplicationMain::create,51),FilePos(null,ApplicationMain::main,138),FilePos(null,sys.io.FileOutput::$statics,1)]

Stage.hx:1448: __onTouch mouse:(x=415.53125, y=284.054565429688) 
stack=[FilePos(null,openfl.display.Stage::__onTouch,1448),FilePos(null,openfl.display.Stage::onTouchStart,877),FilePos(null,lime.app.Application::onTouchStart,465),FilePos(null,lime._backend.native.NativeApplication::handleTouchEvent,58),CFunction,FilePos(null,lime._backend.native.NativeApplication::exec,100),FilePos(null,lime.app.Application::exec,218),FilePos(null,ApplicationMain::create,51),FilePos(null,ApplicationMain::main,138),FilePos(null,sys.io.FileOutput::$statics,1)]

**Comment by Hasufel** [comment]
Stumbled upon this problem some time ago - and discussed it with @jgranick a bit. The ontouch will not trigger 'at some point' but when you touch/release within the active window. Drag your finger from outside the window, then get in without releasing your finger, mouse will work - as soon as you release your finger / put it back, the ontouch prevails and provides with a decay, relative to your finger positionning on the touchpad, and somehow it's added to the mouse values - giving a 'double' pointer. Let's try to fix it :)

**Comment by jgranick** [comment]
Just updated SDL2, could you try and see if it fixes this issue?

**Comment by Hasufel** [comment]
Tested with the updated SDL2 - problem still here on Mac OS X.
