### ISSUE TITLE
Sprite with graphics that have negative coords doesn't receive mouse events

### ISSUE THREAD

**Issue by boblucas** [openfl/openfl#816]
A complete example:
```haxe
package;
import openfl.display.Sprite;
import openfl.events.MouseEvent;

class Main extends Sprite 
{	
	public function new () 
	{
		super ();
		var foo:Sprite = new Sprite();
		foo.x = foo.y = 200;
		foo.graphics.beginFill(0xff0000);
		foo.graphics.drawRect(-100, -100, 200, 200);
		foo.addEventListener(MouseEvent.CLICK, function(event:MouseEvent)
		{
		     trace("click");
		});
		addChild(foo);
	}	
}
```
the click will only show for the bottom right quarter of the square, with positive x and y.
Happens in html5, neko and cpp, didn't test other targets.

**Comment by jgranick** [comment]
Thanks for the test! This is working here. It should be fixed in the latest release, it looks like it was this commit:

https://github.com/openfl/openfl/commit/8f567e42b75a062c9e5cb09f8b0c517a57becfe9#diff-5c046efbf46f21e3672c16d6cabf95afR1205

:smile:
