### ISSUE TITLE
FreeBSD Support

### ISSUE THREAD

**Issue by vyal** [openfl/openfl#820]
Hello, I was successfully able to install Haxe and Neko on FreeBSD 10.2 x86_64. I also installed phaser for my HTML5 game development. But when I try to install OpenFL, there is an issue.
Here are my environment variables:
 ```
HAXE_STD_PATH is "/home/agnis/bin/haxe-3.3.0/std:."
HAXEPATH is "/home/agnis/bin/haxe-3.3.0"
HAXELIB_PATH is "/usr/lib/haxelib"
 ```
haxelib install openfl went smooth. Then I did haxelib run openfl setup, it downloaded and installed lime fine but then crashed with this:
 ```
	Current version is now 2.6.1
Done
Called from lime/system/System.hx line 694
Called from lime/system/System.hx line 371
Called from lime/system/System.hx line 481
Called from lime/system/System.hx line 306
Called from /usr/lib/haxe/std/neko/Lib.hx line 30
Uncaught exception - load.c(237) : Failed to load library : lime.ndll (Shared object "lime.ndll" not found, required by "neko")
 ```

How to compile lime and openfl for FreeBSD x86_64??

**Comment by jgranick** [comment]
It sounds like your Haxe install might not be working properly. By chance, `haxelib path lime` might not be behaving? I'm not sure.

I would recommend (if you haven't tried it) using the script at http://www.openfl.org/download for Linux, or at least checking it out if you'd prefer to run commands yourself. It's the "tried and true" method I've used to install Haxe and Neko on Debian, SuSE, Fedora, Ubuntu, ARCH, etc :smile:

**Comment by vyal** [comment]
Hello, I have been using Haxe on Linux for a time. But FreeBSD remains the Operating System I know the best, so I am slowly moving back to BSD from Linux. I have used Haxe before on Ubuntu and Elementary OS.
Haxe and Haxelib are working very well, as I said I have been using Haxe extern for Phaser whole day.
Problem comes up with OpenFL. Linux ndll wouldn't work with FreeBSD.
When I try to compile it for FreeBSD using method given at https://github.com/openfl/lime/blob/master/README.md#building-from-source , neko starts complaining (std.ndll) about some undefined symbol "WIFEXITED". Given Haxe and Neko are working well and good on FreeBSD and all dependencies given on the how to compile lime page are installed already in FreeBSD, what may be missing and how difficult it may be?

**Comment by vyal** [comment]
```
[agnis@bhagavati ~/Dev]$ haxelib path lime
-L lime/2,6,1/ndll/
/usr/lib/haxelib/lime/2,6,1/
-D lime=2.6.1
```
```
[agnis@bhagavati ~/Dev]$ haxelib path openfl
/usr/lib/haxelib/openfl/3,3,2/
-D openfl=3.3.2
```
Result of haxelib path

**Comment by jgranick** [comment]
Try doing `haxelib dev lime path/to/lime/checkout` and then doing `haxelib run lime rebuild linux` and see what happens

**Comment by vyal** [comment]
```
[agnis@bhagavati ~/Dev]$ haxelib dev lime lime
Development directory set to /usr/home/agnis/Dev/lime
[agnis@bhagavati ~/Dev]$ haxelib run lime rebuild linux
/usr/local/lib/neko/std.ndll: Undefined symbol "WIFEXITED"
```
btw, why rebuilt linux on FreeBSD?

**Comment by jgranick** [comment]
Try running again with `-verbose`

It sounds like Neko is not functioning properly, perhaps Neko needs to be rebuilt?

**Comment by vyal** [comment]
[agnis@bhagavati ~/Dev]$ haxelib dev lime lime
Development directory set to /usr/home/agnis/Dev/lime
[agnis@bhagavati ~/Dev]$ haxelib run lime rebuild linux
/usr/local/lib/neko/std.ndll: Undefined symbol "WIFEXITED"

**Comment by vyal** [comment]
```
[agnis@bhagavati ~/Dev]$ haxelib run lime -verbose rebuild linux
/usr/local/lib/neko/std.ndll: Undefined symbol "WIFEXITED
```

**Comment by jgranick** [comment]
Yeah, sounds like Neko might have to be rebuilt

**Comment by vyal** [comment]
While checkingout neko I didn't use --recursive. That might be issue, rebuilding in a minute..

**Comment by vyal** [comment]
btw, is it necessary to build with gcc? clang wouldn't work? As clang is the default compiler on FreeBSD, but gcc is available too.

**Comment by jgranick** [comment]
I'm not sure, I think most build scripts are set up to use gcc, clang is used for iOS builds, not sure if the arguments would have to be updated to make more targets build with clang

**Comment by vyal** [comment]
Best bet would be building with GCC then

**Comment by vyal** [comment]
oops closed by mistake

**Comment by vyal** [comment]
Recompiled neko with gcc 4.8.4 but same error compiling for FreeBSD. Made hello world program in haxe and compiled to neko. the resulting .n file ran well.

**Comment by vyal** [comment]
Neko test
```
[agnis@bhagavati ~/Dev/neko/test]$ ls
Main.hx		cmp.hxml
[agnis@bhagavati ~/Dev/neko/test]$ haxe cmp.hxml
[agnis@bhagavati ~/Dev/neko/test]$ ls
Hello.n		Main.hx		cmp.hxml
[agnis@bhagavati ~/Dev/neko/test]$ neko Hello.n
Main.hx:3: Hello World
```

**Comment by jgranick** [comment]
std.ndll is used when doing things like `sys.Filesystem` I think, so Neko might work, but perhaps std.ndll is bad?

**Comment by vyal** [comment]
sys.FileSystem test program here:
```
import sys.FileSystem;

class Main {
	
	static function main(){
		if(sys.FileSystem.exists("/usr/local/bin/gcc48")){
			trace("File exists.");
		}
		else {
			trace("File Don't exist");
		}
	}
}
```

Worked fine:
```
[agnis@bhagavati ~/Dev/test/test2]$ haxe -main Main -neko test.n
[agnis@bhagavati ~/Dev/test/test2]$ neko test.n
Main.hx:7: File exists.
```

**Comment by vyal** [comment]
wow, see what happens when I try hxcpp!!
```
[agnis@bhagavati ~/Dev/test/test2]$ haxe -main Main -cpp test
haxelib run hxcpp Build.xml haxe -Dhaxe3="1" -Dhaxe_ver="3.3" -Dhxcpp_api_level="321" -Dsource-header="Generated by Haxe" -I"" -I"./" -I"/home/agnis/bin/haxe-3.3.0/std/cpp/_std/" -I"/home/agnis/bin/haxe-3.3.0/std/"
/usr/local/lib/neko/std.ndll: Undefined symbol "WIFEXITED"
Error: Build failed
```

**Comment by vyal** [comment]
So I think, here I got the problem. The hxcpp don't compile for FreeBSD (Sys.systemName() should return "BSD").
First thing to do now is to compile hxcpp by adding FreeBSD as valid platform....

**Comment by vyal** [comment]
```
[agnis@bhagavati ~/Dev/hxcpp/project]$ neko build.n
Unknown host system: BSD
```
Do you manage/are major contributor in hxcpp too or I should open new issue in hxcpp repository ?

**Comment by vyal** [comment]
I think best for now would be to open a new issue at hxcpp repository and then continue here if some problem persists despite hxcpp.
