### ISSUE TITLE
Sound in html5 only coming through one speaker

### ISSUE THREAD

**Issue by johanvdb** [openfl/openfl#822]
On lime 2.6.1 and openfl 3.3.2, when playing html5 sounds they only come through one of my speakers. This is reproducible via PiratePig. The html5 version exhibits the single channel behaviour, where the neko and native versions plays the sound just fine.

**Comment by johanvdb** [comment]
Seems it is only a chrome issue. Opening up the same html5 app in safari plays the sound correctly. If no-one else has this issue with chrome, feel free to close, it could just be my computer. Interestingly though, youtube and other sound players are not affected in Chrome.

**Comment by Hasufel** [comment]
see https://github.com/openfl/lime/issues/556

**Comment by jgranick** [comment]
Fixed :smile:
