### ISSUE TITLE
HTML5 bug: getpixel caches values on a bitmap

### ISSUE THREAD

**Issue by TerryCavanagh** [openfl/openfl#823]
Hey all,

I'm working on a HTML5 game engine thing powered by OpenFL and hscript! https://github.com/increpare/terrylib_online/issues/239

I ran into this issue earlier today: bitmapdata.getPixel32() isn't working correctly in HTML5. It seems to be caching the first result for given x, y coordinates. Here's an example:

``` haxe
import openfl.display.*;

class Main extends Sprite {
	var bitmap:BitmapData;
	
	function new () {
		super();
		
		bitmap = new BitmapData(16, 16, true, 0);
		
		bitmap.lock();
		getpixeldata(8, 8);
		bitmap.fillRect(bitmap.rect, 0xFFFFFFFF);
		getpixeldata(8, 8);
		bitmap.unlock();
	}
	
	function getpixeldata(x:Int, y:Int) {
		var pixel:Int = bitmap.getPixel32(x, y);
		var a:Int = pixel >> 24 & 0xFF;
		var r:Int = pixel >> 16 & 0xFF;
		var g:Int = pixel >> 8  & 0xFF;
		var b:Int = pixel       & 0xFF;
		
		trace(timescalled, a, r, g, b); 
		timescalled++;
	}
	var timescalled:Int = 1;
}
```

This program creates a bitmapdata object, gets the colour information of a single pixel on it, draws a colour to that bitmapdata, then gets the colour information of the same pixel. In HTML5, getpixel doesn't update.

This program outputs the following in flash:

```
Main.hx:25: 1,0,0,0,0
Main.hx:25: 2,255,255,255,255
```

But incorrectly outputs the following in HTML5: (latest firefox, windows)

```
Main.hx:25: 1,0,0,0,0
Main.hx:25: 2,0,0,0,0
```

In addition, if you comment out the first getpixeldata() call on line 12, the HTML5 console outputs the following:

```
Main.hx:25: 1,255,255,255,255
```

A fix would be nice, but a workaround would be just as good, if you can suggest one! Thanks!

**Comment by larsiusprime** [comment]
Great repro case. What defines is your project using, btw? (If you're using the openfl defaults I presume it would be canvas target, but are you explicitly targeting webgl?)

**Comment by TerryCavanagh** [comment]
Heya!

I'm just using the openfl defaults in this  - gave up on webgl for the time being in the other project! As for other targets, I've not checked CPP, but it's working correctly in both Flash and Neko. It only seems to affect js!

**Comment by larsiusprime** [comment]
Okay, that's good to know. For reference, Neko should have the same behavior as CPP in 99% of cases, so that's the important one to check; Flash just falls through to the Flash player's API and won't necessary expose a bug in our haxe code reimplementing one of its classes. So if it's not happening in Neko but *IS* happening in JS/HTML5 -- that's interesting.

**Comment by TerryCavanagh** [comment]
Nice, thank you very much!
