### ISSUE TITLE
Android. Back key have keyCode 107349

### ISSUE THREAD

**Issue by Omar2002** [openfl/openfl#827]
Hardware key BACK on android have keyCode == 107349 (not 27)
Sample PiratePig do not exit if press Back key

```
actuate: 1.7.2 1.7.3 1.7.5 1.8.0 [1.8.6]
firetongue: 1.0.0 git [dev:E:\Work\my\haxe\lib/firetongue/git]
haxelib_client: [3.2.0-rc.3]
hscript: 2.0.3 2.0.4 [2.0.5]
hxcpp: 3.1.30 3.1.39 3.1.48 [3.2.102]
lime-tools: 1.4.0 1.5.6 [1.5.7]
lime: [2.6.1]
openfl-native: [1.4.0]
openfl-samples: 1.3.0 2.2.0 3.1.0 [3.3.0]
openfl-tools: [1.0.10]
openfl: 1.4.0 2.0.0 2.0.1 2.2.1 3.3.1 [3.3.2]
stablexui: 1.0.17 1.1.1 [1.1.5]
task: [1.0.6]
```

**Comment by jgranick** [comment]
In Lime 2 / OpenFL 3 (without legacy) "APP_CONTROL_BACK" is the code for Android back buttons. I am charging my device, but I added code that should exit on the back button, I'll try and test soon

**Comment by Omar2002** [comment]
Thanks!

**Comment by man2** [comment]
@jgranick 
should be documented somewhere in samples at least
