### ISSUE TITLE
Next: TextField in container with ScrollRect doesn't render

### ISSUE THREAD

**Issue by jcward** [openfl/openfl#838]
This is likely the reason so many elements are missing from the hxScout UI in Next. Tested against OpenFL 3.3.3.

Small testcase: http://onetacoshort.com/temp/ScrollRectTest.zip

Two textfields are in containers, one has a scrollrect, the other doesn't:

```
    cont = new Sprite();
    //cont.scrollRect = new Rectangle(0, 0, 40, 20);
    cont.addChild(make_label("No ScrollRect Hello World!", 14, 0xff0000));
    cont.y = 10;
    addChild(cont);

    cont = new Sprite();
    cont.scrollRect = new Rectangle(0, 0, 80, 20);
    cont.addChild(make_label("ScrollRect Hello World!", 14, 0xff0000));
    cont.y = 100;
    addChild(cont);
```

Works properly in Flash:
![image](https://cloud.githubusercontent.com/assets/2192439/9922520/eafbbf56-5ca6-11e5-8508-4590361aa978.png)

Neko / CPP, the second textfield is simply not there:
![image](https://cloud.githubusercontent.com/assets/2192439/9922527/0437279e-5ca7-11e5-941e-458827781bc7.png)

Note that embedded font or not, doesn't matter.

**Comment by mrcdk** [comment]
Yes, `scrollRect` is broken everywhere. This PR https://github.com/openfl/openfl/pull/828 should fix them.

**Comment by jcward** [comment]
Apparently this is fixed by PR #828.

**Comment by jcward** [comment]
@mrcdk awesome, great work!

**Comment by jcward** [comment]
Joshua said #828 was pulled, so I'm closing this.
