### ISSUE TITLE
Input TextField: caret doesn't appear on focus until textfield contains a character

### ISSUE THREAD

**Issue by Gama11** [openfl/openfl#844]
``` haxe
package;

import openfl.display.Sprite;
import openfl.text.TextField;
import openfl.text.TextFieldType;

class Main extends Sprite 
{
    public function new() 
    {
        super();

        var textField = new TextField();
        textField.type = TextFieldType.INPUT;
        textField.x = textField.y = 10;
        addChild(textField);
    }
}
```

In **Flash**,  clicking the `TextField` to give it focus makes a blinking caret appear. `stage.focus = textField;` has the same effect.

In **Neko Legacy**, the clicking behavior matches, but setting the focus programatically doesn't work at all.

In **Neko Next** and **HTML5**, neither method makes a caret appear - it only does until the textfield  contains at least one character. Setting the focus programatically works though (able to input text immediately).

Tested with Haxe 3.2.0, OpenFL 3.3.3 and Lime 2.6.2.

**Comment by jgranick** [comment]
This should be fixed

https://github.com/openfl/openfl/commit/f49508560ac3d30d2b806459739d48cf455ef80a
