### ISSUE TITLE
Inconsistent behavior of invalid window background colors

### ISSUE THREAD

**Issue by Gama11** [openfl/openfl#845]
`<window background="#ffffff" />` produces a white background on Flash, Neko Next, Neko Legacy and HTML5.

Adding another `f` (so 7x `f` in total) to that, making the color value exceed the RGB space,  still results in a white background on Flash, Neko Next and Neko Legacy, but a black one on HTML5.

Ideally, the behavior here is consistent across all targets.

Tested with Haxe 3.2.0, OpenFL 3.3.3 and Lime 2.6.2.

**Comment by ibilon** [comment]
Couldn't compile on flash with 7 `f`,
```
Called from ? line 1
Called from CommandLineTools.hx line 1400
Called from CommandLineTools.hx line 25
Called from a C function
Called from CommandLineTools.hx line 126
Called from CommandLineTools.hx line 619
Called from lime/project/PlatformTarget.hx line 70
Called from lime/tools/platforms/FlashPlatform.hx line 260
Called from lime/tools/helpers/FlashHelper.hx line 872
Called from lime/tools/helpers/FlashHelper.hx line 685
Called from format/swf/Writer.hx line 59
Called from format/swf/Writer.hx line 1269
Called from /usr/share/haxe/std/haxe/io/Output.hx line 204
```

We should validate that in the project file reader.

**Comment by Gama11** [comment]
Hm, intersting, getting the same behavior now. This must've changed...

**Comment by jgranick** [comment]
I cannot replicate this on Flash or HTML5, so I guess this is no longer issue
