### ISSUE TITLE
Incorrect resize when Android apps button clicked

### ISSUE THREAD

**Issue by mumeka** [openfl/openfl#848]
When device is horizontal and we press "currently open applications" button of android operating system, openfl resizes to portrait window size. However when we return to app, application is still in the landscape view mode. Than we rotate device vertical, app does not resize because it is already in portrait mode.

Example:
Application is landscape at (1000x600) resolution.
We click "currently open applications" button.
Openfl debugging tells us resize happened with (600x1000) resolution. (this is the issue, it should  not be happening, we did not rotated device, we only clicked an operating system button)
We select our app from open applications.
Application is still in the landscape mode, however rendering is in portrait mode due to wrong resize.
We rotate device and operating system buttons change position and we understand portrait mode activated. However our application does not trigger resize because it did already before.

At another device issue triggers when device is vertical and does not trigger when device horizontal.

**Comment by jgranick** [comment]
I think this is fixed, similar to: https://github.com/openfl/openfl/issues/1325
