### ISSUE TITLE
creating an empty graphics is not enough for mouse event triggering

### ISSUE THREAD

**Issue by fserb** [openfl/openfl#850]
There's a regression from 2.5.2/3.2.2 to 2.6.1/3.3.2.
Before, you could do something like:
```
var mysprite = new Sprite();
mysprite.graphics.beginFill (0, 0.0);
mysprite.graphics.drawRect (0, 0, Lib.current.stage.stageWidth, Lib.current.stage.stageHeight);
mysprite.graphics.endFill();
mysprite.mouseChildren = false;
mysprite.addEventListener(MouseEvent.MOUSE_MOVE, function(event: MouseEvent) {
	trace(event.localX, event.localY);
});
```

after 2.6.1/3.3.2, the empty fill is ignored and the mouse events are not triggered. Maybe this was on purpose, but then is there a solution for having a sprite that gets all mouse events without drawing anything?

**Comment by boblucas** [comment]
Set mysprite.alpha to 0 and change the beginFill line to mysprite.graphics.beginFill (0);
That way it does work, it's not identical behaviour to flash, but it's a workable workaround for most cases. When you have a partially transparant Sprite you might need to add some shapes with alpha set to 0.
