### ISSUE TITLE
.wav throws error while embed="true"

### ISSUE THREAD

**Issue by autonomnom** [openfl/openfl#851]
While compiling and using a .wav file in my project as trying to embed that in the output file with embed="true" in the project.xml i get those errors:

```
C:\HaxeToolkit\haxe\std/neko/_std/sys/io/File.hx:30: characters 20-51 : Invalid call
C:\HaxeToolkit\haxe\std/neko/_std/sys/io/File.hx:34: characters 33-49 : Called from
c:\HaxeToolkit\Haxe\lib/openfl/2,0,1/openfl/Assets.hx:1640: characters 19-39 : Called from
c:\HaxeToolkit\Haxe\lib/openfl/2,0,1/openfl/Assets.hx:1787: characters 15-35 : Called from
c:\HaxeToolkit\Haxe\lib/openfl/2,0,1/backends/native/openfl/media/Sound.hx:15: characters 2-11 : Called from
Aborted
Build halted with errors.
```

A friend helped in finding the issue, we tried different openfl versions (3.3.4, 2.0.1, 3.0.8) with different lime versions and in the end with a different .wav file but it's always the same errors.
With .ogg it seems to work.

**Comment by jgranick** [comment]
I added `embed="true"` for PiratePig, but it still worked properly. Do you have a way of bundling a sample project we could use to try and reproduce? What target were you building for? Thanks!

**Comment by christopf** [comment]
I were building for windows/cpp and created a small project with another .wav. Simsalabim, it's working.
So i replaced the small .wav with the bigger one and the problem as mentioned in the op appears again. So i suppose it's a problem of the .wav (or maybe a size problem?)

If you still want to check the project you can get it here:
https://dl.dropboxusercontent.com/u/22796471/wavwav.zip

Both .wav should be created nearly similiar with audacity although the one with the problems came from a friend but i reconfigured it at my place.

**Comment by ibilon** [comment]
@autonomnom if you still have the issue with latest openfl/lime could you reupload the wav file?

**Comment by autonomnom** [comment]
i hadn't the chance to join my project the last months but as chance would have it i have to get it done in the next weeks. i will post back if it occurs again (but i'm not yet sure if the project runs with the newer versions)
