### ISSUE TITLE
Flash MouseEvent stageX and stageY are read only

### ISSUE THREAD

**Issue by vrescobar** [openfl/openfl#853]
Hello,

I need to call a handler which handles a mouse event (followMe) and I want to do it by giving it explicitly the mouse coordinates from the current mouse position.

Because I couldn't find the coordinates of the mouse position outside of a triggered event I prototyped a solution where they are stored. I try to assign them to the MouseEvent object but I find that the code doesn't work on the flash target:

      Cannot access field or identifier stageX for writing

However the same code works in html5 and mobiles without major problems (I assume is the flash implementation of MouseEvent but I don't see any reason why this field can't be override).

Example:

```haxe
        #if mobile
        var me = new MouseEvent(MouseEvent.MOUSE_MOVE);
        me.stageX = stored.x;
        me.stageY = stored.y;
        followMe(me);
        #end
```

A whole running example can be found [here](https://github.com/vrescobar/elm2openfl/blob/master/Events/mouse/tracker/Source/Main.hx) (you can change "Ngon" by rectangle).

**Comment by pozirk** [comment]
Cause in flash MouseEvent stageX and stageY ARE read-only, there is nothing to do with OpenFL.
http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/MouseEvent.html#stageX

**Comment by jgranick** [comment]
You could also use `mouseX` and `mouseY` for objects, or `stage.mouseX` and `stage.mouseY` for an absolute position :smile:

**Comment by vrescobar** [comment]
That still doesn't solve the fact that I can't dispatch a mouse event with custom coordinates. And that is still an inconsistency between platforms.

@pozirk That was not that obvious, especially since I only have read the openfl source code and it works for some platforms.
@jgranick that's nice to get the current position but those are still getters. I wanted to force the code that captured that event :(

**Comment by MSGhero** [comment]
Flash has security restrictions in place so that you can't make your own mouse events. You could hijack the user's mouse and click things, opening up links or saving files to their computer.

**Comment by vrescobar** [comment]
Thanks for the explanation @MSGhero, now everything makes sense (not a bug).
