### ISSUE TITLE
Target Android doesn't trigger event.RESIZE at startup but other targets do

### ISSUE THREAD

**Issue by vrescobar** [openfl/openfl#854]
Hello,

I found an inconsistency: I have some code which initializes the value of objects and corrects positions when the event resize is triggered; because that event is triggered always when the window or program is started they get initialized with the values calculated in the handling function.

However in android this event is not triggered at startup so those objects created me a little bug and they got initialized with their default values (zeroes) until I trigger resize by rotating the screen.

A workaround is possible by creating a separate function to initialize the values and triggering its logic as well in the resize handler.

A small running example can be found [here](https://github.com/vrescobar/elm2openfl/blob/master/Events/mouse/tracker/Source/Main.hx#L18) (you can change "Ngon" by rectangle).

Is reproduce the issue by removing the line 18 which calls the initialize function.

**Comment by jgranick** [comment]
For a while now, we should have a `RESIZE` event that always dispatches at the beginning of the application, similar to Flash :smile:

https://github.com/openfl/openfl/blob/168bf1bd65368dbab172e2c576c81de4c6932614/templates/haxe/ApplicationMain.hx#L208

Thanks again
