### ISSUE TITLE
The drawing coordinates origin point is different depending the target

### ISSUE THREAD

**Issue by vrescobar** [openfl/openfl#855]
Hello,

while drawing on a polygon by using the graphics API (on a Sprite) the origin of the "draw" is inconsistent between platforms when the first action triggered is lineTo.

For example, in html5 and neko the first point on the circuit will be set to the first given one by "lineTo" but on the iOS target the starting point is preset to the already given coordinates x, y of the sprite allocating the graphics.

That means that a regular pentagon drawn inside of a circle which only gives instructions lineTo to the following the vertices, will work as expected in Neko, Flash and html5 but in iOS will create a funny irregular hexagon having an additional vertex in the coordinates of the coordinates x and y of the sprite.

A workaround is possible by just setting up the origin using "moveTo" to the first point.

An example showing the issue is given [here](https://github.com/vrescobar/elm2openfl/blob/master/Elm/graphics/Collage/Ngon.hx#L15); in order to show the issue remove the line 15 which has the moveTo workaround.

**Comment by jgranick** [comment]
Are you using OpenFL legacy on iOS? Perhaps that is the difference? You could try `#if openfl_legacy` around the workaround, and see if that's the only case that needs it

**Comment by vrescobar** [comment]
I can't compile the app unless I activate the legacy flag (independently of the workaround):

haxelib run lime test project.xml ios -j16 -simulator
.
.
.

** BUILD SUCCEEDED **

Launch app on "com.apple.CoreSimulator.SimDeviceType.iPhone-6, 9.0"
2015-09-28 20:54:16.287 ios-sim[31073:6601106] Timeout: 60.000000 second(s)
2015-09-28 20:54:16.346 ios-sim[31073:6601106] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-8201/DVTFoundation/PlugInArchitecture/PlugInManager/DVTPlugInManager.m:257
Details:  Requested but did not find extension point with identifier Xcode.DVTFoundation.DevicePlatformMapping
Object:   <DVTPlugInManager: 0x7f9753440ce0>
Method:   -extensionPointWithIdentifier:
Thread:   <NSThread: 0x7f9753410990>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
Sep 28 20:54:20  Graphics[31143] <Error>: CGContextSaveGState: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.

Sep 28 20:54:20  Graphics[31143] <Error>: CGContextTranslateCTM: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Sep 28 20:54:20  Graphics[31143] <Error>: CGContextRestoreGState: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.

Primitive not found : lime_application_create__1
Primitive not found : lime_application_event_manager_register__2
Primitive not found : lime_application_exec__1
Primitive not found : lime_application_set_frame_rate__2
Primitive not found : lime_gamepad_event_manager_register__2
Primitive not found : lime_key_event_manager_register__2
Primitive not found : lime_mouse_event_manager_register__2
Primitive not found : lime_render_event_manager_register__2
Primitive not found : lime_text_event_manager_register__2
Primitive not found : lime_touch_event_manager_register__2
Primitive not found : lime_window_event_manager_register__2
Primitive not found : lime_mouse_set_cursor__1
Primitive not found : lime_renderer_create__1
Primitive not found : lime_renderer_flip__1
Primitive not found : lime_renderer_get_type__1
Primitive not found : lime_renderer_lock__1
Primitive not found : lime_renderer_make_current__1
Primitive not found : lime_renderer_unlock__1
Primitive not found : lime_window_close__1
Primitive not found : lime_window_create__5
Primitive not found : lime_window_get_height__1
Primitive not found : lime_window_get_id__1
Primitive not found : lime_window_get_width__1
Primitive not found : lime_window_get_x__1
Primitive not found : lime_window_get_y__1
Primitive not found : lime_window_set_enable_text_events__2
Primitive not found : lime_alc_close_device__1
Primitive not found : lime_alc_create_context__2
Primitive not found : lime_alc_destroy_context__1
Primitive not found : lime_alc_get_contexts_device__1
Primitive not found : lime_alc_get_current_context__0
Primitive not found : lime_alc_make_context_current__1
Primitive not found : lime_alc_open_device__1
Primitive not found : lime_alc_process_context__1
Primitive not found : lime_cairo_arc__MULT
Primitive not found : lime_cairo_clip__1
Primitive not found : lime_cairo_close_path__1
Primitive not found : lime_cairo_create__1
Primitive not found : lime_cairo_curve_to__MULT
Primitive not found : lime_cairo_destroy__1
Primitive not found : lime_cairo_fill__1
Primitive not found : lime_cairo_fill_preserve__1
Primitive not found : lime_cairo_get_current_point__1
Primitive not found : lime_cairo_get_target__1
Primitive not found : lime_cairo_has_current_point__1
Primitive not found : lime_cairo_identity_matrix__1
Primitive not found : lime_cairo_in_fill__3
Primitive not found : lime_cairo_in_stroke__3
Primitive not found : lime_cairo_line_to__3
Primitive not found : lime_cairo_move_to__3
Primitive not found : lime_cairo_new_path__1
Primitive not found : lime_cairo_paint__1
Primitive not found : lime_cairo_paint_with_alpha__2
Primitive not found : lime_cairo_pop_group_to_source__1
Primitive not found : lime_cairo_push_group__1
Primitive not found : lime_cairo_rectangle__5
Primitive not found : lime_cairo_restore__1
Primitive not found : lime_cairo_rotate__2
Primitive not found : lime_cairo_save__1
Primitive not found : lime_cairo_scale__3
Primitive not found : lime_cairo_set_antialias__2
Primitive not found : lime_cairo_set_fill_rule__2
Primitive not found : lime_cairo_set_font_face__2
Primitive not found : lime_cairo_set_font_options__2
Primitive not found : lime_cairo_set_font_size__2
Primitive not found : lime_cairo_set_line_cap__2
Primitive not found : lime_cairo_set_line_join__2
Primitive not found : lime_cairo_set_line_width__2
Primitive not found : lime_cairo_set_matrix__2
Primitive not found : lime_cairo_set_miter_limit__2
Primitive not found : lime_cairo_set_operator__2
Primitive not found : lime_cairo_set_source__2
Primitive not found : lime_cairo_set_source_rgb__4
Primitive not found : lime_cairo_set_source_rgba__5
Primitive not found : lime_cairo_set_source_surface__4
Primitive not found : lime_cairo_show_text__2
Primitive not found : lime_cairo_stroke__1
Primitive not found : lime_cairo_stroke_preserve__1
Primitive not found : lime_cairo_transform__2
Primitive not found : lime_cairo_translate__3
Primitive not found : lime_cairo_ft_font_face_create__2
Primitive not found : lime_cairo_font_face_destroy__1
Primitive not found : lime_cairo_font_options_create__0
Primitive not found : lime_cairo_font_options_set_antialias__2
Primitive not found : lime_cairo_font_options_set_hint_metrics__2
Primitive not found : lime_cairo_font_options_set_hint_style__2
Primitive not found : lime_bytes_get_data_pointer__1
Primitive not found : lime_cairo_image_surface_create_for_data__5
Primitive not found : lime_cairo_image_surface_get_height__1
Primitive not found : lime_cairo_image_surface_get_width__1
Primitive not found : lime_cairo_pattern_add_color_stop_rgba__MULT
Primitive not found : lime_cairo_pattern_create_for_surface__1
Primitive not found : lime_cairo_pattern_create_linear__4
Primitive not found : lime_cairo_pattern_create_radial__MULT
Primitive not found : lime_cairo_pattern_create_rgb__3
Primitive not found : lime_cairo_pattern_create_rgba__4
Primitive not found : lime_cairo_pattern_destroy__1
Primitive not found : lime_cairo_pattern_get_matrix__1
Primitive not found : lime_cairo_pattern_set_extend__2
Primitive not found : lime_cairo_pattern_set_matrix__2
Primitive not found : lime_cairo_surface_destroy__1
Primitive not found : lime_cairo_surface_flush__1
Primitive not found : lime_gl_active_texture__1
Primitive not found : lime_gl_attach_shader__2
Primitive not found : lime_gl_bind_buffer__2
Primitive not found : lime_gl_bind_framebuffer__2
Primitive not found : lime_gl_bind_texture__2
Primitive not found : lime_gl_blend_equation__1
Primitive not found : lime_gl_blend_func__2
Primitive not found : lime_gl_buffer_data__5
Primitive not found : lime_gl_buffer_sub_data__5
Primitive not found : lime_gl_clear__1
Primitive not found : lime_gl_clear_color__4
Primitive not found : lime_gl_color_mask__4
Primitive not found : lime_gl_compile_shader__1
Primitive not found : lime_gl_create_buffer__0
Primitive not found : lime_gl_create_program__0
Primitive not found : lime_gl_create_shader__1
Primitive not found : lime_gl_create_texture__0
Primitive not found : lime_gl_disable__1
Primitive not found : lime_gl_disable_vertex_attrib_array__1
Primitive not found : lime_gl_draw_arrays__3
Primitive not found : lime_gl_draw_elements__4
Primitive not found : lime_gl_enable__1
Primitive not found : lime_gl_enable_vertex_attrib_array__1
Primitive not found : lime_gl_get_attrib_location__2
Primitive not found : lime_gl_get_parameter__1
Primitive not found : lime_gl_get_program_parameter__2
Primitive not found : lime_gl_get_shader_info_log__1
Primitive not found : lime_gl_get_shader_parameter__2
Primitive not found : lime_gl_get_uniform_location__2
Primitive not found : lime_gl_link_program__1
Primitive not found : lime_gl_scissor__4
Primitive not found : lime_gl_shader_source__2
Primitive not found : lime_gl_stencil_func__3
Primitive not found : lime_gl_stencil_mask__1
Primitive not found : lime_gl_stencil_op__3
Primitive not found : lime_gl_tex_image_2d__MULT
Primitive not found : lime_gl_tex_parameteri__3
Primitive not found : lime_gl_uniform1f__2
Primitive not found : lime_gl_uniform1i__2
Primitive not found : lime_gl_uniform2f__3
Primitive not found : lime_gl_uniform4f__5
Primitive not found : lime_gl_uniform4fv__2
Primitive not found : lime_gl_uniform_matrix__4
Primitive not found : lime_gl_use_program__1
Primitive not found : lime_gl_vertex_attrib1fv__2
Primitive not found : lime_gl_vertex_attrib2fv__2
Primitive not found : lime_gl_vertex_attrib3fv__2
Primitive not found : lime_gl_vertex_attrib4fv__2
Primitive not found : lime_gl_vertex_attrib_pointer__MULT
Primitive not found : lime_gl_viewport__4
Primitive not found : lime_image_data_util_fill_rect__4
Primitive not found : lime_image_data_util_multiply_alpha__1
Primitive not found : lime_image_data_util_unmultiply_alpha__1
Primitive not found : lime_clipboard_get_text__0
Primitive not found : lime_clipboard_set_text__1
Primitive not found : lime_system_get_directory__3
Primitive not found : lime_system_get_timer__0
Primitive not found : lime_font_get_ascender__1
Primitive not found : lime_font_get_descender__1
Primitive not found : lime_font_get_family_name__1
Primitive not found : lime_font_get_units_per_em__1
Primitive not found : lime_font_load__1
Primitive not found : lime_text_layout_create__3
Primitive not found : lime_text_layout_position__5
Primitive not found : lime_gamepad_get_device_name__1
Primitive not found : lime_bytes_read_file__1
Error Null Function Pointer

**Comment by jgranick** [comment]
Could you check if you have the latest version of OpenFL and Lime? Thanks :smile:

**Comment by vrescobar** [comment]
I think so, at least from haxelib:

openfl: 3.0.1 3.0.2 3.0.6 3.0.8 3.3.1 [3.3.3]
lime: 2.3.1 2.3.2 2.4.3 [2.6.2]

**Comment by Hasufel** [comment]
we're at 3.3.6 for openfl, and 2.6.6 for lime :)

**Comment by vrescobar** [comment]
Wow, thank you for the fast answer. I just updated to the latest versions, and unfortunately something didn't go fine...

- Without the workaround I can compile the example but the mentioned bug is still there while using legacy; see screenshot attached:
<img width="487" alt="screen shot 2015-09-28 at 23 37 02" src="https://cloud.githubusercontent.com/assets/6759126/10149431/e0895df2-6639-11e5-9a97-2d1fd60e04d8.png">

- Now I can compile as well without use -Dlegacy, and the polygons are well formed without the need of the mentioned workaround but something else is broken in relation to coordinates of the ngon sprite and the mouse position, it requires more debug in order to discover what is happening under the cover. A screenshot doesn't show the issue but you can observe it here by yourself by using [this simple example](https://github.com/vrescobar/elm2openfl/tree/master/Events/mouse/stamps) which creates random ngons from class I linked before that manifests the issue. Now when touching the screen (in simulator) the mouse coordinates and the place where the center where the ngon appears is not matching anymore (but with legacy it works as it should); is not in the coordinates 0,0 of the created polygon (so I assume the coordinates is moved a bit down). This latest issue doesn't happen in html5 or flash, just in iOS without legacy flag.

So I think the legacy + workaround is still necessary because of the new introduced bug in the non-legacy implementation. Do you want to report it in a separate bug?

**Comment by vrescobar** [comment]
I verify that there is a separate bug for native (ios at laeast) when compiling without legacy; some additional offset is given to the Y coordianes of the sprite; I open it as a separate issue.
