### ISSUE TITLE
Missing FULLSCREEN value in openfl.events.Event

### ISSUE THREAD

**Issue by graux** [openfl/openfl#858]
The enum field FULLSCREEN is missing in the class openfl.events.Event.
Building the project I get:
 Class<openfl.events.Event> has no field FULLSCREEN

In the old OpenFL documentation the field exists:
http://www.openfl.org/documentation/api/openfl/events/Event.html

Thank you in advance!

**Comment by jgranick** [comment]
I just added `openfl.events.FullScreenEvent` similar to AS3. Does this cover your needs? :smile:
