### ISSUE TITLE
Can't serialize Vector data type when targetting neko

### ISSUE THREAD

**Issue by mikeleeman** [openfl/openfl#864]
when trying to serialize an openfl.Vector or a haxe.ds.Vector, like so:

var positions = new Vector<Position>(5);
var serializer = new Serializer();
serializer.serialize(positions);

it throws an error:

Cannot serialize [null,null,null,null,null]

This error persists when the vector is properly populated with instances. So far the error only happens when targetting neko.  Tried it on cpp and flash, they work.

**Comment by azrafe7** [comment]
As this is probably a haxe/neko issue, I've filed a report there linking to this one.

**Comment by ibilon** [comment]
https://github.com/HaxeFoundation/haxe/issues/4574 answered that Vector cannot be serialized.
