### ISSUE TITLE
TextField, multiple issues

### ISSUE THREAD

**Issue by pozirk** [openfl/openfl#878]
I'm experiencing several issues with TextFIeld:
1. Entering text works on Nexus 7 tablet, but doesn't on Samsung tablet.
   Same for legacy mode.

Nexus 7, can enter text normally, same for flash and windows target:
I have tried basic AddingText sample.
![Image](http://i58.tinypic.com/xqg6rd.png)

Samsung, can delete text, but can't enter it:
![Image](http://i61.tinypic.com/2mmuxvk.png)
1. Filters don't work for text on native platforms:

Flash, glow filter:
![Image](http://i62.tinypic.com/feq87d.png)

Android, filter is not working:
![Image](http://i60.tinypic.com/hv83nb.png)

haxelib list

> actuate: [1.8.6]
> admob-openfl: [0.0.3]
> amazonads-openfl: [0.0.1]
> box2d: [1.2.3]
> extension-admob: [1.4.5]
> extension-amazonads: [0.1.0]
> extension-facebookads: [0.1.0]
> extension-googleplayservices-lib: [1.1.0]
> extension-multiads: [1.1.1]
> extension-share: [2.2.0]
> format: [3.2.0]
> hxcpp: [3.2.180]
> layout: [1.2.1]
> lime-samples: [2.6.0]
> lime: [2.6.8]
> openfl-gps-lib: [1.4.3]
> openfl-samples: 3.3.0 [3.3.1]
> openfl: [3.3.8]
> roxlib: [1.1.3]
> svg: [1.0.8]
> swf: [2.1.1]

**Comment by jgranick** [comment]
Hey! What Android OS version is your Samsung tablet using, and what model is it? I heard something about this issue recently, but have been unable to reproduce. Seems like a hard problem to reproduce without having hardware on hand to figure it out.

As for filters, these are not enabled at the moment, but there's a PR for filter support which I'm hoping we can integrate :)

**Comment by pozirk** [comment]
It's Samsung Galaxy Tab A.
http://www.gsmarena.com/samsung_galaxy_tab_a_8_0-7121.php
And I have Android 5.0.2 installed.
Really weird thing, if I type a lot, letters appears sometimes, but only some of them.

Thank you!

**Comment by jgranick** [comment]
Yeah, it sounds like the same issue :smile:

What country is the device set to, and what is the default keyboard language? I wonder if it is locale specific, but it seems to be also related to current Samsung hardware :confused:

**Comment by pozirk** [comment]
Keyboard has prediction on top of it, so when I tap these predicted words they actually enter into TextField.
![Image] (http://i60.tinypic.com/aenvcn.png)

**Comment by jgranick** [comment]
I believe we fixed this issue by changing the text input type, I have not heard issues in recent months about input on Android :smile:
