### ISSUE TITLE
blurry canvasses w/ anti-aliasing on safari

### ISSUE THREAD

**Issue by increpare** [openfl/openfl#884]
I feel like I might have mentioned this before, but I can't find a reference (ah - here it is https://github.com/openfl/openfl/commit/e74dda2f57e4089b48c9a0cdaf81a812efe32b82#commitcomment-13312458 .  I guess the comment might have been overlooked).  Anyway, safari (at least the version I have, 9.0, which I think is the latest) still requires webkitImageSmoothingEnabled to be set to have nearest-neighbour resizing, but these lines are commented out in openfl (in many places)

```
            untyped (context).mozImageSmoothingEnabled = false;
            //untyped (context).webkitImageSmoothingEnabled = false;
            untyped (context).msImageSmoothingEnabled = false;
            untyped (context).imageSmoothingEnabled = false;
```

uncommenting (or, at least, adding them back in in the generated javascript) them fixes the problems for me.

**Comment by increpare** [comment]
any thoughts about this? it's a case of uncommenting some mysteriously commented lines. right now, whenever I make a build of a game using haxe with (https://github.com/terrycavanagh/haxegon/), I have to go into the js file and add these lines to make sure it's not blurry in safari...

**Comment by larsiusprime** [comment]
Interesting! I've been trying to figure out why text is unnecessarily blurred in Chrome in flixel, which is also using WebKit, correct?

I'll take a peek on Monday :)

**Comment by increpare** [comment]
Ah, cheers :)

I'm not sure if it's directly related to this - chrome supports imageSmoothingEnabled now, but safari doesn't, not even i. (in fact, chrome throws a deprecation warning if you use webkitImageSmoothingEnabled).

(chrome uses a fork of webkit - parity doesn't seem to be guaranteed...I don't know too much about it, though)

I don't have a simple example, but if you want a complicated example that looks blurry on safari, you can get the code of a project here https://github.com/increpare/writing-game

HOWEVER, having just checked again - while the current safari is blurry as described, the current webkit nightly build isn't ( https://webkit.org/nightly/ ). So eventually this bug will fix itself...
