### ISSUE TITLE
Actuate use of color transform produces invalid field:colorTransform error

### ISSUE THREAD

**Issue by niaccurshi** [openfl/openfl#887]
Have set Actuate to change the colour of some text fields using the transform().color() notation. Since a recent update this has now caused my app to crash, the error is Lib.hx 360: Invalid field: colorTransform

I'm using -DLegacy as it's required to compile properly.

**Comment by jgranick** [comment]
Which platform are you testing? Could you share a little bit of sample code?

**Comment by niaccurshi** [comment]
Sure, I'm developing for iOS and Android here. Problem is for both iOS and Android builds. Just tested Neko and while it doesn't crash, it also doesn't perform the colorTransform. 

`Actuate.tween(toggle_noggin, 0.65, { x : s(13) } );`
`Actuate.tween(toggle_noggin_shadow, 0.65, { x : s(15) } ).onComplete(function() {`
`toggle = 2;`
`app.set_timelimit(1, toggle);`
`			});`
`			Actuate.transform(option2, 0.65).color (app.off_white);`
`			Actuate.transform(option1, 0.65).color (app.yellow);`

**Comment by MSGhero** [comment]
Do you have the dce set to `full` (it's `std` by default)? I had this issue when I was tweening a property that got removed. If so, set it to `std` or `off` and see if the problem persists.

**Comment by jgranick** [comment]
If that is the case, see if doing `@:keep class DisplayObject` in OpenFL fixes it :smile:

**Comment by niaccurshi** [comment]
@MSGhero You're right, I changed dce (for no good reason) the other day, need to do my homework better before tinkering!

**Comment by jgranick** [comment]
@niaccurshi DCE is great, and what we enable in "-final" for HTML5 builds. We probably should just @:keep some of the core methods, so you don't have to have either/or here :smile:

**Comment by niaccurshi** [comment]
So I'm a relative newbie on the block, and understand this isn't the place for it necessarily... but where would I put the @:Keep class DisplayObject? Or is it run on command line?

**Comment by jgranick** [comment]
It would be openfl/openfl/display/DisplayObject.hx, adding `@:keep` just before the `class DisplayObject` declaration, but I can do more testing on my end for this :smile:

**Comment by MSGhero** [comment]
You can also put it in your project.xml file, I do:
```xml
<haxeflag name="-dce full" unless="debug" />
<haxeflag name="--macro" value="keep('nape.geom.Vec2')" />
<haxeflag name="--macro" value="keep('haxe.ds.StringMap')" />
```
You need the fully qualified class name, keep that in mind (openfl.display.DisplayObject).
