### ISSUE TITLE
The path is always closed [HTML5]

### ISSUE THREAD

**Issue by ngrebenshikov** [openfl/openfl#889]
Here is the sample of a curve: https://github.com/openfl/openfl-samples/blob/master/features/display/DrawingShapes/Source/Main.hx#L110-L115

It should draw the only curve but it closes the path on HTML5 target. It's OK on the mac target.

Screenshots are below.

HTML5:
![html5](https://cloud.githubusercontent.com/assets/275250/10597593/04da2824-7712-11e5-9da9-20a0bcce30d9.png)

MAC:
![mac](https://cloud.githubusercontent.com/assets/275250/10597595/0b9b2532-7712-11e5-99ba-93388adec5a8.png)

**Comment by jgranick** [comment]
This was fixed some time ago, thank you :grin:
