### ISSUE TITLE
CanvasTextField render redraw & fix

### ISSUE THREAD

**Issue by KnightMearh** [openfl/openfl#893]
Recently have been developing a javascript game to work inside Ludei / CocoonJS Launcher (free testing app here https://play.google.com/store/apps/details?id=com.ideateca.cocoonjslauncher, also available for iOS).

When running the game inside that environment, we noticed TextFields were not refreshing and would generate a stamp effect every time the field changed. This was also causing the game performance to slow down. I believe this framework converts Canvas to Canvas+ and this changes how rendering works a little. We have found a fix for it, and this is probably good for browsers anyway (they still perform as expected with text behavior).

Please insert this into CanvasTextField.hx:170...

<code>context.clearRect( 0, 0, graphics.__canvas.width, graphics.__canvas.height );</code>

This causes the text fields to clear properly before redrawing the new text whenever they change. I don't believe it to be more expensive or anything since I think you guys were assuming setting the width to itself would also invalidate it, but this will force it to work on additional systems.

**Comment by Leander1P** [comment]
Submitted a pull request here to foster discussion: #902

**Comment by jgranick** [comment]
Oops, linked the wrong issue

https://github.com/openfl/openfl/commit/d9ac19c407c952fdc3c28202fc98ec481fbfe32e

Thanks for all of your work and help, please let me know if this makes a difference, and if there are other cases we need something similar.

Have a great day :grin:
