### ISSUE TITLE
TextField with wordWrap=true causes unusual stretching behaviour.

### ISSUE THREAD

**Issue by tienery** [openfl/openfl#896]
With word wrapping on:
![img](http://i.imgur.com/GwizrmL.png)

With it off:
![img](http://i.imgur.com/Lkzv68C.png)

Thinking of just measuring text and adding a "\n" character whenever it reaches a certain length, which actually should be the behaviour of the TextField's word wrapping anyway, but why it results in this behaviour I really don't know.

The behaviour is same in `legacy` but is somewhat readable.

I also think stretching text is horrible, and the width and height properties shouldn't affect it in this way. For example, reducing the height to smaller than the text font squishes the text, instead of clipping it. My personal opinion on how it should behave. But word wrapping behaviour is unusual and I don't like it ;p

**Comment by MSGhero** [comment]
Does this still happen? Doesn't for me.

**Comment by tienery** [comment]
Oh that was only because the TextField was added to a sprite, and the sprite's width was changed, not the TextField itself. So that was just my problem, none other. Thanks for reminding me to close this :P
