### ISSUE TITLE
TextField has different behaviour in html5

### ISSUE THREAD

**Issue by ShaheedLegion** [openfl/openfl#900]
On flash/neko/native setting openfl TextField AutoSize to NONE and adding text gives a valid textWidth and textHeight - whether the textField multiline is set to true/false.

Embedded fonts are also not working correctly on flash.

When using the exact same code with the html5 output, the textfield suddenly stops reporting the textwidth and textheight correctly and the text wraps - regardless of whether I've specified wordWrap.

It seems that the behaviour should remain the same with any backend I choose, and this is mostly the case, except for html5.

As you can see, the top section of the image represents the flash backend - which correctly deduces the width of the text, but does not load the font.

The bottom section of the image is using the html5 backend - which incorrectly calculates the width of the text, but uses the correct font.

![image](https://cloud.githubusercontent.com/assets/5690887/10691253/1b575662-7988-11e5-9dbe-71a65719b22a.png)

Please advise if there is a temporary fix for this, as we need the same behavior across all platforms.

**Comment by larsiusprime** [comment]
Do you get the same problems in these two demos?

https://github.com/openfl/openfl-samples/tree/master/demos/TextMetrics
https://github.com/openfl/openfl-samples/tree/master/demos/TextAlignment

If so then it's definitely a regression and something we should fix ASAP.

**Comment by ShaheedLegion** [comment]
Hi, as a quick update, I've managed to get the fonts working by setting the embedFonts flag on the text field.

However, the text wrapping is still an issue. The html5 output behaves differently from any other backend. I tried using the Dom rendering as well as the canvas rendering mode - they both behave similarly wrt the wrapping bug.

I'll take a look at the demos you've provided and report as soon as I have more info.

Thank you.

**Comment by ShaheedLegion** [comment]
I've run the samples and it seems that the font is not being found for the html build of the TextMetrics sample. This is, however, not the main issue, as I can find workarounds for loading fonts.

I've produced a minimal sample that illustrates the issue I'm facing, and it's a very strange one indeed.

```javascript
package;

import openfl.display.Sprite;
import openfl.text.TextField;
import openfl.text.TextFieldAutoSize;
import openfl.text.TextFormatAlign;

class Main extends Sprite {

	public static var BR: String = "\n";
	
	public function new () {
		super ();
		
		var t:TextField = new TextField();
		t.width = 800;
		t.y = 20;
		
		t.multiline = true;
		t.wordWrap = true;
		t.autoSize = TextFieldAutoSize.LEFT;
		
		t.selectable = false;
		t.border = true;
		t.borderColor = 0x000000;

		var longString: String = "This is a minimal sample which illustrates the problem.";
		longString += "This should be enough text to get some decent wrapping behaviour.";
		
		t.text =  longString;
		addChild(t);
		
		// Now that the text component is added, I'll manually wrap the content.
		// We pretend that we have a "panel" which needs to be a certain width
		// for some layout mechanism to work.
		// So we manually wrap the text after calculating the required width
		// and height for the field.
		var words: Array<String> = t.text.split(" ");
		var tempString: String = "";

		for (w in words) {
			var nextProposedString: String = tempString + w + " ";
			t.text = nextProposedString;
			
			var newTextW: Int = Std.int(t.textWidth);
			if (newTextW >= 200) {
				// Append a line break to it.
				tempString += BR;
			}
			
			// Append the word and set it on the textField.
			tempString += w + " ";
			t.text = tempString;
		}
		// Se the final output on the text field.
		t.text = tempString;
	}
}
```

You'll see very different results when you run this sample in html5 vs. flash and neko.
I'm not exactly sure how to explain it, but I can at least show a screenshot of the differences I've found.

HTML5:
![image](https://cloud.githubusercontent.com/assets/5690887/10752539/06405b30-7c93-11e5-98ba-1079842ba2d9.png)

Flash:

![image](https://cloud.githubusercontent.com/assets/5690887/10752550/1d3b3c7e-7c93-11e5-8e6c-a05544b6a9c7.png)

Neko:

![image](https://cloud.githubusercontent.com/assets/5690887/10752559/2c2389e4-7c93-11e5-979b-ad444e6208e4.png)

**Comment by ShaheedLegion** [comment]
Hi guys,

We have found the problem, it seems that when there's some text in a TextField, adding a newline character actually adds some additional width, I've updated the algorithm to take this into account and we get the correct results in all cases.

Thank you for your assistance with this problem.
Issue is now closed.
