### ISSUE TITLE
BitmapData.perlinNoise does not work on html5 target (no output)

### ISSUE THREAD

**Issue by cemir** [openfl/openfl#913]
Here is the code used :+1:

```
            var bmpFrac:BitmapData = new BitmapData(500,500, false, 0);
            bmpFrac.perlinNoise(8.7, 7.9, 2, 1516468464, false, false, 1, true);

            bmpFrac.setPixel(10,10,0xFF00FF00);

            var testPic : FlxSprite;
            testPic = new FlxSprite();
            testPic.loadGraphic(bmpFrac);
            add(testPic);
```

in html5 it gives a black picture with a colored pixel at 10,10
in cpp it gives a "cloudy" picture, as expected.

openfl version : 3.4.0
lime : 2.7.0

Regards

**Comment by ICTylor** [comment]
Hi, Perlin noise doesn't work for me in any platform except Flash. I'm using this code
```
class Main extends Sprite 
{
	private var _bitmapData:BitmapData = new BitmapData(400, 400);
	private var _bitmap:Bitmap;

	public function new() 
	{
		super();
		_bitmapData.perlinNoise(400, 400, 6, 0, false, false);
		_bitmap = new Bitmap(_bitmapData);
		this.addChild(_bitmap);
	}
}
```
In my case it draws the right image in Flash, in any other platform it draws a white square.

Haxe version: 3.2.1
OpenFL version: 3.4.0
Lime: 2.7.0
Compiling on a Windows 8.1 x64 machine

**Comment by larsiusprime** [comment]
I don't think we've implemented Perlin noise yet, I originally assumed that this was because the algorithm was patented, but it looks like it might be okay:

http://computergraphics.stackexchange.com/questions/19/does-the-original-perlin-noise-ever-have-any-advantage-over-simplex-noise

**Comment by MSGhero** [comment]
Simplex noise isn't patented for 2D, and I don't think perlin noise is either. I'm not sure which one bmd uses, but simplex noise is faster (I have it coded already and can post it).

**Comment by larsiusprime** [comment]
@MSGhero : cool, if you want, here is where you would add it:

https://github.com/openfl/openfl/blob/master/openfl/display/BitmapData.hx#L1568

**Comment by larsiusprime** [comment]
More information if it helps:
http://stackoverflow.com/questions/8467685/how-is-perlin-noise-in-flash-implemented

**Comment by MSGhero** [comment]
So like, I have no idea what flash does, but does it matter if it's consistent? Like SharedObjects are different for flash vs the rest, could this just be simplex (fast) noise?

I can see someone wanting consistent noise per seed across targets (since I need this), but I would just use my own noise function.

**Comment by MSGhero** [comment]
I guess the other thing is that these parameters are weird. Mine takes x, y, scale, and octaves, but bmd's params do different things in order to get the tiled effect.

**Comment by jgranick** [comment]
I'm okay with incremental improvements. Some noise is better than none, and provides a starting point for refining the algorithm :smile:

**Comment by MSGhero** [comment]
I'll look into it this weekend, but here's the noise function: https://www.dropbox.com/s/4812bmy4hnrxluy/Noise.hx?dl=0

It's more than a single function for speed purposes, at least according to the Perlin paper I got the `contr2D` weirdness from.

**Comment by larsiusprime** [comment]
Yaknow, there is always the option of making it consistent across platforms by straight up OVERRIDING flash's native logic on flash target for the what-we-use-everywhere else logic.

**Comment by MSGhero** [comment]
If I have a bunch of private static vars and functions for the noise, is there a preferred place in the file to place those? Or like a BmdUtils class?

**Comment by azrafe7** [comment]
It seems to be implemented in legacy (https://github.com/openfl/openfl/blob/7e3198d31ccda0aa6095f59b8f8cb442f44ff3ca/openfl/_legacy/display/BitmapData.hx#L504). Haven't tested if it behaves the same as the AS3 version but, from the look of it, it should be a direct port of http://www.quasimondo.com/archives/000672.php, which says so in the description.

Can anyone confirm?

**Comment by MSGhero** [comment]
Oh neat. I'll try to check it out tonight if no one else does.

**Comment by azrafe7** [comment]
Great. @MSGhero, while you're at it, can you also check the `noise` implementation, which also seems to be available in legacy but not in next?

**Comment by MSGhero** [comment]
![perlin](https://cloud.githubusercontent.com/assets/5033927/11095538/8b6fd688-8863-11e5-99fa-ebed13d4c677.png)
Neko/windows vs flash.

```haxe
var bmd1 = new BitmapData(100, 100);
bmd1.perlinNoise(50, 50, 1, 1001, true, false);
var bmd2 = new BitmapData(100, 100);
bmd2.perlinNoise(50, 50, 1, 1001, true, true);
var bmd3 = new BitmapData(100, 100);
bmd3.perlinNoise(50, 50, 1, 1001, false, true);
var bmd4 = new BitmapData(100, 100);
bmd4.perlinNoise(50, 50, 1, 1001, false, false);
```

**Comment by MSGhero** [comment]
So if the proper implementation exists somewhere, I guess we should use that even if it's slower than simplex noise. It's just not properly implemented in legacy or at all in next.
