### ISSUE TITLE
Icon generation based on SVG files is broken

### ISSUE THREAD

**Issue by sebthom** [openfl/openfl#916]
When using an SVG file as icon in the project.xml, e.g. 

    <icon path="res/icon.svg"/>

The Generated .png and .ico files are contain wrongly resized images which only covers a fraction of the icon dimensions. Example:

This is the source icon.svg:  http://pastebin.com/k1xxDJaT
This is for example generated at project\bin\android\bin\res\drawable-xxxhdpi\icon.png : http://picpaste.com/icon.png
But it should actually look like this: http://picpaste.com/icon_1.png

**Comment by grapefrukt** [comment]
I've had this issue too, I suspect it's because the bundled SVG renderer does not respect the viewBox property in the SVG.

**Comment by am3000** [comment]
same here, not even the default icon openfl.svg from the flashdevelop template is correct on android.

**Comment by ivodopiviz** [comment]
Any news on this? I stumbled upon this one today...

**Comment by jgranick** [comment]
The current OpenFL/Lime icons work, but I can't promise the SVG library is perfect. The solution is to look at making improvements to https://github.com/openfl/svg

You can see how we use it in our SVG export script here:

https://github.com/openfl/lime/blob/master/tools/SVGExport.hx#L163-L170

To rebuild this, do `cd tools && haxe svg.hxml` in the Lime directory

**Comment by grapefrukt** [comment]
I hacked in support for the viewBox property in a hurry, I've been meaning to do a proper PR with it, but haven't had time. 

In the meantime, this is the code I use:

````` haxe
package com.grapefrukt.games.spacematch.renderers;

import format.SVG;
import format.svg.SVGData;
import format.svg.SVGRenderer;
import openfl.Assets;
import openfl.display.Graphics;
import openfl.display.Sprite;
import openfl.geom.Matrix;
import openfl.geom.Rectangle;

/**
 * ...
 * @author Martin Jonasson, m@grapefrukt.com
 */
class VectorAsset extends Sprite {

	public function new(id:String) {
		super();
		var s = new CustomSVG(Assets.getText('svg/$id.svg'));
		s.render(graphics);
	}
	
}


private class CustomSVG {
	
	public var data:SVGData;
	var viewBox:Rectangle;
	
	public function new(content:String) {
		var xml = Xml.parse(content);
		
		var viewboxString = '';
		for (svg in xml.elementsNamed('svg')) {
			viewboxString = svg.get('viewBox');
			break;
		}
		
		if (viewboxString != '') {
			var arr = viewboxString.split(' ');
			viewBox = new Rectangle(Std.parseInt(arr[0]), Std.parseInt(arr[1]), Std.parseInt(arr[2]), Std.parseInt(arr[3]));
		}
		
		data = new SVGData(xml);
	}
	
	public function render(graphics:Graphics, x:Float = 0, y:Float = 0, width:Int = -1, height:Int = -1) {
		var matrix = new Matrix();
		matrix.identity();
		matrix.translate(x - viewBox.x, y - viewBox.y);
		
		if (width > -1 && height > -1) {
			matrix.scale(width / data.width, height / data.height);
		}
		
		var renderer = new SVGRenderer(data);
		renderer.render(graphics, matrix);
	}
	
}
````

This uses a separate class so I don't have to mess with the library code, which naturally is a better way to do things if you *actually* want to fix it, but yeah, quick fix on my side.

**Comment by ibilon** [comment]
Known issue https://github.com/openfl/svg/issues/18

**Comment by ashes999** [comment]
@grapefrukt could you please create a proper PR? We now have infrastructure in place to automatically test and verify SVGs generate correctly.
