### ISSUE TITLE
Extension resources can be accessed through mainActivity?

### ISSUE THREAD

**Issue by shadowofsoul** [openfl/openfl#919]
Hi,

i'm trying to make compatible the extension for unityAds with the latest SDK ( https://github.com/ipsilondev/openfl-unityads )

The problem i have, is that now the SDK requires to include several resources (.xml). I set them in the res folder of the extension and they are correctly copied and built, but UnityAds can't find them. i traced the problem to:

UnityAds code tries to find the layout from the activity i pass to it:

https://github.com/Applifier/unity-ads/blob/beefc7444ed02224a31f8b64d1f57e99cf8d6cf2/android/sources/src/com/unity3d/ads/android/UnityAds.java#L473

as you see here, i pass mainActivity as parameter for that function:

https://github.com/ipsilondev/openfl-unityads/blob/master/dependencies/android/src/com/ipsilondev/UnityAdsWrapper.java#L36

so, the question is, can i make this resources available somehow through mainActivity? or i need to create a separate activity for the extension itself so i could pass this activity to UnityAds and be like a "bridge" to the files?

**Comment by DanielUranga** [comment]
Try using the template system, like: http://player03.com/2014/08/14/template-basics/

**Comment by shadowofsoul** [comment]
i don't think that is the correct approach  for an extension, is not enough atomic to be used in any project. if doesn't exist any other method, i prefer to build a separated activity or modify the unityAds SDK

**Comment by DanielUranga** [comment]
Why not simply copy the .xmls to the res folder using the template system? of course adding the template tags to the "include.xml" of the extension.

**Comment by shadowofsoul** [comment]
and how i can do that? there is any example of how to do it?

**Comment by shadowofsoul** [comment]
Thanks for your help @DanielUranga ! with your guide i could find a workaround and get it working :)
