### ISSUE TITLE
The first tutorial contains a broken image

### ISSUE THREAD

**Issue by dagnelies** [openfl/openfl#924]
In the tutorial here:

http://www.openfl.org/documentation/getting-started/your-first-project/

Following image is referenced:

https://raw.githubusercontent.com/openfl/openfl-samples/master/DisplayingABitmap/Assets/openfl.png

which appears to be broken.

...don't wanna annoy you, but it really leaves a poor impression.

**Comment by Hasufel** [comment]
This should be fixed. Thx!
