### ISSUE TITLE
TypeError (null access) when -Dwebgl in GL.context.enable

### ISSUE THREAD

**Issue by fzzr-** [openfl/openfl#927]
Not works [Away3D basic example](https://github.com/away3d/away3d-examples-openfl/tree/master/Basic_View) built with `-D debug` & `-D webgl`.

Part of `project.xml`:

``` xml
    <!--<haxedef name="dom" if="html5"/>-->
    <haxedef name="webgl" if="html5"/>

    <!-- DEBUG -->
    <set name="debug"/>
    <haxedef name="debug" if="debug"/>
```

In runtime got exception:

``` log
TypeError: null is not an object (evaluating 'lime_graphics_opengl_GL.context.enable')
configureBackBufferAwayCube.js:62795
onContext3DUpdateAwayCube.js:13540:99
fAwayCube.js:69262:247
__dispatchEventAwayCube.js:197
dispatchEventAwayCube.js:130
(anonymous function)AwayCube.js:62585
runAwayCube.js:32701
(anonymous function)AwayCube.js:32692
```

![screen shot 2015-11-09 at 22 48 32](https://cloud.githubusercontent.com/assets/888526/11044620/0e0cf89a-8734-11e5-876d-17c20032cae3.png)

**Comment by fserb** [comment]
Same thing with BabylonHX. -Ddom works fine though.
