### ISSUE TITLE
Graphics.drawTriangles does not render when not using texture

### ISSUE THREAD

**Issue by grapefrukt** [openfl/openfl#930]
![screenshot-2015-11-11-11 37 41](https://cloud.githubusercontent.com/assets/158901/11089431/fc5e068e-8869-11e5-927b-5f3cdb136080.png)

Above is expected output (obtained using legacy). Using next renderer, nothing is rendered. 
Rectangle is displayed properly when using a texture as per [this example](http://www.openfl.org/documentation/basics/bitmaps/display-images/)

``` haxe
package;

import openfl.display.Sprite;
import openfl.Vector;

class Main extends Sprite {

	public function new() {
		super();
		
		var vertices = new Vector<Float>(8, true);
		var indices = new Vector<Int>(4, true);
		var colors:Vector<Int> = new Vector(4, true);

		vertices[0] = vertices[4] = 10;
		vertices[1] = vertices[3] = 10;
		vertices[2] = vertices[6] = 210;
		vertices[5] = vertices[7] = 210;

		indices[0] = 0;
		indices[1] = indices[3] = 1;
		indices[2] = indices[5] = 2;
		indices[4] = 3;
		
		colors[0] = 0xffff0000;
		colors[1] = 0xff00ff00;
		colors[2] = 0xff0000ff;
		colors[3] = 0xffffffff;
		
		graphics.drawTriangles(vertices, indices, null, null, colors);
	}

}
```

Tested on Windows 7 using: 

		hxcpp: [3.2.193]
		lime: [2.7.0]
		openfl: [3.4.0]

Project is [here](https://dl.dropboxusercontent.com/u/32925/bugreports/drawtriangles.zip)

**Comment by ibilon** [comment]
Crashing for me on neko, not sure why,
```
Called from openfl._internal.renderer.cairo.CairoGraphics::playCommands line 794
Uncaught exception - Invalid operation (*)
```

Display a square on native,
but `drawTriangles` doesn't take a color argument anymore,
so not sure if fixed or not.
