### ISSUE TITLE
getURL not wokring for native

### ISSUE THREAD

**Issue by pozirk** [openfl/openfl#933]
I have **openfl.Lib.getURL** not working on native targets with the latest OpenFL version.
And I think, I know why. :smile:
Any chance it to be fixed?
Thank you!

``` haxe
    public static function getURL (request:URLRequest, target:String = null) {

            if (target == null) {

                target = "_blank";

            }

            #if (js && html5)
            Browser.window.open (request.url, target);
            #elseif flash
            return flash.Lib.getURL (request, target);
            #end

        } 
```

**Comment by pozirk** [comment]
Eah, what about Android, iOS and etc?

**Comment by Tiago-Ling** [comment]
I also need this functionality and i've been looking into `lime.tools.helpers.ProcessHelper` to see how it's done:
```haxe
	public static function openURL (url:String):Void {
		
		if (PlatformHelper.hostPlatform == Platform.WINDOWS) {
			
			runCommand ("", "start", [ url ]);
			
		} else if (PlatformHelper.hostPlatform == Platform.MAC) {
			
			runCommand ("", "/usr/bin/open", [ url ]);
			
		} else {
			
			runCommand ("", "/usr/bin/xdg-open", [ url, "&" ]);
			
		}
		
	}
```

Is there a specific command that can be used here to open native browsers in iOS and Android? Or do i have to include methods in pure java / obj-c? 

Any tips to help direct my efforts will be greatly appreciated! :)

**Comment by jgranick** [comment]
This is supported in current `openfl.Lib.getURL` or `lime.system.System.openURL` and `lime.system.System.openFile` :smile:

**Comment by Tiago-Ling** [comment]
Any tips on how to hack support for this in OpenFL 3.6.1 and Lime 2.9.1? 

I'm stuck with these versions for a project and really need to fix this!

Thanks!

**Comment by jgranick** [comment]
Desktop or mobile?

**Comment by Tiago-Ling** [comment]
Mobile

**Comment by jgranick** [comment]
Are you using legacy? I thought it had this support on iOS/Android

**Comment by Tiago-Ling** [comment]
No, using next. I believe the methods are not implemented for iOS and Android (see previous comment from November, 1st above)

**Comment by jgranick** [comment]
Then you'll likely want to look at adapting this commit: 😄 

https://github.com/openfl/lime/commit/54a8f32f60a3a6c00d985be17eb98c8ffd101078

**Comment by Tiago-Ling** [comment]
Thanks @jgranick !

**Comment by Tiago-Ling** [comment]
@jgranick One more question Joshua: i'm using an altered version of the release versions (3.6.1 and 2.9.1) of OpenFL and Lime, but to make the changes i need the dev version of them right? Is there anything else i need to add besides the `project` folder?

Thanks!

**Comment by jgranick** [comment]
@Tiago-Ling You can try using a "legacy" version of the Lime project directory, and see if it builds for you. I have a feeling it will probably work as a drop-in for your current version, the next step would be making modifications to the source files there to try and include the additional API end points I showed from the newer version.

Current Lime releases have a DRASTICALLY different project/ directory (and resulting C++ binary) and would not be compatible, so you'll have to modify legacy project/ sources instead 😦

**Comment by Tiago-Ling** [comment]
Commit you mentioned is indeed "legacy" only, but i'm using "next". Is there a commit that adds support for `openURL` on mobile using next?

Thanks!
