### ISSUE TITLE
getPath returns null for jpg

### ISSUE THREAD

**Issue by ShaheedLegion** [openfl/openfl#939]
Hi,

I have a simple project, I'm using getPath to get the absolute path to an image (jpg), but this returns null.
I use getBitmapData to get the content of the image, and this works, however getPath does not - for the same path that was passed to getBitmapData.

I stepped into the code, and the image is in the default asset library, but the code just fails to get the path to it.

var bitmapData = Assets.getBitmapData ("assets/slinky.jpg");  // works
			var pathItem: String = Assets.getPath("assets/slinky.jpg");  // doesn't work

Thanks

**Comment by ibilon** [comment]
Couldn't reproduce,
if you still have this problem with the latest versions please reopen with your image attached.
