### ISSUE TITLE
[cpp] crash at start up (related to mouseMove event)

### ISSUE THREAD

**Issue by azrafe7** [openfl/openfl#943]
I'm getting a `Null Object Reference` error with the following:

```haxe
class Main extends Sprite {
	
	public function new () 
	{
		super();
		
		var bmp = new Bitmap(new BitmapData(10, 10));
		
		addChild(bmp);
	}
}
```

Only happens with cpp (neko is fine).

Stepping through code it seems that this unsafe cast to `InteractiveObject` https://github.com/openfl/openfl/blob/bc42e4c99172e819a746d89e423793f27698d867/openfl/display/DisplayObjectContainer.hx#L808 is the offender. It returns null in cpp.

To confirm it I've tested with:
```haxe
	var bmp = new Bitmap(new BitmapData(10, 10));
	toInteractiveObject(cast bmp);
		
	function toInteractiveObject(obj:InteractiveObject):Void {
		trace(obj);  // null on cpp, [object Bitmap] on neko
	}
```

(I'm compiling on win7 with `--window-hardware=false`)

**Comment by larsiusprime** [comment]
I just fixed this in a recent PR, I believe.

On Mon, Nov 23, 2015 at 2:46 PM, Giuseppe Di Mauro <notifications@github.com
> wrote:

> I'm getting a Null Object Reference error with the following:
>
> class Main extends Sprite {
>
>     public function new ()
>     {
>         super();
>
>         var bmp = new Bitmap(new BitmapData(10, 10));
>
>         addChild(bmp);
>     }
>
> Only happens with cpp (neko is fine).
>
> Stepping through code it seems that this unsafe cast to InteractiveObject
> https://github.com/openfl/openfl/blob/bc42e4c99172e819a746d89e423793f27698d867/openfl/display/DisplayObjectContainer.hx#L808
> is the offender. It returns null in cpp.
>
> To confirm it I've tested with:
>
>     var bmp = new Bitmap(new BitmapData(10, 10));
>     toInteractiveObject(cast bmp);
>
>     function toInteractiveObject(obj:InteractiveObject):Void {
>         trace(obj);  // null on cpp, [object Bitmap] on neko
>     }
>
> (I'm compiling on win7 with --window-hardware=false)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openfl/openfl/issues/943>.
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by larsiusprime** [comment]
Does this do the trick?
https://github.com/openfl/openfl/pull/941

**Comment by azrafe7** [comment]
Ah yes... I've applied the same patch locally, but wasn't unsure if it had implications.

**Comment by azrafe7** [comment]
Alright, http://stackoverflow.com/questions/1480524/adding-an-mouse-event-listener-to-a-bitmap-with-actionscript-3 confirms that that is an invalid cast, as Bitmap is not a descendant of InteractiveObject.

Thanks @larsiusprime.
