### ISSUE TITLE
config:hxtelemetry element in project.xml ignored when -Dtelemetry is specified

### ISSUE THREAD

**Issue by sebthom** [openfl/openfl#950]
When executing openfl build commands with the flag -Dtelemetry, e.g.

    openfl build neko -Dtelemetry 

the hxtelemetry declaration in project.xml, e.g.

     <config:hxtelemetry host="192.168.42.11" allocations="true" />

 is ignored:

The generated ApplicationMain.hx still contains the statement to set the host to "localhost":

	public static function main () {
		...
		#if hxtelemetry
		telemetryConfig = new hxtelemetry.HxTelemetry.Config ();
		telemetryConfig.allocations = ("true" == "true");
		telemetryConfig.host = "localhost";

However, when running the same openfl command without the "-Dtelemetry" flag, the generated ApplicationMain.hx contains the expected statement to set the host as defined in the project.xml:

	public static function main () {
		...
		#if hxtelemetry
		telemetryConfig = new hxtelemetry.HxTelemetry.Config ();
		telemetryConfig.allocations = ("true" == "true");
		telemetryConfig.host = "192.168.42.11";

This means, only when actually enabling telemetry support, the hxtelemetry config tag is ignored.

**Comment by crazyjul** [comment]
Can you double check both generated code? If you look at the template, the first code looks anormal : 

```
telemetry.allocations = ::if (config.hxtelemetry != null)::("::config.hxtelemetry.allocations::" == "true")::else::true::end::;
telemetry.host = ::if (config.hxtelemetry != null)::"::config.hxtelemetry.host::"::else::"localhost"::end::;
```

The line ```telemetryConfig.allocations = ("true" == "true");``` should in fact be ```telemetryConfig.allocations = true``` if the config was completely ignore. 

Can you try changing the value in allocations and see what is generated?

**Comment by jgranick** [comment]
I don't think there is a way for us to enforce a default telemetry config at the moment, so we want it to work out-of-the-box for projects that only use `-Dtelemetry` and do not define a config. In the meantime, you will need to define your config _after_ the OpenFL haxelib line in the project.xml

**Comment by ibilon** [comment]
Wasn't the default config in the template?
