### ISSUE TITLE
DOM renderer does not clip DisplayObjectContainer content when using scrollRect

### ISSUE THREAD

**Issue by er453r** [openfl/openfl#951]
DOM renderer does not clip DisplayObjectContainer content when using scrollRect, both CANVAS and WEBGL work ok.

**Comment by er453r** [comment]
I tracked it down to `DOMShape` not editing the `clip` CSS style to objects parent `scrollRect` - will try to fix that

**Comment by jgranick** [comment]
fixed 😄
