### ISSUE TITLE
Font.registerFont exception in flash target

### ISSUE THREAD

**Issue by maaniv** [openfl/openfl#957]
Exception:
[Fault] exception, information=TypeError: Error #1006: __fromBytes is not a function.
In file Assets.hx function embedFont.

Versions:
lime: [2.8.1]
openfl: [3.5.1]

**Comment by slavasitnikov** [comment]
Same error on versions:
lime: [2.8.1]
openfl: [3.5.2]

**Comment by slavasitnikov** [comment]
if replace in lime.Assets.embedFont

**Comment by slavasitnikov** [comment]
Here is possible workarund:
replace in lime.Assets.embedFont

```
var constructor = macro {
	super ();
	__fromBytes (haxe.Resource.getBytes (resourceName));
};
```

with

```
var constructor;
if (!Context.defined("flash")) {
	constructor = macro {
		super ();
		__fromBytes (haxe.Resource.getBytes (resourceName));
	};
}
else {
	constructor = macro {
		super ();
	};
}
```

**Comment by johanvdb** [comment]
Same issue on 

lime 2.9.0
openfl 3.6.0

**Comment by johanvdb** [comment]
See https://github.com/johanvdb/openfl-test-fontembed for a very plain example of the problem.

**Comment by hopewise** [comment]
The same here, any update?

**Comment by radixzz** [comment]
I'm getting the same exception.

**Comment by ibilon** [comment]
Used code from https://github.com/johanvdb/openfl-test-fontembed
note that it also doesn't display anything on native.

But I'm not sure how `@:font` and `font.fontName` are supposed to work together.
