### ISSUE TITLE
Initializing static variables with BitmapData crashes on next 

### ISSUE THREAD

**Issue by Gama11** [openfl/openfl#964]
This code causes a crash on neko / cpp with next. Works fine with `<set name="legacy" />`.

HTML5 and Flash don't have any issues. 

```haxe
package;

import openfl.display.BitmapData;
import openfl.display.Sprite;

class Main extends Sprite 
{
	static var graphic = new BitmapData(1, 1);
}
```

Neko stracktrace:

```
Called from Main.hx line 8
Called from openfl/display/BitmapData.hx line 63
Called from openfl/display/BitmapData.hx line 133
Called from lime/graphics/Image.hx line 392
Called from lime/graphics/utils/ImageDataUtil.hx line 326
Uncaught exception - Invalid call
```

Lime 2.8.1, OpenFL 3.5.1, Haxe 3.2.0.

**Comment by ibilon** [comment]
Trying to call `lime_image_data_util_fill_rect` which is also statically init,
I guess the CFFI macro should generate an `__init__` method to populate these variables.

**Comment by MSGhero** [comment]
Is this related at all to `public var bmd = Assets.getBitmapData("assetName")` creating invalid bmds? It's been a while, but I believe that line caused an `Invalid BitmapData, width/height can't be 0` kind of error. I think the actual crash occurred when trying to use that `bmd`.

This was happening internally in flixel, as my actual use case was trying to create a flixel texture atlas as a `public var`.

**Comment by jgranick** [comment]
Sorry to drum up an old topic, but this is fixed as of the latest OpenFL/Lime development versions
