### ISSUE TITLE
IE/Edge isPointInStroke is unsupported

### ISSUE THREAD

**Issue by er453r** [openfl/openfl#973]
As the title says, but here is a fix I'm using and i I think it is good enough for openfl:

    #if js
    untyped __js__('// openfl IE/Edge isPointInStroke shiv - not super exact for wide strokes
    if(typeof CanvasRenderingContext2D.prototype.isPointInStroke == "undefined"){
        console.log("Pathed CanvasRenderingContext2D with isPointInStroke approximation");

	    CanvasRenderingContext2D.prototype.isPointInStroke = function(path, x, y) {
	        return this.isPointInPath(x, y);
	    }
     }');
    #end

**Comment by CharlesAnifowose** [comment]
Where are you inserting this?

**Comment by CharlesAnifowose** [comment]
fix is working for me until Lime goes live :)
