### ISSUE TITLE
[OpenFL 3.5.3 / Lime2.8.2] Assets.getFont not working properly on Android, fontName returns gibberish

### ISSUE THREAD

**Issue by yuigoto** [openfl/openfl#974]
This was posted on the OpenFL forums, but since it looks like a bug, I'm posting here too, since I didn't find a post on this matter (sorry if this is a duplicate).

I've been testing font embedding on Android and I'm having problems with `fontName`.

While on Windows/Neko/Flash/HTML5 ir returns the proper font name, on Android it just returns some encoded gibberish.

This is the code I'm testing, right now:

``` haxe
        var font:Font = Assets.getFont( "fonts/montserrat.ttf" );

        trace( font );
        trace( font.fontName );

        var tf:TextField = new TextField();
        var td:TextFormat = new TextFormat(
            font.fontName, 
            32, 
            0xffffff
        );
        tf.defaultTextFormat = td;
        tf.text = "TEST";
        tf.autoSize = TextFieldAutoSize.LEFT;
        tf.type = TextFieldType.DYNAMIC;
        tf.multiline = false;
        tf.embedFonts = true;
        tf.selectable = false;
        tf.x = 120;
        tf.y = 120;
        addChild( tf );
```

For the Android output, using legacy mode works just fine and the font is properly rendered.

But, without legacy mode, tracing returns this:

```
I/trace   (27320): Main.hx:67: Font
I/trace   (27320): Main.hx:68: ¹ª¢ì³ªò│¹ùæí²ûØÑþëí
```

I don't know if I'm doing something wrong in here, but looks like I'm not. :stuck_out_tongue:

It also works properly if I do this:

```
        #if android
            var fo:Font = new Font( "fonts/montserrat.ttf" );
        #else
            var fo:Font = Assets.getFont( "fonts/montserrat.ttf" );
        #end
```

Is this a bug, or this is the "proper" way to do it? :confused:

Thanks! :smile:

**Comment by man2** [comment]
https://github.com/openfl/openfl/issues/1215 still an issue until today
