### ISSUE TITLE
html5 bitmapfill repeat correctly on y axis but not on x axis

### ISSUE THREAD

**Issue by TBaudon** [openfl/openfl#975]
here is two images to explain the problem : 
What is expected : 
![expected result](http://s14.postimg.org/ra0uy2wo1/Capture_du_2015_12_22_12_45_54.png)

What it does :
![actual result](http://s23.postimg.org/lmg20lijv/Capture_du_2015_12_22_12_47_55.png)

I guess it's just an uv mistake ?
I'll give it a look but I have no idea where to look.
If anybody knows, please tell me ^^

Thanks

**Comment by RblSb** [comment]
Works fine
https://gist.github.com/RblSb/482a3360a5ddc76ef4352346bfbc2688
