### ISSUE TITLE
Can't compile . PNGEncoderOptions error

### ISSUE THREAD

**Issue by flashultra** [openfl/openfl#979]
With the latest OpenFl and Lime received the following error:
/openfl/3,5,3/extern/flash/display/PNGEncoderOptions.hx:17: characters 0-27 : Recursive typedef is not allowed

**Comment by flashultra** [comment]
I manually set this fix, but still received same error ( target flash) . The problem is in this row: 
  typedef PNGEncoderOptions = openfl.display.PNGEncoderOptions;

Test data : 
-----------------------------------
openfl test flash

/haxe/lib/openfl/3,5,3/extern/flash/display/PNGEncoderOptions.hx:17: characters 0-27 : Recursive typedef is not allowed

Example code:
```
 public function new () {
		Assets.getBitmapData("assets/25.png");
   }
```

**Comment by hopewise** [comment]
I have the same issue, how did you solve it at flash?

**Comment by jgranick** [comment]
Have you tried updating to the latest and (if necessary) doing a -clean build?

**Comment by hopewise** [comment]
Here is my setup:

>haxelib list
actuate: [1.8.6]
cereal: [0.0.4]
hscript: [2.0.5]
lime: 2.7.0 [2.8.3]
openfl: 3.4.0 [3.5.3]
rox-i18n: [1.0.0]
stablexui: [1.1.5]
svg: [1.0.8]
swf: 2.1.2 [2.1.6]

>haxelib run lime build "project.xml" flash -debug -Dfdb -clean

C:/HaxeToolkit/haxe/lib/openfl/3,5,3/extern/openfl/display/PNGEncoderOptions.hx:17:
characters 0-27 : Recursive typedef is not allowed

On Thu, Jan 7, 2016 at 11:54 PM, Joshua Granick <notifications@github.com>
wrote:

> Have you tried updating to the latest and (if necessary) doing a -clean
> build?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openfl/openfl/issues/979#issuecomment-169818479>.
>



-- 
--
Kind Regards,
---------------------------------------------
Samir Sabri
Software Architect& Developer
www.dcaclab.com
Jordan-Middle East
