### ISSUE TITLE
Wrong documentation description -BitmapData

### ISSUE THREAD

**Issue by flashultra** [openfl/openfl#980]
Here : http://www.openfl.org/documentation/api/openfl/display/BitmapData.html
For function encode(....)  we have wrong description
"
This method is not available to the HTML5 and Flash targets.

@param format The encoding format, either "png" or "jpg". @param quality The encoding quality, when encoding with the JPG format. @return A ByteArray in the specified encoding format
"
We not have @param format or @param quality

**Comment by larsiusprime** [comment]
That's right, it seems that you need to supply "PNGEncoderOptions", not "png"

**Comment by CharlesAnifowose** [comment]
Where could something like this be fixed?

**Comment by jgranick** [comment]
Our site is statically generated, this is an old page that doesn't exist in the sitemap. We need to clean it up (with redirects?) and then we can make to api.openfl.org if we need to

**Comment by jgranick** [comment]
*updates to http://api.openfl.org
