### ISSUE TITLE
Hard crash on native and neko when hovering mouse over Tilesheet particles

### ISSUE THREAD

**Issue by KirillPoletaev** [openfl/openfl#983]
Here is the code to reproduce the crash: http://pastebin.com/8hdV2Euj

When I add a lot of particles via Tilesheet to the screen as in the example and set the center point of a tile with X coordinate greater than its width and Y coordinate greater than its height, then hover my mouse over any of the generated particles - the app crashes.

On neko the program crashes if the center point is set to anything greater than a quarter of the tile's size.

Call stack: http://i.imgur.com/xWhPxlV.png
"inSize" value: http://i.imgur.com/eOyBdE4.png

A workaround is to disable mouse on the container of the Tilesheet graphics:

```
g.mouseEnabled = false;
```

Tested on Windows, using OpenFL 3.5.4, Lime 2.8.2, Hxcpp 3.2.193

**Comment by grapefrukt** [comment]
This crash has two parts to it, firstly, it's the actual crash. Secondly, why is it running mouse hit stuff when nothing seems to need it or ask for it?
