### ISSUE TITLE
TextField Selection/Focus and firing events

### ISSUE THREAD

**Issue by peteshand** [openfl/openfl#985]
I've recently noticed an issue with OpenFL HTML5 TextFields where if you carry out the following steps:
* Select the TextField so it has focus.
* Type something on the keyboard to make sure you have focus.
* Then click somewhere other than the TextField so it loses focus.
* After focus is lost, press a key on the keyboard.

The issue is that the key that you press still appears in the TextField, however the KeyboardEvent.KEY_DOWN and KeyboardEvent.KEY_UP events are not fired.

I would expect either once the TextField loses focus new characters don't appear, or at very least the events are still fired. 

This issue can be viewed here:
http://peteshand.net/robotlegs/todo/html5/

I've testing in Chrome 47.0.2526.106

I'll have a dig into this and see if i can identify anything obvious.

**Comment by jgranick** [comment]
This behavior should work like Flash right now, if it gains focus, and is removed from the stage, it still receives events. If it is not removed from the stage, but loses focus, it no longer receives events :smile:
