### ISSUE TITLE
Version Information meta tag for Windows build

### ISSUE THREAD

**Issue by alexandervrs** [openfl/openfl#994]
Application executables on Windows supports additional metadata called *Version Information*. The info is available in detail to the user by right clicking and choosing Properties > Details, it also shows the info under the .exe name in the Explorer and Taskbar entry and used for some System dialogs.

I can't seem to find a way to add this via the project.xml so I am requesting it.
It could be an entry like,

	<meta if="windows" 
		version="1.0.0.0" 
		product="My AppName"
		description="My Application" 
		company="My Company"
		copyright="2016 Author Name" 
	/>

**Comment by ibilon** [comment]
The project.xml file is dealt with by the lime tools,
if you could reopen this issue over there https://github.com/openfl/lime/issues.
