### ISSUE TITLE
ByteArray.hx:118: characters 9-59 : openfl.utils.ByteArrayData should be openfl.utils.ByteArray

### ISSUE THREAD

**Issue by pqyptixa** [openfl/openfl#995]
I get

    /usr/lib/haxe/lib/openfl/3,5,3/openfl/utils/ByteArray.hx:118: characters 9-59 : openfl.utils.ByteArrayData should be openfl.utils.ByteArray

When trying to compile an android app that uses stablexui. The relevant code is:

```
 111         @:from @:noCompletion public static function fromBytesData (bytesData:BytesData):ByteArray {
 112 
 113                 #if display
 114                 return null;
 115                 #elseif flash
 116                 return bytesData;
 117                 #else
 118                 return ByteArrayData.fromBytes (Bytes.ofData (bytesData));
 119                 #end
 120 
 121         }
```

Once that code is edited (ByteArrayData -> ByteArray), I get:

    /usr/lib/haxe/lib/openfl/3,5,3/openfl/utils/ByteArray.hx:92: characters 6-12 : Class<Std> has no field is

Code is:

```
  84         @:from @:noCompletion public static function fromBytes (bytes:Bytes):ByteArray {
  85 
  86                 #if display
  87 
  88                 return null;
  89 
  90                 #else
  91 
  92                 if (Std.is (bytes, ByteArrayData)) {
  93 
  94                         return cast bytes;
  95 
  96                 } else {
```

**Comment by petamoriken** [comment]
I got the same Error, however I updated Haxe to v3.2.1 and got success!

**Comment by pqyptixa** [comment]
Guess I'll just close this report, then... thanks @petamoriken!

**Comment by shadowofsoul** [comment]
i'm facing this same problem, but with hxcpp 3.2.205. here is my haxelib list:

`actuate: [1.8.2]
akifox-transform: [2.2.0]
devicelanguage: [1.0.0]
foo3d: git [dev:C:\Users\shadowv\foo3d]
gamecenter: 1.0.1 [1.1.1]
golems: [1.2.2]
haxe-gif: [0.3.3]
haxelib_client: 3.1.0-rc.4 [3.2.0-rc.3]
hxcpp: 3.1.37 3.1.39 3.1.48 3.1.68 3.2.102 3.2.193 [3.2.205] 3.2.81
iap: 1.0.4 [1.0.6]
lime-tools: 1.4.0 1.5.6 [1.5.7]
lime: 0.9.7 1.0.0 1.0.1 2.0.1 2.0.3 2.1.0 2.1.1 2.1.3 2.3.1 2.3.3 2.4.1 2.4.4 2.7.0 2.8.2 [2.9.0]
nme-dev: 
nme: 
openfl-admob: 1.2.1 [1.3.2]
openfl-bitfive: 2.0.0 [2.1.6]
openfl-gpg: 1.0.0 [1.1.0]
openfl-gps-lib: 1.0.1 [1.0.2]
openfl-html5: [1.4.2-beta]
openfl-native: [1.4.0]
openfl-samples: 1.3.0 [3.1.0]
openfl-share: [1.1.0]
openfl-unityads: 1.0.1 1.0.3 1.0.4 1.0.5 [1.0.6]
openfl-webview: [1.0.0]
openfl: 1.4.0 2.0.0 2.0.1 2.1.7 2.1.8 2.2.5 2.2.6 2.2.8 3.0.1 3.0.3 3.0.6 3.1.0 3.4.0 3.5.3 [3.6.0]`

i'm doing something wrong?

**Comment by jeichelbaum** [comment]
getting the same error, updating all my libraries at the moment
