### ISSUE TITLE
Sound.hx:118: Error: Could not load "assets/music/mysound.ogg"

### ISSUE THREAD

**Issue by pizzamakesgames** [openfl/openfl#998]
**Disclaimer:** This issue persists with HaxeFlixel projects. It was suggested that the cause may lie within OpenFL.

**The Problem:** Every odd start of the game, it doesn't have any sound. This has been happening across projects.

I've prepared a completely clean template project, with the Main.hx looking like this:
```
package;

import flixel.FlxGame;
import openfl.display.Sprite;

class Main extends Sprite
{
	
	public function new()
	{
		super();
		addChild(new FlxGame(256, 192, TitleScreen, 1, 60, 60, true));
	}
}
```
And the TitleScreen.hx looking like this:
```
package;

import flixel.FlxG;
import flixel.FlxState;

class TitleScreen extends FlxState
{
	override public function create():Void
	{
		#if flash
		FlxG.sound.playMusic("assets/music/mysound.mp3");
		#else
		FlxG.sound.playMusic("assets/music/mysound.ogg");
		#end
		
		super.create();
	}

	override public function update(elapsed:Float):Void
	{
		super.update(elapsed);
	}
}
```

The Project.xml is unchanged and the only two assets are the two mp3/ogg files.

While the windows target runs the game without sound, the neko target crashes whenever the issue occurs, tracing this:
```
Build succeeded
Done(0)
haxelib run lime run "Project.xml" neko -debug
Running process: D:\Pizza\Development\HaxeToolkit\haxe\haxelib.exe run lime run "Project.xml" neko -debug
Sound.hx:118: Error: Could not load "assets/music/mysound.ogg"
AL lib: (EE) MMDevApiOpenPlayback: Device init failed: 0x80004005
Invalid operation (/)
Called from flixel.system.FlxSound::update line 241
Called from flixel.system.frontEnds.SoundFrontEnd::update line 273
Called from flixel.FlxGame::update line 696
Called from flixel.FlxGame::step line 648
Called from flixel.FlxGame::onEnterFrame line 493
Called from openfl._legacy.events.EventDispatcher::dispatchEvent line 98
Called from openfl._legacy.display.DisplayObject::__dispatchEvent line 182
Called from openfl._legacy.display.DisplayObject::__broadcast line 161
Called from openfl._legacy.display.DisplayObjectContainer::__broadcast line 280
Called from openfl._legacy.display.Stage::__render line 1103
Called from openfl._legacy.display.Stage::__checkRender line 351
Called from openfl._legacy.display.Stage::__pollTimers line 1084
Called from openfl._legacy.display.Stage::__doProcessStageEvent line 430
Done(1)
```
**Clues:**
The problem does occur on the windows target, resulting in no sound.
The problem does occur on the neko target, resulting in a crash.
The problem does not occur on the flash target.
The problem does not occur when running the game in fullscreen mode (with FlxG.fullscreen = true;).
The problem does not occur when disabling windows visual designs (aero).

.zip of the project:
https://www.dropbox.com/s/o7f45gx3ljs2o8q/Soundhx118Error_project.rar
.zip of the windows cpp bin directory:
https://www.dropbox.com/s/xcvg4xdxkv1wtac/Soundhx118Error_bin_windows.zip

Thank you very much in advance.

**Comment by grapefrukt** [comment]
I had (and still have with other projects) this issue when doing final testing on rymdkapsel for the PC release. What I found with some help from the OpenAL irc, was that OpenAL requires a window handle to "init a device" which in turn is used to play sounds.
If the window is transitioning from or to fullscreen, this handle is lost briefly. If you try to play (or load iirc) a sound at that very moment it will fail. Once it's failed OpenFL (or, presumably Lime) makes no further attempts at starting it again, meaning that your game will stay silent. 
A workaround for me ended up being always starting in windowed mode, load any sounds I need and then after a brief delay (a couple of 100 ms) go into fullscreen.

**Comment by grapefrukt** [comment]
I just went back and checked the source code, the very first thing I upon startup is this:

    // tries to load a sound just to initialize the sound backend
    var s = new Sound();
    s.load(new URLRequest("this_should_fail"));

That got the sound backend initalized and ready for whatever despite that particular sound failing to load. With the backend initialized, I could freely transition to fullscreen whenever it fit. Granted, this was two years ago soon, so it is very possible the backing code is different now.
